### ISSUE TITLE
X symmetry causes polygons to merge at object center

### ISSUE THREAD

**Issue by ArMAx141** [CGCookie/retopoflow#1000]
[test.zip](https://github.com/CGCookie/retopoflow/files/6546382/test.zip)

Retopoflow Version: {3.1.0}

Blender Version/Hash: {2.93 Beta}

Platform Version/Distribution: {Windows}

**Issue:**

Whe x symmetry is enabled all polygons that a created get crushed at the center of the object.

![image](https://user-images.githubusercontent.com/68440030/119653551-52878500-bddc-11eb-90c3-feaacb3bfcd7.png)

**Comment by vxlcoder** [comment]
thanks for the report!

I haven't tested your file yet, but I think you might be working on the mirrored side of the object. does RetopoFlow act in the same incorrect way if you work on the other side of the red symmetry line?

**Comment by ArMAx141** [comment]
thanks for your response, strangely the issue no longer persists, i booted
up blender the next day and retopoflow worked fine.
will let you know if any problems arise in the future.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by vxlcoder** [comment]
ok.  will close this issue for now, but feel free to reopen and include more details if it happens again.

thanks!
