### ISSUE TITLE
Warning: Could Not Save

### ISSUE THREAD

**Issue by Rawrcakes** [CGCookie/retopoflow#1002]
QUESTION

Retopoflow Version: 3.1.0
Blender Version/Hash: 2.90
Platform Version/Distribution: Windows 10

I apparently don't have permission to write to my own drive? I've never had permission errors before installing. Now I'm scared to close out because I'm worried I'll loose my progress. Is there a way to clear this up?

![image](https://user-images.githubusercontent.com/78630303/120079645-ba063480-c069-11eb-83d5-9b5eb2112894.png)

**Comment by vxlcoder** [comment]
thanks for the report!

did you save your blend file or open a previous blend file before starting RetopoFlow?

RF should save the backups to the same location of the original blend file (similar to how blender handles autosave files).

also, I noticed that the filename includes an @ sign. is that supposed to be there? that _might_ be the cause of the issue.

**Comment by vxlcoder** [comment]
hi, @Rawrcakes!

do you have any updates on this issue?  were you able to save your work?

**Comment by Rawrcakes** [comment]
Hello,

Sorry for late reply. I still don't really know exactly what was causing the issue, but it does look like having an @ in the filename or working off the autosave might have been the culprit. I was able to get around this by exiting out of Retopoflow, saving-as the blend file with a normal name, and re-entering Retopoflow.

It was my first time using Retopoflow, so I was a little scared exiting out of Retopoflow would close my Blender completely out. Haha. But yeah, better now. Thank you for a great tool!

**Comment by vxlcoder** [comment]
glad to hear!

be sure to let us know if you run into other problems!

happy retopo'ing :)
