### ISSUE TITLE
Retopoflow won't recognise the active target mesh

### ISSUE THREAD

**Issue by leokisomma** [CGCookie/retopoflow#1003]
Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

None of the retopoflow brushes, features, or indeed any form of mesh creation are working after I click the function saying "New Target at active"

The resulting mesh is either completely devoid of verticies or edges or faces or all 3, but absolutely nothing happens with any of the RF tools when I try to work with the mesh. I have checked and I made sure I installed the correct version of Retopoflow for blender 2.92

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
hi!

did you try using Ctrl+LMB? see help (F1) for more details.

**Comment by vxlcoder** [comment]
hi, @leokisomma.  glad that worked for you.

the high poly count warning will show if your source (high poly) or target (low poly) meshes are above a threshold.  RetopoFlow will work on high poly meshes, but the performance will degrade (RF will become slow).  This is an area that we are working on now.

Closing the original issue.  if you have any other problems, please open a new issue.

Thanks!
