### ISSUE TITLE
Contours: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Vlad-vak-blend** [CGCookie/retopoflow#1004]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.00.2
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1650 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-05-31 23:46:36.001222
- Undo: cut, change segment count, deselect all, cut, cut, cut, cut, deselect all, cut, cut

Error Hash: cb700bff12b9153e57ed6dc2a81263d5

Trace:

- EXCEPTION (<class 'TypeError'>): Vector.dot(other), invalid 'other' arg
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 000 0458:new_vert_point() if rfvert.normal.dot(self.Point_to_Direction(xyz)) > 0 and self.is_visible(rfvert.co, bbox_factor_override=0, dist_offset_override=0):
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_contours\contours_ops.py
- 001 0296:new_cut() verts += [self.rfcontext.new_vert_point(p)]
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 002 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_contours\contours.py
- 003 0613:new_line() self.new_cut(ray, plane, walk_to_plane=False, check_hit=xy01)
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rfwidget.py
- 004 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 005 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rfwidgets\rfwidget_linecut.py
- 006 0075:modal_line() self.callback_actions()
-     .../common\fsm.py
- 007 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
hi!

I noticed that your report states you are using an older version of RetopoFlow.

please try the latest version of RF, and let us know if you continue having issues.

thanks!

**Comment by vxlcoder** [comment]
looked more into this issue... although I haven't been able to reproduce it, this bug could still (potentially) exist in the latest version of RF.  commit 0cd9abb _should_ catch this.  closing for now, but please reopen if the problem persists.

Thanks!
