### ISSUE TITLE
[BUG] Viewport icons disappearing (Blender 2.93 / Retopoflow 3.1.0)

### ISSUE THREAD

**Issue by hced** [CGCookie/retopoflow#1006]
Retopoflow Version: 3.1.0

Blender Version/Hash: 2.93.0 LTS

Platform Version/Distribution: Windows 10 Pro 21H1 (19043.1023)

## Issue

**Viewport Header icons disappear when activating the add-on**

Affects following icons (the standard group in the upper right corner of Viewport):

- View Object Types
- Gizmo
- Overlays
- Toggle X-Ray
- Shading

![Retopoflow_3_1_0_Blender_2_93_Icons_Missing](https://user-images.githubusercontent.com/93350/121090423-e0a23900-c7e8-11eb-92d5-08125d5b5db0.png)

![no_icons_full_screenshot~](https://user-images.githubusercontent.com/93350/121091323-18f64700-c7ea-11eb-8961-e8e2c336ca3e.png)

## How to Reproduce

- Install Blender 2.93 LTS and choose to re-import* settings from previous Blender version (2.92).
- Toggle Retopoflow 3.1.0 add-on in Preferences.

*Not sure if the re-import of old config affect the outcome.

**Comment by vxlcoder** [comment]
@hced, I'm having trouble reproducing this bug with 3.1.1 (which is different from 3.1.0, but the difference should not cause it to start working...).

1. open fresh copy of Blender 2.92
2. install RetopoFlow 3.1.1
3. closed and reopened 2.92 just to make sure all is good
4. open fresh copy of Blender 2.93
5. load settings from 2.92
6. all works

if you're still having these issues, can you open the terminal (Blender > Window > Toggle System Console), copy everything that you see in the terminal, and paste it here?  I wonder if something is breaking during initialization (hopefully reported to terminal).

**Comment by hced** [comment]
@vxlcoder I'm so sorry for late reply. Now, after posting the issue I just decided to wipe my whole Blender (2.92) and re-install a fresh new Blender 2.93. After reading your reply, installed 3.2.0 just now and the issue is non-existing, so maybe we'll just call it a hickup. (Of course, if you wish to continue investigating whatever that was, I can still re-install 3.1.0 and have a look again. EDIT: Just did. Apparently 3.1.0 didn't cause the issue for me this time, so now I definitely suggest we close this and call it hickuppz.)

**Comment by vxlcoder** [comment]
thanks for checking back into this!  let us know if you have other problems. happy retopo'ing!

**Comment by aduffeck** [comment]
@vxlcoder I just hit the same problem. Looking at the console output I found this:

```
No module named 'numpy'
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/bpy_types.py", line 807, in draw_ls
    func(self, context)
  File "/usr/share/blender/scripts/startup/bl_ui/space_view3d.py", line 720, in draw
    VIEW3D_MT_editor_menus.draw_collapsible(context, layout)
  File "/home/andre/.config/blender/2.93/scripts/addons/RetopoFlow/__init__.py", line 626, in hijacked
    if context.mode in {'EDIT_MESH', 'OBJECT'} and retopoflow.RetopoFlow.get_sources(): # context.object and context.object.mode in {'EDIT', 'OBJECT'}:
AttributeError: module 'RetopoFlow.retopoflow' has no attribute 'RetopoFlow'
```

Everything works as expected after installing the numpy module and restarting blender.

**Comment by vxlcoder** [comment]
@aduffeck, that's interesting.

RetopoFlow does not actually use numpy, but it is imported in one file.

i'll remove that import, and thank you for the details and help with debugging!
