### ISSUE TITLE
Selecting handles, strips etc disabled 

### ISSUE THREAD

**Issue by pencilhead** [CGCookie/retopoflow#101]
Selecting strips, junctions, junction handles and patches are disabled with "left click select" enabled in blenders user preferences. With "right click select" enabled in blenders user preferences, selecting Strips etc. seems to work perfectly.

Orthographic and perspective give same results.  Disabling other custom add-ons has no effect.

Using Blender 2.73a official stable release. And retopoFlow_v1.0.0

**Comment by patmo141** [comment]
Thanks for the report pencil.  Can you verify that this is the case in Contours and Polystrips?

**Comment by patmo141** [comment]
Hi Pencilhead,  I am having no trouble with leftmouse select in either tool.  The one thing I do notice is that you can not "click and drag" like a tweak manipulation on the polystrips handles.  You you select, you have to use hotkey G or R to manipulate them. I am using 2.7.4 release candidate so I will test in 2.73

**Comment by pencilhead** [comment]
This only happens with polystrips with the left click select enabled. Right click works perfectly,  I can select,rotate move scale draw polystips as usual.

With the left click select enabled. It just continues to draw more polystips, as apposed to selecting the handles. The right mouse button seems to do nothing.

**Comment by patmo141** [comment]
.Hi Pencil,  I have tested in 2.73a and can not reproduce so let's try a few things.

1.  Try a different model, eg a simple cube or UV sphere, I wonder if there is something inherent in your model that is causing difficulty.  If this fixes it, please post a .blend so that we can diagnose what is causing the problem
2.  Try in orthogrpahic vs perspective mode.  We use raycasting for selection, and there were some raycasting bugs in blender that have recently been fixed.
3. I don't think this is the case because of how you describe right click working, but you aren't trying to "widget" the handles and nodes are you?  Eg, you can't click and drag on them, you have to use G and R to transform them.

We will get to the bottom of it.
Best,
Patrick

**Comment by pencilhead** [comment]
1. I've tried with different models and different scenes, Same results.
2. Ortho and persp give same results.
3. no i'm not trying to widget them. I don't even have the option to select them (highlighted green). Like i said, With right select enable in Blender User preferences--->Inputs. Every thing works perfectly i can draw polystrips, select handles, strips, patches etc.  as well as manipulate them.

With left select enable in Blender User preferences--->Inputs. I can draw polystrips with my Left mouse button. Right mouse button does nothing. there doesn't seem to be a way to select anything this way.

Also tried this with Blender 2.74 rc 2. Same results.  I'll do a screen recording when i get a chance, so you can see exactly what is going on.

**Comment by patmo141** [comment]
That is very weird, I apologize for having to ask those obvious questions.  I look forward to seeing your screencast.  Any console errors or printouts when you first call the operator?

**Comment by pencilhead** [comment]
*facepalm* It seems to be working now. user error.  Don't ask me what i was doing before. I have no idea. Thanks for your time Patrick

**Comment by shonkeee** [comment]
Hi, I am having the same problem, was on a Wacom, changed to mouse right click, can select handle which is green with white ring, have tried left select right select, and alt with both of those, nothing moves it. can use R, S and G but this is not good when l want to Ctl C to change from angle to curve. Im on Mac . any thoughts would be appreciated

**Comment by patmo141** [comment]
Just so I understand
1. you are using a Wacom tablet. 
2.  You can select the handles
3.  You can rotate/scale and grab with hot-keys

 You want to be able to move the poly-strips handles with your tablet without using a hot-key?

**Comment by shonkeee** [comment]
Thank you for quick reply!

Am usually on Wacom but changed prefs back to right select 3 button mouse
Yes can select handles
And can hot key R S G

1st image right button will not move it

Second image shows that left button move adds more poly strips, 

Is there a hot key l am missing?

**Comment by patmo141** [comment]
I think you are describing normal behavior.  I need to check with @carter2422 and @vxlcoder but to my knowledge, we have not built in support for "click and drag" behavior and you must your R, S, G.

**Comment by shonkeee** [comment]
Download full resolution images
Available until 17 Feb 2017
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAciUtxmjidA_GiG8fdt2NU24qSVBAY63W8o48IKYyEh29pPY5rjgjYu7%2F%24%7Bf%7D%3Fo%3DAmlRE6sI2mIJ8gzeVoOxTLsWyqrUa_ldEe8GxXD_6gPR%26v%3D1%26x%3D3%26a%3DBVMaMiZ0S7k3A-g4OQEA_wHIAP9xxCiB%26e%3D1487311198%26k%3D%24%7Buk%7D%26fl%3D%26r%3D4D6000BD-7078-4098-82EF-778A69D0027A-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DCB51B66D-0BFD-4AA6-8B3A-4A76C7ABDBE6%26p%3D34%26s%3DZ1utCI1I1vJYQ-xq9EWvaGgAO2w&uk=Acm6aw7TYwwznQG1cix6Og&f=Images.zip&sz=5497910>Hi, l have attached a few files
1. Part of a cookie tutorial that demonstrates what l feel l am missing Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAVZb0o7Lp1Wajd_I746K6gjDBoeFAeHvMZP9zi8hPDUPyS7pChsljLDa%2F%24%7Bf%7D%3Fo%3DAtAlMqgpQHy6B0UgaaTvQKKzNAMZKGS40NLfsKdLDfFC%26v%3D1%26x%3D3%26a%3DBQyE2HNBryXAA-g4OQEA_wHIAP8kPH6n%26e%3D1487311199%26k%3D%24%7Buk%7D%26fl%3D%26r%3D09BDED8E-49F0-4FC9-A6A9-4BF4CF8899C1-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DCB51B66D-0BFD-4AA6-8B3A-4A76C7ABDBE6%26p%3D34%26s%3D52sa8uyYa1486fXuqqVEu6b3HgU&uk=avjVXAkzezr0KFe78vgpDA&f=IMG_0136.MOV&sz=27735809>IMG_0136.MOV
27.7 MB
Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAV9hO40Py9P5kUj-ars51HODeDr8AdIZbs9mSWw7jIZvJ4Hza0i_c9xS%2F%24%7Bf%7D%3Fo%3DAg64-yT6zGPW6COdPXX7hoNCFmAh768fisFEjMpHkTUx%26v%3D1%26x%3D3%26a%3DBSeeO-h87vNwA-g4OQEA_wHIAP9H-y6c%26e%3D1487311199%26k%3D%24%7Buk%7D%26fl%3D%26r%3D6698A0FE-5FFE-4496-9EEB-A46F21576FF3-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DCB51B66D-0BFD-4AA6-8B3A-4A76C7ABDBE6%26p%3D34%26s%3DhAwHGeh_SiLkA01QTKxXq53qmMI&uk=Sl2ARii7-TZgD8GxF-wPaQ&f=IMG_0138.MOV&sz=45932771>IMG_0138.MOV
45.9 MB



Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAf7BGp-MAUlbLkAPAQn5c4XrIDtgAayk9yaJzjvda14T5C074mm-eQCv%2F%24%7Bf%7D%3Fo%3DAp1LroYQtxfWqwCygM9-AIoQd5lN3bw2rusND_h7XwSG%26v%3D1%26x%3D3%26a%3DBXHwVAoKM6_LA-g4OQEA_wHIAP8cjasf%26e%3D1487311198%26k%3D%24%7Buk%7D%26fl%3D%26r%3D5AF1EBE2-C404-4470-B28C-44BA200860CF-1%26ckc%3Dcom.apple.largeattachment%26ckz%3DCB51B66D-0BFD-4AA6-8B3A-4A76C7ABDBE6%26p%3D34%26s%3Di4qlB718IepH95VpmqkAPrk9wcU&uk=VeXWYH5QZdq0gn9PUzTCKA&f=IMG_0139.MOV&sz=18771776>IMG_0139.MOV
18.8 MB
and the others to show what is happening with me
