### ISSUE TITLE
[Proposal] Draw brush cursor on top of mesh

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1011]
Would it be possible/practical to draw the brush cursor last, on top of the mesh, so that it doesn't clip into the source or target? Here's a comparison with Blender's sculpt mode brush:

![Screenshot 2021-06-14 140804](https://user-images.githubusercontent.com/12982300/121964095-dbc91200-cd1f-11eb-8914-1a3030cfaa77.jpg)

![Screenshot 2021-06-14 140840](https://user-images.githubusercontent.com/12982300/121964087-d7045e00-cd1f-11eb-9c94-ef0cdf38483b.jpg)

I don't think it's worth a lot of effort, but would be nice if it's a quick fix.

**Comment by vxlcoder** [comment]
will work on this tomorrow!

**Comment by vxlcoder** [comment]
done!

![image](https://user-images.githubusercontent.com/3790699/122092389-dcbd7a80-cdd7-11eb-937b-45521f140c73.png)

**Comment by jlampel** [comment]
🥳🥳
