### ISSUE TITLE
Proposal: Relax _along_ boundary

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1012]
I think we should add another boundary option to allow boundary verts to be relaxed, but only along the boundary line (similar to relaxing verts along symmetry line).

**Comment by vxlcoder** [comment]
this does get tricky, as the boundary line will change as vert moves.  maybe the boundary line is set when relaxing starts (and all verts along that line "stick" to that boundary)?

**Comment by vxlcoder** [comment]
this would help relax the boundary when we have something like this

![image](https://user-images.githubusercontent.com/3790699/122119400-236e9d00-cdf7-11eb-9c0a-a112cde477cf.png)

**Comment by vxlcoder** [comment]
i like this idea.... will see how quickly i can implement it tomorrow!

**Comment by jlampel** [comment]
This works great and is a very helpful option to have! Nice idea!
