### ISSUE TITLE
**[BUG]** Symmetry threshold value cant be entered lower then 0.01

### ISSUE THREAD

**Issue by pekloklad** [CGCookie/retopoflow#1013]
Retopoflow Version: 3.1.0

Blender Version/Hash: 2.93

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**

Entered value of symmetry threshold lower then 0.01 is rounded down to 0. Default value is 0.001 so I think it should be possible. Its annoying, because when symmetry is turned on, my relax brush is merging distant vertices with current lowest possible value 0.01. 

Default value
<img width="638" alt="Threshold_01" src="https://user-images.githubusercontent.com/86007151/122242172-66964200-cec3-11eb-873e-c6114cf3a11f.png">

Enter 0.005
<img width="638" alt="Threshold_02" src="https://user-images.githubusercontent.com/86007151/122242287-7d3c9900-cec3-11eb-95a4-4e86fef85193.png">

Value is 0
<img width="645" alt="Threshold_03" src="https://user-images.githubusercontent.com/86007151/122242437-9ba29480-cec3-11eb-8240-cdef53b63736.png">

I also have an issue with disappearing Options and Poly Count menu after I minimize them.

Before
<img width="488" alt="Minimize_dialog_02" src="https://user-images.githubusercontent.com/86007151/122242947-048a0c80-cec4-11eb-8f8d-ca7dcf2afdac.png">

After
<img width="443" alt="Minimize_dialog_03" src="https://user-images.githubusercontent.com/86007151/122243035-14095580-cec4-11eb-9b47-4f82f2017923.png">

Same happens with Options. They just disappear and I am not able to get them back.

&nbsp;

**How to Reproduce:**

Enter value lower then 0.01. Minimize Options or Poly count menu.

**Comment by vxlcoder** [comment]
thanks for the report, @pekloklad!

commit 2607468 reduced the step size to 0.001 for merge threshold.

as for options and geometry count window, you can restore these windows by clicking the `Show Options` or `Show Poly Count` buttons under `Windows` dropdown in main RF menu.

![image](https://user-images.githubusercontent.com/3790699/122248857-62076480-ce96-11eb-9885-183f4f82fdf2.png)

will update the tooltip/icon to better reflect that the windows are closed, not minimized.

**Comment by jlampel** [comment]
Confirmed fixed 👍
