### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by hdharris** [CGCookie/retopoflow#1014]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- Blender: 2.93.0 master 2021-06-02
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2080 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 466.63, 4.50 NVIDIA
- Timestamp: 2021-06-16 12:50:52.752612
- Undo: extrude strip, smart select, relax, relax, relax, relax, relax, relax, relax, relax

Error Hash: 3782d73b634e1c4590b87b37936d5127

Trace:

- EXCEPTION (<class 'AttributeError'>): 'tuple' object has no attribute 'reverse'
-     C:\Users\hassa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 000 0826:extrude_strip() if side_verts[1] == verts[0]: side_verts.reverse()
-     C:\Users\hassa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\hassa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 002 0371:stroke() if self.replay: self.replay()
-     C:\Users\hassa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\hassa\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0087:modal_line() self.callback_actions()
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @hdharris!

this appears to be the same issue as #958, which _should_ be fixed in the soon-to-be-released version of RetopoFlow.  you can test out the patch now by using RetopoFlow Updater to check out branch `v3.1.1` (see [link](https://docs.retopoflow.com/addon_updater.html) for more details), or waiting for the official release (which will be very soon!)

will close this issue for now.  if you continue to have problems, feel free to post updates to this issue or to issue #958.  thanks!
