### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by mackotomi** [CGCookie/retopoflow#1018]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.0
- Blender: 2.93.0 master 2021-06-02
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2, 4.5.0 NVIDIA 465.89, 4.50 NVIDIA
- Timestamp: 2021-06-23 15:31:08.336497
- Undo: extrude strip, create strip

Error Hash: 8a2dd7ee641642e7b159e78acc4a309d

Trace:

- EXCEPTION (<class 'OverflowError'>): cannot convert float infinity to integer
-     C:\Users\knowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 000 0827:extrude_strip() self.strip_crosses = max(math.ceil(avg_dist / (2 * self.rfwidgets['brush'].radius)), 2)
-     C:\Users\knowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\knowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 002 0382:stroke() if self.replay: self.replay()
-     C:\Users\knowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\knowl\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0088:modal_line() self.callback_actions()
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @mackotomi!

can you provide the steps you took that caused this issue? or, can you post a screenshot?

will take a look at this, but either of the above would be very helpful.

thanks!

**Comment by vxlcoder** [comment]
note: i was able to reproduce this by stroking completely on the mirrored side.

**Comment by vxlcoder** [comment]
this issue is possibly fixed in commit 31c1fe0.  you can use the addon updater ([link](https://docs.retopoflow.com/addon_updater.html)) to try out the fix (enter either commit `31c1fe0` or branch `v3.2.1`).  please let us know if you're still able to reproduce this error.

thanks!

**Comment by mackotomi** [comment]
Wat, i didnt expect a reply like this.. this is epic! Ehm, i cant probably
:/ its first time today that i used your retopo addon guys, so i was trying
tons of things which i maybe wasnt intend for, but.. ill try to look into
my head and think when was that thing happen and what i did, if ill
remember ill let you know. Either way, ill keep reporting from now
definitely if something bugs out.

Thanks Folks, btw the retopo is AMAZING, except some things here and
there...

st 23. 6. 2021 o 18:25 Jon Denning ***@***.***> napísal(a):

**Comment by vxlcoder** [comment]
ok. thanks for the update!

please let us know if you run into other issues or if there's anything we can do.

happy retopo'ing!
