### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by szpadeldowegla** [CGCookie/retopoflow#1021]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- CG Cookie built
- Blender: 2.92.0 master 2021-02-24
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2070 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-06-28 18:37:31.620470
- Undo: extrude strip, select smart, select, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move

Error Hash: 3782d73b634e1c4590b87b37936d5127

Trace:

- EXCEPTION (<class 'AttributeError'>): 'tuple' object has no attribute 'reverse'
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 000 0826:extrude_strip() if side_verts[1] == verts[0]: side_verts.reverse()
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0371:stroke() if self.replay: self.replay()
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0087:modal_line() self.callback_actions()
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @szpadeldowegla.

This issue is already fixed in the latest version of RetopoFlow (version 3.2.0).

You can get the latest version by going to your Blender Market Orders page, or you can use the built-in updater system (see [link](https://docs.retopoflow.com/addon_updater.html)).

Let us know if you have any other issues.  Closing this issue for now.

Happy Retopo'ing!
