### ISSUE TITLE
[BUG] Contours Tool not working after Alt Tab

### ISSUE THREAD

**Issue by thegrasstrainer** [CGCookie/retopoflow#1022]
Retopoflow Version: 3.2.0

Blender Version/Hash: 2.93.0

Platform Version/Distribution: Windows 10

**Issue:**

While in Retopoflow the Contours Tool no longer responds if I Alt+Tab to another window and then back. I have to exit back to Blender's Edit Mode, and then re-enter Retopoflow to get the Contours Tool working again. This happens on every mesh I've used Retopoflow 3.2.0 on so far.

**How to Reproduce:**

Add an mesh to scene, make active Retopoflow target, Use the contours tool around a cylindrical shape, Alt+Tab to another window, and go back to Retopoflow and try to use the Contour Tool again.

**Comment by vxlcoder** [comment]
thanks for the report, @thegrasstrainer.

will take a look today

**Comment by vxlcoder** [comment]
Can you test something for me, @thegrasstrainer?

I was able to reproduce your issue, but I was able to workaround without exiting RF.  after you alt+tab back into Blender (with RF running), tapping the alt key again _should_ allow Contours to work again.  can you see if that indeed works around the issue for you?

looking into a non-workaround solution now.

**Comment by thegrasstrainer** [comment]
> 
> 
> Can you test something for me, @thegrasstrainer?
> 
> I was able to reproduce your issue, but I was able to workaround without exiting RF. after you alt+tab back into Blender (with RF running), tapping the alt key again _should_ allow Contours to work again. can you see if that indeed works around the issue for you?
> 
> looking into a non-workaround solution now.

Oh wow, yeah that does work. Surprised I didn't figure that out by accident, but glad this is a solution! Thank you so much!

**Comment by vxlcoder** [comment]
commit 01f9a48 _should_ fix this issue.  you can test it out by using the updater system ([link](https://docs.retopoflow.com/addon_updater.html)) to check out branch `v3.2.1` or commit `01f9a48`.  otherwise, use the workaround until the next official version is released.

thanks for the report, and happy retopo'ing!
