### ISSUE TITLE
[PROPOSAL] Add function for increasing or decreasing brush size incrementally 

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1023]
It looks like we only have a function for changing the brush size based on the mouse position, but we should also have a way to increase or decrease the size incrementally. The hotkeys '[' and ']' are often used for this in other apps, so it would make sense for that to be the default here since they're not used. Another reason to make this change is that 'F' is used for focusing on the selection in the industry compatible keymap so those users don't have a good way to change the brush size.

**Comment by vxlcoder** [comment]
sounds fine to me.  how much to increment by?  ex: 10 pixels

note: artist can change brush size change action from `f` to something else using keymap editor.

another note: although not convenient, the artist should be able to change brush size in options, too.

**Comment by jlampel** [comment]
Awesome, thank you! 10 pixels sounds perfect.

**Comment by vxlcoder** [comment]
@jlampel, would `]` increase and `[` decrease?

**Comment by jlampel** [comment]
@vxlcoder Yep!

**Comment by jlampel** [comment]
Works perfectly 🥳
