### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by szpadeldowegla** [CGCookie/retopoflow#1024]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.0
- CG Cookie built
- Blender: 2.92.0 master 2021-02-24
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2070 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-07-08 19:36:38.012551
- Undo: insert, insert, insert, insert, insert, select, insert, insert, select, insert

Error Hash: ccd86f3e6e5e4b76b4b9f93201fc039c

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0158:co() return self.l2w_point(self.bmelem.co)
-     C:\Users\szpad\AppData\Roaming\Blender Foundation\Blender\2.92\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 001 0658:draw_postpixel() knife_start = self.knife_start or self.rfcontext.Point_to_Point2D(next(iter(self.sel_verts)).co)
-     .../common\fsm.py
- 002 0090:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @szpadeldowegla.

will take a look!

**Comment by vxlcoder** [comment]
@szpadeldowegla, do you happen to recall what steps you took to get this error?  i see where it is happening, but i cannot reproduce the error to determine a correct fix.
