### ISSUE TITLE
Loops: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Junaweng** [CGCookie/retopoflow#1031]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.0
- CG Cookie built
- Blender: 2.93.1 master 2021-06-22
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1060 3GB/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-07-22 11:37:13.576823
- Undo: tweak move, tweak move, tweak move, grab contours, smart select, smart deselect

Error Hash: 0f7cad0a6bca8ff67061bf9f87b5504e

Trace:

- EXCEPTION (<class 'AssertionError'>): Unexpected topology
-     C:\Users\wengw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py
- 000 1186:_crawl_quadstrip_to_loopend() assert False, "Unexpected topology"
- 001 1190:is_quadstrip_looped() _,_,_,looped = self._crawl_quadstrip_to_loopend(edge)
- 002 1214:get_face_loop() is_looped = self.is_quadstrip_looped(edge)
-     C:\Users\wengw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 003 0680:get_face_loop() return self.rftarget.get_face_loop(edge)
-     C:\Users\wengw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_loops\loops.py
- 004 0333:set_next_state() self.edges,self.edge_loop = self.rfcontext.get_face_loop(self.nearest_edge)
- 005 0318:update_next_state_mouse() self.set_next_state()
-     .../common\fsm.py
- 006 0090:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Junaweng.

are you able to provide the .blend file you used when you ran into this issue?  you can email it to retopoflow@cgcookie.com.

or, if you can provide steps and screenshot you did to create this issue, that might work too.

thanks!

**Comment by vxlcoder** [comment]
commit 8c4271d does "fix" this issue.

note: this topology is not ideal, as one of the edges is non-manifold (has 3 faces).  RetopoFlow indicates this by highlighting the edge in red.  but because that edge isn't a manifold edge, loops across that edge are undefined, so RF might suggest a "loop" that you are not expecting.  but, now at least RF won't crash in this situation.  we could have RF try to find the "best" loop, but this could become computationally expensive very quickly.  really, this is a topology issue, not a coding issue.

thanks for the report!

**Comment by jlampel** [comment]
Yeah, I don't think we need to support topology that doesn't make sense - just as long as it doesn't error out or crash. 

I do still get this issue though when hovering closer to the connecting edge:
![image](https://user-images.githubusercontent.com/12982300/127042948-820acd2b-878f-4678-b765-a6a2881c1678.png)

**Comment by vxlcoder** [comment]
by "this issue", do you mean that the preview shows a vertical line rather than a horizontal line?

**Comment by jlampel** [comment]
Oh no, sorry I mean it crashes when I hold ctrl and mouse over that area

**Comment by vxlcoder** [comment]
can you share the .blend file?

**Comment by jlampel** [comment]
Sure: https://pasteall.org/blend/609fe07cb16c4cc296dc7c1fcb2396d1
Try to slide the loop all the way to the intersection:
![CN6U8tZS7m](https://user-images.githubusercontent.com/12982300/127062630-56f5bdd5-00e1-4500-ac5a-cb1a0f0c5267.gif)

**Comment by vxlcoder** [comment]
ah! blender locks up?  (no crash with crash report or anything, correct?)

**Comment by jlampel** [comment]
Ah yes, no actual crash

**Comment by vxlcoder** [comment]
there you go, @jlampel

**Comment by jlampel** [comment]
Awesome, this works great!
