### ISSUE TITLE
[PROPOSAL] Add mark seam functionality with same relax control as boundary verts.

### ISSUE THREAD

**Issue by Sinhouse85** [CGCookie/retopoflow#1034]
[PROPOSAL]

Retopoflow Version: {3.20}

Blender Version/Hash: {2.93}

Platform Version/Distribution: {Windows}

It would be great to be able to mark seams within the retopoflow tool so that you can better visualize and control intended UV seam placement when retopologizing.

When retoping clothing, matching seam placement to actual clothing seams on either scan or sculpt meshes is essential for a proper texturing workflow.
If you could mark seams to be highlighted for easier placement visualization and also be able to set seams to either be locked or slide only while using the relax tool this would seriously help in maintaining correct seam placement.

As it stands its quite easy to loose where the underlying seams should be and relaxing the mesh will drift your intended seam edges across the mesh.

![Seams](https://user-images.githubusercontent.com/41335511/127634169-79271443-ea9a-41b1-8b2c-a4c552c30272.jpg)

**Comment by vxlcoder** [comment]
This is an interesting idea @Sinhouse85.  thanks for the proposal!

all of the various parts to make this work is already written.  the only real issue I can think of regarding this proposal is that many of the tools do not work with seams (or any sort of tagging) in mind.  this means that the seams could be destroyed while editing (some tools simply delete and regenerate geometry).  i don't believe it would be too difficult to update most of these destructive operators, but finding them might be a little tricky.  also, some of RF's operators use Bmesh operators, so we would have to make sure that the used bmesh ops don't destroy the data, too.

there have been proposals for coloring faces which could benefit from combing the code for destructive/regenerative operators and replacing them with modifying operators.

we'll have to think some on this.

**Comment by vxlcoder** [comment]
I have made a few improvements that _should_ solve this issue, @Sinhouse85.

You can use the Pinning / Seams option menu to mark, clear, and pin seams.  You can also simply pin the geometry (stored as custom property in the mesh).  Pinned vertices will not move (using any of the tools, not just relax).

<img width="645" alt="Screen Shot 2022-01-06 at 4 55 36 PM" src="https://user-images.githubusercontent.com/3790699/148464075-27a6e289-44f9-4d84-b874-e029e7321817.png">

thanks for the feature suggestion!
