### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by PhillEvansIllustration** [CGCookie/retopoflow#1037]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.0
- Blender: 2.93.1 master 2021-06-22
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 471.41, 4.50 NVIDIA
- Timestamp: 2021-08-03 08:09:06.113946
- Undo: extrude strip, select smart, select, relax, relax, relax, relax, relax, move grabbed, select

Error Hash: 79ec846576806c3014978cf5c6538cce

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0332:shared_vert() verts = [v for v in self.bmelem.verts if v in bme.verts]
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes_utils.py
- 001 0134:get_strip_verts() vs.append(e0.shared_vert(e1))
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 002 0862:extrude_strip() side_verts = get_strip_verts(edges1)
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 003 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 004 0382:stroke() if self.replay: self.replay()
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidget.py
- 005 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 006 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\phill\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 007 0088:modal_line() self.callback_actions()
-     .../common\fsm.py
- 008 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @PhillEvansIllustration.

This issue _should_ be fixed in the latest version `v3.2.1`.

We recommend uninstalling the current RetopoFlow, restarting Blender, then install the latest version.

Please let us know if that does not resolve the problem or if you run into any other issues.

Happy Retopo'ing!
