### ISSUE TITLE
Brush Falloff Shortcut Doesn't Work in 3.2.1

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1039]
The hotkey Ctrl+F no longer works in 3.2.1 because the brush now disappears when holding Ctrl.

**Comment by vxlcoder** [comment]
fixed!

**Comment by jlampel** [comment]
I'm still seeing the same behavior - 3.2.2 branch, right?

**Comment by jlampel** [comment]
Confirmed fixed!
