### ISSUE TITLE
UI refuses to load in the 3.0 Daily Builds

### ISSUE THREAD

**Issue by blessedcoolant** [CGCookie/retopoflow#1043]
Just wanted to report the issue for when you want to fix the issue. They made a change to how the kerning status of fonts is handled in 3.0 recently. As a result, the UI fails to load when trying to initiate coz it no longer can find a KERNING attribute in blf.

I by passed this by hard coding a return True on the enable kerning function in common/fontmanager.py --- Rest of the app seems to be working fine but thought I'll let you know so you can fix this up for your next versions.

**Comment by vxlcoder** [comment]
thanks, @blessedcoolant!  I actually did something similar about a week ago in latest unreleased version, which should be released later this week.

**Comment by blessedcoolant** [comment]
Thanks. Will download the official one when you release it. :) Thanks again for the update.

**Comment by jlampel** [comment]
Closing this out since it's released. Let us know if that didn't do the trick!
