### ISSUE TITLE
PROPOSAL: Add Background Images to Retopoflow Mode

### ISSUE THREAD

**Issue by metathought** [CGCookie/retopoflow#1046]
This is a proposal to add an image into the background as concept art, and it can be controlled from the 'Viewport Display' options in the properties panel.  The properties of this feature would be an input to add an image to a list of images, and each image has a scale, and X,Y coordinates. You can import an image or multiple images, and delete them.
You could even possibly have a 'stack' of images, where they are drawn in order of the list of images, similar to how the Modifier Stack in Blender is important. In this case you could overlay a smaller image (lower in the stack?) over a larger image to save Viewport real estate.
This feature is similar to the old way Blender would add background images to the 3D Viewport.
 
![phywp](https://user-images.githubusercontent.com/10001781/136718664-3b079258-c265-45a1-9440-b2f49d9a6f5e.png)

Use cases for this feature would include having handy topology guides in your work area, or using reference images to create a unique part from a mesh that would benefit of having it's own topology.

**Comment by metathought** [comment]
> 
> 
> Interesting idea! I agree that looking at a topology guide can be very helpful, but I'm not sure it would be worth setting up a whole new system for adding, transforming, and controlling them from inside RF when things like [PureRef ](https://www.pureref.com/) can be used for overlaying reference onto any app.

The idea is to have the image inside of the editor, so you can maximize Blender and use one program. It can be handy to have it close to the model. The use case I encountered which led to this idea was I was trying to model this
![e34cd71c164112cd197076bedb52a4fe](https://user-images.githubusercontent.com/10001781/141040491-67fbf7fa-40c8-4140-89e8-8d79b57f5042.jpg)
I was trying to create two separate objects, the white cloth-y parts and the gold, metallic ornamental bits. Originally I had a base mesh that had the basic shape. Seeing the above image closer to the base mesh, would have helped with retopologizing the metallic part from the base.

I started thinking about other use cases and came up with having handy nearby retopo guides, and concept pieces in a convenient area nearby. I like Pure Ref personally, but I hate having to switch back and forth between two or more programs just to view an image. I find myself dragging an image into the 3d view or using Add Images as Planes while modeling, and this would be analog to that.

I hope I described that well enough. Thanks!

**Comment by jlampel** [comment]
I can definitely see how this could be useful in some situations. Thank you for the detailed explanation! Our current goal is to better integrate RetopoFlow into Blender, since recreating and redesigning all relevant features into RetopoFlow is just unsustainable. Closing this out for now, but things like this are definitely on my radar and a big reason we want to explore that direction.
