### ISSUE TITLE
Patches: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Node-Zero** [CGCookie/retopoflow#1050]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.3
- CG Cookie built
- Blender: 2.93.2 master 2021-08-03
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2, 4.5.0 NVIDIA 472.12, 4.50 NVIDIA
- Timestamp: 2021-10-20 20:37:39.378899
- Undo: select

Error Hash: 29c23b36600e53e8ea968620b487708f

Trace:

- EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute 'change_count'
-     C:\Program Files\Blender Foundation\Blender 2.93\2.93\scripts\modules\bpy_types.py
- 000 0728:__getattribute__() return super().__getattribute__(attr)
-     C:\Users\tijan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rf\rf_undo.py
- 001 0073:undo_push() self.change_count += 1
-     C:\Users\tijan\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_patches\patches.py
- 002 0206:main() self.rfcontext.undo_push('select')
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Sorry for the late reply on this, @Node-Zero!

This problem has been fixed in later versions of RetopoFlow.  Be sure to try out the latest version.

If you're using v3.2.5 or later (v3.2.6 is being released soon) and you still see this error, let us know.

Closing for now.
