### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by snotnose** [CGCookie/retopoflow#1053]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.4
- CG Cookie built
- Blender: 2.93.5 master 2021-10-05
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 2080/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-11-04 01:54:17.892159
- Undo: stroke, smart select, smart select, smart select, smart select, relax, relax, relax, relax, relax

Error Hash: ad5b76ef9b0e7de0739851a38c40076e

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'x'
-     .../common\maths.py
- 000 1053:w2l_point() v = self.imx_p @ Vector((p.x, p.y, p.z, 1.0))
-     .../common\decorators.py
- 001 0206:callit() ret = fn(*args, **kwargs)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py
- 002 0698:nearest() point_local = self.xform.w2l_point(point)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rf\rf_sources.py
- 003 0144:nearest_sources_Point() hp,hn,hi,hd = rfsource.nearest(point, max_dist=max_dist)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 004 0576:new_vert_point() xyz,norm,_,_ = self.nearest_sources_Point(xyz)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_polystrips\polystrips_ops.py
- 005 0093:create_edge() bmv1 = self.rfcontext.new_vert_point(p1)
- 006 0228:new_brushstroke() to_edge = create_edge(pt, tn, radius, pe)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 007 0148:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 008 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 009 0132:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\Tal\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 010 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 011 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report @snotnose!

I was unable to reproduce you bug, but I think commit 3dcf2ad will fix it.

please let us know if you run into this again.

happy retopo'ing!
