### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by UnrealVistas** [CGCookie/retopoflow#1054]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.4
- CG Cookie built
- Blender: 2.93.5 master 2021-10-05
- Platform: Windows, 10, 10.0.22000, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, 4.5.0 NVIDIA 496.49, 4.50 NVIDIA
- Timestamp: 2021-11-10 11:41:03.008717
- Undo: extrude strip, select, select, select, extrude strip, select, select, select smart, select, select smart

Error Hash: 79ec846576806c3014978cf5c6538cce

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0340:shared_vert() verts = [v for v in self.bmelem.verts if v in bme.verts]
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes_utils.py
- 001 0136:get_strip_verts() vs.append(e0.shared_vert(e1))
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0864:extrude_strip() side_verts = get_strip_verts(edges1)
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 003 0148:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 004 0380:stroke() if self.replay: self.replay()
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 005 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 006 0132:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\TheExcelExperts\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 007 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 008 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @MidnightPuppy!

I believe this is similar to issue #1045, which has possibly been fixed (not confirmed, because I was unable to reproduce).

If you get a chance, can you try out branch `v3.2.5` to test if it fixes this issue?  See [link](https://docs.retopoflow.com/addon_updater.html) for details on switching versions.
