### ISSUE TITLE
[QUESTION] Switch from BGL to GPU

### ISSUE THREAD

**Issue by infosisio** [CGCookie/retopoflow#1056]
With BGL getting deprecated, is a switch to the GPU module being planned?

**Comment by vxlcoder** [comment]
Yes, the plan is to eventually move fully away from BGL.

Note: BGL is still available in 3.1.0 alpha (as of today), so RetopoFlow works as-is across 2.83 (LTS)--3.1.0 (alpha).

Switching to GPU will break everything up to 2.93 (at least), as 2.8x does not have the GPU module.

We are keeping an eye on the progress as well as submitting patches to Blender to add functionality (ex: `gpu.shader`), and we will transition fully to the GPU module once it has all the features and is stable (likely around June 2022 when 2.83 LTS is dropped).

**Comment by vxlcoder** [comment]
closing this issue, but feel free to post follow-up questions.

Thanks again for reaching out!
