### ISSUE TITLE
**[BUG]** Current version is not compatible with Blender 3.0.

### ISSUE THREAD

**Issue by MSageVR** [CGCookie/retopoflow#1058]
Retopoflow Version: 3.2.4

Blender Version/Hash: 3.0 official

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

Sadly, RetopoFlow is 100% unusable right now in blender3.0. I'm sure it's an easy fix. But once you activate retopoFlow on a model, you are no longer able to click on anything other than the tools given by RetopoFlow. 

Like, you can click on strokes and patches and such. but you can't change your view in the viewport, none of the keys on my keyboard do anything, You can pan around your model. Then once you click Exit, you still can't move the viewport or press any keys. It's like it's locked or something even after exiting Retopoflow mode. 

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- Click "retopo ref from curser, or active"
- you then won't be able to move the viewport or click on anything.
- Click on "exit"
- you still won't be able to click or move the viewport at all.

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
@MSageVR, be sure to use v3.2.5, which we just released earlier this week. it works around a bug in blender.

let us know if you continue to have issues.

happy retopo'ing!

**Comment by Capngithub** [comment]
I also can’t click anything other than the toolbar of retookflow but even then the tools don’t do anything on my model. (Yes I’m on edit mode.) (blender 3.1)

**Comment by vxlcoder** [comment]
@Capngithub, are you using RetopoFlow v3.2.5?

**Comment by Capngithub** [comment]
> 

Yes I’m using 3.2.5 . I also installed blender 3 just to make sure and still I can’t use any of the tools and I also see the “setup issue” •no sources detected.

**Comment by vxlcoder** [comment]
@Capngithub, are you in edit mode on your high res model?

RF will treat the edited mesh as the target (low res retopo mesh) and any other meshes as sources (high res messy topo mesh). if in object mode, all meshes are considered source meshes (can only create new target).

if you believe you're trying to start RF correctly, can you either send us your .blend file (retopoflow@cgcookie.com) or try using the default scene to see if you can get it working?

RF v3.2.5 worked fine with Blender 3.0 rc and Blender 3.1 on Thursday (before their official release of 3.0).  I have not fully tested on the official 3.0, but that version should not have changed much.  however, I will run tests tomorrow

**Comment by vxlcoder** [comment]
@MSageVR, I just tried RF v3.2.5 on Blender 3.0 official releases on Linux, OSX, and Windows, and everything worked as expected.  So, be sure to upgrade to the latest version of RetopoFlow.  You can get a copy from the [Blender Market](https://blendermarket.com/products/retopoflow) or use the updater buttons in the Blender RetopoFlow menu ([docs](https://docs.retopoflow.com/addon_updater.html)).  NOTE: don't use the Updater System button, as that will run into the same Blender bug!

@Capngithub, I forgot to mention in my previous comment that the [Quick Start Guide](https://docs.retopoflow.com/quick_start.html) has details on how to start RetopoFlow.  Be sure to check that out.

Please let us know if you have any other questions.

**Comment by After-Skydark** [comment]
Can confirm, Blender 3.0, Retopoflow 3.2.5, Error on opening

Both are unhandled exceptions, reporting unhandled creates new unhandled.

both state error fixed, new version, new versions installed or updated, continues to throw exception.

Updater reports no newer version. 

Seems to throw exceptions on creating/setting up user interface.

**Comment by vxlcoder** [comment]
@After-Skydark, what operating system are you running blender on? can you start blender from the terminal or toggle system console if on windows, then start RetopoFlow and copy-paste everything that is written to terminal? I wonder if something else is causing the problem for you. thanks!

**Comment by vxlcoder** [comment]
thanks for the details, and I am glad to hear that you're up and running with RetopoFlow.

the updater pulls directly from our GitHub repo, so no endpoint setup needed. however, the updater might have failed while in the middle of updating, which could cause problems. I will dig into it a bit more.

**Comment by vxlcoder** [comment]
oh, i think i misread your last post @After-Skydark.

Are you back up and running?

If not, can you try this:

- start Blender
- Window > Toggle System Console, then switch back to Blender (but don't close the console)
- try starting RetopoFlow
- quit RetopoFlow
- copy all the text in the system console (might be several pages, so be sure to scroll) and paste that here.

If I didn't misread your final post and you are running with RF just fine, let me know and I'll close this issue.

**Comment by After-Skydark** [comment]
We’re up and running now, issue resolved. Thank you for the assistance
though.
