### ISSUE TITLE
When entering retopology mode, I can't use any tool (like polystrips) on the object I'm retopologizing.

### ISSUE THREAD

**Issue by MaddestOfLads** [CGCookie/retopoflow#1059]
**[BUG]**

Retopoflow Version: 3.2.5

Blender Version/Hash: 3.0

Platform Version/Distribution: not sure what this means

&nbsp;

**Issue:**

Every time I try to start retopologizing the model, I enter retopo mode, but when I hover my mouse over the high-res model, nothing happens at all. Tools like polystrips or contours - the ones that are supposed to create low-res mesh on the high-res model - just don't work. If I select something that I've already started retopologizing (as in, with actual mesh), I can modify this low-res mesh, but I can't create new mesh on the high-res model without "targeting" the low-res mesh (

![2021-12-07 21_47_12-](https://user-images.githubusercontent.com/95719167/145105045-0ec82f49-9cfe-4f78-8032-c9e30131bf3a.png)

^^ Hovering the cursor over the mesh doesn't show any indicator. Clicking and dragging has no effect.

![2021-12-07 21_56_57-Ustawienia](https://user-images.githubusercontent.com/95719167/145105048-b054b729-9150-4b83-9ba9-5e802fad6881.png)

^^ I can select the loops and move them around, or for example connect edges to each other, but I can't use any tool that adds mesh onto the target. It's as if retopoflow didn't recognize the high-res target as... the target.

&nbsp;

**How to Reproduce:**

- Select a high-res model (decimated so that it doesn't crash the pc)
-Enter retopology mode
-Try to use any tool that adds retopologized mesh onto the raw model

**Comment by vxlcoder** [comment]
Hi @MaddestOfLads!

RetopoFlow uses `Ctrl+LeftMouse` to create new geometry for most of the tools.

The [General Help Doc](https://docs.retopoflow.com/general.html) is a great place to start for general help across all if not most of the tools.  Then, read through the specific tool's help for additional info.

Please let us know if you have any other problems of if this info helped you get started.

Happy Retopo'ing!

**Comment by vxlcoder** [comment]
closing this issue for now.  Please feel free to update with further questions or info if the previous comment did not solve your issue.

thanks!
