### ISSUE TITLE
Pressing 'R' while no loops are selected causes a crash

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#106]
Reported [here](http://cgcookiemarkets.com/blender/forums/topic/problem-with-contours/#post-48284) and confirmed locally.
![screen shot 2015-03-30 at 3 52 41 pm](https://cloud.githubusercontent.com/assets/1648631/6906513/f8b7e15c-d6f4-11e4-80a1-8ba954c691ea.png)

**Comment by patmo141** [comment]
Seems to have been fixed in refactor.  Tested by adding 4 cuts, deleting a cut, then pressing 'R'
