### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by aopaul** [CGCookie/retopoflow#1061]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**
apologies. first time retopo user+github user. prob going to do this all wrong
crash

![RetopoFlow_screenshot](https://user-images.githubusercontent.com/95948342/145660361-9292ba5b-e91a-4026-92b1-80663dc35553.png)

**How to Reproduce:*
1. click on an edge 
2. select Strokes and ctrl+drag cursor

Result: Crash

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- CG Cookie built
- Blender: 3.00.0 master 2021-12-02
- Platform: Windows, 10, 10.0.19042, AMD64, Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3080/PCIe/SSE2, 4.5.0 NVIDIA 496.76, (no shader version)
- Timestamp: 2021-12-10 18:03:04.508799
- Undo: extrude L, smart select, smart select, select, move grabbed, smart select, tweak move, tweak move, tweak move, tweak move

Error Hash: 909926f9f15d51ff581cac2ca0da8fa2

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'is_valid'
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0226:shared_edge() if not self.is_valid or not other.is_valid: return False
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 001 0745:extrude_l() nedges.append(bmv0.shared_edge(bmv1))
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0149:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 003 0421:stroke() if self.replay: self.replay()
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 004 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 005 0132:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\aopau\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 006 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 007 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
this issue should now be fixed.  thanks!
