### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by drtyrell969** [CGCookie/retopoflow#1065]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.4
- CG Cookie built
- Blender: 3.01.0 master 2021-12-13
- Platform: Windows, 10, 10.0.22000, AMD64, Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2070 Super/PCIe/SSE2, 4.5.0 NVIDIA 497.09, 4.50 NVIDIA
- Timestamp: 2021-12-19 00:36:57.482019
- Undo: create cycle, stroke, stroke

Error Hash: 9a42177a85e4c84a725eab0bc42f53aa

Trace:

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh.py
- 000 1592:new_edge() bme = self.bme.edges.new(verts)
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 001 0598:new_edge() return self.rftarget.new_edge(verts)
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0404:<listcomp>() edges = [self.rfcontext.new_edge([v0, v1]) for (v0, v1) in iter_pairs(verts, wrap=True)]
- 003 0404:create_cycle() edges = [self.rfcontext.new_edge([v0, v1]) for (v0, v1) in iter_pairs(verts, wrap=True)]
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 004 0148:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 005 0380:stroke() if self.replay: self.replay()
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 006 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 007 0132:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\markl\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 008 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 009 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thank you for the report, @drtyrell969!

Although I was unable to reproduce this error, I believe it should now be fixed.
