### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by MontyMattness** [CGCookie/retopoflow#1066]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- Blender: 3.00.0 master 2021-12-02
- Platform: Windows, 10, 10.0.22000, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1650/PCIe/SSE2, 4.5.0 NVIDIA 457.63, (no shader version)
- Timestamp: 2021-12-29 20:09:19.775941
- Undo: insert, insert, select

Error Hash: 73441c5b93833c34c6745d09246a9dec

Trace:

- EXCEPTION (<class 'UnboundLocalError'>): local variable 'bmv3' referenced before assignment
-     C:\Users\Dylan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 000 0573:_insert() dprint('Could not insert: ' + str(bmv3.co))
-     C:\Users\Dylan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 001 0149:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Dylan\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 002 0314:insert() return self._insert()
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @MontyMattness!

commit 7e21fcf _should_ fix this bug, as there was a typo.

happy retopo'ing!
