### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by hogawish-hub** [CGCookie/retopoflow#1069]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- RF git: master 3d8b3a47d1d661f99ab0aeb21d31370bf15de35e
- Blender: 2.93.6 master 2021-11-16
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 3090/PCIe/SSE2, 4.5.0 NVIDIA 460.89, 4.50 NVIDIA
- Timestamp: 2022-01-03 19:38:32.283078
- Undo: extrude strip, select, extrude L, select, smart select, tweak move, relax, relax, relax, relax

Error Hash: 1833e431da647aab3f056720e5166707

Trace:

- EXCEPTION (<class 'TypeError'>): 'NoneType' object is not iterable
-     C:\Users\hogaw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py
- 000 0779:extrude_strip() edges1 = [e for e in edges1 if e.is_valid]
-     C:\Users\hogaw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow\retopoflow\rftool.py
- 001 0149:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\hogaw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py
- 002 0421:stroke() if self.replay: self.replay()
-     C:\Users\hogaw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0132:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\hogaw\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 006 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @hogawish-hub!

commit ea4e20f _should_ fix this exception.

Happy retopo'ing!
