### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by mifth** [CGCookie/retopoflow#107]
Hi.

I found some issues:
1) Strange Error message about middle of the cut.
2) cuts are sticked to my polygon in editmode
3) crash in solid shading mode.

I recorded all 3 issues here:
http://youtu.be/RmiiQEeTXbI

Here is the test model:
https://dl.dropboxusercontent.com/u/26887202/blender/fc_decor_129_easter_2.blend

Just open the file and go into editmode.

**Comment by carter2422** [comment]
Hey @mifth, so sorry for the late reply. 

With problem 1 you're running into issues because you have the plane verts selected. Thus it's trying to extend from that. This is also the cause of problem 2. 

For number 3, I'm not sure. I'll have to look into this. Can you consistently repo 3?

**Comment by mifth** [comment]
Hi.

Ok about 1 and 2.

About 3:
- select tree steam
- select a plane and go to edit mode
- enable contours and make a cut from left to right.

You will get such exception:
![cache0](https://cloud.githubusercontent.com/assets/2251298/7556021/c20a9dd6-f768-11e4-8ab9-32e8fe5a9f7e.png)

**Comment by carter2422** [comment]
Huh. I cannot reproduce that. 

Does this happen every single time? And can you repo it on another object?

**Comment by mifth** [comment]
I close the issue if nothing to do here.

**Comment by carter2422** [comment]
Thanks @mifth! 

We are doing a development sprint all this weekend to refactor a lot of the codebase. This should clear up a lot of these more annoying issues that're difficult to replicate.
