### ISSUE TITLE
Permission denied when saving RF options in Blender 3.0.0

### ISSUE THREAD

**Issue by hori345** [CGCookie/retopoflow#1070]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- CG Cookie built
- Blender: 3.00.0 master 2021-12-02
- Platform: Windows, 10, 10.0.19042, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 960/PCIe/SSE2, 4.5.0 NVIDIA 432.00, (no shader version)
- Timestamp: 2022-01-06 15:49:01.702984
- Undo: 

Error Hash: 84c176586fea22766f9a7a7fd833db6d

Trace:

- EXCEPTION (<class 'PermissionError'>): [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 3.0\\3.0\\scripts\\addons\\RetopoFlow\\RetopoFlow_options.json'
-     C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\RetopoFlow\config\options.py
- 000 0422:clean() json.dump(Options.db, open(Options.fndb, 'wt'), indent=2, sort_keys=True)
-     C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\addons\RetopoFlow\retopoflow\rf\rf_states.py
- 001 0053:update() options.clean()
-     .../cookiecutter\cookiecutter.py
- 002 0171:modal() try: self.update()
```

**Comment by hori345** [comment]
Hello!

 RetopoFlow crashes with Blender 3.0. 

 It does not depend on the grid and the working file.

 Do you need any more information from me to fix the bug?

 Regards Vlad

**Comment by hori345** [comment]
Hello!

Additional information.

There is no error in the Blender 3.0.1 build.

**Comment by vxlcoder** [comment]
Thanks for the report, @hori345!  Sorry for the delay response.

This is a strange bug, and I'm not sure how to fix it.  Did you need to give any permissions when installing RetopoFlow?  Did you install RetopoFlow in Blender 3.0, or did you let Blender copy it over from a previous version of Blender?

**Comment by vxlcoder** [comment]
(edited issue title to fit the issue better)

**Comment by hori345** [comment]
Hello!

You're absolutely right. If I install RP from another folder, the bug disappears. 

When installing RP, I copy the downloaded folder to the addons folder. Then I install it through the menu. No additional permissions are requested.

In any case, the bug disappeared. Thank you very much!

Sincerely, Vlad

**Comment by vxlcoder** [comment]
Glad to read that you found a solution, @hori345!

I've pushed some code that will handle this case better (nicely alerts artist that the file cannot be written).

happy retopo'ing!
