### ISSUE TITLE
**[BUG]** Hidden polygons dissapear after exiting RetopoFlow

### ISSUE THREAD

**Issue by Dorate** [CGCookie/retopoflow#1071]
Retopoflow Version: 3.2.1

Blender Version/Hash: 2.93.2

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

Somehow hidden parts of the mesh were irrevocably deleted after I've hidden them to work on the specific part of the mesh without lagging because of the big polygon count. "Reveal Hidden" and Alt+H didn't work and blender statistics showed less polycount than before. Unfortunately, I couldn't reproduce the problem, but I tried to remember all steps of the process I was making.

&nbsp;

**How to Reproduce:**

- Select polygons in edit mode
- Start Retopoflow pressing the diamond button
- Hit "Selected" in Target Visibility
- Edit mesh
- Ctrl+S
- Exit Retopoflow by "Exit" button
- Ctrl+S
- Start Retopoflow again

**Comment by vxlcoder** [comment]
Thanks for the report, @Dorate.  I'm sorry to hear that you've had issues here.

I was unable to replicate your issue, too.  A note: hidden geometry still exist, they just aren't rendered.  In fact, RetopoFlow uses the same attribute that Blender uses to hide geometry.  So, unless the "Edit mesh" step is something I haven't tested, I'm not sure what could have caused this issue.

Do you happen to know which tools you used after hiding the geometry?

Another note: you report that you're using RetopoFlow 3.2.1, which is an older version of RF.  There were a few bugs related to hidden geometry that were fixed recently (don't recall which version at the moment), so maybe this is related to an older issue that has been fixed... not sure.  But, you might consider upgrading to the latest version of RF (v3.2.5).

**Comment by Seonavdp** [comment]
I just wanted to add to this bug that I’ve experienced this issue tonight after retopologising a head in the latest version of retopoflow (downloaded yesterday) in blender 2.93. I finished the head and hid the geometry by selecting all and pressing hide selected, so I could work on the ears. Completed the ears topo, and went to the reveal hidden button and nothing appeared. It seems to be completely gone. I tried going to edit mode and alt H and nothing, and nothing appears in object mode aside from the ears. Usually when geometry is hidden in edit mode it’s still rendered in object mode but the head topo appears to be just gone.

**Comment by vxlcoder** [comment]
very sorry to hear that, @Seonavdp.

which version of RetopoFlow and blender are you using?

**Comment by jlampel** [comment]
Another question - did you hide the head in object mode or in edit mode? If the head is a separate object, see if it's still in the outliner. If it's there but greyed out then go to the outliner filter properties, enable the monitor icon (disable in viewport) option, and then use that toggle to enable it again.

**Comment by Seonavdp** [comment]
I hid the head topo in retopoflow mode using hide selected. I would have
thought this to be the method to hide topo that I wasn’t working on so I
could work on the more complicated ears section. 

On February 9, 2022, Thomas van der Pol ***@***.***>
wrote:
> Another question - did you hide the head in object mode or in edit
> mode? If the head is a separate object, see if it's still in the
> outliner. If it's there but greyed out then go to the outliner filter
> properties, enable the monitor icon (disable in viewport) option, and
> then use that toggle to enable it again.
>

—
Reply to this email directly, view it on GitHub
<https://github.com/CGCookie/retopoflow/issues/1071#issuecomment-
1032877369>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AA6FUSLWOM5C364PRB7ZCGLU2FHTNANCNFSM5LPA76WA>.
Triage notifications on the go with GitHub Mobile for iOS
<https://apps.apple.com/app/apple-store/id1477376905?ct=notification-
email&mt=8&pt=524675> or Android
<https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-
email%26utm_medium%3Demail%26utm_source%3Dgithub>.
You are receiving this because you were mentioned.Message ID:
***@***.***>

**Comment by vxlcoder** [comment]
Yes, @Seonavdp, that's what that feature was intended for.

Which versions of RetopoFlow and Blender are you using?

We did fix an issue with hiding geometry in RF, so if you are running an older version, this issue might already be fixed.  If you're using the latest version, then I'll need to investigate deeper.

**Comment by Seonavdp** [comment]
Yea I’m using blender 2.93.3 and retopoflow 3.2.5. I can’t reproduce the error on a new mesh.

**Comment by vxlcoder** [comment]
thanks for the details, @Seonavdp!

will dig into this!

**Comment by Samaleus** [comment]
I just had the exact same problem. I hid half of the mesh of a creature to do the other half and when I tried later to unhide it, it was gone. I want to cry

**Comment by jlampel** [comment]
I was able to trigger this today, even in the default scene. All I remember doing was:

- Draw some topology with Strokes
- Select everything and hide it
- Draw new strokes
- Exit RF

However, I did not grab the log in time and have not been able to reproduce it again. I still need to figure out what exactly is triggering it.

**Comment by vxlcoder** [comment]
found a reliable way to reproduce!

- load factory defaults
- enable and start RF
- select strokes
- add two strokes (and therefore a patch)
- select all with `a` and hide with `h`
- add new stroke
- press `x` and click delete vertices
- add two new strokes (and therefore a patch)
- exit RF
- reveal hidden geometry with `alt+h`

commit b1ae9d1 explicitly removes hidden verts, edges, and faces from collection to be deleted.  Note: cannot have visible verts if adjacent edges are hidden (same for verts/edges for hidden faces).

**Comment by jlampel** [comment]
I was able to reproduce it every time using those steps in 3.2.9 and not once after the commit. Confirmed fixed!
