### ISSUE TITLE
Target mesh visible through source in 3.2.5 and Blender 3.0

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1072]
In RetopoFlow 3.2.5, the target mesh doesn't seem to be occluded by the source mesh like it was in previous versions:

![image](https://user-images.githubusercontent.com/12982300/148603145-18c409bb-aa76-490b-9b2b-0427fac24adf.png)

Here's an example from a user who compared 3.2.4 and 3.2.5 with what seems like the exact same settings, although the Blender versions are different:

![retopolow324](https://user-images.githubusercontent.com/12982300/148603287-fc98a2bf-c192-4739-b822-18040a8ae333.png)
![retopolow325](https://user-images.githubusercontent.com/12982300/148603311-b230d72f-39ee-415a-8e68-e6cd0b0a410a.png)

https://blendermarket.com/inbox/conversations/61165

**Comment by vxlcoder** [comment]
I recently found a bug in the render code that has been fixed in a recent commit (f1791ba).  Can you try that latest version, @jlampel?

**Comment by jlampel** [comment]
Oh perfect, that does the trick!
