### ISSUE TITLE
[Bug] emulate 3 button mouse interferes with geometry creation

### ISSUE THREAD

**Issue by StarsInDust** [CGCookie/retopoflow#1074]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.25*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*Yes, I read the entire manual. Yes, I am holding down the control key, and no I am not able to create any type of geometry at all. I have tried restarting Blender and even reinstalling the entire add-on. Nothing, this thing just does not work.*}

{*add any screens
![Cannot do anything](https://user-images.githubusercontent.com/35199585/149420087-e41ccebe-cdb2-425d-94ba-be0edbd53783.png)
hots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*Start the program from Object mode, with my object selected. Hit Ctrl-r, or ctrl-left mouse. Nothing works. It does not create geometry*}

{*attach any files needed to replicate the issue*}

**Comment by petcson** [comment]
I have this exact same bug.  Sometimes im able to make it work by pressing alt while i've got control held down but otherwise yeah its not working at all.

**Comment by vxlcoder** [comment]
the loops tool adds an edge loop to existing geometry. since you don't have any existing geometry in target mesh, you might try starting with contours instead.

I know you both said that you've read the docs, but just to reiterate: Ctrl+LMB is the default key for adding new geometry.

**Comment by petcson** [comment]
I think i know whats happening.  I have emulate 3 button mouse on and i think that was screwing things over for me.  Looks like retopoflow and emulate 3 button mouse do not work well together. Emulate 3 button mouse allows you to press alt and control in combination with the mouse to emulate a middle click.  looks like those are stepping on each other's toes.

**Comment by vxlcoder** [comment]
ah, great catch! I will look into that. thanks.

are you up and running now?

**Comment by petcson** [comment]
Ish? Everything is technically working as intended.  I use a graphics tablet so without 3 button mouse i cant zoom in and out so i'll have to figure something out in the mean time.  Thanks for the EXTREMELY fast comments. Can you message back here if that bug gets squashed?

**Comment by vxlcoder** [comment]
will do!

**Comment by petcson** [comment]
Btw this bug has been around for probably at least 6 months.  I just thought it was a problem with my tablet at the time.

**Comment by petcson** [comment]
After navigating with alt and left click it seems that if i tap shift before pressing ctrl+anybrush it seems to work.  Tapping shift seems to reset something.

**Comment by vxlcoder** [comment]
oooh, that's really useful!  I think I might know what the issue (or one of the issues) is!

**Comment by vxlcoder** [comment]
oooh, that's really useful!  I think I might know what the issue (or one of the issues) is!

**Comment by petcson** [comment]
Sorry for the comment spam but i can now tell u when the error occurs.  After i pan using emulate 3 button mouse by pressing alt + shit + lmb it wont let me create geometry anymore by pressing ctrl.  only after pressing shift once will it work again.

**Comment by vxlcoder** [comment]
Thanks for the help, @petcson!

commit 62f29fd _should_ fix this issue.  I have been able to confirm it on my end, but it would be nice to know that it worked for you, too.

**Comment by petcson** [comment]
i would love to test this out but I'm not sure how to get this into my addon.  Is there a new release I can download?

**Comment by vxlcoder** [comment]
@petcson, you can use the updater system to update to branch `v3.2.6`: under RetopoFlow menu > Updater > type `v3.2.6` in advanced branch / commit > ok. then restart Blender.
