### ISSUE TITLE
**[BUG]** Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by dreamparacite** [CGCookie/retopoflow#1075]
**Issue:**

I was making some knife cuts to try and match the knuckle topology from this reference, after a few cuts I got the error message.

![screenshot_of_issue](https://user-images.githubusercontent.com/1375891/149534840-46bc86fe-9656-4a82-ba7d-270019cee233.png)

**How to Reproduce:**
Between the edge loops on the finger where the knuckle would be, use the knife tool to cut a square into the middle of the edge loop. The error occurred before I could cut the diagonal cuts connecting the middle square to the corner vertices.

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- CG Cookie built
- Blender: 3.00.0 master 2021-12-02
- Platform: Windows, 10, 10.0.19043, AMD64, Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 497.29, (no shader version)
- Timestamp: 2022-01-14 08:35:54.726211
- Undo: insert, insert, insert, insert, insert, select all, slide edge loop/strip, insert edge loop, insert, insert

Error Hash: fe59243c687f0132d13819c4367cdd3b

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-     C:\Users\KarlLocal\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0174:co() self.bmelem.co = co
-     C:\Users\KarlLocal\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 001 0561:set2D_vert() vert.co = xyz
-     C:\Users\KarlLocal\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 002 0527:modal_move() set2D_vert(bmv, xy1)
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @dreamparacite.

I was not able to reproduce your bug, but I added some code that _should_ prevent that from happening again.  Please do let us know if you run into this bug again.

you can test it out by using the Updater system ([docs](https://docs.retopoflow.com/addon_updater.html)) to checkout commit `88a99d4`, but we will be posting up an official release soon.

happy retopo'ing!
