### ISSUE TITLE
[QUESTION] Is it possible to not see retoped mesh through high poly? backface cull?

### ISSUE THREAD

**Issue by TitusLVR** [CGCookie/retopoflow#1078]
Retopoflow Version: 3.2.5
Blender Version/Hash:3.0/3.1
Platform Version/Distribution:Wondows 10

Hello,
Is it possible to not see retoped(low poly) mesh through high poly? Because it's is hard to do a retopo when you see backface mesh or a mesh behind low/high poly. Existing parameters doesn't allow to setup viewport.
image is an simple example:
![image](https://user-images.githubusercontent.com/13762728/150684636-16f03395-5964-4b72-811b-27c97ad333ea.png)

Many thanks! Hope to heat from you soon.

**Comment by vxlcoder** [comment]
thanks for the question, @TitusLVR.

we actually found a bug in the code that causes those visual issues. it should be fixed in v3.2.6, which we plan to release next week.

you can try it out using the updater system or wait a few days.

happy reopo'ing!

**Comment by TitusLVR** [comment]
Hey, I've tried 3.2.6 - all works for me. Thank you guys for such amazing addon.
