### ISSUE TITLE
Resolved - BUG Created Target - Blender crashes or Blender Viewport motion freezes, No Retopo Tools work

### ISSUE THREAD

**Issue by grnbriar** [CGCookie/retopoflow#1079]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.2.4

Blender Version/Hash: 3.0

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**
(I have disabled most other addons.)
Start with 1 decimated model 175K. Create target at cursor.
Either crashes Blender instantly, or does open with welcome screen.
Close welcome screen and can not rotate, move  or scale viewport. No retopo tools work when selected.
How do I start retopo process? What is hung?
I usually see white overwritten text at top. No errors appear in the console window.

I can exit RetopoFlow and Blender is frozen, no viewport controls, can not select anything in scene or in scene list.
Have to close Blender.

{*add any screenshots of the issue here*}

Before creating target
![RetopoStart](https://user-images.githubusercontent.com/98400895/150985357-298469a8-67fa-4aab-8320-affce1eee7ac.jpg)

![RetopoFrozen](https://user-images.githubusercontent.com/98400895/150985389-1700fb1d-efec-4693-ae91-f593735b00e0.jpg)

Overwritten Text at top appears most times -

![Retopo Error Text](https://user-images.githubusercontent.com/98400895/150986331-3fa90b06-691d-430f-bd8a-147b6aad9e19.jpg)
&nbsp;

**How to Reproduce:**

Add target, either option.

{*attach any files needed to replicate the issue*}

**Comment by grnbriar** [comment]
Found the 3.2.5 version - this fixes the viewport freeze issue, can now move around, but no retopo tools function.
How to activate them to get started?

**Comment by grnbriar** [comment]
Got them working on Display tablet! On to learning the tool!

**Comment by vxlcoder** [comment]
glad to hear it is working!

let us know if you have any other problems.

happy retopo'ing!
