### ISSUE TITLE
BUG? M1 MacBook reports opengl issue when starting RF

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1080]
Possible bug with RetopoFlow, although I'm leaning toward it being a Mac M1 OpenGL driver bug or a difference in implementation (unclear documentation).

When starting RF, the following is reported to the terminal:

```
UNSUPPORTED (log once): POSSIBLE ISSUE: unit 0 GLD_TEXTURE_INDEX_2D is unloadable and bound to sampler type (Float) - using zero texture because texture unloadable
```

Usually, that report is follow up with some trace.  However, the trace is unrelated.  (it's just some other OpenGL code that finally calls the glCheckError fn and reports it.

As far as I can tell, this is a non-breaking bug.  RetopoFlow _seems_ to continue to operate and render as normal.

A Google search brings up this [link](https://blog.dengine.net/2021/01/wonders-and-mysteries-of-the-m1/), although I'm not sure this is related, as we are not indexing into a sampler2D array.

This might be related to issue #915...

**Comment by BenWeisz** [comment]
Hi, just checking if you've found anything else related to this topic since January. I'm just learning OpenGL and following a tutorial where I have 2 uniform sample2d's and for some reason it just doesn't work and gives me the error message that you posted. Thanks!

**Comment by jlampel** [comment]
We've moved away from OpenGL, so I don't think a fix was found but it's no longer relevant.
