### ISSUE TITLE
Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by piwacket1967** [CGCookie/retopoflow#1081]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- CG Cookie built
- Blender: 3.00.1 master 2022-01-25
- Platform: Windows, 10, 10.0.22000, AMD64, Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 497.29, (no shader version)
- Timestamp: 2022-01-29 10:45:39.152082
- Undo: insert, smart select, insert, select, insert, smart select, insert, select, insert, insert

Error Hash: 540064ee3d7cd3905f68e45a8dd76463

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'merge'
-     C:\Users\John\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 000 0381:_insert() cur.merge(bmv)
-     C:\Users\John\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0149:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\John\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 002 0246:insert() return self._insert()
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @piwacket1967!

Unless the Blender API changed, I'm not sure why this is happening.

Can you give any more information about how it happened?

**Comment by JoshQuake** [comment]
Getting this as well. It seems to occur every time the end click isnt on the target geo?

```
Environment:

- RetopoFlow: 3.2.6
- CG Cookie built for GitHub
- Blender: 3.01.0 master 2022-03-08
- Platform: Windows, 10, 10.0.19042, AMD64, Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3080/PCIe/SSE2, 4.5.0 NVIDIA 511.79, (no shader version)
- Timestamp: 2022-03-18 06:06:42.735321
- Undo: insert, insert, select

Error Hash: 540064ee3d7cd3905f68e45a8dd76463

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'merge'
-     C:\Users\jwake\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 000 0389:_insert() cur.merge(bmv)
-     C:\Users\jwake\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0150:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\jwake\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 002 0254:insert() return self._insert()
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the detail, @JoshQuake.

will take another look

**Comment by Mach12** [comment]
Just got what I assume to be the same error:

```
Environment:

- RetopoFlow: 3.2.9α
- CG Cookie built for GitHub
- Blender: 3.04.1 blender-v3.4-release 2022-12-19
- Platform: Windows, 10, 10.0.19045, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 526.98, (no shader version)
- Timestamp: 2023-01-29 00:29:39.171356
- Undo: insert, select, select, change segment count, cut, change segment count, cut, change segment count, cut, change segment count

Error Hash: 540064ee3d7cd3905f68e45a8dd76463

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'merge'
-     C:\Users\Pixelmod\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 000 0389:_insert() cur.merge(bmv)
-     C:\Users\Pixelmod\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0150:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Pixelmod\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 002 0254:insert() return self._insert()
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

My last course of action before this happened was attempting to knife across a mesh. Left-clicked outside the mesh left of it, left-clicked again to the right of the mesh, crashed.

Any update on this?

**Comment by jlampel** [comment]
I'm having a hard time replicating this issue in 3.2.9. I haven't gotten it to crash regardless of whether the first or second click is outside of the target mesh or even the source mesh. Please let me know if this happens again! A file to test would be very helpful.

**Comment by jfranmatheu** [comment]
After careful review, this issue is being closed due to prolonged inactivity and insufficient diagnostic information.

I tried following the 'last course of action' of reporter prior to the crash but I wasn't able to replicate it in latest RF version.

Feel free to re-open or create a new issue in case you find this issue to be recurrent in newer versions, then please provide new info to help you further.
