### ISSUE TITLE
Tools not always working.

### ISSUE THREAD

**Issue by Pandazole** [CGCookie/retopoflow#1085]
Tool version: 3.2.5
Blender 3.0 and 3.0.1
Windows 10
Model tris count: 125k.

Issue: 
Contours, Polystrips, strokes tools not always working, when pressing CTRL+LMB, the highlight(yellow) line does not always appear (For all previous tools). And if it appears, it doesn't always create a loop (This is correct for only the Contours tool). It gives like cooldown effect, an example I can use it for 10 seconds, then 10 seconds not working.

I'm using only a mouse here, not using the drawing tablet (fully disconnected).

Providing a video for the problem:

https://www.youtube.com/watch?v=GLLEYsydIWA&ab_channel=Keen822

**Comment by Pandazole** [comment]
Hi @vxlcoder ,

Thanks for the fast reply, all sent to the email.

**Comment by Pandazole** [comment]
This is another video with an observation that may help in debugging.

The PolyPen tool is always working, but when the "guiding dotted" lines in the PolyPen tool disappeared, the Contours tool is not working, but when it reappears, the Contours tool works normally.

https://youtu.be/q8-BGQLpKtA

**Comment by vxlcoder** [comment]
oh, interesting @jlampel.

**Comment by Pandazole** [comment]
Hi @jlampel ,

Thanks for your reply.

No, also I only download the addon after experiencing the bug to confirm I was pressing the correct keys.

I disabled all user addons too, the bug is still there.

**Comment by jlampel** [comment]
Ok, this is strange. I've tried it several other times, but I can't get the bug to occur again - even after closing Blender and loading the exact same file with all the same settings. So far, I'm not sure how to reproduce it. Blender 3.0.0 and RF 3.2.5.

**Comment by Pandazole** [comment]
Hi,

A new update, I can now always make the Yellow guiding line reappear by pressing "SHIFT + CTRL", this is always working. However, even if there are guiding lines, the tool is not always registered.

I notice something that, the top view (Num pad 7) has Zero failures if the guiding lines are working. However, the right side view (Num pad 3) has zero success. Even if the model is not in orthographic view, if I review it from a clear straight right view, the problem is the same. However, if I tilt the camera in rotated view, the tool starts working, but not forever. 

All visual details are in the link below:

https://studio.youtube.com/video/WRzU6HEQxdw/edit

**Comment by Pandazole** [comment]
The tool now works normally, maybe because of my software specification or somehow.

Thanks for your efforts.
