### ISSUE TITLE
Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Yuanzhoulv7** [CGCookie/retopoflow#1087]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.5
- Blender: 3.00.1 master 2022-01-25
- Platform: Darwin, 21.4.0, Darwin Kernel Version 21.4.0: Sat Jan 29 03:25:15 PST 2022; root:xnu-8020.100.417.0.4~31/RELEASE_ARM64_T6000, x86_64, i386
- GPU: Apple, Apple M1 Pro, 4.1 Metal - 76.3, (no shader version)
- Timestamp: 2022-02-15 18:41:22.249494
- Undo: insert, insert, insert, insert, insert, deselect all, tweak move, tweak move, tweak move, tweak move

Error Hash: fe59243c687f0132d13819c4367cdd3b

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-     /Users/pi7/Library/Application Support/Blender/3.0/scripts/addons/retopoflow-master/retopoflow/rfmesh/rfmesh_wrapper.py
- 000 0174:co() self.bmelem.co = co
-     /Users/pi7/Library/Application Support/Blender/3.0/scripts/addons/retopoflow-master/retopoflow/rf/rf_target.py
- 001 0561:set2D_vert() vert.co = xyz
-     /Users/pi7/Library/Application Support/Blender/3.0/scripts/addons/retopoflow-master/retopoflow/rftool_knife/knife.py
- 002 0527:modal_move() set2D_vert(bmv, xy1)
-     .../common/fsm.py
- 003 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @Yuanzhoulv7.

I believe this is related to issue #1075, which is already fixed and should be officially released soon.  You can try out the fix by using the Updater System ([doc](https://docs.retopoflow.com/addon_updater.html)) to update to branch `v3.2.6`.

Let us know if you still have this issue after updating to v3.2.6, either with the official release or by using the updater.

Happy retopo'ing!
