### ISSUE TITLE
[BUG] Blender freezes when using Knife

### ISSUE THREAD

**Issue by dtschultz** [CGCookie/retopoflow#1088]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*} 3.25

Blender Version/Hash: {*add here*} 2.93.6

Platform Version/Distribution: {*add here*} 

&nbsp;

**Issue:**

Clicking on a vert with Knife can cause Blender to freeze.

![Screenshot 2022-02-21 105453](https://user-images.githubusercontent.com/53536825/154989033-bf3283f0-a045-4f5d-a568-e75b41c30db6.jpg)

&nbsp;

**How to Reproduce:**

- I've been having a problem with Knife that happens pretty regularly to me. Blender never crashes, and it freezes, so I don't know how to get an error log. It looks like it happens if I accidentally click too close to another vert. This happened in this screenshot. It looked to me like I clicked on the vert, but I think the knife doesn't actually snap to the vert and it tries to add a vert on top of it, so it causes some kind of error. I've had it happen several times. It might be the same thing as the Knife Handle Exception listed elsewhere, but I wanted to report it just in case it was different.

{*attach any files needed to replicate the issue*}

**Comment by hansolocambo** [comment]
Knife is ultra unstable for some reason. I quit retopoflow, save, restart retopoflow then attempt a cut. Every time...

**Comment by vxlcoder** [comment]
thanks for the report, @dtschultz.  will take a look.

**Comment by dtschultz** [comment]
Thank you very much! I love Retopoflow.

**Comment by vxlcoder** [comment]
this issue should now be fixed in commit 8cee069.

i was able to reproduce this issue consistently by clicking randomly with knife for a while.  now, it seems quite stable (at least against random clicking).

i'm working on getting this released soon, but you can try it out by using the Updater System ([doc](https://docs.retopoflow.com/addon_updater.html)) to check out branch `v3.2.6` if you'd like.

let us know if you have any other problems.

happy retopo'ing!

**Comment by dtschultz** [comment]
Thank you very much! I tried it out this morning, and at least in my quick test, it seems to be fixed. I'll give it a more thorough run through later today or tomorrow when I have more time.
