### ISSUE TITLE
**SOLVED** Retopoflow : Vertices snap to Mirror's Center.

### ISSUE THREAD

**Issue by hansolocambo** [CGCookie/retopoflow#1089]
Working with Symmetry Mirror X activated : 

Doesn't matter if Mirror has a very small merge value, or even if merge is ticked at all. Vertices -any vertex no matter how far it is from the center- instantly moves and snaps to the mirror center. 
It's definitely a bug as I worked on a retopology for hours yesterday without issue. And this morning I reload the scene and I can't retopo anymore with mirror activated. 
Very annoying, as working without the mirror modifier makes it really time consuming to eyeball the center of the mesh while retopologyzing :/

I can't reproduce this bug 100% of the time. It works then it doesn't. After months using retopoflow, sure thing is it DOES happen. Still don't know why.

**Comment by jlampel** [comment]
Hi, it sounds like you're working on the wrong side of the mesh! To test, switch to Face for the visualization and make sure you're on the non-red side of the object. We've lined it up so that you can always work from front and side view. If you want to draw on the other side, you can flip the mesh so it is facing the opposite direction. 

We should probably add a warning if we detect drawing on the opposite side. @vxlcoder would that be easy enough to do?

**Comment by vxlcoder** [comment]
I thought I had already replied to this issue, but I might've forgotten to hit send!

Yes, it seems like the vertices are on the "wrong" side of the mesh.  Presently RetopoFlow has a very simple view of symmetry (mirroring).  This is a limitation that I'd like to remove at some point, but it likely won't be too soon.

As a way to prevent confusion like this in the future, I added it commit 7d043c1 a check that will look for bad symmetry vertices during start up of RetopoFlow.  I also added a button under Target Cleaning to select these vertices.  This is not a complete or very satisfying solution, but it at least works to warn the artist.

**Comment by hansolocambo** [comment]
> wrong side of the mesh

@[jlampel](https://github.com/jlampel)
Nope. Been in the gaming industry for 20+ years and I'm pretty confident with my sculpts. It's clean mesh. Normals are facing outside. 
I tried to reduce all snapping values I could find but it doesn't do anything. Moving any geometry snaps it to the center of the mirroring. This NEVER happens in Blender. It just does happen with Retopoflow. I know retopo without mirror on. Which is... fine. Except I need to eyeball the center and then fix the alignment with a scale later.

**Comment by vxlcoder** [comment]
I am sorry for any confusion, and we certainly didn't mean to say that you don't know what you're doing!

What I meant about RF's simple view is this: if x-symmetry is enabled, RF will snap vertices that have a negative X coordinate to the YZ plane (where x=0). this is similar for y- and z-symmetry, although y-symmetry snaps positive y values to 0.  eventually, we want to remove this limited view to have RF behave much like blender does.

so, if your one scene has geometry on the "wrong" side of symmetry, you will get this behavior in RF but not blender.

however, if you have found a situation where it always snaps verts to symmetry plane, no matter which side that vert was on, then that's definitely a bug, and we need to fix it!

would you mind sharing your .blend file with us so we can look at your particular case?  you can send it to retopoflow@cgcookie.com.

**Comment by hansolocambo** [comment]
Wow. Sorry it took me sooooo long to understand. Retopology in 3DCoat is.. well was (thanks to retopoflow I abandoned 3DCoat for that :)  ) exactly the same. One had to select geometry on the +X,Y,Z side of the mirror for the symmetry to work. 
Working on a new asset, I had the issue again today. Saw your answer here > Applied the mirror, deleted the -X side of the mesh > Started Retopoflow again. And hurrah ! it works. That's cool :) Although being able to work on both sides would be cool. Not utterly necessary. 

Sorry about the "I'm in the gaming industry for 20+ [...] ", sounded bad. All I meant was that after a long professional vertices-welding experience, we modelers tend to create perfectly clean and well thought wireframes ;) But I misunderstood your explanations. My apologies. 

Cheers. And thanks for this really neat retopology solution.

**Comment by vxlcoder** [comment]
Glad to hear you're up and running!

let us know if you have any other problems.

happy retopo'ing!
