### ISSUE TITLE
is there a solution for this !!!

### ISSUE THREAD

**Issue by Ahmad4K** [CGCookie/retopoflow#1090]
hi,
I have 2 issues I'm facing with retopoflow, 

1. overlapping , i dont want to see backface, I tried solving this issue with no luck.
![Screenshot (110)](https://user-images.githubusercontent.com/33658421/155750119-101a03ec-6659-4766-8ff7-dd92f2b9a2dc.png)

2. getting texteme lagging , my target is 3m polys, but the tool becomes super slow to the point of being unusable.
I have a project for a client and I'm now on third day researching and trying solving these issues, 

my setup:
5900x
32gb
1 tb nvme
3060
windows 10

looking forward for your help, thanks.

**Comment by hansolocambo** [comment]
your SOURCE if 3M polys. Not your target (retopology)
Make a copy of your source that you'll use later I guess for baking. 
Then remesh / decimate, etc. your source in order to get the polycount down to 100K-300K polygons without loosing the shape. 

Do your retopology on the decimated source. It will work much more smoothly as Blender won't have to compute millions of snapping possibilities every time you move a vertex. 

The problem here is not retopoflow. It's your workflow.

**Comment by vxlcoder** [comment]
Thanks for the report, @Ahmad4K.

@hansolocambo is correct with a solution to the extreme lag.  RetopoFlow's performance does degrade with high poly counts, both in the source mesh (the high poly mesh that's being recreated) and the target mesh (the low poly, nice topo mesh that you're working on).  A simple approach to reducing the source count is to use a decimate modifier.

For the first issue, we did notice a bug in the render code for RetopoFlow v3.2.5, possibly earlier.  We have fixed this issue, but haven't officially released this quite yet... there are a few other issues we were hoping to get into the release, but we might just release it anyways.  You can try out this version right now by using the Updater System to get the `v3.2.6` branch.

**Comment by Ahmad4K** [comment]
yeah I know about the decimation but I thought there will be a fix as I still think that this isnt a good solution, 
when I go to edit mode and do manual edge extrude i dont get any slowdown at all, I have also tested 3dcoat with 9m mesh and havnt found any lagging, I will try 326 now, thanks

**Comment by vxlcoder** [comment]
Yes, unfortunately we have to do a lot of the work in Python through Blender's API, which is much slower than doing all directly in Blender core. we are currently working on some changes that should significantly improve RF's performance if accepted.

please let us know if you have any other problems or questions.

**Comment by vxlcoder** [comment]
please see https://docs.retopoflow.com/addon_updater.html for details on downloading branch `v3.2.6`, or wait for the official release (planning to release by early next week).

**Comment by Ahmad4K** [comment]
great, thanks

**Comment by vxlcoder** [comment]
closing, but let us know if you have any questions or problems.
