### ISSUE TITLE
Why is the source always so transparent

### ISSUE THREAD

**Issue by hansolocambo** [CGCookie/retopoflow#1091]
I tried all visibility options available. But nothing helps. For some reason the source (high poly) mesh is transparent in Retopoflow like... it was a good idea. I used tons of retopology solutions along the years and I've never seen, in  Maya, 3DS Max, 3D-Coat, ZBrush, etc. an app that makes the sources transparent. 
Why would we want to see the other side of everything when all we want is to see the the wireframe we're currently working on and the surface it's snapped onto. 

I'm currently working on a relatively basic chair. And even on such simple objects, the viewport in Retopoflow is a hard to read mess of wireframe. 
![Retopoflo Transparency](https://user-images.githubusercontent.com/33687288/155757009-ba4e2b8a-950e-40e9-99b1-3eca163e7e8f.png)

How can we make the source identical to default viewport settings : NOT see through. Why does it become transparent by default O.o ? Why when I choose the obvious options : Selection > Block backface, block occluded, do I still see the back of everything ? 

I can't understand the logic behind those add-on coding decisions.

**Comment by vxlcoder** [comment]
Thanks for the report, @hansolocambo.

We have fixed this visual bug, but haven't yet officially released it.  if you'd like to try it out, you can use the Updater System to download branch `v3.2.6`.  Otherwise, we hope to release it later today or very early next week.

**Comment by hansolocambo** [comment]
Oh so it's not a decision, it's considered as a bug. Well thanks for the quick answer. At least I know it's being worked on. That's excellent news. This constant see through everything is so terrible. I'm gonna try to download this 3.2.3 version you talk about. Not sure where though. 
Thanks for the info :)

**Comment by vxlcoder** [comment]
see https://docs.retopoflow.com/addon_updater.html for details on using the updater system.

let us know if you have any other problems.

**Comment by hansolocambo** [comment]
I confirm that v.3.2.6 fixes the transparency issue. That's great ! thanks (b^-^)b

Viewport Display > Target Mesh Drawing > Alpha Below 0

**Comment by hansolocambo** [comment]
Don't why I wrote that yesterday. Source mesh and retopo are still transparent. And we see everything through at all times :/

**Comment by hansolocambo** [comment]
I figured that out thank you :) I came back here to delete my comment but you already answered ;) You're fast ^^
Cheers vxlcoder.
Thanks.

**Comment by vxlcoder** [comment]
did that resolve the problem?

**Comment by hansolocambo** [comment]
Yes indeed it did. Sorry I forgot to confirm that. 
Thanks.

**Comment by vxlcoder** [comment]
glad to hear! happy retopo'ing!

**Comment by vxlcoder** [comment]
closing, but let us know if you have any further issues.
