### ISSUE TITLE
[BUG] MMB press while LMB pressed in any tool breaks addon

### ISSUE THREAD

**Issue by faikault** [CGCookie/retopoflow#1097]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.2.6*}

Blender Version/Hash: {*3.0.0/3.0.1*}

Platform Version/Distribution: {*windows*}

&nbsp;

**Issue: 
Python: Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\addon_common\cookiecutter\cookiecutter.py", line 164, in modal
    self._cc_actions.unuse('navigate')  # pass-through commands do not receive a release event
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\addon_common\common\useractions.py", line 570, in unuse
    self.unpress()
  File "C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\addon_common\common\useractions.py", line 578, in unpress
    del self.now_pressed[strip_mods(self.just_pressed)]
KeyError: 'MIDDLEMOUSE'

location: <unknown location>:-1

**

{***[BUG]** MMB press while LMB pressed in any tool breaks addon*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*Press middle mouse button while moving polygons (LMB) with any tool*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
thanks for the report, @faikault.

good catch.  will take a look at this soon.

**Comment by vxlcoder** [comment]
commit d6bc869 should fix this bug.  If you'd like to try it, use the Updater System ([doc](https://docs.retopoflow.com/addon_updater.html)) to update to branch `v3.2.7`.

**Comment by faikault** [comment]
I've tried to update it through the updater system typing in v3.2.7 and pressing install a few times but it seems to break the addon. When I reload it or restart blender it says (broken) retopoflow. Not sure what else I can do to try it.

**Comment by vxlcoder** [comment]
try this: uninstall RF, restart Blender, install v3.2.6, update RF to v3.2.7, restart Blender. then run RF. if that doesn't work, I will make a new zip for you. thanks for trying!

**Comment by faikault** [comment]
So I wasnt able to make that work but i manually copied over the update into the 3.2.6 zip file and that worked, also the bug is gone!
