### ISSUE TITLE
**[BUG]** Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by faikault** [CGCookie/retopoflow#1099]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*Crash when zooming (MMB) while pressing CTRL in knife tool*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*Zoom (MMB) while CTRL knife tool active, crash also present in v3.2.6*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.7α
- CG Cookie built for GitHub
- Blender: 3.00.1 master 2022-01-25
- Platform: Windows, 10, 10.0.19044, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 1080/PCIe/SSE2, 4.5.0 NVIDIA 511.65, (no shader version)
- Timestamp: 2022-03-08 22:08:03.503628
- Undo: grab, select, smart select, smart select, select

Error Hash: 8cb544e32a1e15de0ad45b3bd7918a85

Trace:

- EXCEPTION (<class 'TypeError'>): intersect_line_line_2d
-     C:\Users\USER\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 000 0572:_get_crosses() i = intersect2d_segment_segment(p0, p1, c0, c1)
- 001 0673:draw_postpixel() crosses = self._get_crosses(knife_start, self.actions.mouse)
-     .../common\fsm.py
- 002 0135:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
you're finding all the keymap related issues. will get this fixed soon. thanks, @faikault

**Comment by jlampel** [comment]
This appears to be fixed in the latest versions
