### ISSUE TITLE
[BUG] Single edges are unselectable 

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1100]
Whether they're created by strokes, polypen, or deleting other edges, any vertex or edge that is not part of a face is shown as dim (below the surface?) and unselectable.

This is in Blender 3.0 and RF 3.2.6

![blender_WVt7EBwt8Q](https://user-images.githubusercontent.com/12982300/157496435-1727c519-ec2f-4e84-a595-016d00150815.gif)

**Comment by vxlcoder** [comment]
after much digging, i've found that `normal_update()` on `BMVert` will set `normal` to `Vector((0,0,0))` if it has no `link_faces`.  this is the behavior all the way to Blender 2.93.6.

this bug also makes the verts and edges really hard to see.

commit 632483f fixes this issue.

**Comment by vxlcoder** [comment]
created [blender patch](https://developer.blender.org/D14370) to document this `normal_update()` behavior

**Comment by jlampel** [comment]
And with a Blender patch too... amazing!
