### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Chaoshideout** [CGCookie/retopoflow#1105]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.6
- Self built
- Blender: 2.93.3 master 2021-08-17
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 511.79, 4.50 NVIDIA
- Timestamp: 2022-04-06 02:46:34.537078
- Undo: extrude strip, select, select, select, select, select, select, select, select, select

Error Hash: 909926f9f15d51ff581cac2ca0da8fa2

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'is_valid'
-     C:\Users\flinh\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0241:shared_edge() if not self.is_valid or not other.is_valid: return False
-     C:\Users\flinh\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 001 0908:<listcomp>() nedges = [v0.shared_edge(v1) for (v0, v1) in iter_pairs(last, wrap=False)]
- 002 0908:extrude_equals() nedges = [v0.shared_edge(v1) for (v0, v1) in iter_pairs(last, wrap=False)]
-     C:\Users\flinh\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 003 0150:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\flinh\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 004 0314:modal_main() self.replay()
-     .../common\fsm.py
- 005 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @Chaoshideout.

I will take a look at this as soon as I can.

**Comment by jlampel** [comment]
Closing as a stale issue without much info - it either has come up again and been fixed or it will be reported again in the future.
