### ISSUE TITLE
RetopoFlow Won't Enable 

### ISSUE THREAD

**Issue by YuiFox** [CGCookie/retopoflow#1106]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.2.6*}

Blender Version/Hash: {*2.90*}

Platform Version/Distribution: {*Windows 11 Home/  Intel *}

&nbsp;

**Issue:**

{*Everytime I Try to enable RetopoFlow into my blender  but it'll give me a syntax error and much more .. i even reinstalled blender and retopoflow and closed it out and it still gave me the error once more saying i cannot install it inside my blender .. i have blender 2.90  is there a way anybody can help me fix this problem*}

{* *}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}
![9a5ff60cee183fc6d2f11005782c11eb](https://user-images.githubusercontent.com/66194125/162346818-8df100d7-4e76-4590-bc45-2317d92746c3.png)

**Comment by vxlcoder** [comment]
Hi there @YuiFox!

Sorry that I didn't get to this sooner.

RF v3.2.6 will only run on later versions of Blender.

You will need to install RF v3.2.4.

Please let us know if you have any other issues.
