### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Bataghast** [CGCookie/retopoflow#1107]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.6
- CG Cookie built for GitHub
- Blender: 3.01.0 master 2022-03-08
- Platform: Windows, 10, 10.0.19044, AMD64, Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, 4.5.0 NVIDIA 512.15, (no shader version)
- Timestamp: 2022-04-07 19:00:03.180744
- Undo: insert, insert, select, move after select, grab, smart select, select, insert, select, insert

Error Hash: aa91525e6e6bc87f4600a32e1190d12e

Trace:

- EXCEPTION (<class 'TypeError'>): 'NoneType' object is not subscriptable
-     C:\Program Files (x86)\Steam\steamapps\common\Blender\3.1\scripts\modules\bpy_extras\view3d_utils.py
- 000 0187:location_3d_to_region_2d() prj = rv3d.perspective_matrix @ Vector((coord[0], coord[1], coord[2], 1.0))
-     C:\Users\5623\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rf\rf_spaces.py
- 001 0091:Point_to_Point2D() xy = location_3d_to_region_2d(self.actions.region, self.actions.r3d, xyz)
-     C:\Users\5623\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 002 0721:<listcomp>() coords = [self.rfcontext.Point_to_Point2D(co) for co in coords]
- 003 0721:draw_lines() coords = [self.rfcontext.Point_to_Point2D(co) for co in coords]
- 004 0872:draw_postpixel() self.draw_lines([co1, co2, co3, co0])
-     .../common\fsm.py
- 005 0135:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @Bataghast.

I will take a look at this as soon as I can.
