### ISSUE TITLE
Custom icons!

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#111]
It looks like we may be getting custom icon support in Blender for add-ons! http://wiki.blender.org/index.php/User:Brita/Proposals/UIPreviews

If this hits master then I will add custom icons for Contours and Polystrips.

**Comment by patmo141** [comment]
Whoa cool!

**Comment by carter2422** [comment]
It's in Master!! https://developer.blender.org/rBd30f664c0438e8378c79d5beb114b1338d0e1d94

I'll work to get this implemented this week.

**Comment by patmo141** [comment]
Awesome!
