### ISSUE TITLE
[BUG] Custom navigation hotkeys not working

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1112]
One user reported that RetopoFlow wouldn't work with his custom navigation controls, and I confirmed it on my end. Here's his setup:

![image](https://user-images.githubusercontent.com/12982300/163424680-5e6d5aac-fe25-4a1d-b728-4cfbdc66412b.png)

He reported that it's only a problem when they are set to Click Drag, but that without it there's a conflict with normal loop selection.

**Comment by vxlcoder** [comment]
this _should_ be fixed in commit 132d773

**Comment by jlampel** [comment]
Confirmed fixed!
