### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by ApeInOuterSpace** [CGCookie/retopoflow#1115]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.6
- CG Cookie built for Blender Market
- Blender: 3.01.0 master 2022-03-08
- Platform: Linux, 5.16.16-100.fc34.x86_64, #1 SMP PREEMPT Sat Mar 19 13:54:08 UTC 2022, x86_64, x86_64
- GPU: AMD, AMD Radeon RX 5700 (navi10, LLVM 12.0.1, DRM 3.44, 5.16.16-100.fc34.x86_64), 4.6 (Core Profile) Mesa 22.1.0-devel, (no shader version)
- Timestamp: 2022-04-24 00:20:25.116401
- Undo: extrude strip, create strip, select, extrude strip, create strip, select, extrude strip, create strip, select, delete Vertices

Error Hash: a7910f86332cd6323380afb2ef1fa4f9

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rfmesh/rfmesh_wrapper.py
- 000 0355:<listcomp>() verts = [v for v in self.bmelem.verts if v in bme.verts]
- 001 0355:shared_vert() verts = [v for v in self.bmelem.verts if v in bme.verts]
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rftool_strokes/strokes_utils.py
- 002 0135:get_strip_verts() vs.append(e0.shared_vert(e1))
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rftool_strokes/strokes.py
- 003 0900:extrude_equals() side_verts = get_strip_verts(edges1)
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rftool.py
- 004 0150:wrapper() ret = fn(*args, **kwargs)
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rftool_strokes/strokes.py
- 005 0422:stroke() if self.replay: self.replay()
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rfwidget.py
- 006 0109:_callback_tool() fn(self.rftool, *args, **kwargs)
- 007 0133:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     /home/michael/.config/blender/3.1/scripts/addons/RetopoFlow/retopoflow/rfwidgets/rfwidget_brushstroke.py
- 008 0099:modal_line() self.callback_actions(self.action_name)
-     .../common/fsm.py
- 009 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @ApeInOuterSpace.

I am going to close this issue, as I believe this issue _should_ be fixed in v3.2.7 (releasing very soon).  but if you run into it again after updating, please reopen and let us know.

thanks!
