### ISSUE TITLE
Bug: Updating RF when folder contains a dash causes problems

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1118]
Whenever RetopoFlow's add-on folder contains a dash (`-`) or a period (`.`), updating using the Updater System causes problems.

The dashes are usually due to the artist installing from an unofficial zip file.  Possible source: GitHub's "Source code (zip)" link under releases and the "Download Zip" link under the main page "Code" dropdown will create a zip file where the main RF folder has a dash (ex: "RetopoFlow-master" or "RetopoFlow-3.2.6").  Note: the "RetopoFlow_v3.2.6.zip" link under GH Releases is what _we_ uploaded, and it uses the correctly named folder "RetopoFlow".

<img width="344" alt="Screen Shot 2022-05-07 at 9 25 21 AM" src="https://user-images.githubusercontent.com/3790699/167256349-61eb2f7a-43ba-4698-9a57-f6a9599734b7.png">

<img width="428" alt="Screen Shot 2022-05-07 at 9 26 03 AM" src="https://user-images.githubusercontent.com/3790699/167256378-50ad7d1d-efe4-4286-bf06-9e75b2618472.png">

I'm not sure how to correct this.  Python really does not like folders with dashes or periods in them.  Maybe adding a simple warning to the RF start menu would prompt the artist to use official zips?

**Comment by jfranmatheu** [comment]
Closing this issue since looks like this UI/UX enhancement is already implemented.

![image](https://github.com/user-attachments/assets/f6a56a2d-7f43-464e-b8f5-c1a66f38cc9f)
![image](https://github.com/user-attachments/assets/3d92fafd-bf16-4b34-a2a8-7e54ed622ba4)

```py
def is_addon_folder_valid(context):
        # remove .retopoflow
        path = re.sub(r'\.retopoflow$', '', __package__)
        bad_chars = set(re.sub(r'[a-zA-Z0-9_]', '', path))
        if not bad_chars: return True
        # print(f'Bad characters found in add-on: {bad_chars}')
        return False
```

![image](https://github.com/user-attachments/assets/d11a4c2a-fc5d-4bf9-beba-66df4017e6b6)
