### ISSUE TITLE
**[QUESTION]** RetopoFlow does not turn on and does not work after installation-Syntax error

### ISSUE THREAD

**Issue by fifi768** [CGCookie/retopoflow#1128]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.2.8*}

Blender Version/Hash: {*2.82, portable version*}

Platform Version/Distribution: {*windows 10 home*}

&nbsp;

**Issue:**

{*Installed the addon from https://github.com/CGCookie/retopoflow. I installed the addon at the bottom of the blender with a blue inscription that the addon is installed. after installation, I turn on the checkbox next to the name of the addon and an error appears. I looked at the request by mistake among those that appeared earlier, I found something similar here:
https://github.com/CGCookie/retopoflow/issues/1109
However, I have other errors in the program files.
Also tried installing the addon from here https://github.com/CGCookie/retopoflow/releases. The result is the same. Thanks in advance!*}

{*
![image](https://user-images.githubusercontent.com/42095060/171829170-0f80862f-57c0-49cf-bd26-ad66266536c3.png)
*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Hi there @fifi768.

RetopoFlow v.3.2.8 runs on Blender 3.x.x.  Blender 2.82 is an older version, so you will have to use RetopoFlow v3.2.4. It is available on the Blender Market or GitHub releases.

Please let us know if you have any other questions.
