### ISSUE TITLE
[BUG] Save or undo reverts the target mesh scale

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1132]
Using undo will sometimes cause the target mesh to shrink or scale up while the source mesh remains the same size. Exiting RetopoFlow will bring things back to their correct scale. I've found that it's easiest to replicate if you undo right after saving:
- Save a file
- Start RetopoFlow
- Create some geometry
- Save while in RF
- Immediately undo before making other changes
- Repeat steps 3-5 until it occurs

**Comment by jlampel** [comment]
I can confirm that this doesn't only happen when saving, as mentioned in #1131.

**Comment by JimbobweSmells** [comment]
Also experiencing this problem, it's extremely aggravating.

**Comment by MaxB0zz** [comment]
this problem makes me unable to use this tool...

**Comment by vxlcoder** [comment]
sorry for the delay all!  will tackle this issue (and #1131) now

**Comment by sethflynnmail** [comment]
This retopo program is amazing, it's the only 3dcoat alternative that I have found that makes manual retopo so easy, but yes the undo bug absolutely kills it. must be fixed asap.

**Comment by vxlcoder** [comment]
thanks for the feedback! I made some great progress today, but it is not quite ready for testing. hoping to have something this weekend.

**Comment by jlampel** [comment]
Another user reported this today via BM inbox, and it sounds like it's happening on save.

**Comment by huzaifahalmansor** [comment]
> Using undo will sometimes cause the target mesh to shrink or scale up while the source mesh remains the same size. Exiting RetopoFlow will bring things back to their correct scale. I've found that it's easiest to replicate if you undo right after saving:
> 
>     * Save a file
> 
>     * Start RetopoFlow
> 
>     * Create some geometry
> 
>     * Save while in RF
> 
>     * Immediately undo before making other changes
> 
>     * Repeat steps 3-5 until it occurs

I just get this lovely addons from blender market. This bug happen to me today. it's happen when i use Ctrl+Shift+z for redo.

**Comment by Catology** [comment]
I also have this issue, it happens constantly. I'm new to learning Retopoflow so of course I'm hitting undo a lot, but it's very frustrating to have to constantly Exit then restart the add-on.

**Comment by vxlcoder** [comment]
this issue should now be fixed in commit a8708f3!

**Comment by jlampel** [comment]
Hasn't been an issue since!
