### ISSUE TITLE
[BUG] Toolbar and sidebar stuck after saving

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1133]
Sometimes while saving, the toolbar and sidebar will be drawn over the RetopoFlow UI and get stuck there until exiting RetopoFlow. I have yet to replicate this consistently, but it seems to happen more often when trying to save an unsaved file. 

![Screenshot 2022-06-06 145144](https://user-images.githubusercontent.com/12982300/172256749-3fbc79e4-5396-437e-9d5c-f4e335cfd9bf.jpg)

**Comment by nekorushi** [comment]
Same happens for me, it consistently happens after fresh opening of RetopoFlow, then making any change and first save causes this issue

**Comment by jlampel** [comment]
I believe this has been fixed since I see a change that affected areas with region overlap, and I have not been able to replicate it recently. Will open back up if it comes up again.
