### ISSUE TITLE
[BUG] Text disappears at some UI scales

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1135]
Here's an interesting one! Some (but not all) of the interface text in the RetopoFlow menu disappears when changing Blender's UI scale. For example, it works great when I set the UI scale to 1.25 or 1.4, but it breaks when I set it around 1.3. 

Example:

![Screenshot 2022-06-30 171325](https://user-images.githubusercontent.com/12982300/176799377-68af1e72-a3e7-4f4b-b6fc-a15f0136d25b.jpg)

**Comment by vxlcoder** [comment]
Interesting.  Testing on Blender 3.3.0 alpha and RF v3.2.5, I wasn't able to reproduce it at 1.2, but it this issue does show up at 0.9.

**Comment by jlampel** [comment]
This bug has since disappeared. All arbitrary values now seem to work fine 🎉

**Comment by vxlcoder** [comment]
this should now be worked around enough to not happen with the detail/summary UI elements.

**Comment by jlampel** [comment]
Works great now!
