### ISSUE TITLE
[PROPOSAL] Align RetopoFlow object to active 

### ISSUE THREAD

**Issue by German-S** [CGCookie/retopoflow#1137]
Hello.
The other day I ran into a situation that I had to solve manually, we are talking about symmetrical objects that are rotated at a non-standard angle (arbitrarily).
In Zbrush there is a "local symmetry" option, it is calculated relative to the object and not global coordinates (like you did). This allows you to work with a symmetrical object that is rotated at any angle.
RetopoFlow allows you to enable symmetry and work only with global coordinates.
Because of this, I had to manually make symmetrical parts.

Please add local symmetry so that you can retopologize symmetrical objects located at arbitrary angles.

**Comment by jlampel** [comment]
I could definitely see this being helpful. @vxlcoder do you think this would make sense to add to the At Active option? I actually think we may have had it like that previously, but was it too confusing to use? I forget exactly. 

In the meantime, here's what you can do: Duplicate the object you want to base the transformations off of, head into edit mode on just that new object, delete all the vertices, and then start RetopoFlow from inside Edit Mode to use it as the starting point.

**Comment by vxlcoder** [comment]
RetopoFlow currently mirrors based on the object's origin, which is identical to how Blender's mirror modifier works.  RF gives the option to create a new object at the 3d cursor or at the origin of the active object.

But what I think what @German-S is suggesting is to have more arbitrary symmetry.  For example: rotational symmetry like you might see with the legs of an octopus.

I think what would be better, more general approach is to map one part of the mesh to other parts (maybe by creating corresponding strokes from base to tip for each part, as example?) so that any geometry created or edited on one part is automatically mapped to the corresponding parts.

this is something that i've been thinking about for a long time, and i plan to attack it once my blender dev grant is over.

**Comment by German-S** [comment]
> I could definitely see this being helpful. @vxlcoder do you think this would make sense to add to the At Active option? I actually think we may have had it like that previously, but was it too confusing to use? I forget exactly.
> 
> In the meantime, here's what you can do: Duplicate the object you want to base the transformations off of, head into edit mode on just that new object, delete all the vertices, and then start RetopoFlow from inside Edit Mode to use it as the starting point. It does actually use local symmetry, it's just that when the RetopoFlow object is newly created it's always aligned to the world.



> I could definitely see this being helpful. @vxlcoder do you think this would make sense to add to the At Active option? I actually think we may have had it like that previously, but was it too confusing to use? I forget exactly.
> 
> In the meantime, here's what you can do: Duplicate the object you want to base the transformations off of, head into edit mode on just that new object, delete all the vertices, and then start RetopoFlow from inside Edit Mode to use it as the starting point. It does actually use local symmetry, it's just that when the RetopoFlow object is newly created it's always aligned to the world.



I'm sorry, I did the steps that you suggested and the local symmetry worked out as it should.
I figured out what my problem was, I reset the shape parameters, Ctrl + A -> All Transforms, this resets all object parameters, I use this option to reset the modified mesh so that the modifiers work on it correctly.
Unfortunately, this caused the axes of the mesh (which was rotated) to be set to the initial global coordinates, which is the reason why RetopoFlow built the symmetry incorrectly.

I beg your pardon, I don't know how I could have overlooked such a detail.
On the other hand, it would be great if you could set an arbitrary axis by specifying several vertices as reference ones.

**Comment by jlampel** [comment]
Glad that's working for you! I'll close this out for now, and we can come back to a more general approach to symmetry in the future. 

Oh, and to get that local rotation back, try selecting a face or edge that's pointing in the right direction and using this tool: https://github.com/jlampel/orient_to_selection
