### ISSUE TITLE
How to install RetopoFlow for Blender 3.2.1?

### ISSUE THREAD

**Issue by Jacksonmodel** [CGCookie/retopoflow#1140]
How to install RetopoFlow for Blender 3.2.1?
I've downloaded the file and extracted it on Desktop, but I can't find it in Blender Preferences.

**Comment by vxlcoder** [comment]
Hi, @Jacksonmodel.

You will need the _original_, officially packaged zip file to install RetopoFlow in Blender.  Do not extract it, and also don't try to re-compress to zip.  Sometimes different operating systems will do weird things with the files when creating a zip file, and Blender expects the zip file to have a particular structure.

Similar to installing any other Blender, start Blender, click through Edit > Preferences... > Add-ons > Install..., then browse to the original zip file, and hit OK.

Please let us know if you have any other problems.

**Comment by jlampel** [comment]
Closing this out as it's not a RF issue, but if you still need help feel free to comment
