### ISSUE TITLE
UI BUG! [BUG]

### ISSUE THREAD

**Issue by wangxiao0075** [CGCookie/retopoflow#1143]
**`UI BUG!`** txt can`t be showed correctly, pls check it out **XD!**

![1657865591689](https://user-images.githubusercontent.com/5772230/179162427-c8ebe2b0-1d54-4d9c-8e45-fd3f6f6e98d7.png)

- [BUG ] ````

**Comment by vxlcoder** [comment]
Thanks for the report, @wangxiao0075.

This seems very similar to issue #1135.

Can you give us a few more details?

- which OS are you using?
- Blender version?  RF Version?
- Has RF worked fine before, but now it isn't?  if so, how long ago did it change, and what do you recall you did at that time?  (ex: updated RF, updated graphics drivers, etc)
- Can you try adjusting the `Resolution Scale` in Edit > Preferences > Interface? 
![image](https://user-images.githubusercontent.com/3790699/179210194-46bc16c7-18d7-462f-8c03-f68fc63f42f9.png)
- Can you try adjusting the `UI Scale` in RetopoFlow > Options > General (top-most drop-down) > Interface > UI Scale? 
![image](https://user-images.githubusercontent.com/3790699/179210454-fc50de74-3660-4ac1-a3dc-c3c99bb0e0af.png)

Thank you for helping us debug this issue!

**Comment by wangxiao0075** [comment]
> Thanks for the report, @wangxiao0075.
> 
> This seems very similar to issue #1135.
> 
> Can you give us a few more details?
> 
> * which OS are you using?
> * Blender version?  RF Version?
> * Has RF worked fine before, but now it isn't?  if so, how long ago did it change, and what do you recall you did at that time?  (ex: updated RF, updated graphics drivers, etc)
> * Can you try adjusting the `Resolution Scale` in Edit > Preferences > Interface?
>   ![image](https://user-images.githubusercontent.com/3790699/179210194-46bc16c7-18d7-462f-8c03-f68fc63f42f9.png)
> * Can you try adjusting the `UI Scale` in RetopoFlow > Options > General (top-most drop-down) > Interface > UI Scale?
>   ![image](https://user-images.githubusercontent.com/3790699/179210454-fc50de74-3660-4ac1-a3dc-c3c99bb0e0af.png)
> 
> Thank you for helping us debug this issue!



> Thanks for the report, @wangxiao0075.
> WIN11
> This seems very similar to issue #1135.
> 
> Can you give us a few more details?
> 
> * which OS are you using?
> * Blender version?  RF Version?
> * Has RF worked fine before, but now it isn't?  if so, how long ago did it change, and what do you recall you did at that time?  (ex: updated RF, updated graphics drivers, etc)
> * Can you try adjusting the `Resolution Scale` in Edit > Preferences > Interface?
>   ![image](https://user-images.githubusercontent.com/3790699/179210194-46bc16c7-18d7-462f-8c03-f68fc63f42f9.png)
> * Can you try adjusting the `UI Scale` in RetopoFlow > Options > General (top-most drop-down) > Interface > UI Scale?
>   ![image](https://user-images.githubusercontent.com/3790699/179210454-fc50de74-3660-4ac1-a3dc-c3c99bb0e0af.png)
> 
> Thank you for helping us debug this issue!


ohch！ thanks for reply so quick , @vxlcoder

> WIN11
> Blender 3.2.1
> I `ve changed language but not work yet.
> Both 3.2.7 and 3.2.8  are all this bug ( i have not  install other version yet ) 
> Let me try your suggestion 
> i`ll issue whether it work.
> Thanks for your awsome work on this project

**Comment by wangxiao0075** [comment]
E......@vxlcoder
I found some intersting thing bro
when i use 1,0 /1.1/ 1.2 /1.4 /1.5/1.6 /1.7/2.0 /2.2 /2.4/2.8  (only tried this range)   **menu is work**
when i use 1.3/1.8 **menu is not work**
hope this test can help u  XD
