### ISSUE TITLE
I have a problem with this addon,at first i did not experience such a problem then when i closed blender and i decided to open it again and immediately i clicked on the add retopo to active object it will load a retopoflow-rotate empty that will not allow me to retopologize the surface of my mesh. Have tried many fixes to it but it is still the same problem. Please i would like to know a solution tho this issue . Thank you! : )

### ISSUE THREAD

**Issue by ninjax-codes2004** [CGCookie/retopoflow#1146]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Hi @ninjax-codes2004.

Be sure to use `Ctrl+LeftMouse` to create new geometry.

There are more details in the help (press `F1` or visit docs.retopoflow.com)

If I misunderstood your issue, let me know.

**Comment by ninjax-codes2004** [comment]
Thanks it solved my issue

**Comment by vxlcoder** [comment]
great!

Happy retopo'ing!
