### ISSUE TITLE
View Jumping Back When Manually Saving & "Finish Auto Save Recovery" Scaling Down Mesh [BUG]

### ISSUE THREAD

**Issue by iminurwalls** [CGCookie/retopoflow#1147]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.2.8

Blender Version/Hash: 3.2.2

Platform Version/Distribution: Blender Market

&nbsp;

**Issue:**

When in RetopoFlow, if you try to manually save (Ctrl+S), your field of view will jump back/zoom out abruptly and your work will not be saved unless you exit RetopoFlow; overlays seen in Edit Mode will also flash every time you hit Ctrl+S. Also, if you select "Finish Auto Save Recovery," your target mesh will drastically scale down.

&nbsp;

**How to Reproduce: 
For Manual Save Problem - Select target mesh, once in RetopoFlow, hit Ctrl+S. 
For Auto Save Recovery Problem - Create some geometry in RetopoFlow, exit, click the drop-down on RetopoFlow menu, select "Finish Auto Save Recovery."**

For Manual Save Problem: 1. Select target mesh, 2. Open RetopoFlow, 3. Press Control then "S" on your keyboard
For Auto Save Recovery Problem: 1. Create some geometry in RetopoFlow, 2. Exit, 3. Click the drop-down on the RetopoFlow menu, 4. Select "Finish Auto Save Recovery."

https://user-images.githubusercontent.com/110753728/183298056-95e54649-b139-4662-b7ab-0854152ab949.mp4

**Comment by vxlcoder** [comment]
thanks for the report, @iminurwalls.

We are currently working on this issue. It is partially fixed right now in the unreleased `v3.3.0` branch (still working on recovery system).  we will release this update as soon as it is ready, but you can test it out now by using the updater system to download branch `v3.3.0` (see https://docs.retopoflow.com/addon_updater.html).

**Comment by iminurwalls** [comment]
Hi @vxlcoder, thanks for the reply. I am able to install v3.3.0 of RetopoFlow as an add on but I can't enable it in Blender.

**Comment by vxlcoder** [comment]
Hmm... let's try this.

Start Blender as usual, but then open the system console (see https://docs.retopoflow.com/debugging.html#:~:text=the%20terminal%20/%20console.-,Windows,-Start%20Blender%20as).  Then, try enabling / starting RetopoFlow.  Lots of text will show up in the console that can give us hints as to why it's not working on your machine.  Select _all_ that text (you might need to scroll) and paste it here as a reply.

Thank you for helping us debug this issue!  We'll get you up and running as quickly as possible!

**Comment by iminurwalls** [comment]
Okay, so I had to download the .zip directly because auto-update failed when I tried to use the updater system.

**This is what showed up in the console from installation of v3.3.0 to attempting to enable it:**

Read prefs: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
addon_utils.disable: retopoflow-3.3.0 not disabled
Modules Installed (retopoflow-3.3.0) from 'C:\\RetopoFlow\\retopoflow-3.3.0.zip' into 'C:\\Users\\grays\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'retopoflow-3'

**This is the end of what the console had in the attempt described above.**

I tried this next attempt because I noticed that the top level folder inside the .zip was titled "retopoflow-3.3.0" instead of just "retopoflow."

**This is what showed up in the console from installation of v3.3.0 to attempting to enable it after changing the top level folder inside the .zip from "retopoflow-3.3.0" to "retopoflow":**

Read prefs: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
addon_utils.disable: RetopoFlow not disabled
Modules Installed (RetopoFlow) from 'C:\\RetopoFlow\\RetopoFlow.zip' into 'C:\\Users\\grays\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\__init__.py", line 84, in <module>
    update_based_on_hive()
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\__init__.py", line 58, in update_based_on_hive
    from .addon_common.hive.hive import Hive
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\hive\hive.py", line 3, in <module>
    from ..common.blender import get_path_from_addon_root
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\__init__.py", line 56, in <module>
    from . import debug as _
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\debug.py", line 41, in <module>
    from .blender import show_blender_popup
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\blender.py", line 368, in <module>
    class BlenderIcon:
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\blender.py", line 370, in BlenderIcon
    path_icons = get_path_from_addon_root()   # default to add-on root
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\blender.py", line 351, in get_path_from_addon_root
    assert len(modules) == 1, f'Could not find root for add-on containing {path_here}: {modules}'
AssertionError: Could not find root for add-on containing C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common: []

Exception ignored in: <function ImagePreviewCollection.__del__ at 0x00000207F65B8D30>
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\bpy\utils\previews.py", line 66, in __del__
    raise ResourceWarning(
ResourceWarning: <ImagePreviewCollection id=0x207f659a020[0], <super: <class 'ImagePreviewCollection'>, <ImagePreviewCollection object>>>: left open, remove with 'bpy.utils.previews.remove()'

**Comment by vxlcoder** [comment]
That's really frustrating.  sorry that you're having these issues.

I'm looking into that last bit right now

**Comment by vxlcoder** [comment]
Ok, @iminurwalls, try this version: https://www.dropbox.com/s/e2n3ikarenznwtd/RetopoFlow_v3.3.0-alpha-GitHub.zip?dl=0

I've packaged it as a zip to make it easier on your end.

**Comment by iminurwalls** [comment]
Unfortunately v3.3.0 still can't be enabled.

### **This is what the console said:**

Read prefs: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
addon_utils.disable: RetopoFlow not disabled
Modules Installed (RetopoFlow) from 'C:\\RetopoFlow\\RetopoFlow_v3.3.0-alpha-GitHub.zip' into 'C:\\Users\\grays\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow: Initial load
RetopoFlow git: None
gpustate.gpu_info cannot get shader version!
RetopoFlow options path: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\RetopoFlow_options.json
No options file
Addon Common: (bmesh_render) GLSL Version: NVIDIA Corporation, NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 516.59, (no shader version)
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.2\3.2\scripts\modules\addon_utils.py", line 335, in enable
    mod = __import__(module_name)
  File "C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\__init__.py", line 461, in <module>
    elif not configoptions.retopoflow_product['cgcookiue built']: rf_label_extra = " (self)"
KeyError: 'cgcookiue built'

**Comment by vxlcoder** [comment]
ah, a typo that I haven't run across yet.

Let's try this again: https://www.dropbox.com/s/e2n3ikarenznwtd/RetopoFlow_v3.3.0-alpha-GitHub.zip?dl=0

And, again, thank you for you patience and help with debugging this!

**Comment by iminurwalls** [comment]
You're welcome. Thanks for your quick replies.

I was able to enable RetopoFlow, open it, and add some geometry. Then I manually saved my work (Ctrl+S) and noticed it still has that "jumping back" issue with the view. I did not get the "Finish Auto Save Recovery" prompt. 

### **This is what the console said:**

Read prefs: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
Read blend: M:\Lessons\Blender\Sculpting Course\02_Fish Character\02_Fish_Reto2.blend
addon_utils.disable: RetopoFlow not disabled
Modules Installed (RetopoFlow) from 'C:\\RetopoFlow\\RetopoFlow_v3.3.0-alpha-GitHub.zip' into 'C:\\Users\\grays\\AppData\\Roaming\\Blender Foundation\\Blender\\3.2\\scripts\\addons'
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow: Initial load
RetopoFlow git: None
gpustate.gpu_info cannot get shader version!
RetopoFlow options path: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\RetopoFlow_options.json
No options file
Addon Common: (bmesh_render) GLSL Version: NVIDIA Corporation, NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 516.59, (no shader version)
cgcookie addon: Verbose is enabled
cgcookie addon: Wrote out updater JSON settings with content:
cgcookie addon: {'last_check': '', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
RetopoFlow keymaps path: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\RetopoFlow_keymaps.json
RetopoFlow: storing clip distances: 0.009999999776482582 1000.0
RetopoFlow: storing view: <Vector (-0.1627, 0.8551, 0.0397)> 4.18310022354126
RetopoFlow: computing unit scaling factor
  Unit scaling factor: 4.908540012380468
RetopoFlow: scaling to unit box
RetopoFlow: scaling to factor=4.908540012380468, view='SCALE', clip='OVERRIDE', mesh='SCALE'
Addon Common: Loaded font id=3: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\fonts\DroidSans-Blender.ttf
RetopoFlow: Pausing help image preloading (1659907109.3522103)
RetopoFlow: Setting up target mesh (0.010008573532104492)
RetopoFlow: Setting up source mesh(es) (0.004003047943115234)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures (0.003001689910888672)
RetopoFlow: Setting up rotation target (0.0030019283294677734)
RetopoFlow: Setting up RetopoFlow states (0.013047218322753906)
RetopoFlow: Setting up RetopoFlow tools (0.010852575302124023)
RetopoFlow: Setting up grease marks (0.002002239227294922)
RetopoFlow: Setting up visualizations (0.011572837829589844)
RetopoFlow: Setting up user interface (0.015453815460205078)
RetopoFlow: Setting up undo system (0.3965487480163574)
RetopoFlow: Checking auto save / save (0.0710608959197998)
RetopoFlow: Checking target symmetry (0.008006811141967773)
RetopoFlow: Loading welcome message (0.013463735580444336)
Addon Common: Loaded font id=4: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\fonts\OpenSans-Bold.ttf
Addon Common: Loaded font id=5: C:\Users\grays\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\RetopoFlow\addon_common\common\fonts\DejaVuSansMono.ttf
RetopoFlow: Resuming help image preloading (0.34064221382141113)
RetopoFlow: done with start
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
Info: Saved "02_Fish_Reto2.blend"
RetopoFlow: scaling to unit box
RetopoFlow: scaling to factor=4.908540012380468, view='SCALE', clip='OVERRIDE', mesh='SCALE'
RetopoFlow: saved to M:\Lessons\Blender\Sculpting Course\02_Fish Character\02_Fish_Reto2.blend
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
Info: Saved "02_Fish_Reto2.blend"

### **This part of the console is from when I manually saved and the "jumping back"/"zooming out" problem occurred:**

RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
Info: Saved "02_Fish_Reto2.blend"
RetopoFlow: scaling to unit box
RetopoFlow: scaling to factor=4.908540012380468, view='SCALE', clip='OVERRIDE', mesh='SCALE'
RetopoFlow: saved to M:\Lessons\Blender\Sculpting Course\02_Fish Character\02_Fish_Reto2.blend

### **This part of the console is from when I exited RetopoFlow:**

RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'
RetopoFlow: unscaling from unit box
RetopoFlow: scaling to factor=1.0, view='RESTORE', clip='RESTORE', mesh='RESTORE'

Not sure if any of that helps but I thought it might be interesting for solving that problem in the future.

**Comment by vxlcoder** [comment]
that's very strange. would you mind doing another screen capture of the jump and maybe sending us your blend file? you can send it to retopoflow@cgcookie.com.

**Comment by iminurwalls** [comment]
It's been sent.

**Comment by vxlcoder** [comment]
thank you! I will to take a look as soon as I can.

**Comment by borco** [comment]
I'm also experiencing this with:

* Blender 3.2.2 (macOS/M1)
* RetopoFlow v3.2.8

For me it is enough to:

* select existing retopoflow mesh
* enter *Edit* mode
* in the *RetopoFlow* menu, select *Start RetopoFlow*
* exit the *RetopoFlow* without doing anything

At this point:

* the scale of the target mesh and the *RetopoFlow* mesh still have a **scale** set to `1`
* *RetopoFlow* menu shows an *Auto Save* warning and there is a button to *Finish Auto Save Recovery*

Clicking that button will mess the things up and both my target and the retopoflow meshes are to **0.266**.

If I once again repeat the above steps, the scale is further reduced to something even smaller (0.019), after clicking the *Finish Auto Save Recovery*.

Trying to install the v3.3.0 branch as suggested above didn't work for me, but using the zip from dropbox worked ok and this bug looks to be fixed there for me.

**Comment by iminurwalls** [comment]
Yes, the "Finish Auto Save Recovery" issue seems to be resolved in v3.3.0 for me as well.
I'm curious to know if you, @borco, are experiencing your field of view "jumping back"/"zooming out" when you manually save (Ctrl+S) while working in RetopoFlow?
That problem has yet to be resolved for me, but I know @vxlcoder is working on it.

**Comment by vxlcoder** [comment]
@iminurwalls, I have found and fixed the issue with view jumping on save!

please try this version, and let me know if it works for you. https://www.dropbox.com/s/e2n3ikarenznwtd/RetopoFlow_v3.3.0-alpha-GitHub.zip?dl=0

I still have more work to do on the auto save recovery feature, but saving _should_ be correct now.

**Comment by iminurwalls** [comment]
It worked :) thank you so much. I'm very excited to continue using RetopoFlow as I think it is a great tool, but developers like you are what make it so good. Thanks again.

**Comment by vxlcoder** [comment]
glad to hear!  will go ahead and close this issue, even though the auto save recovery is still being worked on.  let us know if you have any more issues.  and, if you have a moment, we'd appreciate a review on the Blender Market.

@borco, if the version I linked above (same as `v3.3.0` branch) does not resolve your issue, will you please open a new issue with the details you gave above?

happy retopo'ing!

**Comment by iminurwalls** [comment]
Done.

**Comment by borco** [comment]
@vxlcoder the latest download works ok for me (btw, there is another annoying thing: when exiting the retopoflow editor, the screen flutters/flickers for a couple of seconds. not sure if this is an issue with the retopoflow, macos, blender on M1, Metal, my monitor/cables..., but i haven't seen it happening with other plugins programs so far...; pls let me know if i should make a ticket for this)

@iminurwalls i haven't seen any zoom issue after saving inside the retopoflow editor while using 3.2.8; the only problem was that retopoflow reported that it has to recover and after the recover, the scalling was completely messed up...

**Comment by vxlcoder** [comment]
@borco, please open a new ticket for the flicker. if possible, can you record a video of it? it would be best to record a screen capture as opposed to a camera pointed at screen. I am thinking it is the m1, since that new chip/machine has given me all sorts of weird issues in my experience. I have an m1 that I can test on, too.

as for the recovery, I am hoping to get that resolved this week.

**Comment by borco** [comment]
@vxlcoder i've made ticket #1148, but couldn't make any good recording of the issue: i've try using both my old iphone and recording the screen, but the flicker is not visible on either of these. unfortunately, i have no other way to record this issue...

**Comment by iminurwalls** [comment]
@borco you can download and use OBS to record your screen, which is a free, open source software that is mac and windows compatible.

**Comment by vxlcoder** [comment]
thank you for trying, @borco. frankly, the m1 has been a pain to work with. we have worked around all sorts of issues with it already, including a very strange crashing bug (their glsl implementation of discarding a fragment inside a switch statement was/is? broken). I ended up buying an m1 just to run tests and debug. will take a closer look at it.
