### ISSUE TITLE
Cannot draw in Contours in 2.75

### ISSUE THREAD

**Issue by Italic-** [CGCookie/retopoflow#115]
I'm running Blender from git hash 68d72e2 and cannot draw loops in Contours. I can use it in 2.74 release, so I've been using that. From what I know, the py API has changed in 2.75, so this might be a manifestation of that change. 

These are my output from console and error popup from within Blender. 
http://www.pasteall.org/59385/text - It looks like it's the same line repeating.
http://www.pasteall.org/pic/show.php?id=90256
![contours_output](https://cloud.githubusercontent.com/assets/3143630/8510479/ec1ab15c-229b-11e5-8fe2-ed6f1daa0882.jpg)

**Comment by vxlcoder** [comment]
thanks for the report, @Italic-!  we're going to be taking a look at 2.75 this coming weekend.

**Comment by carter2422** [comment]
@patmo141 I suspect this has been fixed in the refactor. Can you verify?

**Comment by carter2422** [comment]
@Italic- could you try this version of RetopoFlow and see if it's working in 2.75 for you now? https://www.dropbox.com/s/69x2sxkpadg9tzp/retopoFlow-1.1.0alpha2.zip?dl=0

**Comment by Italic-** [comment]
Seems to still be giving me errors. http://www.pasteall.org/59545

EDIT: I had to reload blender after saving new version as default. It allows me to cut again in 2.75a release. I haven't gone through the whole thing to check, but at least it's letting me cut and confirm now. Thanks guys!

**Comment by carter2422** [comment]
@Italic- I suspect the issue was due to some temporary data getting left behind that RetopoFlow was then still trying to read from.
