### ISSUE TITLE
Viewport Angle not working at all in Retopoflow

### ISSUE THREAD

**Issue by TofuLad69** [CGCookie/retopoflow#1150]
Retopoflow Version: 3?

Blender Version/Hash: 2.93.4

Platform Version/Distribution: Microsoft Surface Pro 5 (Windows 10 OS)

&nbsp;

I cannot change the angle of my viewport in Retopoflow. Any time I drag the cursor, literally nothing happens, leaving me a very awkward angle.
I have all default settings btw.
The only way that I have been able to change the angle is with the number keys. And even then it hasn't helped much.
I would really appreciate it if someone knew how to help me.

&nbsp;

**Comment by vxlcoder** [comment]
hi @TofuLad69.

what is your keymap setting for viewport move and rotate?

we haven't had issues with most standard settings, but maybe your setup is different.

**Comment by TofuLad69** [comment]
@vxlcoder
I've mostly just been trying to use my trackpad, like I've normally used in vanilla blender. It's seemed to work on other people's computers so I don't know why I'm the only person with this problem.

**Comment by vxlcoder** [comment]
hmmm. the trackpad should work fine, but not sure why not for you, yet.

here are a few things to try:

- try loading factory defaults (file > defaults), enable RF, then try it.
- does it work with mouse?
- try using RF, exit, open system console (window > toggle system console), then copy _all_ the text you have in there (could be a lot!) and paste it here.

thanks for helping us debug this! we will get you up and running as quickly as we can!

**Comment by TofuLad69** [comment]
it still doesn't work in factory default settings. 
I also do not have a mouse for my laptop.
but here is the text that appears when I toggle system console.

Read prefs: C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\config\userpref.blend
RetopoFlow: Initial load
Addon Common: (shaders) GLSL Version: 4.50 - Build 27.20.100.8682
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow Shader Info: uiShader (22)
  attribs:
  uniforms: uMVPMatrix (5), left (0), right (1), top (3), bottom (2), width (12), height (15), depth (4), margin_left (6), margin_right (7), margin_top (9), margin_bottom (8), padding_left (13), padding_right (14), padding_top (16), padding_bottom (17), border_width (11), border_radius (10), border_left_color (23), border_right_color (21), border_top_color (20), border_bottom_color (22), background_color (24), using_image (25), image_fit (19), image (18)
RetopoFlow git: None
RetopoFlow options path: C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\RetopoFlow_options.json
Addon Common: (bmesh_render) GLSL Version: Intel, Intel(R) Iris(R) Plus Graphics 640, 4.5.0 - Build 27.20.100.8682, 4.50 - Build 27.20.100.8682
cgcookie addon: Verbose is enabled
cgcookie addon: Read in JSON settings from file
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
RetopoFlow keymaps path: C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\RetopoFlow_keymaps.json
RetopoFlow: setting up scaling factor
  Unit scaling factor: 0.2
RetopoFlow: scaling view, sources, and target by 5.00
RetopoFlow: storing clip distances: 0.009999999776482582 1000.0
ERROR 1/10 (UI_Document.draw: start): invalid enum
  File "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\cookiecutter\cookiecutter_ui.py", line 117, in postpixel
    try: self.document.draw(self.context)
  File "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\ui_document.py", line 688, in draw
    Globals.drawing.glCheckError('UI_Document.draw: start')
  File "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\decorators.py", line 208, in callit
    ret = fn(*args, **kwargs)
  File "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\drawing.py", line 510, in glCheckError
    traceback.print_stack()
Addon Common: Loaded font "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\fonts\DroidSans-Blender.ttf" as id 3
RetopoFlow: Pausing help image preloading (1660607621.1607976)
RetopoFlow: Setting up target mesh (0.11884450912475586)
RetopoFlow: Setting up source mesh(es) (0.03637337684631348)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures (0.021718978881835938)
RetopoFlow: Setting up rotation target (0.02212047576904297)
RetopoFlow: Setting up RetopoFlow states (0.030725955963134766)
RetopoFlow: Setting up RetopoFlow tools (0.019588708877563477)
RetopoFlow: Setting up grease marks (0.017256498336791992)
RetopoFlow: Setting up visualizations (0.016769886016845703)
RetopoFlow: Setting up user interface (0.021077871322631836)
RetopoFlow: Setting up undo system (0.6764552593231201)
RetopoFlow: Checking auto save / save (0.027585744857788086)
Addon Common: Loaded font "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\fonts\OpenSans-Italic.ttf" as id 4
Addon Common: Loaded font "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\fonts\DejaVuSansMono.ttf" as id 5
RetopoFlow: Checking target symmetry (0.053829193115234375)
RetopoFlow: Loading welcome message (0.02740764617919922)
Addon Common: Loaded font "C:\Users\hgaco\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\retopoflow-master\addon_common\common\fonts\OpenSans-Bold.ttf" as id 6
RetopoFlow: Resuming help image preloading (0.8348839282989502)
RetopoFlow: done with start
RetopoFlow: scaling view, sources, and target by 0.20
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
Bad characters found in add-on: {'-'}
RetopoFlow: setting up scaling factor
  Unit scaling factor: 0.2
RetopoFlow: scaling view, sources, and target by 5.00
RetopoFlow: storing clip distances: 0.009999999776482582 1000.0
RetopoFlow: Pausing help image preloading (1660607731.8788908)
RetopoFlow: Setting up target mesh (0.13118505477905273)
RetopoFlow: Setting up source mesh(es) (0.03889155387878418)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures (0.029217958450317383)
RetopoFlow: Setting up rotation target (0.024957895278930664)
RetopoFlow: Setting up RetopoFlow states (0.03484916687011719)
RetopoFlow: Setting up RetopoFlow tools (0.025079727172851562)
RetopoFlow: Setting up grease marks (0.019898176193237305)
RetopoFlow: Setting up visualizations (0.02397894859313965)
RetopoFlow: Setting up user interface (0.024632930755615234)
RetopoFlow: Setting up undo system (0.6577579975128174)
RetopoFlow: Checking auto save / save (0.07871365547180176)
RetopoFlow: Checking target symmetry (0.05689263343811035)
RetopoFlow: Loading welcome message (0.06283211708068848)
RetopoFlow: Resuming help image preloading (0.6662387847900391)
RetopoFlow: done with start
RetopoFlow: scaling view, sources, and target by 0.20

**Comment by TofuLad69** [comment]
also, not sure if this is related, but this error message has been showing up.
![image](https://user-images.githubusercontent.com/93833206/184756098-8ca54b5a-7813-4350-814e-476998620ef3.png)

**Comment by vxlcoder** [comment]
perfect, thanks!  i've noticed a few things, but nothing seems to point to why the trackpad isn't working, though.  i'll dig around in my code a bit to see what i can find (i'm currently working on a big change in that area right now anyways).  in the mean time...

I missed you're using Blender 2.93.  the latest verson of RF _should_ still work in 2.93, but I haven't tested recently.  Are you able to try RF out in a later version of Blender, like Blender 3.2?

I also noticed that you've pulled RF from GitHub, but you used the download button from the main page.  this causes issues, as GitHub packages those zip files in ways that can cause problems in Blender.  that's why we give the "Invalid add-on folder name" warning.  it's better to install officially packaged versions either from https://blendermarket.com/products/retopoflow or from https://github.com/CGCookie/retopoflow/releases.  Can you try one of officially released versions, say 3.2.8 or 3.2.7?

**Comment by vxlcoder** [comment]
you _might_ need to install version 3.2.4 or 3.2.5, though.  again, I haven't tested against blender 2.93 in a while.

**Comment by TofuLad69** [comment]
Okay then. thanks for letting me know! I'm gonna download it from the github link you shared since that one is free. Do I have to download the source code with it too? Also, do you recommend that I upgrade to a newer version of blender?

**Comment by jlampel** [comment]
From https://github.com/CGCookie/retopoflow/issues/1166 
> I have had this issue before in the past and it's come up again right as I started using Blender again. For whatever reason, I cannot move the viewport display at all in Retopoflow, so I end up getting stuck at really awkward angles and it's getting really frustrating at this point. I have the most recent versions of both Blender (3.3.1) and Retopoflow (3.2.9) so I don't understand why this bug even exists for me. The worst part about this is that it almost seems like I am the only person with this problem, so I have absolutely no way of troubleshooting this.

Is there any chance that you could share a file where this is happening? You can email it to us at retopoflow@cgcookie.com if you don't want it public. 

Two things to check:

- Is it possible that a key is being accidentally held down somehow while navigating? A stuck key on a keyboard can really cause some confusion here and would make navigation not work as expected. 
- It's a long shot but try turning off Hide Overlays and Automatically Adjust View Clipping in the options under Viewport Display to check if anything in the scene is somehow blocking the navigation. Sometimes zooming in really close to an object can slow the navigation to molasses even if that object is transparent due to backface culling, which we have enabled for performance. 

To answer the previous question, you do not need to download the source code as well - just the .zip from the releases page. It shouldn't matter which Blender version you're on as long as it's later than 2.93, though testing with the latest stable version (3.3) is always helpful.

**Comment by jlampel** [comment]
Closing since it's been several months since the last follow-up, and we recently supported more input devices in the upcoming 3.4.0 version. Do let us know if this continues to be an issue.
