### ISSUE TITLE
3.2.8 in blender 3.2.1 use Contours will get Stuck

### ISSUE THREAD

**Issue by tiantianaixuexi** [CGCookie/retopoflow#1153]
3.2.8 in blender 3.2.1 use Contours will get Stuck

When I click Ctrl to draw the first line and let go, it will get stuc

https://user-images.githubusercontent.com/31758095/186597782-c32c79a0-d17b-4cec-9c51-e2c31e51e96e.mp4

**Comment by jlampel** [comment]
Closing this out as I tried replicating the issue with the same shape and possible variations with holes in the mesh, flipped normals, subdivision surfaces, and custom normals, but I didn't get any hanging. The issue appears to be fixed, but if it comes up again, please feel free to re-open the issue. Providing the file as an example would be a huge help!
