### ISSUE TITLE
[BUG] v3.3.0 - Strokes brush creates extra geometry when changing vertex count twice

### ISSUE THREAD

**Issue by Roonschot** [CGCookie/retopoflow#1154]
Retopoflow Version: v3.3.0 (9th of August 2022)

Blender Version/Hash: 3.2.2 & 3.3 

Platform Version/Distribution: Windows

&nbsp;

**Issue:**

When having made a stroke with the "Strokes" brush, changing the vertex count by scrolling spawns in new edges with the vert count of the desired scroll, after changing it twice. This makes the brush largely unusable.

This also applies to Strokes that extend faces/patches.

![bug](https://user-images.githubusercontent.com/26141033/188615460-1535d595-67ea-4dba-bf05-1fb67f0ebda8.png)

&nbsp;

**How to Reproduce:**

- Make a line with the Strokes brush, hold shift and scroll twice in either direction to change the count and have said additional geometry spawn in, when it shouldn't. 100% reproduction rate for me.

**Comment by vxlcoder** [comment]
Thanks for the report and great details, @Roonschot!

I'll take a look at this.

**Comment by vxlcoder** [comment]
so sorry this took so long!  this issue should now be fixed in commit d322b87!

**Comment by jlampel** [comment]
Tested and confirmed fix on my end 👍
