### ISSUE TITLE
[BUG] Target mesh is scaled up largely, when reopening an earlier retopo project

### ISSUE THREAD

**Issue by GMJ80** [CGCookie/retopoflow#1157]
**[BUG] Target mesh is scaled up largely, when reopening an earlier retopo project**

Retopoflow Version: 3.2.8

Blender Version/Hash: 3.2

Platform Version/Distribution: Win10

I've just started to use Retopoflow and at the first project I'm having the following issue. Started to get around with the tools in the addon and properly exited from the file when finished (no crash happened). When reopened the file, the target mesh scaled up about 3-4 times (with Scale value=1). Also I have a warning in Retopoflow about a possible AutoSave problem. It suggests to chose "Finish AutoSave Recovery", what actually scales down the target properly, but at the same time it scales down the source mesh as well, at a similar rate. If I don't use this step, but instead try to snap the vertices on the source, they do snap back on the surface, but their placement is really off.

Could you help perhaps what may cause this issue? Thank you

![image](https://user-images.githubusercontent.com/113591169/190366457-4c031dae-1aa8-4593-aaec-9e73d2e5cf10.png)

**Comment by jlampel** [comment]
One frequent scaling issue was fixed recently, so I would bet that this is fixed, but scaling issues can always come up if RetopoFlow manages to fully crash before it has a chance to correct the scale while exiting. The real cause would be whatever caused that crash. If that ever happens again, please let us know! There will be an error log saved that could help us diagnose the problem.
