### ISSUE TITLE
[BUG] Target mesh jumps off the source mesh after "Undo" or when decreasing the number of segments (with the use of "Strokes" tool)

### ISSUE THREAD

**Issue by GMJ80** [CGCookie/retopoflow#1158]
[BUG] Target mesh jumps off the source mesh after "Undo" or when decreasing the number of segments (with the use of "Strokes" tool)

Retopoflow Version: 3.2.8

Blender Version/Hash: 3.2

Platform Version/Distribution: Win10

**Issue:**

When creating a new line of edges with "Strokes" tool, the target mesh jumps off from the source mesh, either at
- "Undo" (I did not save the file just before chosing "Undo", as I read it was a known bug in previous versions) or
-  when decreasing the number of segments of the newly created strip

The target mesh can be moved back to its original place, if I undo the last operations, but not only the last one, but maybe even 5-6 steps. Thus my new topology evolutes backwards, I'm losing several earlier created steps, which I need to recreate again, what can be really annoying after the 4-5 consecutive attempt.

Thank you if you could help me in this issue.

![image](https://user-images.githubusercontent.com/113591169/190405900-ec1fa851-767f-487f-89c2-8d95a8675b68.png)

**Comment by vxlcoder** [comment]
Thaanks for the report, @GMJ80, and I'm sorry for such a delayed response and for the trouble this issue causes!

I _believe_ this is fixed in the latest official version of retopoflow (v3.2.9).

Could you try downloading the latest version?

**Comment by jlampel** [comment]
Closing this out as it should be solved, but please open it back up if the issue comes up again in the latest version.
