### ISSUE TITLE
[BUG] Error message when enabling: "path should be string, bytes, os.PathLike or integer, not None Type"

### ISSUE THREAD

**Issue by BlueSaved** [CGCookie/retopoflow#1160]
[BUG]

Retopoflow Version: 3.2.9

Blender Version/Hash: 3.3

Platform Version/Distribution: Windows 11 64bit

&nbsp;

**Issue:**

After installing Retopoflow in Blender Add-ons, I clicked the checkbox to activate it and received the following error message:

> Python: Traceback (most recent call last):
> File "C:\Program Files\Blender Foundation\Blender3.3\3.3\scripts\startup\bl_operators\userpref.py", line 432, in execute mod = addon_utils.enables(self.module, default_set=True, handle_error=err_cb)
> File "C:\Program Files\Blender Foundation\Blender3.3\3.3\scripts\modules\addon_utils.py", line 287, in enable if mod and os.path.exists(mod.__file__):
> File "C:\Program Files\Blender Foundation\Blender3.3\3.3\python\lib\genericpath.py", line 19, in exists os.stat(path)
> TypeError: stat: path should be string, bytes, os.PathLike or integer, not None Type

I couldn't find any known bugs for Retopoflow specifically, but after some research I found out this was an odd Python library issue that's cropped up for several people across numerous programs and development environments. I'm a scripting amateur at best, so I didn't want to edit libraries, and I suspected uninstalling Python might work. After uninstalling my Python console and launcher (version 3.1 I believe), removing the add-on, restarting Blender, then reinstalling the add-on, I was able to enable Retopoflow. Here's a screenshot of the error message, if that's somehow helpful:

![image](https://user-images.githubusercontent.com/113970321/191190645-d2037ab9-cc8e-4cfd-a3be-85a74960eabb.png)

&nbsp;

**How to Reproduce:**

- Install Python console and launcher, version 3.1
- Open Blender, install Retopoflow add-on
- Attempt to enable the Retopoflow add-on, error should appear

**Comment by vxlcoder** [comment]
Do you have any other details, @BlueSaved?

**Comment by vxlcoder** [comment]
closing this issue for now, but please reopen if you have more details.  thanks!

**Comment by gentlecolts** [comment]
I am encountering this same issue in Blender 3.5, retopoflow  3.3.0, on Manjaro linux

**Comment by gentlecolts** [comment]
For me, it seems to have resolved itself, possibly having been due to some stale state.  The full steps of what I went through are as follows:

- Install retopoflow in an earlier version of blender.
- Update blender to 3.5
- Retopoflow functions as expected
- Use retopoflow's built in check-for-updates feature, this produces the error in this ticket
- Try manually installing the update from zip, same issue
- Remove retopoflow, restart blender, re-install from zip
- Issue appears to be gone
