### ISSUE TITLE
Input not working when Retopo is active.**[BUG]**

### ISSUE THREAD

**Issue by RemoBlockade** [CGCookie/retopoflow#1163]
Retopoflow Version: {*3.2.9*}

Blender Version/Hash: {*3.3.0*}

Platform Version/Distribution: {*Windows 10 *}

**I start up RetopoFlow, but when I try to use it my input no longer works on the mane editing screen. I can select the different tools, and even pan and zoom. but i can't edit my object at all. it wont draw on my figure at all and it wont let me close out of the program. Ill have to use the task manager to end Blender so i can re start. It wont let me switch modes. I have uninstalled and reinstalled blender and turned most of my other addon's off to see if there was a conflicting issue between addon's, but nothing seams to work. Knowing me its probably something silly I am missing.**

**Comment by vxlcoder** [comment]
Thanks for the report @RemoBlockade.  Sorry for our late reply!

When you start RF, did you try using `Ctrl+LeftMouse` to create geometry with the tools?  To exit, you _should_ be able to press `Tab` or click the Exit button from the RF menu.

**Comment by vxlcoder** [comment]
closing this issue for now.  please reopen if you have more details on your particular issue.  thanks!
