### ISSUE TITLE
Viewport still isn't working

### ISSUE THREAD

**Issue by TofuLad69** [CGCookie/retopoflow#1166]
I have had this issue before in the past and it's come up again right as I started using Blender again. For whatever reason, I cannot move the viewport display at all in Retopoflow, so I end up getting stuck at really awkward angles and it's getting really frustrating at this point. I have the most recent versions of both Blender (3.3.1) and Retopoflow (3.2.9) so I don't understand why this bug even exists for me. The worst part about this is that it almost seems like I am the only person with this problem, so I have absolutely no way of troubleshooting this.

**Comment by jlampel** [comment]
Hi, sorry to hear that it's still been an issue! It looks like the previous bug report https://github.com/CGCookie/retopoflow/issues/1150 is still open - i'll pick up the conversation over there to keep things organized.
