### ISSUE TITLE
cursor in the tweak mode

### ISSUE THREAD

**Issue by BenderBlender** [CGCookie/retopoflow#1169]
the cursor in the tweak mode closes the entire view, can it be turned off somehow (make it in the form of a thin line without orange highlight elements or Alpha)?

**Comment by jlampel** [comment]
I'm not sure I fully understand, could you please post a screenshot or describe how it closes the view? Is it very large and covering too many vertices and at full strength / opacity? What size are you using it at?

**Comment by vxlcoder** [comment]
commit 0881265 adds options that can control the alpha (opacity) of the brushes.  i'm not sure if this was what @BenderBlender was requesting, but it made enough sense to add it.

**Comment by jlampel** [comment]
Tested and it works great. It may be worth updating the brush visualization to match what Blender does now since it's changed since ours were implemented, but it won't be worth it until after RF 4 is more fleshed out.
