### ISSUE TITLE
PolyPen move point in one click function

### ISSUE THREAD

**Issue by BenderBlender** [CGCookie/retopoflow#1170]
It is very annoying to have to first click on a point to select it, and only then is it possible to move it. I would like to be able (for example, when pressing Alt or some other key ("1")) to immediately move the points without having to wait for the selection function to work.

**Comment by jlampel** [comment]
It would be good to explore new ideas for keymaps before the next large update, but in the meantime, you can hold C and use the tweak brush while in any mode. It's not exactly the same but fairly close and quick to use. Closing this out since it's a duplicate request. It's on our radar!
