### ISSUE TITLE
Crash when Tweak or Relax falloff is set to 0

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1171]
Setting the brush falloff to 0 and clicking and dragging in the viewport will crash RetopoFlow and Blender. 
Reported via BM: https://blendermarket.com/inbox/conversations/81765

**Comment by vxlcoder** [comment]
should be fixed in commit ac5c9e1!

**Comment by jlampel** [comment]
Confirmed fixed!
