### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by kyushu** [CGCookie/retopoflow#1172]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.9
- CG Cookie built for Blender Market
- Blender: 3.03.1 master 2022-10-04
- Platform: Windows, 10, 10.0.22000, AMD64, Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, 4.5.0 NVIDIA 522.25, (no shader version)
- Timestamp: 2022-10-30 14:20:12.101025
- Undo: 

Error Hash: 8d9cb813011211ccf7a3cdb3cbd65d38

Trace:

- EXCEPTION (<class 'ReferenceError'>): StructRNA of type VIEW3D_OT_RetopoFlow_LastTool has been removed
-     F:\Blender_Versions\stable\blender-3.3.1+lts.b292cfe5a936\3.3\scripts\modules\bpy_types.py
- 000 0813:__getattribute__() properties = StructRNA.path_resolve(self, "properties")
-     C:\Users\morpheus\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RetopoFlow\retopoflow\rf\rf_drawing.py
- 001 0052:callback() self.rftarget_draw.replace_opts(target_opts)
-     C:\Users\morpheus\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RetopoFlow\config\options.py
- 002 0436:call_callbacks() for callback in self._callbacks: callback()
- 003 0459:update_external_vars() self.call_callbacks()
- 004 0464:dirty() self.update_external_vars()
- 005 0425:__setitem__() self.dirty()
-     C:\Users\morpheus\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RetopoFlow\retopoflow\rf\rf_tools.py
- 006 0061:select_rftool() if not quick: options['quickstart tool'] = rftool.name
-     <string>
- 007 0001:<module>() 
-     .../common\utils.py
- 008 0165:run_it() return exec(action, f_globals, nf_locals)
- 009 0170:run_it() raise e
-     .../common\ui_core.py
- 010 2068:_fire_event() cb(details)
- 011 2074:_fire_event() raise e
- 012 2105:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_properties.py
- 013 1049:_checked_change() self.dispatch_event('on_input')
- 014 1043:checked() self._checked_change()
-     .../common\ui_elements.py
- 015 0754:on_click() self.checked = True
-     .../common\ui_core.py
- 016 2068:_fire_event() cb(details)
- 017 2074:_fire_event() raise e
- 018 2105:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_elements.py
- 019 0726:mouseclick() ui_for.dispatch_event('on_mouseclick')
-     .../common\ui_core.py
- 020 2064:_fire_event() cb(details)
- 021 2074:_fire_event() raise e
- 022 2101:dispatch_event() cur._fire_event(event, ui_event)
-     .../common\ui_document.py
- 023 0555:mousedown_exit() under_mouseclick.dispatch_event('on_mouseclick')
-     .../common\fsm.py
- 024 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @kyushu!  i'm not sure how to reproduce this.  can you provide more details on what caused this error?  are you able to reproduce it?

**Comment by vxlcoder** [comment]
@kyushu, are you able to reproduce this error using the latest version of RetopoFlow (temp link: https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0)? I have not been able to replicate this error.
