### ISSUE TITLE
could not save RetopoFlow

### ISSUE THREAD

**Issue by Adambekow** [CGCookie/retopoflow#1173]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
Warning: Could not save 

---
Please prefix your issue name with one of the following: [BUG]

Retopoflow Version: {*3.2.9*}

Blender Version/Hash: {*3.3.0*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Could not save blend file**

{*Unable to save an unsaved file with an empty or unset "filepath" property
[retopoflow-master.zip](https://github.com/CGCookie/retopoflow/files/9898915/retopoflow-master.zip)
[copyright.txt](https://github.com/CGCookie/retopoflow/files/9898918/copyright.txt)
*}

{*![image](https://user-images.githubusercontent.com/117067290/198953632-ea000837-b708-4a68-b9a2-6bc1a8771170.png)*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Hi @Adambekow.

This warning is telling you that the file that you're working on has not been saved before.  Note: this is not an error, meaning that nothing is broken, but it is warning you to make sure you save your work.

The best way to correct this is to exit RetopoFlow, save your file, then enter RetopoFlow again and continue working.

Please let us know if you have any other questions or problems.  Thanks!
