### ISSUE TITLE
**[BUG]** Source mesh incorrectly marked as unused

### ISSUE THREAD

**Issue by akomili** [CGCookie/retopoflow#1174]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {3.2.9}

Blender Version/Hash: {3.3.1}

Platform Version/Distribution: {Windows 10}

&nbsp;

**Issue:**

{Hello

I've been retopologizing a character for a while successfully but suddenly it decided to stop working. Every time I try to start Retopoflow I get an immediate "unexpected crash" error and Retopoflow doesn't start. I tried taking one of the meshes out of the Blender file and pasted it into a fresh Blender file, however in that one I don't even get the option to start Retopoflow, it says "no sources detected" and sometimes also "setup issue"

Any ideas what might be causing this?

Thanks
Amy
}

{
![image](https://user-images.githubusercontent.com/76419082/201994162-0bea7f2e-3192-43db-abda-338e738c4778.png)
![image](https://user-images.githubusercontent.com/76419082/201994310-8ff2c178-78d2-41e5-95b5-3f0d483543bb.png)

}

&nbsp;

**How to Reproduce:**

- {No idea why it started doing this}

{I have a Blender file I can send you, it won't let me attach it here}

**Comment by vxlcoder** [comment]
Thanks for the report, @akomili!

can you try emailing us the .blend file at retopoflow@cgcookie.com?

**Comment by vxlcoder** [comment]
@akomili, i hope i didn't miss you email.  could you try emailing it again?

**Comment by jlampel** [comment]
I've simplified the file down to just two objects that demonstrate the issue:

[retopoflow_detection_issue.zip](https://github.com/CGCookie/retopoflow/files/10356531/retopoflow_detection_issue.zip)

For whatever reason, RetopoFlow put an Unused tag on the custom properties of all the objects and deleting that will allow RF to detect them:

![image](https://user-images.githubusercontent.com/12982300/210907829-cf2443db-d1ea-4f79-9354-ddc62a0b6cbd.png)

**Comment by akomili** [comment]
Thank you! Just got around to testing this and it works once I remove that
custom property. Really appreciate your awesome support :)

**Comment by vxlcoder** [comment]
glad it is now fixed!  closing this issue.  please let us know if you continue to have problems.

happy retopoing!
