### ISSUE TITLE
Unable to select target

### ISSUE THREAD

**Issue by Sulivar** [CGCookie/retopoflow#1175]
It's all in the title, in general I always manage to manage but there impossible to do anything.

I can't select the target by following the instructions in the guide provided with the addon.

I select the target in object mode then new Target at cursor or new targeter at active but nothing seems to work.
In both cases, I have the poly count at zero and I can't modify anything.

In target display and cleaning, I tried all the possible paths but it doesn't work to score there.

**Comment by vxlcoder** [comment]
hi, @Sulivar.

after you click new target, does RetopoFlow start up?  if not, let us know.  but if it does, try using Ctrl+LMB to create geometry with the selected tool.

**Comment by Sulivar** [comment]
Thank you, that was it, I'm just a jerk, it was the first addon I bought for my studies that's why I backed out :) neck it works now.

**Comment by vxlcoder** [comment]
glad to hear!

happy retopo'ing

**Comment by Sulivar** [comment]
Thanks.

I haven't found a conclusive tutorial yet, I think it must be a new addon. I spent an evening on it without much success.

I'm going to settle for the basic sculpting while waiting for it to be better known.
