### ISSUE TITLE
Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by satantamere** [CGCookie/retopoflow#1178]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- Blender: 2.90.0 master 2020-08-31
- Platform: Windows, 10, 10.0.22621, AMD64, AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
- GPU: ATI Technologies Inc., AMD Radeon RX 6800 XT, 4.5.0 Core Profile Context 22.8.2.220819, 4.60
- Timestamp: 2022-12-15 12:55:20.359426
- Undo: insert, insert, select, select, insert, insert, select, select, select, select

Error Hash: 0d90719e24ae5f3ce7a1e4651806d66f

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'merge'
-     C:\Users\satan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\retopoflow-master\retopoflow\rftool_knife\knife.py
- 000 0381:_insert() cur.merge(bmv)
-     C:\Users\satan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\satan\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\retopoflow-master\retopoflow\rftool_knife\knife.py
- 002 0246:insert() return self._insert()
-     .../common\fsm.py
- 003 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @satantamere.  Sorry for the late response!

I saw that you're using RF 3.1.0, which is a very old version of RF.  I believe this bug was already fixed.  Since you're using Blender 2.90, you can try using RF 3.2.4.

I'm closing this issue for now, but feel free to reopen if this bug continues even when using RF 3.2.4.

Thanks!
