### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Eilinger** [CGCookie/retopoflow#1180]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.9
- CG Cookie built for Blender Market
- Blender: 3.03.1 master 2022-10-04
- Platform: Windows, 10, 10.0.19044, AMD64, AMD64 Family 25 Model 33 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3070/PCIe/SSE2, 4.5.0 NVIDIA 527.37, (no shader version)
- Timestamp: 2023-01-07 08:50:39.367582
- Undo: 

Error Hash: 7219be82d192c7240b189b71f56843f5

Trace:

- EXCEPTION (<class 'AssertionError'>): 
-     C:\Users\Anwender\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\RetopoFlow\retopoflow\retopoflow.py
- 000 0211:setup_next_stage() assert False
-     .../common\fsm.py
- 001 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by Eilinger** [comment]
bought retopoflow an its crashing an all i wanna do ... help

**Comment by vxlcoder** [comment]
sorry for your troubles, @Eilinger .

can you try opening the terminal and copying all the text that's printed there when RetopoFlow crashes and pasting it here?  see https://docs.retopoflow.com/debugging.html for details.

will take a look at this tomorrow or Monday.

thanks!

**Comment by vxlcoder** [comment]
@Eilinger, are you able to provide any more information?  I tried replicating this error (using Blender 3.3.1), but I was unable to cause it.
