### ISSUE TITLE
New Target at Active creates target at 3D Cursor instead

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1181]
It looks like RetopoFlow is creating all new targets at the 3D Cursor regardless of which option is selected. 

Steps to reproduce:
1. Move the 3D Cursor away from the center of the active object
2. Start RF by creating a new target at the active object 

I glanced through rf_target.py `setup_target()` and rf_blender_objects.py `create_new_target()` (which looks like duplicated code from rf_blender.py?) but didn't find where the location and rotation of the new object is set. Maybe it's not and that's the issue?

Reported here: https://blendermarket.com/inbox/conversations/89080

**Comment by vxlcoder** [comment]
commit f2fa8d3 fixes this!

**Comment by jlampel** [comment]
Confirmed fixed!
