### ISSUE TITLE
**[BUG]** View rotation loses pivot when nothing selected. 

### ISSUE THREAD

**Issue by Geo4TH** [CGCookie/retopoflow#1182]
Retopoflow Version: 3.2.9 (from Github)

Blender Version/Hash: 3.4.1/55485cb379f7

Platform Version/Distribution: Windows 10 pro 5120x1440 display (window size does not seems to affect the issue)

**Issue**

When in RF, if I deselect everything, view rotation defaults to the whole mesh, as opposed to the pivot remaining the on last selected object. This is particularly an issue when very close to an object.

https://youtu.be/xouAxUJtP8E

This may not be a bug. If not, I'd like to see an option to add the ability for RF to remember/use the previous pivot when nothing is selected.

**Comment by vxlcoder** [comment]
Thanks for the report @Geo4TH.

This is an issue when Blender's `Orbit Around Selection` is enabled.

I've added an option to make orbitting in RF similar to Blender's default, but you will lose the ability to press numpad period to center on all the sources when the option is changed.

![image](https://user-images.githubusercontent.com/3790699/216789980-076181d1-b5c9-4dec-b7d2-73f9ab62af0a.png)

**Comment by Geo4TH** [comment]
Thank you. Look forward to checking this out

**Comment by jlampel** [comment]
I don't generally use Orbit Around Selection, but this option does make it behave as requested when that's enabled, and I can see how that could be useful.
