### ISSUE TITLE
Part of source mesh disappears? Or becomes transparent? 

### ISSUE THREAD

**Issue by Starshotte** [CGCookie/retopoflow#1183]
<img width="502" alt="Screenshot 2023-01-23 at 14 32 00" src="https://user-images.githubusercontent.com/75481043/214075391-8815ead6-83a9-4123-b37c-ed2ba1d800c9.png">

Edit Mode: Mesh is solid as sculpted 

<img width="485" alt="Screenshot 2023-01-23 at 14 33 14" src="https://user-images.githubusercontent.com/75481043/214075499-6fa67421-1e7b-48af-ada2-f4e366735e9d.png">
<img width="454" alt="Screenshot 2023-01-23 at 14 33 06" src="https://user-images.githubusercontent.com/75481043/214075566-6a636604-d744-4f01-914d-b7f4bcfbc11f.png">

Retopoflow: Unsure why only this part of the mesh loses form and density...?

**Comment by vxlcoder** [comment]
hi @Starshotte.

it looks like the normals on the source are facing inwards. RF will enable blackface culling by default (can be disabled), which would make your source appear to lose geometry. you can check the normals by editing the source and enabling face orientation viewport overlay option (see https://docs.blender.org/manual/en/latest/editors/3dview/display/overlays.html). if the faces turn red, then your normals are facing the wrong direction. select all, then recalculate normals (see https://docs.blender.org/manual/en/latest/modeling/meshes/editing/mesh/normals.html)

let us know if this isn't the case, and we'll go from there.

thanks!

**Comment by Starshotte** [comment]
> hi @Starshotte.
> 
> it looks like the normals on the source are facing inwards. RF will enable blackface culling by default (can be disabled), which would make your source appear to lose geometry. you can check the normals by editing the source and enabling face orientation viewport overlay option (see https://docs.blender.org/manual/en/latest/editors/3dview/display/overlays.html). if the faces turn red, then your normals are facing the wrong direction. select all, then recalculate normals (see https://docs.blender.org/manual/en/latest/modeling/meshes/editing/mesh/normals.html)
> 
> let us know if this isn't the case, and we'll go from there.
> 
> thanks!

Hi @vxlcoder, thank you for getting to this so quickly! 

On the source mesh itself, all the normals turn blue, including on the problem area itself. This was an import from Nomad Sculpt, but was joined _in_ Blender, if that helps at all?

**Comment by Starshotte** [comment]
> https://docs.blender.org/manual/en/latest/modeling/meshes/editing/mesh/normals.html

Hi @vxlcoder, 

Sorry to do this; I had the wrong settings selected. You were right: it was the normals. 

I've recalculated them and they seem to have turned blue on the problem area: Wish me luck!

**Comment by vxlcoder** [comment]
glad that solved the problem!

when you get a chance, we would appreciate reading your review of RF on the Blender Market.

happy retopo'ing!
