### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Gn0sis89** [CGCookie/retopoflow#1189]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.9
- Self built
- Blender: 3.04.1 blender-v3.4-release 2022-12-19
- Platform: Windows, 10, 10.0.19044, AMD64, Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 528.24, (no shader version)
- Timestamp: 2023-02-08 18:22:35.726526
- Undo: 

Error Hash: 28cf64e2ba8a573f81acf8a1bf755c82

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-     C:\Users\roger\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0122:select() return self.bmelem.select and not self.bmelem.hide
-     C:\Users\roger\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 001 0233:main() elif self.nearest_geom and self.nearest_geom.select:
-     .../common\fsm.py
- 002 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Gn0sis89.  commit 22e88e8 _should_ fix this issue.

note: this issue is difficult to reproduce, so i cannot test the fix thoroughly.  please reopen issue if the problem continues.

Thanks!
