### ISSUE TITLE
Strokes changes previous topology when changing spans

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1191]
The strokes tool will alter topology that is not part of the current stroke when you:

- Draw a stroke
- Extend that stroke
- Change the span count
- Extend that new patch with a stroke
- Change the span count again 

![blender_ZrP1CMpGWY](https://user-images.githubusercontent.com/12982300/218878922-a58c81a1-88b1-409b-8907-b0260d58f177.gif)

**Comment by vxlcoder** [comment]
this issue should be fixed in commit 2a27b22

**Comment by jlampel** [comment]
Confirmed fixed!
