### ISSUE TITLE
[BUG] Unable To Detect Source/Target

### ISSUE THREAD

**Issue by Paciris** [CGCookie/retopoflow#1192]
Retopoflow Version: 3.2.9

Blender Version/Hash: 3.2.0

Platform Version/Distribution: Windows 10

**Issue:**

Retopoflow unable to detect any source/target [source issue: no sources detected]. When in either object or edit mode, even if only the object is selected, the "create at cursor/active" buttons are grayed out. Unknown what caused the issue, but I created a new blend file and copy/pasted the previous meshes only with no retopoflow objects in order to start over.

Due to the lack of a "trigger" for the issue, I don't believe console output is necessary. The problem is apparently a setup issue.

I'm guessing it has something to do with the issue I had with the initial blend file (base_female_3.3), where I had created a face retopology using retopoflow, but wanted to create a separate retopology for the body only to get some kind of error about the autosave. If needed, I can upload this other blend file as well.

![image](https://user-images.githubusercontent.com/99859509/219274794-267638d1-9b9a-41a2-a1cf-a7c693aea94c.png)

**How to Reproduce:**
Blend file attached below
[base_female_3.4.zip](https://github.com/CGCookie/retopoflow/files/10752412/base_female_3.4.zip)

**Comment by vxlcoder** [comment]
thanks for the report, @Paciris.

having multiple targets shouldn't be an issue. I'm not sure why RF isn't detecting the source.

if you could upload your blend file, that would be very helpful in debugging this issue. you can email to retopoflow@cgcookie.com if you'd like.

**Comment by jlampel** [comment]
My guess is that it got marked as unused, like in this issue: https://github.com/CGCookie/retopoflow/issues/1174 

Does the source object have a custom property that looks like this? 
![image](https://user-images.githubusercontent.com/12982300/219426962-2cfc5d5f-2689-4f47-bf65-b2885cecd6ac.png)

**Comment by Paciris** [comment]
@jlampel 

This seems to have been the issue, changing the tag to "source" fixes it, but I guess I didn't see that ticket since the title was pretty niche. Thanks for your assistance.

**Comment by vxlcoder** [comment]
there was a reason a long time ago that I have since forgotten. will dig through the code to find and remove it.
