### ISSUE TITLE
Ripping edges and vertices

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1195]
At the moment, I don't believe we have a way to rip edges and vertices in RetopoFlow. Ripping is an important action in retopology since it's the fastest way to add a gap between two loops. 

![image](https://user-images.githubusercontent.com/12982300/223882308-987baaac-3341-48b3-878a-1e6f8d03165e.png)

To match Blender, all tools should rip with the V key:
![blender_opGlMVuued](https://user-images.githubusercontent.com/12982300/223883351-2b42c772-2758-40ec-8701-0b35fac7d9e3.gif)

And rip fill with Alt+V:
![blender_z8dvWUhWub](https://user-images.githubusercontent.com/12982300/223883372-c5327287-16fa-49f8-b118-2ccad13c033b.gif)

I added the tag v4 to clarify that it's not a priority for RF 3x.

**Comment by vxlcoder** [comment]
this is a bit tricky, because `bmesh` does not have an equivalent set of operators, especially with fill.

the closest i found are `face_vert_separate` ([doc](https://docs.blender.org/api/current/bmesh.utils.html#bmesh.utils.face_vert_separate)) and _maybe_  `loop_separate` ([doc](https://docs.blender.org/api/current/bmesh.utils.html#bmesh.utils.loop_separate)), although documentation for `loop_separate` seem to be a copy-paste from `face_vert_separate`.

**Comment by vxlcoder** [comment]
also, i'm not entirely sure how blender makes decisions on what to rip.

for example, what _should_ happen if i press `V` here?

![image](https://github.com/CGCookie/retopoflow/assets/3790699/2cf65b04-edd9-432e-adfb-08966541d3fd)

**Comment by vxlcoder** [comment]
here is a very _simple_ implementation.

![simple rip](https://github.com/CGCookie/retopoflow/assets/3790699/fb21365f-6656-453e-b364-2d6831c2726c)

**Comment by vxlcoder** [comment]
it works only on a single selected edge that is adjacent to exactly two faces, and it rips that edge and verts completely away from surround geometry.  note: this is different from what blender does, which involves a lot more work.

**Comment by jlampel** [comment]
That's still great! Most of the time I use it it's in very simple situations like one edge only connected to two faces. Would it be a quick thing to add this shortcut to the other tools as well so it's not just in PolyPen?

**Comment by vxlcoder** [comment]
done!
