### ISSUE TITLE
Automatic Decimation

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1199]
For objects > 1 million polygons, we could add a decimate modifier with a percentage set so that the total is < 1 million. In the vast majority of cases, this will increase performance a good bit while not affecting the resulting retopology at all. Since the change is done via a modifier, it's completely non-destructive and can be reverted upon exiting. The downside is the increased start up time. Whether or not this would be useful, though, depends on how performant RetopoFlow 4 turns out to be.

**Comment by vxlcoder** [comment]
might be worth adding a section of optimization options (RF Blender menu, RF add-on options, RF options menu).

other optimization options along with this option:

- Viewport: hide overlays, hide header, hide panels
- Shading: Light / Dark / Off
- View Clipping: automatic
- etc.

if RF goes more integrated, these options can be executed by button click to "Optimize for Retopo Work" or something like that.

**Comment by vxlcoder** [comment]
Unfortunately, adding a Decimate modifier has two big issues:

- If the source has a subdiv modifier, following up with decimate modifier just undoes this, but jankier.
- Adding a decimate modifier makes startup _much_ slower, especially when the ratio is very low (ex: 0.01).

I believe the reason for the latter issue is how Blender's depgraph evaluates.  It is overly eager to re-evaluate with (nearly) any scene change, which includes showing / hiding target mesh.  Testing on a mesh from issue #1216 (originally 3k faces, 390k after mirror and subdiv modifiers), decimating by 0.01 ratio reduces the faces back down to 7k, but also adds ~5sec delay to startup.  We could use a lower ratio, but I don't think the tradeoff will be worth it in the end.

In the end, it might be better do one of the following:

- rework RF's rendering system
- just use Blender's retopo overlay when it is ready
- inform the artist with ways to prep their meshes for a good retopo session
