### ISSUE TITLE
Updating gedges with fixed counts is jumpy

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#12]
When gedge has fixed segment count, updating (by moving a gvert) can cause the segmentation to act erratically and cut non-uniformly.

![image](https://cloud.githubusercontent.com/assets/3790699/5599878/d6dac382-9294-11e4-984c-3bfa8e13bed8.png)

**Comment by patmo141** [comment]
confirmed, still a bit of an issue

**Comment by vxlcoder** [comment]
closing
