### ISSUE TITLE
Optimize Shading doesn't revert when turned off

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1200]
Optimize Shading no longer switches back to the user's custom shading settings when turned off. It will retain the settings if RetopoFlow is enabled while it is off, but if you switch to Light or Dark and then back to Off, it will just stay at Light or Dark.

**Comment by jlampel** [comment]
Ok, it looks like this is from `self.shading_restore` being removed from `rf_ui.py` and `cookiecutter_blender.py` in the current 3.3.0 alpha. It's also the cause of #1196. @vxlcoder do you remember which issue that change was related to?

**Comment by vxlcoder** [comment]
this should be fixed now

**Comment by jlampel** [comment]
Fix confirmed!
