### ISSUE TITLE
x axis while in symetry out of place

### ISSUE THREAD

**Issue by MelonMannn** [CGCookie/retopoflow#1201]
**[BUG]**

Retopoflow Version: {*3.3.0*}

Blender Version/Hash: {*3.4*}

&nbsp;

**Issue:**

*so while i was working with this addon, i tried doing the symetry and set it to the x axis, but the axis seemed off:*
![Screenshot (78)](https://user-images.githubusercontent.com/128430972/226480894-546d3696-a595-49e3-bcbc-06ebac11e614.png)

*so i thought it was me who put the model at the wrong place so i went out of retopoflow, but turns out the model was in the right place:*
![Screenshot (79)](https://user-images.githubusercontent.com/128430972/226481049-468c9ae0-de30-4ac6-82cd-5e7771b32ede.png)

*Am i doing something wrong, how come no one has gotten this problem other than me? i thought it was one of my addons, but none of them affected the symetry. Please help me out, i cant progress any further on my model without this bug fixed :(*

**Comment by MelonMannn** [comment]
nevermind, suddently when i start the retopoflow at the cursor, it solves everything

**Comment by jlampel** [comment]
Hi, the X axis symmetry is based on the origin point of the new retopo object that gets created when you choose one of the New Target options. It can either be placed at the 3d cursor or at the active object. Whichever one was selected in this case was not at 0 along the global X axis. Try setting the cursor to world origin and then creating a new target at the cursor. That should do it!

**Comment by MelonMannn** [comment]
> Hi, the X axis symmetry is based on the origin point of the new retopo object that gets created when you choose one of the New Target options. It can either be placed at the 3d cursor or at the active object. Whichever one was selected in this case was not at 0 along the global X axis. Try setting the cursor to world origin and then creating a new target at the cursor. That should do it!

thank you!
