### ISSUE TITLE
BUG, Retopoflow does not install in Blender

### ISSUE THREAD

**Issue by Kelvins120** [CGCookie/retopoflow#1202]
BUG
-----------------------------------

---

Retopoflow Version: {*3.3.0*}

Blender Version/Hash: {*3.0*}

Platform Version/Distribution: {*Mac Os*}

&nbsp;

**Issue:**

*Retopoflow does not install in Blender, I get the message below and then Retopoflow (Broken) appears. I have already tried to reinstall and download several times, I am downloading it from github. Is rare. By the way, how much does the zip file weigh? When I download it, its weight is 12.7 Mb, is it okay?*

![Captura de Pantalla 2023-03-26 a la(s) 10 36 49 p  m](https://user-images.githubusercontent.com/74762586/227828357-66ea9fa5-7534-4a80-b8e3-0a67256c9ae5.png)

&nbsp;

**Comment by vxlcoder** [comment]
thanks for the report, @Kelvins120.

two things:

first, i somewhat recently started using `match` in some parts of the code.  `match` was introduced in python 3.10, but blender 3.0 uses python 3.9.  so, i'll discuss if we should introduce a version break so we can use python 3.10 features or if we'll switch back to using only python 3.9 features.  in the meantime, you can try using an earlier version of RF.

second, it looks like you downloaded RF from the Code dropdown on the GitHub page.  this can cause problems, where the zip that GH creates contains `-` in the name (notice: `scripts/addons/retopoflow-master/...` in your screenshot).  this can cause problems.  instead, download directly from the Blender Market and support future development or download from the [RF GitHub Releases](https://github.com/CGCookie/retopoflow/releases), where the zip files are built correctly.

**Comment by wsoulless** [comment]
Update Blender to the latest verison and see if the addons works (reinstall the addon on the new blender's version if necessary).

**Comment by bch77** [comment]
Seems like it might be a Blender 3.5.0 problem? Was working in earlier versions, but I noticed in 3.5 that Retopoflow (earlier version) was causing View Display options not to appear in Object and Edit views, and also was not activating. I updated to RT 3.3.0, and now the View Display options appear correctly, but RT will not run (as described above).

**Comment by vxlcoder** [comment]
commit cab0455 improves compatibility with previous versions of blender (2.93--3.2).  note: soon, RF will need to break away from some backwards compatibility due to some upcoming breaking changes in Blender's Python API (bpy).
