### ISSUE TITLE
[BUG] HARD Crashing on Zoom-In/Out

### ISSUE THREAD

**Issue by desertpogona** [CGCookie/retopoflow#1203]
Retopoflow Version:  3.29 (3.30 refuses to install)

Blender Version/Hash:  Happens on any version between 3.0 and 3.5.0

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**
Crashing when Zooming In/Out
After a certain point, and not very far into manually retopoing, without fail, this program will eventually crash blender hard by doing something as simple as zooming in and out within the plugin, while using whatever tools. There doesn't seem to be any actual trigger other than zooming in and out. There isn't an error or crash log. Blender just freezes forever.

I've ran into this issue possibly a hundred times by now, by no exaggeration, and I'm surprised no one else has said anything. I'm not pushing the limits of the plugin at all. I'm really confused, because this is supposed to support up to 100k tris and I am absolutely not pushing that. I'm not even pushing 20k as far as I'm aware. This is a weirdly consistent crash regardless.

This completely disrupts my workflow and makes all my progress erased because I have to close Blender once the crash occurs. It does not recover. I've left it for hours and it doesn't come back, and its not recoverable. This makes this otherwise great but rather expensive software unreliable and unusable for me, sadly. I'm at a loss how to proceed. I am hoping someone can provide insight. 

I'm not savvy with Github bug reports, so I'll try to include a screenshot of the crash. I don't really know what else to do to give you more information, but this happens to me a lot.

I have a 3080 and an i9-13900k and 64 gigs of RAM. This cannot be right.

I'm on version 3.29 because 3.30 will not install in Blender as of this time, no matter what version I use. I see there is an issue open about that right now. I was hoping 3.30 would address this issue, but I see nothing in the notes about it. 

![image](https://user-images.githubusercontent.com/20937179/229958268-3e0111d6-d0a0-4fe9-bcbc-1863daa5c517.png)

&nbsp;

**How to Reproduce:**
Zoom in and out after working on a manual retopo for a while. I wish i had more information.

**Comment by desertpogona** [comment]
I managed to generate a crashlog using Blender's Debug Log feature. I don't know if this will help, but i reproduced the crash again.
[blender_debug_output.txt](https://github.com/CGCookie/retopoflow/files/11154482/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/CGCookie/retopoflow/files/11154483/blender_system_info.txt)

**Comment by vxlcoder** [comment]
thanks for the report, @desertpogona!

will take a look as soon as I can

**Comment by desertpogona** [comment]
I appreciate that.
I can safely say I can reliably reproduce this by simply zooming in and out rapidly with a knife tool (for example) out being dragged along the model as it zooms in and out. Maybe it's because I'm holding ctrl while I'm zooming sometimes, but I don't see how that would add up to a crash. I'm really not sure what exactly is the trigger here. I can make it happen consistently now under a minute by zooming in and out like that.
Crash logs seem... sparse. As far as I can tell they don't say much.
I'm not sure if it's the tools themselves that cause this, because it doesn't seem to correlate. It seems to happen with any tool. I have also disabled many plugins to test this since that last one, and it doesn't matter if say CATS is disabled or VRM software. I have disabled them all and it still occurs, so I don't know if it's a plugin conflict.

I hope you can figure it out. Feel free to ask me any questions.

**Comment by vxlcoder** [comment]
@desertpogona, i scanned through the logs and didn't see anything useful there (as you noted).

we did recently fix a performance issue that _might_ be related to this issue.

would you mind trying out the latest version of RetopoFlow v3.3.1 to see if you continue to have issues?  You can use this temp link to download a premade zip: https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0

thanks!

**Comment by jlampel** [comment]
I was able to trigger this behavior pretty easily in the previous version, but not in 3.3.1. It seems impossible to cause now since the visualization no longer updates during navigation. Nice find!
