### ISSUE TITLE
[BUG] Can't add vertices with `+` key (german keyboard)

### ISSUE THREAD

**Issue by ngreve** [CGCookie/retopoflow#1205]
Retopoflow Version: 3.3.0

Blender Version/Hash: 3.5.0

Platform Version/Distribution: Arch Linux 

&nbsp;

**Issue:**

I will explain the issue using the `Contours` tool.
Normally, when you create a line of edges using the `Contours` tool, you can hit the `-` key to decrease the resolution, so, remove vertices, or hit the `+` key to increase the resolution, by adding vertices.

I am using a german keyboard and adding vertices with the `+` key does not work.
On the other hand, removing vertices with the `-` key does work. 

`Shift`+`Drag` does not seem to work either.

&nbsp;

**How to Reproduce:**

See issue description

**Comment by vxlcoder** [comment]
@ngreve, were you able to run the test above?

**Comment by ngreve** [comment]
Sorry for the late response. I've sent the email just now. Maybe you have your reasons why you want me to sent you the logging result via email, but just so you know, I have no problem with just copy and pasting the logging results here.

**Comment by vxlcoder** [comment]
@ngreve, thanks for the file!  the RetopoFlow keymap editor should be able to allow you to customize the keymaps in this way, but I'm unable to reproduce on my US QWERTY keyboard.  but, I went ahead and added the key as a default in RetopoFlow.  it _shouldn't_ interfere with other keymaps.  you can try it using this temp link: https://www.dropbox.com/s/o4dof9jjqmhszuk/RetopoFlow_v3.3.1-GitHub.zip?dl=0  please let me know if that worked for you!

**Comment by vxlcoder** [comment]
thank _you_ for your help, @ngreve!

if you haven't yet, we'd appreciate a review on the [blender market](https://blendermarket.com/products/retopoflow).

happy retopo'ing!
