### ISSUE TITLE
Polys unelectable after being placed

### ISSUE THREAD

**Issue by RobertjlRea** [CGCookie/retopoflow#1207]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.3.30

Blender Version/Hash: 3.5

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**

This has only started today but when I am trying to use retopo flow im unable to select polys after placing them it seems to go inside the model or looks as if its under the model when ever its placed ive tried changing the displace modifer but same issue.

![image](https://user-images.githubusercontent.com/19908952/231257551-fa6cbd8e-42d1-4891-b55f-cb3f9e9d4e02.png)

![image](https://user-images.githubusercontent.com/19908952/231257998-2456e68d-b117-469a-ac1a-1c10ed789c2a.png)

&nbsp;

**How to Reproduce:**

- Honestly All I do is use retopoflow and the issue happens

{*attach any files needed to replicate the issue*}

**Comment by RobertjlRea** [comment]
Thank you for the quick reply and the advice it seems that didnt work fully, the normals are point out correctly,

![image](https://user-images.githubusercontent.com/19908952/231271416-5323bfd3-3325-4fc3-9698-be3970d78c4b.png)

strange thing is that the poly normals  point the correct way when its being worked on if i scale it and move it it works without the block back face clicked aswell 

![image](https://user-images.githubusercontent.com/19908952/231272135-6fea70af-7591-4ff2-b229-7c4cb91de6f9.png)

Its just strange as it was working the last few days and this just happened.
Okay just figured it out, It seems if you import OBJ instead of OBJ legacy it creates that issue 
as you can work on the highpoly no problem when imported as obj legacy

**Comment by vxlcoder** [comment]
weird. will check out the obj import options, but it really shouldn't matter how it's imported, though.

just to be clear, did the disable occluded or backfacing options help?

**Comment by vxlcoder** [comment]
checking again, @RobertjlRea, did you try disabling occluded or backfacing options in RF?  thanks!

**Comment by RobertjlRea** [comment]
My apologises been very busy recently, I did  disable the back face and
works fine it seems that  it just didn't like the importing of obj file as
it worked with fbx which was werid.

**Comment by vxlcoder** [comment]
@RobertjlRea, i'm glad to hear this is working again!

I'm now sure why importing from OBJ should make a difference, unless the OBJ import code is doing something weird / incorrect with normals.  This is likely the case, since everything works as expected when the mesh is imported differently.  If you are able to, you can share the obj file with us by emailing to retopoflow@cgcookie.com and we take a closer look.

I'm going to close this issue for now, but let us know if you continue to have issues.

happy retopo'ing!
