### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by RRRagul** [CGCookie/retopoflow#1214]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.2.6
- CG Cookie built for GitHub
- Blender: 3.01.2 master 2022-03-31
- Platform: Windows, 10, 10.0.19043, AMD64, Intel64 Family 6 Model 142 Stepping 9, GenuineIntel
- GPU: Intel, Intel(R) HD Graphics 620, 4.5.0 - Build 24.20.100.6344, (no shader version)
- Timestamp: 2023-04-19 22:37:11.834400
- Undo: extrude strip, select, select, relax, move grabbed, create strip, select, select, move grabbed, select

Error Hash: a7910f86332cd6323380afb2ef1fa4f9

Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0355:<listcomp>() verts = [v for v in self.bmelem.verts if v in bme.verts]
- 001 0355:shared_vert() verts = [v for v in self.bmelem.verts if v in bme.verts]
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes_utils.py
- 002 0135:get_strip_verts() vs.append(e0.shared_vert(e1))
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 003 0900:extrude_equals() side_verts = get_strip_verts(edges1)
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 004 0150:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 005 0422:stroke() if self.replay: self.replay()
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 006 0109:_callback_tool() fn(self.rftool, *args, **kwargs)
- 007 0133:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\HP\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 008 0099:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 009 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @RRRagul.

I believe this issue should be fixed in RetopoFlow 3.2.7, but I did just add a bit more code to check for invalid / removed BMesh geometry in that function for v3.3.1 (not released yet).  You can try upgrading to a later, officially published version of RetopoFlow, or download v3.3.1 alpha using this temporary link: https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0

I'll close this issue for now, but please let us know if you run into any other problems or have questions.  thanks!

This report is similar to issues #1036, #1037, #1054, #1102, and #1115.
