### ISSUE TITLE
Cannot activate add-on with latest version 3.3.0

### ISSUE THREAD

**Issue by hansolocambo** [CGCookie/retopoflow#1215]
Issue : BUG

Retopoflow Version: 3.3.0

Blender Version/Hash: 3.5.1

Platform Version/Distribution: Windows 11 Pro

**Issue:**
Version 3.3.0 cannot be activated
![2023_05_02_18_38_15_Blender_Preferences](https://user-images.githubusercontent.com/33687288/235732812-28c964f5-2e67-4e6f-bb75-73e387dd2818.png)

**How to Reproduce:**
Install Retopoflow 3.3.0 from the Github Zip : RetopoFlow_v3.3.0-GitHub.zip
Attempt to activate it : fail. 

Just FYI : I downloaded and tried to install the precedent version, using Github's ZIP :  RetopoFlow_v3.2.9-GitHub.zip 
This one can be activated. But if I attempt to start Retopoflow (whether it is by creating a new 
mesh, or starting retopo from an existing mesh in Edit Mode), and Retopoflow crashes :/ 

![2023_05_02_20_15_17_Blender](https://user-images.githubusercontent.com/33687288/235751328-be228b3e-c4ab-414d-b9e7-d81e63869d2d.png)

I'm gonna stick with good old Vanilla retopo for now. Good luck with fixing bugs ;)
Cheers.

**Comment by jlampel** [comment]
I have not been able to replicate this issue, using the same 3.3.0 download and Blender version, also on Windows 11. Please try removing any previous version of RetopoFlow, restarting Blender, and installing again. If it still gives you trouble, please try restoring factory defaults (be careful not to save settings when doing so) to see if any other addons might be causing conflicts. 

The latest version includes fixes for changes in Blender 3.5, so using an older version won't work. 

If that doesn't do the trick, please let us know! Feel free to reopen this issue if that's the case.
