### ISSUE TITLE
[PROPOSAL] Selecting linked faces

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1217]
One quick win would be to add Blender's Select Linked operator to RetopoFlow mode. It should at least be a button in the options, but ideally would be able to be called in any tool with the hotkeys L and Ctrl+L. This would make it much easier to hide sections of a mesh, which is one of the main workarounds we have for performance.

**Comment by vxlcoder** [comment]
ready for testing!

**Comment by jlampel** [comment]
Works great! This is going to be really helpful. I've added a button for it in the selection options as well.
