### ISSUE TITLE
PROPOSAL - Change topology viewport color. 

### ISSUE THREAD

**Issue by DannyHusk** [CGCookie/retopoflow#1218]
Can we PLEASE have an option to change the 'default' topo color. AFAIK the default high res and low res are basically the same color. I posted an example of what I am seeing. There is ZERO contrast and it's a pain to see what you're doing. 

![image](https://github.com/CGCookie/retopoflow/assets/62627452/e159bba4-a604-4c2e-8481-9ce6db4401ae)

**Comment by jlampel** [comment]
Hi there, you can actually change the source object color in the Optimize Shading options under Viewport Display. I usually have mine set to Dark for the extra contrast. You can also turn it off, which uses whatever shading settings you had set in the 3D view before starting RetopoFlow. Changing the color of the target geometry is something we could look at in the future, but only after we figure out how we want to display geometry in the next major version.
