### ISSUE TITLE
[BUG] Contours crash on overlapping vertices. 

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1219]
Source models should not have overlapping vertices, but sometimes they're created by the user without their being aware of it. In this case, duplicate vertices along the center line of a cylindrical source will cause contours to fully crash.  

To replicate, use contours on the neck area in this file:
[duplicate-vertices-crash.zip](https://github.com/CGCookie/retopoflow/files/11457033/duplicate-vertices-crash.zip)

**Comment by vxlcoder** [comment]
fixed!
