### ISSUE TITLE
[BUG] Strokes tool completely ignores Fixed Span Insert Mode, only recognizes Brush Size 

### ISSUE THREAD

**Issue by redrapptor** [CGCookie/retopoflow#1220]
Retopoflow Version: 3.3.0

Blender Version/Hash: 3.5.0

Platform Version/Distribution: Windows 10

**Issue:**

No matter what I do, the `Strokes` tool seems to completely ignore the `Fixed` Span Insert Mode, always drawing from the `Brush Size` Span Insert Mode instead. I've tried uninstalling and reinstalling RF from both Blender Market where I bought it and from here on GitHub, I've ensured that the source mesh is clean, and I've tried doing the same thing with a Suzanne mesh in a brand new file, but the `Strokes` tool always behaves the same way.

This issue isn't the end of the world since I can just adjust the result after it's created, but it's a significant waste of time doing so and should not be necessary when the `Fixed` Span Insert Mode exists.

I've used RF previously since purchasing it and never encountered this issue until now; the `Strokes` tool always worked as expected before which is very strange. I'm either somehow missing something very obvious, or I'm getting some sort of bug.

![broken strokes tool](https://github.com/CGCookie/retopoflow/assets/111337635/af785600-9a19-4d76-b3cc-39777ac77ed4)

It may also be worth noting that RF has also been relentlessly insisting that I need to finish some Auto Save Recovery, even after fresh installs. Clicking the `Finish Auto Save Recovery` button does nothing.

![rf autosave anomaly](https://github.com/CGCookie/retopoflow/assets/111337635/1a45bf41-ed85-4846-905c-cf073c3b761f)

**How to Reproduce:**

I have no idea how to reproduce this as it never occurred before and I haven't done anything differently.

**Comment by vxlcoder** [comment]
thanks for the report, @redrapptor. will take a look at this

**Comment by vxlcoder** [comment]
commit 9f96538 fixes the inability to specify a fixed span count with new strips.  you can test it using this temp link: https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0

the "Finish Auto Save Recovery" issue should also be fixed.

Thanks for the report, @redrapptor!

**Comment by redrapptor** [comment]
@vxlcoder Hey, thanks for giving the issue a go. I've tested it out and it seems like something is still off, but I'm not sure what the exact nature of the situation might be. 

In this alpha version, the Strokes tool partially obeys the Fixed Span Insert Mode, _but_ it seems to break and ignore the Fixed input if I draw a connected loop. In other words, if I draw an unconnected stroke, it adheres to the Fixed value - but if I draw any sort of connected loop, it ignores the Fixed value and goes back to Brush Size for some reason. 

You can see the issue occurring in these screenshots I took; both strokes were drawn at a Fixed value of 8, but only the disjointed stroke adhered to the value I set.

![strokes issue 1](https://github.com/CGCookie/retopoflow/assets/111337635/8d662e0f-513c-4217-8dd0-b63b533baffb)
![strokes issue 2](https://github.com/CGCookie/retopoflow/assets/111337635/86a9a09c-3915-4184-8a18-310a3da70a7e)

**Comment by vxlcoder** [comment]
ah, good catch. will check into that

**Comment by vxlcoder** [comment]
commit 3fa8f19 should fix that.  i went through and found a few other places where the changes needed to be applied.  they should all be done now :)  this temp link has these updates: https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0

thanks for your feedback!  closing this issue, but let us know if you have any other problems.

happy retopo'ing!
