### ISSUE TITLE
**[BUG]** Blender freezes when drawing Contour along Symmetry axis with "Non-manifold Check" enabled

### ISSUE THREAD

**Issue by Copperplate** [CGCookie/retopoflow#1221]
RetopoFlow Version: {*3.3.0*}

Blender Version/Hash: {*3.3.1 hash: `rBb292cfe5a936`*}

Platform Version/Distribution: {*Windows 8.1*}

&nbsp;

**Issue:**
(Purchased RetopoFlow way back in 2018 and never had a reason to use it. Now almost 5 years later I finally cracked it open, and all I can say is WOW, this is an amazing tool!! A huge timesaver.) During my testing I came across a significant bug: When attempting to draw a Contour along the Symmetry axis, where only half of the contour exists and the other half is mirrored, **Blender will instantly freeze if "Non-manifold Check" is enabled.** Disabling "Non-manifold Check" will allow the contour to draw correctly.

&nbsp;

**How to Reproduce:**

1. Open attached .blend file.
2. Select RetopoFlow mesh, enter Edit mode and start RetopoFlow.
3. With the Contours tool selected, make sure X and Y symmetry is enabled and "Non-manifold Check" is enabled.
4. Attempt to create a Contour anywhere on the mesh and Blender will instantly freeze (use Task Manager to close).
5. Repeat the above steps with "Non-manifold Check" disabled and the Contour will draw correctly.
6. (BONUS Check: Note that the Contour at the base of the mesh along the X-symmetry line incorrectly displays as 14 vertices when selected despite only having 8 vertices, though this bug is unrelated to the main issue.)

{*attach any files needed to replicate the issue*}

[Retopoflow 3.3.0_Contour Freeze2.blend.zip](https://github.com/CGCookie/retopoflow/files/11546931/Retopoflow.3.3.0_Contour.Freeze2.blend.zip)

**Comment by vxlcoder** [comment]
interesting find. thanks for the report! will take a look as soon as I can.

**Comment by vxlcoder** [comment]
@Copperplate, do you still get the same behavior with RF v3.3.1?  I'm trying to replicate what you're seeing on your .blend file, but I'm unable to do so.  (I do get the non-manifold warning, which shouldn't happen... but that's a different issue from what you're describing)

**Comment by Copperplate** [comment]
@vxlcoder Hi Jon, I just checked v3.3.1 and no, the freeze doesn't happen anymore, although I now see the non-manifold warning (which I've never seen before-- previously Blender just froze altogether). Thanks for all your hard work! :-)

**Comment by vxlcoder** [comment]
great! will check into the overly ambitious warning...

**Comment by vxlcoder** [comment]
as the original issue is fixed, closing this issue.  i've opened a new issue (#1224) to take care of the warning message.

Thanks again for your help!

**Comment by Copperplate** [comment]
You're very welcome, Jon! Thanks for your diligent labor! :-)
