### ISSUE TITLE
**[BUG]** AutoSave files have wrong scale and open with Blender UI hidden

### ISSUE THREAD

**Issue by Copperplate** [CGCookie/retopoflow#1222]
RetopoFlow Version: {*3.3.0*}

Blender Version/Hash: {*3.5.0 hash: `1be25cfff18b`*}

Platform Version/Distribution: {*Windows 8.1*}

&nbsp;

**Issue:**

**If Blender Scene Scale is set to 0.01** (ideal for exporting meshes to Unreal Engine), RetopoFlow will incorrectly generate AutoSave files with a Scene Scale of 1.00 and also set the scale of both your high poly mesh and your RetopoFlow mesh to **0.000815**. Additionally, Blender's toolbar and header are hidden, and Overlays are disabled.

**If Blender Scene Scale is set to 1.00**, RetopoFlow will generate AutoSave files with a Scene Scale of 1.00 and incorrectly set the scale of both your high poly mesh and your RetopoFlow mesh to **0.081488**. Additionally, Blender's toolbar and header are hidden, and Overlays are disabled.

&nbsp;

**How to Reproduce:**

1. Open same .blend file included in report noted below.
2. Observe the Scene Unit Scale and Object Scale. Wait for an auto-save to occur.
3. Open the AutoSave file and observe the Scene Unit Scale is now 1.000 and the Object Scale is now **0.000815**. Also note Blender's toolbar and header are hidden, and Overlays are disabled.
4. Reopen same .blend file included in report noted below.
5. Change Scene Unit Scale to 1.00. Wait for an auto-save to occur.
6. Open the AutoSave file and observe the Scene Unit Scale remains at 1.000 but the Object Scale is now **0.081488**. Also note Blender's toolbar and header are hidden, and Overlays are disabled.

{*attach any files needed to replicate the issue*}

Please see .blend file included in #1221

**Comment by vxlcoder** [comment]
these _should_ be restored if you use RF's restore feature. If you load the files directly, RF hasn't had a chance to put things back. RF does a lot of temporary changes to support RetopoFlow work, but it can be distracting if the settings get reset before each auto save.

**Comment by Copperplate** [comment]
Hi Jon, thanks for your reply. I wasn't aware RetopoFlow had a restore feature. Where exactly is this feature located? Thanks!

**Comment by vxlcoder** [comment]
I am away from the computer at the moment, but I will post directions and screenshot once I am back. (also, on phone, so sorry for short answers!)

**Comment by Copperplate** [comment]
No problem, thanks for your time. :-)

**Comment by Copperplate** [comment]
I actually just found the setting in the RetopoFlow menu. However, the effect is the same as opening the AutoSave file directly. The UI is hidden, and the scale is wrong as described above.

![image](https://github.com/CGCookie/retopoflow/assets/16230743/390d4ac7-21ed-4f76-a99f-b42ba49bcaf3)

**Comment by vxlcoder** [comment]
hmm... that's not correct behavior. will take a look!

**Comment by vxlcoder** [comment]
ok.  turns out I only _started_ working on that code, and I left myself a big note to finish it, but I never got back to finishing it.  now it seems to be working.

if you would, please test this out using this temp link: https://www.dropbox.com/s/bee8gmq16escltz/RetopoFlow_v3.3.1-alpha-GitHub.zip?dl=0

(I put back in the alpha in the version for now, but it'll hopefully get removed very soon!)

**Comment by Copperplate** [comment]
@vxlcoder Thanks so much, Jon! I will test it out first thing on Monday. :-)

**Comment by Copperplate** [comment]
@vxlcoder Hi Jon, I just finished testing the new build, and it works great!! Pressing "Open Last Auto Save" now correctly loads the last auto save file without hiding the UI and preserves the original object scale of 1, and immediately puts the user into Edit Mode. Prior to restoring the auto save, I noticed an additional warning in the RetopoFlow menu saying, "Finish Auto Save Recovery", however, pressing that button before pressing "Open Last Auto Save" appears to have no result, as the file opens just fine even without pressing it. Thanks so much again for all your hard work! 🥇 

![FinishAutoSaveRecovery](https://github.com/CGCookie/retopoflow/assets/16230743/7e916fb3-e5fa-4019-8d44-fe264fe2b7fa)

**Comment by vxlcoder** [comment]
glad to read it's working as expected now!

@Copperplate, the `Finish Auto Save Recovery` operator is there because the current .blend file you have open has RF recovery info stored in it (if you opened the auto save file directly).  it should recover as expected from this point forward.  this operator should not show up if you're working with a normal .blend file.

the `Open Last Auto Save` operator means that there is an auto save file that was found that can be recovered.  clicking this will open that file and auto recover.  we need to think a bit more on when to show this operator or not...

will leave this issue open for a bit longer while we finish testing.

happy retopo'ing!

**Comment by Copperplate** [comment]
@vxlcoder Thanks Jon, for clarifying. The `Finish Auto Save Recovery` operator was showing up when opening either the original .blend file or the auto-save file. However, after I clicked the button once and resaved the file, it did not show up again. I also re-installed the add-on and let an auto-save occur, closed without saving, then opened the source .blend file and the `Finish Auto Save Recovery` operator was not showing. So I have no idea why it triggered the first time, but it appears to be working now. Have a great week ahead! :-)

**Comment by vxlcoder** [comment]
thanks for the final report!  closing this issue
