### ISSUE TITLE
**[BUG]** RetopoFlow 3.3.0 very slow even on medium poly source, but claims high fps

### ISSUE THREAD

**Issue by Copperplate** [CGCookie/retopoflow#1223]
RetopoFlow Version: {*3.3.0*}

Blender Version/Hash: {*blender-v3.5-release, commit date: 2023-03-29 02:56, hash: `1be25cfff18b`*} 

Platform Version/Distribution: {*Windows 8.1*}

&nbsp;

**Issue:**

Possibly related to #448 and #710 

Using a medium-poly source mesh (176,712 tris), and a low poly RetopoFlow mesh (2,840 tris), attempting to pan the 3D view with Retopoflow active results in chugging (very low fps). However, RetopoFlow claims it is running at approx. 65 fps, but in reality it is more like 5 or 8 fps.

**Please see unlisted video of issue here:** [https://youtu.be/cX1SGv8BG40](https://youtu.be/cX1SGv8BG40)

**System specs:**
Windows-8.1-6.3.9600-SP0 64 Bit Home
CPU: Intel i7-5930K 6-core @ 3.50 GHz
RAM: 32 GB DDR4
GPU: EVGA NVIDIA GeForce GTX 970 with 4 GB RAM (Driver 473.04)

&nbsp;

**How to Reproduce:**

1. Open attached .blend file.
2. Shift+Middle Mouse Pan the 3D view. Observe the smooth frame rate.
3. Enter RetopoFlow and pan again. Notice the very low frame rate, despite RetopoFlow claiming a high fps.

**Test file:**

[Retopoflow 3.3.0_PerformanceBug.blend.zip](https://github.com/CGCookie/retopoflow/files/11556972/Retopoflow.3.3.0_PerformanceBug.blend.zip)

**Comment by vxlcoder** [comment]
Thanks for the detailed report, @Copperplate!

I _believe_ this was fixed in v3.3.1 (not _yet_ released... but soon!)  you can test using this temp link: https://www.dropbox.com/s/o4dof9jjqmhszuk/RetopoFlow_v3.3.1-GitHub.zip?dl=0

please let me know if the updated version does not fix it, and i'll dig more into your report.

**Comment by Copperplate** [comment]
Thanks so much, Jon! I will check out the pre-release and let you know. :-)

**Comment by Copperplate** [comment]
Whoo-hoo! No chugging at all in this build, frame rate is nice and fluid! Fantastic work, guys!!! Thank you so much!!  🥇
