### ISSUE TITLE
BUG - Console Errors for Retopoflow

### ISSUE THREAD

**Issue by pixelinkmedia** [CGCookie/retopoflow#1230]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {3.2.9}

Blender Version/Hash: {3.5.1} Blender has removed the hash from the about screen

Platform Version/Distribution: {Windows 10}

&nbsp;

**Issue:**

I am getting a lot of depreciated warnings on the console when Blender starts up.

![image](https://github.com/CGCookie/retopoflow/assets/51757955/d49f2057-2fec-4783-a115-bb0b5b0ffea5)

&nbsp;

**How to Reproduce:**

Just when I start Blender

**Comment by vxlcoder** [comment]
thanks for the report, @pixelinkmedia!

we are aware of these warnings. Blender has deprecated a module that we use in RF, but we have been working to switch to another module, and we hope to have this completed before Blender 4.0 arrives later this year.

You should be able to ignore these warnings.

Closing this issue for now, but let us know if you have any more questions or concerns.

Happy retopo'ing!
