### ISSUE TITLE
**[BUG]** PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by kgilliam2** [CGCookie/retopoflow#1231]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [X] Read through the README.md file in the branch used to assure the process taken is correct
- [X] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [X] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

Retopoflow 3.3.0 (installed from github release) + Blender 3.5. Crashes when starting retopoflow. Here's some stuff I did before creating this ticket:
 - Reset blender to factory preferences
 - Rebooted computer (just in case)
 - Opened blender and enabled only retopoflow addon
 - Created new blend file -> made a cube -> tried to start retopoflow with cube as active
 - Retopoflow reports an error before crashing blender
 - Also tried to start at cursor, same result

![image](https://github.com/CGCookie/retopoflow/assets/10750198/692f8280-11a9-402e-95f5-cd6ba93a0b2e)

**How to Reproduce:**
- open blender, create a cube, and start retopoflow

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.3.0
- Self built
- Blender: 3.05.1 blender-v3.5-release 2023-04-24
- Platform: Windows, 10, 10.0.22621, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3080/PCIe/SSE2, 4.5.0 NVIDIA 527.56, (no shader version)
- Timestamp: 2023-06-10 12:31:20.191088
- Undo: 

Error Hash: 5ad931ef1e82e197e269aca6
[blender_system_info.txt](https://github.com/CGCookie/retopoflow/files/11713160/blender_system_info.txt)
4c013967

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'is_2D'
-     C:\Users\gilli\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\RetopoFlow\retopoflow\rf\rf_target.py
- 000 0261:get_point2D() if point.is_2D(): return point
- 001 0241:accel_nearest2D_face() xy = self.get_point2D(point or self.actions.mouse)
-     C:\Users\gilli\AppData\Roaming\Blender Foundation\Blender\3.5\scripts\addons\RetopoFlow\retopoflow\rftool_polystrips\polystrips.py
- 002 0190:main() self.hovering_sel_face,_ = self.rfcontext.accel_nearest2D_face(max_dist=options['action dist'], selected_only=True)
-     .../common\fsm.py
- 003 0169:wrapped() return fn(*args, **k
[blender_debug_output.txt](https://github.com/CGCookie/retopoflow/files/11713159/blender_debug_output.txt)
wargs)
```

[blender_debug_output.txt](https://github.com/CGCookie/retopoflow/files/11713185/blender_debug_output.txt)
[blender_system_info.txt](https://github.com/CGCookie/retopoflow/files/11713186/blender_system_info.txt)

**Comment by vxlcoder** [comment]
thanks for the report, @kgilliam2!

i have fixed this error is commit a9f8265, which we plan to release soon.
