### ISSUE TITLE
Vertex merging at the mirrored are problem

### ISSUE THREAD

**Issue by WizardGroon** [CGCookie/retopoflow#1234]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {3.3.0}

Blender Version/Hash: {3.3.7}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*When the mirror modifier is active vertices which close to the middle area merges at mirrored area.*}

{![image](https://github.com/CGCookie/retopoflow/assets/48471118/abc6f9f6-dae7-4a94-82f1-1a180794b7cf)}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
@WizardGroon, under Options > Symmetry > Merge / Apply, there is a Threshold box.  The value in that box determines how close vertices can be get to symmetry plane when snapping starts (same as Merge Distance with Mirror Modifier).  setting this to 0 will disable the snapping.

![image](https://github.com/CGCookie/retopoflow/assets/3790699/58f1480e-2afd-45c6-bb3a-eb92f081be60)

Closing this issue for now, but please let us know if you have any other questions!

happy retopo'ing!
