### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Umoy** [CGCookie/retopoflow#1242]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.3.0
- Self built
- Blender: 3.06.0 blender-v3.6-release 2023-06-27
- Platform: Windows, 10, 10.0.19045, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 1660 Ti/PCIe/SSE2, 4.5.0 NVIDIA 536.23, (no shader version)
- Timestamp: 2023-07-13 13:09:07.080750
- Undo: create strip, select, insert, insert, select, select, slide edge loop/strip, insert edge strip, insert, insert

Error Hash: 6c12cfa5368df4cba260184fb36e2a5d

Trace:

- EXCEPTION (<class 'TypeError'>): edges.new(...): expected (BMVert), not 'NoneType'
-     C:\Users\Tronics\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh.py
- 000 1625:new_edge() bme = self.bme.edges.new(verts)
-     C:\Users\Tronics\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 001 0620:new_edge() return self.rftarget.new_edge(verts)
-     C:\Users\Tronics\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 002 0538:<listcomp>() edges = [self.rfcontext.new_edge([v0, v1]) for (v0, v1) in iter_pairs(verts, wrap=False)]
- 003 0538:create_strip() edges = [self.rfcontext.new_edge([v0, v1]) for (v0, v1) in iter_pairs(verts, wrap=False)]
-     C:\Users\Tronics\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 004 0150:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Tronics\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 005 0307:modal_main() self.replay()
-     .../common\fsm.py
- 006 0169:wrapped() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Umoy.  I was not able to reproduce this issue, but I _think_ commit 1df9fca fixes it.
