### ISSUE TITLE
[BUG] 3.3.0 - No Source Detected

### ISSUE THREAD

**Issue by tylru** [CGCookie/retopoflow#1243]
**Retopoflow Version:**
3.3.0

**Blender Version/Hash:**
3.6.1

**Platform Version/Distribution:**
Windows 10

&nbsp;

**Issue:**

Even though the mesh is visible and selected, it cannot be detected by RetopoFlow. This is after a fresh install of Blender 3.6 and RetopoFlow 3.3.0

![image](https://github.com/CGCookie/retopoflow/assets/22118920/80701267-f8bd-4e5e-93e9-724e5dc3ce93)

**Comment by vxlcoder** [comment]
Interesting... thanks for reporting the issue, @tylru. 

I am not sure why it is doing that. would you mind sending your .blend file to retopoflow@cgcookie.com so I can take a look at your setup?

**Comment by tylru** [comment]
I attempted to bypass the issue by adding a cube to the scene, which then let me progress, but instantly crashed giving this error:


Environment:

- RetopoFlow: 3.3.0
- Self built
- Blender: 3.06.1 blender-v3.6-release 2023-07-17
- Platform: Windows, 10, 10.0.19045, AMD64, Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 3080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 536.67, (no shader version)
- Timestamp: 2023-07-18 23:04:50.233291
- Undo: 

Error Hash: d1282c452d548cc71720b88cf419b5d9

Trace:

- EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute 'rftool'
-     C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\bpy_types.py
- 000 0855:__getattribute__() return super().__getattribute__(attr)
-     C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow\retopoflow\rf\rf_fsm.py
- 001 0196:modal_main() if self.rftool._fsm.state == 'main' and (not self.rftool.rfwidget or self.rftool.rfwidget._fsm.state == 'main'):
-     .../common\fsm.py
- 002 0169:wrapped() return fn(*args, **kwargs)


If this doesn't shed any light on the issue above, I will send over the .blend file as requested :)

Thanks

**Comment by vxlcoder** [comment]
Not sure what's happening there.  let's try this:

- uninstall RF
- restart Blender
- install RF v3.4.0 from this [temp link](https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0)

then let me know if you run into issues with the default cube and/or your initial blend file.

one other question: did RetopoFlow ever work for you before, or is this your first time trying?

thanks for helping us debug this issue!  we'll get you up and retopo'ing soon!

**Comment by tylru** [comment]
Thank you!

Attempting to install the addon you have provided gave this error when enabling it:

![image](https://github.com/CGCookie/retopoflow/assets/22118920/e24750d6-59eb-4c5e-9375-42aeac38a650)
![image](https://github.com/CGCookie/retopoflow/assets/22118920/69acc247-ab95-4ee0-85ed-7c4e8a4882e9)

RF worked fine for me until yesterday. Something went wrong with my 3.5 / RF install where it got stuck in a strange autosave situation (after opening an RF autosave, it wouldn't let me do anything)

 So I uninstalled RF/Blender 3.5 and installed Blender 3.6 / RF 3.3 and that's where we're at now.

**Comment by vxlcoder** [comment]
what other add-ons are enabled?

can you try loading factory defaults, then enable on RF?

this is acting like another add-on is causing problems.

**Comment by tylru** [comment]
I had UV Packmaster, a Blender to UE bridge, and a few other small QoL add-ons, though I've just removed them completely and this is with no other add-ons installed:

![image](https://github.com/CGCookie/retopoflow/assets/22118920/c9476bed-9739-4fe6-a3a2-914c125564d9)
![image](https://github.com/CGCookie/retopoflow/assets/22118920/f283cec7-ed83-4154-bab2-e5f552980bb9)

**Comment by tylru** [comment]
After a Blender restart, the addon is still enabled but obviously not functioning as intended:
![image](https://github.com/CGCookie/retopoflow/assets/22118920/71e6cbc9-6561-4790-8e6a-85905a4f4fa3)

**Comment by tylru** [comment]
Certainly! The mentioned debug text file is empty.



`Read prefs: "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\config\userpref.blend"
 ╔═╡ Deep Debugging ╞═════════════════════════════════════════════════════════════════════════════════════════════════╗
 ║ Redirecting ALL STDOUT and STDERR                                                                                  ║
 ║ path: C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\RetopoFlow_debug.txt ║
 ╚════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╝
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.6\3.6\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\__init__.py", line 49, in <module>
    from .addon_common.hive.hive import Hive
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\addon_common\hive\hive.py", line 5, in <module>
    from ..common.blender import get_path_from_addon_root
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\addon_common\common\__init__.py", line 59, in <module>
    from . import drawing as _
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\addon_common\common\drawing.py", line 48, in <module>
    from .fontmanager import FontManager as fm
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\addon_common\common\fontmanager.py", line 26, in <module>
    from . import gpustate
  File "C:\Users\Tyler\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\addon_common\common\gpustate.py", line 74, in <module>
    print(f'Addon Common: {use_bgl_default=} {use_gpu_default=} {use_gpu_scissor=}')
OSError: [WinError 6] The handle is invalid







`

**Comment by vxlcoder** [comment]
hmmm... it seems that some deep debugging code i recently wrote is causing problems.  one sec...

**Comment by vxlcoder** [comment]
I just modified the zip to disable the deep debugging, so that we can work around the recent `The handle is invalid` issue.

Try uninstalling RF, restart Blender, and then installing this [version](https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0).

if you run into issues again, please copy-paste from the terminal again.  there tends to be more debugging info in the terminal than what's shown in Blender.  This is what the deep debugging feature (that seems to be causing problems) is supposed to make easier to obtain.

**Comment by tylru** [comment]
When trying to remove the addon the normal way (the remove button in preferences):
![image](https://github.com/CGCookie/retopoflow/assets/22118920/40d30477-c160-4043-9b86-0fa5ebacfb9f)

However deleting the RF folder in AppData, and installing this new zip seemed to work:
![image](https://github.com/CGCookie/retopoflow/assets/22118920/b8e99c5e-f778-4d60-8d96-ce6f098b546c)

Trying with a new scene/cube:
![image](https://github.com/CGCookie/retopoflow/assets/22118920/63c03a0e-fc22-4aaa-b3ee-0ad351675811)

My existing scene however, still doesn't work:
![image](https://github.com/CGCookie/retopoflow/assets/22118920/0b2ff572-8b91-4d5e-8eed-ae265a8822ca)

I've emailed you the .blend file :)

**Comment by vxlcoder** [comment]
great, and boo!

ok, at least we're back to the original problem.  (i'll investigate the deep debugging issue later)

does RF 3.4 work with default cube scene?

If so, I still think it is your .blend set up, and I might need to take a closer look at the file.

**Comment by vxlcoder** [comment]
and, thanks again for helping us through this!

**Comment by tylru** [comment]
> does RF 3.4 work with default cube scene?

It did at one point, yes. Of course 3.4 worked with everything at one point, including the cursed blend file :D 

That would be much appreciated. I'm not sure how I might have got the file into this state, but I guess perhaps the autosave issue is persisting somehow.

Thanks again!

**Comment by vxlcoder** [comment]
ok, @tylru, i was able to figure out why you're getting the `No sources detected` error!

the objects are marked as sources, target, or unused when starting RF, so that RF can recover some settings correctly.  However, I rewrote the recovery code, and forgot to clear the markings.  Now they're cleared.

So, if you ever open up a .blend file that was autosaved (ex: the file you sent me over email), you'll need to click Recover from auto save button, then those markings will go away and RF will see all the meshes correctly.

You can download the updated version using this [link](https://www.dropbox.com/s/16xu7mowqkbm3mm/RetopoFlow_v3.4.0-alpha-GitHub.zip?dl=0).

one note: let me know if you get that `The handle is invalid` error again, though, and I'll just remove the deep debugging code until I can test it more later and update the zip once more.

please let me know if this solves your problem, and once again thanks for helping debug this issue!

**Comment by tylru** [comment]
Superb, thank you so much again for your assistance. I will test this in the next hour or so and let you know :)
