### ISSUE TITLE
Can't undo in Knife

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1244]
Undo is working in every tool except Knife. 

To replicate:
- Use Knife to make a cut
- Undo that cut while still in the Knife tool

I also noticed that it takes two presses of Ctrl+Z to undo a loop made with the Loops tool. Not sure if that's related or not, but it's less important.

**Comment by vxlcoder** [comment]
fixed!

**Comment by jlampel** [comment]
Confirmed!
