### ISSUE TITLE
[PROPOSAL]Display switch for low polygons displayed in front

### ISSUE THREAD

**Issue by NoPlan123** [CGCookie/retopoflow#1247]
Polygons created by repository work are forced to appear in front of high polygons.
This makes it difficult to ascertain whether or not the results are optimal.
It would be nice if there was a button to toggle this forced display on and off.

**Comment by vxlcoder** [comment]
there are options for the viewport to adjust how much the target geo is pushed over the source. most of the time, the default values provide the desired visualization.

can you provide a screenshot of where you would prefer the non-retopo render instead?

**Comment by jlampel** [comment]
Closing for lack of info. Visualization height for the low poly can already be adjusted.
