### ISSUE TITLE
[BUG] Infinite loop while "Resuming help image preloading"

### ISSUE THREAD

**Issue by cwrenniks** [CGCookie/retopoflow#1248]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.4

Blender Version/Hash: 3.6.1

Platform Version/Distribution: Windows 11

&nbsp;

**Issue:**

When going into edit mode on an existing object ( in my case, a simple plane with four vertices ), and then selecting the button to the left of the retopoflow toolbar button, retopoflow hangs infintitely at the screen found in the screen shot. The dialog in the middle of the screen reads: "Loading Retopoflow.... Resuming help image preloading"
![Screenshot 2023-08-07 191907](https://github.com/CGCookie/retopoflow/assets/188627/294ba5f7-dc66-4d0a-963f-e0447e28962f)

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
thanks for the report, @cwrenniks .

can you copy-paste anything you see in the terminal? there might be a lot.  see https://docs.retopoflow.com/debugging.html for more details

**Comment by vxlcoder** [comment]
oh interesting... will take a look!

**Comment by vxlcoder** [comment]
@cwrenniks commit 901c20c _should_ fix this issue, although i was not able to reproduce it.  thanks for the report!
