### ISSUE TITLE
[QUESTION] How to bridge with the Strokes Tool

### ISSUE THREAD

**Issue by cwrenniks** [CGCookie/retopoflow#1251]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Retopoflow Version: 3.4

Blender Version/Hash: 3.6.1

Platform Version/Distribution: Windows

&nbsp;

**Issue:**

I'm trying to bridge the gap between two "islands" of polygons, both of which have the same number of sides, using the Stroke tool, but am not able to make it work. Trying to follow along with the CGCookie tutorial and can't seem to get the Strokes tool to behave as I'm seeing Jonathan do in the "Strokes Tool" video around minute 2:24.

I've added a video showing my problem. I'm assuming I'm just not doing something right here. :)

&nbsp;

https://github.com/CGCookie/retopoflow/assets/188627/0de1298e-2123-4ae0-9e86-4cc5d54cafd5

**Comment by vxlcoder** [comment]
that should work just as you're using it. will take a look. thanks for the report and video!

**Comment by imh1kiko** [comment]
Can confirm it not to work in 3.6.1a either. Tried toggling auto-merge buttons, didn't seem to do much.
https://drive.google.com/file/d/1c98ScaxNLwGb-SsFgJMIH4e2HlI6eXmd/view?usp=drive_link

**Comment by vxlcoder** [comment]
this issue is now fixed in commit 807fc06.  thanks for the report!

**Comment by jlampel** [comment]
Confirmed fixed!
