### ISSUE TITLE
[BUG] No Source Detected!

### ISSUE THREAD

**Issue by loganloganlo** [CGCookie/retopoflow#1253]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.4

Blender Version/Hash: 3.6

Platform Version/Distribution: Blender Marketplace

&nbsp;

**Issue:**

Getting an error on installation as above "No Source Detected" when attempting to install the RetopoFlow_v3.4.0 version directly from the folder from Blender Marketplace.

![image](https://github.com/CGCookie/retopoflow/assets/29672721/ca406bd4-7f82-440b-a823-cea890c5dbc1)

&nbsp;

**How to Reproduce:**

It's every time I try going through Edit > Preferences > Add-ons > Install

Then installing the .zip file of the version above. 

I've done the following in an attempt to remove this issue.

- Clean install 
- Removal of all add-ons while using RetopoFlow
- Updated version of Blender & RetopoFlow

I'm still getting the issue.

**Comment by vxlcoder** [comment]
hi @loganloganlo.

what does your scene look like?

it looks like you're in edit mode on the default cube. if you switch to object mode, you should be able to start RetopoFlow right away.  RF will treat any meshes (the cube) as the "sources" (high poly count objects that you're wanting to retopo) and create a new "target" (low poly retopo mesh).

if you're in edit mode, RF will treat that as the target and all other meshes as sources. but on this case, it looks like you are editing the only mesh in the scene.

https://docs.retopoflow.com/quick_start.html has more details.
