### ISSUE TITLE
Tweak: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Zeraphel** [CGCookie/retopoflow#1255]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.0
- Build: CG Cookie built for Blender Market
- Blender: 3.06.1 blender-v3.6-release 2023-07-17
- Platform: Windows, 10, 10.0.22621, AMD64, Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 3080/PCIe/SSE2', 'version': '4.5.0 NVIDIA 536.99', 'compute_shader_support_get': True, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True, 'shader_storage_buffer_objects_support_get': True}
- Timestamp: 2023-08-16 21:46:50.978520

Runtime:

- Undo: tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move
- Error Hash: 9f4f8b48ebb6ed6d4261c037db522902

Trace:

- EXCEPTION (<class 'AssertionError'>): unhandled type of other: None (<class 'NoneType'>)
-     .../common\maths.py
- 000 0202:__sub__() assert False, "unhandled type of other: %s (%s)" % (str(other), str(t))
-     C:\Users\yamil\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\retopoflow\rftool_tweak\tweak.py
- 001 0206:move_doit() delta = Vec2D(self.rfcontext.actions.mouse - self.mousedown)
-     C:\Users\yamil\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0207:wrapper() ret = fn(*args, **kwargs)
-     .../common\fsm.py
- 003 0135:wrapped() return fn(*args, **kwargs)

```

**Comment by vxlcoder** [comment]
thanks for the report, @Zeraphel!

i was not able to reproduce your error, but I believe commit cf762d6 _should_ fix it.

you can test it using this temp link: https://www.dropbox.com/s/ycdml8zlwvxyqca/RetopoFlow_v3.4.1-alpha-GitHub.zip?dl=0

please let me know if you are still getting that issue after updating or if you think that issue is no longer there.  thanks!
