### ISSUE TITLE
[BUG] bgl.glGetError() deprecation for Blender 4.0

### ISSUE THREAD

**Issue by draeath** [CGCookie/retopoflow#1259]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.3.0

Blender Version/Hash: 3.6.1 / 8bda729ef4dc (via Steam)

Platform Version/Distribution: linux x86_64 (opensuse tumbleweed)

&nbsp;

**Issue:**

The `bgl.glGetError()` call used in `addon_common/common/drawing.py` has been deprecated and emits warnings when blender loads with the addon enabled. The warning (follows this description) indicates the call will be removed in release 4.0.

Note that this does not interfere with the addon at this time, but it will need to be addressed in the future.

{*add any screenshots of the issue here*}

    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module

&nbsp;

**How to Reproduce:**

- run blender 3.6.1 or newer with the addon enabled

{*attach any files needed to replicate the issue*}

Elided debug output follows:

    REDACTED@ginnungagap:~> blender --debug-all
    
    ... irrelevant output trimmed
    
    bl_app_template_utils.reset('')
            addon_utils.enable io_anim_bvh
            addon_utils.enable io_curve_svg
            addon_utils.enable io_mesh_ply
            addon_utils.enable io_mesh_stl
            addon_utils.enable io_mesh_uv_layout
            addon_utils.enable io_scene_fbx
            addon_utils.enable io_scene_gltf2
            addon_utils.enable io_scene_obj
            addon_utils.enable io_scene_x3d
            addon_utils.enable cycles
            addon_utils.enable object_print3d_utils
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetString' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    Addon Common: (shaders) GLSL Version: 4.60
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    WARN (bgl): source/blender/python/generic/bgl.c:54 report_deprecated_call: 'bgl.glGetError' is deprecated and will be removed in Blender 4.0. Report or update your script to use 'gpu' module.
    Addon Common: compiling UI shader
    Addon Common: batching for shader
    Addon Common: UI shader initialized
    Addon Common: ########################################
                Loading shader using Shader
    RetopoFlow: Initial load
    RetopoFlow git: None
    gpustate.gpu_info cannot get shader version!
    RetopoFlow options path: /home/REDACTED/.config/blender/3.6/scripts/addons/RetopoFlow/RetopoFlow_options.json
    No options file
    Addon Common: (bmesh_render) GLSL Version: Intel, Mesa Intel(R) UHD Graphics 770 (ADL-S GT1), 4.6 (Core Profile) Mesa 23.1.5, (no shader version)
    cgcookie addon: Verbose is enabled
    cgcookie addon: Read in JSON settings from file
            addon_utils.enable RetopoFlow
            addon_utils.enable io_mesh_3mf
    Python Script Load Time 0.2675
    
    ... irrelevant output trimmed
    
    REDACTED@ginnungagap:~> cd .config/blender/
    REDACTED@ginnungagap:~/.config/blender> ag 'bgl.glGetError'
    3.6/scripts/addons/RetopoFlow/addon_common/common/drawing.py
    61:    bgl.glGetError()
    472:        err = bgl.glGetError()
    497:        err = bgl.glGetError()

**Comment by draeath** [comment]
Looks like this was fixed in a subsequent addon version. No such warning is emitted with 3.4.0

**Comment by vxlcoder** [comment]
thanks for the report, @draeath!

yes, RF v3.4.0 now uses the blender gpu module, so you shouldn't get that deprecation warning any more.

please let us know if you have any other questions or issues.

happy retopo'ing!
