### ISSUE TITLE
Plugin installation error, not sure what the error is.

### ISSUE THREAD

**Issue by sangouzhi** [CGCookie/retopoflow#1266]
![QQ图片20230918235654](https://github.com/CGCookie/retopoflow/assets/114461992/f283ff6f-70aa-42df-bdbd-1403aa87e184)

**Comment by vxlcoder** [comment]
thanks for the report, @sangouzhi .

where did you get RetopoFlow? Blender Market, GitHub, somewhere else? if GH, where did you download it from?

it looks like the packaging of RF was not correct, but I am not sure yet.

**Comment by sangouzhi** [comment]
> 感谢您的报告，@sangouzhi。
> 
> 您从哪里获得 RetopoFlow？Blender 市场、GitHub 还是其他地方？如果是GH，你从哪里下载的？
> 
> 看起来RF的包装不正确，但我还不确定。

![Snipaste_2023-09-19_08-00-22](https://github.com/CGCookie/retopoflow/assets/114461992/07b38a7c-a042-4801-9ea4-804eed82534e)
over here

**Comment by vxlcoder** [comment]
ah, try downloading using the top link there, right above the one your arrow is pointing to.
