### ISSUE TITLE
[BUG] Can't select certain vertices

### ISSUE THREAD

**Issue by Iruszz** [CGCookie/retopoflow#1271]
Retopoflow Version: v3.4.0

Blender Version/Hash: v3.6.4

Platform Version/Distribution: Windows 11

Issue:
I can't edit some of the vertices in my scene.

![Screenshot (12)](https://github.com/CGCookie/retopoflow/assets/83592796/319f001c-3b88-42bb-9f9c-9f3abfd3e6d0)

How to Reproduce:
I have added in the low poly object after I saw that the poly count was still a bit too high. So I wanted to reduce it. I had to scale down the model to fit over the high poly model. I then set the scale. This means that some vertices are probably below the high poly model. Somehow I can't move these vertices.

I can't upload the file here as it is too big so I've put it on my google drive:
https://drive.google.com/file/d/1mPgDfOB2ycdO0j2hTXK4Iyk2ExR2ND2-/view?usp=sharing

**Comment by Iruszz** [comment]
On further inspection. I have scaled up the vertices that I couldn't move. They are now outside out the high poly model but I can still not move them.

**Comment by Iruszz** [comment]
I figured out why. The vertices were seams. When I removed them I could move the vertices.

**Comment by vxlcoder** [comment]
thanks for reporting this along with details, @Iruszz!  i'm glad to hear that you were able to figure it out.

I made a few changes (commits 908ddc5, a11165d, a35a355) that I hope will prevent making these type of issues.

closing this issue for now, but please let us know if you run into any other issues.

happy retopo'ing!
