### ISSUE TITLE
[Proposal] Quick Merge

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1275]
(this is a copy from issue #1269 by @sangouzhi)

With the new 'select' command, it's faster to select points, lines, and faces. I noticed that you added the 'ctrl+x' shortcut for quick deletion, which is great. Can you add a similar shortcut for quick merging of points, lines, and faces?

**Comment by vxlcoder** [comment]
@sangouzhi, are you asking to replicate the Blender merge menu?  (maybe as a pie menu)

![image](https://github.com/CGCookie/retopoflow/assets/3790699/3b340808-0930-4fec-98d1-78c2201c099e)

**Comment by sangouzhi** [comment]
> @sangouzhi, are you asking to replicate the Blender merge menu? (maybe as a pie menu)
> 
> ![image](https://user-images.githubusercontent.com/3790699/278895358-3b340808-0930-4fec-98d1-78c2201c099e.png)

yes,  If we add 'Merge' to this command, it will be perfect. This will allow for quick merging and improve work efficiency.
![Snipaste_2023-10-30_14-28-10](https://github.com/CGCookie/retopoflow/assets/114461992/46e843dd-3fad-4b98-adac-4c213c22d493)

**Comment by sangouzhi** [comment]
at center  and   any  other  one  ,  i think

**Comment by vxlcoder** [comment]
commit d3ac15f adds Merge at Center and Merge by Distance options.

**Comment by jlampel** [comment]
Looks good to me!
