### ISSUE TITLE
[Proposal] Space to confirm knife

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#1276]
(this is a copy from issue #1269 by @sangouzhi)

when using the 'knife' tool, it currently requires a right-click to confirm. It would be better if it used the left-click or space bar instead.

**Comment by vxlcoder** [comment]
commit 593a403 adds space as quick tool confirm (only applies to knife and loops right now, as tweak and relax will leave quick switch upon release of quick key)

**Comment by jlampel** [comment]
This makes a lot of sense. Works great!
