### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Esonver** [CGCookie/retopoflow#1277]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.0
- Build: CG Cookie built for GitHub
- Blender: 3.06.5 blender-v3.6-release 2023-10-16
- Platform: Windows, 10, 10.0.22621, AMD64, AMD64 Family 25 Model 97 Stepping 2, AuthenticAMD
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 4090/PCIe/SSE2', 'version': '4.5.0 NVIDIA 537.42', 'compute_shader_support_get': True, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True, 'shader_storage_buffer_objects_support_get': True}
- Timestamp: 2023-10-30 15:49:07.406925

Runtime:

- Undo: 
- Error Hash: 81712b99871d2f463828d38eab325ac9

Trace:

- EXCEPTION (<class 'TypeError'>): cannot unpack non-iterable NoneType object
-     C:\Users\Esgar\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 000 0119:update_nearest() self.nearest_face,_ = self.rfcontext.accel_nearest2D_face(max_dist=options['polypen merge dist'], selected_only=True)
-     .../common\fsm.py
- 001 0135:wrapped() return fn(*args, **kwargs)

```

**Comment by vxlcoder** [comment]
thanks for the report, @Esonver.  I believe this issue has already been fixed in RF v3.4.1, but I just realized that I forgot to publish v3.4.1 on GH!   it's there now.  you shouldn't see this issue again after updating to the latest version.  closing this issue for now, but please let us know if you have any other issues.

**Comment by Esonver** [comment]
Thank you, I don't know what caused this, but I thought an submission might be useful nevertheless.

**Comment by vxlcoder** [comment]
yes, submitting issues as they come up is helpful, as it lets us know what needs fixed. thank you again, and happy retopo'ing!
