### ISSUE TITLE
Relax: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by atarpey44** [CGCookie/retopoflow#1279]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.1
- Build: Self built
- Blender: 3.06.5 blender-v3.6-release 2023-10-16
- Platform: Windows, 10, 10.0.19045, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 3070/PCIe/SSE2', 'version': '4.5.0 NVIDIA 536.23', 'compute_shader_support_get': True, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True, 'shader_storage_buffer_objects_support_get': True}
- Timestamp: 2023-11-01 14:43:30.442211

Runtime:

- Undo: 
- Error Hash: 939ac3d58bc4bdeb4690ea894bcc3306

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'x'
-     .../common\maths_accel.py
- 000 0199:get() if isinf(v2d.x) or isinf(v2d.y) or isnan(v2d.x) or isnan(v2d.y): return set()
- 001 0219:get_edges() return self.get(v2d, within, fn_filter=self._is_edge)
-     C:\Users\adamt\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 002 0339:accel_nearest2D_edge() edges = vis_accel.get_edges(xy, max_dist)
-     C:\Users\adamt\AppData\Roaming\Blender Foundation\Blender\3.6\scripts\addons\retopoflow-master\retopoflow\rftool_strokes\strokes.py
- 003 0203:update_hover_edge() self.hovering_sel_edge,_ = self.rfcontext.accel_nearest2D_edge(max_dist=options['action dist'], selected_only=True)
-     .../common\fsm.py
- 004 0135:wrapped() return fn(*args, **kwargs)

```

**Comment by vxlcoder** [comment]
thanks for the report, @atarpey44.

I was not able to reproduce this error, but commit c4a88aa should fix it.
