### ISSUE TITLE
RF symetry going negative if crossing the mirror border, snap not snapping unless extremely close

### ISSUE THREAD

**Issue by DrPepeR** [CGCookie/retopoflow#1283]
**[BUG]**

Retopoflow Version: 3.4.2B

Blender Version/Hash: 4.0

Platform Version/Distribution: windows 10

As the tittle describes it, it is pretty simple, start RF enable symmetry (even on the default cube or any other shape) go past the symmetry line, the symmetry starts going backwards and the snapping does not work unless manually pushed by the poly pen as close as you can get to the middle without going negative.

![20 November 2023 03 22 42 (Unsaved)_-_Blender_4 0](https://github.com/CGCookie/retopoflow/assets/12982937/3e882d24-1477-4bbc-a182-fa4834e2ad09)

(Cant SS while holding Ctrl, took the SS as soon as I left click and the vertex was created.

**Comment by jlampel** [comment]
In the symmetry options, you can turn off Mirror Input to disable this behavior. I'll look at turning this off by default since it is a bit hard to work with near the symmetry line.
