### ISSUE TITLE
[PROPOSAL] Retopology view, 

### ISSUE THREAD

**Issue by ibo1985** [CGCookie/retopoflow#1284]
Retopoflow Version: 3.4.2
Blender Version/Hash: 3.6
Platform Version/Distribution: Windows 11

Hi.
Have you thought about changing your viewport settings? Not that they are bad, but maybe you could implement alternative viewport settings like native "Retopology" option from "Vieport Overlays" with is simple with one offset slider. It is quite good and enough for professional work. This could be much simpler than "factor" settings etc. builded in your tool and maybe it could resolve any perforamce problems? :)

**Comment by jlampel** [comment]
Hi, yes! @vxlcoder helped out with the development of that feature early on, so we are well aware of it and will look at using it in the next major version.
