### ISSUE TITLE
RETOPOFLOW DONT WORK AT ALL .. 

### ISSUE THREAD

**Issue by Robert001977** [CGCookie/retopoflow#1294]
I install the program and I cannot use nothing . . my Blender version is 4.0 and this Retopoflow i see is different version 3,4,2 ... can anyone help me out is not working at all .. i cannot retopology anything ..

**Comment by vxlcoder** [comment]
hi, @Robert001977.

Can you answer a few questions so we can see how to help? 

- Where did you get RetopoFlow from?  Blender Market?  RetopoFlow's front GitHub page?  RF's release page?  Somewhere else?
- After you install, does RF show up in add-ons list, and did you check it? 
![image](https://github.com/CGCookie/retopoflow/assets/3790699/f808555e-a918-4bba-b570-edc2b8560c42)
- When you're in Object or Edit mode, do you see a RetopoFlow dropdown in your tool bar? 
![image](https://github.com/CGCookie/retopoflow/assets/3790699/b275a596-39e0-4955-9e23-1d335c7a4593)
- You say that you're not able to see anything.  What do you mean by this?  Can you post some screenshots of what you do see?

thanks for helping us debug your issue!

**Comment by jlampel** [comment]
Closing for lack of info
