### ISSUE TITLE
**[BUG]**RetopoFlow isn't working anymore. It worked last night though.

### ISSUE THREAD

**Issue by ZCreates** [CGCookie/retopoflow#1295]
Retopoflow Version: 3.2.8

Blender Version/Hash: 3.1.1

**Issue:**

So the issue is, I installed Retopoflow about 4 days ago. Last night was the first time I used it and it worked fine. I was able to get a mesh created and exported. 

However, I am trying to use it now and it won't work. When I click it in object mode it switches to edit mode and from then I click it again to start retopoflow and it doesn't pop up. I get an error message instead. 

![8120ab1dc58b2d25fddfcc4a10f3f5ed](https://github.com/CGCookie/retopoflow/assets/149840670/0fe73d37-4ff2-4c7e-b8e3-669b9f74c7bc)
![Untitled](https://github.com/CGCookie/retopoflow/assets/149840670/bf12759d-fa57-4f9b-b56b-460f6d67754e)

Any constructive criticism is welcomed. I just want to be able to create lol.

**Comment by vxlcoder** [comment]
Hi, @ZCreates.

I'm not entirely sure why you're getting that particular error message (`OSError: [WinError 233] No process is on the other end of the pipe')

Here are a few things to try:

- Try using a newer version of RF.  RF v3.3.0 should work on Blender 2.93 and later.  (v3.4.x requires at least Blender 3.6).
- Try using a newer version of Blender?
- Open the System Console (see [link](https://docs.retopoflow.com/debugging.html#windows) for details), then try starting RetopoFlow.  after it crashes like this, copy-paste _everything_ that is printed into the system console here so we can inspect the log.

**Comment by ZCreates** [comment]
Okay, just downloaded v3.3.0 and it is still coming up with an error. 

Also did the system console:

Read prefs: C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\config\userpref.blend
Blender Version: (3, 1, 1)
Bento Buddy Version: (2023, 41)
Python Version: 3.10.2
Handlers loaded
Bento Buddy: enabled
Avastar Handlers registered
WARNING:  Copied 5 template files to
WARNING:  C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\presets\avastar
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'avastar-master'
RetopoFlow: Initial load
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
Addon Common: ########################################
              Loading shader using Shader
RetopoFlow Shader Info: uiShader (22)
  attribs:
  uniforms: uMVPMatrix (23), left (12), right (21), top (22), bottom (7), width (25), height (9), depth (8), margin_left (14), margin_right (15), margin_top (16), margin_bottom (13), padding_left (18), padding_right (19), padding_top (20), padding_bottom (17), border_width (6), border_radius (3), border_left_color (2), border_right_color (4), border_top_color (5), border_bottom_color (1), background_color (0), using_image (24), image_fit (11), image (10)
RetopoFlow git: None
gpustate.gpu_info cannot get shader version!
RetopoFlow options path: C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\RetopoFlow_options.json
Addon Common: (bmesh_render) GLSL Version: NVIDIA Corporation, NVIDIA GeForce GTX 1660 Ti with Max-Q Design/PCIe/SSE2, 4.5.0 NVIDIA 546.17, (no shader version)
cgcookie addon: Verbose is enabled
cgcookie addon: Read in JSON settings from file
addon_utils.disable: RetopoFlow not loaded
addon_utils.disable: RetopoFlow not loaded
Modules Installed (RetopoFlow) from 'C:\\Users\\ambit\\OneDrive\\Desktop\\sl\\Blender\\addons\\RetopoFlow_v3.3.0-GitHub.zip' into 'C:\\Users\\ambit\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons'
module changed on disk: 'C:\\Users\\ambit\\AppData\\Roaming\\Blender Foundation\\Blender\\3.1\\scripts\\addons\\RetopoFlow\\__init__.py' reloading...
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 330, in enable
    importlib.reload(mod)
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\python\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 619, in _exec
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\__init__.py", line 84, in <module>
    update_based_on_hive()
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\__init__.py", line 58, in update_based_on_hive
    from .addon_common.hive.hive import Hive
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\addon_common\hive\hive.py", line 3, in <module>
    from ..common.blender import get_path_from_addon_root
ImportError: cannot import name 'get_path_from_addon_root' from 'RetopoFlow.addon_common.common.blender' (C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\addon_common\common\blender.py)

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.1\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\__init__.py", line 84, in <module>
    update_based_on_hive()
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\__init__.py", line 58, in update_based_on_hive
    from .addon_common.hive.hive import Hive
  File "C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\addon_common\hive\hive.py", line 3, in <module>
    from ..common.blender import get_path_from_addon_root
ImportError: cannot import name 'get_path_from_addon_root' from 'RetopoFlow.addon_common.common.blender' (C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\addon_common\common\blender.py)

**Comment by vxlcoder** [comment]
thanks for the information, @ZCreates!

I see the error that's causing your issue `ImportError: cannot import name 'get_path_from_addon_root' from 'RetopoFlow.addon_common.common.blender' (C:\Users\ambit\AppData\Roaming\Blender Foundation\Blender\3.1\scripts\addons\RetopoFlow\addon_common\common\blender.py)`.  However, looking at the rest of the log, I'm not sure why this is at all an issue.  The path looks correct according to the line where you installed RF.  RF v3.3.0 has a `blender.py` file in that location which has a `get_path_from_addon_root` function ([link](https://github.com/CGCookie/retopoflow/blob/v3.3.0/addon_common/common/blender.py#L344))

Can we try one more thing?  Try this:

- Start Blender.  Open Preferences, and remove RetopoFlow and close Blender. 
![image](https://github.com/CGCookie/retopoflow/assets/3790699/19d80352-8821-4b0c-961c-44289375f24c)
- Now restart Blender.  Open the System Console.  Install RetopoFlow from zip (same as you did before), enable it.  Then try running RetopoFlow.
- If it fail again, copy-paste the system console log here again.

Separately, it looks like an add-on called avastar is having issues (`ModuleNotFoundError: No module named 'avastar-master'`).  this shouldn't be a cause for RF's issue, but I thought I would note it here since I saw it.

**Comment by jlampel** [comment]
Reinstalling RF as noted above should fix the issue. If not, please let us know!
