### ISSUE TITLE
UI text disappears after loading new file with the same Blender instance

### ISSUE THREAD

**Issue by FelixPias** [CGCookie/retopoflow#1296]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by FelixPias** [comment]
When I tried to retopo my mesh after saving and exiting by entering the Interface was showing accept all textes and instructions.
I downgraded the version of retopo to the last version before I had saved and it worked again ... so. Sadly I don't have a screenshot. (All buttons were working but no text at all)

**Comment by jlampel** [comment]
Hi, which version of Blender are you using with which version of RetopoFlow? There's not much we can do without that info. Glad you have a version that's working though!

**Comment by jlampel** [comment]
I can actually trigger this pretty easily now in 3.4.2 by:

- Starting Blender
- Starting RF
- Exiting RF
- Opening a new or different file in the same instance of Blender
- Starting RF again

![Screenshot 2024-01-29 130059](https://github.com/CGCookie/retopoflow/assets/12982300/4eb38539-812a-405c-9b14-952718b77fa7)

**Comment by jfranmatheu** [comment]
Closing this issue as it is fixed starting from version 3.4.3. Tested by following the provided trigger steps:

> * Starting Blender
> * Starting RF
> * Exiting RF
> * Opening a new or different file in the same instance of Blender
> * Starting RF again
