### ISSUE TITLE
RetopoFlow failed to be enable when added in Steam version Blender 4.0.2

### ISSUE THREAD

**Issue by HollowCrusader** [CGCookie/retopoflow#1301]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

v3.4.2 - BlenderMarket

Blender Version/Hash: {*add here*}
4.0.2

Platform Version/Distribution: {*add here*}

Steam

&nbsp;

**Issue:**

{*enter your issue here*}

The error is after trying to enable the Retopoflow, installation went perfectly.

{*add any screenshots of the issue here*}

<img width="746" alt="blender_mZ0iOOqqnO" src="https://github.com/CGCookie/retopoflow/assets/28148217/a6a10a5a-1c89-448e-bce8-2077a2627b59">

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}
Install the Retopoflow add-on and then enable it by clicking the checkbox

<img width="495" alt="blender_qhnwj4fizs" src="https://github.com/CGCookie/retopoflow/assets/28148217/4267d64e-e6c0-4511-b1d1-888c41ac1c48">

{*attach any files needed to replicate the issue*}

**Comment by HollowCrusader** [comment]
Apology, apparently Steam hasn't fully stopped the launch of Blender even after closing the window so it "didn't" clear the previous version after reinstallation of the newer one. I will check thoroughly through the task manager if any issue should pop up with retopoflow.

**Comment by vxlcoder** [comment]
interesting find. thanks for the details. please let us know if you have any other problems!
