### ISSUE TITLE
**[BUG]** Blender 3.6.8+ not installable

### ISSUE THREAD

**Issue by DavyJonesSocks** [CGCookie/retopoflow#1302]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.4.2

Blender Version/Hash: 3.6.8

Platform Version/Distribution: Windows 10

&nbsp;

**Issue:**

I cannot activate the addon in Blender. I freshly installed Blender 3.6.8 and the RF addon. I tried following Blender versions:
* 4.0.2
* 3.6.8

and following RF versions:

* 3.4.2
* 3.4.1
* 3.4.0

With every combination l I get the same error when trying to activate the addon. It does not recognize the python module 'retopoflow-3'.

![Screenshot (33)](https://github.com/CGCookie/retopoflow/assets/43553224/28c95ee9-fa81-4c9a-92d6-ae0edf7be733)

&nbsp;

**How to Reproduce:**

- Install Blender 3.6.8 or later
- Install RF 3.4.0 or later
- Install the addon in Blender
- Try to activate the addon and it fails

**Comment by vxlcoder** [comment]
it looks like you're installing from the zip that GitHub automatically creates, which is not blender-friendly. instead, you need to use the official zips from blender market or the release page (https://github.com/CGCookie/retopoflow/releases)

![Screenshot_20240127-183303.png](https://github.com/CGCookie/retopoflow/assets/3790699/515b04a5-df36-4e0a-9d8c-f1dd36916b9e)

**Comment by DavyJonesSocks** [comment]
That solved it, thank you!
