### ISSUE TITLE
retoflow not working

### ISSUE THREAD

**Issue by seonhyejang** [CGCookie/retopoflow#1309]
** 다음을 읽고 템플릿을 사용하여 문제를 게시하십시오**

1. The message appears, and the add-on is terminated and will not be reactivated.
2. The add-on does not work as the message appears.

- RetopoFlow crashed unexpectedly.
Be sure to save your work, and report what happened so that we can try fixing it

- RetopoFlow Error
An unexpected error occurred while trying to start RetopoFlow.
Please consider reporting this issue so that we can fix it.
Visit Blender Market
Create a new issue on GitHub
Open Blender Market RetopoFlow in the default browser

**Comment by vxlcoder** [comment]
@seonhyejang, thank you for reporting this issue.

We are going to need a little bit more information to know what is happening when it crashes.

Can you give us more information about what you were doing when it crashed?  Also, which version of Blender and RetopoFlow are you using?  Are you on Windows, OSX, or Linux?  Does this happen when you try using RetopoFlow on the default cube scene? 

If you can, please read the [debugging docs](https://docs.retopoflow.com/debugging.html#terminal--console-output) to see how to gather useful information that we'll need to debug this issue.

Thanks for helping us figure out what is wrong!  We'll get you back to retopo'ing as quickly as we can.
