### ISSUE TITLE
RetopoFlow does not appear in header 

### ISSUE THREAD

**Issue by StatusEffects** [CGCookie/retopoflow#1313]
I have used RetopoFlow in the past, but I can’t seem to get it to work now. It isn’t appearing on the header. I have attached a screenshot. In it I circled where I remember the addon appearing. Has its location changed? Any help would be appreciated.

Extra information I attempted to download and install the last three versions. Versions 3.41 and 3.3.0 will create an error pop up when I attempt to install them. Version 4.0 installs but as you can see from my screenshot I can’t seem to find it in the header. I am running the latest version of Blender. and Windows.

![RetopoFlow](https://github.com/CGCookie/retopoflow/assets/129320021/7d902c75-33a3-40d9-9f97-bb87ad5b4028)

**Comment by jlampel** [comment]
Hi, it looks like you're using the RetopoFlow 4 early alpha build, which has moved to the Edit Mode toolbar and is just PolyPen at the moment. If you remove it and install RetopoFlow 3.4.3, which is the latest release, it will work as before.

**Comment by jlampel** [comment]
Can you try fully removing RetopoFlow, restarting Blender, and then installing again? I believe the 4.0 alpha and 3.4.3 have some conflicts.

**Comment by StatusEffects** [comment]
okay that did it, thank you very much!
