### ISSUE TITLE
[QUESTION] How do I make Retopoflow 4 alpha show up in the 3D view header?

### ISSUE THREAD

**Issue by Carramone** [CGCookie/retopoflow#1319]
Retopoflow Version: 4.0.1 Alpha
Blender Version/Hash: 4.1.1
Platform Version/Distribution: Windows 11

&nbsp;

I have installed the addon, and everything seems to install just fine, but the addon doesn't show up in the 3D view header. In edit mode the tool "PolyPen" show up, but no menu in the header there either.  I can't find any settings in the add on to turn on or off the menu, so I don't know what I'm doing wrong. I have tried in Blender 4.0.X as well, but I have the same issue there. 

<img width="629" alt="noshow_retopoflow" src="https://github.com/CGCookie/retopoflow/assets/32165452/f055245d-2211-461a-ab65-237fb51345cc">
&nbsp;
<img width="629" alt="noshow_retopoflow_editmode" src="https://github.com/CGCookie/retopoflow/assets/32165452/aa935774-acbc-4de6-90b4-cbc6ab65738d">

**Comment by vxlcoder** [comment]
hi @Carramone .

The new RF4 does not have the menu in the header anymore. we have integrated it into Blender to make it look and feel like any other blender tool.

Here is a very short video explaining it more.

https://youtu.be/Fr8QiQTe6dM?si=i-tByQ2n2yKIcEMc

Please let us know if you have any other questions or problems.

Happy retopo'ing!

**Comment by Carramone** [comment]
Wow, this is absolutely amazing. Thank you very much!

**Comment by vxlcoder** [comment]
happy to help!

please consider leaving us a rating on the Blender Market / SuperHive.

cheers!
