### ISSUE TITLE
blendermarket 10th birthday retopoflow 4 alpha vesion have no icon after installed

### ISSUE THREAD

**Issue by s1702w0246** [CGCookie/retopoflow#1320]
there is no icon on header after installed

**Comment by jlampel** [comment]
Hi, RetopoFlow 4 no longer lives in the 3D View header. More info in the tutorial: https://www.youtube.com/watch?v=Fr8QiQTe6dM

**Comment by s1702w0246** [comment]
> Hi, RetopoFlow 4 no longer lives in the 3D View header. More info in the tutorial: https://www.youtube.com/watch?v=Fr8QiQTe6dM

ok，thanks bro
