### ISSUE TITLE
[BUG] No Sources Detected-Shape lab Import 

### ISSUE THREAD

**Issue by Linesdrawn2** [CGCookie/retopoflow#1324]
Retopoflow Version: 3.4.3

Blender Version/Hash: 4.1

Platform Version/Distribution: Blender Marketplace

**Issue:**

I am rather new to blender but also using Retopoflow, so be aware that I might just be not doing it right. However the issue is that it is not detected the active target , however can detected edit the mesh on it. I've seen other people be able to use it immediately without issues and confused why it doesn't work the same way.

It remains greyed out no matter what I do. And the other thing I could think that could be messing with it is that I use a scuplture program called Shapelab which could be causing all of the issues. Here's the screenshots of the problem and sorry for  reporting this issue, just been a constant issue since I installed the add-on.

![Screenshot 2024-06-26 201447](https://github.com/CGCookie/retopoflow/assets/173951587/05a5b3a1-9d11-4b45-9b96-c8f8a7e789d1)
![Screenshot 2024-06-26 201627](https://github.com/CGCookie/retopoflow/assets/173951587/6dc4c64c-4c33-4d79-8a90-1bbbc481a939)

**How to Reproduce:**

- Import file made in shapelab
- Select Active Target
- Reproduced results
or
-Import file 
-edit mode on target
-edit existing mesh

Files:-
[Comedy_Voxel Remesh.zip](https://github.com/user-attachments/files/15994303/Comedy_Voxel.Remesh.zip)

**Comment by jlampel** [comment]
Hi, so the issue here is probably just the terminology. The Source is the high poly object that you want to draw on, while the Target is the low poly object that you create with RetopoFlow. Here's a full video guide that shows how to set up RetopoFlow and should answer all these questions: 

https://www.youtube.com/watch?v=9OjS2rU-Jr0 

Let me know if that doesn't solve it!

**Comment by Linesdrawn2** [comment]
Thank you so much! Yeah it works perfectly, thanks for explaining it ^_^
