### ISSUE TITLE
Loops: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Shylightbulb** [CGCookie/retopoflow#1325]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.3
- Build: CG Cookie built for Blender Market
- Blender: 4.01.0 blender-v4.1-release 2024-03-25
- Platform: Windows, 10, 10.0.22631, AMD64, Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 3090/PCIe/SSE2', 'version': '4.6.0 NVIDIA 551.86', 'compute_shader_support_get': True, 'hdr_support_get': False, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True}
- Timestamp: 2024-06-30 02:37:02.728340

Runtime:

- Undo: 
- Error Hash: d0d7bef2afdc0c76880bbf2eceedc7b5

Trace:

- EXCEPTION (<class 'ReferenceError'>): StructRNA of type Object has been removed
-     C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\retopoflow\retopoflow\rfmesh\rfmesh.py
- 000 0253:get_obj_name() return self.obj.name
-     C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\retopoflow\retopoflow\rf\rf_sources.py
- 001 0100:get_rfsource_snap() n = rfsource.get_obj_name()
- 002 0111:raycast_sources_Ray() if not self.get_rfsource_snap(rfsource): continue
- 003 0131:raycast_sources_Point2D() return self.raycast_sources_Ray(self.Point2D_to_Ray(xy, min_dist=self.drawing.space.clip_start), correct_mirror=correct_mirror, ignore_backface=ignore_backface)
- 004 0138:raycast_sources_mouse() return self.raycast_sources_Point2D(self.actions.mouse, correct_mirror=correct_mirror, ignore_backface=ignore_backface)
-     C:\Users\Administrator\AppData\Roaming\Blender Foundation\Blender\4.1\scripts\addons\retopoflow\retopoflow\rf\rf_fsm.py
- 005 0099:update() self.actions.hit_pos,self.actions.hit_norm,_,_ = self.raycast_sources_mouse()
-     .../cookiecutter\cookiecutter_modal.py
- 006 0143:modal_mainloop() self.update()
-     .../cookiecutter\cookiecutter_exceptions.py
- 007 0036:try_exception() yield

```

**Comment by vxlcoder** [comment]
Thanks for the report, @Shylightbulb .

there isn't quite enough context to figure out what caused this issue. do you recall what you were doing when this happened?

**Comment by Shylightbulb** [comment]
Hello guys, I remember I was uninstalling the uv plugging  you have because it was getting my computer very slow, the moment I hit uninstalled and came out from blender preferences and into Retopoflow again, I got this alert. At the end I had to uninstall everything again and reinstall. Just maybe in case of having some programming resemblance I did install bith plugins again. I am not a programmer, so every time I get into this trouble I get nervous. Retopoflow is one of the best pluggings I have ever have in my life. I am 41, so, take it as a compiment. Keep the good work. 


Enviado desde Yahoo Mail para iPhone


El martes, julio 2, 2024, 10:40, Jon Denning ***@***.***> escribió:




Thanks for the report, @Shylightbulb .

there isn't quite enough context to figure out what caused this issue. do you recall what you were doing when this happened?

**Comment by jlampel** [comment]
Did reinstalling fix the issue with RetopoFlow, or is it still occurring? 

Also, if UV Flow is causing a slowdown in your scene, please message me in the contact form below with more details so we can fix that as well: https://orangeturbine.com/p/contact

**Comment by Shylightbulb** [comment]
Yes it did fix the issue with Retopoflow. They are both running ok, for now. If I ever run into that issue again I’ll let you know. I’ll safe this mail foe future problems. Thanks for the concern guys. 


Enviado desde Yahoo Mail para iPhone


El martes, julio 2, 2024, 12:59, Jonathan Lampel ***@***.***> escribió:




Did reinstalling fix the issue with RetopoFlow, or is it still occurring?

Also, if UV Flow is causing a slowdown in your scene, please message me in the contact form below with more details so we can fix that as well: https://orangeturbine.com/p/contact

**Comment by jlampel** [comment]
Awesome, glad to hear it! I'll close this out since we need to focus on version 4 which does not seem to have this problem, but we will keep an eye out for related issues.
