### ISSUE TITLE
**[QUESTION]** Paper craft using Retopo Geom.

### ISSUE THREAD

**Issue by Indifferent1570** [CGCookie/retopoflow#1328]
Retopoflow Version: 3.4.3

Blender Version/Hash: 4.1
Platform Version/Distribution: Windows 10
&nbsp;

**Issue:**

I want to use retopoflow to create planes on 3-D models in blender such that I can export these to papercraft inside of blender. When I do this, all I am met with is the outline and no fold locations. Is there a way I can generate "planes" from the retopo surfaces?

**Comment by jlampel** [comment]
Hi, sorry, I'm not sure I fully understand the question since I haven't used Blender for papercraft yet. Do you want each face of the retopology to be a separate plane, or what should the end result look like?

**Comment by Indifferent1570** [comment]
I wish I was versatile enough here, from what I understand Papercraft likes having planes and not the retopo element that comes out of retopoflow. From what I can gather, the plane produced by retopo is not the same as a plane in blender, meaning that the paper-craft program can not gather correct information from these "planes" generated from retopo. Please see the example below which has around 5 squares in it, but only the outline of the five squares are output. 
[RetopoPlanes.pdf](https://github.com/user-attachments/files/16242225/RetopoPlanes.pdf)


Whereas planes from blender create this instead for paper-craft:
[BlenderPlanes.pdf](https://github.com/user-attachments/files/16242232/BlenderPlanes.pdf)

**Comment by jlampel** [comment]
Sorry for the delayed response, but this is not really a use case we can focus on right now. At the moment we need to focus on getting RetopoFlow 4 working for the basic character sculpt retopology workflow, and maybe after that we can branch out to other use cases. In general, it sounds more like a problem for a standalone add-on for exporting to papercraft and not a retopology specific problem within Blender.
