### ISSUE TITLE
[BUG] Retopoflow Header Button Missing

### ISSUE THREAD

**Issue by trwb** [CGCookie/retopoflow#1329]
Retopoflow Version: 4.0.0

Blender Version/Hash: 4.0.2 / 4.1.1

Platform Version/Distribution: Windows

&nbsp;

**Issue:**

The Retopoflow button is missing from the header. It doesn't appear so unable to initiate. 

![image](https://github.com/user-attachments/assets/9fc2efe2-62d8-477a-9453-d80728aa6f8f)

&nbsp;

**How to Reproduce:**

- download 4.0.2/4.1.1 
- install addon

**Comment by vxlcoder** [comment]
Hi, RetopoFlow 4 no longer lives in the 3D View header. see the tutorial for more details: https://www.youtube.com/watch?v=Fr8QiQTe6dM. please let us know if you have any other questions or issues. happy retopo'ing!
