### ISSUE TITLE
Edge slide occasionally draws pole edges incorrectly

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#133]
![image](https://cloud.githubusercontent.com/assets/2917743/8713811/84653c82-2b3b-11e5-8126-b6fae5c564c3.png)

![image](https://cloud.githubusercontent.com/assets/2917743/8713814/9475c4e8-2b3b-11e5-88d5-7bb79e648bc7.png)

**Comment by vxlcoder** [comment]
shouldn't be an issue in v2!  closing!
