### ISSUE TITLE
Contour is not showing in retopoflow

### ISSUE THREAD

**Issue by Scarlett77777** [CGCookie/retopoflow#1334]
My contour just stopping being viewed while using retopoflow does anyone happen to know a fix I have tried install and reinstall ect thanks

**Comment by jfranmatheu** [comment]
@Scarlett77777 

Thank you for the report

Can you provide this info to help you further?
- Blender version
- RF version
- System info, Operative system
- Did it work in previous RF versions or in previous Blender version?

Additionally, does it show up any 'error' like message in the system console when trying to use RF?
You can enable the system console (See https://docs.retopoflow.com/debugging.html for reference), then run RF and use it as usual. Finally, copy the contents of the system console and paste it here. If there is any hint of internal error it could appear there to that could be helpful for us to debug.

Thanks!

**Comment by jlampel** [comment]
Closing for lack of info, but please let us know if you continue to have this problem! We can reopen the issue then. Apologies for my initial delay in responding.
