### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by aphixe** [CGCookie/retopoflow#1336]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

I was using poly tool and then it crashed on me I was adding onto a part that had a quad.

{*add any screenshots of the issue here*}

**How to Reproduce:**

hard to say I just had a quad and I was splitting it with the poly tool

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.4
- Build: CG Cookie built for Blender Market
- Blender: 4.02.1 blender-v4.2-release 2024-08-19
- Platform: Darwin, 23.6.0, Darwin Kernel Version 23.6.0: Mon Jul 29 21:14:46 PDT 2024; root:xnu-10063.141.2~1/RELEASE_ARM64_T6031, arm64, arm
- GPU: {'backend': 'METAL', 'device': 'APPLE', 'vendor': 'Apple M3 Max', 'renderer': 'Metal API', 'version': '1.2', 'compute_shader_support_get': True, 'hdr_support_get': True, 'max_batch_indices_get': -2147483648, 'max_batch_vertices_get': -2147483648, 'max_images_get': 128, 'max_texture_layers_get': 2048, 'max_texture_size_get': 16384, 'max_textures_frag_get': 128, 'max_textures_geom_get': 0, 'max_textures_get': 128, 'max_textures_vert_get': 128, 'max_uniforms_frag_get': 1024, 'max_uniforms_vert_get': 1024, 'max_varying_floats_get': 60, 'max_vertex_attribs_get': 31, 'shader_image_load_store_support_get': True}
- Timestamp: 2024-09-07 15:45:34.959567

Runtime:

- Undo: insert, insert, insert, insert, insert, insert, select, move after select, grab, grab
- Error Hash: 0559f37293298e827845c0e62d45afff

Trace:

- EXCEPTION (<class 'RuntimeError'>): Error: Could not write image: Read-only file system
- 
-     /Applications/Blender.app/Contents/Resources/4.2/scripts/modules/bpy/ops.py
- 000 0109:__call__() ret = _op_call(self.idname_py(), kw)
-     /Users/aphixe/Library/Application Support/Blender/4.2/extensions/user_default/retopoflow/retopoflow/rf/rf_ui_alert.py
- 001 0153:screenshot() bpy.ops.screen.screenshot(filepath=filepath)
-     .../common/ui_core_events.py
- 002 0069:<lambda>() callback = lambda e: old_callback()
- 003 0092:_fire_event() cb(details)
- 004 0098:_fire_event() raise e
- 005 0129:dispatch_event() self._fire_event(event, ui_event)
-     .../common/ui_document.py
- 006 0559:mousedown_exit() under_mouseclick.dispatch_event('on_mouseclick')
-     .../common/fsm.py
- 007 0169:wrapped() return fn(*args, **kwargs)

```

**Comment by vxlcoder** [comment]
thanks for the report, @aphixe. unfortunately the debug info you posted here is not related to polypen, but it's related to taking a screenshot. I can work on that issue, but please let us know if you run into the polypen issue again!

**Comment by jfranmatheu** [comment]
Closing this issue since it seems closely related to an error in Blender source code `EXCEPTION (<class 'RuntimeError'>): Error: Could not write image: Read-only file system` due to the screenshot operator  `bpy.ops.screen.screenshot`.

Feel free to re-open if you find it could be related to the PolyPen tool, then please provide more information to help you further.
