### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by icius99** [CGCookie/retopoflow#1338]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.3
- Build: CG Cookie built for GitHub
- Blender: 4.02.1 blender-v4.2-release 2024-08-19
- Platform: Windows, 10, 10.0.22631, AMD64, AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 4070 Ti/PCIe/SSE2', 'version': '4.6.0 NVIDIA 560.81', 'compute_shader_support_get': True, 'hdr_support_get': False, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_images_get': 8, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True}
- Timestamp: 2024-09-15 16:01:21.901445

Runtime:

- Undo: extrude strip, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip
- Error Hash: 276bce7cc7876673f7847bbc86540441

Trace:

- EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
-     C:\Users\icius\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes_insert.py
- 000 0700:<listcomp>() per_lens = [l / strip_len for l in edge_lens]
- 001 0700:extrude_equals() per_lens = [l / strip_len for l in edge_lens]
-     C:\Users\icius\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0208:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\icius\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes_insert.py
- 003 0229:stroke() if self.replay: self.replay()
-     C:\Users\icius\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 004 0112:_callback_tool() fn(self.rftool, *args, **kwargs)
- 005 0136:callback_actions() self._callback_tool('action', action_name, *args, **kwargs)
-     C:\Users\icius\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 006 0114:modal_line() self.callback_actions(self.action_name)
-     .../common\fsm.py
- 007 0169:wrapped() return fn(*args, **kwargs)

```

**Comment by jfranmatheu** [comment]
Good to mention this one has some similarities with https://github.com/CGCookie/retopoflow/issues/1362
- Exact the same undo stack
- Similar call stack structure
- Both happen in the same script files: `strokes_insert.py` and `rftool.py`
- Similar nested function calls through `wrapper()`, `stroke()` and `callback_actions()`

But they have different error types and different error locations:
- `ReferenceError `vs `ZeroDivisionError`
- `rfmesh_wrapper.py` vs `strokes_insert.py`

These errors appear related to mesh manipulation instabilities in Retopoflow, likely arising from rapid, successive extrude operations that stress the addon's mesh handling mechanisms. I would recommend to implement safeguards against sequence of rapid and successive operations as well as other safeguard mechanisms as to check for potential zero divisions prior division operation and extra checks for BMesh object validation.

**Comment by jfranmatheu** [comment]
A preventive measure was taken to avoid the ZeroDivisionError. https://github.com/CGCookie/retopoflow/commit/e2622443b3b2f8054ff9b5c6f3e2080a9789d6e8
