### ISSUE TITLE
We broke guide mode

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#134]
You can't draw in guide mode anymore. At all.

**Comment by patmo141** [comment]
adopted this problem

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/9021683/e8846028-381d-11e5-88e2-5ae03783a29c.png)

It seems to be working for me.  2.75 from builder.bender 7/31
It may be a key map issue.

**Comment by patmo141** [comment]
I can draw in guide mode.  2.76RC 10/1/2015  hash: 550527b

**Comment by carter2422** [comment]
Okay seems the issue is Guidemode isn't using the new keymap to determine `selection` and `action` mouse. Switching selection to RMB works.

**Comment by carter2422** [comment]
I think we'll need to handle this via the distance travelled method, like we do in Polystrips:
```
            # if is selection mouse, check distance
            if 'LEFTMOUSE' in selection_mouse():
                dist_traveled = 0.0
                for s0,s1 in zip(self.sketch[:-1],self.sketch[1:]):
                    dist_traveled += (Vector(s0[0]) - Vector(s1[0])).length

                # user like ly picking, because distance traveled is very small
                if dist_traveled < 5.0:
                    self.pick(eventd)
                    self.sketch = []
                    return 'main'
```
