### ISSUE TITLE
Selection Limit

### ISSUE THREAD

**Issue by 3DCarveTech** [CGCookie/retopoflow#1340]
Please add double-click selection limited stopped by preselected segments. See image.

![image](https://github.com/user-attachments/assets/141d2b9a-a11a-4071-a026-1c35a5e0d887)

**Comment by jlampel** [comment]
Thanks for the feedback! The solution to this in RetopoFlow 3 is to click and drag to select the shortest path, and I have it in my notes to make shortest path selection easier in version 4. I think that would be better and more Blender-like than complicating loop selection.
