### ISSUE TITLE
Retopoflow 3.4.3 - Visualization/ Clipping Issue 

### ISSUE THREAD

**Issue by Retribution3D** [CGCookie/retopoflow#1341]
Retopoflow Version: 3.4.3

Blender Version/Hash: 4,2

Platform Version/Distribution: GitHub

&nbsp;

**Error in Viewport Clipping and Visualization**

Hi, Working on a project and Just cant seem to get the visualization working properly. 

I have tried editing the values for the start minimum and end maximum to no avail. 

I'm not sure if I am missing something small. I've tried to make sure all items on the model are scaled and to size and scale applied.

 I am working In Blender 4.2.
 I have decimated the model so that the polycounts aren't too high.

I am trying to retopo the hand/ other elements of the body but the mesh visibility is just too strong and I cant see through the items I am needing to work on. I have followed "The Complete Guide to Retopology with RetopoFlow 3 in Blender" in Youtube the section on Display and still not sure if I am missing something.

Assistance would be greatly appreciated!

![image](https://github.com/user-attachments/assets/2474a9fc-546e-4a1a-b6d1-1f178ad79701)

![image](https://github.com/user-attachments/assets/a0fc9253-9a49-4f07-bde0-e8d4d8e39aaf)

![image](https://github.com/user-attachments/assets/7fba6449-3ea6-4505-9eb1-ef0b7582851a)

![image](https://github.com/user-attachments/assets/7e8be0bc-1072-4350-ab8f-c6a4b85133b6)

&nbsp;
How to Reproduce

[Retopo_V3.zip](https://github.com/user-attachments/files/17429413/Retopo_V3.zip)

**Comment by jlampel** [comment]
We received another report of this via the BM inbox, and it looks to be a common problem in Blender 4.2:

![Screenshot_20241115_042959](https://github.com/user-attachments/assets/717949b6-03e9-4f0b-affe-6497ff33ed5e)

**Comment by jlampel** [comment]
Please try going to the Options and under Viewport Display, use the following settings:

Start Factor: 0.001
Start Minimum: 0.01
End Factor: 1
End Maximum: 10 

Also, please check your unit scale in Blender and set it to 1 if you can if the above is not doing anything. 

That should fix it. If not, please re-open this and let me know!
