### ISSUE TITLE
Snapping Mirror

### ISSUE THREAD

**Issue by AwwabShuaib** [CGCookie/retopoflow#1345]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]**

Retopoflow Version: 3.4.4

Blender Version/Hash: 4.2

Platform Version/Distribution: {blender market}

&nbsp;

**Issue:**

Every time I add any quad(s) or edge(s) to the symmetry, it snaps literally to the symmetry.  I tried changing the merging threshold, but it still happened. 

![Screenshot 2024-11-07 161150](https://github.com/user-attachments/assets/f614a9b9-c05a-4bca-93c0-79776f7fd226)

**How to Reproduce:**
![Screenshot 2024-11-07 161334](https://github.com/user-attachments/assets/30e47454-11a4-4e07-85e9-2c3409cf900f)

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Thanks for the report.

What are you expecting PolyStrips to do instead?

usually with mirror symmetry, you want the verts and edges to be at the symmetry line so that the mirrored geometry doesn't overlap.

Are you trying to do something different or use PS in a different way?

**Comment by AwwabShuaib** [comment]
I want the quads to go *around *my character with the symmetry, not snap to
the center plane.  I tried every tool that creates quads or edges and they
still keep on doing this.

**Comment by jlampel** [comment]
That's a very valid request and I agree it would be helpful in some situations. But this is one of those many things that just comes automatically with RetopoFlow 4, and I don't think we should take time away from that to support it in RetopoFlow 3. So, I'll close this out because it's already supported in the next major update.
