### ISSUE TITLE
Filling patches with strokes

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1351]
Using strokes to fill patches doesn't work yet, since the number of segments isn't overridden by the vertex count between the connected edges and the ends aren't snapped together. This operation works perfectly in RF 3. 

Action:
![image](https://github.com/user-attachments/assets/5691f401-2687-40d2-8f85-28a0f65009f4)

Result:
![image](https://github.com/user-attachments/assets/bd8eaac0-df67-43a9-9efc-e5274d71f4e8)

**Comment by jlampel** [comment]
Looks like some bridging already works, and is even better than in v3! It's great that I can draw from any vertex and not just the outsides. 

![image](https://github.com/user-attachments/assets/c42006a2-e735-4448-8ac0-6f2aee37db54)

![image](https://github.com/user-attachments/assets/55d5ef60-53d5-4888-aaa6-81dbdddb3f20)

But situations like the example in the post above and the image below are still missing. 

![image](https://github.com/user-attachments/assets/44cdbf55-c860-4911-ad94-d195e03f5390)

**Comment by vxlcoder** [comment]
this should work now!

**Comment by jlampel** [comment]
Awesome! Works really well!
