### ISSUE TITLE
Increase vert hitbox for PolyPen tweak

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1356]
Being able to just click and drag on any vert to tweak it in PolyPen is hugely helpful. Right now, I find myself very often missing the hitbox by just a few pixels though while working. If that could be bumped up by about 25%, that should be perfect.

**Comment by vxlcoder** [comment]
ready for testing!

**Comment by jlampel** [comment]
This feels way better! Thank you!
