### ISSUE TITLE
Strokes can create flipped faces

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1358]
In the attached file, add a stroke from the selected verts to the top hairline (maneline?) of the lion's forehead. If the brush isn't so big that only a few faces are created, inevitably some end up flipped in this particular scenario. 

File: https://www.dropbox.com/scl/fi/vd3fbzls7wyekc87gm4wp/lion_strokes-flipped-faces.blend?rlkey=sa9qwyauqqqdvvy8xuili7hjb&dl=0 

![image](https://github.com/user-attachments/assets/356368fa-9fae-49c2-a148-e70cafa06945)

**Comment by vxlcoder** [comment]
this should now be fixed!
