### ISSUE TITLE
[BUG] polystrips brush size UI not showing

### ISSUE THREAD

**Issue by byAndrewsDesign** [CGCookie/retopoflow#1361]
Retopoflow Version: 3.4.3

Blender Version/Hash: 4.3

Platform Version/Distribution: PC Win10

&nbsp;

**Issue:**

The brush size UI doesn't show when using the polystrips tool. for me it instead focuses/ zooms in to selected faces or the whole object. It does however actually change the brush size. I just can't see it

&nbsp;

**How to Reproduce:**

- select polystrips tool, hit f

It displays when disabling what I think is a (blender default?) hotkey

![image](https://github.com/user-attachments/assets/a02f2bd6-2fbe-4211-81ed-54fbb44ecdf2)

**Comment by jfranmatheu** [comment]
In the [docs ](https://github.com/CGCookie/retopoflow/blob/master/docs/keymap_editor.md) you have info about how you can change the default keys of the addon to avoid conflicts, by using the `RetopoFlow Keymaps Editor`.

Once you are in the editor you can click the 'Change brush radius' key config and set one of your like.

![image](https://github.com/user-attachments/assets/de4d3d99-31bc-4746-9cd3-0b28ff28dee5)
![image](https://github.com/user-attachments/assets/3e043756-6a62-4527-ad2f-5a03872ae8c3)
