### ISSUE TITLE
[BUG] Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by esbowman** [CGCookie/retopoflow#1363]
Was having difficulty adding a knife cut so was using the mouse wheel to zoom out so it was within view. When zoomed in, the knife was not allowing me to add a point to the edge. After zooming out I added a point, but it crashed. 

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.4.3
- Build: CG Cookie built for GitHub
- Blender: 4.02.3 blender-v4.2-release 2024-10-14
- Platform: Windows, 10, 10.0.19045, AMD64, Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
- GPU: {'backend': 'OPENGL', 'device': 'NVIDIA', 'vendor': 'NVIDIA Corporation', 'renderer': 'NVIDIA GeForce RTX 3080/PCIe/SSE2', 'version': '4.6.0 NVIDIA 555.85', 'compute_shader_support_get': True, 'hdr_support_get': False, 'max_batch_indices_get': 1048576, 'max_batch_vertices_get': 1048576, 'max_images_get': 8, 'max_texture_layers_get': 2048, 'max_texture_size_get': 32768, 'max_textures_frag_get': 32, 'max_textures_geom_get': 32, 'max_textures_get': 192, 'max_textures_vert_get': 32, 'max_uniforms_frag_get': 4096, 'max_uniforms_vert_get': 4096, 'max_varying_floats_get': 124, 'max_vertex_attribs_get': 16, 'shader_image_load_store_support_get': True}
- Timestamp: 2024-12-04 16:36:22.923095

Runtime:

- Undo: insert, select, insert, select, select, insert, select, delete Faces, dissolve Faces, select
- Error Hash: 1633e878be91e47ea27893cdd2636344

Trace:

- EXCEPTION (<class 'TypeError'>): intersect_line_line_2d
-     C:\Users\Eric\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife_insert.py
- 000 0368:_get_crosses() i = intersect2d_segment_segment(p0, p1, c0, c1)
- 001 0194:draw_postpixel() crosses = self._get_crosses(knife_start, self.actions.mouse)
-     C:\Users\Eric\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0147:<lambda>() self._callback_after_navigating.setdefault(name, lambda: fn(self, *args, **kwargs))
- 003 0227:_done_navigating() for fn in fns: fn()
-     C:\Users\Eric\AppData\Roaming\Blender Foundation\Blender\4.2\scripts\addons\RetopoFlow\retopoflow\rf\rf_fsm.py
- 004 0330:modal_main_rest() if not self.actions.is_navigating: self.rftool._done_navigating()
- 005 0374:quick_switch() self.modal_main_rest()
-     .../common\fsm.py
- 006 0169:wrapped() return fn(*args, **kwargs)

```

**Comment by jfranmatheu** [comment]
Thanks for the report!

I'm trying to replicate your issue in all ways possible by combining knife and zooming but so far I could not replicate it after quite some time of trying.

I have some questions:
- Did you trigger it just once?
- Are you able to replicate it again and possibly screen record it?
- Can you post a .blend file where it does trigger?

**Comment by esbowman** [comment]
Yeah I was worried it would be hard to repo. I use your tool a lot so I’ll report back if I see the issue again. This is literally the first time I’ve had retopoflow crash on me, and I’ve used it quite frequently for three years. So great job! Haha

I will say that most of my issues result from zoom level. If I’m too zoomed in I often have an issue with not being able to use the knife tool or select individual vertices but if I zoom out a little I can typically select or cut with the knife tool. There are probably settings that I could change to fix that behavior. 

Unfortunately I’m not allowed to send the blend file as it features an unreleased product but will see if I can repro. Thank you!

**Comment by jfranmatheu** [comment]
If you used specific settings please let us know so we can match that in our tests. Also, what scale do you work with?

**Comment by esbowman** [comment]
Almost always working with Imperial and inches in Blender. I can change to cm if that's a known issue. I like the metric system better anyway, but have it defaulting to that for easy measurement of assets. 

I did just record myself having some issues selecting vertices and cutting with the knife tool. Can I email this to you? Don't want to post it publicly.

**Comment by jfranmatheu** [comment]
> Can I email this to you?

You can send it to [retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com)

**Comment by jfranmatheu** [comment]
Thanks for the info and video @esbowman I could replicate it!

https://github.com/user-attachments/assets/0ea527b8-0075-4f9b-8f3d-9ad242dd54ff

I tried to see if mesh overlapping and angle had its role in the issue but certainly it seems more related to the view distance relative to the object as stated in the report

**Comment by esbowman** [comment]
I assume you don’t know the root cause just yet, but do you think it’s related to scene units?

 I forgot to set my project to meters on my last retopology session. Will try again soon though.

**Comment by jfranmatheu** [comment]
> but do you think it’s related to scene units?

Does not seem related to it

**Comment by jfranmatheu** [comment]
Ok I just debugged it and detected what the issue is really about. Looks like if an edge is not fully visible on screen it won't be taken into account for the knife tool, so unless both ends of the edge are effectively visible, it won't work.

Here a video to demonstrate it:
https://github.com/user-attachments/assets/260e36ff-ba9f-4f5a-bfdf-12b74325d805

**Comment by esbowman** [comment]
Ahhhh. That makes sense. Well at least I'll know that going forward. Thanks for updating.

**Comment by jfranmatheu** [comment]
@esbowman can you test the attached RF build and confirm if it works for you? thanks in advance

[RetopoFlow_v3.4.4.zip](https://github.com/user-attachments/files/18115114/RetopoFlow_v3.4.4.zip)

**Comment by jfranmatheu** [comment]
@esbowman sorry, the build I made with the RF builder might be badly generated, i will check why.

At the moment, if you are used to git, you can try to checkout this commit https://github.com/CGCookie/retopoflow/commit/d2784aca54d7888842da612068a708e3d935f2df or the `v3.4.4` branch and give it a try.

Otherwise here it is the raw project which should work for you:
[retopoflow v3.4.4.zip](https://github.com/user-attachments/files/18153102/retopoflow.v3.4.4.zip)

**Comment by esbowman** [comment]
Thank you so much for the quick reply. Will give this a shot today and
report back!

**Comment by esbowman** [comment]
So far, this definitely seems to have fixed the issue. Thank you! 

I have also noticed however that a similar issue is present when trying to select edges. 

For example:
- Select Polypen
- Zoom into an area in which the edge extends beyond the window boundary
- Try to select the edge...you likely won't be able to. 
- Zoom out so that you see the extents of the edge and you are then able to select. 

Do you see this behavior as well?

**Comment by jfranmatheu** [comment]
@esbowman Yes, I confirm this behaviour in both: Select and PolyPen tools. I will open another issue from your comment
