### ISSUE TITLE
Consider adding Average method for Spans in Strokes

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1364]
Most of the time when I'm working with Strokes, I want the spacing of the newly created quads to be as even as possible. Having that automatically calculated would save time! 

We could use the average of the lengths of the selected edges and use that as the brush size, so that the result forms near-perfect quads. 

![image](https://github.com/user-attachments/assets/908e0676-ed70-4877-9b45-5f009566aeca)

![image](https://github.com/user-attachments/assets/990ca8a6-c1b7-478b-b221-bf4c4ea5d4ab)

Of course, this method would not work at all when there is a brand-new stroke with no connected geometry, so in that case it would fall back on a default count like the Fixed method has.

**Comment by vxlcoder** [comment]
easy to add.  ready for testing!

**Comment by jlampel** [comment]
Oh man, this is such a big quality of life improvement. I rarely need to adjust the count afterwards now. Thank you!!
