### ISSUE TITLE
Brush size doesn't match quad size in Strokes

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1365]
The Strokes brush size doesn't really match the resulting quad size, which makes it really hard to guess how big or small I should make it when drawing a stroke. 

Here is the brush size next to the size of the quad it produces:

![image](https://github.com/user-attachments/assets/82294b47-fdfb-46fe-b8b1-fd398d93c7bc)

It doesn't need to be exact, but cutting the brush size in half looks like it would be a lot closer to the right size. 

It also seems to have a slightly different relationship to the size of new edges:

![image](https://github.com/user-attachments/assets/9ff3003c-18a7-4b9f-9b09-651ff7209746)

So even if I draw close to a perfect square, I get an uneven result:

![image](https://github.com/user-attachments/assets/283fd01f-14a8-472c-86b7-3d99ac48fcbf)

**Comment by vxlcoder** [comment]
ah, this might be due to how I'm computing the initial number of segments... will work on this more.

not sure about straightness. will check in on this too
