### ISSUE TITLE
RetopoFlow object rotation cleared when opening backup file via RetopoFlow menu

### ISSUE THREAD

**Issue by kirkjaney** [CGCookie/retopoflow#1367]
Hello Im having an issue with the retopo program and Im having a difficult time trying to figure things out.... Whenever I reopen a file that I worked on from the previous day I noticed retopoflow always flip the source mesh and the new geometry up seperating it from the rest of the model. Is it possible to stop it from doing this every time? I can simply rotate it back down but now Im having a hard time realigning the body suit with the body. I've included a photo for you to better see the issue I'm having. As soon as I open up a saved file in retopoflow it immediately flips the source mesh and new geometry up!
<img width="2560" alt="Screenshot 2024-12-08 at 11 46 27 PM" src="https://github.com/user-attachments/assets/bb344096-5665-4971-9985-c1bfb4f57313">

**Comment by jfranmatheu** [comment]
Hello @kirkjaney , thanks for the report.
Can you send a .blend file where this happens to [retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com) with the issue number in the subject, so we can analyze it?

**Comment by jlampel** [comment]
I have not yet been able to replicate this issue with the file, whether saving while RetopoFlow is running or after exiting, but I did notice that the 'Extract3' mesh has two loose verts far above the head, which is very likely to cause some weirdness. It would also be worth applying scale and rotation. Does doing those three things fix the problem?

**Comment by kirkjaney** [comment]
Download full resolution images
Available until Jan 10, 2025
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAZJxZPYTM_i0ptN78HZmIt8zPN7eAakG_uDjKhMlhS-36JECZA_sfOCe%2F%24%7Bf%7D%3Fo%3DAqAgmY639vY2OnH8-CTS9YiHaSyaVijI8CY0RQRcwg6B%26v%3D1%26x%3D3%26a%3DCAog0YMQeIbtn1eVEQLpzezE_BRqkfGal6vTHliQ_3rJGpsSdhCrupyluzIYq8qX-cQyIgEAKgkC6AMA_ymiljRSBDM83t5aBOx84J5qJbTm2HERLAYZlC6VQb9haqo_TomUMb_UlA8pIzCbaFwnIVC7Px1yJT2L8uCd7MMPWOabl5AT5ujhPA40pqecKT2sLi6VXgQc-e_8aL0%26e%3D1736494671%26fl%3D%26r%3DB4607DEA-951D-4B83-B5FA-5E45D32DE573-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DFF9617DB-77BD-4952-BE24-03F6F8EFA1B9%26p%3D71%26s%3DQR4y85Fnv_hgzGuQnYeYNBr5jSo&uk=HeF2nzg7rlHOKPrz6fTlaQ&f=Images.zip&sz=1136884>Hello Jonathan I was able to demonstrate the issue Im having in a quick 34 second video. What’s happening is the following

I select the drop down retopoflow option in the top left

I select “open” 

then retopoflow brings the model into blender and I have to zoom out to see the model (I don’t know why the camera angle changes)

but when Im zoomed out far enough to see the whole model “Extract3” and “Retopoflow” are automatically oriented facing up. The belly side of “Extract3” is facing up

In case you can’t see the video I also attached a picture. It just shows how retopoflow likes to separate parts and pitch parts up that I previously worked on 

Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAb5AA_FzNwxt0my4qYRsstK7rtuHAcflcbbKzBt6poIGKECzUz4Hhlb5%2F%24%7Bf%7D%3Fo%3DAk9OxmngQmhRGvb6Zew9w-Cv20X58HR3-qZCw6GW0aR2%26v%3D1%26x%3D3%26a%3DCAognnAvhgyx5LNeiV3scQfmgiANvxM2WZWbKOVon_jOsIkSdhCbu5yluzIYm8uX-cQyIgEAKgkC6AMA_wEfKwlSBLuu24daBAeGVvlqJXuVcnuDh6PTZH9AMXuWvGxWc7Phd7L8z6Hflny5r39sazG1FZ5yJbBbdGKXei_6kRyiwT0oxCR2pVkbj4WRFVOHg92C3VfM0eZL2bk%26e%3D1736494671%26fl%3D%26r%3DBE8E1788-9F69-4CF3-A231-A5E909DE6DB8-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DFF9617DB-77BD-4952-BE24-03F6F8EFA1B9%26p%3D71%26s%3DvY3imezBaM3CvkJcBIeSSCZ0Mso&uk=ytDcU7jioQAQDN4R9GDSOg&f=Screen%20Recording%202024-12-11%20at%202.05.58%E2%80%AFAM.mov&sz=53500075>Screen Recording 2024-12-11 at 2.05.58 AM.mov
53.5 MB
￼

**Comment by jlampel** [comment]
Oh, I see! This only happens when opening the file via the RetopoFlow menu and not Blender's File menu. 

@jfranmatheu If I rename this file to `retopoflow_backup.blend` and place it in my Users folder (I'm on Windows, and that's where RF keeps the backups.... which is probably worth revisiting as well), it loads the file just fine if opened normally in Blender but with the RetopoFlow object's rotation cleared if opened via the RetopoFlow menu. Could you investigate further when you have a chance?

**Comment by jfranmatheu** [comment]
Thanks for the hint on the backup file location @jlampel I will take a look at it as soon as possible

**Comment by kirkjaney** [comment]
Mr. Jonathan, I really appreciate you for your help. I didn’t realize it was such a simple fix. Thanks again my friend KirkOn Dec 11, 2024, at 4:41 PM, Jonathan Lampel ***@***.***> wrote:﻿
Oh, I see! This only happens when opening the file via the RetopoFlow menu and not Blender's File menu.
@jfranmatheu If I rename this file to retopoflow_backup.blend and place it in my Users folder (I'm on Windows, and that's where RF keeps the backups.... which is probably worth revisiting as well), it loads the file just fine if opened normally in Blender but with the RetopoFlow object's rotation cleared if opened via the RetopoFlow menu. Could you investigate further when you have a chance?

**Comment by jfranmatheu** [comment]
@kirkjaney Can you try this RF build and tell me if it works for you and preserves the rotation? (attached)
[Uploading RetopoFlow_v3.4.4.zip…]()

**Comment by jlampel** [comment]
I wonder why rotation is touched by RetopoFlow here when, as far as I know, we're only scaling the objects. It makes sense that, in the event of a crash, some might be the wrong scale and the recover auto-save would correct for that. @vxlcoder can correct me if I'm wrong, but I can't find where rotation is involved at all in entering or exiting RetopoFlow mode (besides new targets being rotated to align with the active object if that's chosen), so I think we can safely leave that alone during recovery.

**Comment by jfranmatheu** [comment]
@jlampel This is what happen

Note that the expected matrix is different from the one that is finally applied to the objects, specially in the target mesh object (Retopoflow). And even tho the object has rotation, the matrix does not represent that rotation actually, kind of an Schrodinger cat in there heh, so when we apply an scale to the matrix, as the matrix does not represent any rotation, the actual rotation is cleaned up afterwards.

```py
Extract3: 
	- rotation_euler (before)
<Euler (x=1.5708, y=-0.0000, z=0.0000), order='XYZ'>
	- rotation_euler (after)
<Euler (x=1.5708, y=-0.0000, z=0.0000), order='XYZ'>
Extract3: 
	- matrix_world (before)
<Matrix 4x4 (1.0556, 0.0000,  0.0000, 0.0000)
            (0.0000, 0.0000, -1.0556, 0.0000)
            (0.0000, 1.0556,  0.0000, 0.0000)
            (0.0000, 0.0000,  0.0000, 1.0000)>
	- matrix_world (after)
<Matrix 4x4 (0.0100, 0.0000,  0.0000, 0.0000)
            (0.0000, 0.0000, -0.0100, 0.0000)
            (0.0000, 0.0100,  0.0000, 0.0000)
            (0.0000, 0.0000,  0.0000, 1.0000)>
	- matrix_world (expected)
<Matrix 4x4 (0.0095, -0.0000,  0.0000, 0.0000)
            (0.0000,  0.0000, -0.0095, 0.0000)
            (0.0000,  0.0095,  0.0000, 0.0000)
            (0.0000,  0.0000,  0.0000, 1.0000)>
RetopoFlow: 
	- rotation_euler (before)
<Euler (x=1.5708, y=-0.0000, z=0.0000), order='XYZ'>
	- rotation_euler (after)
<Euler (x=0.0000, y=-0.0000, z=0.0000), order='XYZ'>
RetopoFlow: 
	- matrix_world (before)
<Matrix 4x4 (1.0000, 0.0000, 0.0000, 0.0000)
            (0.0000, 1.0000, 0.0000, 0.0000)
            (0.0000, 0.0000, 1.0000, 0.0000)
            (0.0000, 0.0000, 0.0000, 1.0000)>
	- matrix_world (after)
<Matrix 4x4 (0.0095, 0.0000, 0.0000, 0.0000)
            (0.0000, 0.0095, 0.0000, 0.0000)
            (0.0000, 0.0000, 0.0095, 0.0000)
            (0.0000, 0.0000, 0.0000, 1.0000)>
	- matrix_world (expected)
<Matrix 4x4 (0.0095, -0.0000,  0.0000, 0.0000)
            (0.0000,  0.0000, -0.0095, 0.0000)
            (0.0000,  0.0095,  0.0000, 0.0000)
            (0.0000,  0.0000,  0.0000, 1.0000)>
```

**Comment by jfranmatheu** [comment]
Ok I did a quick test... what if we manually update the rotation... will it trigger an update in the matrix world?

short answer: no

- Looks like if the object is not visible in the viewport, all changes over transform props are not propagated to the transform matrix... so when RF recovers that and updates the matrix... as the matrix does not have any rotation applied (rotation was applied while the object was hidden in viewport), then updating the matrix is updating the rotation and making it looks like it is reset.

![image](https://github.com/user-attachments/assets/8cfcda81-0106-43d9-8cae-a4766d91157a)

Mystery solved!

**Comment by jfranmatheu** [comment]
So far,
1. It looks like an expected behavior by Blender so we can conclude is a user issue, because objects that are hidden from viewport are not taken into account for updates, depsgraph, etc, as far as I know.
2. Since it is something not so obvious nor common-knowledge and hidden from base-users as they can't see the transform matrix unless accessed via console, we can also conclude it is a Blender issue (likely UI/UX issue as they could block certain editing from happen or add some feedback about it).
3. I have finally patched that in RF, so in case we detect a mismatch in the rotation we just recover it. https://github.com/CGCookie/retopoflow/commit/7bd68f9b1b047c643e010d188585868b40dabd96
