### ISSUE TITLE
Contours no longer bridges between cuts

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1370]
I know this tool is still a WIP, but I think this was already working at some point, so I'm logging this just in case it's a regression. 

Contours does not bridge between cuts. In the example below, I created one cut at the top, and with it still selected, created another cut below. The first few attempts actually result in nothing happening, but after a few tries another cut will be created but without being connected to the selection. 

![image](https://github.com/user-attachments/assets/94d8e667-578d-4914-883e-8fddb1147a95)

**Comment by vxlcoder** [comment]
was anything reported to the console? that's a strange issue

**Comment by vxlcoder** [comment]
should be fixed!

**Comment by jlampel** [comment]
Confirmed fixed!
