### ISSUE TITLE
T strokes do not work on closed loops

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1371]
T strokes do not work on selections that are continuous or closed loops. Example:

Before

![image](https://github.com/user-attachments/assets/6fb4aa84-13cb-4185-9284-b0e8f7dfdbef)

After

![image](https://github.com/user-attachments/assets/00969f85-ad95-475c-ab46-8b05f11e0639)

As opposed to:

![image](https://github.com/user-attachments/assets/78e1c0d7-0418-4e45-938b-48cd6c528976)

![image](https://github.com/user-attachments/assets/44d8c8a6-3f0e-430d-8fd0-41f9ad420f7c)

**Comment by vxlcoder** [comment]
this should be doable now with commit 711f1c5!

**Comment by jlampel** [comment]
Amazing! Works great!
