### ISSUE TITLE
Strokes: Tweaking and snapping components

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1379]
It would be nice if all of the non-brush tools could share the same behavior for adjusting components, such as tweaking and snapping. Can adjusting components in Strokes be the same as in PolyPen?

**Comment by jlampel** [comment]
Awesome! Along the same lines, it would be great to allow selecting loops while in PolyPen

**Comment by vxlcoder** [comment]
I'm not sure what you mean by "selecting loops while in PolyPen"

**Comment by jlampel** [comment]
Oh! I had thought that regular loop selection (Alt LMB or double LMB depending on navigation preferences) was blocked in PolyPen, but it was just because that's the normal Blender behavior while both edge and face select mode are enabled at the same time, and in Strokes we're not using face select mode. Never mind!

**Comment by vxlcoder** [comment]
tweaking and snapping is now a thing in strokes!

**Comment by jlampel** [comment]
It works, and it's so helpful!
