### ISSUE TITLE
Strokes: t-bridge doesn't attach to expected verts

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#1385]
When bridging a connected set of three verts, the expectation is that if I draw a bridge from the top vert, the vert that the stroke ends on would also become the top vert. Instead, it becomes the bottom vert. Example:

![blender_jrOtUzeEob](https://github.com/user-attachments/assets/f10165ec-b0bf-409d-8e38-67585c8f693a)

It happens every time, so I think it just needs to be flipped.

**Comment by vxlcoder** [comment]
should be fixed!

**Comment by jlampel** [comment]
Looks good to me!
