### ISSUE TITLE
buttons lose icon

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#146]
our button icons are disappearing when they just begin to fall out of the region.  could be blender bug?  this does not happen with normal blender buttons

![before scrolling](https://cloud.githubusercontent.com/assets/3790699/10269608/c8ae652c-6aaa-11e5-882a-d68a6ea3aa7e.png)

![after scrolling](https://cloud.githubusercontent.com/assets/3790699/10269612/db24d9ca-6aaa-11e5-8855-ecab207b4579.png)

![does not happen here](https://cloud.githubusercontent.com/assets/3790699/10269613/e2e51f3a-6aaa-11e5-8a99-0f3bf15a2566.png)

**Comment by carter2422** [comment]
I believe this is a Blender bug. Need to test further and report to devs.

**Comment by carter2422** [comment]
Closing this for being old and almost certainly a Blender bug.
