### ISSUE TITLE
Drawing onto an existing stroke never cuts in the GVert

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#147]
See video: http://cl.ly/dQUx

**Comment by carter2422** [comment]
Likely related, as mentioned in Slack. If you start drawing on a strip and end on another, then the beginning almost never cuts.

Drawing from left to right:
http://cl.ly/dksi
http://cl.ly/dkfl

**Comment by vxlcoder** [comment]
@carter2422 are you still able to repo this?

**Comment by carter2422** [comment]
@vxlcoder I'm getting it every now and then but not very consistently. For example: https://cl.ly/ghIm

Perhaps it has to do with the slight grazing angle?

**Comment by carter2422** [comment]
I can no longer repo this. Considering it closed.
