### ISSUE TITLE
PolyStrips: do not snap inner control points to surface

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#149]
do not snap inner control points for bezier of strip to the model's surface.  fixing this requires switching to screen-space selection, but this would make curves fit to surface in a more predictable manner (possibly "correcting" bug #35)

**Comment by carter2422** [comment]
@vxlcoder I'm removing the milestone on this, maybe we can get this into 1.2.1 though?

**Comment by vxlcoder** [comment]
done!
