### ISSUE TITLE
Switch to use OpenGL 3+

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#150]
once bgl supports OpenGL 3+ API (it may already with 2.76 release), replace all immediate mode drawing code to use newer API.  this means rewriting code to use buffers, shaders, etc.  benefit: much faster rendering (!!!), cleaner render code paths, better integration with new viewport, and it's just a better way to live.

**Comment by carter2422** [comment]
Duplicate of #173
