### ISSUE TITLE
Navigation Fails when system language is not English

### ISSUE THREAD

**Issue by 765563652** [CGCookie/retopoflow#154]
system：win10  64
blender：2.76

When I started contours or Polystrips， can't rotate the view. I reinstall the blender，Let it work on other computers，，But still can't normal operation

**Comment by patmo141** [comment]
What keys/mouse fns do you normally use to rotate the view?

**Comment by 765563652** [comment]
I use the blender's default Settings

**Comment by patmo141** [comment]
Any error messages in the console?

**Comment by 765563652** [comment]
After some try，I found the reason.This plugin does not support Chinese ,I can work normally after change the system language to English ! : )

**Comment by 765563652** [comment]
My English is not very good, can you understand I write

**Comment by patmo141** [comment]
Very interesting!  We will make a separate issue and try and track that down.  Thank you for the report.

**Comment by patmo141** [comment]
Yes your English is better than my Chinese!

**Comment by carter2422** [comment]
@765563652 when you say "System Language", are you referring to your Operating Systems language or Blenders language?

**Comment by 765563652** [comment]
@carter2422  I mean to blender language

**Comment by carter2422** [comment]
I've tracked this down to primarily the `navigation_events` dict, which is used to list out the events to listen for passing through the model. 

Now I just need to figure out how to automatically translate these... Reading up via http://wiki.blender.org/index.php/Dev:Doc/Process/Translate_Blender

**Comment by carter2422** [comment]
Hey @765563652 I've fixed this. Could you give this branch a try? https://github.com/CGCookie/retopoflow/compare/release/1.2.0
