### ISSUE TITLE
Contours Traceback issue

### ISSUE THREAD

**Issue by TheWalshinator** [CGCookie/retopoflow#158]
I'm currently using Blender 2.76 and I keep getting this error after drawing a few lines with Contours
![](http://i.imgur.com/jGT80Ld.png)

**Comment by carter2422** [comment]
Thanks for the report @TheWalshinator. We'll look into it.

**Comment by carter2422** [comment]
@TheWalshinator I have not been able to replicate this. Are you still seeing this error from time to time?

**Comment by carter2422** [comment]
I was not able to replicate the crash but I found the error and fixed it. This will be fixed in v1.2.0.
