### ISSUE TITLE
Sometimes stale caches cause crashes

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#160]
Occasionally the mesh cache won't clear and it'll become invalidated, causing a crash on the next run. It was reported [here](https://cgcookiemarkets.com/forums/topic/retopoflow-1-1-0-crashing/) and I've also experienced this a few times.

**Comment by carter2422** [comment]
I think we need to add some safety checks to clear and recreate the cache if it's invalid somehow.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
