### ISSUE TITLE
Contours and Polystrips will usually crash Blender the next time they're started if selected target object is missing/deleted

### ISSUE THREAD

**Issue by Two-Tone** [CGCookie/retopoflow#162]
This [error](https://i.imgur.com/TOJ2HGE.png) pops up if it doesn't crash.

This [error](https://i.imgur.com/wmeg4fJ.png) pops up before the above and is the only one that pops up if Blender does crash.

**Comment by carter2422** [comment]
Thanks for the report @Two-Tone. I've seen this as well. We'll try and improve it.

**Comment by carter2422** [comment]
Fixed!
