### ISSUE TITLE
Loop Extrude Tool

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#167]
gverts -> gedges, gedges are duplicated, gpatches fill in between

**Comment by carter2422** [comment]
What's this for?

**Comment by vxlcoder** [comment]
ex: the eye of the monster bust (8m15s and 8m35s of monster-bust-polystrips video)

**Comment by carter2422** [comment]
I have some ideas on how to tackle this. I don't think it should be in Polystrips. Probably needs to be a separate tool, or within Edge Patches

**Comment by carter2422** [comment]
Here's a quick demo of how it works in Bsurfaces: http://cl.ly/djVA

This could be a good started point for the tool.

**Comment by carter2422** [comment]
Another video demo for Loop Extrude​: http://cl.ly/eBGd

**Comment by vxlcoder** [comment]
Solved with Strokes!!! :D

**Comment by carter2422** [comment]
Strokes are glorious!
