### ISSUE TITLE
Retopoflow won't show as installed

### ISSUE THREAD

**Issue by George-the-1st** [CGCookie/retopoflow#171]
Attempting to install Retopoflow source code from zip file the way it was described but it simply does not work. In the info screen in blender it simply states " Modules Installed from 'C:\\Users\\Plastwix\\Downloads\\retopoflow_1_1_0.zip' into 'C:\\Users\\Plastwix\\AppData\\Roaming\\Blender Foundation\\Blender\\2.76\\scripts\\addons' ()
". However when I go to search for retopoflow it does now show up. I think I fixed this problem in a previous version with a simple renaming but that doesn't seem to be working anymore.

**Comment by carter2422** [comment]
@George-the-1st did you uninstall previous versions first? Also, have you tried restarting Blender to check if it then works? Sometimes Blender's add-ons don't refresh very well when installing.

**Comment by George-the-1st** [comment]
I have done both of these things. It has not fixed the problem.

**Comment by carter2422** [comment]
Try installing it manually then by copying the extracted folder into  `C:\Users\Plastwix\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons`

**Comment by George-the-1st** [comment]
That doesn't seem to be working as well.

**Comment by George-the-1st** [comment]
I tested it with a few other add-ons just now and they seem to be working. It seems to be this particular add-on that is the problem

**Comment by carter2422** [comment]
@George-the-1st I assume you're downloading from this repo as opposed to downloading the version from the Blender Market? GitHub packages the .zip differently than Blender needs, so that could be issue.

What is the folder structure of the extracted folder? 

It should be like this: http://cl.ly/drii

**Comment by George-the-1st** [comment]
ah, I now know the problem. The folder (and zip I tested it with both) has to be named EXACTLY: retopoFlow  . It must have all lowercase except for the F that has to be a capital. Now it understands what I'm telling it to grab from. Gotta love that code. Anyways, thanks for showing me how it is supposed to be. Now I'm going to go on CGCookie and learn how to use the darn thing and then I'm going to go to the other two courses that have retopology work in them (according to the search system) and learn from there. Thanks. for this plugin and thanks for teaching on that site. It's a great way to slingshot me past these problems.

**Comment by carter2422** [comment]
Good to hear you got it fixed! It *shouldn't* require exact naming, so we may need to refine that bit of the codebase. 

If RetopoFlow works out well for you I hope you'll consider [purchasing a license](https://cgcookiemarkets.com/all-products/retopoflow) if you haven't already :)

**Comment by George-the-1st** [comment]
I wish I could but I can't afford a 70 dollar expenditure at this time (I should start selling more work). Ironically my spare cash is going to a CGcookie premium account so I'm still supporting you. I just don't  have enough reserves to make a 70 dollar purchase. One day...one day....but anyways, again thank you.

**Comment by carter2422** [comment]
Fair enough :+1: Thanks for the support!
