### ISSUE TITLE
IndexError: List Index out of range

### ISSUE THREAD

**Issue by 3DEsprit** [CGCookie/retopoflow#172]
After getting this "List Index" error, I can no longer draw any strips. The first two times, it gave a warning type error, but after it then acted like it worked, allowing me to draw strokes without error, but not actually creating the strips. 

I've included a screenshot of exactly what I was doing, where the exact original polystrips mesh existed. I had been adding more strips to it, and as I progressed submitted so not to lose any progress. I did not change the name, or anything else. This was simply submitting strips while it was working, and going right back in to add more to the existing mesh.

When I went to add a new strip, this error came about. I was not using the existing strip mesh to bind the strip either. The strip I was laying down is marked with the 3D cursor, and the direction outlined with a GP line, showing exactly where I went. 

![index](https://cloud.githubusercontent.com/assets/3156278/11411797/d87ebc96-9399-11e5-8684-0c77d9c5eef8.jpg)

The Exact Error is:

Traceback (most recent call last):
  File "C:\Users\viles\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\retopoFlow\modaloperator.py", line 244, in modal
    nmode = self.FSM[self.fsm_mode](context, eventd)
  File "C:\Users\viles\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\retopoFlow\op_polystrips\polystrips_ui_tools.py", line 101, in modal_sketching
    self.polystrips.insert_gedge_from_stroke(p3d[:next_i_p], False)
  File "C:\Users\viles\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\retopoFlow\op_polystrips\polystrips_datastructure.py", line 1798, in insert_gedge_from_stroke
    gv0 = [gv for gv in self.extension_geometry if gv.is_picked(stroke[0][0])]
  File "C:\Users\viles\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\retopoFlow\op_polystrips\polystrips_datastructure.py", line 1798, in <listcomp>
    gv0 = [gv for gv in self.extension_geometry if gv.is_picked(stroke[0][0])]
IndexError: list index out of range

location: <unknown location>:-1

**Comment by patmo141** [comment]
@vxlcoder this looks to me like the stroke is empty.  Perhaps when the stroke is pruned of points that do not hit the mesh it ended up with an empty stroke.

**Comment by punkoffice** [comment]
I get "List index error" as well with one of my models.  Its a 200k poly 3D scan, but its been polished and its all one connected mesh (no separate eyes or tounge).  This happens as soon as I try to lay down a polystrip around the eyes.  It freezes Blender and I have to close the whole application.  I can lay polystrips on other areas like the forehead, but it crashes when going around the eyebrow.
![list_index_error](https://cloud.githubusercontent.com/assets/5295016/14402458/c87a6a34-fe79-11e5-9de0-e83b77035dcb.jpg)  This is with Retopoflow 1.2.0 and Blender 2.77a

**Comment by patmo141** [comment]
Can you upload that blend or even just the parts around the eyebrows?

**Comment by punkoffice** [comment]
Sure thing.  You can download the blend file here [http://www.punkoffice.com/downloads/polystrips.zip](url)   Its a 14MB file.

**Comment by patmo141** [comment]
Thanks, I happen to have a few moments right now I'll see if I can tackle this

**Comment by patmo141** [comment]
I'm having trouble reproducing this error.  Am I in the right area. I didn't see any non manifolds near the eybrows.
![image](https://cloud.githubusercontent.com/assets/2917743/14403797/0131e7d6-fe33-11e5-9c69-72acba43d7c8.png)

**Comment by patmo141** [comment]
I think I need to see the error that is beneath the 2nd popup there which looks related to "none type has no attribute dot" in polystrips_datatructure.py. Can you get this to happen consistently?

**Comment by punkoffice** [comment]
Here's a video of me trying to put polystrips around the eye and mouth [https://youtu.be/v7S0_cWWIw0](https://youtu.be/v7S0_cWWIw0)

**Comment by patmo141** [comment]
awesome thanks. This is the error we are looking for.  We have come across this one in the past.[image](https://cloud.githubusercontent.com/assets/2917743/14403822/cc82a3e8-fe34-11e5-9d29-aa6709dd2481.png)

**Comment by patmo141** [comment]
ok, interesting.  You error message gives me a line that's different in the current 1.2.0 release. sometimes we see old code stuck around that does not uninstall (I tihnk it's the cached compiled python code of the previous version).  Try unstalling v1.2.0, saving unser settings, restarting blender, then reinstalling v1.2.0.

![image](https://cloud.githubusercontent.com/assets/2917743/14403871/4b8e8c3c-fe36-11e5-8a76-1e3c7866671c.png)

**Comment by patmo141** [comment]
Oh, as an experiment, if you go into edit mdoe and "make normals consistent" on your source mesh before you update your addon, see if that fixes it.  Because the error we were having was where the ray cast returns a Hit on the mesh, but does not return a surface normal for that hit which is quite strange.

**Comment by punkoffice** [comment]
ok, I reinstalled it and made sure to recalculate normals.  Its definitely better now.  Thanks mate!  I can lay polystrips without crashing. I do get an error sometimes when creating a circle around the eye then trying to fill it 
![fill](https://cloud.githubusercontent.com/assets/5295016/14404101/1eb15998-feb2-11e5-8a05-18e5259bfbd5.png)
Its quite possible I'm doing something wrong with where I'm placing things and the area I'm trying to fill, but I should get some kind of meaningful message

**Comment by patmo141** [comment]
Please open a separate issue for the circular patch fill.

**Comment by patmo141** [comment]
closing this old issue :-)
