### ISSUE TITLE
Refactor for OpenGL 3.2+

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#173]
Blender will soon require OpenGL 3.2+, meaning we need to refactor anything utilizing 1.x: http://lists.blender.org/pipermail/bf-committers/2015-November/046243.html

For example, anything utilizing `glBegin` and `glEnd` will have to be refactored.

**Comment by carter2422** [comment]
OpenGL refactor docs for Blender here: http://wiki.blender.org/index.php/Dev:2.8/Source/OpenGL

**Comment by nortikin** [comment]
it is cool, and many job (specially for Sverchok or retopoflow)  all will be break at one moment

**Comment by vxlcoder** [comment]
this is mostly taken care of now, but will be addressed more when blender 2.8 is out.  closing for now.
