### ISSUE TITLE
Installation trouble

### ISSUE THREAD

**Issue by bpwmd** [CGCookie/retopoflow#174]
How do you Install this from this file??????

**Comment by bpwmd** [comment]
the whole thing

**Comment by carter2422** [comment]
You have to select the .zip file that you downloaded. If your browser automatically extracted it then you'll need to recompress it first.

Also, please post support questions on the forum. This issue track is just for bug reports.

The forum is here: https://cgcookiemarkets.com/all-products/retopoflow/?view=support
