### ISSUE TITLE
Bridge Tool

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#179]
The Bridge Tool is needed in order to manually fill two Contour strokes, such as this: 

![screen shot 2015-12-13 at 8 01 12 pm](https://cloud.githubusercontent.com/assets/1648631/11771327/47d332b4-a1d4-11e5-9e8a-59dd08a3d9dc.png)

**Comment by carter2422** [comment]
I'd like to see this work by simply selecting two disconnected strokes and connecting them by pressing `F`

**Comment by vxlcoder** [comment]
done!

![image](https://user-images.githubusercontent.com/3790699/43234758-1497a768-904c-11e8-8501-98253fb433b2.png)

![image](https://user-images.githubusercontent.com/3790699/43234768-1fc22af0-904c-11e8-9657-95846f7cd080.png)

**Comment by carter2422** [comment]
This works great! Only issue seems to be the inability to cut into the bridges area, via #552. Closing!
