### ISSUE TITLE
Enable problem for 1.1.2

### ISSUE THREAD

**Issue by fxswan** [CGCookie/retopoflow#182]
![blender 1 1 2 enable error](https://cloud.githubusercontent.com/assets/16266218/11827523/2eeaa618-a339-11e5-952d-85a3b30bb99f.png)
Loaded ok, but when you try to enable it it gives a missing file error in the apps.....retopflow folder

**Comment by carter2422** [comment]
Please copy the error message here.

**Comment by carter2422** [comment]
@fxswan can you try restarting Blender and then enabling? I'm guessing this is a stale path issue.

**Comment by fxswan** [comment]
Thanks Jonathan.....found that if I do a remove 1.1.1 first, then reload my blender, then reload the 1.1.2  it worked on the second go around. Not sure why it took twice but sounds a lot like what we have to do in aircraft simulation (I work for FedEx Training) when we do a Visual/Hud software update...lol....looking forward to checking it out...

thanks again

**Comment by fxswan** [comment]
Done...ty again
 
Date: Tue, 15 Dec 2015 18:03:41 -0800
