### ISSUE TITLE
Brush Enhancements

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#184]
Currently, brush radius checks all verts in the mesh.

```
for i_mv,mv in enumerate(self.dest_bme.verts):
            d = (mx*mv.co-hit_p3d).length / self.stroke_radius
```
1.  This will find verts on thin parts of meshes that user may not want
2.  not extremely speedy.  Less of an issue because our Retopo "problem" by definition is low density meshes.

Possible Enhancements: 
-Use accelerated data structure like KD tree
-Use mesh connectivity
-Use face normals to filter out faces which are not facing the user

**Comment by carter2422** [comment]
A combination of mesh connectivity and normals seem like great enhancements, particularly for thin models where you potentially might work on both sides at the same time.

**Comment by vxlcoder** [comment]
- acceleration structures used
- ability to mask hidden faces
- not using connectivity, but an interesting idea for another tool i have on the back burner.... :)
