### ISSUE TITLE
assert False with check_source_target_objects() on startup

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#186]
On startup the `check_source_target_objects()` throws an assert error while running `get_settings()`

```
Traceback (most recent call last):
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/lib/common_utilities.py", line 83, in check_source_target_objects
    settings = get_settings()
  File "/Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/lib/common_utilities.py", line 76, in get_settings
    assert False, 'could not find non-"lib" folder'
AssertionError: could not find non-"lib" folder
```

**Comment by patmo141** [comment]
Is this new since the app handler?

**Comment by carter2422** [comment]
Yes @patmo141, I just can't figure out what's causing it. Initially I thought it was because the handler was running before the function was imported.

**Comment by patmo141** [comment]
I think it's looking for settings before settings are registered :-)  About
to test

**Comment by patmo141** [comment]
Ok, darn.  However, the if/else tab spacing in the get_settings() fn looks funky

**Comment by carter2422** [comment]
> Ok, darn. However, the if/else tab spacing in the get_settings() fn looks funky
Feel free to do a  cleanup commit, just keep it separate from any functionality changes please.
