### ISSUE TITLE
Support for Retina and 4k displays

### ISSUE THREAD

**Issue by JacquesLucke** [CGCookie/retopoflow#187]
Since a few versions Blender has a feature called "Virtual Pixel Mode" that allows you to double the size of all the ui elements. This mainly exists because 144 (the max limit for the dpi value) is still to small on those screens. (I only have a 4k screen to test it here, but should be the same with retina)

To support those screens I suggest to implement two helper functions:

```python
import bpy

def get_dpi_factor():
    return get_dpi() / 72

def get_dpi():
    system_preferences = bpy.context.user_preferences.system
    factor = getattr(system_preferences, "pixel_size", 1)
    return system_preferences.dpi * factor
```

The 72 is the default dpi value. I use getattr here so that this function as backward compatible to older blender versions that don't have this feature yet. 

You will need both function for different purposes. Everywhere you draw text you should use the *get_dpi()* function.
Margins, rectangle dimensions, ... should be multiplied with the value returned by *get_dpi_factor()*.

**Comment by carter2422** [comment]
Thanks for the suggestion @JacquesLucke! I'll take a look at this. Unfortunately we don't have a 4k or retina screen to test on, but I'll try and work something out.

**Comment by JacquesLucke** [comment]
You're welcome!
It is easy to test this without one of those high density screens:

![test dpi without 4k screen](https://cloud.githubusercontent.com/assets/5881326/12048584/3f9b4530-aedd-11e5-8309-4a2ae4140573.png)

**Comment by vxlcoder** [comment]
@JacquesLucke perfect!  thanks!

**Comment by carter2422** [comment]
Thanks @JacquesLucke! That worked beautifully.

**Comment by JacquesLucke** [comment]
I'm glad that I could help you. :)
