### ISSUE TITLE
Conflict with Blend4Web when both enabled.

### ISSUE THREAD

**Issue by boyleo** [CGCookie/retopoflow#193]
Enable both Retopoflow and Blend4Web SDK, save preferences, restart blender.
The interface changes to become like this issue
https://github.com/CGCookie/retopoflow/issues/183

clicking Retopoflow gives repeated error like this many times

Traceback (most recent call last):
  File "/home/user/.config/blender/2.76/scripts/addons/retopoflow/interface.py", line 92, in draw
    if settings.retopoflow_panel_settings:
AttributeError: 'B4WPreferences' object has no attribute 'retopoflow_panel_settings'

location: <unknown location>:-1

Disable Blend4Web, save prefs and restart, Retopoflow gets back to normal.

System:
Ubuntu Studio 14.04
Blender 2.76b both Steam & BuildBot versions
Retopoflow 1.1.3
Blend4Web SDK 15.11

**Comment by carter2422** [comment]
This is very interesting...

**Comment by carter2422** [comment]
Likely related if not identical to #183

**Comment by carter2422** [comment]
We're investigating this @boyleo, thanks for reporting.

**Comment by boyleo** [comment]
Sometimes, when both addon enabled, trying to click the addon checkboxes to disable any of them resulted in Blender terminated without warning.

**Comment by carter2422** [comment]
@boyleo can you give this version a try? https://github.com/CGCookie/retopoflow/tree/issue/183

**Comment by boyleo** [comment]
Same error happens.

**Comment by boyleo** [comment]
Oh wait, that's another branch? let me try remove the old one.

**Comment by boyleo** [comment]
Yes! that fix it.

**Comment by vxlcoder** [comment]
@boyleo great!

**Comment by carter2422** [comment]
Whoop!

**Comment by YuriKovelenov** [comment]
Hi guys, so you believe there is nothing to fix on the Blend4Web side?

**Comment by vxlcoder** [comment]
@YuriKovelenov as far as we can tell, it was a bug in retopoflow
