### ISSUE TITLE
Kill Contours and Revive it in God-Mode

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#196]
Contours needs to be killed and then revived with the new, more unified data structure like Polystrips. This would then enable all sorts of cool, magnificent things.

**Comment by carter2422** [comment]
![screen shot 2015-12-30 at 10 32 57 pm](https://cloud.githubusercontent.com/assets/1648631/12061184/51fec23e-af45-11e5-8ed4-552c1c5ffbe7.png)

**Comment by patmo141** [comment]
Perfect implementation would be this.
1. Tighter integration of all tools with bmesh, so patches, polystrips and contours just become interfaces to the same retopo datastructure. Allowing seamless switching between those tools.  This will take a mastermind, or several master minds to accomplish.  @gfxcoder has been lobbying this approach for a while.

Initial implementation will be as follows.
2.  Initially, I will hack contours modal and superficial datastructute to output edge patch boundaries or polystrips boundaries and see how that goes.

**Comment by vxlcoder** [comment]
done!
