### ISSUE TITLE
Addon actvation error cannot import name 'check_source_target_objects'

### ISSUE THREAD

**Issue by rt974** [CGCookie/retopoflow#205]
Downloaded the github version.
Importing the zip in blender 2.76 rc3

Then when i click on the checkbox there is this message :

---------------------------------------------------------------

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.76\scripts\modules\addon_utils.py", line 324, in enable
    mod = __import__(module_name)
  File "C:\Users\renau\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\retopoflow-master\__init__.py", line 43, in <module>
    from .lib.common_utilities import bversion, check_source_target_objects
ImportError: cannot import name 'check_source_target_objects'

---------------------------------------------------------------

**Comment by carter2422** [comment]
You likely just need to restart Blender @rt974. This happens sometimes dues to some files being stale, not being fully overwritten, or something otherwise conflicting with Blender. 

Restart Blender and then it should work.

**Comment by carter2422** [comment]
Did restarting Blender work @rt974?

**Comment by carter2422** [comment]
Closing due to silence and seemingly fixed.
