### ISSUE TITLE
Concave quads cause contours failure

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#209]
concave quads can cause the same quad to be crossed twice, causing a contour cut faulure.  One solution is to triangulate everything.  Another would be to triangulate only the concave quads.  There is a bmesh function to do this

https://www.blender.org/api/blender_python_api_2_76_release/bmesh.ops.html?highlight=concave#bmesh.ops.connect_verts_concave

a good test model is Cobra.blend. Apply the multires and then use contours.  many failures happen

**Comment by carter2422** [comment]
Any thoughts on a good way to test this and then split concave faces on the source if needed @patmo141?

**Comment by patmo141** [comment]
I think we just split the concave quads on the bmesh.  Concave quads can be considered like non manifolds or holes. Basically, they shouldn't be there.  We never write the bmesh back to source, so it's fine for this task I think.

**Comment by carter2422** [comment]
Holy crap. That's night and day difference. Previously the _Cobra.blend_ file was absolutely unusable with Contours, now it works perfectly: 
![screen shot 2017-01-06 at 12 59 24 pm](https://cloud.githubusercontent.com/assets/1648631/21729265/f74e373e-d40f-11e6-9b10-f6eb16b8d12a.png)
