### ISSUE TITLE
Intersecting Polystrips on thin surfaces cause lots of flipping

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#218]
If you intersect a strip into an existing strip, which is on a thin surface, the strip will frequently get flipped a lot. This causes very unsavory results:
![screen shot 2016-03-07 at 9 49 20 pm](https://cloud.githubusercontent.com/assets/1648631/13591477/9d53c11e-e4ae-11e5-8ebb-95f28e76e929.png)
![screen shot 2016-03-07 at 9 49 23 pm](https://cloud.githubusercontent.com/assets/1648631/13591478/9d69be6a-e4ae-11e5-938e-014c1d17081e.png)
![screen shot 2016-03-07 at 9 49 30 pm](https://cloud.githubusercontent.com/assets/1648631/13591479/9fb3f08c-e4ae-11e5-880d-92cc9a2ed6c2.png)

**Comment by carter2422** [comment]
That's dramatically improved!

**Comment by carter2422** [comment]
Although on large objects it seems to go back to flipping a lot:
![screen shot 2016-03-23 at 4 00 08 pm](https://cloud.githubusercontent.com/assets/1648631/14000692/5f114520-f110-11e5-8d43-af349af20cf5.png)

**Comment by vxlcoder** [comment]
ok, i think i have an idea...

**Comment by vxlcoder** [comment]
@carter2422, when you get a chance, retest that last example, and let me know what you are scaling the object by.  also, try applying the scale before testing.  i cannot reproduce this error unless the scaling is negative.

**Comment by carter2422** [comment]
@vxlcoder if I scale the cylinder by 10x everything works great, including at default scale. However, soon as I apply the scale on the cylinder the intersections start happening again:
![screen shot 2016-07-13 at 3 49 46 pm](https://cloud.githubusercontent.com/assets/1648631/16819323/8911a3de-4911-11e6-9e16-868b5a69df3f.png)
![screen shot 2016-07-13 at 3 50 41 pm](https://cloud.githubusercontent.com/assets/1648631/16819335/92042106-4911-11e6-905c-9bbdd418ee4a.png)

**Comment by carter2422** [comment]
@vxlcoder I think I found the issue on this. It's dependent on the length of the stroke, whereby if the line between the start/end passes on the opposite side then it causes flipping: https://cl.ly/ghJC

**Comment by carter2422** [comment]
I know this is your favorite issue ever @vxlcoder  :) 

The outside of the cylinder test works great now! Unfortunately it fails on the inside. https://cl.ly/iDWH

Seeing as this is a great improvement already I'm going to commit for 1.2.2 but let's keep this open for continued improvements. 

Moving to v1.3.0

**Comment by PostPollux** [comment]
I have the same problem with a model here. Polystripe is almost unusable. It's flipping like hell. Its a CAD model converted to a poly object (with Rhino). That's why not all polys are connected (like you can see at the end of the video).

https://goo.gl/photos/v6izYq6usoF47Bau7

Here is the object so you can try your self:
[bugTestFile.zip](https://github.com/CGCookie/retopoflow/files/633857/bugTestFile.zip)

**Comment by carter2422** [comment]
@PostPollux that's a great test model! Mind if I keep that around as a part of our testing suite? 

For now I have a workaround for you. Simply scale the object by 10x and apply the scale with CTRL+A. Polystrips will no longer flip :)

**Comment by carter2422** [comment]
@vxlcoder any chance you could take a look at [the pull request for issue/218 merge](https://github.com/CGCookie/retopoflow/pull/287) to resolve the merge conflicts?

**Comment by PostPollux** [comment]
@carter2422  As long as you don't share it and just use it for the sole purpose of testing, I think it's ok.

**Comment by carter2422** [comment]
I'm very happy to say that this is now a non-issue! It's been resolved in v2.0.0: https://cl.ly/tEWD
