### ISSUE TITLE
Connecting a vert to another vert in an adjacent face fails

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#219]
```
EXCEPTION (<class 'ValueError'>): face_split(...): verts are adjacent in the face
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polypen/polypen_modal.py
000 0853:handle_action_seledge() bmesh.utils.face_split(bmf, bmv0, bmv2)
001 0713:handle_action() return self.handle_action_seledge(context, eventd)
002 0369:modal_wait() return self.handle_action(context, eventd)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py
003 0223:modal_main() nmode = self.FSM['wait'](context, eventd)
004 0276:modal() nmode = self.FSM[self.fsm_mode](context, eventd)
```

![screen shot 2016-03-08 at 2 53 24 pm](https://cloud.githubusercontent.com/assets/1648631/13615983/8cc59d4c-e53d-11e5-9aaa-022d6dca491d.png)

**Comment by carter2422** [comment]
Note, the edge actually gets created, but it throws the error. 

Additionally, this seems to only happen when both edges on the initial vert are selected. If you just select the first vert and then CTRL+Click to connect then no error is thrown.

**Comment by vxlcoder** [comment]
see if branch issue/219 fixes the problem

**Comment by patmo141** [comment]
What does the before picture look like?  I'm not sure how to duplicate this one

**Comment by carter2422** [comment]
Appears to be working!

**Comment by carter2422** [comment]
Reopened for the PR above, which has a merge conflict.

**Comment by carter2422** [comment]
Whoops, wrong issue for the PR.
