### ISSUE TITLE
can't Slide or Rotate in 1.2 Beta

### ISSUE THREAD

**Issue by gamescubed** [CGCookie/retopoflow#220]
Clean installation of Beta version.
Fire up Contours.
Draw a loop.
Try to Slide or Rotate the loop ... it won't happen.
It's not that the loop simply isn't moving at all, more that there is a strange type of snapping in place with a very large/irregular step distance.

**Comment by carter2422** [comment]
@gamescubed which version of Blender are you using? 

I believe I found the cause (and definitely found a different one at least).

**Comment by gamescubed** [comment]
Tried in 2.76b and 2.77 rc1 with the same results.

P.S. Thanks for adding the Bug tag.

**Comment by carter2422** [comment]
@gamescubed go ahead and give this version a try: https://www.dropbox.com/s/fvcbbg9wipic31q/RetopoFlow_v1.2.0_issue220.zip?dl=0

**Comment by gamescubed** [comment]
Yeah, that got it! Nice job Jonathan!

**Comment by carter2422** [comment]
Great! Thanks for the quick report and followup.
