### ISSUE TITLE
Pie Menus while using Retopoflow modules

### ISSUE THREAD

**Issue by gamescubed** [CGCookie/retopoflow#221]
I've really got into the way of using the pie menus, in particular for the View menu. Is there any chance Pie Menu support will be added to the suite?

**Comment by carter2422** [comment]
@gamescubed Pie Menus for accessing the various tools? I'm not opposed, I've just not played with it much. 

I'll happily consider it for a future release :+1:

**Comment by gamescubed** [comment]
I actually just meant being able to use the same pie menus we have available to us outside of Retopoflow. e.g. Holding Q brings up the View menu, Z brings up the Shade menu etc. but maybe pie menus for Retopoflow tools would be handy as well ...
For now, I'd be more than happy with just my precious View menu.
