### ISSUE TITLE
crashes and logs

### ISSUE THREAD

**Issue by wolfie138** [CGCookie/retopoflow#224]
i was trying to retopo some sculpted hair;
1) sometimes the tool seems to lock on first use - it seems to be the help box, as if i clicked on that the tool would release.
2) i draw circles around the crown of the head ok, but when drawing down the strands of the fringe the machine would just vanish - i can't find the blender crash logs.
3) couple other errors attached,

![retoperrors](https://cloud.githubusercontent.com/assets/17825397/13740860/e1707038-e9ca-11e5-9448-f3eb7a06950a.jpg)

**Comment by patmo141** [comment]
Ok, the first issue in the images you post seems to be related to a source/target issue.  That one I can fix no problem.  can you possibly screen cast the issue with the help box?

**Comment by carter2422** [comment]
@wolfie138 are the hair strands mesh objects?

**Comment by wolfie138** [comment]
yes, it was a rough base mesh i'd made (pretty rough, i was just testing the tool out, the mesh will be much more refined for the model itself). i was above and slightly forward of the head to retopo the top, looking down on it at a pretty steep angle, and was running a strand down the fringe from the concentric loops i'd made at the top. so maybe it was a z/depth issue? i have had the occasional issue (especially on thinner strands) where the retopo faces sometimes twist on themselves or jump through the mesh if they can't lock onto the surface properly.
oddly enough, starting at the bottom of the strand and running up towards me didn't seem to cause the issue.

**Comment by carter2422** [comment]
The grazing angle almost certainly contributed to the problem. 

As for the thinner surfaces, this is a known problem that we've been working on improving for a while, but it's still a bit problematic at times: #35 #218 #217

**Comment by carter2422** [comment]
With these being noted in specific issues above I'm going to go ahead and close this. If you come across something new @wolfie138 please do let us know!
