### ISSUE TITLE
Translating entire polystrip when attached to existing geom moves handles

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#225]
Be in edit mode with existing geometry
Start Poly strips
Draw a strip from existing geometry
Select it
Translate it
![image](https://cloud.githubusercontent.com/assets/2917743/13800634/51752662-eb01-11e5-9f98-46bd721f4936.png)

**Comment by carter2422** [comment]
Good catch @patmo141. Think we can squeeze this in for 1.2.0 or 1.2.1?

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/13885240/c79f3db6-ed07-11e5-9cba-b2f3f2450893.png)
