### ISSUE TITLE
Unable to move or delete particular junctions in 1.2.0 beta polystrips

### ISSUE THREAD

**Issue by OneRatNoWalls** [CGCookie/retopoflow#226]
I'm having seemingly random issues with particular junctions in polystrips becoming impossible to move or delete. This occurs when I've been working on a session for five or ten minutes, and the details vary between incidents. In the most recent incident, trying to drag the junction with the mouse and G key just caused the junction handles to move off the junction, while a nearby part of the mesh became distorted. I've attached a screenshot and error log from this incident.

In general, I'm running into a lot of trouble with the beta. Polystrips and polypen frequently freeze Blender entirely, so that there's nothing to do except close it and lose the whole session. (I haven't tried out contours yet.) Polystrips is doing a lot of random-seeming misbehavior, eg. sudden refusal to extend existing mesh in edit mode, strips twisting, certain polystrips becoming impossible to select (sometimes causing a different polystrip to be selected when I try, sometimes just not selecting at all). I'm finding the beta too unstable to work with for more than very simple short sessions. Version 1.1.3 seems to be working fine.
[RetopoFlow_log.txt](https://github.com/CGCookie/retopoflow/files/178814/RetopoFlow_log.txt)

![face cant be moved or deleted](https://cloud.githubusercontent.com/assets/6516892/13863553/ced0f616-ec57-11e5-9764-7aa295a5de1c.jpg)

**Comment by carter2422** [comment]
Thanks for the report @OneRatNoWalls. Are you by chance able to replicate any of these issues one at a time? We'll dig into the error log and see what we can do, but if you're able to replicate the problems that'd help a lot in tracking it down. 

@vxlcoder, @patmo141 these seem to be the two main errors (which I've seen pop up else where as well):

```
EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'dot'
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\op_polystrips\polystrips_datastructure.py
000 1251:snap_igverts() d0,d3 = nr.dot(self.gvert0.snap_norm),nr.dot(self.gvert3.snap_norm)
001 1153:update_nozip() self.snap_igverts()
002 1176:update() self.update_nozip(debug=debug)
003 0306:update() if self.gedge_inner: self.gedge_inner.update()
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\op_polystrips\polystrips_ui_tools.py
004 0618:grab_tool_gvert_list() gv.update()
005 0641:grab_tool_gvert_neighbors() self.grab_tool_gvert_list(command, eventd, lgv)
006 0444:modal_grab_tool() self.tool_fn((mx-px,my-py), eventd)
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\modaloperator.py
007 0274:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

EXCEPTION (<class 'AssertionError'>): 
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\op_polystrips\polystrips_datastructure.py
000 2038:disconnect_gedge() assert gedge in self.gedges
001 2050:disconnect_gvert() self.disconnect_gedge(gvert.gedge0)
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\op_polystrips\polystrips_ui_modalwait.py
002 0303:modal_wait() self.polystrips.disconnect_gvert(self.act_gvert)
         C:\Users\Tim Tylor\AppData\Roaming\Blender Foundation\Blender\2.76\scripts\addons\RetopoFlow\modaloperator.py
003 0221:modal_main() nmode = self.FSM['wait'](context, eventd)
004 0274:modal() nmode = self.FSM[self.fsm_mode](context, events)
```

**Comment by carter2422** [comment]
@OneRatNoWalls when Polystrips froze Blender, where you by chance drawing strips across a thin model?

**Comment by carter2422** [comment]
One of these issues has been fixed now @OneRatNoWalls in #217.

If you can replicate the issue with the Polystrips handles becoming unattached that'd be very helpful. 

I'll update the issue title to reflect that.

**Comment by carter2422** [comment]
Ah I believe the unattached handles was due to #225, which has now been fixed. Closing.

**Comment by patmo141** [comment]
The handles can still move if a GVert is selected, I only fixed GEdge.  Working in it right now
