### ISSUE TITLE
guide mode error in contours

### ISSUE THREAD

**Issue by MattPackard** [CGCookie/retopoflow#227]
haha, I tried guide mode for the first time to quickly retopo an arm from the hand to shoulder. It is a separate object from torso. When i got to the end it gave an error but did not cancel, i've got green dotted lines running all over my screen now and i cant back out.
![bug](https://cloud.githubusercontent.com/assets/15812944/13871461/fa355e02-eca0-11e5-9f0e-f6a4d161295f.PNG)

**Comment by MattPackard** [comment]
note... if its possible with the code, perhaps you could make so that even if the cursor is not over a mesh but in empty space, it would still create a loop to the furthest possible point between the cursor and last loop.

**Comment by carter2422** [comment]
Well that's a fun one @MattPackard....hah.

Have you by chance been able to replicate this?

**Comment by patmo141** [comment]
Surely it just kept recording your strokes, and that's all of your mouse movements after it "hung up."  That for sure is an entertaining one

**Comment by patmo141** [comment]
Confirmed.

![image](https://cloud.githubusercontent.com/assets/2917743/13883989/411d4e90-ed02-11e5-83f8-2b459f333f8a.png)

**Comment by carter2422** [comment]
Great @patmo141! Added to v1.2.0 milestone; let's get this fixed :)

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/13884478/90dc1842-ed04-11e5-9af9-c08580dcf231.png)

**Comment by carter2422** [comment]
That works well @patmo141. Go ahead and merge. Although you might consider commenting the `if trim:` block to document what and why the trim is used.
