### ISSUE TITLE
Knife'd junctions draw poly on Handle hover

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#229]
If you knife a junction into a strip, then select that junction, the two handles that're parallel with the target strip draw a square on hovering the handle:

![screen shot 2016-03-18 at 11 37 01 am](https://cloud.githubusercontent.com/assets/1648631/13884881/f2e40e20-ecfd-11e5-805d-ce65f87b6e1c.png)
![screen shot 2016-03-18 at 11 37 09 am](https://cloud.githubusercontent.com/assets/1648631/13884886/f5f52ea0-ecfd-11e5-99de-097cc9e3f2b3.png)

**Comment by patmo141** [comment]
Ah HA!  It's orphaned inner gverts after the split
![image](https://cloud.githubusercontent.com/assets/2917743/13887687/8531d66c-ed13-11e5-89ad-da053a1afa44.png)
