### ISSUE TITLE
Strange Glitch - Polystrips

### ISSUE THREAD

**Issue by mx1001** [CGCookie/retopoflow#237]
While testing the tool I experienced some strangeness at this moment in the video. 

https://youtu.be/R6xiBkaeORQ?t=4m54s

This is what my screen looked like. http://i.imgur.com/OM1NDDU.png
JW also pointed out the help isnt supposed to look like that. That could be something with the blf not being tied to the dpi or something. We experienced something like that too.

**Comment by vxlcoder** [comment]
quick question, @mx1001: what is the scale on that mesh?  did you apply the scale (so scale is 1.0)?

**Comment by vxlcoder** [comment]
ah, i think i know the problem!  there seems to be an issue when you draw a polystrip from an existing strip that connects back to itself.  if you add an extra endpoint before connecting back to the existing geometry, it seems to work.  i'll think through this a bit more.

**Comment by mx1001** [comment]
that could be the issue. I did scale it down by 100x before beginning sculpting and retopo. I guess since I did it uniform scale didnt prove an issue during dynamic tesselation sculpting. Ill try it again with that in mind on my next video.

**Comment by vxlcoder** [comment]
screenshots highlighting the issue here:

![works fine](https://cloud.githubusercontent.com/assets/3790699/14002707/0e1d0794-f124-11e5-8783-abc1687a350d.png)

![sketch of what does not work](https://cloud.githubusercontent.com/assets/3790699/14002717/1a11b55e-f124-11e5-826a-d84223a2b51d.png)

![broken result](https://cloud.githubusercontent.com/assets/3790699/14002729/233ee656-f124-11e5-8bfe-09d9e73ece57.png)

i think the stretching of incorrectly positioned strip is just a strange consequence that will be corrected with a solution, but it might be from something else.

**Comment by mx1001** [comment]
ah excellent. Ill give that a try. Im sure it was something i did moreso than the tool malfunctioning

**Comment by vxlcoder** [comment]
confirmed.  using mesh scaling does weird stuff in this scenario.

![image](https://cloud.githubusercontent.com/assets/3790699/14003420/e62d2386-f128-11e5-8a89-2306ccd1fccb.png)

**Comment by mx1001** [comment]
excellent. So quick to find the source of the issue. Nice! Ill keep that in
mind. Awesome work! Youre a python detective haha.

**Comment by vxlcoder** [comment]
@mx1001, the above commit is a workaround for this issue.  it's not a great solution, but it should correct any strange behavior.  note: to create a loop from existing geometry (as intended in the second screenshot above), you will need to add explicitly an extra end point between the two endpoints of the strip. see below

![image](https://cloud.githubusercontent.com/assets/3790699/14003748/52c9402c-f12b-11e5-9054-a09468d5553e.png)

let me know if this solution causes any other issues.  thanks!

**Comment by carter2422** [comment]
@vxlcoder this seems to be a bit erratic still. I need to test more, though. Going to tentatively put towards 1.2.1

**Comment by vxlcoder** [comment]
@carter2422: can you repo this?

**Comment by carter2422** [comment]
This appears to be fixed from the changes in #276. I cannot replicate any longer, considering closed.
