### ISSUE TITLE
Source and Target objects should not require origin and rotation/scale to match

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#242]
With some tools, such as Tweak, it turns out the Object Origins of the Source/Target must match for behavior to work correctly. In addition, it seems both objects must have the same rotations. 

Are we able to remove these limitations? There're more corner-cases than anything, but when they do come up their quite frustrating to users.

**Comment by patmo141** [comment]
yes we can remove this limitation

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/14268257/d86cf758-faa6-11e5-8025-0c41884ed663.png)

PolyPen when existing source/target have different world matrices.  This might be in the BMesh render code?

**Comment by vxlcoder** [comment]
test branch `issue/242`

**Comment by carter2422** [comment]
- [ ] Contours fails with new Bmesh Cache
```
EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMesh has been removed
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_contours/contour_utilities.py
000 2219:cross_section_seed_ver1() bme.faces.ensure_lookup_table();
001 2318:cross_section_seed() ret = cross_section_seed_ver1(bme, mx, point, normal, seed_index, max_tests, debug)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_contours/contour_classes.py
002 2923:cut_object() cross = contour_utilities.cross_section_seed(bme, mx, pt, pno, indx, debug = True, method = meth)
003 0388:release_place_cut() self.sel_loop.cut_object(context, mesh_cache['bme'], mesh_cache['bvh'], self.mx)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_contours/contours_modal.py
004 0294:modal_cut() self.contours.release_place_cut(context, self.settings, x, y)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py
005 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)
```

**Comment by carter2422** [comment]
There's a corner case where transforms can become misaligned. If you start a retopo, then transform the source, the target will no longer match and thus can fail. 

@vxlcoder what do you think about a conditional to check `if transforms match, use cache, if not regenerate cache`? 

Although I'm not sure that would work as the Target object would already be created and so wouldn't match. 

Another solution might simply be to Parent the target to the source upon creation, such that any transforms made to the source are also made to the child.

**Comment by vxlcoder** [comment]
i don't think it is a good idea to force target and source to _always_ have same xform.

now if the source is transformed after retopo, any subsequent changes to the target _should_ conform to the newly transformed source.

**Comment by carter2422** [comment]
> i don't think it is a good idea to force target and source to always have same form.

Agreed. 

And actually now that I test it more I don't think there's corner case so much. Ignore me. I'll create a new issue if something arises.

**Comment by carter2422** [comment]
I'm so happy to close this!

**Comment by carter2422** [comment]
Found a small issue:
- [ ] The tweak brush size is broken, making user unable to adjust the size.

**Comment by carter2422** [comment]
The above issue is confined to `issue/242`, so likely something to do with Bmesh Cache?

**Comment by carter2422** [comment]
I think the above issues are corner cases that we can continue to track down. Initially I think this is indeed good to close. 

The problem with a source or target being transformed after Retopo has already begun is not something that's going to happen often and it's an easy fix on the user's part.
