### ISSUE TITLE
Error message with Polystrips: object has no attribute 'create_gvert'

### ISSUE THREAD

**Issue by Eric-Lafarge** [CGCookie/retopoflow#243]
OsX 10.11.4  / 2.77
Open an old file, try to PolyStrip and got this message. Then Blender crash (Crash report)
Works fine with a new file.
![capture d ecran 2016-04-06 a 16 43 44](https://cloud.githubusercontent.com/assets/9129984/14322584/b9cd027a-fc1d-11e5-8cdc-a9a6b6d3cd59.png)

![capture d ecran 2016-04-06 a 16 39 01](https://cloud.githubusercontent.com/assets/9129984/14322618/d28efe58-fc1d-11e5-8a3a-e03e695852b8.png)

[RetopoFlow_log.txt](https://github.com/CGCookie/retopoflow/files/206719/RetopoFlow_log.txt)

[CrashReport-retopoFlow-06:04:16.txt](https://github.com/CGCookie/retopoflow/files/206725/CrashReport-retopoFlow-06.04.16.txt)

Best regards.

**Comment by carter2422** [comment]
@Eric-Lafarge could you possibly share the .blend file that crashes?

**Comment by carter2422** [comment]
@Eric-Lafarge just following up on this, are you able to share the .blend file that caused the crash? I'm not able to replicate this yet.

**Comment by alekulyn** [comment]
@carter2422 I'm getting the same error.  I can send you a file, but I have to PM it due to some privacy restrictions (long story).  When are you usually on IRC?

**Comment by carter2422** [comment]
@alekulyn to be sure, which version of RetopoFlow are you using and did you fully uninstall the previous version prior to installing the current? 

You can send me the file via jonathan@cgcookie.com

**Comment by alekulyn** [comment]
@carter2422 I checked out both the release/1.2.3 and release/1.3.0 branches, and I got the error both times.  I'm using Blender from the Debian Testing repo, which is at 2.78a right now.

**Comment by carter2422** [comment]
@alekulyn I found the problem to this. Can you please uninstall your current version and then try this one? 
[RetopoFlow-v1.2.5.zip](https://github.com/CGCookie/retopoflow/files/652560/RetopoFlow-v1.2.5.zip)

**Comment by carter2422** [comment]
@Eric-Lafarge if you can also test that would be great.

**Comment by Eric-Lafarge** [comment]
@carter2422  
2.78a Osx 10.12.2 .  V1.2.5 is getting worst, (Ok with v1,2,4) Open a new file. A simple cube, orthographic and perspective view :  Tried Polypen and got this message : 

![capture d ecran 2016-12-14 a 20 58 24](https://cloud.githubusercontent.com/assets/9129984/21199223/e6329208-c242-11e6-89ea-23d311420767.png)
![capture d ecran 2016-12-14 a 21 00 50](https://cloud.githubusercontent.com/assets/9129984/21199245/fa7c94ac-c242-11e6-8138-97564b616d22.png)
![capture d ecran 2016-12-14 a 20 59 58](https://cloud.githubusercontent.com/assets/9129984/21199257/0621a9dc-c243-11e6-8691-08996632165e.png)

Good luck

**Comment by carter2422** [comment]
@Eric-Lafarge sorry that was from a last minute change that I missed; fixed in 
[RetopoFlow-v1.2.5b.zip](https://github.com/CGCookie/retopoflow/files/652807/RetopoFlow-v1.2.5b.zip)

**Comment by Eric-Lafarge** [comment]
@carter2422 Looks fine so far. Well done. All the best for U

**Comment by carter2422** [comment]
Thanks @Eric-Lafarge!
