### ISSUE TITLE
Error when filling in polystrip circle

### ISSUE THREAD

**Issue by punkoffice** [CGCookie/retopoflow#244]
I get an error sometimes when creating a circle around the eye then trying to fill it.  You can download the .blend file I'm using here [www.punkoffice.com/downloads/polystrips.zip](http://www.punkoffice.com/downloads/polystrips.zip)
![fill](https://cloud.githubusercontent.com/assets/5295016/14408088/4567dbd0-ff29-11e5-9ff9-95cad8a5f3e3.png)

**Comment by punkoffice** [comment]
Another polystrip fill error
![fill_error](https://cloud.githubusercontent.com/assets/5295016/14682265/29c6d542-0768-11e6-9882-d42e48a575eb.jpg)

**Comment by carter2422** [comment]
@punkoffice could you screenshot the polystrips behind the error that you were trying to fill?

**Comment by punkoffice** [comment]
ok, here it is but from slightly different angle to the pic above so you can see a clearer picture 
![polypen_selection](https://cloud.githubusercontent.com/assets/5295016/14682933/796f067a-076b-11e6-9da6-918c9ba46775.jpg)  I try my best to rotate view to an angle where the polys on the other side of the head aren't anywhere near the cursor, but yet it'll still connect to them, even after changing viewport start / end.  By the way, this is with Blender 2.77a

**Comment by carter2422** [comment]
@punkoffice this should be long-since resolved. If you're still having trouble please chime in.
