### ISSUE TITLE
Polypen tool selecting verts/edges/faces far away from actual cursor

### ISSUE THREAD

**Issue by punkoffice** [CGCookie/retopoflow#248]
When I try to lay down polystrips it becomes very difficult with a lot of existing polystrips on the object because what happens is the cursor will randomly start selecting items far away.  Sometimes I don't even notice this 'cos its selecting something out of view, then when I drop down a polygon it connects to something random.
![wrong_selection](https://cloud.githubusercontent.com/assets/5295016/14681550/e82c3da0-0764-11e6-9ff0-43c6ba0d45c9.jpg)

**Comment by carter2422** [comment]
That's the Polypen tool, but I believe the issue @punkoffice is that it's selecting items through the mesh based on the angle. 

Something to try: adjust the viewport `Start / End` of the **Viewport Properties** `View` settings. 

The clipping in RetopoFlow is dependent on these settings, so it could be that the distance is simply too small or large.

**Comment by punkoffice** [comment]
I can adjust start / end of the viewport to isolate the surface that I'm editing but it still ends up connecting to some edge on the other side of the head even though that edge can't be seen

**Comment by toomanydemons** [comment]
I have this issue as well. F2 is still the fastest retopology. I do love polypen for getting started, but wish I could stay in polypen, it's pretty great but at a certain point I always run into this and have to switch back to F2...

**Comment by vxlcoder** [comment]
will take a look at it

**Comment by vxlcoder** [comment]
@punkoffice and @toomanydemons, will you two please take a look at branch `issue/248` to see if it fixes these issues?  thanks!

**Comment by toomanydemons** [comment]
248 works excellent :) I took time to use it for awhile on a detailed mesh and was able to go all the way around it with polypen. I didn't have any problems. This is really nice :)

**Comment by vxlcoder** [comment]
glad to hear that! for the record, the problem was a weirdness in one of the blender python calls.  `intersect_point_tri` will return a non-None answer even if the given point does not lie in the triangle.  just need to test the distance between the given point and the returned point.

**Comment by vxlcoder** [comment]
@toomanydemons are there other issues or difficult workflows that run you into that slow you down in polypen vs f2?

**Comment by toomanydemons** [comment]
One issue that I would fix but isn't a serious problem:The selection radius for grabbing vertices is very small. The mouse pointer has to be right on a vertex to grab it, or you grab an edge instead. This makes it difficult to work quickly, but after some practice it's not too big a deal. The tool is very great :) Thank you!
