### ISSUE TITLE
Dynamic Z-Depth

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#252]
Dynamically adjust/tune z-depth values (near and far) depending on viewport scaling to prevent rendering occluded geometry over mesh at different scales

ok: ![ok](https://cloud.githubusercontent.com/assets/3790699/16736069/7c12e2ce-4759-11e6-89b2-05678b4ac504.png)

bad: ![bad](https://cloud.githubusercontent.com/assets/3790699/16736052/5a99b640-4759-11e6-9262-eafe0e68b1eb.png)

really bad: ![really bad](https://cloud.githubusercontent.com/assets/3790699/16736092/8d339314-4759-11e6-8168-46b816c24209.png)

**Comment by carter2422** [comment]
This would be great @vxlcoder. When are you thinking we might be able to do this?

**Comment by vxlcoder** [comment]
i don't believe it is difficult, so i could get it in for 1.2.2, but a nice, clean, abstracted version could be done with 2.0

**Comment by carter2422** [comment]
That would be great @vxlcoder, let's do it. The goal for 1.2.2 is third or final week of July.

**Comment by carter2422** [comment]
Oh man, the rendering in 59fc7dc8efc0bc8f8540e10c9881f48154f7be45 is sooooo much better! Nice going @vxlcoder. Shall I merge this in?

**Comment by vxlcoder** [comment]
sure @carter2422!
