### ISSUE TITLE
Optimization: apply xforms to bmesh of source mesh

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#253]
In order to eliminate mx/imx computation and multiplication (except for commit), apply object xforms to bmesh of source mesh at start of modal.

**Comment by patmo141** [comment]
great idea

**Comment by carter2422** [comment]
Is this something we can apply to only the generated bmesh rather than the original object, such that transforms are never altered on the original objects without the artists consent?

**Comment by carter2422** [comment]
Long since implemented!
