### ISSUE TITLE
PolyPen: verts and edges aren't occluded in backfacing

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#258]
Seems only faces are being occluded currently, we need to occlude verts and edges as well to improve visualization.
![screen shot 2016-08-08 at 2 44 17 pm](https://cloud.githubusercontent.com/assets/1648631/17493602/b13706dc-5d76-11e6-86f4-b63f7b34fd43.png)

**Comment by carter2422** [comment]
Backface occlusion is working great now, although faces aren't drawing on top of the source: 
![screen shot 2016-08-15 at 2 51 06 pm](https://cloud.githubusercontent.com/assets/1648631/17677290/c74a64ce-62f7-11e6-82fe-fa6f93672be1.png)

**Comment by vxlcoder** [comment]
@carter2422 your last screenshot is concerning....  this is what i get on both of my linux boxes

![image](https://cloud.githubusercontent.com/assets/3790699/17677597/882c9ea6-6301-11e6-818f-eee00274d0d8.png)

i think we need to look into differences more here

**Comment by carter2422** [comment]
Well that's weird....which version of Blender? If master, which commit?

**Comment by vxlcoder** [comment]
blender 2.77a (2016-04-05, hash:abf6f08)

**Comment by carter2422** [comment]
I'm on blender 2.77 (2016-04-25, hash: a10b2fe)

**Comment by carter2422** [comment]
I'm updating to latest master right now

**Comment by vxlcoder** [comment]
issue: osx does not support glsl version 1.3.  rewrote to use older version

**Comment by carter2422** [comment]
Confirmed fixed! Seems my previous issues were due to the double versions snafu.
