### ISSUE TITLE
PolyPen: hidden geometry is hoverable,selectable,editable

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#259]
geometry that is hidden behind other geometry (could be on other side of thin surface, too) can get modified.

**Comment by carter2422** [comment]
Nice @vxlcoder! Go ahead and merge into `release/1.2.2` when ready.

**Comment by hitrpr** [comment]
The same bug.
Win7x64, Blender 2.77a

**Comment by vxlcoder** [comment]
@hitrpr does commit 60f6806 (branch issue/259) solve the problem?

**Comment by hitrpr** [comment]
Yes, now all works properly! Thanks! Sorry, I am new here, IDK how reply-to or download code as file. So I grab all code and put it into my old file ^_^

**Comment by vxlcoder** [comment]
glad to hear @hitrpr!  we've been squashing a lot of bugs to get ready for the next release, so we haven't posted publicly much yet.  if you run into problems in the future, please do report them just like this!  we can only fix the bugs we know about :)

**Comment by hitrpr** [comment]
Got it!

**Comment by hitrpr** [comment]
Sorry, but I misinformed you :( 
I put the same (original) code in the original file (nothing was changed). And at first all worked properly. But then bug appeared.

When I put new code (from issue 259) into my polypen_modal.py, I get error
![prtscr177--20-08-2016](https://cloud.githubusercontent.com/assets/21099918/17826346/e5bb2510-6680-11e6-895a-707950580308.jpg)

Am I copied code wrong?
Then, when I tried to save RAW file , I`ve got another error

![prtscr178--20-08-2016](https://cloud.githubusercontent.com/assets/21099918/17826401/83720ca6-6681-11e6-87e4-3a366180b705.jpg)

Sory if I am bothering you if I am doing something wrong. I don`t even know  :(

**Comment by carter2422** [comment]
@hitrpr rather than replacing the files manually can you try uninstalling the previous version and then installing v1.2.2 fresh?

**Comment by carter2422** [comment]
Confirming this as fixed!

**Comment by hitrpr** [comment]
It seems it is working ok now with Blender 2.78a Backside of retopo-mesh now is not visible through sculpt-mesh and it is good for me.
