### ISSUE TITLE
PolyPen: selection on the other side

### ISSUE THREAD

**Issue by hitrpr** [CGCookie/retopoflow#260]
When I am workin with polypen and simple shape with hole it select poligon on the bottom side of volume when I am hovering mouse above top side. So it is impossible to make new free vertex on the top with Ctrl+Click

![selectjumping](https://cloud.githubusercontent.com/assets/21099918/17781495/9132d502-6580-11e6-8b51-51aebacda851.gif)

![prtscr171--18-08-2016](https://cloud.githubusercontent.com/assets/21099918/17781039/b510bfae-657e-11e6-85ad-898d64604017.jpg)

**Comment by vxlcoder** [comment]
@hitrpr, this looks like issue #259.  can you confirm this?  thank you for the issue report!

**Comment by carter2422** [comment]
Closing as duplicate of #259
