### ISSUE TITLE
Are tool-buttons should be inactive, when I am using tool?

### ISSUE THREAD

**Issue by hitrpr** [CGCookie/retopoflow#261]
After I pressing any tool (i.e. polystrips) all buttons become inactive until I press Esc/Enter. 
If I choose polypen, I see new buttons (twear, cut loop, loop slide). They are inactive too.
Should is be so?

**Comment by carter2422** [comment]
This is correct behavior, due to how Blender works. During modal events Blender blocks all UI actions (unless explicitly passed through). It's the same thing when using default Blender modals, such as the Knife tool.

**Comment by hitrpr** [comment]
Ok, thanks for reply.
So it is a problem of Blender sometimes. In example: blocking rotation with circle select-brush.
