### ISSUE TITLE
Is multiselection exists?

### ISSUE THREAD

**Issue by hitrpr** [CGCookie/retopoflow#263]
I found than multiselection is working in contour mode with shift, but doung nothing.
May be it is a glitch?
Anyway it will be useful to glide few rings smultaniously

**Comment by carter2422** [comment]
Hey @hitrpr, sorry about the late reply. Full multi-selection support in Contours is on our wishlist as well. There's no timeframe right now, but it's on the list. 

Closing for now since it's not a bug.
