### ISSUE TITLE
Add confirmation dialogue to exit tool

### ISSUE THREAD

**Issue by jpweeks** [CGCookie/retopoflow#264]
I've only been experimenting with `retopoflow` for a few days and it's been a great experience; a really great tool. However, one pattern of behavior I keep repeating is hitting `escape` intending to dismiss an error message or some other action and accidentally exiting the tool. Although it's easy enough to recover lost work by re-entering and undoing the last action, it is a bit unnerving to see all the paths and patches instantly disappear and I believe could be remedied by adding a confirmation dialogue to exit if any paths have been created.

**Comment by carter2422** [comment]
This is a great suggestion @jpweeks. Thanks

**Comment by carter2422** [comment]
This will no longer be an issue in version 2.0.0 as we're writing directly to the edit mesh via BMesh, meaning that hitting ESC will keep your current mesh. 

You can test this in the `release/2.0.0` branch
