### ISSUE TITLE
Allow to contour multiple meshes at once

### ISSUE THREAD

**Issue by YainVieyra** [CGCookie/retopoflow#265]
Currently, the contours tool projects the vertices based on the selected object. This is fine to speedup the mesh analysis.
But sometimes, the user needs to contour several objects at the same time. For example, there are varios sculptings that are made up of several individual intersecting parts. Think about an arm with overimposed decorations or a leg with tight props conforming its shape. The user might still want to contour all of them at once to make the baking process take care of the small details without the need to "separate" all these parts.
We are still talking about a somewhat cylindrical shape, but not a continuous one. Currently, the user can join the relevant meshes to make them act as a single Source Object, but the contours tool ignores this completely, limiting to the nearest "continuous" mesh. This leads to really messy contours that aren't useful at all, forcing the user to project the vertices individually.
The native Blender tool to snap vertices works just fine when several individual objects are involved, so there must be a way to achieve this. I think this could a be a great addition to the versatility of RetopoFlow.

The image sequence shows an example where there are three overlayed cylinder primitive meshes in the same Source Object, and you can see what happens when the user draws a line that covers them all.
![report](https://cloud.githubusercontent.com/assets/22411682/18807717/122020be-8225-11e6-8d39-9a20185509e8.gif)

**Comment by carter2422** [comment]
Enabling Contours (or Polystrips, Polypen) to retopo a group of objects at once is on our short list of needed features. 

In the mean time it's best to merge them all into a single object with booleans, such that you don't have interior faces. I realize this is not ideal, but it's a current limitation with how we detect the surface for snapping.

**Comment by vxlcoder** [comment]
Note for future: have option to switch between these two modes: retopo along connected geometry / retopo all intersecting geometry.  along with option, need to have a visualization to help artist know which mode they're in beyond looking/interpreting which option is selected.

**Comment by carter2422** [comment]
That's a good idea @vxlcoder

**Comment by YainVieyra** [comment]
Thank you guys.
Cheers.

**Comment by carter2422** [comment]
This is coming in v2.0.0 @YainVieyra! You can already test it via `release/2.0.0` branch. 

Currently we have a basic version of PolyPen, PolyStrips, Tweak, and Relax implemented. The rest are coming soon.

**Comment by YainVieyra** [comment]
That is awesome Jonathan.
Thanks.
