### ISSUE TITLE
Undo with tweak mode is not working well

### ISSUE THREAD

**Issue by CenekStrichel** [CGCookie/retopoflow#266]
1) Use Tweak Tools for change position of some vertexes
2) CTRL+Z for UNDO 
3) Nothing happen until you move another vertex (wire is not redrawed)

**Comment by carter2422** [comment]
Just to be certain while trying to replicate this @CenekStrichel, which versions of Blender and RetopoFlow are you using?

**Comment by CenekStrichel** [comment]
Blender 2.77, but same for 2.78 and RetopoFlow 1.2.1

![retopoflowbug](https://cloud.githubusercontent.com/assets/8094238/19109038/dc891a32-8af3-11e6-9ec7-b056e197d008.gif)

**Comment by carter2422** [comment]
Confirmed. Tossing this to you @vxlcoder

**Comment by carter2422** [comment]
Confirmed!
