### ISSUE TITLE
Polypen can not detect surface

### ISSUE THREAD

**Issue by CenekStrichel** [CGCookie/retopoflow#267]
Maybe it is limitation, but it looks that polypen is not working well. I found many cases, where it is not possible select right survace to add polygon.

![polypen](https://cloud.githubusercontent.com/assets/8094238/19109282/df2bfc7c-8af4-11e6-8375-4959fd5164c7.gif)

**Comment by CenekStrichel** [comment]
I just found version 1.2.2 and problem is solved there, thanks! :)

**Comment by carter2422** [comment]
Hey @CenekStrichel, sorry about the late reply. It's good to hear that 1.2.2 resolves the issue!
