### ISSUE TITLE
Caching settings causes crashes

### ISSUE THREAD

**Issue by plasmasolutions** [CGCookie/retopoflow#272]
Hi guys,

Sergey S. talked to me on IRC because I was named as the author of the file lib/common_utilities.py . He experienced crashes in the Blender Institute while they were using retopoflow and figured out that it was our add-on which was causing them.

Issue is that we read the user preference settings (in the method get_Settings() ), cache them and use this cached version whenever we need to access settings. So far so good. Dangerous is that the saved settings pointer becomes invalid when Blender f.e. loads a new file (Ctrl+N) while the add-on is enabled. In this case crashes will occur!

Am away from home now and will fly back home hopefully tomorrow, so it would be good if one of you could have a quick look. Should not be more than removing the "if not ... is_cached" condition entirely...

Cheers, 
Thomas

**Comment by carter2422** [comment]
Thanks for the heads up @plasmasolutions! I will get this fixed asap.

**Comment by carter2422** [comment]
All fixed! I'm thrilled to finally know what was causing those crashes. They were such a pain.

**Comment by plasmasolutions** [comment]
Really makes me happy to hear that Jonathan. Am really happy that Sergey debugged it - so kudos to Sergey! :)

**Comment by carter2422** [comment]
Yes!! Many thanks to Sergey.
