### ISSUE TITLE
Contours: canceling a loop move or rotate causes twisting

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#274]
Before pressing G
![image](https://cloud.githubusercontent.com/assets/3790699/20573654/ed816cc0-b17e-11e6-89c4-42f943eb5e80.png)

After pressing G and moving just a bit
![image](https://cloud.githubusercontent.com/assets/3790699/20573662/faa25f2c-b17e-11e6-8d71-9025e1351bb9.png)

After pressing escape (cancel grab/move)
![image](https://cloud.githubusercontent.com/assets/3790699/20573674/073ab8ec-b17f-11e6-93e1-6a3edb46303f.png)

blender 2.78a, release/1.2.2

**Comment by carter2422** [comment]
This was a real jerk, nice to see it was a simple fix 🎉
