### ISSUE TITLE
Polystrips: patching corner of existing geometry not handled

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#276]
related: issue #237 

When trying to fill a corner with existing geometry, patching will create a triangle.

Existing geometry:
![existing geometry](https://cloud.githubusercontent.com/assets/3790699/20579310/037d4ec0-b19a-11e6-84a4-f39822df20a1.png)

Incorrect:
![incorrect](https://cloud.githubusercontent.com/assets/3790699/20579362/3d303ccc-b19a-11e6-99f5-5edb9b220eea.png)

Correct:
![correct](https://cloud.githubusercontent.com/assets/3790699/20579373/49b276fe-b19a-11e6-9580-2ffa6ea6d322.png)

Also, a junction should be automatically inserted if stroking between two existing geometry junctions, but only if they are on same loop.  Workaround for issue #237 

![image](https://cloud.githubusercontent.com/assets/3790699/20579456/9df6f2b2-b19a-11e6-90ba-3d086cf2e5c8.png)

**Comment by carter2422** [comment]
Nice!

**Comment by carter2422** [comment]
21e79f4ecb7f1773cdf60d095bc78ae02e75f564 causes a complete stall on OS X when starting Polystrips with existing geometry. 

Reverting for now and will push to 1.3.0.

**Comment by carter2422** [comment]
I can't seem to replicate it now @vxlcoder....I'm testing on OS X against sources with and without existing geometry. All is working good. 

If you can't replicate go ahead and merge back into `release/1.3.1`

**Comment by carter2422** [comment]
@vxlcoder I still cannot replicate this and so I think it's good to go. However, I found a corner case. 

Filling a corner patch on the opposite side of another corner patch fails:
![screen shot 2017-01-06 at 12 51 36 pm](https://cloud.githubusercontent.com/assets/1648631/21729056/f615b578-d40e-11e6-9aec-fb72c9d6fd50.png)

```
EXCEPTION (<class 'NameError'>): name 'lids1' is not defined
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_datastructure.py
000 3526:<genexpr>() gv3 = next((gv for gv in self.gverts if any(i in gv.from_mesh_loops for i in lids0) and any(i in gv.from_mesh_loops for i in lids1)), None)
001 3526:attempt_gpatch() gv3 = next((gv for gv in self.gverts if any(i in gv.from_mesh_loops for i in lids0) and any(i in gv.from_mesh_loops for i in lids1)), None)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_ui.py
002 0364:fill() lgpattempt = self.polystrips.attempt_gpatch(self.sel_gedges)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/op_polystrips/polystrips_ui_modalwait.py
003 0267:modal_wait() self.fill(eventd)
         /Users/jonathanwilliamson/Dropbox (Personal)/blenderDev/addons/cgCookie/scripts/addons/retopoFlow/modaloperator.py
004 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
005 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)
```
