### ISSUE TITLE
Tools panel is available even it is not usable

### ISSUE THREAD

**Issue by CenekStrichel** [CGCookie/retopoflow#277]
If you use any modal tools, list of others tools are still available, but it is not clickable. I know that it is not bug, but it is little confusing for new user.

It would be fine disable layout (layout.enable = False) and add some info label: "Press Enter to confirm" or something like this.

![enabled](https://cloud.githubusercontent.com/assets/8094238/20595615/da825064-b23a-11e6-8c3d-893730a706dc.png)

**Comment by carter2422** [comment]
This is more of an issue with how Blender handles Modal operators @CenekStrichel. In Blender 2.8 this interaction is being looked at, so it's not really a retopoflow issue. 

There are some things that we could likely do to make it more clear, but presently it has identical behavior to Blender's modal tool (such as Knife), and so I'm inclined to leave as is.
