### ISSUE TITLE
Problems after I update Retoflow Version 1.2.2 [PolyPen]

### ISSUE THREAD

**Issue by OscarLeif** [CGCookie/retopoflow#278]
Hello.
Hello I have a problem when I update my retoflow Addon.
The problem starts like this, when I want to start using Retoflow **Polypen** I can draw a Vertex over the default cube that works, but when I want to draw the second one it fails and shows this debug

`EXCEPTION (<class 'TypeError'>): create_vert() missing 1 required positional argument: 'normal'
         C:\Users\OscarLeif\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_polypen\polypen_modal.py
000 1210:handle_insert_vert_and_bridge() bmv1 = self.create_vert(self.mouse_downp3d)
001 0783:handle_action() return self.handle_insert_vert_and_bridge(context, eventd)
002 0388:modal_wait() return self.handle_action(context, eventd)
         C:\Users\OscarLeif\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
003 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
004 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)
`
I already tried in two machines and it doesn't work.
I use Blender 2.78 and 2.78a. Still don't know why it doesn't work, anyone know what happens here ?
I was testing more and I Found that the problem is when Retoflow start from an object using Polypen tool.

**Comment by vxlcoder** [comment]
thank you for the bug report, @OscarLeif!  turns out, polypen is broken.  looking into it now.

**Comment by vxlcoder** [comment]
i believe this should fix the problem.  feel free to test it yourself.  we will test some more and merge as soon as possible.  Thanks, again!

**Comment by OscarLeif** [comment]
@vxlcoder Thanks I make some tests, it seems to work now. Sometimes I have problems creating new faces it seems that the direction of the face goes inverted, not always but sometime fails,It just create an X face, is very difficult to describe. Here I upload a video of the test.
[https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be](url)
And if you look at the **video** the **problems** about the **bad faces** happen in this time.
https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be#t=2m58s#
**And here.**
https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be#t=5m51s#

**Comment by toomanydemons** [comment]
I continually ran into this issue also. The polypen is my favorite tool so
I was forced to revert :'(

**Comment by carter2422** [comment]
Thanks for the quick report @OscarLeif! I've just pushed out the v1.2.3 release with the fix from @vxlcoder

**Comment by vxlcoder** [comment]
Will take another look

**Comment by vxlcoder** [comment]
@OscarLeif and @toomanydemons, I have created a new issue (issue #281) for the crossing quads, and pushed an update (branch issue/281) that might fix this problem.  would you please test this and report your findings on issue #281?  Thanks!
