### ISSUE TITLE
Polystrips visibility degraded in ortho view

### ISSUE THREAD

**Issue by JackOfShadow** [CGCookie/retopoflow#280]
old retopoflow - polystrips
![retopo-old](https://cloud.githubusercontent.com/assets/10739109/20647109/a4f2601a-b49c-11e6-89ed-18365d0e31cf.jpeg)
latest git retopoflow - polystrips
![retopo-new](https://cloud.githubusercontent.com/assets/10739109/20647123/ec390f6e-b49c-11e6-9460-216d6c08db1d.jpeg)

**Comment by carter2422** [comment]
@JackOfShadow just so I can test and confirm, what is the scale and dimension of your sphere?

**Comment by JackOfShadow** [comment]
Default cube. SubdivSurface - 6. Apply. That's all.

**Comment by vxlcoder** [comment]
@JackOfShadow Thank you for the report!  We are still in the middle of updating how the tools render the mesh, and the revamp is not quite complete, yet.  If you can, try checking out branch issue/280 to see if that helps.

**Comment by carter2422** [comment]
Good catch @vxlcoder; replicated and confirmed the fix here. Will add to next release.

**Comment by OscarLeif** [comment]
Was this fixed ?

**Comment by carter2422** [comment]
@OscarLeif it's fixed in the issue branch for #280 and will get merged into v1.2.4 for release soon.

**Comment by carter2422** [comment]
Small thing, but this same fix needs applied to polystrip handles: https://cl.ly/iQIg
