### ISSUE TITLE
PolyPen: inserting vert to tri->quad often ends up with twisted quad (X)

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#281]
as reported by @OscarLeif and @toomanydemons:

> Sometimes I have problems creating new faces it seems that the direction of the face goes inverted, not always but sometime fails,It just create a X face, is very difficult to describe. Here I upload a video of the test.
> https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be
> And if you look at the video the problems about the bad faces happen in this time.
> https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be#t=2m58s#
> And here.
> https://www.youtube.com/watch?v=zSo_hzGJABk&feature=youtu.be#t=5m51s#

**Comment by OscarLeif** [comment]
I'm gonna make some tests, this time in more complex objects

**Comment by vxlcoder** [comment]
Thanks!

**Comment by OscarLeif** [comment]
I make some tests, **the problem with the twisted quad is solved** (I guess I just make some test on some of the head models that you can find at Blend swap). I tested on two different computers. But I found more problems. 
The first one no to critical just display a warning dialog: 
**EXCEPTION (<class 'AssertionError'>):** 
**EXCEPTION (<class 'ValueError'>):** 
I was even able to continue working, in most of the cases...I need time to know of to replicate this.
The critical one was something like this. 
After make a big mesh I need to fix a bad loop but polystrips fails. And the UI is destroyed, you cannot use Blender...that is the problem right now I will try to duplicate, I will open a new issue when I know how to replicate that.

**Comment by carter2422** [comment]
> After make a big mesh I need to fix a bad loop but polystrips fails. And the UI is destroyed, you cannot use Blender...that is the problem right now I will try to duplicate, I will open a new issue when I know how to replicate that.

Please do let us know if you can replicate that! That's a bad, bad bug if so.

@vxlcoder you able to look into the two exceptions above? I can merge into 1.2.4 after I confirm testing.
