### ISSUE TITLE
Visibility of Polystrips on Mac OSX and Linux Mint Sarah

### ISSUE THREAD

**Issue by artistCDMJ** [CGCookie/retopoflow#282]
I am having problems seeing the new polystrips above surface in 1.2.3, and had not had a problem when using the previous version 1.2.1, and am wondering if anyone else seems to have this issue. I used to only have this issue with the resulting mesh after committing the polystrips to mesh, but am wondering if there is a setting I am missing.

**Comment by carter2422** [comment]
Is the display issue only in orthographic?

**Comment by artistCDMJ** [comment]
I don't think so, but later tonight I can load a model and grab screen shots of both versions and compare side by side for you.

**Comment by carter2422** [comment]
Thanks, that'd be very helpful!

**Comment by artistCDMJ** [comment]
![retopoflow1 2 1](https://cloud.githubusercontent.com/assets/16747273/20856389/36a70756-b8d3-11e6-8738-6a88b2d21117.png)
![retopoflow1 2 3](https://cloud.githubusercontent.com/assets/16747273/20856390/36a80516-b8d3-11e6-80aa-9fb7d7d38479.png)
The first image is of what I get with the 1.2.1 release, giving me very good view of the polystrips above the mesh surface. The second is with the 1.2.3 release that I downloaded, adn is too hard to see where my junctions are and reminds me of the classic magnetic surface behaviour that I get manually placing my retopo. 
I hope this makes sense and is actually something I can fix with a setting and not an actual bug.
Thanks for looking.
Craigo

**Comment by carter2422** [comment]
Ah yes, this is the same as #280, which you can try by grabbing the [issue/280](https://github.com/CGCookie/retopoflow/tree/issue/280) branch.

**Comment by carter2422** [comment]
A quick way to confirm @artistCDMJ is simply toggle into Perspective view, does the overlapping shading correct its self?

**Comment by artistCDMJ** [comment]
I tried the numpad 5 key and lost my view, so I zoomed out a bit and tried again, and yes, that got me a better view of the Polystrips. I am guessing something is different now, but I can work with this and keep going, so feel free to close this issue :+1: 

Going to be a few days before I can try it deeper, but this does already look pretty good as a far as I can tell. Thanks!
