### ISSUE TITLE
Polystrips. Transform tweak do nothing 

### ISSUE THREAD

**Issue by OscarLeif** [CGCookie/retopoflow#283]
Hello I found a interesting option in Polystrips, in the help section shows a Transform.
G: grab
R: rotate
S: scale
**T: Tweak (Hold T and drag with LMB)**

I'm not sure about this you can actually tweak the geometry, but if you're in edit mode.
The Polystrips shows this, I guess it means that tweak works in Polystrips edit mode but If I press **T**
and use LMB and click on the geometry it do nothing.

**Comment by carter2422** [comment]
@OscarLeif Polystrips Tweak is primarily intended for fine-tuning patch results. After drawing your strips and filling patches press and hold T then brush across vertices to tweak their position. They will turn white to indicate they've been modified and are no longer dynamic.

**Comment by OscarLeif** [comment]
Oh I guess there's no problem with that...I'm gonna close this.

**Comment by carter2422** [comment]
Cheers! Please keep on reporting any other issues you find @OscarLeif, it's a big help!
