### ISSUE TITLE
Polypen Error

### ISSUE THREAD

**Issue by richobrien** [CGCookie/retopoflow#286]
Polypen error log

`EXCEPTION (<class 'AssertionError'>): 
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\op_polypen\polypen_modal.py
000 0892:handle_action_seledge() assert bme in self.selected_bmedges
001 0778:handle_action() return self.handle_action_seledge(context, eventd)
002 0386:modal_wait() return self.handle_action(context, eventd)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\modaloperator.py
003 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
004 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

EXCEPTION (<class 'TypeError'>): intersect_point_tri_2d
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\op_polypen\polypen_modal.py
000 0733:closest_bmface() if not intersect_point_tri_2d(p2d, v02d, v12d, v22d): continue
001 0307:modal_wait() min_bmf = self.closest_bmface(context, p2d, p3d, 0.05)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\modaloperator.py
002 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
003 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

EXCEPTION (<class 'TypeError'>): intersect_point_tri_2d
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\op_polypen\polypen_modal.py
000 0733:closest_bmface() if not intersect_point_tri_2d(p2d, v02d, v12d, v22d): continue
001 0307:modal_wait() min_bmf = self.closest_bmface(context, p2d, p3d, 0.05)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoFlow\modaloperator.py
002 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
003 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)`

**Comment by OscarLeif** [comment]
I also get that error but what exactly did you do ?

**Comment by richobrien** [comment]
Enter Edit Mode

Hover to highlight edge|vert and error occurs

**Comment by carter2422** [comment]
@richobrien I'm not able to replicate this. Which version of RetopoFlow are you using? Additionally, did you do a full uninstall of the previous version before you installed your current one?

**Comment by richobrien** [comment]
@carter2422 1.2.3

I used Blender's Remove button to get rid of 1.2.2 then added 1.2.3. Restarted Blender.

The error mostly occurs if I middle mouse down or scroll wheel while highlighting points | edges | faces. There's a pause then the error occurs.

**Comment by richobrien** [comment]
`EXCEPTION (<class 'TypeError'>): intersect_point_tri_2d
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_polypen\polypen_modal.py
000 0743:closest_bmface() if not intersect_point_tri_2d(p2d, v02d, v12d, v22d): continue
001 0307:modal_wait() min_bmf = self.closest_bmface(context, p2d, p3d, 0.05)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
002 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
003 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

EXCEPTION (<class 'TypeError'>): intersect_point_tri_2d
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_polypen\polypen_modal.py
000 0743:closest_bmface() if not intersect_point_tri_2d(p2d, v02d, v12d, v22d): continue
001 0307:modal_wait() min_bmf = self.closest_bmface(context, p2d, p3d, 0.05)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
002 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
003 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)

EXCEPTION (<class 'TypeError'>): intersect_point_tri_2d
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_polypen\polypen_modal.py
000 0743:closest_bmface() if not intersect_point_tri_2d(p2d, v02d, v12d, v22d): continue
001 0307:modal_wait() min_bmf = self.closest_bmface(context, p2d, p3d, 0.05)
         C:\Users\User1\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
002 0245:modal_main() nmode = self.FSM['wait'](context, eventd)
003 0300:modal() nmode = self.FSM[self.fsm_mode](context, eventd)`

Upgraded to 1.2.4 and got this using the Polypen again. It happened when zooming. It seems to occur more frequently when I zoom. At times if I immediately re-enter Polypen/Polystrips after this error then Blender crashes....

![image](https://cloud.githubusercontent.com/assets/4971991/21156044/50f5de6a-c16c-11e6-9d1c-5950646a1cea.png)

**Comment by carter2422** [comment]
@vxlcoder you able to dig into @richobrien report above with me? I've not yet been able to replicate it but that's a really nasty bug...

**Comment by richobrien** [comment]
Could this issue is related to the camera/view?

![retopoflow-error](https://cloud.githubusercontent.com/assets/4971991/21232307/085056ea-c2e3-11e6-8878-9e966bb104d4.gif)

The majority of errors occur if you enter into a mesh. Just throwing that out in case it helps.

**Comment by SkaveRat** [comment]
Got the error as well. Happened the first time when I entered the mesh with the camera, so I think it has to do with that

**Comment by carter2422** [comment]
Interesting. We'll investigate!

**Comment by vxlcoder** [comment]
branch issue/286 should fix this problem.  thanks for the report!  let me know if anything else shows.

**Comment by carter2422** [comment]
Confirmed fixed @vxlcoder! Thanks for the reports everyone. This will be fixed in v1.3.1.
