### ISSUE TITLE
EXCEPTION (<class 'RecursionError'>): maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by bassair** [CGCookie/retopoflow#291]
![image](https://cloud.githubusercontent.com/assets/9505224/21177050/572f39be-c1e1-11e6-9012-0030a3f1a787.png)

No idea what's causing it :) I'm using mirrors and polystrips.

**Comment by carter2422** [comment]
@bassair was this a one-time error or are you able to replicate it? If you can replicate it, can you tell me the steps taken to do so?

**Comment by bassair** [comment]
@carter2422 I mean I was just... using it. I know that sounds a lot like a cop-out but that's honestly all I was doing.

1. Import high-poly messy mesh from zbrush
2. Assign it as source
3. Click polystrips
4. Start applying polystrips
5. Shift+F to fill holes
6. Rearranging the draggy parts when the holes don't match up right
7. Adding more strips

Then eventually once most of the face had strips it started spitting that error, then it told me to open an issue on CgCookie, then it deleted my work. I clicked polystrips again, then I hit undo and it came back, but it errored out the same way afterwards.

I also did the topology around an eye using polypen afterwards and it did the same thing. 

I mean, I guess it might be my high poly model but... I'm unsure why it would be?

**Comment by carter2422** [comment]
@bassair roughly how many polystrips and/or patches had you created?

**Comment by bassair** [comment]
@carter2422 Um... 50 strips? Unsure about patches. Maybe another 25?

**Comment by carter2422** [comment]
Although it shouldn't happen, it's possible you're running into a unrecognized limit. I'll investigate as best I can but for now I'd recommend you work in shorter segments; creating 10-20 strips (and associated patches), then commit the work, then activate polystrips again. 

☝️ this is actually how the tool is intended to be used.

**Comment by bassair** [comment]
Fair enough! Honestly I only started with it a couple of hours ago, running into the issues slowed down my practice though :) 

Thanks so much for the speedy replies and assistance.

**Comment by carter2422** [comment]
Let me know if you encounter any other issues!

**Comment by bassair** [comment]
Hello again, I encountered more issues!

I went over my body sculpt with a bunch of loops to set up for more detailed retopo:

![image](https://cloud.githubusercontent.com/assets/9505224/21213515/c71a2fd0-c28c-11e6-8a39-19a1a8863886.png)

Then I hit enter and I swapped to polypen

I hit polypen and it comes up like this

![image](https://cloud.githubusercontent.com/assets/9505224/21213527/d96c38cc-c28c-11e6-98fd-68976a0ea491.png)

Then I move my mouse and this comes up

![image](https://cloud.githubusercontent.com/assets/9505224/21213532/e38fd336-c28c-11e6-946c-b2551b22fecb.png)

Aaand

![image](https://cloud.githubusercontent.com/assets/9505224/21213539/ee4a37a8-c28c-11e6-8d7b-83ad65cadf87.png)

And then it sends me out to nothingness and now I can't edit my retopo to clean it up :/ 

Zooming in and out seems to make it bug out too.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
