### ISSUE TITLE
PolyStrips draws strange polystrips 

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#293]
The green line where the polystrip is going to be is drawn properly but when releasing the mouse and the polystrip is drawn it is something. 
![2016-12-06 18_53_04-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192514/261babc6-c229-11e6-8f31-c52996b0ca3c.png)
the green line looks properly

![2016-12-06 18_53_22-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192524/2fbb3034-c229-11e6-9635-4683761ea079.png)
after applying the polystrip it looks completily wrong. 

![2016-12-06 18_57_04-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192561/499e6c46-c229-11e6-9c79-19b32c36f659.png)
![2016-12-06 18_57_20-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192563/4b7e6f34-c229-11e6-873f-5b5b8fc10559.png)

**Comment by Weisl** [comment]
I commited it by accident already. The green line where the polystrip is going to be is drawn properly but when releasing the mouse and the polystrip is drawn it is something. 
![2016-12-06 18_53_04-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192514/261babc6-c229-11e6-8f31-c52996b0ca3c.png)
the green line looks properly

![2016-12-06 18_53_22-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192524/2fbb3034-c229-11e6-9635-4683761ea079.png)
after applying the polystrip it looks completily wrong. 

![2016-12-06 18_57_04-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192561/499e6c46-c229-11e6-9c79-19b32c36f659.png)
![2016-12-06 18_57_20-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21192563/4b7e6f34-c229-11e6-873f-5b5b8fc10559.png)

**Comment by carter2422** [comment]
To be sure, @Weisl which version of RetopoFlow are you on?

**Comment by carter2422** [comment]
Also @Weisl, what is the scale and dimension of the character model?

**Comment by Weisl** [comment]
Ok, those screenshots are still from some days ago. I was still using the older version, the one before the last release. I quickly tried it out with the current version and it worked fine for those areas. If I run into trouble here I will write it. 
The character size was 1,8m.

**Comment by carter2422** [comment]
Okay great! If you run into the issues again please just re-open this issue.
