### ISSUE TITLE
Source Object with 0 vertices -> Crash

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#296]
Polystrips crashes when using an object with no vertices as the source object. You should be abble to reconstruct the error by deleting all vertices of the source object and use polystrips on it. 

[RetopoFlow_zero_vertices.txt](https://github.com/CGCookie/retopoflow/files/654521/RetopoFlow_zero_vertices.txt)

**Comment by OscarLeif** [comment]
That doesn't look so hard to fix. 
I propose this, If an Object who has a mesh with zero vertex should be erased. That's like an empty object.

**Comment by carter2422** [comment]
Good catch @Weisl; I'll get this fixed! If a source object has no vertices then we shouldn't allow the tool the start and thus display a relevant error message for the user.

**Comment by vxlcoder** [comment]
should be fixed

**Comment by carter2422** [comment]
Confirmed fixed. Will be in 1.3.1.
