### ISSUE TITLE
maximum recursion depth exceeded

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#297]
"EXCEPTION (<class 'RecursionError'>): maximum recursion depth exceeded in comparison ...."

If it helps you, I can send you the file I am wokring with. 

![image](https://cloud.githubusercontent.com/assets/6353016/21223017/5369e038-c2c5-11e6-85f7-dcfa177e5b83.png)

[RetopoFlow_max_recursion_log (2).txt](https://github.com/CGCookie/retopoflow/files/654562/RetopoFlow_max_recursion_log.2.txt)

**Comment by Weisl** [comment]
It happens when i try to fill this area.

![2016-12-15 12_56_40-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21223141/fca4eef4-c2c5-11e6-95e2-5f28e587a1d5.png)

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
