### ISSUE TITLE
Unwanted segment adding destroys fills. 

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#298]
Just a minor thing

![2016-12-15 13_00_31-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21225153/e09f3c46-c2cf-11e6-8357-97379e34e747.png)

![2016-12-15 13_00_41-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21225154/e20f68f8-c2cf-11e6-856a-fe783d6b099d.png)
When I want to draw a stroke upwoards, it also adds new segments at the bottom, which destroys my fills. 

![2016-12-15 14_10_28-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21225247/47216a70-c2d0-11e6-8fa0-1fafe20455fb.png)
![2016-12-15 14_10_35-blender_ e__onedrive_2016_pro1_da_002_production_edit_character_blender_low_cha](https://cloud.githubusercontent.com/assets/6353016/21225249/49239352-c2d0-11e6-8ebf-07b45ff2e819.png)

**Comment by carter2422** [comment]
Hm. I can't replicate this. I've attempted to recreate your patch pattern @Weisl and then repeat the process. No such extra segment gets added. 

![screen shot 2016-12-22 at 9 49 03 am](https://cloud.githubusercontent.com/assets/1648631/21431203/fea10d9e-c82b-11e6-86f9-189fc4365444.png)
![screen shot 2016-12-22 at 9 49 15 am](https://cloud.githubusercontent.com/assets/1648631/21431207/00c98c40-c82c-11e6-9f3b-ac68c3ba430b.png)


Are you able to consistently replicate this?

**Comment by carter2422** [comment]
@Weisl were you ever able to replicate this by chance?

This issue will no longer be present in 2.0.0 as we're changing the way geometry is created. I'm going to go ahead and close this due to 2.0.0 changing things, but if you run into it again please feel free to re-open.
