### ISSUE TITLE
Move Contour Edge on not waterproof object -> error

### ISSUE THREAD

**Issue by Weisl** [CGCookie/retopoflow#299]
This error should be really easy to reconstruct. 

Contouring a non-manifold object, such as the pictured cube, causes a error if you move one of the loops over the hole. For example, create two contours immediately to the left of the hole then slide the right-most loop over the hole. Instant error. Seemingly the only option then is to delete the loop and redo it, as any interaction with the loop recalls the same error. 

![screen shot 2016-12-22 at 9 43 49 am](https://cloud.githubusercontent.com/assets/1648631/21431058/6a4b7616-c82b-11e6-9535-bce813ad3724.png)
![screen shot 2016-12-22 at 9 43 54 am](https://cloud.githubusercontent.com/assets/1648631/21431061/6c946630-c82b-11e6-8ef0-9f6bdc48838b.png)

Here is the error:
```
EXCEPTION (<class 'StopIteration'>): 
         C:\Users\Matthias\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_contours\contour_utilities.py
000 2162:cross_section_walker() f_cur = next(f for f in bme.edges[eind_from].link_faces if f.index != find_from)
001 2251:cross_section_seed_ver1() verts0,looped = cross_section_walker(bme, pt, no, seed_index, ei0_max[0].index, ei0_max[1], epsilon)
002 2307:cross_section_seed() ret = cross_section_seed_ver1(bme, mx, point, normal, seed_index, max_tests, debug)
         C:\Users\Matthias\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_contours\contour_classes.py
003 2912:cut_object() cross = contour_utilities.cross_section_seed(bme, mx, pt, pno, indx, debug = True, method = meth)
004 0870:widget_transform() self.sel_loop.cut_object(context, mesh_cache['bme'], mesh_cache['bvh'], self.mx)
         C:\Users\Matthias\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\op_contours\contours_modal.py
005 0340:modal_widget() self.contours.widget_transform(context, self.settings, eventd)
         C:\Users\Matthias\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\RetopoFlow\modaloperator.py
006 0300:modal() nmode = self.FSM[self.fsm_mode](context, events)

```
[Contour_log.txt](https://github.com/CGCookie/retopoflow/files/663511/Contour_log.txt)

**Comment by carter2422** [comment]
Good catch @Weisl. I'll update the original post with more info.

**Comment by vxlcoder** [comment]
As noted in commit 5af4421, this issue is patched, but the underlying problem still remains.  @carter2422, should we open a new issue to address loops that cut across holes in a mesh?  on a separate but related note, what if mesh is broken up across several objects?

**Comment by carter2422** [comment]
@vxlcoder yeah let's go ahead and open a new issue for loops crossing holes and perhaps a second for for supporting multiple objects (group?) as the source.

**Comment by carter2422** [comment]
- [ ] Add *Why* comments on code conditions for handling holes: https://github.com/CGCookie/retopoflow/commit/5af4421c1579247442c2018e024c8f19ef06b46c#commitcomment-20391170
