### ISSUE TITLE
Tweak resets vertex position when they reach the Border

### ISSUE THREAD

**Issue by OscarLeif** [CGCookie/retopoflow#301]
Hello I found this behavior while using Tweak when you are editing a surface and when you reach the border it will reset to the original position. Using **Polypen** when you do this it doesn't happen. I really don't know if this was designed to work like this.

![polypen issue](https://cloud.githubusercontent.com/assets/2281056/21593368/36312756-d0e4-11e6-816f-fe15f4f27559.gif)

**Comment by carter2422** [comment]
That's pretty annoying. Good catch @OscarLeif. 

We should improve this by simply stopping at the border rather than resetting. 

Thoughts @vxlcoder?

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
