### ISSUE TITLE
Contours: deleting loop when hovering causes crashes

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#302]
Deleting loop while hovering over it causes widget to not disappear.  If widget is activated, crash.

![image](https://cloud.githubusercontent.com/assets/3790699/21612529/9a1c7c00-d19f-11e6-8189-74a37bd32bfb.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21612552/b6d250a4-d19f-11e6-824d-731fdb4b4c29.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21612711/4fa3c9b6-d1a0-11e6-84a3-82d114b18eb0.png)

Also, when deleting the last loop, widget stays permanently, and crash occurs when trying to make another cut.

![image](https://cloud.githubusercontent.com/assets/3790699/21612632/077029be-d1a0-11e6-94b5-6af3882e9bfd.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21612647/13549bd4-d1a0-11e6-8675-a7a07ebc306c.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21612668/25477d34-d1a0-11e6-8824-619ce0f3e2fe.png)

**Comment by carter2422** [comment]
Good catch! I'll test shortly.

**Comment by carter2422** [comment]
I couldn't ever replicate this, other than the widget not disappearing until a mouse move. 

What're the steps to replicate @vxlcoder ?

**Comment by carter2422** [comment]
Never mind, I replicated! Merging and closing.
