### ISSUE TITLE
Contours: shifting loop too far causes strange results

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#303]
Strange results if a loop is shifted too far in either direction.

![image](https://cloud.githubusercontent.com/assets/3790699/21614117/3354deca-d1a6-11e6-93a7-33459be687f6.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21614169/6162c6d8-d1a6-11e6-824e-1d3245f5f903.png)

![image](https://cloud.githubusercontent.com/assets/3790699/21614183/7744e634-d1a6-11e6-860c-7a0530a8bced.png)

**Comment by carter2422** [comment]
I can't replicate this at all.

**Comment by vxlcoder** [comment]
select a loop, then hold left (or right) until it wraps/cycles around 2 or 3 times.

**Comment by carter2422** [comment]
Ah ha! Replicated and confirmed fixed.
