### ISSUE TITLE
Polystrips existing geometry drawing below the surface

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#305]
I'm not sure when it changed, but Polystrips is drawing existing geometry blow the surface. 

Here's what it looks like on the Cobra model:

![screen shot 2017-01-06 at 1 04 07 pm](https://cloud.githubusercontent.com/assets/1648631/21729480/ed902620-d410-11e6-8d68-a356a00cb186.png)

![screen shot 2017-01-06 at 1 04 15 pm](https://cloud.githubusercontent.com/assets/1648631/21729481/ed918b14-d410-11e6-89b7-48268f733350.png)

![screen shot 2017-01-06 at 1 04 27 pm](https://cloud.githubusercontent.com/assets/1648631/21729482/ed926e9e-d410-11e6-8ea3-d417fdf97286.png)

For comparison, here's Polypen:
![screen shot 2017-01-06 at 1 04 34 pm](https://cloud.githubusercontent.com/assets/1648631/21729479/ed8530ee-d410-11e6-9f59-2c9779776fa3.png)

**Comment by carter2422** [comment]
@vxlcoder game to look at this one for 1.3.1?

**Comment by vxlcoder** [comment]
will take a look

**Comment by carter2422** [comment]
That's much better @vxlcoder, although we've now lost the face-highlight on-hover for Polystrips from existing faces.

**Comment by vxlcoder** [comment]
@carter2422 Is this better?

**Comment by vxlcoder** [comment]
note: there is still some issue with geometry poking through, but this will always be a problem

**Comment by carter2422** [comment]
That appears to be substantially better. Merged.
