### ISSUE TITLE
LoopCut bug: no attribute `cyclic`

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#312]
When starting LoopCut, this error showed up in console

```
EXCEPTION (<class 'AttributeError'>): 'LoopCut' object has no attribute 'cyclic'
         /home/jdenning/software/blender-2.78a/2.78/scripts/addons/retopoflow/op_loopcut/loopcut_ui_draw.py
000 0035:draw_postview() if self.loopcut.cyclic:
         /home/jdenning/software/blender-2.78a/2.78/scripts/addons/retopoflow/modaloperator.py
001 0162:draw_callback_postview() self.draw_postview(context)
```

**Comment by carter2422** [comment]
I can't seem to replicate this in `release/1.3.1`. Doing anything special to output that other than starting loop cut @vxlcoder ?

**Comment by vxlcoder** [comment]
It happened very specific condition, and I cannot recall how I produced it.  at the very least, the commit e9da692 is removing duplicate code.
