### ISSUE TITLE
Retoflow 1.3 not working tweak in Polystrips

### ISSUE THREAD

**Issue by santimsf** [CGCookie/retopoflow#318]
Press "T" not nothing happens

**Comment by carter2422** [comment]
@santimsf double check that the Location, Rotation, and Scale of your source and target objects match. This is a limitation that is being removed in v1.3.1, but in v1.3.0 it can break Tweak. 

I'd also suggest applying the Scale and Rotation on both objects via CTRL+A.

**Comment by santimsf** [comment]
Thanks!!

**Comment by carter2422** [comment]
Happy to help!
