### ISSUE TITLE
"Maximum recursion depth exceeded" error

### ISSUE THREAD

**Issue by OneRatNoWalls** [CGCookie/retopoflow#319]
When using polystrips on the mesh shown in the images, I'm getting the error message "Maximum recursion depth exceeded in comparison". It comes up when I'm creating a patch, generally after I've made several other patches successfully. I then find I can't delete any of the strips around the attempted patch; I get a class 'AssertionError' message when I try. (I can delete all the other strips without trouble; only the ones I tried to make the patch with are stuck.) If I press escape and then recover the session with ctrl+z, the strips are still undeletable. I'm forced to abandon the session and lose the work. The problem occurs every time I try to create the mesh around the eyes as shown in the images.
The recursion error:
![recursion error](https://cloud.githubusercontent.com/assets/6516892/22180687/6a730974-e02c-11e6-9e3c-1bc9762439f9.jpg)
The assertion error message:
![assertion error](https://cloud.githubusercontent.com/assets/6516892/22180696/a59adb4e-e02c-11e6-8035-580fc7b8705f.jpg)
The strips I'm trying to make:
![error mesh](https://cloud.githubusercontent.com/assets/6516892/22180698/b28fb748-e02c-11e6-9d95-b84548b4d144.jpg)

**Comment by carter2422** [comment]
Hey @OneRatNoWalls my apologies for completely missing this report. 

The error is likely because you're trying to fill the five-sided patch, which requires you to select all bordering polystrips. We try and auto-detect the type of patch to fill but in these scenarios it requires you to be more explicit in the filling.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!
