### ISSUE TITLE
Getting an installation issue 

### ISSUE THREAD

**Issue by relaxis** [CGCookie/retopoflow#320]
When I try to activate the module in the user preferences I get this - : 

[https://postimg.org/image/iuocbfstj/](url)

Is there a fix? Blender 2.78a

**Comment by carter2422** [comment]
@relaxis that image link isn't working. You can upload the image directly here on GitHub.

**Comment by TheDuckCow** [comment]
If you copy paste the plain image URL it works - and I see it's an issue with a sub import of the updater module. What version of windows are you running? As it seems to have an issue with the in lauded blender socket library.

**Comment by TheDuckCow** [comment]
@carter2422 looking into seeing how we can make imports more stable, but it's a bit tricky (though possible) to defend against built in system library issues like the socket library. Nonetheless I'm working on it.

**Comment by TheDuckCow** [comment]
The code added now in this 320 branch is complete and would allow retopoflow to be used in the above scenario; it adds code to essentially gracefully disable the updater module if there are errors that occur in the `addon_updater.py` file, such as failing to import the system's socket library as in this reported case.

**Comment by carter2422** [comment]
Thanks @TheDuckCow! I'll check it out and tentatively merge into 1.3.1.

**Comment by carter2422** [comment]
Merged for release in 1.3.1
