### ISSUE TITLE
Parts of object unable to be edited - clipping plane?

### ISSUE THREAD

**Issue by animatoring** [CGCookie/retopoflow#321]
![preview](https://cloud.githubusercontent.com/assets/25253627/22346042/741a65c4-e3d0-11e6-9276-6c0dfb86a962.PNG)

When adjusting part of the topology, parts of the model will be unable to be edited. They will have something similar to a clipping plane issue where parts of the object cannot be edited with RetopoFlow. Above is a preview of the error. Adjusting the clip plane in Blender didn't solve the problem within RetopoFlow.

**Comment by carter2422** [comment]
From your screenshot it would appear you have no source object behind the geometry. The source object is required for Polypen, and so if you start polypen with "floating geometry" this geometry will not be able to be modified via Polypen as it has no source to snap to.

**Comment by animatoring** [comment]
I hid the source object to better view the error. I'll try to make a blend file with the error.

**Comment by animatoring** [comment]
I'm working on a popcorn scene and I think the scale is affecting how well some vertices can be selected with polypen.

Blend file: http://pasteall.org/blend/index.php?id=45273
![hidden](https://cloud.githubusercontent.com/assets/25253627/22355635/c251a378-e3f9-11e6-98b8-9e4665c7ac71.PNG)

For this one I'd like to block out the rough shape of the object by making four faces around the largest part of the object. Polypen doesn't seem to like it if the points are too far away from each other and hides some of them from view. This model's problem isn't too bad because I can still move the vertices closer but there have been some times where I can't select some vertices at all. I think it may have to do with the source object's scale.

Two vertices I'd like to connect to make a face are not visible from some views. This makes sense sometimes but if you are working with an object with certain scales it seems like most of the angles to view the object don't allow the vertices to be selected. It happens a lot when you try to zoom in on an object and a lot of the vertices can no longer be selected. You can select them if you zoom out sometimes but on smaller scale objects zooming out isn't always an option because you can't select vertices that are too small.

**Comment by animatoring** [comment]
I just read the reply on the blender market about the vertices being obscured from view by the object, that completely makes sense. Think that is what is happening in this case and adjusting the scale of the source object is the fix. : )

**Comment by carter2422** [comment]
That's good to hear the scale and view fixed it @animatoring! Thanks for being so diligent and active on reporting these issues. It really helps a lot to improve RetopoFlow.

**Comment by animatoring** [comment]
After working with this more, is there any chance an option could be created to adjust the sensitivity clip plane within RetopoFlow for smaller objects? Scaling is one fix but scaling multiple objects really increases your workflow with a large scene.

**Comment by carter2422** [comment]
Sorry for missing this earlier. 

Clip plane sensitivity is something we aim to fix entirely in v2.0, which is being worked on right now. We hope to show an alpha at SIGGRAPH.
