### ISSUE TITLE
Hotkeys (enhancement)

### ISSUE THREAD

**Issue by animatoring** [CGCookie/retopoflow#322]
Is it possible to add hotkeys for each RetopoFlow function? For example could Polypen in object mode or Edge Loop in edit mode have hotkeys?

**Comment by carter2422** [comment]
Yep! You can do this already via Blender's User Preferences > Input. 

Simply add a new entry under `3D View > Object` for Polypen, Polystrips, and Contours. And then entries in `3D View > Mesh` for the other tools. 

The identifier for the hotkey is simply `cgcookie.<name of tool in lowercase>`. For example, `cgcookie.polypen`. 

Here's a screenshot: 
![screen shot 2017-01-26 at 1 25 15 pm](https://cloud.githubusercontent.com/assets/1648631/22346969/ac6bca1c-e3cb-11e6-852d-5c94145503c5.png)

The full list is:

- `cgcookie.contours`
- `cgcookie.polystrips`
- `cgcookie.polypen`
-`cgcookie.tweak`
-`cgcookie.loop_cut`
-`cgcookie.loop_slide`

**Comment by animatoring** [comment]
Thanks Carter this helps a lot! : )

**Comment by theoldben** [comment]
Can I use this to redirect the Undo / Redo commands somehow? I am not using a QWERTY keyboard.

**Comment by carter2422** [comment]
@theoldben you can modify the hotkeys in RetopoFlow 2 by modifying the `keymaps.py` file directly. It's located in the base RetopoFlow folder in your add-ons path. It's not the most user friendly but the previous method had some serious limitations that we've had to work around.

**Comment by theoldben** [comment]
No sweat, that'll work fine for me!

**Comment by theoldben** [comment]
Works like a charm. Having all the hotkeys in one tight space like that is neat. Well done.
