### ISSUE TITLE
Add support for View selected while in RetopoFlow

### ISSUE THREAD

**Issue by ChameleonScales** [CGCookie/retopoflow#327]
"View selected" (numpad .) is still using the entire object when using Retopoflow. How can we center the view on the selection so we can move our camera around our working area ?
The 3D cursor can't be moved when using Retopoflow. We may position it where we'll start working but then we'll have to exit Retopoflow to reposition it, thus losing our dynamic work.

**Comment by carter2422** [comment]
@ChameleonScales this is something I'd like to see resolved as well. We'll investigate it. 

@patmo141 @vxlcoder do either of you know if this is something we can do? To my understanding there's no way do modify the selection during RetopoFlow, as it's all in BMesh and not yet an Edit Mesh for which selections operate on. Or maybe I'm totally wrong?

**Comment by carter2422** [comment]
I'm happy to say this is working in `release/2.0.0`, which is a major overhaul of RetopoFlow's entire workflow and codebase.

**Comment by ChameleonScales** [comment]
2.0 really looks like a complete rework. That's exciting ! Although it's pretty laggy compared to 1.3 at the moment.

**Comment by carter2422** [comment]
It's a complete overhaul! The lagginess is bbecause we haven't done much optimization yet. 

2.0.0 is in pre-pre-alpha, so everything is subject to change.
