### ISSUE TITLE
Keep x-ray enabled

### ISSUE THREAD

**Issue by ChameleonScales** [CGCookie/retopoflow#328]
I don't know why leaving a retopoflow tool disables x-ray, but usually when retopologizing, we want to see our retopologized model clearly. If there's a good reason I don't know as for why it behaves like this, at least an option to keep it enabled for those who want to would be great.

**Comment by carter2422** [comment]
This shouldn't be happening. I'll investigate. Thanks for the report @ChameleonScales

**Comment by vxlcoder** [comment]
@ChameleonScales please see if branch `issue/328` fixes the problem for you.  Thanks for the report!

**Comment by ChameleonScales** [comment]
You rule.

**Comment by carter2422** [comment]
Merged for 1.3.1!
