### ISSUE TITLE
View material thru polypen/tweak modes

### ISSUE THREAD

**Issue by animatoring** [CGCookie/retopoflow#329]
Is there any chance you could add an option for the material to be visible through polypen and tweak modes? It is helpful for your eyes to see something like a matcap on under the points. 

For example:
![material](https://cloud.githubusercontent.com/assets/25253627/22597266/e934264c-e9fc-11e6-9df6-6e6a5d949873.PNG)
I duplicated my object with a matcap on underneath and made it visible but not selectable in polypen mode. It would be great to work with something like this in polypen and tweak modes. Duplicating the original model and keeping it underneath half helps but if you dramatically change the geometry it isn't very helpful unless it is the original model.

**Comment by vxlcoder** [comment]
@animatoring, do you mean to have the PolyPen slightly transparent?  And that the transparency can be controlled?

**Comment by animatoring** [comment]
Could polypen be 100% visible with the material underneath either at 100% or controlled transparent? It helps not to see the backface on polypen sometimes too so maybe a backface on/off would also be helpful. Thanks!

**Comment by carter2422** [comment]
@animatoring this is actually how it should already be working. Here's a screenshot of Polypen while working on a source object that has a MatCap. 
![screen shot 2017-02-04 at 1 03 42 pm](https://cloud.githubusercontent.com/assets/1648631/22620873/741c22d6-eada-11e6-8acc-b15411ea3c43.png)

It seems your's is not working this way?

Based on the stepping in the shading of your source object (the blocky shading artifacts) it looks to me like you have a visual display problem in Blender its self. Which MatCap are you using?

**Comment by animatoring** [comment]
Yeah it might be a display problem on custom matcaps. I was using a custom matcap using one of zbrush's matcaps. I am using this node setup:
![matcapnodes](https://cloud.githubusercontent.com/assets/25253627/22622616/0c840dc2-eb0d-11e6-95b9-c14ebb98b1ad.PNG)

With this matcap image: 
![sculpy_peach](https://cloud.githubusercontent.com/assets/25253627/22622619/1fac7218-eb0d-11e6-9b6f-e81309765566.png)

I tried it polypen with Blender's matcaps and the are working great. Looks like it might just be the custom matcaps that don't display with polypen.

**Comment by animatoring** [comment]
Blend file: http://pasteall.org/blend/index.php?id=45420

Thanks for the tip about Blender's matcaps, for now that seems like the best option. : )

**Comment by carter2422** [comment]
I don't have a matcap image on hand to test, but I have confirmed that Cycles Material view works nicely with RetopoFlow 2.0.

Here's a screenshot with a Fresnel blend of two colors on a sphere. 
![screen shot 2018-07-25 at 4 30 53 pm](https://user-images.githubusercontent.com/1648631/43228800-371e5972-9028-11e8-864a-591a23ae8e6a.png)
