### ISSUE TITLE
Weird text issue when trying to use polypen

### ISSUE THREAD

**Issue by thedonquixotic** [CGCookie/retopoflow#333]
Just started using and learning Retopoflow and I can only use the polypen for about 3 minutes before my screen wigs out and I get messed up text, looks like this: http://i.imgur.com/tPLQbNs.png

**Comment by carter2422** [comment]
I've seen this a few times but have never been able to replicate it. @thedonquixotic are you able to replicate the issue on a particular model and let us know how to replicate it ourselves? 

Also, are you seeing any errors in the error log? You can open the log via the tool bar, *Open Error Log*.

**Comment by thedonquixotic** [comment]
I can't really see the error log because the text makes it hard to see anything and everything else goes kind of crazy. I can replicate it pretty easily. Using a hi-poly sculpt exported from Oculus Medium. let me upload it real quick

**Comment by carter2422** [comment]
You can open the error log after restarting Blender. 

Let me know the steps you take to replicate on the file and I'll test it as well.

**Comment by thedonquixotic** [comment]
Here's a temporary link: https://expirebox.com/download/5f31db1e96bdf0c9eaf3622ebbe393f6.html

**Comment by carter2422** [comment]
Great! I'm heading off for dinner now but will test it soon. Thanks.

**Comment by thedonquixotic** [comment]
Thanks! Love what I've tried so far :)

**Comment by thedonquixotic** [comment]
Here's another example of it happening: http://i.imgur.com/bcvrAcH.png

**Comment by vxlcoder** [comment]
Hi @thedonquixotic! 

I'm here too late for your temp link to work.

Any chance you might be able to reproduce the console log?

**Comment by thedonquixotic** [comment]
Hey sorry, I just remembered to check back in on this. 

So I ended up finding my around this without retopoflow. Mostly just selecting and merging vertices by hand. It doesn't have good edgeflow (a concept I'm still learning about) but it got the job done for what I needed for now. (here's the thing I made! https://sketchfab.com/models/fa0a42be044742ffade1d468fad21cbb) 

It's been too long for me to check the console logs but as I'm intending to integrate Oculus Medium into my regular 3D workflow, and since OM outputs at high polys without the benefit of a multi resolution modifier like Zbrush, I'll be needing to do do retopo work in the future, and when I do, and if I run into this error again, I'll be sure to post about it and try and get you guys as much info as possible. 

Some of it may just come down to the meshes generated by OM being not particularly good. These are my first really large scale efforts in modeling, so I'm having to learn and improvise a lot. The original way I modeled things was definitely not optimized for exporting and then pulling things into blender. It's been an interesting process! If you're interested at all, I wrote a medium article here: https://medium.com/@davidaslanfrench/what-ive-learned-sculpting-in-virtual-reality-oculus-medium-15ba6b16d93a#.byiql3xia

Originally I modeled her dress using a leaf stamp, but when exported it was well over 1.5 gigabyte OBJ file, and I had to basically just scrap it and box model then resculpt the dress with the idea of using transparency shaders in mind.

**Comment by carter2422** [comment]
Thanks for the input @thedonquixotic! 

> Some of it may just come down to the meshes generated by OM being not particularly good.

I suspect this is exactly the issue, which should help us track down the core of the issue.

**Comment by vxlcoder** [comment]
I believe this issue applies to v1.x only, so I'm going to close this issue now that v2.0 is officially released (see `release/2.0.0` branch or Blender Market page).  If this is still an issue with v2.0, please reopen, and post more details.  Thanks for reporting this issue, and we look forward to seeing how v2.0 helps your retopo workflow!

**Comment by thedonquixotic** [comment]
Thanks will do :)
