### ISSUE TITLE
Tweak tool crashing often

### ISSUE THREAD

**Issue by animatoring** [CGCookie/retopoflow#334]
The tweak tool crashes when I use a larger brush size with an average amount of vertices. Is there anything I can do to avoid it crashing so often? It does really well with some models and crash every other time on other ones. When it crashes it locks the 3d view in the tweak tool unfortunately making it so you cannot exit to save previous work. If possible could it be edited to undo the last tweak tool if it crashes?

For example, on this blend file on the popcorn13 contours object using the tweak tool causes it to crash about every other time you use it. 

Blend file: http://pasteall.org/blend/index.php?id=45720

**Comment by animatoring** [comment]
I think it had to do with the scale of the object in this case, it was a smaller object and zooming out helps it to crash less often.

**Comment by vxlcoder** [comment]
Which version of RF and Blender are you using?  I'm having troubles trying to reproduce your crash.

**Comment by animatoring** [comment]
Blender v2.78a, Retopoflow 1.3 on windows 10. It usually crashes most often if you zoom in some then use a larger brush size. It does somewhat of a soft crash where it will get stuck in the tweak tool.

**Comment by animatoring** [comment]
Another quirky fix that somewhat helps with the tweak tool freezing is pressing the +/- to adjust the brush size on the numpad. Somehow it was able to get out of the freeze mode at least sometimes. :D

**Comment by carter2422** [comment]
@animatoring did you ever get a chance to test the tweak issues in 1.3.1? From all my testing this is resolved and so I'm closing. If you can replicate in 1.3.1 then please reopen and let me know.
