### ISSUE TITLE
Polypen Randomly Breaks Blender UI

### ISSUE THREAD

**Issue by Shannon212** [CGCookie/retopoflow#339]
http://prntscr.com/err4km

I've been running into the same problem, I have had to resort to manually retopo for now,

In Polypen tool mode, when I try to connect my verts up, it will at random break my Blender UI, causing everything to go black.

Running Blender 2.78, and done a clean install of the addon.

**Comment by vxlcoder** [comment]
@Shannon212 thank you for your issue.  your link does not work.  can you repost it?

**Comment by Shannon212** [comment]
@vxlcoder try this link http://prntscr.com/err4km

**Comment by vxlcoder** [comment]
@Shannon212  thanks for the screenshot.  I have a few questions.

- What does the model look like prior to PolyPen breaking?
- Does it happen only on this model, or every model, or some of the models?
- When PolyPen breaks, does it report an error?
- Are you using Windows, OSX, or Linux?
- Do you know how to run Blender from the console/terminal?  If you can, please do that, and then copy-paste into here anything that is written to the console/terminal around the time PolyPen breaks.

Thanks!

**Comment by dmitsuki** [comment]
I'm not that person, but here is a screenshot. 

![screenshot 2017-05-06 11 19 53](https://cloud.githubusercontent.com/assets/1768438/25774960/9e963540-324e-11e7-88d8-d86b33fb2e8a.png)


And this is what the console says. 

Traceback (most recent call last):
  File "C:\Users\DMitsuki\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoflow-master\modaloperator.py", line 172, in draw_callback_postpixel
    self.handle_exception()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polypen has been removed
Traceback (most recent call last):
  File "C:\Users\DMitsuki\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoflow-master\modaloperator.py", line 170, in draw_callback_postpixel
    self.draw_postpixel(context)
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polypen has been removed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\DMitsuki\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoflow-master\modaloperator.py", line 172, in draw_callback_postpixel
    self.handle_exception()
  File "C:\Program Files\Blender Foundation\Blender\2.78\scripts\modules\bpy_types.py", line 601, in __getattribute__
    properties = StructRNA.path_resolve(self, "properties")
ReferenceError: StructRNA of type CGC_Polypen has been removed


Not, that the console just repeats this error thousands of times, and was doing so before everything crashed to this state. 


Now, if on that black screen I exit polypen mode, and scroll over everything, I begin to get UI features to restore, so I believe it's crashing the Blender UI and then blender attempts to recover once you exit the mode. 

(The actual thing I ended up clicking was polystrips, which brought me into that mode, and everything began to recover.)

**Comment by vxlcoder** [comment]
Thanks for the update @dmitsuki !  I will take a look.
Does this occur every time you open PolyPen, or just sometimes?

**Comment by dmitsuki** [comment]
It only happens sometimes. It actually fixes it if you exit polypen and reopen polypen. It hasn't happened to me today so I don't want to give false info, but I believe it generally happens after an error is thrown. (I could be wrong there.)

**Comment by vxlcoder** [comment]
You're right about the error.  We tried making the tools catch and handle errors gracefully, but those every-once-in-a-while errors that get by without being caught are usually very hard to debug and they also cause most of the problems!
Is the error you reported above one of the first errors you see in the terminal?

**Comment by dmitsuki** [comment]
Both fortunately and unfortunately, today I have not had any errors using Polypen, so I couldn't tell you. The next time it happens I'll be sure to dump the entire console to a txt.

**Comment by vxlcoder** [comment]
That would be very helpful, at least the very first of it up to the `ReferenceError: StructRNA of type CGC_Polypen has been removed` line.

**Comment by carter2422** [comment]
@dmitsuki @Shannon212  did this ever happen to you again?

**Comment by dmitsuki** [comment]
Hi. Unfortunately, almost all my contract work recently has been in 2D, so I have not had a chance to use and document this. I feel like I remember during May when it happened if I was careful with the pen somehow and kept switching modes and didn't do any extreme lines it wouldn't break, so I did that to finish my work with no errors. 

If when I use 3D again it happens I will be sure to document it.

**Comment by Herosnack** [comment]
![capture d ecran 2017-07-19 a 12 07 55](https://user-images.githubusercontent.com/29092380/28362158-b7f22b4a-6c7b-11e7-9fa6-b321ee40d717.png)
![capture d ecran 2017-07-19 a 12 08 19](https://user-images.githubusercontent.com/29092380/28362160-b7f36640-6c7b-11e7-85af-a6d8f90723c5.png)

I got that using polypen. 
No error showing before the crash

Running 2.78 on OSX

**Comment by carter2422** [comment]
I'm happy to say that this is no longer an issue in v2.0.0 so far as we're aware. Closing.
