### ISSUE TITLE
random error causes polypen to delete retopoflow meshing

### ISSUE THREAD

**Issue by dionyroxys** [CGCookie/retopoflow#341]
EXCEPTION(<class'AssertionError>):
          C;\Users\prker family\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoflow-master\op_polypen\polypen_modal.py
000 0911:handle_action_seledge() assert bme in self.selected_bmedges
001 0797:handle_action()return self.handle_action_selege(context, eventd)
002 0393:modal_wait() return self.handle_action(context, eventd)
         C;\Users\prker family\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\retopoflow-master\op_polypen\modaloperator.py
003 0245:modal_main() nmode = self.sfm['wait'](context, eventd)
004 0300:modal() nmode = self.sfm[self.sfm_mode]context, eventd)

^legit made my retopoflow mesh dissapear, please fix

**Comment by carter2422** [comment]
This is an obscure bug that we've run into several times @dionyroxys. Luckily @vxlcoder has tentatively fixed the core issue during the 2.0 rewrite. 

Stay tuned for news on 2.0 very soon. 

I'm going to go ahead and close this, simply because it no longer applies in 2.0, unless you've got something else to add @vxlcoder?

**Comment by carter2422** [comment]
Hey @dionyroxys, we just had another issue similar to this reported, #345, which ended up being due to the object being very, very small. Do you by chance know what the size of your object was?

**Comment by dionyroxys** [comment]
It is within 2 blender floor grid units , sorry I don't really know more

**Comment by carter2422** [comment]
No problem, thanks.

**Comment by carter2422** [comment]
This has been resolved in 2.0.
