### ISSUE TITLE
Polypen breaks the header 

### ISSUE THREAD

**Issue by Herosnack** [CGCookie/retopoflow#348]
![capture d ecran 2017-07-19 a 11 20 18](https://user-images.githubusercontent.com/29092380/28361285-a27c1346-6c78-11e7-99d1-f24e44b2d5d2.png)

I can't remember the last thing I did with polypen,but then edition stops and the header goes blank and it's impossible to change mode or get rid of the panel. I tried to maximize by right clicking on the header but then Blender crashes. 

I am running 2.78 on a mac.

**Comment by carter2422** [comment]
Sorry about missing this @Herosnack. Has this ever happened since?

We're working on v2.0 right now, which will no longer use the header for helper text, thus this will no longer be an issue. 

I'm going to close but if it happens again please do let us know.
