### ISSUE TITLE
Polystrips on thin areas often flip to the wrong side

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#35]
We've talked about this one before, and so far as I know there's no good solution at the moment but it's something we should kind in mind to investigate.

On thin models there's often a problem with polystrips flipping to the opposite side of the mesh from that which it's drawn on. This can be really troublesome for certain models.

**Comment by patmo141** [comment]
can i get a picture/blend example of this

**Comment by carter2422** [comment]
Trying to repo this again but I can't...

**Comment by carter2422** [comment]
Never mind, just repo'd this. 

http://cl.ly/dR0y

Try on this model: https://www.dropbox.com/s/f4avuss4pdlrogw/thin-surface.blend?dl=0

**Comment by vxlcoder** [comment]
unfortunately, this will be a limitation for the foreseeable future.   maybe we can implement a "smarter" version that requires more computation?  we need a way to filter out parts of the mesh during snapping (only snap to faces that "face" a particular direction)

**Comment by patmo141** [comment]
this is a function of the fitting right of the bezier, then re-snapping?  I think I can improve it using the initial sketch info

**Comment by vxlcoder** [comment]
as soon as the strip is manipulated, though, you cannot use the sketch info anymore.  we could test the 2d surface distance (not 3d euclidean) between inner verts of strip, but that would only inform us of bad things happening.  this problem *could* get improved by not snapping the two internal bezier control points to the surface (would require doing screen-space selection, though)

**Comment by patmo141** [comment]
yeah, my idea would be easy to implement for the initial sketch, but you are right, manipulation would be very difficult.

**Comment by carter2422** [comment]
is this ready for testing @vxlcoder?

**Comment by carter2422** [comment]
@vxlcoder tested and confirmed! Closing.
