### ISSUE TITLE
Bring back Insert knife-like functionality for Polypen

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#355]
We need to bring back the knife functionality from 1.x that allows for inserting vertices into existing edges, including connecting vertices through faces.

Here's 1.x in action: https://cl.ly/m1Be

This works by CTRL+Clicking onto an edge. If a vertex is selected prior to inserting then the new vert will be connected to the selection.

**Comment by vxlcoder** [comment]
Note: if a vertex is selected prior to inserting, and that selected vertex and the hovered edge are parts of the same face, the common face needs to be split into two faces.

**Comment by vxlcoder** [comment]
solved!
