### ISSUE TITLE
Relax/Tweak: option to not affect non-manifold vertices

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#359]
Don't allow tweaks to create non-manifold faces or to pull away from the symmetry line when symmetry is enabled.

**Comment by carter2422** [comment]
Is this intended to prevent the problem with Relax causing overlaps to worsen?

**Comment by vxlcoder** [comment]
that, and to keep vertices at symmetry plane

**Comment by vxlcoder** [comment]
done. closing
