### ISSUE TITLE
Keymaps should be created as a Modal Keymap

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#36]
The hard-coded keymaps are really troublesome right now, particularly for selection. They aren't flexible and are easily missed if we forget to update the header.

According to @ideasman42, it should be possible to define an actual modal keymap in Python, like this:
![screen shot 2015-01-03 at 8 22 13 pm](https://cloud.githubusercontent.com/assets/1648631/5604512/3bdd2292-9386-11e4-892f-4e32c0f0b77f.png)

**Comment by vxlcoder** [comment]
keeping around for v2.0+epsilon

**Comment by carter2422** [comment]
No longer relevant and covered by #718
