### ISSUE TITLE
Polypen crashes, hides my mesh, undoes newly added faces

### ISSUE THREAD

**Issue by cornflaky** [CGCookie/retopoflow#367]
![retopoflow](https://user-images.githubusercontent.com/32924241/31759758-28e420e0-b4fe-11e7-8604-058d85e32ff4.PNG)

This issue occurs whenever faces are overlapping over each other in 3D view, like when I'm doing the nose and ears.

After it crashes, polypen hides my mesh and it undoes the new faces I've added. I would have to exit out of polypen, go back to object mode, go back into edit mode, unhide my mesh, activate polypen again without its changes, and press ctrl + z to return the newly added faces that would not show up after unhiding it.

**Comment by carter2422** [comment]
Sorry about this @cornflaky. This should already be resolved in the upcoming 2.0 release (which is a complete rewrite). 

If this is preventing you from completing a project we can try and look at it but otherwise we'll hold for 2.0. We're aiming for a beta release in a few weeks.

**Comment by jfranmatheu** [comment]
Closing issue due to prolonged inactivity. It seems to be resolved in later versions.
