### ISSUE TITLE
X symmetry contours crash with Suzanne

### ISSUE THREAD

**Issue by mathieu-bourdin** [CGCookie/retopoflow#371]
RetopoFlow 2.0.0 crashes on contours with X symetry in following case :

Steps to reproduce, or see [this screencast](https://github.com/CGCookie/retopoflow/files/1432698/contours_symmetry_crash.zip):

- Start blender (factory default scene with a cube, lamp and camera)
- Delete the cube, add Suzanne (a.k.a "Monkey")
- Deselect all
- Enter RetopoFlow by clicking Contours
- Activate X Symmetry in Options panel
- Control + LMB drag for an horizontal contour around Suzanne's jaw.
- Boom

For some reason it does not crash when doing the same steps on a torus or a cube.
This bug seems to be "Suzanne related" somehow.
Suzanne is made of 3 pieces (eyes and head) maybe this bug is related to this ? (unless it isn't :)

Cheers, keep up the good work.

--------------------------------------------------------------------------------
Details
--------------------------------------------------------------------------------
This happens on branch release/2.0.0 (commit a5a37b5c9dfa1ccab51b95ce1915f1e026b21dee)

Stacktrace :
```
EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_contours_ops.py
000 0198:new_cut() p = c0 + (c1 - c0) * (dist / d)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
001 0073:wrapper() ret = fn(*args, **kwargs)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_contours_ops.py
002 0023:line() self.new_cut(ray, plane, walk=False, check_hit=xy01)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget_line.py
003 0017:modal_line() if self.line_callback: self.line_callback()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget.py
004 0175:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
005 0474:modal_main() if self.rfwidget.modal():
006 0423:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blend
[contours_symmetry_crash.mkv.zip](https://github.com/CGCookie/retopoflow/files/1432686/contours_symmetry_crash.mkv.zip)
er/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py
007 0505:framework_modal() ret = self.rfctx.modal(context, event) or {}

EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_contours_ops.py
000 0198:new_cut() p = c0 + (c1 - c0) * (dist / d)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
001 0073:wrapper() ret = fn(*args, **kwargs)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_contours_ops.py
002 0023:line() self.new_cut(ray, plane, walk=False, check_hit=xy01)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget_line.py
003 0017:modal_line() if self.line_callback: self.line_callback()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget.py
004 0175:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
005 0474:modal_main() if self.rfwidget.modal():
006 0423:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py
007 0505:framework_modal() ret = self.rfctx.modal(context, event) or {}
```

**Comment by vxlcoder** [comment]
Thanks @mathieu-bourdin for the bug report!
I'm not certain why there are duplicate verts in the list (have only seen it happen on Suzanne!), but commit 5cd62bd _should_ fix the issue.  I will have to investigate this further at a later time.
If you could confirm the fix works, I'll close the issue.
Thanks, again!

**Comment by mathieu-bourdin** [comment]
Thanks @vxlcoder for the quick fix. Your commit actually fixes the issue, yay !
The reason of the duplicate verts is plain simple, Suzanne has two of them. See here :
![suzanne_duplicate_vertices](https://user-images.githubusercontent.com/25270691/32269596-2ddac096-bef3-11e7-878f-e3f804d65834.png)

**Comment by vxlcoder** [comment]
interesting...
