### ISSUE TITLE
Polystrips sharp turn crash

### ISSUE THREAD

**Issue by mathieu-bourdin** [CGCookie/retopoflow#372]
Drawing a polystrip with an angle throws an exception.
No symmetry was used in this test : [polystrips_sharpturn.mkv.zip](https://github.com/CGCookie/retopoflow/files/1435258/polystrips_sharpturn.mkv.zip)

This kind of path :
![0129](https://user-images.githubusercontent.com/25270691/32290774-5ccf5a36-bf3b-11e7-987f-84f27b060281.png)

This happens with 5cd62bd7384fb9fa37c8ba04d3ee049758106521 which is (as of today) almost identical to release/2.0.0 and unrelated to issue #371.

Kind regards.

Stacktrace:
```
EXCEPTION (<class 'ValueError'>): vert_splice(...): vert arguments match
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmesh_wrapper.py
000 0318:merge() vert_splice(verts1[i1], verts0[i0])
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_polystrips_ops.py
001 0221:merge_faces() bmf0.merge(bmf1)
002 0234:stroke() merge_faces()
003 0239:stroke() raise e
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
004 0073:wrapper() ret = fn(*args, **kwargs)
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget_brushstroke.py
005 0026:modal_stroke() if self.stroke_callback: self.stroke_callback()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfwidget.py
006 0175:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
007 0474:modal_main() if self.rfwidget.modal():
008 0423:modal() nmode = self.FSM[self.mode]()
         /home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py
009 0505:framework_modal() ret = self.rfctx.modal(context, event) or {}
```

**Comment by vxlcoder** [comment]
Thanks again for the bug report, @mathieu-bourdin!
I have a temporary fix for it (pushed to branch `release/2.0.0`) that detects and skips the crashing condition.  I need to rethink how some of PS strokes will work, but at least RF should not crash if you do this again.
I'm closing the issue, but please let me know if you have any other problems!
