### ISSUE TITLE
Unassigned var with PolyPen

### ISSUE THREAD

**Issue by mathieu-bourdin** [CGCookie/retopoflow#373]
I have no clue about this one, except that I was using the PolyPen.
![unasigned_var](https://user-images.githubusercontent.com/25270691/32391345-f66d887e-c0d1-11e7-8545-d1b1cc01767c.png)

On branch release/2.0.0, currently at commit 528322a904c0b978c03012576f62d04ca32cc975.

As a dev I like text stacktrace better so here you go:
```
EXCEPTION (<class 'UnboundLocalError'>): local variable 'bmv1' referenced before assignment
/home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_polypen.py
000 0252:modal_insert() xy = self.rfcontext.Point_to_Point2D(bmv1.co)
/home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
001 0073:wrapper() ret = fn(*args, **kwargs)
002 0093:modal() nmode = self.FSM[self.mode]()
/home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
003 0476:modal_main() self.tool.modal()
004 0423:modal() nmode = self.FSM[self.mode]()
/home/mathieu/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py
005 0505:framework_modal() ret = self.rfctx.modal(context, event) or {}
```
By the way, I've noticed that stacktraces are logged twice in the console.
Cheers.

**Comment by vxlcoder** [comment]
Hmm.  Did you happen to change the keymap for `insert` or `insert alt0` (in `rfcontext_actions.py`)?  Were you using SHIFT+LMB, CTRL+LMB, or something else?
Thanks!

**Comment by mathieu-bourdin** [comment]
I did not change a single byte in source code :)
When in PolyPen mode I use only RMB to select edge or vertex, then Ctrl+LMB to build quad(s).
I *think* the exception was raised when I Ctrl+LMBed  to close a quad (not sure though).
I don't know if that matters but I have caps lock remapped to left Ctrl at OS level. (Linux Mint by the way)

**Comment by carter2422** [comment]
@vxlcoder I believe we can probably close this since the `b280` rewrite?

**Comment by jlampel** [comment]
Closing out since a lot has changed in this area. If you have this issue again please let us know!
