### ISSUE TITLE
1.3.2 keeps locking up Blender

### ISSUE THREAD

**Issue by NickMe3** [CGCookie/retopoflow#376]
I installed through the zip, but cannot initialize it.

Tried a manual install with the same result.

**Comment by vxlcoder** [comment]
Will take a look at it!

**Comment by vxlcoder** [comment]
Thanks for reporting the issue, @NickMe3!  I am having troubles reproducing your problem, so here a few starter questions to try to help me see what's happening.  Which version of Blender are you using?  Can you try opening Blender from console / terminal to see if any useful information is printed there?

**Comment by NickMe3** [comment]
I am using 2.79. I cannot get to the consol because Blender Locks up, then I have to restart and if anything was there it is gone.

**Comment by JosephCatrambone** [comment]
I think I have a fix for this here: https://github.com/CGCookie/retopoflow/pull/387
