### ISSUE TITLE
Polypen: dissolving edge should leave vertices intact 

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#378]
Dissolving this selection should not remove the vertices.

Before:
![screen shot 2017-11-24 at 1 09 28 pm](https://user-images.githubusercontent.com/1648631/33221913-d777879c-d118-11e7-8ec4-000c13c87f4e.png)

After:
![screen shot 2017-11-24 at 1 09 32 pm](https://user-images.githubusercontent.com/1648631/33221919-e6a00514-d118-11e7-9348-b2091f782733.png)

Desired:
![screen shot 2017-11-24 at 1 09 43 pm](https://user-images.githubusercontent.com/1648631/33221925-eeb26fd0-d118-11e7-8ef7-561f20d07b12.png)

**Comment by vxlcoder** [comment]
added ability to dissolve different types in commit 6d7b192 as a fix.
