### ISSUE TITLE
Polystrips: cannot adjust segments when end face is a junction

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#379]
If the last face in a strip is part of a junction then you cannot adjust the segments. This is a really bad (but understandable) restriction.

Ideally the strip would simply ignore the junction face and adjust segments on the remainder.

![screen shot 2017-11-24 at 1 07 50 pm](https://user-images.githubusercontent.com/1648631/33221963-399a8686-d119-11e7-9040-a31b280f709f.png)
enhance

**Comment by vxlcoder** [comment]
note: this would be fixed when issue #380 is fixed.

**Comment by vxlcoder** [comment]
fixed!
