### ISSUE TITLE
Relax: Unhandled exception caught

### ISSUE THREAD

**Issue by TvoyBatek** [CGCookie/retopoflow#382]
When using the "Relax" tool gives an error: 
![blender_2017-11-29_12-12-29](https://user-images.githubusercontent.com/8208165/33367073-b1c28302-d506-11e7-94a7-ec3c908378dc.png)

Attached file with error. This project also gives an error if you press the "Snap All Vertex"

[Test_01.zip](https://github.com/CGCookie/retopoflow/files/1513124/Test_01.zip)

**Comment by TvoyBatek** [comment]
![blender_2017-11-29_13-18-44](https://user-images.githubusercontent.com/8208165/33367417-f8177d16-d507-11e7-93d1-eee02f2dd739.png)

**Comment by TvoyBatek** [comment]
If i press the "Snap All Vertex"

![blender_2017-11-29_13-21-12](https://user-images.githubusercontent.com/8208165/33367557-74b620de-d508-11e7-9a1f-29fcf6858784.png)

**Comment by vxlcoder** [comment]
Thanks for the report and the .blend file, @TvoyBatek!

I'm looking into it right now.  It seems that vertex[2] is located at (NaN, NaN, NaN), which is very strange.

**Comment by vxlcoder** [comment]
@TvoyBatek, if you could, please try pulling the latest commit to see if that works.

I did notice that using Relax of the mesh you supplied acts very strangely.  Also I noticed that the visualization is off due to the clip start and end settings (3d view > properties panel > view > clip).  I will work on these issues soon.

**Comment by TvoyBatek** [comment]
@vxlcoder, thank you! Problem solved.

The problem with the clip appeared recently, I will not say when, but it happened not so long ago.

**Comment by vxlcoder** [comment]
Great!  Closing this issue, and will continue to look at clipping and relax.
