### ISSUE TITLE
Polystrips: increase / decrease count don't work 

### ISSUE THREAD

**Issue by TvoyBatek** [CGCookie/retopoflow#386]
After the last update, the increase / decrease tool gives an error. 

![blender_2017-12-02_09-45-12](https://user-images.githubusercontent.com/8208165/33512279-71496ea2-d746-11e7-94ba-2b531b3a30dd.png)

It happens in any project

**Comment by vxlcoder** [comment]
Hmmm. Will take a look at it

**Comment by vxlcoder** [comment]
RF shouldn't crash here now.  Thanks for the report, @TvoyBatek!  Your reports are definitely making RF a better product!
