### ISSUE TITLE
PP (and other tools): pressing delete should bring up options similar to Blender Edit Mode

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#389]
right now, there is no (direct) way to delete an edge or face without also deleting the vertices.  workaround for edge: create a vert in middle of edge, then delete newly created vert.

**Comment by carter2422** [comment]
Per [Slack discussion](https://cl.ly/pir3) we're going to explore moving all delete/dissolve functions to a menu on <kbd>X</kbd>, mimicking Edit Mode, including the available options.

**Comment by vxlcoder** [comment]
done!

**Comment by carter2422** [comment]
Giggity
