### ISSUE TITLE
Contours: improve cutting

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#392]
Cutting a strip reconnects in strange ways

![before](https://user-images.githubusercontent.com/3790699/34274311-04ef2790-e666-11e7-8a6b-b176dd0ce014.png)

![after](https://user-images.githubusercontent.com/3790699/34274319-0e674302-e666-11e7-9a96-23dffbed1ec8.png)

**Comment by patmo141** [comment]
In contour classes.py (current master, not v2)  there is a function called "align_to_other" that attempts to assess the direction of the adjacent loops (clockwise/anti-clockwise) and then tries to pick the connectivity which minimizes the total ed he length or maximizes perpendicular-ness of the edges.  I can't quite remember.  It looks like the new cut gets aligned to the upstream loop but the downstream loop is not being re-aligned to the new cut.  If you translate the cut...does it fix it?

**Comment by vxlcoder** [comment]
thanks, @patmo141!  i'll take a look at that fn.

btw, fun fact: i've rewritten all of the code for v2!  i don't suggest doing that normally, but the framework for v2 was too different to simply port.  so all the nice, polished, well-performing code that you've written is replaced with a mad-dash version.

**Comment by patmo141** [comment]
I figured you might have.  I recall tackling these kinds of bugs.  "Polished" is a generous term for some of the old contours code :)

**Comment by vxlcoder** [comment]
solved with commit 9d4bc79!
