### ISSUE TITLE
mirror edge viz does not show if target is scaled

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#402]
seems to work fine if target is rotated, but scaling target makes mirror edge visualization disappear.

source scaling seems to have no effect.  also, face viz works fine with scaled target.

**Comment by vxlcoder** [comment]
example:
![no mirror viz](https://user-images.githubusercontent.com/3790699/36548733-10410700-17bf-11e8-8b09-6c0c534e6f4b.gif)

**Comment by carter2422** [comment]
Confirmed bug here.

**Comment by carter2422** [comment]
This is fixed in the `b280` branch!
