### ISSUE TITLE
PolyPen: Unhandled exception caught

### ISSUE THREAD

**Issue by TvoyBatek** [CGCookie/retopoflow#404]
If I try to merge these points:

![2](https://user-images.githubusercontent.com/8208165/34552983-54c6c7b8-f13e-11e7-9e11-50cea34b4a08.png)

I get the error:

![retopoflow_screenshot](https://user-images.githubusercontent.com/8208165/34552997-6f2af3d6-f13e-11e7-935f-74ed4cc54696.png)

Attached file with error. 

[Test_01.zip](https://github.com/CGCookie/retopoflow/files/1602638/Test_01.zip)

**Comment by vxlcoder** [comment]
will take a look.  thanks, @TvoyBatek!

**Comment by vxlcoder** [comment]
finally got around to fixing this @TvoyBatek.  let me know if you have any other problems.

also, thanks for the useful reports!  reports with test files, screenshots, expected results, and actual results make fixing these problems _way_ easier!

**Comment by TvoyBatek** [comment]
Thanks @vxlcoder! Of course, I will report all the problems. Where can I submit proposals?

**Comment by vxlcoder** [comment]
At this point, @TvoyBatek, we don't have an official way to submit proposals for new features or feature changes (not necessarily bugs).  For the time being, perhaps you can submit via the GitHub issue tracker, maybe with a "proposal:" prefix.  Will look into this.
