### ISSUE TITLE
Zero division error when profiling

### ISSUE THREAD

**Issue by plachenko** [CGCookie/retopoflow#409]
https://github.com/CGCookie/retopoflow/blob/release/2.0.0/lib/classes/profiler/profiler.py#L172

this causes a

>  ZeroDivisionError: float division by zero

 which forces a nasty crash when enabling advanced profiling options. Deletes mesh and stops retopoflow from being usable. Even after restarting blender, uninstalling the addon and reinstalling it you get an error and can't recover. Was working off of https://github.com/CGCookie/retopoflow/tree/d72b14339a2efc2f00e2af5e22967f70c9ea119e

this is the exact error

> Traceback (most recent call last):
>   File "C:\Users\Denny\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-d72b14339a2efc2f00e2af5e22967f70c9ea119e\rfmode\rfmode.py", line 146, in modal
>     return self.framework_modal(context, event)
>   File "C:\Users\Denny\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-d72b14339a2efc2f00e2af5e22967f70c9ea119e\rfmode\rfmode.py", line 541, in framework_modal
>     profiler.printfile()
>   File "C:\Users\Denny\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-d72b14339a2efc2f00e2af5e22967f70c9ea119e\lib\classes\profiler\profiler.py", line 207, in printfile
>     fps = totcount/tottime
> ZeroDivisionError: float division by zero
> 
> location: <unknown location>:-1

**Comment by plachenko** [comment]
Also note that I was using that version because I couldn't seem to find retopoflow in the addons panel when installing from the latest versions but I suppose that's a different issue all together.

**Comment by vxlcoder** [comment]
thanks for the report, @plachenko!

commit 9365af9 _should_ fix that problem (cannot reproduce it here, but now that line won't divide by 0)

as for the other issue (RF not in addons panel), can you start another issue and provide details?  if you can, please start Blender from the terminal to see if anything important is printed there.  Thanks!

**Comment by plachenko** [comment]
Thanks for the update @vxlcoder just FYI this line should cause a similar issue (I noticed it from my naive attempts to get it working again).

https://github.com/CGCookie/retopoflow/blob/release/2.0.0/lib/classes/profiler/profiler.py#L207

I'll make a separate issue for the addons panel soon.

**Comment by vxlcoder** [comment]
great catch @plachenko.  fixed that too.

**Comment by plachenko** [comment]
Also I'm going to leave this here because I suppose the second thing I mentioned isn't really an issue. 

What was happening is I was downloading a zip of the release/2.0.0 branch HEAD and it wouldn't show up in the addons when installing. Then I noticed that if you specify any commit then download a zip those work just fine. A head scratcher, but not sure what the fix for this would be. 

Also cloning the repo and using the head of release/2.0.0 in the addons directory works just fine too. So all good. 

Good work, this is shaping up nicely! Hoping to use this in my sculpting workflow soon
