### ISSUE TITLE
Retopo Mesh not showing anymore...

### ISSUE THREAD

**Issue by Elowan** [CGCookie/retopoflow#412]
hi there,

I got some retopo-mesh done, by using contours and polypen. Now, after switching to another blender theme, it seems my retopo´d mesh is not visible anymore... I still can see faces and lines, but only when hovering above it, when in polypen mode. Basically, I only see the original high poly mesh, but not the retopo´d one.

There were issues like this reported, but the solution was "just to hold on" to release of V2.0, which would be within "weeks".. this was on Oct. 17, which is already another 3 month ago....

small edit: Dont get this wrong! The mesh ist still there and visible - but you just cant see the "overlay", when trying to work on it with the retopoflow tools. Working on it with blender standard tools is still ok.

If I use contours, mesh overlay is working - but polypen seems to be broken;  when choosing polypen-tool, I just get the green highlights, when hovering above faces/lines/verts, but the "overall mesh" is not shown.

![1m](https://user-images.githubusercontent.com/16538920/35388184-07b89046-01d3-11e8-8635-f700bbea8b75.PNG)

When leaving retopo-tool, the retopo´d mesh is there (blue):

![2m](https://user-images.githubusercontent.com/16538920/35388186-07cd157a-01d3-11e8-8a3a-1b869bdef3d6.PNG)

edit 2: ok- the problem seems to be "blend file specific" - I´ve made a fresh new file and retopo-mesh-overlay shows, like normal. hmmmm -

edit 3: man, seems like other objects within the "faulty belndfile" still work - so it´s an error, that is just with that one object...
kind regards

**Comment by Elowan** [comment]
Ok - I´ve found a workaround: I exported all meshes as obj and re-imported in a new blend-file. Polypen now works, like it should!

**Comment by Elowan** [comment]
me again - I could reproduce this error: it seems to occur, when you delete verts/lines/faces, when in polypen - mode. I deleted some  lines (edges) and the Viewport/retopomesh is not updating... when leaving the tool (enter), the changes were there (on the ret mesh) BUT after this, the issue is back (see above)

**Comment by Elowan** [comment]
hey,

this is not blend-file specific - the thing is, if you go in and edit (delete) some geo and maybe do this not carefully enough (like having some verts invisble leftovers or such things) - then the issue arises.

so maybe "strange configuration mesh"  could be the troublemaker.

anywho, where is 2.0 - saw the video, looks awesome and if this is going to work, you guys provide us with a tool, better than topogun or all standard tools, like in Modo, Max, etc...

kind regards

**Comment by vxlcoder** [comment]
I'm still unable to reproduce this error.  By "blend-file specific" I meant that the bug persists across saving/reloading the blend file, or it may have to do with the specific source mesh or settings stored in the blend file.  Could you upload a blend file where the bug persists?  I'd really like to nail this thing :)

Thanks on 2.0 comments!  We're working hard on it!  Sadly, we ran into a few OSX-specific issues that are extremely hard to track down.  We want to put out a stable version that matches or supersedes the current version, which means matching all of the original features (and there are many in 1.3!).  We'll keep everyone up-to-date once we have a stable, working beta ready for testing.

**Comment by Elowan** [comment]
To be honest, I did not dare to save the project, so I can´t tell, if this would have solved the issue...

Just exported, exit blender without save, new file, import and saved under the previous file name.
If I should have this issu again, I will make a copy and post again.

Chances are good, because tomorrow I am going to work on this project, again ;)

**Comment by Elowan** [comment]
Ok, please try this:

make a face (4 verts), then make another 3 verts (triangle) over the previously created 4-vert face. then delete a face and see, if your "retopo-mesh-overlay" still works. I got this issue again, because I was not able to see, if topopen did draw somwthing or not (clipping into object), so I accidently did some kind of "double geometry"

**Comment by Elowan** [comment]
Ok, FYI: I got this issu once again. Saving the blendfile an re-open it does not solv this! 

![1m](https://user-images.githubusercontent.com/16538920/35435448-0e640822-028b-11e8-970d-ddab6f972673.PNG)
![2m](https://user-images.githubusercontent.com/16538920/35435449-0e79d788-028b-11e8-99ac-c1d8907c3bfe.PNG)

[HD-retopoed_bug.zip](https://github.com/CGCookie/retopoflow/files/1667400/HD-retopoed_bug.zip)

**Comment by Elowan** [comment]
Oh, I forgot:

to get rid of this issue, I went into edit-mode, deleted the edge and the mesh-overlay starts working once again :)

**Comment by vxlcoder** [comment]
Thanks for the file, @Elowan!
I've tried to replicate this issue, but I'm still having problems.  In fact, when I open your file, everything seems to work just fine without needing to "fix" anything!
![image](https://user-images.githubusercontent.com/3790699/35487822-17e4787c-044e-11e8-85cd-85c2044ddbd5.png)

This leads me to believe that it's a system/driver difference that manifests itself as a bug on your machine but not on any of mine.

Can you report the following for me?

Blender version, including build number and build settings (64b or 32b, if applicable).  A screenshot of the splash would suffice.
Operating system info
Graphics card you're using, and the drivers for said card (ex: nvidia card with nvidia drivers, intel gfx chip with intel drivers, etc.)
opengl version (ex: 3.0 mesa 17.0.7)

thanks!

**Comment by Elowan** [comment]
Ok, after shutdown/restarting my PC, I was downloading the uploaded file and opened it in blender and I still got this issue. I am on 2.76b (2015-11-03) Windows 7 Pro 64bit with Nvidia Quattro K620, driver version 375.63 DX 11.0

**Comment by jfranmatheu** [comment]
Closing issue due to prolonged inactivity. If the issue persists in later versions, please feel free to reopen it. Thank you!
