### ISSUE TITLE
Geometry: allow artist to Hide selection 

### ISSUE THREAD

**Issue by Elowan** [CGCookie/retopoflow#413]
hi there,

I wonder, if this function is missing or not: when I try to retopo some small pieces (like bones of fingers/hand) that are really close to each other, I assign Vertex groups for masking things.

But if I start the polypen tool, the "mesh overlay" (the blue stuff) still shows, which comes into my way, when retopo. Is there a way to just hide faces, when in topo-mode? If not, I may suggest this to be implemented ;)

Kind regards

![1m](https://user-images.githubusercontent.com/16538920/35433240-f93295fc-0282-11e8-95a3-72ac92d23405.PNG)

![2m](https://user-images.githubusercontent.com/16538920/35433343-67baa1cc-0283-11e8-8c7d-5b1eed5a1bda.PNG)

**Comment by carter2422** [comment]
Thanks for the suggestion @Elowan. We don't have a good solution for this yet, but I agree that it needs to happen in some form or another.

We'll keep it in mind!

**Comment by Elowan** [comment]
great, good to hear :)

**Comment by jlampel** [comment]
The latest update added the ability to hide and unhide parts of the mesh with H and Alt+H. Closing out!
