### ISSUE TITLE
Add a License to project root

### ISSUE THREAD

**Issue by dali99** [CGCookie/retopoflow#417]
It wasn't entirely clear what license the project was under, some files are gpl3 while other files have no license declarations.

This is pretty confusing, but fixing this needs the authors and respective copyright holders of those source files to agree and license the non-gpl source files under GPLv2+ or GPLv3

This can easily be safeguarded in the future by adding a LICENSE file to the project root, defining the entire project as GPLv3

Obligatory I am not a lawyer btw, dont take this as legal advice or anything. But I figured the incomplete GPLing was just a slip up

**Comment by vxlcoder** [comment]
Thanks for the report, @dali99!

I _thought_ I had gone through and added the appropriate license info to the top of each file, but seems that I missed a couple of files.  I have also added a blanket `LICENSE` file to the root.   (under `release/2.0.0` branch so far... will be merged to `master` soon)

Note for future reference: https://www.gnu.org/licenses/gpl-faq.en.html#NoticeInSourceFile

Closing.
