### ISSUE TITLE
memory leak

### ISSUE THREAD

**Issue by JackOfShadow** [CGCookie/retopoflow#418]
Hi, Retopoflow 2.0. 
If I close Blender2.79 Win7x64 I get console message "Error: Not freed memory blocks: 12, total unfreed memory 0.000702 MB"
There is no message if Retopoflow is disabled before quiting.

**Comment by vxlcoder** [comment]
Thanks for the report, @JackOfShadow!

We store quite a number of things in Python's "global" space (cached bmeshes, options/settings, instances of tools, etc.).  The report from Blender upon quitting is simply stating that this memory is not cleaned up by RF itself, but that Python/Blender had to free it.  However, although Python/Blender reports this as an "Error", this is not an indication that there is a memory leak.  Unless you create new target meshes over and over again, no additional allocation is happening that isn't automatically garbage collected by Python at some point.  Even the the undo stack is limited to storing only the last 100 modifications.

We could try to detect when Blender is quitting and free all the memory ourselves, but that would not change the performance of RF or Blender in any significant way.

Please let us know if you find any other issues!

Closing.
