### ISSUE TITLE
Patches in 2.x worse then 1.x

### ISSUE THREAD

**Issue by OnlyIAmSorda** [CGCookie/retopoflow#419]
In 1.x verson Shif+F shortcut automaticly create surface independently of edges count, but in 2.x it must have that edges count of two line was  same. I think it is not normal.

**Comment by carter2422** [comment]
@OnlyIAmSorda patches have been completely rebuilt and redesigned from the ground up. The version in 2.0 is still very rudimentary, though, and will be substantially improved.

Closing since this isn't a bug.

**Comment by Elowan** [comment]
hmmm - is 2.0 avail rigth now?

**Comment by carter2422** [comment]
Not quite. We're working on finishing up the beta right now. You can download it here from Github but otherwise has not yet been released.
