### ISSUE TITLE
Add a Face Loop selection tool

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#42]
Allow user to select a faceloop with **ALT+SELECTMOUSE**:

![screen shot 2015-01-04 at 9 52 10 pm](https://cloud.githubusercontent.com/assets/1648631/5609076/f5bf7e46-945b-11e4-8b51-4dd47375218a.png)

**Comment by carter2422** [comment]
This would be a good thing to add in 2.0.0 now that we have direct face selection working.

**Comment by patmo141** [comment]
RF Loop cut has a nice face loop algo if I remember correctly

**Comment by carter2422** [comment]
@vxlcoder this is actually still applicable to v2 Polystrips.

**Comment by vxlcoder** [comment]
done!

**Comment by carter2422** [comment]
Very nice!
