### ISSUE TITLE
Loop slide and PS Handle Scale transforms should be relative to geometry, not left/right movement

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#423]
Loop Slide and Scale currently use left and right mouse movement to adjust the amount. This is not at all intuitive, mostly because it behaves very differently than Blender master. 

Input transforms like this should use them mouse location relative to the geometry, irrelative of mouse direction.

**Comment by vxlcoder** [comment]
similar to #406

**Comment by vxlcoder** [comment]
fixed!

**Comment by carter2422** [comment]
Yesssss!
