### ISSUE TITLE
Add Edgeloop and Faceloop selection methods to relevant tools

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#425]
Many tools use loop selection frequently. To make this easier on the user we should map CTRL+SHIFT+SELECT to loop selection, with the edge/face differentiation being dependent on which tool is active. 

Edgeloops:
- Loop Tool
- Patches
- Contours

Faceloops:
- Polystrips

**Comment by carter2422** [comment]
We may want to instead simply make all selection tools universal, such that they're absolutely consistent and allows the user to select whatever they want, even if it's not appropriate for the chosen tool. 

This would mirror Blender behavior a bit more and perhaps yield an easier learning curve?

**Comment by vxlcoder** [comment]
this is done!  closing :)
