### ISSUE TITLE
Face dissolve doesn't appear to work

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#427]
When trying to dissolve a face in Polypen nothing happens.

Here's the face I'm attempting to dissolve with CTRL+SHIFt+X: 
![screen shot 2018-02-22 at 10 42 57 am](https://user-images.githubusercontent.com/1648631/36551426-2a7068b6-17bd-11e8-9d75-6b595164a787.png)

Here's what I expect to happen:
![screen shot 2018-02-22 at 10 44 01 am](https://user-images.githubusercontent.com/1648631/36551496-4f9c152c-17bd-11e8-88b4-a73c5b911014.png)

Perhaps I'm misunderstanding how Dissolve Faces should work?

**Comment by vxlcoder** [comment]
dissolve verts/edges/faces are bmesh operations, and they don't do what you have here.  this is how you'd use dissolve faces.

![dissolve faces](https://user-images.githubusercontent.com/3790699/36555877-4ea5bb14-17d1-11e8-9abe-0ac45e2e33f0.gif)

what you have here is delete face only, which would be handled in issue #389

**Comment by carter2422** [comment]
Ah ha! That makes more sense.
