### ISSUE TITLE
Unmerged vertices in symmetry mode

### ISSUE THREAD

**Issue by JackOfShadow** [CGCookie/retopoflow#430]
RetopoFlow 2.
Contours. I get some unmerged verices if Symmetry mode is on.
![unmerged](https://user-images.githubusercontent.com/10739109/36663567-0f7ca478-1af3-11e8-805c-4284ad0cf6c0.png)

**Comment by vxlcoder** [comment]
Thanks for the report, @JackOfShadow.  I will take a look into it.

Note to self: there have been some lingering issues with symmetry+snapping, and this might be part of that list.  Time to start in on those issues!

**Comment by vxlcoder** [comment]
this should now be fixed!  re-open if you still have problems.  Thanks!
