### ISSUE TITLE
Unable to run Retopoflow 2

### ISSUE THREAD

**Issue by JackOfShadow** [CGCookie/retopoflow#432]
Sorry, it's me again.
 I can't run Retopoflow 2 ( Latest commit dbd2d83 ) on the one of my computers. 
Console output - [log.txt](https://github.com/CGCookie/retopoflow/files/1761597/log.txt)
The same Blender version and the same computer - Retopoflow test merge 1.3.2 ( Latest commit 67df869 ) works fine.

**Comment by vxlcoder** [comment]
That's really strange!  @JackOfShadow, can you tell me you machine specs?  Especially graphics card and graphics driver.  I'm curious if the graphics driver reports via error channel even when no errors occurred.

I apologize for the troubles thus far.  We'll get you up and running as soon as possible.  Thanks!

**Comment by JackOfShadow** [comment]
graphic card - ATI Radeon HD 3400 series.
I've tested "Rf commit 6bb93cb" - it runs. But after pressing Contours or Polystrip I get flood of messages - [rf-380.txt](https://github.com/CGCookie/retopoflow/files/1766599/rf-380.txt). That flood stops after Esc pressing.
And there is Retopoflow test merge 1.3.2 commit 67df869 log - [rf-test-merge-1.3.2.txt](https://github.com/CGCookie/retopoflow/files/1766620/rf-test-merge-1.3.2.txt)

**Comment by JackOfShadow** [comment]
full system information was generated by  Blender - [system-info.txt](https://github.com/CGCookie/retopoflow/files/1774113/system-info.txt)

**Comment by vxlcoder** [comment]
@JackOfShadow Thanks again for the report and the useful logs!

I've worked in a temporary fix for you.  I'll need to make this test more robust, but I *think* it can wait for now.  If you would, please test the latest commit to `release/2.0.0` to see if you're now able to use RF.

Thanks!

**Comment by carter2422** [comment]
Did you get a chance to test RetopoFlow 2.0.0 beta 2 @JackOfShadow?

I'm closing this since we haven't heard anything. If you're still having trouble please re-open the issue.
