### ISSUE TITLE
Contours Unhandled Exception

### ISSUE THREAD

**Issue by colorofblack** [CGCookie/retopoflow#433]
Hey, 
just quickly trying out the current 2.0 version, I wanted to create some mesh with the contours tool. 
First Retopoflow says the mesh is too large (unclear error message...as it isn't large in scale..just maybe in polydensity because it is sculpted..though I thought that's what retopoflow is made for :D) 
When using contours it first worked great, but when I try to cut over certain areas (for example before the leg) it gives me the following error:

![blender_2018-02-27_13-25-57](https://user-images.githubusercontent.com/12233896/36730363-7271b76a-1bc7-11e8-9946-b3302d9c45ca.png)
Hope this helps. 

Cheers 
Daniel

**Comment by vxlcoder** [comment]
Thanks for the report, @colorofblack.

The note about the source mesh being large is just a note to let you know that RF may pause a bit when starting the first time.  It's not an error report.  And, yes, it is based on the poly count, not the scale.

As for Contours exception, it seems that your source mesh is more tessellated than the test models I have worked with.  I will work on this fixed as soon as I can.

In the mean time, you can workaround this issue by using the decimate modifier on the source to reduce the poly count.

**Comment by colorofblack** [comment]
Ah thanks. 
Would be great if the warning could be more clear (as I first checked the scale of my object ;) )

Yes my source mesh is pretty dense and I used your proposal with the decimate modifier already. Though it has some limits as I start to lose details in some areas. 
Therefor great if you can fix it for the release version! 

Thanks for the response, looks really promising already!

**Comment by vxlcoder** [comment]
This issue *should* be fixed, but needs further testing.  I rewrote that section of code, so there may be a chance that a different bug was introduced.

**Comment by carter2422** [comment]
Seemingly fixed! @colorofblack if you still get this error please re-open.
