### ISSUE TITLE
Retopoflow does not run on Linux system

### ISSUE THREAD

**Issue by yvesbodson** [CGCookie/retopoflow#435]
I get error msg when trying to select an object (see msg) and a warning that script files are missing (see msg)
![img_20180309_093617](https://user-images.githubusercontent.com/354200/37198292-22588ba0-237e-11e8-9813-1753c8ec3d11.jpg)
![img_20180309_093559](https://user-images.githubusercontent.com/354200/37198304-27fd2f52-237e-11e8-82a6-5ec1c6ef601c.jpg)
![retopo missing script files](https://user-images.githubusercontent.com/354200/37198309-2b422c94-237e-11e8-943c-08e278556634.png)

**Comment by vxlcoder** [comment]
Thanks for the report, @yvesbodson.

Do all of the other tools work properly (if you don't use the eyedropper)?

**Comment by yvesbodson** [comment]
Hello JonWell I have solved the issue by deleting completely Blender and the .config .  Then reinstalled it and it worked.  From what I could see there was a second install of Retopoflow in the config folder ..  I  have no idea as how that happened..  but it works great now.  Thanks  for your reply.

    On Friday, March 9, 2018, 1:55:57 PM GMT+1, Jon Denning <notifications@github.com> wrote:  
 
 
Thanks for the report, @yvesbodson.

Do all of the other tools work properly (if you don't use the eyedropper)?

**Comment by vxlcoder** [comment]
Great to hear!  closing.
