### ISSUE TITLE
Moving snapped geometry past the symmetry line pushes it below the surface

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#442]
~Any geometry that touches the X/Y symmetry line cannot be selected.~

~Geometry on the Z symmetry line works fine.~

Moving snapped geometry past the symmetry line pushes it below the surface, making it unselectable. 

Can we prevent geo from going under the surface on transform?

**Comment by carter2422** [comment]
Nevermind, this was because some geometry was under the surface somehow. Snapping to surface solved it.

Good to know!

**Comment by carter2422** [comment]
FYI, I figured out how it got below the surface. Watch this: https://cl.ly/qWhS

**Comment by vxlcoder** [comment]
same as #370 and #368. related to #430

**Comment by vxlcoder** [comment]
this should be fixed now!  re-open if you still have problems!
