### ISSUE TITLE
RetopoFlow 1.3 also showing installed with 2.0 beta

### ISSUE THREAD

**Issue by 3DNut** [CGCookie/retopoflow#444]
RetopoFlow 1.3 also showing installed with 2.0 beta. It seems to me like it should be removed. I thought I had some kind of double install, only to find out after downloading it from Blender Market and manually installing it that RetopoFlow 1.3 is still showing in the Retopology tab and says it needs to be updated, along with RetopoFlow 2.0.

**Comment by vxlcoder** [comment]
@3DNut, thanks for the report, but this is the intended effect for now. Since RF 2 if still beta, we wanted artists to continue to have access to RF 1.3 tools in case there was a major issue with the new version. You can collapse the RF 1.3 section in the tool shelf. Future release will remove 1.3.

**Comment by 3DNut** [comment]
Okay. If that is the intended effect, maybe you should let people know about that so they don't waste time like I did trying to fix something that isn't actually broken ; ) Thanks.

**Comment by vxlcoder** [comment]
Yeah, we could have presented that better, but we were excited to get it out quickly so we can improve it further!
Thanks for the report!
