### ISSUE TITLE
Tools aren't working, such as PolyStrips

### ISSUE THREAD

**Issue by 3DNut** [CGCookie/retopoflow#449]
I am sure this will end up being user error, but if that is the case it is because I don't understand how to set up the scene. LMB dragging with PolyStrips does not draw a polystrip for me.

You can download a video of me walking through this issue here:
https://d.pr/v/haZsh0
Please let me know what I am doing wrong or if it is a legitimate bug (which I can't imagine it is) how I can help.

**Comment by vxlcoder** [comment]
The new default insert action is CTRL+LMB. More details under tool help (F2). Let us know if you still have problems!

**Comment by carter2422** [comment]
Does it work correctly for you with CTRL+LMB Drag @3DNut?

**Comment by 3DNut** [comment]
Sorry for the confusion. Yes, I was working from old info and should have read the current info better. Thanks for being responsive to my issue.
