### ISSUE TITLE
error and crash !!

### ISSUE THREAD

**Issue by Voguart** [CGCookie/retopoflow#457]
my computer configuration is as follows;
windows 7 family primium 64
intel (r) core (tm) i7-4790cpu
blender 2.79.4
![error](https://user-images.githubusercontent.com/23705454/38293662-ade24336-37e8-11e8-96d7-77dad487a9f3.JPG)

**Comment by vxlcoder** [comment]
Hi @Voguart!  I am closing this issue for now, but feel free to comment if you're continuing to run into this bug.  Thanks for the report!
