### ISSUE TITLE
Recursion Depth Exceeded On UI Hover

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#459]
Retopoflow occasionally crashes when hovering over UI elements. I haven't been able to find an exact set of steps beyond using any tool and then hovering over another with tooltips enabled, but it seems to happen fairly often with this file: https://www.dropbox.com/s/em5xt3ser6r5yh4/goblin_sculpt.blend?dl=0

![2018-04-06 08_14_11-blender_ c__users_jonathan_desktop_goblin_sculpt blend](https://user-images.githubusercontent.com/12982300/38429734-1afdb428-3974-11e8-9d5e-7b6cc0f2ce64.png)

**Comment by vxlcoder** [comment]
I believe this _should_ be fixed.  It is similar to issue #471.
