### ISSUE TITLE
PolyStrips: Scale Strip Unexpected Behavior

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#462]
When using Ctrl+Shift and Click+Dragging on any inner control point, the strip jumps around in odd ways. My best guess is that it might be scaling along the normals instead of scaling regularly, but I can't quite tell. 

Expected behavior: 
![36549847-ce5a74cc-17c1-11e8-8b9f-df559bd69b4c](https://user-images.githubusercontent.com/12982300/38521155-b6c69c6c-3bf9-11e8-9ce6-78f5d79cd9a8.gif)

What I see:
![7sidksqbae](https://user-images.githubusercontent.com/12982300/38521158-b8d840a0-3bf9-11e8-9104-5fae22b7a3c5.gif)

**Comment by vxlcoder** [comment]
this does not appear to be happening anymore.

closing for now
