### ISSUE TITLE
Retopo Vers 2 - Nothing Draws

### ISSUE THREAD

**Issue by wildspidee** [CGCookie/retopoflow#463]
The RetopoFlow doesn't appear to be working at all. When you draw with the tools, nothing appears. My computer is working (I can hear it), but nothing appears on the screen. I tried opening and closing RF and also Blender to no avail.

I finally recorded it, just in case this is useful. I've attached the Blender file I'm using too. The items I'm working on are on layer 4. You'll see five flat planes, all separate objects. I was working on the topmost one.

Here are my specs:
Blender 2.79
RF 2.0 Updated today
Windows 10 Pro 16299.309
32 GB RAM
i7 3.5GHZ
GeForce GTX 1070 Driver 391.24

I thought these meshes would be very easy to do, since they are so simple. Perhaps I'm just doing something incorrectly. Thank you for your time.

[Testing.zip](https://github.com/CGCookie/retopoflow/files/1896296/Testing.zip)

**Comment by carter2422** [comment]
Hey @wildspidee, drawing is done with CTRL+LMB now.

**Comment by wildspidee** [comment]
I'm an idiot. I watched all the 1.0 vids before purchasing and was going with those instructions. That's a major difference. Thanks for the quick response.

**Comment by carter2422** [comment]
No problem at all!
