### ISSUE TITLE
Can't scroll through options with a stylus, requires mouse scrollwheel

### ISSUE THREAD

**Issue by 3DNut** [CGCookie/retopoflow#464]
I expanded the advanced options but couldn't see all of the contents. There is no scroll bar that I can find and no hotkey that I can find to move up and down through the options with the stylus. I had to go back to the mouse and use the scroll wheel to see the option contents.

**Comment by carter2422** [comment]
Good catch @3DNut. We'll look into adding stylus support in some way or another.

**Comment by vxlcoder** [comment]
@3DNut, you can scroll the options using MMB drag, similar to drag-scrolling the panels in Blender.  Is there an equivalent form of MMB drag using stylus?  I'll add keyboard shortcuts for scrolling, too.

Thanks!

**Comment by vxlcoder** [comment]
@3DNut, with the latest commit (5c94d53), you _should_ be able to scroll the options panel using page up and page down.  Please let me know if this works, or if there are issues.  Thanks!

**Comment by carter2422** [comment]
Works here!

@vxlcoder should we add Up/Down arrow scroll support too? Most Mac users won't know that FN+Up/Down is PageUp/PageDown.

**Comment by vxlcoder** [comment]
added, @carter2422!

closing this issue.
