### ISSUE TITLE
Unable to use Retopoflow 2.0.0.1

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#466]
Hi all of you !

First I apologize for my bad english... I'm a frenchie...
I have an issue with RetopoFlow (RF), in it's 2.0.0.1 version that I obtained as an update from 1.3.2 version.
Even with Blender 2.78c nor 2.79, the viewport isn't correctly modified, I still see the T,N, ... panels, as shown with this screen capture :

![capture](https://user-images.githubusercontent.com/38527057/38990100-49604e42-43d9-11e8-8a67-99ff73044af1.JPG)

So, I don't have the same result than we can see in this video (at time = 4') :
[https://www.youtube.com/watch?v=mA3h87OXRwI](url)

Is it because of it ? I can't at all use Contours or PolyStrips, the tools don't trace anything...

If it is useful, I attach the .txt file I obtain with Blender, for all informations about my configuration...

Thanks a lot for any help !

ILYA

[system-info.txt](https://github.com/CGCookie/retopoflow/files/1927997/system-info.txt)

**Comment by carter2422** [comment]
Hi there,

Per the Quick Start the drawing hotkey is now CTRL+LMB Drag. 

Cheers!

**Comment by vxlcoder** [comment]
Thanks for the report, @ilyafr37.

The T and N panels will hide if you have Region Overlap option set in Blender Options (User Prefs > System tab > Region Overlap).  As for the other areas (Datablocks, Timeline, etc.), you can click the Maximize Area button in the RF options window to toggle the 3D View to take up the entire window (or press CTRL+UP).

To address the inability to use Contours or PolyStrips, RF 2.0 uses different shortcuts from RF 1.3.  You'll need to use CTRL+LMB to start a contour cut or sketch a curve.

There are more details under the General Help (F1) and Tool Help (F2).

**Comment by ilyafr37** [comment]
Hi !

Thanks a lot Carter 2422 and Vxlcoder, with your explanations all is working well ! Sorry, in the Tool Help that I read it, though... I didn't notice the information about CTRL + LMB instead of LMB !
OK for the Overlap option, never I would have find it !

ILYA

**Comment by vxlcoder** [comment]
Glad to hear you're up and running!
