### ISSUE TITLE
PolyStrips: Error when trying to delete specific face

### ISSUE THREAD

**Issue by Lucatiel641** [CGCookie/retopoflow#467]
I was trying to delete this face and then the error happened.
![delete_face](https://user-images.githubusercontent.com/25983521/39021220-3e7e7df0-4406-11e8-810b-6413829f3c21.png)

-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-          C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfmesh_wrapper.py
- 000 0125:co() self.bmelem.co = co
-          C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext_target.py
- 001 0342:set2D_vert() vert.co = xyz
-          C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool_polystrips.py
- 002 0417:modal_move() set2D_vert(bmv, xy + delta)
-          C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0103:modal() nmode = self.FSM[self.mode]()
- 005 0107:modal() raise e
-          C:\Users\david\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 006 0472:modal_main() self.tool.modal()
- 007 0396:modal() nmode = self.FSM[self.mode]()

**Comment by vxlcoder** [comment]
Thanks for the report, @Lucatiel641!

Will take a look at this soon.

**Comment by vxlcoder** [comment]
I still have not been able to reproduce this issue, @Lucatiel641, but I did add a check to prevent the crash from happening again.
I'm closing this issue for now.  Please reopen if you run into it again.  Thanks!
