### ISSUE TITLE
Unable to start RetopoFlow 2.0

### ISSUE THREAD

**Issue by bc-griffin** [CGCookie/retopoflow#468]
Hi,

I am unable to initialize RetopoFlow 2.0 beta. I am also presented with a WARNING stating that my Target Polycount is high and that RetopoFlow may load slowly. Please see screenshot below...

[https://drive.google.com/file/d/1Aa6JClhhAWLeZewbcsZit66-pNZ6U-Ye/view?usp=sharing](url)

My system specs are as follows...

[https://drive.google.com/file/d/1vqMlEVgGqhA8otDdv4YDkgK1dXwCRcgC/view?usp=sharing](url)

Thank you.

Bennie

**Comment by bc-griffin** [comment]
Not to worry. Sorted out problem.

Thanks again.

Bennie

**Comment by carter2422** [comment]
Let us know if you run into any other issues!
