### ISSUE TITLE
Symmetry line is completely off.

### ISSUE THREAD

**Issue by 3DNut** [CGCookie/retopoflow#469]
I have a model that I have mirrored and all the transforms have been applied, yet when I turn symmetry on the edge is clear over to the right. Contact me and I will give you my client's file that is having the issue as I am not comfortable spreading it to the four winds.

**Comment by vxlcoder** [comment]
Thanks for the report, @3DNut.

Is this happening in RF 2.0 beta?

Are you able to reproduce this bug on Suzanne?

This might be similar to #402.  Try applying scale transform on the target mesh.

**Comment by ilyafr37** [comment]
Hi !

May I propose an explanation ?... if I well understood the issue : sorry, I'm a frenchie and english isn't my native language...
 I think this problem of bad symmetry position occurs when the 3D cursor is not just at the same place than the geometrical center of the source object.

Here are two screen captures showing what happen : 

1 - geometrical center of source object with red arrow, 3D cursor with blue arrow : 

![badcursorposition](https://user-images.githubusercontent.com/38527057/39940906-234274b8-555b-11e8-99c3-e4dd808eb024.JPG)

2 - result : symmetry separation line placed at the 3D cursor position : 

![symmetryxtooright](https://user-images.githubusercontent.com/38527057/39941012-7b3ba52c-555b-11e8-9f1e-f67767fec6f9.JPG)

ILYA

**Comment by vxlcoder** [comment]
@ilyafr37 is correct.  Here are more details:

Similar to Blender's approach to adding new objects, a new target mesh will have it's origin at the 3D cursor location, regardless of the source's center.  (also, mirror modifier duplicates geometry over the origin of the modified object)  Also, the symmetry visualization is based on the origin of the target mesh, not the source mesh.  Therefore, it may look like the symmetry is wrong, but it's actually correct behavior.

Does that better explain your situation @3DNut?

**Comment by vxlcoder** [comment]
Closing this issue for now.
