### ISSUE TITLE
Crash when hovering Tools panel

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#471]
Hi all of you !

With my poor english ability...  When I use a tool, hovering the Tools floating panel sometimes (not always...) occure a crash, as shown with this screen capture :

![errormessage](https://user-images.githubusercontent.com/38527057/39600928-9485ee2a-4f20-11e8-9986-b76d48f0088a.JPG)

If that can help to analyse, here is the log file with a veryyyyy long list of lines : 

[RetopoFlow_log.log](https://github.com/CGCookie/retopoflow/files/1972546/RetopoFlow_log.log)

Thanks in advance for an explanation and, I hope so, a solution **(*)** !

Cheers,

ILYA

**(*)** Edit : not a solution, just an idea... Instead of hovering the panel to remember me the shortcut of a tool with the tooltip, with the risk of the crash I mentionned above, it would be easier to notify the shortcut with the name of the tool. 
For example : Polystrips (W) instead of Polystrips... I want Polystrips ? Easy : it is W, no need of hovering  !
I tried to modify the script in this goal, alas without success. I could only change the title of the panel, as shown here : 

![changelabel](https://user-images.githubusercontent.com/38527057/39630154-c9ef41c2-4fae-11e8-870c-13fa8975c93c.JPG)

... but it is not the best way to help a bad memory, mine !

May I ask you to know what to modifiy in what script, in order to change the tools'label of the panel ?

**Comment by vxlcoder** [comment]
@ilyafr37 I believe this latest commit should fix it, although I haven't been able to reproduce the bug.  Thanks!

**Comment by ilyafr37** [comment]
Thanks Vxlcoder !

I modifiy the .py file based on your commit, hope that wil help ! 

ILYA

**Comment by ilyafr37** [comment]
Good !

Vxlcoder, I just tried a lot and a lot of hovering on the tools  floating panel, without having any bug as I had !

Thanks !

ILYA
