### ISSUE TITLE
Abnormal display with this graphics card

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#474]
Hi all of you,

With a specific graphic card, I obtain an abnormal display of, for example, a strip made with Polystrips.
Here are two screen captures of : 

1 - the graphic card I use : 

![graphiccard](https://user-images.githubusercontent.com/38527057/39939991-2959bb2a-5558-11e8-8d4d-ad95604e604a.JPG)

2 - what I obtain with Polystrips : 

![screendisplay](https://user-images.githubusercontent.com/38527057/39940031-40d663d4-5558-11e8-815a-be21a60ad1e4.JPG)

Is there a solution to avoid this bad display ?

Thanks a lot for any help I need !

ILYA

**Comment by vxlcoder** [comment]
Thanks @ilyafr37 for the report!

By bad display, are you referring to the missing handles on the selected strip?  That seems like a strange bug, since one handle is already showing.

Have you tried changing to orthographic or perspective projection (NUM5)?

Do any of the other tools have display glitches like this?

**Comment by ilyafr37** [comment]
Hi Vxlcoder !

Yes, you said right : the default in displaying is that one, missing handles of the selected strip... and, yes, it's the same in all point of view like orthographic or perspective...
With the other tools there is not any default in the display... such a strange bug !

ILYA

**Comment by vxlcoder** [comment]
Is this problem similar to the other issue you posted about the handles, Issue #489?

Have you been able to replicate this bug?

**Comment by ilyafr37** [comment]
Hi Vxlcoder,

I anwer to your question : " _Is this problem similar to the other issue you posted about the handles, Issue #489?_ "

Of course, I can't generalize based on what I see with 2 PC, but : 

1 - the problem of abnormal display for a strip made with Polystrips : missing handles on the selected strip, subject of this issue, appears only on one of the two PC, that one which uses AMD Radeon R9 200 Series. This bad display is permanent on this PC.

2 - this problem isn't similar to the other issue #489, because what I mention in this issue #489 appears on both PC...

I wish that my answer will help you to analyse, I hope so !

ILYA

**Comment by vxlcoder** [comment]
@ilyafr37, when you get a chance, can you see if this is still an issue with the latest version of `release/2.0.0` branch?

**Comment by ilyafr37** [comment]
Hi Vxlcoder !

Sorry, I was on holidays for a long time, so I answer to your question after a very long delay ! 

Yes, I confirm that the "bug"  is still an issue with the 2.0.0 version of RF...

ILYA

**Comment by jlampel** [comment]
There was quite a bit changed in the jump to 3.0. Are you still experiencing this issue? So far we haven't had a similar report, so it's definitely a curious one.

**Comment by ilyafr37** [comment]
> There was quite a bit changed in the jump to 3.0. Are you still experiencing this issue? 
Hi Jlampel,
I should have made a "feedback" on this subject, sorry !
Your question is welcome to remind me of this oversight !
I mention it to you, with version 3.0 of retopoflow, I no longer have this bug !

**Comment by jlampel** [comment]
Awesome, thank you!
