### ISSUE TITLE
Unknown Issue In Retopoflow 2.0

### ISSUE THREAD

**Issue by MannyFanny** [CGCookie/retopoflow#475]
Is there any particular reason _this_ is happening? This is my source object, no retopoflow functions have been applied, and I even decimated the geometry (because of the warning, thinking that was the issue). Nope, it'll only allow me to select the original geometry (move some vertices, but operation is jank). I figure this is me, not knowing what I'm doing or simply unknowledgeable information I have yet learn, and not enabling or disabling a function or two.
![2018-05-11](https://user-images.githubusercontent.com/39206715/39952642-6107d73a-5569-11e8-9985-12e2e27500cf.png)

**Comment by vxlcoder** [comment]
@MannyFanny, it looks like you had the hair selected when you started RF.  Instead, do not select anything, then enter RF.

RF treats the selected and active mesh as the target mesh, and all other visible meshes as source.  By unselecting all objects, RF will create a new mesh (target) and all other visible meshes will be treated as source.

Please let me know if this fixes your problem, or if I missed your question.

Thanks!

**Comment by vxlcoder** [comment]
Also, there are more details under the "Quick Start Guide" button in the tool panel.
![image](https://user-images.githubusercontent.com/3790699/40021040-c755d42c-5791-11e8-8b4f-28d0a6324260.png)

**Comment by vxlcoder** [comment]
closing for now.
