### ISSUE TITLE
Not an issue, but a real wish for RF 2.0.0 !

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#476]
Hi !

A wish, indeed... I would really appreciate if I could modify the label of the buttons in the tools panel, these buttons : 

![toolsmenu](https://user-images.githubusercontent.com/38527057/39957323-7522b31a-55f1-11e8-8db1-851f59a78ad0.JPG)

I tried unsuccessfully to find what script I have to modifiy, and how...
Would you help me in this goal please ? For example, I would prefer seeing "Contours (Q)" instead of "Contours"... just as an help for my memory !

Thanks in advance !

ILYA

**Comment by vxlcoder** [comment]
You're right, @ilyafr37.  I don't have an easy way to change the labels of the tools at the moment.  I started working on that UI feature, but have not yet finished it.  I will let you know as soon as I get it working.  Thanks!

Let us know if you have any other feature requests!

**Comment by ilyafr37** [comment]
Thank you Vxlcoder for considering my request !

ILYA

**Comment by vxlcoder** [comment]
Finally got the code modified in a reasonable way to accomplish this!
![image](https://user-images.githubusercontent.com/3790699/41110257-eecab1b8-6a46-11e8-97ec-2070f4147220.png)

**Comment by ilyafr37** [comment]
Well done, so great !

Thanks a lot Vxlcoder, it's quite what I wished ! 
 I tried a modified code for myself, but it wasn't as good as yours, cause of my bad level in scripting... 

![capture](https://user-images.githubusercontent.com/38527057/41189288-d4e51f50-6bcb-11e8-85f4-35907d63693a.JPG)

Thanks !

ILYA

**Comment by ilyafr37** [comment]
Hi Vxlcoder !

I just finished modifying the 11 files as you detailed them :  

![fileslist](https://user-images.githubusercontent.com/38527057/41199407-a987ab4a-6c91-11e8-8b6f-b7829588614e.JPG)

... but I probably forget an action, because I always have the same "look" for the Tools panel, that one I obtained with some personal minor adjustments of the file rfmode\rfcontext_drawing.py : 

![rfcontext_drawing](https://user-images.githubusercontent.com/38527057/41199482-36ec438c-6c93-11e8-83fc-6780e4a5bc71.JPG)

I guess I have something else to do, maybe about shortcuts ? I think about that because of your comment : " ... added keyboard shortcuts for each tool to label "... but what and where must I modify something in order to obtain the same Tools panel than yours ?

Thanks in advance for this help !

ILYA
