### ISSUE TITLE
Increase the value of FPS in RF 2.0 ?

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#477]
Hi !

I had a surprise : on a PC having a very ordinary graphic card, RF 2.0 works at ~ 100 fps.
On my "current" PC, with this graphic card : 

![graphiccard](https://user-images.githubusercontent.com/38527057/40002881-36e20432-5792-11e8-8be5-f04ba76960c9.JPG)

... I obtain at most 30 fps !

How RF 2.0 define this value, is there any way to increase this value ?

Thanks !

ILYA

**Comment by vxlcoder** [comment]
RF backend will run as fast as the system will allow, up to 120hz.  This is accomplished by using an event timer (`rfmode/rfmode.py:332`).  Each time any event triggers (including the timer above), a redraw is triggered (`rfmode/rfmode.py:557`).  This lets Blender know that it should redraw the 3D View, including the RF plug-in.  So, RF's drawing FPS is dependent on Blender and the system.  The FPS reported is estimated by counting the number of times Blender calls RF's `draw_postpixel` function (`rfmode/rfcontext_drawing.py:129--134').

As for increasing it, I don't have an easy answer.  I tried writing the code to be as efficient as possible, but there are many places that I was not as careful as I could've been.  For example, RF should not have to trigger a redraw every time an event is processed.  Changing this to only redrawing when needed would improve the overall performance, possibly significantly (some of the tools rely on the continuous redraw, though...).  At this time, I'm focusing on show-stopping bugs and missing features.  Soon, I will go back into optimizing.

**Comment by ilyafr37** [comment]
Thanks Vxlcoder for your answer, that help me for a better understanding of the scripts.
I understand that the priority is to treat defaults before carrying out optimization actions !
So, good luck with that job !

ILYA

**Comment by vxlcoder** [comment]
Thanks, @ilyafr37!  Closing this issue, since general optimization is in the plan already.
