### ISSUE TITLE
Just isn't working at all - Landscape retopology

### ISSUE THREAD

**Issue by briligg** [CGCookie/retopoflow#478]
I'm working on retopologizing an accurate model of a particular crater on the Moon. I have several versions of it. I've tried Retopoflow on one that has 15,000 vertices, and one that has 58,000 vertices. In both cases i've scaled the model down from it's actual size, which is about 25 km across, to 2 or 3 meters. Note that the original file from Lunar Reconnaissance Orbiter data had over a million vertices and i've already worked really hard to get it down to this size. Part of that work was with an earlier version of Retopoflow, over a year ago.

Retopoflow  2.0 has given me warnings that the source object's polycount is high and bbox is large. I've tried to get it to do something anyhow as i'm nervous of making the thing any smaller, or removing more vertices (which would also be labor intensive, the thing i'm trying to avoid). But it won't do anything at all. The interface opens, i can see the brush, i choose polystrips and stroke along a part of the crater, and nothing happens. It just crashed when i tried again.

Is this really just too big? I had problems with the previous version, but i could at least get it to work. Is there anything i should try to help it handle the job?

I'm submitting the smallest version of this file in hopes that will help. It's one i've already tried Retopoflow 2, but there doesn't seem to be any data, just an empty mesh. 

[LalandeMaster-Retopo.zip](https://github.com/CGCookie/retopoflow/files/2003053/LalandeMaster-Retopo.zip)

**Comment by carter2422** [comment]
Hey @briligg,

I just tested your model and all appears to work fine after I Applied the scale on the object with CTRL+A. 

Can you try applying the scale and then starting RetopoFlow?

**Comment by briligg** [comment]
Yes, i did notice that after posting, and it's a good point. But for me, applying the scale hasn't made any difference. 

If it works for you, perhaps the issue is my system. The OS is Ubuntu 18.04, just installed. The graphics card is a Geforce GTX 960 and there's 16 GB of memory, so it's not that.

**Comment by briligg** [comment]
I've now tested on another file that just has a low-poly human figure in it, and it still doesn't work. The interface loads but the brushes don't work. I'm going to disable other add-ons i have to see if it fixes it. First up, Verge3D.

**Comment by carter2422** [comment]
To be sure, are you using CTRL+LMB to draw polystrips?

The hotkey has changed in 2.0, which is explained in the Quick Start guide.

**Comment by briligg** [comment]
Ah - no. I had gotten used to the way it worked before. Just didn't occur to me that part would change. 

I'd even opened that tool help section (that's where it is actually, not the Quick Start) and scanned it, but it seemed similar and i felt i already understood how to use that tool.

Then i got into asking and searching online. Alright, i suppose this could have been a lot worse. I was thinking about removing my desktop and individual programs one by one, because i didn't know what to do.

Thanks for your help.
