### ISSUE TITLE
Patches: Assert Error! while selecting edges around a gap, with stray selections and a dangling vertex

### ISSUE THREAD

**Issue by briligg** [CGCookie/retopoflow#481]
I was filling in an area with a patch. There are only gentle curves on the underlying mesh in this area, and the resolution is about the same or maybe less than the retopoflow object. I was using a stylus and tablet to select edges around the gap. I was trying to choose three sides of the gap so it would automatically decide how to place the faces of the patch. As can be seen in the first screenshot, some edges not on the boundary of the empty patch had been selected. The stylus is sensitive and it's hard to move it precisely enough to avoid this, as it's in midair when i do this. Also as seen in the 2nd screenshot, a vertex had gotten created unintentionally at some point, and was overlapping another face and near to another vertex.
![screenshot from 2018-05-16 15 53 13](https://user-images.githubusercontent.com/5508441/40143833-234f8282-5922-11e8-9ca3-92f8b6ae84af.png)
![screenshot from 2018-05-16 16 05 18](https://user-images.githubusercontent.com/5508441/40144098-069a90b8-5923-11e8-9f78-66bad90de348.png)

-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'AssertionError'>): 
-          /home/kim/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_patches.py
- 000 0179:update() assert len(next_edges) == 1
-          /home/kim/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext_target.py
- 001 0464:select() if self.tool: self.tool.update()
-          /home/kim/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_patches.py
- 002 0489:modal_select() self.rfcontext.select(bme, supparts=False, only=False)
-          /home/kim/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
- 003 0103:modal() nmode = self.FSM[self.mode]()
- 004 0107:modal() raise e
-          /home/kim/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
- 005 0472:modal_main() self.tool.modal()
- 006 0396:modal() nmode = self.FSM[self.mode]()

**Comment by vxlcoder** [comment]
thanks for the report @briligg.  will check it out soon!

**Comment by vxlcoder** [comment]
Thanks for the note @briligg!  the latest commit to `release/2.0` _should_ handle that situation (and others that I haven't thought about) more gracefully.

**Comment by carter2422** [comment]
Nicely done @vxlcoder. The graceful ignore seems to work very well in my recreation.
