### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by lucianomunoz** [CGCookie/retopoflow#483]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.4

- EXCEPTION (<class 'UnboundLocalError'>): local variable 'sel_only' referenced before assignment
-          C:\Users\elect\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool_loops.py
- 000 0110:modal_main() if sel_only: self.rfcontext.deselect_all()
-          C:\Users\elect\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 001 0103:modal() nmode = self.FSM[self.mode]()
- 002 0107:modal() raise e
-          C:\Users\elect\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 003 0472:modal_main() self.tool.modal()
- 004 0396:modal() nmode = self.FSM[self.mode]()

**Comment by LeviSchuck** [comment]
Experienced this too, Blender version 2.79.0

**Comment by vxlcoder** [comment]
Thanks for the report!  Will take a look at this tomorrow
