### ISSUE TITLE
Allow edges to be pinned, locking in place during relaxation and tweak

### ISSUE THREAD

**Issue by Tyrannosaurus1234** [CGCookie/retopoflow#486]
It would be very handy to have the ability to mark an edge as pinned when using the Relax tool such that it would stay in place, similar to how boundary edges act when boundary relaxation is turned off. This is fairly important in places like finger joints on hands, where you need to have an edge loop around the joint for the purposes of deformation, and hitting it with the Relax tool has a tendency to move that edge.

**Comment by carter2422** [comment]
This is a very good suggestion @Tyrannosaurus1234! We'll keep it in mind.

**Comment by Sinhouse85** [comment]
I second this!
Also really helpful for intended UV borders.
Not sure how possible it would be, but it would be great if vertices on pinned loops could still be relaxed, but only along the pinned loop, ie edge constraint. that way spacing could be smoothed out without compromising edge placement.

**Comment by jlampel** [comment]
In the last couple versions the ability to mask Tweak and Relax using the selection has been available.
