### ISSUE TITLE
PolyStrips: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by andersrson** [CGCookie/retopoflow#487]
I Created a default cylinder to test on, created a poly strip, selected the first face on the strip and hit x -> delete face.

-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

```
- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
-          /Users/anders/Library/Application Support/Blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmesh_wrapper.py
- 000 0125:co() self.bmelem.co = co
-          /Users/anders/Library/Application Support/Blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext_target.py
- 001 0342:set2D_vert() vert.co = xyz
-          /Users/anders/Library/Application Support/Blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool_polystrips.py
- 002 0417:modal_move() set2D_vert(bmv, xy + delta)
-          /Users/anders/Library/Application Support/Blender/2.79/scripts/addons/RetopoFlow/rfmode/rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0103:modal() nmode = self.FSM[self.mode]()
- 005 0107:modal() raise e
-          /Users/anders/Library/Application Support/Blender/2.79/scripts/addons/RetopoFlow/rfmode/rfcontext.py
- 006 0472:modal_main() self.tool.modal()
- 007 0396:modal() nmode = self.FSM[self.mode]()
```

(updated by vxlcoder for easier reading)

**Comment by andersrson** [comment]
Hi, I haven’t been able to reproduce this after it happened. I can try some more tonight.
I’m pretty sure those were the steps, but I could be mistaken.

Regards, Anders

4 juni 2018 kl. 19:26 skrev Jon Denning <notifications@github.com<mailto:notifications@github.com>>:


Thanks for the report, @andersrson<https://github.com/andersrson>, but I'm having troubles trying to reproduce your bug. Can you please answer the following questions to help us debug this issue?

  *   Are you able to reproduce it easily? Can you post progressive screenshots or a video screencast?
  *   You said that you deleted a face, but the traceback states the exception occurred while trying to move the vertices. Did you do anything else after deleting the face?

Thanks!

**Comment by vxlcoder** [comment]
I'm closing this issue for now, @andersrson.  If you reproduce this, please reopen and post the steps you used.  Thanks!
