### ISSUE TITLE
Visibility of the grey inner control point with Polystrips (RetopoFlow 2.0)

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#489]
Hi !

I experiment some visual difficulties with Polystrips of RetopoFlow 2.0 : 
Due to the relief of the model mesh, the grey inner control point, at the end of the tangenting handle, is sometimes "into" the model mesh, as for example this : 

![perspview](https://user-images.githubusercontent.com/38527057/41082305-21683a50-6a2e-11e8-87e6-a0d6f87db8d2.JPG)

The only way I found to avoid this is choosing a front ortho view (with numeric touch 1), instead of user perspective (with numeric touch 5), as it was with the screen capture above. Here is what I obtain in this case of a front ortho view : 

![frontview](https://user-images.githubusercontent.com/38527057/41082954-3bfd3062-6a30-11e8-81bf-a2db19f8f3c0.JPG)

Is there a better solution to assure that the grey inner control point will always be visible, in every mode of viewing in the 3D view ?

Thanks a lot for an answer !

ILYA

**Comment by vxlcoder** [comment]
Now, you can adjust the alpha values of the handles.  Just know that hidden handles with alpha=100 will show through the mesh entirely!

![ps adjusting alpha](https://user-images.githubusercontent.com/3790699/41112273-820b7840-6a4c-11e8-80e2-82e445c334cc.gif)

**Comment by ilyafr37** [comment]
Hi Vxlcoder !

Thanks for your job, and excuse me ! I sent you an email, just before having taken a alook here, and so I sent this email without knowing that you had posted a commit, which is the best answer at my mail... sorry !

ILYA
