### ISSUE TITLE
The 2.8 Issue

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#490]
As Blender 2.8 gets closer to beta we will most likely need to make some substantial changes to make RetopoFlow compatible. 

This issue is for keeping track of all 2.8 specific changes needed and further discussion.

**Comment by NazzarenoGiannelli** [comment]
Any news on a 2.8 version now that this new version is more stable?

**Comment by zaha** [comment]
With the expected release of Blender 2.8 today, is there a roadmap for RetopoFlow 2's update for Blender 2.8?

**Comment by NazzarenoGiannelli** [comment]
This is the only addon I am missing and that keeps me opening 2.79 that I don't use anymore as main version. Please guys! Your addon is too good and too important to not get a 2.80 update!

**Comment by norphie** [comment]
So, are there any news about 2.8 version?

**Comment by helloimneil** [comment]
Can't wait to use the plugin for 2.8!

**Comment by fiddybux** [comment]
Same here. RTF is the only reason I go back into 2.79! Aitolda, and so did everyone else. 💯

**Comment by Elowan** [comment]
hmmm, still nothing to announce?

#feelsbadman ;) 

come on guys, do it !

**Comment by fiddybux** [comment]
There is always BSurfaces which is a built in retopo add-on.

**Comment by carter2422** [comment]
Thanks for bearing with us everyone! The 2.8 version is still in progress; it’s taken an immense amount of work to rewrite a large part of the codebase for the new API.

**Comment by fiddybux** [comment]
Thanks for the update!

**Comment by Elowan** [comment]
hey, is there any estimate, on how long it would take?

**Comment by vxlcoder** [comment]
Hi all!

We've released an alpha version of RF!  Check you Blender Market inbox for details, or you can check out the `b280` branch on this repo.

There are still a handful of missing features and a performance issue with large meshes, but we're actively working on them.

Hoping to get a beta version out soon.

Thank you for your patience with this process!  This work has taken a very long time, but we are happy with the results.

**Comment by Elowan** [comment]
Sounds great, awesome :)
Really very happy, you guys still care a lot about this fine retopo-tool !

**Comment by vxlcoder** [comment]
Be sure to report any issues you have, so that we can take care of them!

Cheers :)
