### ISSUE TITLE
Patches: Assert Error!

### ISSUE THREAD

**Issue by duke0179** [CGCookie/retopoflow#498]
https://drive.google.com/file/d/1kpGPAzIOF-7Wfopldjyu3RWJideTSVxJ/view?usp=sharing

Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
```
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'AssertionError'>): 
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool_patches.py
- 000 0179:update() assert len(next_edges) == 1
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext_target.py
- 001 0485:select_inner_edge_loop() if self.tool: self.tool.update()
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool_patches.py
- 002 0466:modal_main() self.rfcontext.select_inner_edge_loop(edge, supparts=False, only=sel_only)
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 003 0103:modal() nmode = self.FSM[self.mode]()
- 004 0107:modal() raise e
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 005 0472:modal_main() self.tool.modal()
- 006 0396:modal() nmode = self.FSM[self.mode]()
```
(edited by for readability)

**Comment by duke0179** [comment]
https://drive.google.com/file/d/1kpGPAzIOF-7Wfopldjyu3RWJideTSVxJ/view?usp=sharing
screenshot

**Comment by vxlcoder** [comment]
Thanks for the report, @duke0179!
Will take a look at it soon.

**Comment by vxlcoder** [comment]
I believe this issue is the same as #481, which _should_ be fixed.  If you continue to have this issue after updating, please report the details on the other issue.  Closing for now.  Thank you!
