### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by duke0179** [CGCookie/retopoflow#499]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'StopIteration'>): 
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool_loops.py
- 000 0093:set_next_state() c0,c1 = next((c0,c1) for e,c0,c1 in self.edges_ if e == self.nearest_edge)
- 001 0104:modal_main() self.set_next_state()
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 002 0103:modal() nmode = self.FSM[self.mode]()
- 003 0107:modal() raise e
-          C:\Users\duke0\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 004 0472:modal_main() self.tool.modal()
- 005 0396:modal() nmode = self.FSM[self.mode]()

**Comment by duke0179** [comment]
https://drive.google.com/open?id=1HroMzXR0uhtq5f_-mv8ITH_dxX2UQcqe
screenshot

**Comment by vxlcoder** [comment]
Thanks for the report, @duke0179!
I will take a look at it soon.

**Comment by vxlcoder** [comment]
@duke0179, I've requested access to the screenshot.  Please let me know when I can take a look at it!

**Comment by vxlcoder** [comment]
I've added a line to check for this issue, but it doesn't fix the underlying problem.  I'll revisit this issue when you have granted access to the screenshot.  Also, could you post a .blend file and steps to reproduce the error, @duke0179? Thanks!

**Comment by vxlcoder** [comment]
Thanks for the screenshot, @duke0179.
I'm still not quite certain what the underlying issue is, but I'm fairly certain that the issue shouldn't happen again, so I will close this issue.

If you happen to run into this problem again, please reopen the issue and post the .blend file so we can investigate it further.

Thanks!
