### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by WinExploder** [CGCookie/retopoflow#500]
A comment I left on this video: https://youtu.be/mA3h87OXRwI

[...] I specifically said "forced" because the strip tool doesn't work when applied in any real scenario. It's noticeable in the video as well where you are using very small quads because that is the only thing the tool will allow. Any bigger than that and it starts to fall apart in its usability, I tried it using the free version. As anyone who has experience with retopology knows that the best practice is to keep the quads as big as possible (My impression is that this is the part that you are underestimating immensely). The strip tool is a nice concept but not much more than that. 

And even the basic poly drawing tool isn't even close to the competition in retopology tools. Maya's Quad Draw allows the free placement of points which can then be formed into a poly with Shift-RMB. In comparison, the poly pen requires the user to always select an edge or a vertex before beginning and the inability to plot out the flow by placing points is restricting, overall slower and gives rise to flow errors. 

The tweak tool is quite simply broken, the resizing of the brush doesn't work and the mesh relaxing function is very weak and has bad performance. The only redeeming feature of Retopoflow is the countours tool which is very useful and easy to use. 

Overall I recommend you study other retopology applications such as Quad Draw in Maya or 3DCoat in order to make Retopoflow an actual, production ready alternative. The best way to improve the tool at the moment would be to merge every tool of Retopoflow into one and utilize hotkeys to activate the different functions. When looking at QuadDraw, an industry standard, you'll find that this is exactly how that tool works.﻿

**Comment by carter2422** [comment]
Hi @winexploder, just to be sure, we’re tou using v1.x or the 2.0 beta?

It sounds to me like you were in 1.x, which is being retired after a complete rewrite and extensive upgrade in 2.0.

**Comment by WinExploder** [comment]
I left this comment on a video regarding the Beta, therefore I assume that the feedback is valid.

**Comment by carter2422** [comment]
@WinExploder I didn't mean to imply your feedback wasn't valid; it certainly is. I simply wanted to confirm that you were testing the 2.0beta before going through your feedback, since if it was 1.x then the experience would be very different.

**Comment by WinExploder** [comment]
I used the 1.x version is there a way to obtain the beta version?

**Comment by vxlcoder** [comment]
@WinExploder, if you purchased RF through the Blender Market, you should have access to the beta version of RF 2.0 through your purchases.  We will be releasing a second beta version very soon (~1 day or less!).

If you cloned the repository, checkout the `release/2.0.0` branch.

Since this is an issue that applies to 1.x, I'm closing this issue for now.  Do let us know if you have any issues with 2.0!
