### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by Nit-Pick** [CGCookie/retopoflow#502]
Right, so I'm trying to do more VRChat stuff but this one model is giving me problems. Completely unrelated to the plugin bug (maybe). So this [model](https://www.models-resource.com/pc_computer/overlord/model/24569/):

1. Separate all loose parts until there's nothing except the body

1. Try contouring the arm up to the shoulder.

1. Now try to add a horizontal loop to the arm with the loops tool

You should get this error every time a loop is attempted to be made on the arm.
IF you can see, I added mesh to the seam of the X axis to try to merge with the arm mesh. Just an added detail.

![retopoflow_screenshot](https://user-images.githubusercontent.com/9891501/42242981-75b8773a-7ed5-11e8-8319-c01eed85c435.png)

```
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'TypeError'>): unsupported operand type(s) for -: 'NoneType' and 'NoneType'
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfmesh.py
- 000 0719:nearest2D_bmedge_Point2D() diff = bmv1 - bmv0
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext_target.py
- 001 0156:nearest2D_edge() return self.rftarget.nearest2D_bmedge_Point2D(xy, self.Point_to_Point2D, edges=edges, max_dist=max_dist)
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool_loops.py
- 002 0242:prep_edit() nearest_edge,_ = self.rfcontext.nearest2D_edge(edges=working)
- 003 0145:modal_main() self.prep_edit()
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool.py
- 004 0103:modal() nmode = self.FSM[self.mode]()
- 005 0107:modal() raise e
-          C:\Users\nit_p\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext.py
- 006 0472:modal_main() self.tool.modal()
- 007 0396:modal() nmode = self.FSM[self.mode]()
```
(edited for readability)

**Comment by vxlcoder** [comment]
Thanks for the report, @Nit-Pick.  Will take a look!

**Comment by vxlcoder** [comment]
I believe this issue is similar to issue #501.  @Nit-Pick, could you post a .blend file and steps for reproducing the bug?

**Comment by vxlcoder** [comment]
I'm closing this issue for now.  If you run into it again, please re-open and post the .blend file.  Thanks!
