### ISSUE TITLE
Un-Maximizing area throws a context is incorrect error

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#509]
Un-maximizing the area in RetopoFlow throws a blender API error for `context is incorrect`:
<img width="1129" alt="screen shot 2018-07-10 at 7 20 02 pm" src="https://user-images.githubusercontent.com/1648631/42544296-717b473c-8476-11e8-9beb-3d5e018fa44c.png">

**Comment by vxlcoder** [comment]
fixed by commit 9d87dc8!
