### ISSUE TITLE
Contours with Symmetry doesn't always place right at center

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#513]
When creating Contours that cross the center line the symmetry-line vertex is frequently offset just slightly:
<img width="152" alt="screen shot 2018-07-10 at 7 35 19 pm" src="https://user-images.githubusercontent.com/1648631/42544630-8b9e6642-8478-11e8-8387-737e285b4d71.png">

**Comment by vxlcoder** [comment]
this is related to issue #430, and it should be fixed now!
