### ISSUE TITLE
Bug updating

### ISSUE THREAD

**Issue by yahnatidias** [CGCookie/retopoflow#515]
When I click to update it leaves the tool shelf, and the addon options disappear

**Comment by vxlcoder** [comment]
Thanks for the report, @yahnatidias.
I'll look into this.

**Comment by vxlcoder** [comment]
What version are you upgrading from?

**Comment by yahnatidias** [comment]
From 1.3.2 to the latest, but I also tried the beta 1 and 2 and both behaved in the same way.

**Comment by vxlcoder** [comment]
Thanks.  Are you clicking the `Update now` button from the tool shelf or from user preferences?

**Comment by yahnatidias** [comment]
For me there does not appear an update button on the tool shelf, I tried going in the preferences and clicked to check now for updates.

**Comment by vxlcoder** [comment]
Open the Add-ons tab in your user preferences and see if RetopoFlow is in the list.  It might be there, just unchecked.

**Comment by yahnatidias** [comment]
https://imgur.com/a/IZZMFWY

**Comment by vxlcoder** [comment]
Could you try opening Blender from terminal/console?  If there is an error occurring, RF should print useful info to the terminal.
Thank you for your help and patience on this!

**Comment by vxlcoder** [comment]
I just noticed that RF has installed itself into `~/.config/blender/2.79/scripts/addons/retopoflow-master/`, when it should install to `.../addons/RetopoFlow`.  that might be the issue.
Please still report (copy-paste) what RF dumps into the terminal while I dig into the install folder issue.
Thanks, @yahnatidias!

**Comment by yahnatidias** [comment]
RetopoFlow Options path: /home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/RetopoFlow_options.json
No options file
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/__init__.py", line 49, in <module>
    from .interface import CGCOOKIE_OT_retopoflow2_panel, CGCOOKIE_OT_retopoflow1_panel, CGCOOKIE_OT_retopoflow_menu
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/interface.py", line 28, in <module>
    from .rfmode.rftool import RFTool
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rftool.py", line 42, in <module>
    from .rfwidget import RFWidget_Default
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rfwidget.py", line 35, in <module>
    from .rfwidget_brushstroke import RFWidget_BrushStroke
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rfwidget_brushstroke.py", line 26, in <module>
    from ..common.shaders import brushStrokeShader
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/common/shaders.py", line 23, in <module>
    from ..lib.common_shader import Shader
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/lib/common_shader.py", line 28, in <module>
    from ..ext.bgl_ext import VoidBufValue
  File "/home/yahnatidias/.config/blender/2.79/scripts/addons/retopoflow-master/ext/bgl_ext.py", line 30, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

**Comment by vxlcoder** [comment]
Which version of Blender are you using?  Did you build it yourself?
Normally, the NumPy package is distributed along with Blender, but it seems that it cannot be found.

**Comment by yahnatidias** [comment]
No, I'm not capable of it, I just downloaded it from the internet, I'm going to download another version and try again, on windows it works normally.

**Comment by vxlcoder** [comment]
Also, @yahnatidias, be sure that you're installing RetopoFlow from the .zip file that you get via Blender Market, not from GitHub.  (that's likely why RF installed under the `retopoflow-master` folder instead of `RetopoFlow`)

**Comment by yahnatidias** [comment]
I downloaded a new version of blender and it worked, thank you for the tips :D

**Comment by vxlcoder** [comment]
Glad to help.  Please let us know if you run into any other problems.  Also, consider giving us a rating on Blender Market, and let us know how RF has helped your workflow!

Thanks!
