### ISSUE TITLE
UI: add icons to all the tool shelf buttons

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#516]

**Comment by carter2422** [comment]
Which buttons are you thinking of @vxlcoder? I don't think the Quick Start, Report, or Error log really need icons. I'd be tempted to remove the auto save one too actually; letting icons draw the user's focus to the actual tools.

**Comment by vxlcoder** [comment]
removed them.  i like it better this way.  thoughts?

**Comment by carter2422** [comment]
Agreed. Much cleaner and better focus on the tools.
