### ISSUE TITLE
Patches: allow artist to insert/delete corners

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#520]
In this example, it is difficult to figure out why it is detected as an L-shaped patch (see issue #519).  But even if the artist understands why, adjusting the angle property is not very intuitive.

Instead, the artist should be able to insert/delete corners at will.

![image](https://user-images.githubusercontent.com/3790699/42659788-57b916da-85f7-11e8-8d0c-38be15683931.png)

**Comment by vxlcoder** [comment]
give that a go, @carter2422 !

**Comment by carter2422** [comment]
This makes me very happy and works well :)
