### ISSUE TITLE
Auto scale (normalize) meshes to a fit a 1x1x1 bbox

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#525]
The user should not need to worry about BBox too big / small warnings, which leads to rendering artifacts.  Should auto scale the meshes to fit in a 1x1x1 bbox when entering RF, and then undo the scaling when leaving.

See issue #524 for more details.

**Comment by carter2422** [comment]
How would this work with scale factors other than 1?

**Comment by vxlcoder** [comment]
done!
