### ISSUE TITLE
Patches need segment support when bridging

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#529]
When using the Patch tool for bridging two open loops we need the ability to adjust segments. Here's an example use case: 
![screen shot 2018-07-17 at 3 23 06 pm](https://user-images.githubusercontent.com/1648631/42843330-64e59720-89d5-11e8-9224-a226ec8cb14e.png)

**Comment by vxlcoder** [comment]
done!

**Comment by carter2422** [comment]
Booyah!
