### ISSUE TITLE
Polystrips UI options have indention issues

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#534]
The indention for `Handle Size` (and the sub inner/outer options) is mis-aligned. 

`Handle Size` should align with `Count`, `Scale Falloff`, `Max Strips`, and `Draw Curve`:

<img width="310" alt="image 2018-07-19 at 2 40 23 pm" src="https://user-images.githubusercontent.com/1648631/42966153-debdd6d8-8b61-11e8-91d6-641a51e30d79.png">

**Comment by vxlcoder** [comment]
related to issue #491

**Comment by vxlcoder** [comment]
this is improved (still needs tuning, though)

**Comment by carter2422** [comment]
Much better. Closing
