### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by ghost** [CGCookie/retopoflow#536]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0 beta 2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1050 Ti/PCIe/SSE2, 4.6.0 NVIDIA 388.13, 4.60 NVIDIA


Error Hash: 0a65176110f9148a27dc386e05253a9d


Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMEdge has been removed
- .../rfmode\rfmesh.py
- 000 0717:nearest2D_bmedge_Point2D() bmv0 = Point_to_Point2D(l2w_point(bme.verts[0].co))
- .../rfmode\rfcontext_target.py
- 001 0156:nearest2D_edge() return self.rftarget.nearest2D_bmedge_Point2D(xy, self.Point_to_Point2D, edges=edges, max_dist=max_dist)
- .../rfmode\rftool_polypen.py
- 002 0566:draw_postpixel() e1,d = self.rfcontext.nearest2D_edge(edges=self.vis_edges)
- .../rfmode\rfcontext_drawing.py
- 003 0146:draw_postpixel() self.tool.draw_postpixel()
```

**Comment by vxlcoder** [comment]
Thanks for the report!  Although I haven't been able to reproduce this bug, I've made some changes in the latest commit that should prevent this from happening.  Closing for now, but comment/reopen if you run into it again.
