### ISSUE TITLE
Installation failing on MacOS High Sierra

### ISSUE THREAD

**Issue by robleeper** [CGCookie/retopoflow#537]
Trying to install 1.3.2 and Beta 2 both fail for me.

Blender version 2.79 (date 208-03-22) in MacOS 10.13.6 (17G65) on an iMac 5k, 27", late 2014.

Installing the Add-on from file just generates a message: ﻿
`Modules Installed () from '/Users/xxxxx/Downloads/retopoflow-1.3.2.zip' into '/Users/xxxxx/Library/Application Support/Blender/2.79/scripts/addons'`

The window returns to the Add-on selection pane but RetopoFlow doesn't show. Looking in the addons folder does show that the addon has been copied into place but Blender doesn't recognize it's there.

**Comment by robleeper** [comment]
Hi @carter2422, I've tried restarting Blender to no effect. I wasn't clear enough in my original post, but I am using the `Install from File` option inside Blender when it fails. I've also tried the reverse and pasted the expanded add-on into the scripts folder without effect... I've even gone so far as to completely remove Blender from the system (with all its associated files) and done a fresh install... problem persists. It's weird.

**Comment by carter2422** [comment]
Are you downloading the beta from Blender Market or here on Github? If you're downloading from GitHub then you have to modify the download in order to install it. Github does not compress the add-on in a Blender-compatible method.

**Comment by robleeper** [comment]
It's through GitHub... aaaaaaand yep, that was the issue! I can finally try Retopoflow out!

**Comment by carter2422** [comment]
Good to know!
