### ISSUE TITLE
Allow C fills on Strokes

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#539]
C-Shaped extrusions is really important for Strokes. 

Here's a *very* common scenario where the Stroke tool is a perfect candidate:
![screen shot 2018-07-23 at 11 25 46 am](https://user-images.githubusercontent.com/1648631/43089779-2a6957b8-8e6b-11e8-8474-14da646f0ff5.png)

**Comment by vxlcoder** [comment]
done!

**Comment by carter2422** [comment]
Yay!
