### ISSUE TITLE
Selection dragging too-easily selects perpendicular edges

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#540]
When using Selection dragging with Contours, Polypen, Loops, and Strokes it's much too easy to select perpendicular edges/faces to your drag path. 

Are we able to bias selection towards those elements that're parallel with the mouse stroke? Or perhaps reduce the selection margin while dragging such that the stroke needs to pass over the center 3rd of the edge?

**Comment by carter2422** [comment]
@vxlcoder the new stroke selection branch works in many cases, but fails when selecting areas with tight curves. See this: https://cl.ly/tAEm

It keeps going back over nearby edges and toggling their selection.

**Comment by vxlcoder** [comment]
here is my latest attempt:

when starting selection, the hovered edge is immediately selected. then, as the artist "paints" over the surface, a hovered edge is added _only_ if it neighbors a selected edge and the cursor is at least 25% along the length of the edge toward the unselected vertex.

let me know if that works any better, @carter2422 .

**Comment by carter2422** [comment]
So much better! I'll keep playing with it but I think this solves it nicely.
