### ISSUE TITLE
Error pops up when I try to do anything

### ISSUE THREAD

**Issue by RainbowTiff** [CGCookie/retopoflow#546]
![retopoflow error](https://user-images.githubusercontent.com/41662543/43179786-b6dde096-8fa2-11e8-9d39-0597e87879a2.png)

I am not sure if I am doing something wrong, or if this is a bug, but every time I click on any retopoflow button to attempt to begin retopologize my  asset, I get this same error. I clicked Polystrips and polypen and the same werror came up. It is also telling my that the poly count on my asset is high, but of course it is, that's why I'm retopologizing it... 

Is this a fixable error?

**Comment by RainbowTiff** [comment]
Thank you for the reply!

This is the first time I've used Retopoflow 2.0, I haven't used retopoflow before, I was getting acquainted with re-topology as a concept fist, then when I went to learn about retopoflow, I saw that 2.0 had come out and read that it was far superior, so I figured I'd skip the middleman.

I installed it using this youtube video as a reference: https://www.youtube.com/watch?v=5xqi_uyhQrM

If I update Blender, is that going to mess up my husband's animations he's been working on? if not, I should be able to update it (I didn't know there was a newer version available).

I have been clicking "no" on a pop-up window on my PC for some time that was asking to make changes to the computer, but I don't remember whether it was coming up before I downloaded Retopoflow.

The Retopoflow folder had "read only" checked in properties, I unchecked that and checked for it to apply to all subfolders and files, should that help?
I will also check your provided link to see what I can add up.

Thanks!
-Tiff

**Comment by RainbowTiff** [comment]
I closed and re-opened blender after un-checking those boxes and still got the same error :/

I did use the second method from the video because when I tried the first way, nothing happened. I was getting super frustrated because I know that installing an add-on should just be a few clicks, so I did it the long way and it seemed to work. The tools are there and i have that nifty Retopology tab, but it won't let me do anything.
I am sure that box being checked wasn't doing me any favors, but unfortunately, it doesn't seem to be the only issue.
Did I install it wrong, even though the menu and tools showed up?

**Comment by vxlcoder** [comment]
You might try deleting the RetopoFlow folder from the addon folder, and then reinstalling using the .zip file.  Just to be sure, where are you getting the RF files from?  Are you getting them from Blender Market, or are you downloading a zip from GitHub, or something else?

**Comment by vxlcoder** [comment]
Also, did you install the add-on from a different Windows account, such as from your husband's account?  It could be that the folder is associated to his account and not your's.

**Comment by vxlcoder** [comment]
Also, I'm sorry for your frustration!  We'll get you up and running as quickly as possible!

**Comment by RainbowTiff** [comment]
I downloaded it from Blender market, we share an account. I feel like I probably did mess up when installing it, I couldn't just click through as I assume you're supposed to be able to do.
So, should I try and install it using "install from file" again? it's just that last time, when I clicked on "Retopoflow" it just opened the folder and I didn't know which one thing to click or if I messed something up.
I'm really more of a creator than a techy, so I can be a little dense with these things >.<
I appreciate your help!

**Comment by RainbowTiff** [comment]
OK, so, I went and deleted the file from the add on file like you suggested, then went in to install it from the file. I got this: 
![installing retopoflow](https://user-images.githubusercontent.com/41662543/43243815-5f95da3a-9076-11e8-843b-b4e44507f1bc.PNG)
and I selected the 2.0 version.
it looks like it worked since I have this nifty screen now:
![nifty retopoflow screen](https://user-images.githubusercontent.com/41662543/43243853-861fe6f0-9076-11e8-980b-234c4f8fb0cf.PNG)
but I still don't seem to be able to use the tools, the brushes show up on my mouse, but if I click and drag, nothing happens. This could very well be my own ignorance considering I haven't the slightest idea how to use it, but it seems like I am at least headed in the right direction!
=D

**Comment by vxlcoder** [comment]
It looks like it's working now!  Great job in sleuthing!

The tools use Ctrl+LMB to start most interactions (sketching, brushing, etc.).  Be sure to read the Quick Start Guide (in RetopoFlow panel above the buttons), but also the General Help and Tool Help.

**Comment by RainbowTiff** [comment]
Awesome! So my only issues should be user error from here! xD
Thank you so much!!

**Comment by carter2422** [comment]
Great to hear @RainbowTiff! Let us know if you run into anything else.
