### ISSUE TITLE
Polystrip Handle are drawn HUGE on retina

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#553]
On retina displays the Polystrips handles huuuuge. 
<img width="503" alt="screen shot 2018-07-25 at 10 09 20 pm" src="https://user-images.githubusercontent.com/1648631/43239336-75b422f0-9057-11e8-907a-e4da8a86190d.png">

**Comment by vxlcoder** [comment]
see if commit b78db77 corrects this.

**Comment by carter2422** [comment]
Confirmed!
