### ISSUE TITLE
Smart selection: stop selection at open face boundaries

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#554]
If able we should stop *smart selection* at face boundaries, e.g two-valence verts. Such that this:
<img width="525" alt="screen shot 2018-07-25 at 10 11 08 pm" src="https://user-images.githubusercontent.com/1648631/43239382-a542bdec-9057-11e8-9a59-93f0c5185f28.png">

Instead is this:
<img width="453" alt="screen shot 2018-07-25 at 10 11 27 pm" src="https://user-images.githubusercontent.com/1648631/43239402-b28ffabe-9057-11e8-9ffe-6c3ed7a0a0bc.png">

Or alternatively this:
<img width="526" alt="screen shot 2018-07-25 at 10 11 49 pm" src="https://user-images.githubusercontent.com/1648631/43239417-bcdc01ac-9057-11e8-89f0-19ae84c05c60.png">

**Comment by vxlcoder** [comment]
i feel like the middle option is the best.  it does require more selecting (only if you wanted the loop of the third option), but it's pretty obvious what the selection alg is going to do.

here are my two suggestions:

the hovered edge can be part of 0 faces, 1 face, or 2 faces (not really supporting >2 faces), which categorize the walking algorithm.

for 0 faces, option 1: walk from one edge to the next as long as there is exactly one next edge and it has no faces.
![image](https://user-images.githubusercontent.com/3790699/43279820-1ebc1990-90dd-11e8-8fd3-6a51abe73c15.png)

for 0 faces, option 2: walk from one edge to the next as long as the next edge has no faces and it is the next "straightest" edge (turning left/right the least amount)
![image](https://user-images.githubusercontent.com/3790699/43279896-5504234e-90dd-11e8-8d79-c69bc5fc0f68.png)


for 1 face:
walk from one edge to the adjacent edge which also has one face.  but, the two faces cannot be the same face.  in other words, at each intersection (vertex), it continues if the next edge is not a left (or right) turn, keeping a single face on the same "side".
![image](https://user-images.githubusercontent.com/3790699/43279645-b050de8c-90dc-11e8-8060-53f0e2f450e7.png)


for edge with 2 faces:
walk from one edge to the adjacent edge which also has two faces.  but, no face of one edge can neighbor the face of another edge.  basically, at each intersection (vertex), it continues if the next edge is not a left turn or right turn but there are still 2 faces on either side.
![image](https://user-images.githubusercontent.com/3790699/43279439-f4a68b32-90db-11e8-9145-05f4623c9070.png)


thoughts?

**Comment by vxlcoder** [comment]
in other words, keep walking along edges until it isn't clear which edge is next (running into a vertex with 5 edges, for example), the number of faces changes, or the face switches sides.

**Comment by carter2422** [comment]
Option 1 for 0 faces is exactly what I want!

And both 1 and 2 face scenarios look perfect.

**Comment by vxlcoder** [comment]
ok, try again!

**Comment by carter2422** [comment]
This is working great!
