### ISSUE TITLE
Not able to generate any retopologized mesh ! 

### ISSUE THREAD

**Issue by Mehd6384** [CGCookie/retopoflow#563]
Hello there ! 

I recently bought retopoflow 2.0 and I was really excited to start using it but, surprisingly, I haven't been able to generate any mesh ! When I launch blender and load a HP mesh, I'm able to enter retopology mode, with the gradient background, I can see the brushes and/or the pointer, however, whatever I try, nothing appears. No contour mesh, no stream of faces with polybrush... :( 

I had the previous retopo version (1.3) and it worked fine, but currently I'm not able to retopologize anything. Could I get some help  ? 

Thanks a lot!

**Comment by carter2422** [comment]
The hotkey for drawing with any tool has changed to CTRL+LMB in v2, per the welcome guide :)
