### ISSUE TITLE
Patches sets all newly selected verts as corners

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#565]
The recent commit to fix the double-clicking to disable a corner has unfortunately resulted in every new vertex being marked as a corner:

https://cl.ly/tKXu

**Comment by carter2422** [comment]
https://github.com/CGCookie/retopoflow/commit/6919dd875c6de6be79dd40bca8a217cc25377e77

**Comment by carter2422** [comment]
Seems to only be an issue when selecting verts/edges one by one. Smart Selection is unaffected.

**Comment by vxlcoder** [comment]
should work correctly now.

**Comment by vxlcoder** [comment]
tested; closing!
