### ISSUE TITLE
Support switching LMB / RMB  for Selection / Action

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#568]
This will be a tricky one but we will need to work on adding full support for artists to choose Left/Right select. 

Ideally we just follow the user's chosen selection mouse in User Preferences.

**Comment by carter2422** [comment]
Note, we had this working in 1.x actually. Might be able to reference some of that. It even allowed for selection and action on the same mouse button, which is my preferred route.

**Comment by jlampel** [comment]
Done in v3.0!
