### ISSUE TITLE
Can't get tools to draw on MacOS Sierra

### ISSUE THREAD

**Issue by artistCDMJ** [CGCookie/retopoflow#569]
Installed RF 2.0 and deselected object (default cube), selected PolyStrip and attempted to draw and nothing draws - same with other tools. Concerned this may be a gpu driver issue since these old macs also have issues with Blender 2.8 Eevee as well.

2010 Mac Pro, Sierra, ATI Radeon HD 5770 1024 MB

**Comment by carter2422** [comment]
Drawing is done with CTRL Left Mouse in v2.

**Comment by artistCDMJ** [comment]
That fixes it - maybe add that in the Quick Start Guide, as I was following
that instruction and missed the difference. Saw the PolyStrips brush cursor
and thought it had to be doing something - but as side note, flipping sweet
interaction on the polypen out of the gate, amazing stuff holy *&(*&)(*$%#@

**Comment by carter2422** [comment]
I could have sworn we had that in the QuickStart and welcome already....whoops!
