### ISSUE TITLE
Error initializing updater code

### ISSUE THREAD

**Issue by Eric-Lafarge** [CGCookie/retopoflow#570]
Hello.
OSX 10.13.6, Blender 2.79
No access to Retopoflow when I select an object. 
![capture d ecran 2018-07-31 a 19 10 21](https://user-images.githubusercontent.com/9129984/43476754-a2c7e672-94f9-11e8-9b82-65724afb5d7f.png)
![capture d ecran 2018-07-31 a 19 25 41](https://user-images.githubusercontent.com/9129984/43476767-a96a8ca0-94f9-11e8-95af-825dc87dc12e.png)
![capture d ecran 2018-07-31 a 19 26 00](https://user-images.githubusercontent.com/9129984/43476769-ab5785e0-94f9-11e8-830b-c86f363dbb67.png)

Best regards.
Eric

**Comment by carter2422** [comment]
V2 uses all deselected objects as the source and the selected object as the target. 

Since you only have the one object RetopoFlow isn’t able to start because there’s no source. 

Simply deselect the cube and then it’ll work.

**Comment by Eric-Lafarge** [comment]
Hello.
That's what I've understood. Still no action with any tools. What about the message error : "Error initializing updater code" 
Best. Eric
![capture d ecran 2018-07-31 a 19 58 56](https://user-images.githubusercontent.com/9129984/43477800-65f91966-94fc-11e8-9ca0-32c201263c2c.png)

**Comment by carter2422** [comment]
Sorry I didn’t realize you were reporting multiple issues. Please keep it one issue per problem so that at easier to keep track :)

For actions use CTRL+LMB, not just LMB.

**Comment by Eric-Lafarge** [comment]
Hello.
Oh.. Sorry. All my confuses. Got it with CTRL+LMB. Thanks a lot and bravo.
Best regards from Paris.
Eric

**Comment by Eric-Lafarge** [comment]
By the way, I thought that the error message ( Error initializing updater code) was the source of the issue, not 2 different problems...

**Comment by jlampel** [comment]
Any problems with the updater should now be fixed. If you have any trouble please let us know by opening a new issue. Thanks!
