### ISSUE TITLE
Working with metric units make the brush shake.

### ISSUE THREAD

**Issue by Sjockey** [CGCookie/retopoflow#573]
Hello ,

I started a new retopology on a simple sphere. My blender units are set up to metric centimeters and while I use Polystrips, Strokes, Relax or tweak tools my brush circle is shaking (scale up/down).
I do not have the issue if my unit settings are set on none(Blender default units).

Here is a video and my blender file showing the problem.
https://www.dropbox.com/s/kgfjwh66cisl6gr/BrushShakingIssueMetric.mp4?dl=0 
https://www.dropbox.com/s/rucfeu4nxnp7m24/BrushShakeIssueMetric.blend?dl=0 

Thanks

**Comment by vxlcoder** [comment]
Thanks for the report, @Sjockey!
This is very interesting.  Looking into it now.

**Comment by vxlcoder** [comment]
With commit 453a9e5, RF now takes into account the scale length of the selected scene units, which _should_ correct this issue.  If you know how to use git, you can clone the `release/2.0.0` branch and test it out.  Otherwise, work in Blender Units only for now, because we will probably release a minor update soon that will contain this fix. Thanks for your report!

**Comment by Sjockey** [comment]
Thanks you for fixing !
I work in the video game industry and It's really important for me to have Retopoflow2 working with metric units. Usually I don't use blender units.

**Comment by vxlcoder** [comment]
tested; closing!

**Comment by vxlcoder** [comment]
Ack!  This issue also shows up if near clip distance is too small (actually might not have been units).  Reopening...

**Comment by vxlcoder** [comment]
I couldn't find a good solution to this.  I believe it's a matter of floating point precision :(, which means that there might not ever be a good solution.

Instead, I've added a warning prompt at the start of RF.  It will only show if the clip start is too small (<0.1), and it simply states that the brush size may jitter when moving the mouse.
