### ISSUE TITLE
Loops: Assert Error!

### ISSUE THREAD

**Issue by jay3sh** [CGCookie/retopoflow#578]
[retopo-human.zip](https://github.com/CGCookie/retopoflow/files/2259050/retopo-human.zip)
Hi,

I was trying to add a loop somewhere in the head area. The model is attached in the zip file. HTH

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.78.0 Unknown Unknown
- Platform: Linux, 4.13.0-46-generic, #51-Ubuntu SMP Tue Jun 12 12:36:29 UTC 2018, x86_64, x86_64
- GPU: Intel Open Source Technology Center, Mesa DRI Intel(R) Iris Pro Graphics 580 (Skylake GT4e) , 3.0 Mesa 17.2.8, 1.30
- Timestamp: 2018-08-03 19:50:02.693221


Error Hash: 0f7cad0a6bca8ff67061bf9f87b5504e


Trace:

- EXCEPTION (<class 'AssertionError'>): Unexpected topology
- .../rfmode/rfmesh.py
- 000 0992:_crawl_quadstrip_to_loopend() assert False, "Unexpected topology"
- 001 0996:is_quadstrip_looped() _,_,_,looped = self._crawl_quadstrip_to_loopend(edge)
- 002 1018:get_face_loop() is_looped = self.is_quadstrip_looped(edge)
- .../rfmode/rfcontext_target.py
- 003 0449:get_face_loop() return self.rftarget.get_face_loop(edge)
- .../rfmode/rftool_loops.py
- 004 0079:set_next_state() self.edges,self.edge_loop = self.rfcontext.get_face_loop(self.nearest_edge)
- .../common/profiler.py
- 005 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode/rftool_loops.py
- 006 0109:modal_main() self.set_next_state()
- .../rfmode/rftool.py
- 007 0110:modal() nmode = self.FSM[self.mode]()
- 008 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode/rfcontext.py
- 009 0556:modal_main() self.tool.modal()
- 010 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report, @jay3sh!

Will take a look at this soon.

**Comment by jlampel** [comment]
@vxlcoder This file still causes problems and even crashes RF! I have yet find out exactly why, but open it up and try adding a loop around here:

![image](https://user-images.githubusercontent.com/12982300/102830975-7ebb5780-439f-11eb-8450-fca8d046b9a0.png)

There doesn't appear to be any inverted normals, doubles, triangles, or any usual suspects that I can find. The only notable thing I see is that the character isn't centered around the origin so the symmetry is lopsided. In other cases though, that hasn't been an issue.

**Comment by jfranmatheu** [comment]
Closing this issue as it seems to be resolved. Tested in Blender 4.3 and RF 3.4.4 with the same provided blend file. If the issue persists, please reopen it. Thank you!
