### ISSUE TITLE
Contours: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by TeoLions** [CGCookie/retopoflow#580]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.6 experimental-build 2018-07-23
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 970/PCIe/SSE2, 4.6.0 NVIDIA 398.82, 4.60 NVIDIA
- Timestamp: 2018-08-04 23:43:13.312389


Error Hash: 50ad1aa17c2cc9ca94e14a9a237bc6ff


Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
- .../rfmode\rfmesh_wrapper.py
- 000 0150:co() self.bmelem.co = self.symmetry_real(co, to_world=False)
- .../rfmode\rftool_contours.py
- 001 0399:modal_move() verts[i].co = p
- .../common\profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0556:modal_main() self.tool.modal()
- 007 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report, @TeoLions!

Can you provide a bit more context of when this error occurred?  I'd like to try to reproduce it to figure out how to fix it.  A screenshot or steps to reproduce would be very helpful.

Thanks!

**Comment by jlampel** [comment]
Closing out since it's been over two years without a response. If it happens again please open a new issue. Thanks!
