### ISSUE TITLE
Retopoflow cant activate without administrator privileges

### ISSUE THREAD

**Issue by ghost** [CGCookie/retopoflow#584]
![capture2](https://user-images.githubusercontent.com/42103414/43681781-12f32314-982c-11e8-88c3-ffadc5abcaa8.PNG)

**Comment by vxlcoder** [comment]
Thanks for the report, @buzzrapide.

Unfortunately, we've seen that some versions of Blender (especially for Windows) do not include some of the Python libraries that we use, but some versions do.

Are you using Blender 2.79b?  Where did you get the installer?  Did you use the installer or download the zip?

**Comment by buzzrapide** [comment]
Its on blender 2.79b and both installer and zip doesnt work

**Comment by EmeraldEelEntertainment** [comment]
I have the same issue too. I'm using 2.79.

**Comment by vxlcoder** [comment]
Ok, this is somewhat of a known issue.  see https://docs.blender.org/manual/en/dev/troubleshooting/python.html#mixed-python-libraries-dll-s

A question for you all: What other Blender add-ons have you installed or enabled?

Here is a possible workaround:

1. exit Blender (in case it is open)
2. rename the `2.79` folder in `C:\Users\YourName\AppData\Roaming\Blender Foundation\Blender\` to `2.79.bak` or something similar.
3. start Blender
4. install RF

Note: any add-ons installed or settings stored in the `2.79` folder will need to be reinstalled / re-set.  If all else fails, you can simply rename the `2.79.bak` folder back to `2.79`.

**Comment by Reoxur** [comment]
I noticed you have to Run Blender in Administrator mode for  Retopoflow to work and or Activate

**Comment by carter2422** [comment]
@vxlcoder do you have a windows machine at hand to look into the Administrator mode requirement? That shouldn't be the case.

**Comment by vxlcoder** [comment]
Interesting.  I have never had this be an issue before.  Maybe Blender was installed by an admin, and the settings are stored in a folder that needs special permissions to write into?  @Reoxur, what happens if you download Blender as a zip file, extract the folder to a personal folder (ex: `C:\Users\yourusername\Downloads`), install RF, and then try to activate it?

Hmm, I also wonder if `socket.py` tries to open a port (or something like that), and the Windows permissions prevent it for some reason.  I'll look into that more.

**Comment by Reoxur** [comment]
I guess I do have a messed up Windows install 
I mean I am the admin but things still require admin to run sometimes

And your right, if I installed Blender in a personal folder it doesn't require admin.
And Blender right now is installed in "Program Files"  folder where it does require admin but only for Retopoflow it seems.

Its not really an issue but I can imagine some people wouldn't know they had to run it with Admin.

**Comment by vxlcoder** [comment]
Thanks for the feedback, @Reoxur!

Could you do something for me?  Can you start Blender (the Program Files one) from the terminal (or open the terminal after starting), try to enable RF (which should fail), and then copy-paste everything that was reported in the terminal?  Thanks!

**Comment by ArtBlend** [comment]
AL lib: (EE) UpdateDeviceParams: Failed to set 44100hz, got 48000hz instead
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
RetopoFlow Options path: C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\RetopoFlow_options.json
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\__init__.py", line 69, in <module>
    raise e
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\__init__.py", line 48, in <module>
    from .interface import (
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\interface.py", line 40, in <module>
    from .rfmode.rftool import RFTool
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py", line 36, in <module>
    from .rfwidget import RFWidget_Default
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfwidget.py", line 36, in <module>
    from .rfwidget_brushstroke import RFWidget_BrushStroke
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\rfmode\rfwidget_brushstroke.py", line 26, in <module>
    from ..common.shaders import brushStrokeShader
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\common\shaders.py", line 329, in <module>
    brushStrokeShader = Shader.load_from_file('brushStrokeShader', 'brushstroke.glsl', checkErrors=False, bindTo0='vPos')
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\common\shaders.py", line 109, in load_from_file
    return Shader(name, srcVertex, srcFragment, *args, **kwargs)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\common\shaders.py", line 128, in __init__
    logv = self.shader_compile(name, self.shaderVert)
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\addons\retopoflow-master\common\shaders.py", line 64, in shader_compile
    assert not log and 'was successfully compiled' not in log, 'ERROR WHILE COMPILING SHADER %s: %s' % (name,log)
AssertionError: ERROR WHILE COMPILING SHADER brushStrokeShader: No errors.

**Comment by ArtBlend** [comment]
This is what shows in the terminal

**Comment by prophet067** [comment]
Hello, I am having this issue currently in Windows was there ever any fix found?

**Comment by Reoxur** [comment]
@prophet067
Try run Blender as administrator

**Comment by prophet067** [comment]
Hey @Reoxur I tried this but still the same error

**Comment by James-mwangi** [comment]
RF does not activate even after i try the suggested fixes bove

**Comment by vxlcoder** [comment]
@ArtBlend and @James-mwangi, you two are seeing a different problem.  Your problem should now be fixed in commit 87ae7fd.  Try pulling the latest version of `release/2.0.1` branch.  Let us know if you still have problems.

@prophet067, try downloading and unzipping Blender to your desktop (rather than installing it).  Then, run the Blender.exe that is inside the Blender folder on your desktop.  Your issue may also be a permissions issue.

**Comment by jfranmatheu** [comment]
Closing issue due to prolonged inactivity. It could be resolved in later Blender versions. If the issue persists, please reopen it. Thank you!
