### ISSUE TITLE
Loops crash

### ISSUE THREAD

**Issue by TeoLions** [CGCookie/retopoflow#586]
I'm trying to use Loops on this exact loop and it's deadlocking whole Blender, I have to kill it via task manager. Interesting thing is that's happens ONLY from point of view like on this screenshot:

![image](https://user-images.githubusercontent.com/42072774/43802251-e65a435e-9a9d-11e8-9ea0-d6ba29444b2d.png)

But if you rotate camera to another side, it would cut it without any problem. 
Scene: https://drive.google.com/open?id=1TpfbywFcSqDY_NLIHoAzoQJYdVpN3Yuw

**Comment by carter2422** [comment]
I've just replicated this.

@vxlcoder it hard-crashes when cutting a loop that includes a triangle. Like this: | | | < | | |, with it looping all the way around.

**Comment by jlampel** [comment]
This still crashes reliably, and seems to be any time that a single triangle is stopping both ends of the loop:
![image](https://user-images.githubusercontent.com/12982300/101206068-746d2f80-3623-11eb-9f2f-04ff2764a04d.png)

**Comment by vxlcoder** [comment]
oh my!  sorry that I totally missed this!

should now be fixed! :)

**Comment by jlampel** [comment]
Confirmed fixed!
