### ISSUE TITLE
In Japanese language mode , View can't move.

### ISSUE THREAD

**Issue by iCyP** [CGCookie/retopoflow#593]
user preferences -> Internationa Fonts :True , Language:Default(Japanese), Translate->Interface:True
When above setting, RetopoFlow's view can't be moved in center mouse button drug and Numpad.

it causes reason:
useractions.py -> class Actions ->dict: "navigation_events" 's keys are English hard cording.
But Blender's i18n translate above keys target words.  

My Solution
compare operator's idname
I don't know why bpy.app.translate.pgettext("View Pan") and so on are not translated.
Code:
useractions.py :line 123
->if kmi.idname not in self.navigation_events.values(): continue

**Comment by vxlcoder** [comment]
Thanks for the report, @iCyP!  I believe that commit 45d4618 fixes this issue.  At least, my tests show this works.  Do you know how to download a branch from GitHub?  If so, could you test the `release/2.0.1` branch to see if RF works properly with your internationalization settings?  If not, let me know, and I'll copy instructions to do so.  Otherwise, wait for the next minor release (should be only a week or so).

**Comment by iCyP** [comment]
release/2.0.1 works  view camera in Japanese Interface. Thank you!! 👍

**Comment by vxlcoder** [comment]
You are right, @TJYSunset.  We did plan to release a new version shortly after 2.0 to correct a few lingering bugs and to address the many new bugs that surfaced.  We missed that mark, and I am sorry that we didn't get something out sooner.  I appreciate your frustration, especially as a developer who knows how the code could be written and corrected.

We have corrected this issue along with many others in the `release/2.0.1` branch, and we are currently working on getting a release ready for the Blender Market as I write this.  If it helps, you can download and install a pre-release of v2.0.1 from [here](https://www.dropbox.com/s/khjv2it1aerun48/RetopoFlow_v2.0.1.zip?dl=0) or checkout the branch.  This pre-release version _should_ be production ready, only needing updated documentation, a few smaller issues tended, and some polish worthy of an official release on the Blender Market.

As a way to improve RF for the entire Blender/retopo community (especially the non-English), would you please consider opening a new issue with a proposal on how to make the documentation friendlier?
