### ISSUE TITLE
Need to be able to toggle xray view while in Retopoflow

### ISSUE THREAD

**Issue by Two-Tone** [CGCookie/retopoflow#594]
As it stands right now, you can't toggle xray view. You have to 
 
1. leave RF

2. toggle it on
 
3. go back into RF (which can take some time with high poly stuff!)
 
4. do what you need xray for
 
5. leave RF again, toggle xray off
 
6. then go back into RF and continue

This is really cumbersome.

**Comment by vxlcoder** [comment]
@Two-Tone, how are you using xray?  Can you post a few example screenshots?

**Comment by Two-Tone** [comment]
The main thing I have been using xray is for a fast and easy way to make sure the number of quads I have on one side of my mesh matches the side I was working on.  

This isn't a real world example as the blend file for mesh I was retopo-ing has become corrupted, but it does show how I use xray.

![](https://i.imgur.com/K58L5xl.png)

![](https://i.imgur.com/Xudgdfu.png)

The second requires fullscreening to see the verts, but you *can* see them. Wouldn't hurt if they were a little brighter (or a different color to show we're seeing a vertex from the back).

**Comment by vxlcoder** [comment]
Under `General Options > Target Rendering`, you have controls over how the target mesh is rendered.  Changing the alpha values can mimic the xray view.  Below is an example using the latest `release/2.0.1` branch, which will be released soon.  I believe you should have similar ability in the current 2.0.0 version.

![backfacing](https://user-images.githubusercontent.com/3790699/44091932-08b7feb0-9f9d-11e8-8e4e-693c78a72d8f.gif)

This isn't exactly the same as Blender's xray, and I do think this is a useful feature to have, so maybe it should be a RF feature?  @carter2422, do you have any thoughts on a good way to bring this to RF?  We could "erase" the depth info after rendering the sources, but before rendering the target, which would be much closer to Blender's xray, but I don't know if that's the best approach for us.  Maybe an xray checkbox simply presets the alphas to something reasonable?

**Comment by jlampel** [comment]
The display options seem to address the pain point, so I'll close this out. If you continue to find it to be a burden, please open a new issue to let us know. Thanks!
