### ISSUE TITLE
. key on numpad doesn't center view on selected

### ISSUE THREAD

**Issue by Two-Tone** [CGCookie/retopoflow#595]
This is along the same lines as #594. Just seems like a simple oversight.

I did this as a separate issue since they're separate features.

**Comment by vxlcoder** [comment]
This _should_ work as expected (at least is does on all of my machines).  Would you mind posting a .blend file that has an element selected that fails to center the view?  Also, have you changed from default any of the Blender settings?  I'm wondering if there is a setting that is affecting this operation.  Thanks!

**Comment by Ginoan** [comment]
I'm having the same issue where hitting . key on numpad won't center on selected, it will keep rotating around the center point. This doesn't happen all the time though, but I don't know what triggers the problem and what solves it. Sometimes leaving retopoflow mode will cause or fix the issue, but I think it also happens in the middle of working [while inside retopoflow mode].

I have changed some things from the Blender default settings but I don't know if there's anything too major... On "Input" I changed it to "select with Left", and on Interface I have "Rotate around Selection" checked.

**Comment by 3DEsprit** [comment]
Making a note here that someone reported a similar issue with a hotkey not working when using an alternative keymap, more specifically the in-tool Fill hotkey. Neither the default hotkey, and the newly assigned fill hotkey would not work as a fill, though it did in fact work in Edit Mode. Moving back to the default Blender keymap was their only resolve for this issue.

**Comment by carter2422** [comment]
Closing this since it's almost certainly due to not (yet) being included in RetopoFlow's custom keymap. This custom keymap is scheduled to be replaced with native Blender keymaps via #718
