### ISSUE TITLE
Loops: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by garthhendy** [CGCookie/retopoflow#596]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.0

- EXCEPTION (<class 'UnboundLocalError'>): local variable 'sel_only' referenced before assignment
-          C:\Users\garth\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool_loops.py
- 000 0110:modal_main() if sel_only: self.rfcontext.deselect_all()
-          C:\Users\garth\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rftool.py
- 001 0103:modal() nmode = self.FSM[self.mode]()
- 002 0107:modal() raise e
-          C:\Users\garth\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\RetopoFlow\rfmode\rfcontext.py
- 003 0472:modal_main() self.tool.modal()
- 004 0396:modal() nmode = self.FSM[self.mode]()

**Comment by vxlcoder** [comment]
Thanks for the report, @garthhendy.  This issue has already been taken care of!  You should be able to upgrade from 2.0 beta to the official 2.0 release using the add-on updater or download from Blender Market.  I will close this issue for now, but please let us know if you run into any problems.  Thanks!
