### ISSUE TITLE
UI: Options are becoming very large, Too many windows?

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#597]
The options window is becoming very large, which makes it more difficult to find the right settings (even with auto-collapse turned on)

Here are some options:

1. hide, not just collapse, options for tools that are not the currently selected tool
2. place all tool options in their own window, and then reveal the options for the currently selected tool
3. put tool options in a pop-up window (like `X` for delete/dissolve)
4. others?

Another issue is the number/size of windows.  There is the option to hide windows with F9, but this all or none feature isn't as useful.  Could add close buttons to windows, but need to have some way to reopen.  What about making F9 open a dialog (like `X` for delete/dissolve) to open/close specific windows?

**Comment by SavMartin** [comment]
I prefer option 2, and F9 will be ok..

**Comment by jlampel** [comment]
Seems like something we'll continue to explore, but for now it looks like all pain points mentioned have been addressed
