### ISSUE TITLE
Retopoflow 2.0 not Working on iMac 2017

### ISSUE THREAD

**Issue by MooseQ** [CGCookie/retopoflow#598]
When I go into the RF screen Contours, Polystrips etc are greyed out.  I also get an error message:

TARGET WARNING:
Polycount is high.
Retopoflow may load slowly.

My target object has 150,792 tris. only. 

Not sure why it's not working.  The 1st version of RF worked.

**Comment by vxlcoder** [comment]
In RF 2.0, the selected _and_ active object is the target mesh (the low-res retopo mesh), while all other visible meshes are considered sources (high-res mesh that you're reconstructing with RF).  It sounds to me like you're trying to retopo the 150k mesh.  In that case, deselect all meshes, and when you click a RF button, RF will automatically create a new target mesh.

If I'm not understanding your situation correctly, please let me know, perhaps with some screenshots.

Thanks!

**Comment by MooseQ** [comment]
trying to add a screenshot.  Let me know if you can't see it. ~ Thanks!

<img width="1482" alt="screen shot 2018-08-14 at 4 58 44 pm" src="https://user-images.githubusercontent.com/42391247/44118984-c5d040b4-9fe5-11e8-802e-4141847163b6.png">

**Comment by MooseQ** [comment]
OK.  Got it.  I also need to press Ctrl. when drawing.  Thanks very much!

**Comment by vxlcoder** [comment]
You are welcome!  We're happy to help!

closing the issue.
