### ISSUE TITLE
Blender Crashes on Symmetry Selection

### ISSUE THREAD

**Issue by MooseQ** [CGCookie/retopoflow#602]
I have been trying to practice RF 2.0 on Suzanne, nothing complicated.  Frequently, upon clicking the "X" button for symmetry selection, Blender just crashes.

**Comment by carter2422** [comment]
We've seen this a few times @MooseQ but have never been able to consistently replicate it. 

Do you see any errors in the system console after crashing?

**Comment by MooseQ** [comment]
I didn't note the error message if there was one, but I will pay close attention next time and document it if that would help.

I have a 2017 iMac in case that makes a difference.  So far I'm struggling with this add-on but I want to give it a good try before giving up.

I wonder also if there is an Undo function with this?  The usual Cmd Z doesn't seem to work.

Thanks for your help!

**Comment by carter2422** [comment]
You can undo with CTRL Z. We will add CMD Z support. 

Please do let us know any other issues you run into, it’s a big help!

**Comment by MooseQ** [comment]
Will do.  Thanks very much for all your efforts!

**Comment by MooseQ** [comment]
Oh, here's a problem that I've encountered a few times also...vertexes sometimes not snapping to the surface.
<img width="1319" alt="screen shot 2018-08-16 at 4 14 12 pm" src="https://user-images.githubusercontent.com/42391247/44232690-d0200000-a16f-11e8-9813-501b03f557ea.png">

**Comment by vxlcoder** [comment]
@MooseQ, I'm not sure what you mean.  In the screenshot, the rightmost vertex is snapped to the surface of the ear.  Note: when you're using the tools (especially PolyStrips), the new geometry is created by snapping to what is visible on the screen.  So, if you use the tool on a part of the source that slopes away from the view, you will get skewed geometry.

**Comment by MooseQ** [comment]
Got it. Thank you!

**Comment by jlampel** [comment]
Closing this out as it hasn't been replicated in two years and is out of date. If you have any trouble in the future please open a new issue and we'll take a look. Thanks!
