### ISSUE TITLE
X Symmetry Off Center 

### ISSUE THREAD

**Issue by MooseQ** [CGCookie/retopoflow#604]
Is there a way to adjust the symmetry plane on my object?  It's way off the center line of the object.
<img width="1136" alt="screen shot 2018-08-17 at 3 06 44 pm" src="https://user-images.githubusercontent.com/42391247/44284427-96163300-a22f-11e8-9857-6e5cff5851ef.png">

**Comment by carter2422** [comment]
The symmetry line is placed at the 3D cursor location when first starting RetopoFlow, as that's where the new target object's origin is place; just like any other object in Blender. 

You can adjust it after the fact by moving the object origin.

**Comment by MooseQ** [comment]
OK. Got it. Thanks!
