### ISSUE TITLE
Stretch: Selecting an edge and drawing a line to stretch to causes Unhandled Exception

### ISSUE THREAD

**Issue by hnm-zz** [CGCookie/retopoflow#606]
create a new file
shift a> mesh> uv sphere
shift a>mesh> plane
in the assets tree, select the plane
select tools> retopology> polystrips
draw any line
select tools> retopology> stretch
right click to select one edge
hold ctrl click and draw a line

A sort of animation is created at the selected edge. The two vertices slowly draw together and try to merge into one. Once this begins, the errors start. The errors cannot be skipped or silenced, and cycle continuously, forcing a restart.

repro: 50%

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 7, 6.1.7601, AMD64, Intel64 Family 6 Model 62 Stepping 4, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 770/PCIe/SSE2, 4.4.0, 4.40 NVIDIA via Cg compiler
- Timestamp: 2018-08-24 11:25:53.697136


Error Hash: 887c95275b1f15eccb46719e0071b03f


Trace:

- EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
- .../rfmode\rftool_stretch.py
- 000 0242:process() a = (od - d) * force / d
- 001 0098:modal_main() if self.rfcontext.actions.timer and self.process: self.process()
- .../common\profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 003 0110:modal() nmode = self.FSM[self.mode]()
- 004 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 005 0556:modal_main() self.tool.modal()
- 006 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by carter2422** [comment]
Thanks for the report @hnm-zz. The Stretch tool is not yet ready and failures are expected. We'll get it fixed regardless!

**Comment by jlampel** [comment]
Closing out as the stretch tool is no longer part of RF. We'll investigate issues like this if / when it's added back. Thanks!
