### ISSUE TITLE
Vertices move to center of mesh when I activate symmetry

### ISSUE THREAD

**Issue by billkakou** [CGCookie/retopoflow#609]
Hi, first of all thanks for this great addon!!
Ok now, when I activate symmetry and try to edit, vertices stick to the center of the mesh. This happens with all tools. 
![error](https://user-images.githubusercontent.com/41488530/44741746-b20ab600-ab06-11e8-9ad4-eafd71c6c759.jpg)

**Comment by carter2422** [comment]
My hunch @billkakou is that your source and newly created target objects are super tiny, leading to the Mirror clipping value causing the verts to snap to the center line when manipulated. 

Can you try scaling your objects in Object Mode, Applying the scale with CTRL+A, and then see if it still happens?

**Comment by billkakou** [comment]
Thanks for the super fast response Jonathan. Well I made the objects really big and I applied scales but I have the same issue. That's weird because this happens only in this specific scene.

**Comment by vxlcoder** [comment]
@billkakou, I'm pretty sure that your target mesh is on the "wrong" side of the symmetry.  If you select `Face` for symmetry visualization, I'd bet your target is on the colored side.  One quick fix is to tab into edit mode on the target, select all (`A`), scale (`S`) along the x-axis (`X`), type `-1` and hit enter.  That will flip the target geometry to the "correct" side.

**Comment by billkakou** [comment]
Thanks Jon that was the problem!
