### ISSUE TITLE
Strokes: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by ColdNightHour** [CGCookie/retopoflow#612]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------
All I did was enter into retopoflow and try to pan around my mesh.
```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1050 Ti with Max-Q Design/PCIe/SSE2, 4.6.0 NVIDIA 398.36, 4.60 NVIDIA
- Timestamp: 2018-08-31 11:17:17.978323


Error Hash: ccd86f3e6e5e4b76b4b9f93201fc039c


Trace:

- EXCEPTION (<class 'ReferenceError'>): BMesh data of type BMVert has been removed
- .../rfmode\rfmesh_wrapper.py
- 000 0145:co() return self.l2w_point(self.bmelem.co)
- .../rfmode\rftool_strokes.py
- 001 0322:create_strip() co = snap1.co
- .../rfmode\rftool.py
- 002 0076:wrapper() ret = fn(*args, **kwargs)
- .../rfmode\rftool_strokes.py
- 003 0261:stroke() if self.replay: self.replay()
- .../rfmode\rfwidget_brushstroke.py
- 004 0056:modal_brushstroke() if self.stroke_callback: self.stroke_callback()
- .../rfmode\rfwidget.py
- 005 0189:modal() nmode = self.FSM[self.mode]()
- 006 0194:modal() raise e
- .../rfmode\rfcontext.py
- 007 0554:modal_main() if self.rfwidget.modal():
- 008 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report, @ColdNightHour.  I'm confused how panning could have caused this.  Have you changed your keyboard/mouse mapping for panning to something that uses CTRL, ALT, or SHIFT?

**Comment by vxlcoder** [comment]
Are you able to reproduce this bug with the startup .blend file (default cube)?

**Comment by vxlcoder** [comment]
I'm not certain how to replicate this issue, so I cannot debug it directly.  If you can reproduce this issue consistently, please add a comment.

In the meantime, I have made some changes in b9f7b42 that might fix this issue.  Let us know if you continue to run into this issue.

**Comment by jlampel** [comment]
Closing this out due to lack of activity. I'm not able to replicate the problem, but if you experience it again, especially in v3.0+, please report it as a new issue. Thanks!
