### ISSUE TITLE
Contours: Unhandled Exception while trying to rotate loop with 'S' key

### ISSUE THREAD

**Issue by Shulito** [CGCookie/retopoflow#616]
![retopoflow_screenshot_error](https://user-images.githubusercontent.com/2199770/45004374-533fb380-afc2-11e8-891f-e4fd932b884d.png)
![retopoflow_screenshot_noerror](https://user-images.githubusercontent.com/2199770/45004375-53d84a00-afc2-11e8-9351-e80fbac6659c.png)

I created a contours from right view (number 3 in keypad), then I went into front view (number 1 in keypad) and hit the 'S' key to adjust the rotation and the error was thrown (first image). Strangely, if I go back to right view (number 3 in keypad) I can rotate the loop with the 'S' key (second image). I attach the blender scene for debugging.

[hero_error.zip](https://github.com/CGCookie/retopoflow/files/2346779/hero_error.zip)

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 1080 Ti/PCIe/SSE2, 4.6.0 NVIDIA 398.11, 4.60 NVIDIA
- Timestamp: 2018-09-03 21:40:20.055406


Error Hash: b9af582398556064c0d4e234a1d33685


Trace:

- EXCEPTION (<class 'NameError'>): name 'dprint' is not defined
- .../rfmode\rftool_contours.py
- 000 0221:prep_shift() dprint('could not crawl around sources for loop')
- 001 0187:modal_main() return self.prep_shift()
- .../rfmode\rftool.py
- 002 0110:modal() nmode = self.FSM[self.mode]()
- 003 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 004 0556:modal_main() self.tool.modal()
- 005 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report, @Shulito!  It's strange that you ran into this particular problem, but I'll get a fix for it as soon as I can.

**Comment by jlampel** [comment]
This file no longer throws an error, and instead shows a note and stops the operation:
![image](https://user-images.githubusercontent.com/12982300/101203661-e5124d00-361f-11eb-9922-fdb1d1e3c720.png)
