### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by emilsvfx** [CGCookie/retopoflow#617]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.Also, change the title of this bug report to something descriptive and helpful.
Thank you!
-------------------------------------
RetopoFlow: 2.0.0 beta
Blender: 2.79.4

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
-          C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rfmesh.py
- 000 1281:new_edge() bme = self.bme.edges.new(verts)
-          C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext_target.py
- 001 0370:new_edge() return self.rftarget.new_edge(verts)
-          C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rftool_polypen.py
- 002 0256:modal_insert() bme = self.rfcontext.new_edge((bmv0, bmv1))
-          C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0103:modal() nmode = self.FSM[self.mode]()
- 005 0107:modal() raise e
-          C:\Users\Emilsvfx\AppData\Roaming\Bforartists\Bforartists\2.79\scripts\addons\retopoflow-master\rfmode\rfcontext.py
- 006 0472:modal_main() self.tool.modal()
- 007 0396:modal() nmode = self.FSM[self.mode]()

**Comment by jlampel** [comment]
I'm closing this out because it's outdated and similar issues have since been fixed, but if you have trouble with this in the future please open a new issue and we'll take a look. Thanks!
