### ISSUE TITLE
Unable to use when isolated with the "/" mode

### ISSUE THREAD

**Issue by VESPERDESIGN** [CGCookie/retopoflow#618]
I was trying to remove the clutter out of the way when working on retopologizing and I noticed all the options were grayed out! As soon as I brought all the other meshes into the scene the options turned on. I am using 2.0

**Comment by carter2422** [comment]
This is due to limitations in the Blender API when working with visible objects.

Rather than using local view simply hide the objects you don’t want visible. RetopoFlow will use all unselected, visible, mesh objects as the source.

**Comment by VESPERDESIGN** [comment]
Question do you have to hold CTRL to use the objections in isolation?

**Comment by carter2422** [comment]
Use CTRL + H to hide all but the selected object.

**Comment by VESPERDESIGN** [comment]
no what I mean is that I can't use contours or polystrips or any of the others without holding CTRL???

**Comment by carter2422** [comment]
That’s correct. Use CTRL + LMB for activating each tool. Lmb to manipulate selection. Rmb to select.

**Comment by carter2422** [comment]
Note, I’m closing this since it’s not actually a bug. For further support please open a ticket on the Blender Market via your inbox. Thanks!

https://blendermarket.com/inbox
