### ISSUE TITLE
improve bgl drawing

### ISSUE THREAD

**Issue by patmo141** [CGCookie/retopoflow#62]
Many of the draws in Contours use inefficient methods to achieve visualization.  Eg.  Duplicating the last vert of a closed loop and draw with GL_LINES instead of not duplicating the vert and using GL_LINE_LOOP.

Also many of the utilities do not do good bookkeeping and will sometimes leave GL settings altered until another Blender callback resets them.

A general code review and optimization is in order.

**Comment by carter2422** [comment]
With the pending OpenGL upgrade coming I assume we can close this?

**Comment by carter2422** [comment]
@patmo141 ping. Can we close this what with #173 ?

**Comment by vxlcoder** [comment]
done!
