### ISSUE TITLE
Retopoflow contours isn't working

### ISSUE THREAD

**Issue by NuhanKhan** [CGCookie/retopoflow#622]
don't know why but something is wrong with my retopoflow 2.0
![retopoflow](https://user-images.githubusercontent.com/43064320/45212919-00c4f800-b24b-11e8-9448-9beda75aa56c.PNG)

**Comment by vxlcoder** [comment]
When you start RF, whatever mesh is selected and active is considered the target mesh (the retopo'd surface), while all other visible meshes are considered the source.  If you want RF to create a new target mesh (which you'll be doing the very first time you start RF), deselect all meshes before you start RF.

See the Quick Start Guide for more details.

**Comment by NuhanKhan** [comment]
Thanks
