### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by ps-gregg** [CGCookie/retopoflow#623]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070 Ti/PCIe/SSE2, 4.6.0 NVIDIA 388.13, 4.60 NVIDIA
- Timestamp: 2018-09-08 23:54:15.784468


Error Hash: 7b8b20170278afb7b60154fb5ba8160c


Trace:

- EXCEPTION (<class 'TypeError'>): glVertex2f() argument after * must be an iterable, not NoneType
- .../rfmode\rftool_polypen.py
- 000 0496:draw_lines() bgl.glVertex2f(*coords[0])
- 001 0576:draw_postpixel() self.draw_lines([bmv0.co, p0])
- .../common\profiler.py
- 002 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rfcontext_drawing.py
- 003 0137:draw_postpixel() self.tool.draw_postpixel()
```

**Comment by carter2422** [comment]
Let's review this in `b280` please @vxlcoder

**Comment by jlampel** [comment]
I'm closing this out because similar issues have since been fixed, but if you have trouble with this in the future please open a new issue and we'll take a look. Thanks!
