### ISSUE TITLE
Version 2.0.0 unusable on blender 2.79b

### ISSUE THREAD

**Issue by CharlysTorres** [CGCookie/retopoflow#626]
code error in __init__

**Comment by CharlysTorres** [comment]
Report: Error
Traceback (most recent call last):
File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
mod = _import_(module_name)
File"/home/user/.config/blender/2.79/scripts/addons/retopoflow-master/__init__.py", line 69, in <module>
raise e
File"/home/user/.config/blender/2.79/scripts/addons/retopoflow-master/__init__.py", line 48, in <module>
from.interface import (

and ETC....

**Comment by vxlcoder** [comment]
Thanks for the report, @CharlysTorres.
We will need more information to figure out what is causing the problem, though.  For example:

- Copy-paste everything reported in the terminal.
- Did you clone the repo directly into the `addons` folder or symlink there?  Or, did you download the created zip from GitHub?  You can try renaming the `retopoflow-master` folder in the `addons` folder to `retopoflow`, or install the zip provided by us through the Blender Market.
- Has it worked before, but now it isn't?

**Comment by tripleqs** [comment]
This is all console line I got:
Traceback (most recent call last):
  File "/usr/share/blender/scripts/modules/addon_utils.py", line 331, in enable
    mod = __import__(module_name)
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/__init__.py", line 69, in <module>
    raise e
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/__init__.py", line 48, in <module>
    from .interface import (
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/interface.py", line 40, in <module>
    from .rfmode.rftool import RFTool
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rftool.py", line 36, in <module>
    from .rfwidget import RFWidget_Default
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rfwidget.py", line 36, in <module>
    from .rfwidget_brushstroke import RFWidget_BrushStroke
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/rfmode/rfwidget_brushstroke.py", line 26, in <module>
    from ..common.shaders import brushStrokeShader
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/common/shaders.py", line 30, in <module>
    from ..ext.bgl_ext import VoidBufValue
  File "/home/excavator/.config/blender/2.79/scripts/addons/retopoflow-master/ext/bgl_ext.py", line 30, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'

I had tried RF on Blender 2.79 on Windows 10, it is worked like a champ. But When I tried it on Ubuntu and Blender 2.79b I got this error. I have no ideas that it about Ubuntu nor 2.79b ver

**Comment by tripleqs** [comment]
I have just check it again, I found that error is problem of Blender version, I tried 2.79 ver it is work properly again.

**Comment by vxlcoder** [comment]
@tripleqs: just to be clear, RF worked fine on 2.79 on Ubuntu, but not on 2.79b?  NumPy _should_ come with the Linux build, but sometimes Blender will try to use your system's Python if it is installed.  If you can, try starting Blender with the `--debug-python` flag.  This will cause Python debugging output to be printed to console.  Thanks!

**Comment by tripleqs** [comment]
Yub it work with 2.79 but not on 2.79b.

**Comment by wolfx** [comment]
Hello,
for me the error come from ui.py on line 1373 with the async=True. async is a reserved keywords since python 3.5.
I have changed the naming and all is working now.

**Comment by DarthMoulByte** [comment]
> Thanks for the report, @CharlysTorres.
> We will need more information to figure out what is causing the problem, though. For example:
> 
> 
![image](https://user-images.githubusercontent.com/24207840/60854559-539e7180-a1c6-11e9-8207-70e3e253f095.png)

> * download ZIP from github repository.  yes i can but you should put this information in your READ.ME`, I do not want to pay $ 86 for something that is not working properly.
> * if a zip file of 2018 works on my laptop, but now that I install it on my desktop it does not work


download the github zip
what difference is there, apart from paying $ 86 for something that according to the creator is already free and was announced in many places in blender communities?

download the github zip
what difference is there, apart from paying $ 86 for something that according to the creator is already free and was announced in many places in blender communities?

What happens if I pay the 86 dollars for the same error? Are they going to return them? or apply the GNU license where it says there are no guarantees?

because this could be understood quite badly to the detriment of his image

**Comment by carter2422** [comment]
@DarthMoulByte the Github version is the same code as is sold on Blender Market. The code is all GPL and provided for free. The difference is when you purchase a copy you help ensure continued development and we will provide user support for the tools. 

Note, simply installing the download from Github will not work; GitHub packages the .zip differently than Blender requires. The purchased download form Blender Market is ready to install directly. 

The Github repository is kept open to the public to encourage collaborative development and sharing of the code. It is not intended for end-user consumption, although we do not prevent that, it's just up to you to work through the installation.

**Comment by vxlcoder** [comment]
@DarthMoulByte, I am confused about what your question / issue is. Are you asking why should you pay for a program that has its source code available for free online? That is a question for another issue thread or the forums. But the short is this: we package RF in a nice zip that is easily installable in blender (that is what the makefile is for) and we offer customer support through blender market. This GitHub issue tracker is for reporting and debugging issues. Sometimes BM customers might need to post an issue here. Sometimes we need more info, like .blend files or screenshots or terminal dump.

If you're asking about getting RF working, be sure to uninstall any previous version of RF first, to use the latest build of Blender 2.79b, and to install the latest version of RF 2.0.3. You can download a zip of RF from GH, but you will likely need to manually install in Blender's add-on folder. (Blender's install doesn't work well with GH zip files, hence the makefile)

**Comment by carter2422** [comment]
Closed for inactivity.
