### ISSUE TITLE
Rotate around selection / zoom to mouse position

### ISSUE THREAD

**Issue by miecz** [CGCookie/retopoflow#628]
It's more of a feature request. It would be great if Retopoflow respected the "rotate around selection" or "zoom to mouse position" option from the preferences. So if you select a vertex / edge or face you rotate the view around it. Right now it seems like the rotation is around the object's pivot point (with the "rotate around selection" option enabled). It can get quite confusing, especially if your pivot is not inside the object. In my example I have several clothes that I need to retopologize for my character. All the clothes have their pivot points in my character's feet (which is a usual case when working on game characters). I can of course use a workaround and temporarily change the pivot point of an object, but a "rotate around selection" option would be perfect.

**Comment by carter2422** [comment]
Hey @miecz; apologies for never following up on this but the Rotate Around Selection functionality was added a while back!
