### ISSUE TITLE
Strokes: Unhandled Exception on attempting to connect third stroke

### ISSUE THREAD

**Issue by Syndaryl** [CGCookie/retopoflow#630]
**Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened**.

I put down one stroke following the orbit of my figure and adjusted the crosses to 16. I then put down a second stroke up the brow of my figure, and adjusted the crosses to 16. I tried to initiate a third stroke starting from the top left vertex (see screenshot below) and then blender chucked the Exception. 

**Screenshots and .blend files are very helpful.**

[retopoflow_screenshot](https://user-images.githubusercontent.com/8820565/45632779-30a2a580-ba6c-11e8-8985-60cdae31e21d.png)

[Blend File That Threw Exception (in zip)](https://github.com/CGCookie/retopoflow/files/2389192/Exception.zip)
-------------------------------------

```
Environment:

- RetopoFlow: 2.0.0
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 10, 10.0.17134, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 1080 Ti/PCIe/SSE2, 4.6.0 NVIDIA 391.35, 4.60 NVIDIA
- Timestamp: 2018-09-17 11:23:16.075517


Error Hash: 0261875fd38741a7a94a7a79fa7edbf7


Trace:

- EXCEPTION (<class 'ValueError'>): faces.new(...): found the same (BMVert) used multiple times
- .../rfmode\rfmesh.py
- 000 1336:new_face() bmf = self.bme.faces.new(verts)
- .../rfmode\rfcontext_target.py
- 001 0399:new_face() return self.rftarget.new_face(verts)
- .../rfmode\rftool_strokes.py
- 002 0507:extrude_c() new_face([a,b,c,d])
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- .../rfmode\rftool_strokes.py
- 004 0261:stroke() if self.replay: self.replay()
- .../rfmode\rfwidget_brushstroke.py
- 005 0056:modal_brushstroke() if self.stroke_callback: self.stroke_callback()
- .../rfmode\rfwidget.py
- 006 0189:modal() nmode = self.FSM[self.mode]()
- 007 0194:modal() raise e
- .../rfmode\rfcontext.py
- 008 0554:modal_main() if self.rfwidget.modal():
- 009 0469:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report @Syndaryl, and thanks for the .blend file.  I'll dig into this problem as soon as I can!

**Comment by jlampel** [comment]
This file appears to no longer throw an exception, so I'm assuming it's fixed. If you have trouble with this in the future please open a new issue and we'll take a look. Thanks!
