### ISSUE TITLE
"Apply scale" to origin object and changing View clip distance breaks retopoflow

### ISSUE THREAD

**Issue by felixleonhart** [CGCookie/retopoflow#631]
First issue: 
if you scale the origin object - everything is fine, but if you apply scale to the origin object - the selection of retopo verticies completely stops working (Right mouse click doesn't work)
scaleapplied - clip not changed.blend - selecting verts doesn't work
scalenotapplied - clip not changed.blend - everything works fine

Second issue:
changing view clip distance to higher values creates a buggy offset when exiting Retopo mode.
When you reenter into retopo mode the vertices are placed right, but if you exit they are offseted again.
scaleapplied.blend - selecting verts doesn't work + strange offset
scalenotapplied.blend - strange offset
Btw, unitscale is changed to 0.01 cause UE4 needs it

No other user plugins enabled
v2.79b
Retopoflow 2.0.0 and 2.0.1 

[blendfiles.zip](https://github.com/CGCookie/retopoflow/files/2397179/blendfiles.zip)

**Comment by aftamat4ik** [comment]
i fixed this issue by appending object from broken blend file to old one.

**Comment by jlampel** [comment]
All example files work fine, so this appears to have been resolved. Closing out. If you have this problem again, please open a new issue. Thanks!
