### ISSUE TITLE
Trouble with input and shortcuts.

### ISSUE THREAD

**Issue by superfalse** [CGCookie/retopoflow#634]
Using RetopoFlow 2 with Blender 2.79b. 

I have set Rotate View to Tweak-RMB-Any, Move View to Tweak-MMB-Any and I use CTRL-Tweak-RMB with all the several directions to change the viewport perspective (such as CTRL-Tweak-RMB-North for top view). All of these do not work when using the addon even though it does not seem to utilize these inputs for anything else (correct me if I'm wrong on this). I can see that it does make sense to disable or override certain actions that you wouldn't use during retopo anyway. But simply blocking anything seems like a really bad idea, especially if you're not given the possibility to change RetopoFlow's shortcuts.

Another confusing thing is that the ACTION button is always LMB and SELECT always RMB regardless of the actual individual Blender settings.

Other than that, this addon does look like a huge timesaver and I'd happily throw my money at you. ;)

**Comment by vxlcoder** [comment]
Thanks for the report, @superfalse.

Currently, RF uses its own keymaps, which do not align with your Blender keymaps.  Although it isn't very convenient, you can modify RF keymaps (see `keymaps.py` file in the root folder of the RetopoFlow add-on).  Keep in mind that these keymaps are very limited.

I'm going to close the issue for now, but know that we are planning to revisit this with Blender 2.80.

Please let us know if you have any other questions or issues!
