### ISSUE TITLE
ERROR WHILE COMPILING SHADER brushStrokeShader: Vertex shader was successfully compiled to run on hardware.

### ISSUE THREAD

**Issue by Visitorsama** [CGCookie/retopoflow#636]
Hello, I downloaded the version of Retopoflow 2.0 from Github, but I can not enable it in blender 2.79 the error that I get is the following.

`Read prefs: C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79
\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender\2.79\python
RetopoFlow Options path: C:\Users\Visitorsama\AppData\Roaming\Blender Foundation
\Blender\2.79\scripts\addons\retopoflow-master\RetopoFlow_options.json
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender\2.79\scripts\modules\addon_u
tils.py", line 331, in enable
    mod = __import__(module_name)
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\__init__.py", line 69, in <module>
    raise e
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\__init__.py", line 48, in <module>
    from .interface import (
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\interface.py", line 40, in <module>
    from .rfmode.rftool import RFTool
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\rfmode\rftool.py", line 36, in <module>
    from .rfwidget import RFWidget_Default
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\rfmode\rfwidget.py", line 36, in <module>
    from .rfwidget_brushstroke import RFWidget_BrushStroke
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\rfmode\rfwidget_brushstroke.py", line 26, in <modu
le>
    from ..common.shaders import brushStrokeShader
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\common\shaders.py", line 329, in <module>
    brushStrokeShader = Shader.load_from_file('brushStrokeShader', 'brushstroke.
glsl', checkErrors=False, bindTo0='vPos')
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\common\shaders.py", line 109, in load_from_file
    return Shader(name, srcVertex, srcFragment, *args, **kwargs)
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\common\shaders.py", line 128, in __init__
    logv = self.shader_compile(name, self.shaderVert)
  File "C:\Users\Visitorsama\AppData\Roaming\Blender Foundation\Blender\2.79\scr
ipts\addons\retopoflow-master\common\shaders.py", line 64, in shader_compile
    assert not log and 'was successfully compiled' not in log, 'ERROR WHILE COMP
ILING SHADER %s: %s' % (name,log)
AssertionError: ERROR WHILE COMPILING SHADER brushStrokeShader: Vertex shader wa
s successfully compiled to run on hardware.`

The specifications of my team are the following

AMD Athlon II x2 250 Procesor 3.0 GHz
4GB ram
Windows 7 64 bits
Radeon 3000 IGP
![cosa](https://user-images.githubusercontent.com/19819676/46366067-d1ce5600-c63f-11e8-8ce5-8ae28fd7983b.gif)

**Comment by vxlcoder** [comment]
Thanks for the report, @Visitorsama!

This issue should now be fixed in 87ae7fd.  Try pulling the latest version of `release/2.0.1` branch.

Let us know if you still have problems.

**Comment by vxlcoder** [comment]
This should be fixed now, so I'm going to close the issue.  Please reopen and let us know if you have any other issues with this.  Thanks!
