### ISSUE TITLE
Syntax error? Won't let me add to blender

### ISSUE THREAD

**Issue by Zoglow** [CGCookie/retopoflow#640]
<img width="880" alt="screen shot 2018-10-07 at 7 30 32 pm" src="https://user-images.githubusercontent.com/43863350/46588297-fbd0af80-ca67-11e8-9d48-fbeaf8d8768a.png">

Was having issues with the addon, so I tried re-downloading it. But now it won't let me add it to Blender...

**Comment by vxlcoder** [comment]
How did you download retopoflow? Did you get it from GitHub or from blender market? Which version of RF are.you using?

**Comment by Zoglow** [comment]
> How did you download retopoflow? Did you get it from GitHub or from blender market? Which version of RF are.you using?

I downloaded from the Blender Market, and I am using version 2.0. Also, it is only having problems on my macbook, on my windows desktop it works great.

**Comment by vxlcoder** [comment]
Thanks for the additional info, @Zoglow.
Have you tried installing to a fresh copy of Blender on your macbook?  We have had strange issues like this show up, where simply "starting over" with Blender fixed it for whatever reason.

**Comment by Zoglow** [comment]
I will try that, thanks!

**Comment by yvesbodson** [comment]
I just tried to install RetopoFlow v2.00 and got the same error .  I have tried to use both versions, from Blender market and GITHub.  I tried to install under Blender 2.79b and Blender experimental but same situation.

**Comment by yvesbodson** [comment]
In addition of difficulties to install your app, the link to documentation does not work anymore.. Just to mention it..

**Comment by yvesbodson** [comment]
Close the issue.  Reinstalling Blender did solve the issue..; d'ont know why but it works now.  Thanks

**Comment by Zoglow** [comment]
Worked for me too! Thanks!

**Comment by Zoglow** [comment]
Worked for me too! Thanks!

**Comment by Dikruzz** [comment]
> 

Same issue any solution?

**Comment by vxlcoder** [comment]
Hi @Dikruzz.  Can you post more details on the issue that you're having?  Which versions of Blender and RetopoFlow are you using?  Operating system?  where did you get RF from (GitHub, Blender Market, other?)?  etc.

The solution to OP's problem was to get a fresh copy of Blender and RetopoFlow.  However, this is an old issue, so your issue might be different.
