### ISSUE TITLE
selection

### ISSUE THREAD

**Issue by NuhanKhan** [CGCookie/retopoflow#641]
Retopoflow is not selecting the target as expected. it is not taking visible mesh.

**Comment by carter2422** [comment]
Can you please elaborate on what you mean by "not taking visible mesh" @NuhanKhan?

RetopoFlow 2 uses all visible, de-selected object(s) as the Source. Do not select anything when starting retopoflow unless you're trying to work with an existing low res object as the target.

**Comment by carter2422** [comment]
If it happens again please feel free to re-open this issue and let us know steps to replicate (or provide the .blend file for testing.)

Cheers!
