### ISSUE TITLE
Contour strip (and other input) visually turns solid - cannot see edges or vertices

### ISSUE THREAD

**Issue by rlawhill** [CGCookie/retopoflow#645]
![retopoflow 2 issue](https://user-images.githubusercontent.com/44275193/47180604-c896e780-d2d5-11e8-9166-9042aa6abf15.png)
I am new to this add-on so the error may be mine, but I am unable to find a solution.

Thank you

**Comment by rlawhill** [comment]
I see that this has been a problem for others as well when using a Mac, as I am.

**Comment by vxlcoder** [comment]
Thanks for the report, @rlawhill, and I'm sorry for my late reply!

Could you try the latest version of the `release/2.0.1` branch?  I've made some changes to that branch that _might_ fix this issue.

If you're still having problems, can you post a screenshot of the areas outlined in red in the image below?  I'm wondering if you have a different setting than I do.  Thanks!

![image](https://user-images.githubusercontent.com/3790699/48969120-1636fc00-efc8-11e8-91f5-8a2e560ce908.png)

**Comment by carter2422** [comment]
Great to hear @rlawhill!
