### ISSUE TITLE
Why does retopo flow not work with big models?

### ISSUE THREAD

**Issue by brunodemasi** [CGCookie/retopoflow#646]
Example: cylinder radius 60, height 330

**Comment by vxlcoder** [comment]
Retopoflow should work on any sites mesh.  It does temporarily rescale the mesh for technical reasons, then scale it back once you leave RF, but you might have found an interesting limitation. I'll check this out soon.

**Comment by brunodemasi** [comment]
I'm using Blender to create a model to 3D printer.
I can scale the object but I don't understand. WARNING: Source bbox is large!
This also happens with a simple cylinder.

**Comment by vxlcoder** [comment]
Ah. You can safely ignore that warning. In the latest version of RF (not released yet), that warning doesn't show anymore.

**Comment by brunodemasi** [comment]
great idea but retopo doesn't work

**Comment by brunodemasi** [comment]
ok. Thank you
