### ISSUE TITLE
Various errors (Contours and Polystripes)

### ISSUE THREAD

**Issue by AntonioCaroppos** [CGCookie/retopoflow#648]
I haven't been able to draw anything onto my 1mio poly object (no matter if Contours or Polystripes).
I also get a "Polycount is high!" warning.
It's Retopoflow designed to decimate a hi poly model?

A screenshot of the error is attached.

Is there any stable version that I could test? 
![error1](https://user-images.githubusercontent.com/29504639/47355261-37eb4d80-d6c1-11e8-96f3-8c332e9fd501.jpg)

**Comment by vxlcoder** [comment]
@AntonioCaroppos, it looks like you're trying to use the older version of Contours and Polystrips.  Be sure to uninstall any older versions of RF.  It might be good to uninstall, then reinstall the latest version of RF.

Also, in the new version of RF (2.0), you do not select the mesh you want to retopologize.  Instead, you either select the low poly count target mesh (if you have already started a retopo session) and then start one of the RF tools, or deselect all meshes to start a new RF session.  See the Quick Start Guide for more details.

Please let me know if this does not fix your problem.

Thanks!

**Comment by AntonioCaroppos** [comment]
Yes, that solved it. 
Thank you.

**Comment by vxlcoder** [comment]
You're welcome!

Closing the issue.
