### ISSUE TITLE
it Does not work when I click x-axis symmetry

### ISSUE THREAD

**Issue by gorani4989** [CGCookie/retopoflow#652]
When I check the x-axis matching function, the center line is drawn in the wrong place, as shown in the figure, and nothing works. help me

![question](https://user-images.githubusercontent.com/44567829/47638557-38dd1d00-dba2-11e8-8369-2f7469f9d773.png)

**Comment by vxlcoder** [comment]
Symmetry is based on the origin and rotation of your target.  If you want to move the symmetry plane, exit RF, and change the location and rotation of your target in the `n` panel so the origin of the target is at the "center" of your source.  Alternatively, you can move the source object.
