### ISSUE TITLE
Retopoflow Not Conforming to Surface

### ISSUE THREAD

**Issue by tdw46** [CGCookie/retopoflow#653]
### **Overview**
I am sculpting a face and it has relatively uniform topology. However, when using the retopflow tools, newly created vertices do not conform to the surface correctly, and they even change locations when exiting retopoflow and entering object mode or edit mode. No errors are thrown and restarting Blender doesn't fix the issue.

### **Screenshots, File, and Steps to Recreate**
**1)** Retopoflow seems to conform to most of the surface, but when I begin working around the mouth of the character pictured below is when the strange behavior begins. You will see in the file that regardless of which tool is used, the vertices do not conform to the original mesh's surface:
![screenshot 410](https://user-images.githubusercontent.com/10996763/47749993-b0738080-dc64-11e8-8f9c-b97b50b0b185.png)

**2)** When entering object/edit mode, however, the vertices do seem to conform properly.
![screenshot 411](https://user-images.githubusercontent.com/10996763/47750036-cf721280-dc64-11e8-9056-2b9188728d1d.png)

**3)** And yet, upon entering retopoflow again, the vertices are displaced from the surface—this time in entirely different locations than before.
![screenshot 412](https://user-images.githubusercontent.com/10996763/47750086-f3355880-dc64-11e8-80fc-3126cb6f2ece.png)

_These steps are repeatable around this area of my mesh, and you can loop between 2 and 3 infinitely with the same result._

### **FILE OF INTEREST** _NOT to be redistributed, re-used, or sold_
***FILE REMOVED DUE TO ADEQUATE ANSWER

**Comment by vxlcoder** [comment]
Thanks for the report, @tdw46. There are options under either view options or target rendering for adjusting how far the vertices are visually displaced from the surface while in RF. Note: the verts are actually snapped. Only their visualization is offset.

**Comment by tdw46** [comment]
@vxlcoder MUCH APPRECIATED! I was not aware of that visualization option, and I feel a bit dense now that I realize this is actually a great feature to include. Thanks for you quick response!

**Comment by vxlcoder** [comment]
You're welcome, @tdw46!

Closing this issue.
