### ISSUE TITLE
Bug on linux or my mistake?

### ISSUE THREAD

**Issue by brothermechanic** [CGCookie/retopoflow#654]
Hello
Want to rty this addon
Susses activeted but can't start to work
```
Traceback (most recent call last):
  File "/home/bm/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py", line 154, in invoke
    self.framework_start(context)
  File "/home/bm/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py", line 205, in framework_start
    self.ui_start()
  File "/home/bm/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rfmode.py", line 307, in ui_start
    RFRecover.save_window_state()
  File "/home/bm/.config/blender/2.79/scripts/addons/RetopoFlow/rfmode/rf_recover.py", line 76, in save_window_state
    open(filepath, 'wt').write(json.dumps(data))
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\name\\AppData\\Local\\Temp\\/RetopoFlow_backup.state'

location: <unknown location>:-1


```

**Comment by carter2422** [comment]
@vxlcoder any thoughts on this?

**Comment by vxlcoder** [comment]
Thanks for the report, @brothermechanic, and I'm sorry that I'm so late in replying!

It looks like the Blender temp folder is configured for Windows, but you're running Blender on Linux.

Try either loading factory settings or changing the temp folder directly in User Preferences > File.

![image](https://user-images.githubusercontent.com/3790699/48968818-0b2d9d00-efc3-11e8-81c2-f9ebac4668a9.png)

![image](https://user-images.githubusercontent.com/3790699/48968805-e6392a00-efc2-11e8-83ab-8b98a7f0f29a.png)

Please let us know if you are still having issues.

**Comment by vxlcoder** [comment]
Closing issue now, but reopen if you continue to have problems.

Thanks!

**Comment by brothermechanic** [comment]
@vxlcoder 
Thank you
You right, i copy blender config from my windows os, and have windows temp path!))))
Sorry
And thank you.
I will start to learn your addon now)
