### ISSUE TITLE
Low FPS with RetopoFlow 2.0.0 using Blender 2.79.0

### ISSUE THREAD

**Issue by nTiko** [CGCookie/retopoflow#655]
Platform: Windows 10.0.17134, AMD64, Intel64 Family 6 Model45 Stepping 7, GenuineIntel
GPU: NVIDIA GeForce GTX 1080/PCle/SSE2, 4.6.0 NVIDIA 388.13, 4.6 NVIDIA
Target: verts:0, edges:0, faces:0
Sources:  number:1, verts:1538, edges:4608, faces:3072
FPS: current:2.652739, threshold:5, time:10

I just trying it out on a simple cube subdivided.

**Comment by josuesevahc** [comment]
Enviado pelo meu Windows Phone
________________________________
De: nTiko<mailto:notifications@github.com>
Enviada em: ‎08/‎11/‎2018 14:09
Para: CGCookie/retopoflow<mailto:retopoflow@noreply.github.com>
Cc: Subscribed<mailto:subscribed@noreply.github.com>
Assunto: [CGCookie/retopoflow] Low FPS with RetopoFlow 2.0.0 using Blender 2.79.0 (#655)


Platform: Windows 10.0.17134, AMD64, Intel64 Family 6 Model45 Stepping 7, GenuineIntel
GPU: NVIDIA GeForce GTX 1080/PCle/SSE2, 4.6.0 NVIDIA 388.13, 4.6 NVIDIA
Target: verts:0, edges:0, faces:0
Sources: number:1, verts:1538, edges:4608, faces:3072
FPS: current:2.652739, threshold:5, time:10

I just trying it out on a simple cube subdivided.

**Comment by jlampel** [comment]
I'm closing this out because it's outdated, but if you have trouble with this in the future please open a new issue and we'll take a look. Thanks!
