### ISSUE TITLE
Friendlier documentation

### ISSUE THREAD

**Issue by TJYSunset** [CGCookie/retopoflow#665]
In request of @vxlcoder in #593:

+ [x] Add missing docs for tools other than contours in the built-in "Tool Help" panel.
  + It's frustrating when the built-in help section isn't complete at all.
+ [ ] Host text-and-image based, localizable documentation on somewhere like [Read the Docs](https://readthedocs.org/).
  + Most English learners are more skilled at reading than listening.<sup>[citation needed]</sup> YouTube's auto generated subtitles can be great, but it's usually funky when it comes to technical stuff. Plus, users in some parts of the world may find accessing YouTube difficult.
  + Better to use some l10n workflow simplifying service e.g. [Transifex](https://www.transifex.com/), which is the [recommended by Read the Docs](https://docs.readthedocs.io/en/latest/guides/manage-translations.html) and free for open source projects.
  + I can translate English to Simplified Chinese, if that helps.
+ [x] Have [the docs page on Blender Market](https://blendermarket.com/products/retopoflow#tab-docs) and the built-in help and/or welcome message pointed to the complete, localized documentation with a hyperlink.
+ [x] Briefly explain what the tool does on their button's tooltip.
  + Even the "Exit" button has a tooltip explaining what "exit" means...
    ![Screenshot of the exit button](https://user-images.githubusercontent.com/12986688/48986831-6b077d80-f154-11e8-8f28-4f63f4c1b821.png)
    Nothing wrong with that, but logically speaking, the tools should also have one.
+ [x] Stylize key strokes in built-in help.
  + ["Studies have been conducted on the readability and legibility of all caps text. Scientific testing from the 20th century onwards has generally indicated that all caps text is less legible and readable than lower-case text."](https://en.wikipedia.org/wiki/All_caps) Stylizing key strokes instead like <kbd>Shift</kbd>, or even better, <kbd>⇧ Shift</kbd>, would greatly improve readability.
  + If that's impossible due to Blender's limits, at least ditch all caps.
+ [x] Align keystroke-usage pairs in built-in help.
  + Also improves readability. By align I mean something more like a table:
    ![Demonstration](https://user-images.githubusercontent.com/12986688/48987386-41048a00-f159-11e8-8fc0-1fc677646fec.png)
    Tab characters should do it for proportional fonts.

**Comment by vxlcoder** [comment]
Thanks for the proposal, @TJYSunset!  Your suggestions head the RF community in a constructive direction.

Just a couple of notes:

- All of the tools have built-in help, and the tool help is context sensitive.  So, you must first select the tool, then press F2 or press Tool Help
- We plan to put the docs for 2.x online.  We did have 1.x docs available, but they no longer apply.  With the built-in help, the online documentation lowered in priority and seemed a bit redundant.  Further, we do plan to make video tutorials with the new RF.  We just haven't made it that far, yet.
- The tooltips do need updated.  Thanks for the reminder!
- We could use help in translating the docs.  Unfortunately, we know only English (and my English is quite poor as it is).  Any help would be great!
- Stylized and aligned keys: absolutely!  The UI system (basically everything that is drawn once you start RF) is custom code, and a hack at that.  I never finished the table UI element, which would easily solve the alignment problem.  And for stylized keywords, I just need a smarter text layout system that handles non-text UI elements (text layout is a very hard problem... even robust internet browsers and document editors get it wrong frequently)

I'll start in on some of these items as soon as 2.0.1 is officially released.

Thanks again for your help!

**Comment by TJYSunset** [comment]
> you must first select the tool, then press F2 or press Tool Help

That's... counterintuitive. A better implementation would be *putting everything in one page* (or separate pages with a navigator like [chm](https://en.wikipedia.org/wiki/Microsoft_Compiled_HTML_Help)) and *jump to the currently selected tool* on opening Tool Help.

> With the built-in help, the online documentation lowered in priority and seemed a bit redundant.

One important thing to note is the current built-in help will have accessibility problems. While it's sensible to assume zero visually impaired people would happens to be a RF user, this built-in help lacks *selecting and copying* feature, and *might not properly implemented accessibility apis*.

You might wonder who that'll help - one case is English learners. Free copying allows fast pasting into online machine translation services, and some dictionary-like software may have automatic translate feature utilizing accessibility apis to get text in the active window.

Browser-based docs generally don't have this problem, as long as the webpage isn't using some quirky method to render the text or disable selecting/copying with javascript/css.

**Comment by vxlcoder** [comment]
All help docs are now accessible through the help system without needing to change tools. see commit 915a80c

**Comment by vxlcoder** [comment]
Key mappings in help docs are aligned using a table in commit b927221.

**Comment by carter2422** [comment]
Unless I'm mistaken we can now close this @vxlcoder ?

**Comment by jlampel** [comment]
I'll keep this open as I'd still like to have online documentation, or at least have a text based version available in the download so the user can have it off to the side while working
