### ISSUE TITLE
Completely lost.  Contours do not work.  Still have to explore the other tools, but so far, no luck.

### ISSUE THREAD

**Issue by Goran-M** [CGCookie/retopoflow#675]
I don't know what I'm doing wrong.  Object selected in object mode.  Press Contours Tab.  Get the floating pop ups, dark background, but mesh goes from object mode into edit mode, with really thick wireframe.  CTRL Left mouse click draws the green dotted line, but nothing happens after I let go.  I watched videos on this, and everything I see in the videos does not happen to my mesh.  I've worked in Blender since 2.49B and I'm on 2.79 now.

**Comment by Goran-M** [comment]
Just wow.  I'll just crawl back to my Blender cave.  I knew I missed something.  Works perfectly.  Many thanks!

**Comment by carter2422** [comment]
No problem! Happy blending.
