### ISSUE TITLE
Hovering retopo-mesh. No mesh- tweaking possible

### ISSUE THREAD

**Issue by LunarOrbiter77** [CGCookie/retopoflow#676]
Good evening there. First of all i have to say that english is not my native language, So please be patient with my writing and feel free to ask if something isn't clear. 

I updated from Retopoflow 1.x to 2.0.2 from within Blender 2.79b. and i tried to retopologize a simple spherical source object to get used to the handling of RF2. The issue is,  that everytime my generated mesh is hovering way above the surface of the source object. It doesn't really matter, which tool i use  (contours, polystrips etc.). With this offset, it's not possible for me to tweak the geometry in any way, because by moving it around, its snapping goes very weird.  As soon as i click onto a handle to adjust the geometry, it bends and twists like crazy. For better understanding, i have added some screenshots (see below). 

For my configuration please see screenshot added. Video Driver is newest (Version 417.22)
I am using two Monitors -> ASUS ROG PQ27A (Primary) and ASUS ROG PG278Q (Secondary)

I would be very happy for some help here cos i am stuck at the moment. 

Thanks in advance and greeting to you from Germany.

LunarO.
![configuration](https://user-images.githubusercontent.com/45736558/49748951-5d4f0d80-fca7-11e8-9e9d-1299399c6b27.PNG)
![retopoflow2 0 schwebende geometrie 1](https://user-images.githubusercontent.com/45736558/49699733-18f33d00-fbd5-11e8-9271-3e6ed1887610.PNG)
![retopoflow2 0 schwebende geometrie 2](https://user-images.githubusercontent.com/45736558/49699739-26102c00-fbd5-11e8-8e9c-520f2e00ba61.PNG)
![retopoflow2 0 schwebende geometrie 3](https://user-images.githubusercontent.com/45736558/49699741-3cb68300-fbd5-11e8-85a6-684ad6d47632.PNG)

**Comment by carter2422** [comment]
@LunarOrbiter77 can you please try two things for me:
1. Apply the Scale and Rotation on your source object in Object Mode by pressing CTRL+A > Apply Scale. 
2. Adjust the *Normal Offset* under Target Rendering of the Options panel. 

Let me know if either of those work!

**Comment by LunarOrbiter77** [comment]
With _Normal Offset_ to 0 and after grabbing a Handle for adjustment:
![witrh normal offset 0ed](https://user-images.githubusercontent.com/45736558/50101344-c9d78880-0222-11e9-849b-00d17319689b.PNG)

**Comment by vxlcoder** [comment]
hmmm... any chance you could upload the .blend file so I can inspect?

(Thanks for the images!  they are helpful!)

**Comment by LunarOrbiter77** [comment]
Hi vxlcoder . For shure. 

https://www.fastshare.org/download/Pulley_Trus..7z

I hope it works.

Regards...

**Comment by vxlcoder** [comment]
Got it!

Ok.  I'm not sure what the cause is quite yet, but a workaround is to not use orthographic projection.  For some reason, the PS handles are not intersecting the surface correctly when using orthographic projection.

Will be taking a look at this issue soon.

**Comment by LunarOrbiter77** [comment]
Hi vxlcoder. 
That's damn great man. Not using orthographic view is not a big problem. But what i get is so great. 

Thank you so much and have a nice christmas over there.

Best Regards!

PS:
Maybe its not a question you can answer. But i would like to know if i can find a video tutorial for RF 2.0 somewhere. I remember this great tutorial for RF 1.0 by Jonathan.

**Comment by jlampel** [comment]
The orthographic projection issue seems to be solved in v3.0, but if you have this problem again please open a new issue. Thanks! Also, a tutorial for v3 will be coming
