### ISSUE TITLE
I cannot slide, rotate nor shift selected loop or edge in contours mode.

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#678]
Hello, I noticed I cannot slide, rotate nor shift selected loop or edge in contorus mode. I press G, S or shift+S with edge or loop selected (ctrl + select), but nothing happens.

**Comment by SavMartin** [comment]
I have same problem with ver 2.02 , but no always, and with a simple sphere to retopo never happens..

**Comment by vxlcoder** [comment]
@Lewiatan45 or @SavMartin, can you post a .blend file where this issue occurs?  I cannot reproduce this bug.

**Comment by Lewiatan45** [comment]
@vxlcoder
I'm unable to upload 4.6GB blend file in reasonable timeframe.

I noticed later it's inconsistant issue. Once I can get things to work, another time I can't. Only in the one case I can rotate loops in 100% of times, when loop displayes numbers of verticles with yellow number.

**Comment by SavMartin** [comment]
I have read this issues : https://github.com/CGCookie/retopoflow/issues/677 , and I think I have to try to see if the problem comes from the size of the object .. 
If it still fails, I'll send you the .blend file

**Comment by SavMartin** [comment]
Being in spelling mode was the problem, in a perpective way, it always works.

**Comment by SavMartin** [comment]
Be in orthographic mode was the problem,In perpective mode, it's perfect.

**Comment by carter2422** [comment]
I'm finally looping back around to this issue (thanks for your patience!). It's my understanding @SavMartin that you're only experience problems when in orthographic mode. Is that correct?

**Comment by jlampel** [comment]
Closing this out due to lack of activity. I'm not able to replicate the problem, but if you experience it again, especially in v3.0+, please report it as a new issue. Thanks!
