### ISSUE TITLE
Cannot increase / decrease vertex count in Contours Tool

### ISSUE THREAD

**Issue by Copperplate** [CGCookie/retopoflow#679]
Shift+Middle Mouse Up / Down does nothing, = / - does nothing, and the shortcut + / - buttons in the options panel does nothing. I tried this in 2.79b as well as a daily build, same issue. Symmetry on / off does not make a difference. Thanks.

-Adam

**Comment by Copperplate** [comment]
Shift+Middle Mouse Up / Down does is pan the interface.

**Comment by Copperplate** [comment]
Thanks SavMartin for your suggestion. The issue occurs both in perspective and orthographic mode for the Contours Tool. Other tools work fine for their shortcuts to increase count (except the shift+middle mouse wheel shortcut seems to have been removed in Retopoflow 2.0), but the Contours Tool definitely has a bug a present.

**Comment by vxlcoder** [comment]
Thanks for the report, @Copperplate, and I am sorry that I've been slow to respond!

Can you post a screenshot of when you try to change the counts?

Can you change the counts when you make the very first cut? For example, I started with a default cube, made a single cut to create a loop with 16 vertices, then I pressed the `-` key to reduce the count to 8 (note: not the numpad `-`, but the `-` between the `0` and `BACKSPACE` on the top row of the keyboard).

![image](https://user-images.githubusercontent.com/3790699/50223668-dfa39580-0369-11e9-80cc-5775e1cec5ad.png)

**Comment by Copperplate** [comment]
Hi Jon, no problem. The count can be changed on the very first cut, but not afterwards. Attached is the .blend file, a very lame test sculpt, as I wanted to test the add-on on a high-res mesh (p.s. having access to the project files on the CG Cookie Retopoflow Introduction course would be very helpful for newcomers to follow along, despite the course not using RF 2.0). :-) Thanks for checking on this.


[Snake Sculpt_01.zip](https://github.com/CGCookie/retopoflow/files/2698895/Snake.Sculpt_01.zip)

**Comment by carter2422** [comment]
We don’t yet have support for adjusting more than the first cut. This is on our wishlist but hasn’t yet been implemented. 

And I agree, a full intro course is needed and we are trying to get it done!

Cheers!

**Comment by Copperplate** [comment]
I see; thanks Jonathan for your reply. I did not realize that, as the video on CG Cookie shows the count being adjusted at any time (@4:15): https://cgcookie.com/lesson/using-contours 

Is there a way to download the previous version of Retopoflow that had this ability? This was one of the reasons I purchased Retopoflow...

**Comment by carter2422** [comment]
Sure thing @Copperplate! Here's a zip of the previous version that's shown in the old course:
[RetopoFlow-v1.3.2.zip](https://github.com/CGCookie/retopoflow/files/2699721/RetopoFlow-v1.3.2.zip)

**Comment by Copperplate** [comment]
Hi Jonathan, thanks so much for the link. I tried it out, and it certainly works a lot better (the vertex resampling works good, and the UI is smaller and less intrusive). Unfortunately, I'm using the emulate 3 button mouse mode in Blender (because I don't like the feel of my middle mouse button), and whenever I pan with Alt+LMB, Retopoflow 1.3.2 throws a major exception error and lines of code, then if I move again, my viewport goes completely black. More black screens if I try to slide a loop when two separate (un-connected) contour sections have been made.

Both versions of Retopoflow look very powerful, but at this point, I sadly don't envision myself using it. I'm actually preferring the familiar feel of working with Blender's built-in retopology tools and shortcuts... as limiting as they may be. :-) Not sure if it's possible to get a refund or store credit (I bought it Nov 26, 2018 from the Blender Market), but didn't download it until Dec 10). My Order ID: 199250

To remain legal, I would be sure to permanently delete both versions of RF off of my PC. Thanks so much for your understanding and apologies for any inconvenience. Maybe someday I'll be ready for this add-on. :-)

Sincerely,
Adam Janz
