### ISSUE TITLE
Running Polystrips is significantly faster on the second run

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#68]
For some reason Polystrips starts significantly faster on the second run. This is only noticeable on high-poly objects, but in these cases it's a matter of 2-3 second delays on the initial start. 

Something somewhere is getting cached, created, or otherwise references on subsequent runs. No idea what it is.

If we can track this down, it'd be preferable to make the delay happen upon mesh generation rather than the beginning (if possible).

**Comment by patmo141** [comment]
I think we can close this.  Any delay on first run of PS or Contours is seems to be inherent to the cost of generating the bmesh and bvh and are as fast as the API and user system allow.

**Comment by carter2422** [comment]
Agreed.
