### ISSUE TITLE
The retopoflow freezes Blender every 2 minutes during retopology. 

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#680]
Hello,

I began retopology of my model and I noticed retopoflow freezes my Blender regurarly every 2 minutes. The hourglass icon appears, then disappears and everything freezes. After some time Blender stars to respond with choppy framerate and it starts to run faster and faster till it reaches 60 fps. I had the task manager turned on when that issue occures and I didn't see higher CPU usage than 19% and RAM usage than 39%. The blend file is 4.6 GB with 60 mln poly model.

Specs:
I7 6700k 4.4 Ghz, Gtx 1080, 48 GB RAM DDR4 3000 Mhz CL 15. The blend file is on SSD.
I'll post detailed specs later. 

By the way is there a place where feature suggestion can be posted?

**Comment by vxlcoder** [comment]
The pause could be due to auto save. You can try turning it off to see if that helps with the pausing. Setting is in blender options (RF auto save looks at blender's auto save settings)

**Comment by vxlcoder** [comment]
As for feature requests, you can open a new issue, but we might not get to it soon (still working on some other bugs and getting a version compatible with blender 2.80)

**Comment by Lewiatan45** [comment]
I'll give it a try and let you know if that helps. 

Thanks, I'll make one.

**Comment by Lewiatan45** [comment]
@vxlcoder Turning off autosave solved the issue.
