### ISSUE TITLE
Suggestion: the Improvment of selection mechanics. 

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#681]
Hello, 
my suggestion is to change way verts/edges/faces are selected. 

In Blender edit mode when you press C, the circle appears and you use it to mark what you want in one of 3 togglable modes (vert/edge/faces). I found retopoflow way of selection (RMB click) really unresponsive and unrealiable, because retopoflow doesn't interpretate what I want to select correctly. I hover over the verticle, RMB click, but the edge is selected. I hover over the edge, RMB click, but the face is selected. The lack of togglable selection that we know from Blender edit mode make results random.

**Comment by carter2422** [comment]
Hi @Lewiatan45, 

It sounds to me like something is behaving incorrectly; selection should not be that inconsistent or difficult. It's intended to work very closely to Blender's default. 

Can you try applying the scale and rotation on both the source and target objects and then trying selection in RetopoFlow again?

**Comment by SavMartin** [comment]
Hi, @carter2422 , for version 2.80 of Blender, it will change this way of selecting and action,cause Blender's default will be left click Select and action.. ??

**Comment by Lewiatan45** [comment]
@carter2422 It's inconsistent because the retopoflow decides on its own how to interpret your selection. In Blender edit mode you toggle things that you want to select. Such mechanics in retopoflow are missing so, in the end, it does pick up the wrong things. Quite often I have to click around the verticle to select it for example. I worked on a model with the applied scale of the mesh and retopoflow mesh.

**Comment by carter2422** [comment]
I'm closing this in favor of #568. We've always wanted to have native selection support, such that RetopoFlow directly follows the Blender config. 

Doing our best to make it happen!
