### ISSUE TITLE
Retopoflow very low performance when mirror of target mesh is turned on.

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#684]
Hello, 

My source high poly model is 60 mln polygons. The target retopo mesh at this moment is 5400 polygons without mirror turned on. However, as soon as I turn mirror on, the performance of the program becomes so terrible to the point it takes over a few seconds to zoom out with scrolling.

In the task manager, I noticed whenever I try to do anything with mirror turn on, GPU usage increases to 67%. CPU to 19% and memory to 57%. I should have enough power to use mirror without problems.

**Comment by carter2422** [comment]
Hi @Lewiatan45, is it possible your source model has a mirror on it? 

If not could you possibly share the model you're working with so we can test it?

**Comment by carter2422** [comment]
In that case the issue is almost certainly due to your source being 60 million polygons. Unfortunately this is much higher than we can reasonable support within Blender while keeping the tools interactive. 

Can you try decimating the source, applying the decimate, and then checking the symmetry performance again?

**Comment by Lewiatan45** [comment]
Blender doesn't like what I want to do with decimate, so It'll take some time before it catches up.

**Comment by Lewiatan45** [comment]
@carter2422 I halved polycounts of source high poly model with decimate. Now I have 7,70 fps with retopoflow mirror turned on in a small window, with maximised window 8.08 fps. It's smooth enough to use it to relax polygons. CPU usage: 19% Memory usage: 65% GPU usage: 27% So there is still some power left that retopoflow could use.


I think I'll go around with low framerate by doing retopology on lower poly source mesh and then copy and paste it to blend file with a high poly model to bake normal maps.
