### ISSUE TITLE
(<class 'TypeError'>)

### ISSUE THREAD

**Issue by seagullinfinity** [CGCookie/retopoflow#686]
Hello, the tools are pretty amaising:) Thank you for your work! 
-I don't know if this is important, but when I thought I was using contours brush, and later I saw that it was the strokes brush, I was dragging through a mesh (leg) just like I would with contours brush, and this is what happened:

Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 7, 6.1.7601, AMD64, Intel64 Family 6 Model 42 Stepping 7, GenuineIntel
- GPU: ATI Technologies Inc., AMD Radeon HD 6450, 4.5.13399 Compatibility Profile Context 15.200.1062.1004, 4.40
- Timestamp: 2018-12-23 02:23:34.062075
- Undo: extrude strip, extrude strip, create strip, grab, grab, grab, select, select, grab, grab

Error Hash: 272ad85124035e75c34b593a0d9252bf

Trace:

- EXCEPTION (<class 'TypeError'>): faces.new(...): expected (BMVert), not 'NoneType'
- .../rfmode\rfmesh.py
- 000 1367:new_face() bmf = self.bme.faces.new(verts)
- .../rfmode\rfcontext_target.py
- 001 0412:new_face() return self.rftarget.new_face(verts)
- .../rfmode\rftool_strokes.py
- 002 0681:extrude_strip() self.rfcontext.new_face([prev[i+0], cur[i+0], cur[i+1], prev[i+1]])
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- .../rfmode\rftool_strokes.py
- 004 0261:stroke() if self.replay: self.replay()
- .../rfmode\rfwidget_brushstroke.py
- 005 0056:modal_brushstroke() if self.stroke_callback: self.stroke_callback()
- .../rfmode\rfwidget.py
- 006 0189:modal() nmode = self.FSM[self.mode]()
- 007 0194:modal() raise e
- .../rfmode\rfcontext.py
- 008 0577:modal_main() if self.rfwidget.modal():
- 00

**Comment by vxlcoder** [comment]
Thanks for the report, @seagullinfinity!

I was able to reproduce this error when there is a hole in the source.  Commit b082e44 in branch `issue/686` fixes this by generating as much geometry as possible.

![image](https://user-images.githubusercontent.com/3790699/50524630-df5f7480-0aa4-11e9-8605-67afb7dccd74.png)

![image](https://user-images.githubusercontent.com/3790699/50524638-e8504600-0aa4-11e9-8b26-0bcfb53599da.png)
