### ISSUE TITLE
Is it possible somehow to use these tools to build my original mesh?

### ISSUE THREAD

**Issue by MostHated** [CGCookie/retopoflow#695]
These tools are great, so great that I wish I could use them when building my original mesh. I was just trying to work with the default PolyBuild tool and it is terrible compared to yours. Is there some way to use them to work on existing meshes without building over them?

**Comment by carter2422** [comment]
Unfortunately not; the tools rely on a source object to project onto. I'm glad you like the tools, though!

**Comment by MostHated** [comment]
Understood. I definitely want to toss out a feature request if at least even just the poly building tool you guys have could be adapted to work normally and released as a standalone item. I would gladly pay like $5-8 or so for that.

**Comment by carter2422** [comment]
We'll take that to heart! Thanks for the suggestion.
