### ISSUE TITLE
Cursor goes bonkers

### ISSUE THREAD

**Issue by Ingapambi** [CGCookie/retopoflow#697]
After using for 2-3 minutes the cursor becomes an hour glass that rapidly flashes (2-4 flashes/sec); and often  in contours or pol pen the stroke is not connected to the previous one.

**Comment by carter2422** [comment]
@Ingapambi can you provide some details on the source objects you're working with, such as the total polycount?

**Comment by Ingapambi** [comment]
Details forgotten the last 10 days but yes, several dialogs regarding low fps were present and the poly count was between 200k and 550k depending on the model. Occurs on both 5yr old laptop and iMac Pro.
Thankyou for following up on this.
John 

    On Wednesday, February 6, 2019, 6:53:10 AM PST, Jonathan Williamson <notifications@github.com> wrote:  
 
 
Most likely this is related to #448

**Comment by carter2422** [comment]
Thanks @Ingapambi. We're trying to solve these performance issues and are making some progress but it's a slow process.

**Comment by carter2422** [comment]
Given the extensive changes in the upcoming Blender 2.8 version of RetopoFlow I'm assuming this issue will no longer be relevant and thus closing the issue. If it occurs in 2.8 then of course we can re-investigate.
