### ISSUE TITLE
Can't add Retopoflow

### ISSUE THREAD

**Issue by 0George0** [CGCookie/retopoflow#698]
Hi there, I wanted to try Retopoflow before buying, but I can't install it. I'm using today's Blender build and the Retopoflow download from here. I renamed the download to just "retopoflow" and re-zipped, but I get an error saying "upgrade to 2.8x required" - can anyone help me get it working? Thanks.

**Comment by carter2422** [comment]
Be sure you're grabbing the `master` branch @0George0 https://github.com/CGCookie/retopoflow

**Comment by 0George0** [comment]
Ah, I'm using 2.8. When will you have support? Thanks for your quick reply.

**Comment by carter2422** [comment]
We are working on it now but it's a very complicated upgrade and so it may take a bit longer.

**Comment by 0George0** [comment]
Okay, I'll come back to it when you're ready. Thanks for your help.
