### ISSUE TITLE
Strokes: Assert Error!

### ISSUE THREAD

**Issue by theoldben** [CGCookie/retopoflow#700]
Bridging two edge loops with the Stroke Tool. 4 Verts on each side, drew a connecting stroke, that worked, when I reduced the number of in-between segments, ka-boom.
-------------------------------------

```
Environment:

- RetopoFlow: 2.0.2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 970/PCIe/SSE2, 4.6.0 NVIDIA 399.24, 4.60 NVIDIA
- Timestamp: 2019-02-06 12:38:43.435068
- Undo: extrude C, select, select, select, select, select, select, tweak move, tweak move, tweak move

Error Hash: d3b4bfb6628a2b27ec16220570dfe963

Trace:

- EXCEPTION (<class 'AssertionError'>): 
- .../rfmode\rftool_strokes.py
- 000 0450:extrude_c() assert bmv0 and bmv1
- .../rfmode\rftool.py
- 001 0076:wrapper() ret = fn(*args, **kwargs)
- .../rfmode\rftool_strokes.py
- 002 0200:modal_main() self.replay()
- .../common\profiler.py
- 003 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0579:modal_main() self.tool.modal()
- 007 0494:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
Thanks for the report, @theoldben.  I have looked into this, but I could not replicate your exact issue.  I think it has to do with duplicate verts (two vertices at the same location), but I'm not sure.  I've made some changes in commit ba074d0 that _should_ take care of this issue.  If you find that these changes didn't correct the issue (or cause other issues), feel free to report this along with a `.blend` file that causes it, and I'll take another look at it.  Thanks!
