### ISSUE TITLE
Amateur Mistakes

### ISSUE THREAD

**Issue by abre0** [CGCookie/retopoflow#702]
I don't know what is actually happening but it's my first time using Retopoflow and seems like everything is wrong.
![blender c__users_henrique abreu_documents_projetos_3d_projetos_rosa navalha_rosah blend 09_02_2019 13_15_42](https://user-images.githubusercontent.com/47479441/52522474-02b53c00-2c6d-11e9-9d6d-b4550f482176.png)
This is my actual mesh
![blender c__users_henrique abreu_documents_projetos_3d_projetos_rosa navalha_rosah blend 09_02_2019 13_15_12](https://user-images.githubusercontent.com/47479441/52522479-0cd73a80-2c6d-11e9-8595-3391ebed33aa.png)
And this is how it looks in Retopoflow. And I have no Pen to use omg i'm totally lost

**Comment by vxlcoder** [comment]
Sorry that I'm just now getting to this, @abre0 .

When starting RF, the selected the object is considered the target object (low-resolution, nice topology version of your high-resolution, messy model).  This is useful for continuing retopo work.  If you're starting a new retopo session, deselect everything first, then start a tool.  This will create a new target.

In either case, all other visible meshes (not active and selected) is treated as a source object.

See the Quick Start Guide for more information (topmost button in the RF panel).

**Comment by vxlcoder** [comment]
closing this issue for now, but please let us know if you have any other issues.
