### ISSUE TITLE
Retopo tools are  not working at all?

### ISSUE THREAD

**Issue by LightSkyStudios** [CGCookie/retopoflow#703]
None of the tools do anything when clicked
![screenshot 61](https://user-images.githubusercontent.com/44513285/52833963-4974bd00-30d7-11e9-8648-b95a23432484.png)

**Comment by vxlcoder** [comment]
@LightSkyStudios : the action controls are bound to CTRL+LMB.  Holding the CTRL button, you should see a visualization change in some of the tools.
Please see the General Help for more information.
Let us know if you have any other questions!

**Comment by LightSkyStudios** [comment]
Thanks so much! i thought it was a glitch cause i couldn't see it written anywhere lol.

**Comment by vxlcoder** [comment]
closing this issue.  please let us know if you have any other issues!
