### ISSUE TITLE
COULD NOT FIND PYTHON PACKAGES

### ISSUE THREAD

**Issue by Rvbds** [CGCookie/retopoflow#704]
Hi, i am using Blender on Linux Mint and when I install the Retopoflow Add On I receive this message. I used this same file of Retopoflow on Windows and it worked well.

![captura de tela em 2019-02-16 11-25-14](https://user-images.githubusercontent.com/47692389/52900579-c048ad80-31de-11e9-9709-b864f3a84bf4.png)

**Comment by vxlcoder** [comment]
If you install blender through the Linux mint repos/apt manager/etc., it probably uses your system's python install. This means that you can either install numpy through your package manager, or you can try downloading blender from blender.org which comes with python and the needed python modules. Let us know if you have anymore questions!

**Comment by Rvbds** [comment]
I installed Numpy and it worked, thank you
