### ISSUE TITLE
Cannot select anything when using different scene units

### ISSUE THREAD

**Issue by Lexeon** [CGCookie/retopoflow#706]
In scene properties, when setting the units to something such as metric with a size of 0.01, nothing can be selected. Cannot click onto vertices, faces, and even strips. If the clip start is set to 100, then objects can sometimes be selected when zoomed far out. Spamming the right mouse button while slowly zooming out shows that some zooms work properly.

I have also noticed that when using polystrips, trying to create a strip that merges with another fails to merge the end of the new strip and the desired face, instead they are both separate strips that overlap.

**Comment by vxlcoder** [comment]
Thanks for the report, @Lexeon.  I'm unable to find the right combinations of setting to replicate this issue.  Can you post a `.blend` file where this issue shows, so that I can see what you're seeing?  Also, which version of RF do you have installed?  Thanks!

**Comment by carter2422** [comment]
Closed for inactivity.
