### ISSUE TITLE
Keys/Shortcuts changeable?

### ISSUE THREAD

**Issue by dman317** [CGCookie/retopoflow#708]
Hey! :)

Is it possible to change the shortcuts and if no, are there any plans to make them changeable?

Thanks!

**Comment by vxlcoder** [comment]
Right now, we don't have a very convenient way to change the keymaps, but you can certainly change them by modifying the code.  Specifically, open the `keymaps.py` file located in the root of RetopoFlow add-on folder (also, see https://github.com/CGCookie/retopoflow/blob/release/2.0.3/keymaps.py).  In there is a dictionary (`default_rf_keymaps`) that contains a human-readable action (ex: `select`, `undo`) with a corresponding key or mouse input (ex: `RIGHTMOUSE`, `CTRL+Z`).  Most of the tools use the `action`, `action alt0`, and `action alt1` actions to do their main operation, but some have special operations (ex: Contours has loop shift).  Other more complicated things like click+drag might not get captured in this simple set up, though.

In the future, we hope to make a more convenient UI to do this, but this is it for now.

**Comment by vxlcoder** [comment]
although this issue is on our TODO list, I'm going to close this issue for now, because a solution will likely change depending on what happens with Blender 2.80.  Please let us know if you have any other questions!

**Comment by dman317** [comment]
Thanks for the answer!
