### ISSUE TITLE
RetopoFlow 2.0.3 is unusably slow (related to #448)

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#710]
We have had an ongoing performance bug on some machines.  I _think_ we might have this fixed for most cases, but there are still some people that are seeing this issue.

We have opened a GitHub issue to collect details on this issue (#448), but that thread has become long, and it's difficult to know which of the issues have been resolved and which are still outstanding.  So, we are starting a new issue thread.

If you're seeing the low FPS warning, please consider reporting your machine's specs, the poly counts for your source(s) and target, and any additional context (ex: tools used, actions performed) that might help us debug this issue.  If possible, please consider uploading your `.blend` file here, so that we can take a look at it.

Thanks!

**Comment by tasteless63** [comment]
Its the first time I try to use RetopoFlow, could not get it to work so far (speed, etc,). I tried the free version with much more effort and would like to breathe the full functionality now! ;) Greeez TT
Details:

- RetopoFlow: 2.0.2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2080/PCIe/SSE2, 4.6.0 NVIDIA 411.70, 4.60 NVIDIA
- Target: verts:1271, edges:2520, faces:1250
- Sources: number:95, verts:66111, edges:196377, faces:129994
- FPS: current:2.878382, threshold:5, time:10

**Comment by vxlcoder** [comment]
@tasteless63, can you try installing the latest version of RetopoFlow (2.0.3). It looks like you're still using the previous version.

**Comment by OldSalty** [comment]
Same problem, happens mostly at late stage of retopolgy making the the work crawl to a halt, and some cases corrupted the blend file. 

Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.7 blender2.7 2019-03-20
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1080/PCIe/SSE2, 4.6.0 NVIDIA 417.22, 4.60 NVIDIA
- Target: verts:1741, edges:3437, faces:1694
- Sources: number:1, verts:34320, edges:102967, faces:68652
- FPS: current:5.001607, threshold:2, time:15

**Comment by vxlcoder** [comment]
Thanks for the info, @OldSalty.

Are you able to post the .blend file that is causing this? Does it show down if you "retopo" the default cube? I'm wondering if it is a specific seeing that is causing the slowness.

Thanks!

**Comment by OldSalty** [comment]
I can't share the blend file, but I I can try another mesh. I had a lot of problems with selecting from certain view angles and not being able to zoom in on selection. May be related to scene scale or model size vs camera clipping. I just use defaults for blender and import the obj from zbrush.

**Comment by vxlcoder** [comment]
I understand, @OldSalty.

Another option to see if it's a particular setting in your `.blend` file is to add in a shape to the scene with exactly the same vertex positions (roughly), scale, rotation, and translation, then delete all of the other data in the file (not just high- and low-res meshes), and then post that .blend file.  To ensure that the new mesh is exactly the same:

- duplicate the high-res mesh, and give it a nice generic name
    - this will keep the transformations (scale, translation, rotation)
- edit the duplicate mesh
    - select and delete all vertices
    - add a cube, Suzanne, or any other shape (while still in edit mode)
    - scale the new geometry to be the same size as the original mesh (while still in edit mode)
    - this will position the vertices in roughly the same location as the original with respect to the transformations
- now, delete all other objects
    - in the outliner with "All Scenes" selected, delete everything even if it's not on visible layer or selected scene (see image below)
    - also, unlink any textures, materials, text blocks, etc. that might be under NDA or the like.  you can check that nothing is secretly revealed by using the "Data Blocks" view in the outliner (see image below)

![all scenes](https://user-images.githubusercontent.com/3790699/54883933-55277200-4e41-11e9-9abd-b47dc47ad3be.png)

![data blocks](https://user-images.githubusercontent.com/3790699/54884022-38d80500-4e42-11e9-8270-2633b864451a.png)

**Comment by aquaraider11** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 Unknown Unknown
- Platform: Linux, 4.18.0-16-generic, #17-Ubuntu SMP Fri Feb 8 00:06:57 UTC 2019, x86_64, x86_64
- GPU: X.Org, AMD Radeon R9 200 Series (HAWAII, DRM 3.26.0, 4.18.0-16-generic, LLVM 7.0.0), 4.5 (Compatibility Profile) Mesa 18.3.3 - padoka PPA, 4.50
- Target: verts:473, edges:892, faces:420
- Sources: number:1, verts:11492, edges:39257, faces:27867
- FPS: current:0.077508, threshold:2, time:15

**Comment by vxlcoder** [comment]
Thanks for the report, @aquaraider11. Does blender run well normally? Can you try RetopoFlow on the default cube after loading blender factory settings to see if it's a setting? Can you post your .blend file or a screenshot?

**Comment by OldSalty** [comment]
[Retopoflow_LowFPS.zip](https://github.com/CGCookie/retopoflow/files/3051423/Retopoflow_LowFPS.zip)

Sorry it took me a while, I just had to finish the commission job before I went back to resolve the issues

**Comment by theDankReaver** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1050/PCIe/SSE2, 4.6.0 NVIDIA 425.31, 4.60 NVIDIA
- Target: verts:1507, edges:3029, faces:1520
- Sources: number:5, verts:2504238, edges:7511636, faces:5007431
- FPS: current:1.951822, threshold:2, time:15

**Comment by Shyki13** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, Intel64 Family 6 Model 158 Stepping 12, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 2080 Ti/PCIe/SSE2, 4.6.0 NVIDIA 425.31, 4.60 NVIDIA
- Target: verts:563822, edges:1691460, faces:1127640
- Sources: number:6, verts:3396, edges:9908, faces:6520
- FPS: current:0.002103, threshold:2, time:15

**Comment by vxlcoder** [comment]
@Shyki13, I think you have your source and target swapped. Be sure to read the quick start guide (top button on RetopoFlow panel). Please let me know if this fixes your issue. Thanks!

**Comment by Cariaga** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 750 Ti/PCIe/SSE2, 4.6.0 NVIDIA 430.64, 4.60 NVIDIA
- Target: verts:26089, edges:76139, faces:50072
- Sources: number:1, verts:7667, edges:19746, faces:12188
- FPS: current:0.067838, threshold:2, time:15

**Comment by vxlcoder** [comment]
Thanks for the report, @Cariaga. When you started RF, did you have the correct low-poly target mesh selected? 50k faces for target and 12k faces for high-res source mesh doesn't seem right.

**Comment by jonbragado** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, Intel64 Family 6 Model 79 Stepping 1, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1070/PCIe/SSE2, 4.6.0 NVIDIA 417.22, 4.60 NVIDIA
- Target: verts:32, edges:46, faces:15
- Sources: number:1, verts:63596, edges:170483, faces:107512
- FPS: current:0.269071, threshold:2, time:15

**Comment by sbstratos79** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1050 Ti/PCIe/SSE2, 4.6.0 NVIDIA 430.86, 4.60 NVIDIA
- Target: verts:1368, edges:2674, faces:1306
- Sources: number:1, verts:1604, edges:4812, faces:3208
- FPS: current:0.188841, threshold:2, time:15

**Comment by Dadstruction** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2017-09-11
- Platform: Darwin, 18.6.0, Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64, x86_64, i386
- GPU: ATI Technologies Inc., AMD Radeon Pro 575 OpenGL Engine, 2.1 ATI-2.9.26, 1.20
- Target: verts:82493, edges:247552, faces:165061
- Sources: number:1, verts:1057, edges:2795, faces:1732
- FPS: current:0.619811, threshold:2, time:15

Seemed fine until I switched away, and then came back to it after making a minor changed to the mesh is sculpt mode in a region that I had not yet created a retopo for.

**Comment by deock90** [comment]
Same problem:

Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 1050 Ti/PCIe/SSE2, 4.6.0 NVIDIA 430.64, 4.60 NVIDIA
- Target: verts:332037, edges:995153, faces:663144
- Sources: number:1, verts:482, edges:1440, faces:960
- FPS: current:0.008074, threshold:2, time:15

**Comment by AlainViesca** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.7 blender2.7 2019-05-23
- Platform: Windows, 10, 10.0.18362, AMD64, Intel64 Family 6 Model 45 Stepping 7, GenuineIntel
- GPU: NVIDIA Corporation, Quadro M2000/PCIe/SSE2, 4.6.0 NVIDIA 431.02, 4.60 NVIDIA
- Target: verts:269370, edges:791524, faces:522033
- Sources: number:1, verts:6884, edges:17516, faces:10755
- FPS: current:0.046517, threshold:2, time:15

**Comment by ensoreus** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Darwin, 18.6.0, Darwin Kernel Version 18.6.0: Thu Apr 25 23:16:27 PDT 2019; root:xnu-4903.261.4~2/RELEASE_X86_64, x86_64, i386
- GPU: ATI Technologies Inc., AMD Radeon Pro 580 OpenGL Engine, 2.1 ATI-2.9.26, 1.20
- Target: verts:514568, edges:1537667, faces:1023078
- Sources: number:1, verts:1092, edges:3264, faces:2176
- FPS: current:0.056502, threshold:2, time:15

**Comment by XhnPLayer** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 960/PCIe/SSE2, 4.6.0 NVIDIA 431.60, 4.60 NVIDIA
- Target: verts:64, edges:96, faces:32
- Sources: number:1, verts:728, edges:2178, faces:1452
- FPS: current:0.054802, threshold:2, time:15

**Comment by grapa2** [comment]
Details:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 10, 10.0.17134, AMD64, Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 980M/PCIe/SSE2, 4.6.0 NVIDIA 431.60, 4.60 NVIDIA
- Target: verts:69114, edges:207336, faces:138224
- Sources: number:1, verts:222, edges:558, faces:336
- FPS: current:0.008616, threshold:2, time:15

**Comment by carter2422** [comment]
Given the extensive changes to RetopoFlow in Blender 2.8 I'm closing this issue to try and keep everything relevant. Should the issue persist in 2.8 upon release (any time now) then we will start a new issue.
