### ISSUE TITLE
Retopo create the mesh inside instead of outside the model

### ISSUE THREAD

**Issue by esciron** [CGCookie/retopoflow#711]
As i say in the title, when i try to use the tools it creates the geometry inside the model instead of outside where the normals are pointing to.

https://imgur.com/IEqL49w

https://imgur.com/MTSYMnV

**Comment by vxlcoder** [comment]
Thanks for the report, @esciron.  Can you confirm that the normals of the source mesh are pointing outward?

**Comment by esciron** [comment]
> 
> 
> Thanks for the report, @esciron. Can you confirm that the normals of the source mesh are pointing outward?

It seems that i messed up my normals and i didn't notice afterwards, sorry for wasting your time :_(

**Comment by vxlcoder** [comment]
I'm glad to hear that the normals were the problem, and it wasn't something introduced in latest update!

Thanks for following up!  Let us know if you have any other problems.
