### ISSUE TITLE
Can't see target mesh

### ISSUE THREAD

**Issue by Crux628** [CGCookie/retopoflow#712]
![image](https://user-images.githubusercontent.com/48577855/54406716-13e2e400-4716-11e9-99de-3162cf004d03.png)

Hi. I can't see my target mesh when I'm using RF. As you can see in the picture I'm using PolyStrips, the curve is there but I can't see the mesh, same goes to all tools. Also all I can see is that vertices in the origin of source mesh. But when I exit RF the target mesh is there like nothing happened, the only problem is I can't see target mesh when working inside RF. Is this because of my PC or I missed something on the settings?

![image](https://user-images.githubusercontent.com/48577855/54406838-9b305780-4716-11e9-9fbe-6e5fdadd4423.png)

**Comment by kapawlak** [comment]
Are your normals pointing in the right direction? I've had this issue before and it turns out for whatever reason my normals got flipped when importing a mesh from 2.8 into 2.79 and retopoflow put my verts under the surface.

**Comment by vxlcoder** [comment]
I think @kapawlak  is correct looking at the edit mesh.  try flipping the normals on your source mesh.  Let us know if that doesn't work, though.

**Comment by vxlcoder** [comment]
Also, @Crux628, I'm sorry that I missed this issue!  I was _really_ busy around mid-March, so this unfortunately slipped below the fold, and I haven't had time to go back through all the issues.

**Comment by edandy126** [comment]
I have this same issue with retopoflow. I have searched and searched the internet for the solution until i found this here. Kindly pls guide me as i am inexperience with blender . Exactly, the same my retopoflow 2.0.3 cant see target. it shows as shown by @crux628. EVEN ON NEW MESH. imean on the default cube.

**Comment by vxlcoder** [comment]
@edandy126, can you post a screenshot when trying to use RetopoFlow with the default cube? You might also try loading factory settings.

**Comment by edandy126** [comment]
yes please, thanks for the promt response
![retopo1](https://user-images.githubusercontent.com/52508854/60620981-7bf82b80-9dd4-11e9-9e54-adce3bc281bd.png)
![retopo2](https://user-images.githubusercontent.com/52508854/60620991-80244900-9dd4-11e9-8305-7145ddd806e8.png)

**Comment by edandy126** [comment]
It was very slow before but removing meta cap stabilised it BUT i still have this issue here

**Comment by vxlcoder** [comment]
Did you try loading factory settings in Blender?

**Comment by edandy126** [comment]
I have reloaded factory setting several times. And sometimes it still bring out the issue of low FPS
![retopo3](https://user-images.githubusercontent.com/52508854/60621574-ecec1300-9dd5-11e9-83c9-ecca96b4910e.png)

**Comment by edandy126** [comment]
The above screen shot is after factory reset in blender

**Comment by vxlcoder** [comment]
I'm not sure why it's not showing.

Can you post your machine's specs?  (ex: windows version, processor, ram, video card, video driver, etc.)

Also, did RetopoFlow ever work correctly for you, then suddenly not?  Or has it never worked?

**Comment by edandy126** [comment]
It has never worked. I really loved it
![retopo4](https://user-images.githubusercontent.com/52508854/60622189-97186a80-9dd7-11e9-87a0-36599bc36e31.png). I left if for some time, and it brought this back

**Comment by edandy126** [comment]
![retopo5_ mSystem info](https://user-images.githubusercontent.com/52508854/60622632-b06de680-9dd8-11e9-86d5-0dd55bc6cd1f.png)
My system Information

**Comment by edandy126** [comment]
![retopo5_ mSystem info png2 png](https://user-images.githubusercontent.com/52508854/60622917-54579200-9dd9-11e9-803d-3c88f3b4cdca.png)
Systeminfo2

**Comment by vxlcoder** [comment]
Just curious, but does the latest build of Blender 2.80beta work OK on your machine?

**Comment by edandy126** [comment]
No

**Comment by edandy126** [comment]
I tried it once, it failed. have not tried it since

**Comment by vxlcoder** [comment]
What does not work with b280?  Are there things missing visually, does it runs very slowly, does it crash, ...?

I'm wondering if your machine is a little too underpowered.  Both RF and the new Blender 2.80 are computationally heavier than just Blender 2.79.

**Comment by edandy126** [comment]
Thank you so much. The beta 2.8 when it was install was unsuccessful. it showed the below sreen shot.
![retopo error](https://user-images.githubusercontent.com/52508854/60624670-cdf17f00-9ddd-11e9-9d1c-c3cfaccca085.png)

**Comment by carter2422** [comment]
@edandy126 thanks for your patience. The last screenshot appears to be an issue with the 2.8 build you were running. 

Please try using the official Blender 2.80 or 2.81 install. 

We are aiming to have a beta of RetopoFlow for 2.8 anytime now, at which point I'd ask you to try again. 

In the meantime I'm closing this issue so that we can stay focused on 2.8 issues.

**Comment by KofiAidoo** [comment]
I had the same problem and what @vxlcoder says about our hardware being not so powerful to use the Retopoflow addon is true. Even Blender 2.8x doesn't work on my machine. So I went on to download the Opengl work around from here https://www.rexoweb.com/2019/09/how-to-run-blender-2-8-without-graphics-card.html?m=1

To my amazement when you do same for Blender 2.79 with OpenGl work around file, Retopoflow works flawlessly and the target meshes are visible in the retopoflow mode. Try it out @edandy126

**Comment by RexoWeb** [comment]
> I had the same problem and what @vxlcoder says about our hardware being not so powerful to use the Retopoflow addon is true. Even Blender 2.8x doesn't work on my machine. So I went on to download the Opengl work around from here https://www.rexoweb.com/2019/09/how-to-run-blender-2-8-without-graphics-card.html?m=1
> 
> To my amazement when you do same for Blender 2.79 with OpenGl work around file, Retopoflow works flawlessly and the target meshes are visible in the retopoflow mode. Try it out @edandy126

**The Url is Changed**

Here Correct Post Url: [](https://www.rexoweb.com/how-to-run-blender-2-8-without-graphics-card.html)

**Comment by vxlcoder** [comment]
First, please take caution any time you download, install, and/or run anything from the internet, especially when downloading from a 3rd party source.  This also applies to Blender add-ons like RetopoFlow.

Second, we are not planning to confirm whether the workaround solution linked above actually works.

The linked article states that using a different OpenGL / graphics driver implementation (Mesa, for example) could work around the issue of not having a graphics card + graphics driver that is capable of running Blender.  This is a valid point, as there are software-only rendering systems that are capable of doing 3D graphics without a dedicated graphics card, albeit at a much lower framerate and possibly with fewer features.  Without testing, I'm just not sure how effective this option is for this case or whether it can be done by simply dropping in a binary.  Really it all depends on how Blender links to the driver.  Note: Mesa drivers are already available on most Linux distributions, and you can download the source directly from mesa3d.org and build it for your system (whether windows, linux, or mac).  The linked site is seemingly providing links to pre-built binaries.
