### ISSUE TITLE
Syntax Error: invalid syntax 

### ISSUE THREAD

**Issue by Nodir250699** [CGCookie/retopoflow#714]
Hi, could someone help on fixing this? " PBR material converter" add-on is not working properly. Everytime I reopen Blender i have to remove addon and again install from files in order to make it work... Thanks a lot in advance !
![Error](https://user-images.githubusercontent.com/40915589/54837192-9b68be00-4ce7-11e9-99b7-fedf1a0ff20f.png)

**Comment by vxlcoder** [comment]
@Nodir250699, I'm not sure how to help, since we didn't develop the PBR material converter add-on, and RF _shouldn't_ affect other add-ons.  Where did you get it from?

**Comment by Nodir250699** [comment]
https://3d-wolf.com/products/textures.html. From this website... I am sorry I accidently contacted wrong place I think

**Comment by vxlcoder** [comment]
That's OK.  I just didn't know how to help with your issue.  I thought that maybe you thought that RF was interacting incorrectly with that add-on.  Feel free to reopen the issue if there is something we can do to help!
