### ISSUE TITLE
My retopoflow tools can not be used.  edit: Local View prevents RF buttons from working

### ISSUE THREAD

**Issue by bluppies** [CGCookie/retopoflow#715]
so i just got the addon an started working on my hard surface mesh but the tools wont allow me to click here is the file if you need
![image](https://user-images.githubusercontent.com/49387755/55703061-512a5100-59f8-11e9-8ff8-fb8ed34ccd39.png)

**Comment by vxlcoder** [comment]
Hi @bluppies.

Please read the quick start guide, the button near the top of the RetopoFlow panel.  You either need to unselect all (to create new retopo mesh) or select the retopo mesh to continue working.

Let us know if you have any other problems

**Comment by bluppies** [comment]
i know i that but even when i deselect i m not allowed to use the tool
![image](https://user-images.githubusercontent.com/49387755/55728378-adf72d00-5a33-11e9-9a2e-6d873639207e.png)
could you try my blend file andd look for the issue

**Comment by vxlcoder** [comment]
Ah, sorry. I missed that. That is strange. Also, the list of sources is much smaller than the number of meshes in scene. Will take a look and get back to you. Thanks for sharing the blend file.

**Comment by bluppies** [comment]
thank your sir

**Comment by vxlcoder** [comment]
ok. you're in local view mode, so things act differently.  notice that you don't see the view layers in the 3D view toolbar (see images below).  To exit local view, press the numpad `/` key.  then, you _should_ be able to use RF.

![image](https://user-images.githubusercontent.com/3790699/55766060-ccaff080-5a40-11e9-9677-ae0f8f049bfe.png)
![image](https://user-images.githubusercontent.com/3790699/55766068-d76a8580-5a40-11e9-9b54-fb8143c89563.png)

**Comment by bluppies** [comment]
Thanks man it finally worked

**Comment by vxlcoder** [comment]
My pleasure!  that issue has come up many times, and it's difficult to figure out (partly because this is a Blender design decision that I think is not helpful).  perhaps we should add a "switch out of local view mode" note in the RetopoFlow panel....
