### ISSUE TITLE
Keybindings for Retopoflow 2.0.3 on BForArtists 1.0.0

### ISSUE THREAD

**Issue by longearsdesign** [CGCookie/retopoflow#716]
Issue: I am able to get Retopoflow 2.0.3 working fine on a clean version of Blender, but not for bforartists 1.0.0. Having to relearn Blender w/o BForArtists would probably be a deal-breaker for me.

Setup:
My input bindings: [myBindings.py.txt](https://github.com/CGCookie/retopoflow/files/3061483/myBindings.py.txt)
My active Add-Ons: ![AddOns](https://user-images.githubusercontent.com/30812968/55843695-6681a700-5aee-11e9-979e-dd2a50f212bd.png)

Issue detail:
1. Under Contours, I cannot RClick to Select an Edge; work-around with A (deselect all) and Shift-RClick.
2. [Shift] Ctrl+RClick selects as expected... usually. But then it will stop working for a while, for no apparent reason.
3. S, G, and Shift-S do not work at all. Except when Shift-S decides to work.
4. -/= do not appear to work, but I may be using it wrong?
5. Under Polystrips, RClick to select doesn't work. Shift-RClick often selects the poly on the opposite side for no good reason. I cannot get the rest of the tool to work either.
6. I stopped here.

Also: Being able to dock the Tool Help dialog as I learned these tools would have made this SO much easier as a new user. Going back and forth between the Tool Help and the functional UI to attempt each unmemorable combo was a big headache.

**Comment by longearsdesign** [comment]
I have friends pushing me to move over to zbrush, which apparently also has retopology. And a sizeable price tag. I have too much time already invested in Bforartists to give up quite yet though, especially since Retopoflow is exactly what I'm after.

I will try to identify exactly what add-ons are getting in the way, by disabling them, and then adding them back individually. I'll share my findings.

**Comment by vxlcoder** [comment]
Thanks for the report, @longearsdesign. I am not familiar with bforartists, but I will check it out. Also, thanks for the useful settings, etc!

**Comment by longearsdesign** [comment]
I don't know how many bforartists users there are, but in short, it's a fork of Blender that:
(1) "fixes" a lot of issues with the UI that make it frustrating for new users, most notably overriding Blender's implementation of LClick vs RClick
(2) hides/disables many of the options and shortcuts Blender offers OOTB, assuming that advanced users will re-enable the features they need.

For me, Bforartists made Blender a useable product.

**Comment by longearsdesign** [comment]
Got some diagnostics for you!

1. I am running BForArtists v1.0.0. BForArtists is explained, and can be obtained, here: https://www.bforartists.de
![BForArtists_Version](https://user-images.githubusercontent.com/30812968/55927885-7f13bf00-5bcb-11e9-8503-3af373e92d41.png)
(There is a BForArtists v2 in alpha, but Retopoflow isn't recognized as a viable add-on, possibly due to a version difference? It was worth a try.)

2. Disabled all other addons.
![BForArtists_NoOtherAddOns](https://user-images.githubusercontent.com/30812968/55927886-7f13bf00-5bcb-11e9-9519-7859242c1856.png)

3. Unbound everything from the "S" button.
![BForArtists_SButtonUnbound](https://user-images.githubusercontent.com/30812968/55927881-7e7b2880-5bcb-11e9-8665-9477e01827e0.png)

3a. An export of the remaining bindings:
[BForArtists_Bindings.py.txt](https://github.com/CGCookie/retopoflow/files/3066740/BForArtists_Bindings.py.txt)

4. Created a topology mesh over a mannequin, in the Contours tool. Some features respond, but "S" and "G" do nothing.
![BForArtists_Contours_SGButtonTest](https://user-images.githubusercontent.com/30812968/55927884-7e7b2880-5bcb-11e9-8c5b-3eceacdcdd56.png)

5. I hope this info is helpful. My alternative is dropping BForArtists entirely, which is a real shame, because I loathe Blender's OOTB controls, and I've never managed to configure LClick & RClick so they work intuitively for me.

**Comment by longearsdesign** [comment]
After some googling, I see the Blender 2.8 alpha is quite stable, and they "fixed" a lot of the things that irritated me so much in the Blender UI. So my reason for using BForArtists in the first place no longer applies. I can just use 2.8 OOTB!

Thank you, and please feel free to close this ticket.

**Comment by carter2422** [comment]
Thanks for the followup @longearsdesign! We're aiming to have our RetopoFlow for 2.8 beta out anytime now. Stay tuned!
