### ISSUE TITLE
Keymapping

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#718]
- [x] expose keymap to user
- [x] ability to bind to specific blender keys
- [x] ability to bind to specific rf keys

**Comment by 3DEsprit** [comment]
In the same vein, will documentation dynamically show the assigned keys for each core and tool function?

I ask, because it looks like changing the keymap to one of the other built-in maps (Max, Maya) throws off the hotkeys (e.g. Fill key using Max map). _It looks like this is also the case with #595_

**Comment by vxlcoder** [comment]
that's a great idea, @3DEsprit, one that's on my list of to-dos.

one important note for right now: RF has its own keymap, which is (mostly) independent of Blender's keymap (actually, the navigation stuff _should_ work, but the actions are fully independent)

after RF is fully released, "use blender keymaps for actions", including LMB/RMB select, is one of my top items to work on

**Comment by xan2622** [comment]
> [ ] expose keymap to user

For this task, maybe you could take a look at the source code of the [Bezier Utilities](https://github.com/Shriinivas/blenderbezierutils) or [qBlocker](https://blenderartists.org/t/qblocker-for-blender-2-8/1146607) addons? 

Both addons have this feature and makes it very easy to know what hotkeys do (and which hotkeys are available). There is also an option (in the Addon preferences) to show (or not) these hotkeys.

Bezier Utilities also come with some options to set the font size and font position on the viewport, as well as some lines of code to only display the _hotkeys overlay_ on the biggest viewport (very convenient, especially if the user has one main viewport and several ones on the side of his/her screen for other Left/Right/Top views).

![fb07e40c5e1e59f106b4a2c39f501732f2b5cb1d](https://user-images.githubusercontent.com/1732773/75098360-7b0b4880-55b5-11ea-9caa-cd0c9df6e9a6.gif)

**Comment by jlampel** [comment]
Custom keymapping is now in 3.1.1
