### ISSUE TITLE
Selection problem

### ISSUE THREAD

**Issue by Stotch228** [CGCookie/retopoflow#720]
Hi! The selection does not work if I am close to the ref object, if I have zoom up its working well. This is not such a critical problem, but if possible, correct it in the updates.
![image](https://user-images.githubusercontent.com/50520876/57570291-f32ec600-7408-11e9-8b98-426167680dbe.png)

**Comment by Stotch228** [comment]
Actually, this is an nasty problem. Any tips?

**Comment by grimakaka** [comment]
I support, the selection works very badly. This bug negates the advantages of this wonderful tool! The retopology becomes very painful!

**Comment by Stotch228** [comment]
> I support, the selection works very badly. This bug negates the advantages of this wonderful tool! The retopology becomes very painful!

and selection through the object, it is generally a disaster. But the tool is really good and optimized. Maya and 3dCoat can't eat 2 million polys without lagging.

**Comment by grimakaka** [comment]
> > I support, the selection works very badly. This bug negates the advantages of this wonderful tool! The retopology becomes very painful!
> 
> and selection through the object, it is generally a disaster. But the tool is really good and optimized. Maya and 3dCoat can't eat 2 million polys without lagging.
It is strange that everyone is silent about it. I do not believe that this problem only we have two. I wrote to the author of this tool but he, too, is silent!

**Comment by vxlcoder** [comment]
Thanks for the report, all. Sorry I haven't responded immediately, as I am finishing up my term at the University. I will be focused on RF development starting tomorrow, and so I will be addressing these issues directly soon. Sorry for inconvenience.

In the meantime, @Stotch228, would you mind posting a .blend file that has these problems? I have not had an issue on any of our test files, so your set up is something new. Thanks!

**Comment by Stotch228** [comment]
> Thanks for the report, all. Sorry I haven't responded immediately, as I am finishing up my term at the University. I will be focused on RF development starting tomorrow, and so I will be addressing these issues directly soon. Sorry for inconvenience.
> 
> In the meantime, @Stotch228, would you mind posting a .blend file that has these problems? I have not had an issue on any of our test files, so your set up is something new. Thanks!

Hi! Ty for your answer! I hope your business with the university is well. My blend file - https://drive.google.com/file/d/13SG6uK57y6fNMTJaYZt08jcwgZjqL0ZH/view?usp=sharing

**Comment by vxlcoder** [comment]
Thanks, @Stotch228, for the file!

I've made a tweak to internal parameters in the selection code, so it is easier to select geometry when closer to the source.  If you can, please check out the issue/720 branch to see if that corrects the problem.  Let me know if you need help with this.

**Comment by vxlcoder** [comment]
noticed that selection in orthographic mode is still sketchy.  working on this now

**Comment by vxlcoder** [comment]
ok, I found one other bug in the visibility code that is fixed now (commit c95b77d).  i tried several times to replicate the bug that @grimakaka recorded about an hour ago on issue #724, but have not been able to reproduce it now.  can you give that a try now?

![trouble replicating](https://user-images.githubusercontent.com/3790699/58433959-5fefc480-8087-11e9-91db-4f436fc28bc9.gif)

**Comment by Stotch228** [comment]
> Thanks, @Stotch228, for the file!
> 
> I've made a tweak to internal parameters in the selection code, so it is easier to select geometry when closer to the source. If you can, please check out the issue/720 branch to see if that corrects the problem. Let me know if you need help with this.

Hi! The issue with close range picking fixes, now working at 9/10. 
The second issue that I described earlier, with the picking poly through the ref object, was due to an open object. After i closed it, there was no problem. Great thx for fixing, your tool is really nice. 
![image](https://user-images.githubusercontent.com/50520876/58535122-c4309680-81f5-11e9-879e-77cbdb0b9b3c.png)
