### ISSUE TITLE
Snapping through ref geometry?

### ISSUE THREAD

**Issue by Stotch228** [CGCookie/retopoflow#723]
Is it possible to turn off transperent snapping?
![image](https://user-images.githubusercontent.com/50520876/57973527-cd7a6180-79b2-11e9-8c37-8a36b2d97bae.png)
![image](https://user-images.githubusercontent.com/50520876/57973531-d8cd8d00-79b2-11e9-903b-bee961afbd7f.png)

**Comment by carter2422** [comment]
@Stotch228 apologies for missing this. Snapping like this can be fine-tuned with the Clip Start/End settings while RetopoFlow is running. Additionally you can enable *Cull Backfaces* to further help.
