### ISSUE TITLE
Selection Distances not matched to Blender unit settings

### ISSUE THREAD

**Issue by solosails** [CGCookie/retopoflow#727]
If units in Blender set to mm, the selections distances do not work, if it were possible to add a decimal selection distance this may solve the issue, but as you can't it appears to stop selection from working so the user must be in the default metres unit for the plugin to work as expected.

(awesome tools by the way -  thanks.

**Comment by carter2422** [comment]
Thanks for the suggestion @solosails. Working with different types of units in Blender is quite tricky. 

That being said, the upcoming Blender 2.8 version of RetopoFlow has full decimal support in numeric inputs 👍

**Comment by solosails** [comment]
Thanks!
