### ISSUE TITLE
PolyPen: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by Rcott** [CGCookie/retopoflow#728]
![RetopoFlow_screenshot](https://user-images.githubusercontent.com/40922389/60398369-46bdb600-9b14-11e9-98a0-42ecbeabda22.png)
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.Below are a few notes that will help us in fixing this problem.

- Provide as much information as you can so that we can reproduce the problem and fix it.
- Screenshots and .blend files are very helpful.
- Change the title of this bug report to something descriptive and helpful.

Thank you!

Just trying to remove a line...
```
Environment:

- RetopoFlow: 2.0.3
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, AMD64 Family 21 Model 2 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GT 740/PCIe/SSE2, 4.6.0 NVIDIA 430.86, 4.60 NVIDIA
- Timestamp: 2019-06-30 08:49:18.090528
- Undo: insert, grab, select, select, select, select, select, grab

Error Hash: 741b4c3badafc0a70ae2426d7b6bf633

Trace:

- EXCEPTION (<class 'ValueError'>): faces.new(verts): face already exists
- .../rfmode\rfmesh.py
- 000 1382:new_face() bmf = self.bme.faces.new(verts)
- .../rfmode\rfcontext_target.py
- 001 0414:new_face() return self.rftarget.new_face(verts)
- .../rfmode\rftool_polypen.py
- 002 0322:modal_insert() bmf = self.rfcontext.new_face([bmv0, bmv1, bmv2])
- .../rfmode\rftool.py
- 003 0076:wrapper() ret = fn(*args, **kwargs)
- 004 0110:modal() nmode = self.FSM[self.mode]()
- 005 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 006 0581:modal_main() self.tool.modal()
- 007 0496:modal() nmode = self.FSM[self.mode]()
```

**Comment by carter2422** [comment]
@Rcott apologies for missing your report before and thanks for reporting it. This issue should no longer be present in the Blender 2.80 branch, which we are working on getting ready for beta anytime now. 

If it happens again once the 2.8 version is released please let us know!
