### ISSUE TITLE
Help Text jitters during Middle Mouse navigation events if mouse is over

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#73]
When using **MMB** to navigate, anytime the mouse is over the model then the help text jitters. This includes SHIFT+MMB, CTRL+MMB, CTRL+MMB.

http://cl.ly/ZC0s

If zooming with Wheelup/down or if the help is collapsed then there's no jitters.

**Comment by vxlcoder** [comment]
@carter2422 is this still an issue?  i cannot reproduce it.

**Comment by carter2422** [comment]
I can no longer replicate this either @vxlcoder. Closing.
