### ISSUE TITLE
How does this makefile file work, and how do you execute it?

### ISSUE THREAD

**Issue by DarthMoulByte** [CGCookie/retopoflow#730]
How does this makefile file work, and how do you execute it?
does this build the zip to install in blender?
![image](https://user-images.githubusercontent.com/24207840/60855284-b0029080-a1c8-11e9-82b7-a99b00dcd592.png)

**Comment by vxlcoder** [comment]
The makefile is a config file for GNU Make, a programming tool used to perform actions. This makefile does create a zip that blender can install... It is how we create zip files for BM. If you can get make installed on your machine, just run `make build` to create a zip file. Note: the makefile is tested to run on Linux and OSX, so if you're running Windows ymmv. We would be happy to accept a PR if you can get it working correctly on a Windows machine.

**Comment by DarthMoulByte** [comment]
ok, just one question, I would need you to help me by answering some of the occasional questions outside of here and so I could do this task to contribute to guimp, I am not someone who spends it asking every 3 minutes, I only ask when I am without more options to create a solution, then if you help me in this way I can do it, doing it alone without knowing the necessary gimp in questions of code and scripting would be like putting a blind man to paint straight lines on a highway [Unofficial DISCORD GIMP](https://discord.gg/Q3Unk33) because this is where I started recently to put my gimp ideas, to develop solutions for my family

**Comment by DarthMoulByte** [comment]
> The makefile is a config file for GNU Make, a programming tool used to perform actions. This makefile does create a zip that blender can install... It is how we create zip files for BM. If you can get make installed on your machine, just run `make build` to create a zip file. Note: the makefile is tested to run on Linux and OSX, so if you're running Windows ymmv. We would be happy to accept a PR if you can get it working correctly on a Windows machine.
I will try, but I hope that my lack of experience in this field will be compensated by your occasional help when I get stuck in something that I do not know how to solve, surely I will be assisted or occasionally occasioned with my questions, I will be able to do it and I will gladly donate this I work in the community, since I have relived many joys of everything I have taken from GNU software, yes, I am currently working with windows, although 90% of my time is GNU with linux

Thank you, and I look forward to your support response for advice occasionally to achieve this goal.
