### ISSUE TITLE
PolyStrips: Unhandled Exception Caught!

### ISSUE THREAD

**Issue by mynameisdido** [CGCookie/retopoflow#731]
Please tell us what you were trying to do, what you expected RetopoFlow to do, and what actually happened.
Provide as much information as you can so that we can reproduce the problem and fix it.
Screenshots and .blend files are very helpful.
Also, change the title of this bug report to something descriptive and helpful.
Thank you!

-------------------------------------

```
Environment:

- RetopoFlow: 2.0.2
- Blender: 2.79.0 master 2018-03-22
- Platform: Windows, 10, 10.0.17763, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 1080/PCIe/SSE2, 4.6.0 NVIDIA 431.36, 4.60 NVIDIA
- Timestamp: 2019-07-21 01:06:21.657519
- Undo: move grabbed

Error Hash: 11fe08aec24056eeeb7e571a8715a2dd

Trace:

- EXCEPTION (<class 'AttributeError'>): Vector addition: (NoneType + Vec2D) invalid type for this operation
- .../rfmode\rftool_polystrips.py
- 000 0452:modal_move() set2D_vert(bmv, xy + delta)
- .../common\profiler.py
- 001 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 002 0076:wrapper() ret = fn(*args, **kwargs)
- 003 0110:modal() nmode = self.FSM[self.mode]()
- 004 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 005 0579:modal_main() self.tool.modal()
- 006 0494:modal() nmode = self.FSM[self.mode]()
```

**Comment by carter2422** [comment]
@mynameisdido apologies for not replying to this earlier and thank you for the report. This issue should no longer be relevant due to most everything being re-written for Blender 2.8. 

We are releasing a beta anytime now. If you see new issues once that is released then please let us know.
