### ISSUE TITLE
Twisted Contours 

### ISSUE THREAD

**Issue by MSCreationAndMore** [CGCookie/retopoflow#732]
Hello there :

i have issue with twisted contours ... why this happen 

![Capture](https://user-images.githubusercontent.com/36688285/62214503-770fa300-b3a5-11e9-812c-11f9f800b8d0.JPG)

**Comment by MSCreationAndMore** [comment]
i tested version 1.3.2 i have no issue but why all new versions have the same issue with me

**Comment by vxlcoder** [comment]
All of the tools were rewritten from scratch to make use of the new RF (2.0) system.  This rewrite is unnoticeable for some tools, but the behavior has changed for others.  Unfortunately, Contours has a few new quirks that still need ironed out (this is one of them).  I plan to revisit each tool once I get RF working in Blender 2.80.

In the meantime, can you post a video of how you created that mesh, @MSCreationAndMore?  There might be a simple workaround, depending on your workflow.

**Comment by MSCreationAndMore** [comment]
thank you so much for quick respond and for this great tool, sure i would love to give you a feedback GIF,if you need video for better quality please inform me  .

version 1.3.2 "work great"

![01](https://user-images.githubusercontent.com/36688285/62230767-ca441e80-b3c2-11e9-92a2-ed042d32f6c5.gif)

version 2.0.3 "Twisted"

![02](https://user-images.githubusercontent.com/36688285/62231010-65d58f00-b3c3-11e9-8552-51f006d54b23.gif)

**Comment by vxlcoder** [comment]
These will work great!

Note: the Strokes might be a great tool to use now.  From front view of chair, stroke along each peak and valley of the corrugation (similar to the beginning of the second GIF).  Once you have the front done, select one of the edges and stroke along the respective curved edge of seat, and then along the back.  Do same for other side.  Then you can use Patches tool to fill in the backside.

Not as quick as Contours, but will get the job done.

Again, will take another look at these tools once RF is working in 2.80.  Thanks for the report!
