### ISSUE TITLE
Blender 2.8 doesn't want to install the addons

### ISSUE THREAD

**Issue by ZebiMedia** [CGCookie/retopoflow#735]

**Comment by TheCharacterhero** [comment]
Answer: https://github.com/CGCookie/retopoflow/issues/726#issuecomment-516548206
Follow us on Twitter: https://twitter.com/gfxcoder

**Comment by carter2422** [comment]
Thanks for chiming in with a link to the answer @TheCharacterhero. 


I'm closing this issue as it's not a bug; the 2.8 version will be released just soon as we can and it will be emailed to all existing customers.
