### ISSUE TITLE
Blender 2.8 

### ISSUE THREAD

**Issue by ZebiMedia** [CGCookie/retopoflow#736]
The addons in not compatible with Blender 2.8 according to the user preference panel. 
![Anteckning 2019-08-18 120949](https://user-images.githubusercontent.com/18197590/63223134-57ec8000-c1b1-11e9-8776-1ef275306486.jpg)

**Comment by TheCharacterhero** [comment]
Answer: https://github.com/CGCookie/retopoflow/issues/726#issuecomment-516548206
Follow us on Twitter: https://twitter.com/gfxcoder

**Comment by carter2422** [comment]
@ZebiMedia we are very actively working on the 2.8 version. I wish we could give an exact timeframe but it's proven to be a huge project due to the depth of changes in Blender 2.8.

We will send an email out to all RetopoFlow customers via Blender Market the moment it's ready.
