### ISSUE TITLE
when will the addon for Blender 2.8 be ready ?

### ISSUE THREAD

**Issue by deock90** [CGCookie/retopoflow#737]

**Comment by taylrobe** [comment]
It'll probably be a while.  They decided to wait for Blender 2.80 to officially release before seriously starting on it.  They've had the b280 branch on Github for a while, but have not been updating it much. And that branch currently does not work in any form in Blender 2.80 right now (Even when you download and add in the addon_common folder separately).

**Comment by TheCharacterhero** [comment]
Answer: https://github.com/CGCookie/retopoflow/issues/726#issuecomment-516548206
Follow us on Twitter: https://twitter.com/gfxcoder

**Comment by carter2422** [comment]
@deock90 we are _very_ actively working on the 2.8 version. I wish we could give an exact timeframe but it's proven to be a huge project due to the depth of changes in Blender 2.8. 

We will send an email out to all RetopoFlow customers via Blender Market the moment it's ready.
