### ISSUE TITLE
Does not build on Windows

### ISSUE THREAD

**Issue by jayanam** [CGCookie/retopoflow#738]
The Retopoflow for Blender 2.8 does not run with cmake on windows os.

**Comment by vxlcoder** [comment]
Thanks for the report.  RF does not need building to work on Blender. There is a makefile (make, not cmake), but that is needed only to create a Blender-friendly zip file for installing via preferences dialog. We are working on a 2.80-working version in the `b280` branch, but it is still pre-alpha.

**Comment by jayanam** [comment]
Ok, but how to install it then? Extract the folder and paste it into the
scripts folder of Blender?

**Comment by carter2422** [comment]
@jayanam we are very actively working on the 2.8 version but it is not ready yet and so the installer is not expected to work.

Once everything is ready for 2.8 then the make file will generate a blender-ready .zip that can be used to *Install from File*.

We will send an email out to all RetopoFlow customers via Blender Market the moment it's ready.
