### ISSUE TITLE
retopoflow b280 doesnt start when i try to enable it :( 

### ISSUE THREAD

**Issue by GalaxisN7** [CGCookie/retopoflow#740]
![image](https://user-images.githubusercontent.com/55031797/64478904-25ceac80-d1b8-11e9-83f0-3ae6f1116185.png)

**Comment by vxlcoder** [comment]
Thanks for the report, @GalaxisN7.

The `b280` branch for Blender 2.80 is still under heavy development, so RF might not enable correctly until the changes stabilize.

Did you clone the repo directly into the `addons` folder?  Blender tends to not like this, because the default root folder name from git is not Python friendly.

**Comment by taylrobe** [comment]
You have to download "addon_common" separately and merge it in.  It's not included when you get the b280 branch.

**Comment by Vytek** [comment]
I would like to buy this plugin if it was for Blernder 2.80. Tell me how to help  ;-)

**Comment by GalaxisN7** [comment]
> You have to download "addon_common" separately and merge it in. It's not included when you get the b280 branch.

I did it, but when i add utils.py file, Blender is freezing.

**Comment by vxlcoder** [comment]
@GalaxisN7, did you follow the instructions at the bottom of the `readme.md` under `b280` branch?
see: https://github.com/CGCookie/retopoflow/tree/b280

It's difficult to determine what isn't working for you without knowing what you did.  please provide more details.

**Comment by GalaxisN7** [comment]
> le

**Comment by GalaxisN7** [comment]
> @GalaxisN7, did you follow the instructions at the bottom of the `readme.md` under `b280` branch?
> see: https://github.com/CGCookie/retopoflow/tree/b280
> 
> It's difficult to determine what isn't working for you without knowing what you did. please provide more details.

Now it's working !!! Thank you a lot !!!

**Comment by RealMango** [comment]
> > @GalaxisN7, did you follow the instructions at the bottom of the `readme.md` under `b280` branch?
> > see: https://github.com/CGCookie/retopoflow/tree/b280
> > It's difficult to determine what isn't working for you without knowing what you did. please provide more details.
> 
> Now it's working !!! Thank you a lot !!!

What did you exactly do? I don't have a coding background so I'm pretty lost. 

Is this what has to be done? 

> $ git clone git@github.com:CGCookie/retopoflow.git retopoflow
> $ cd retopoflow
> $ git checkout b280
> $ git submodule update --init --recursive
> 
> # to update addon_common
> $ cd retopoflow
> $ git pull
> $ git submodule foreach git pull origin master

**Comment by vxlcoder** [comment]
@RealMango, the instructions at the bottom of the readme (https://github.com/CGCookie/retopoflow/blob/b280/README.md) walk you through getting RF using git.  We will package an addon .zip ready for install once RF is fully ready for Blender 2.8x.  Keep an eye on issue #746!

**Comment by vxlcoder** [comment]
sorry, @RealMango. For some reason, the second part of your question didn't show up on GH, but yes.  the first set of commands are git commands for cloning the `b280` branch of the RetopoFlow repository, and the second set are for pulling down new updates.

**Comment by MattCowdery** [comment]
I'm having the same problem that @RealMango and @GalaxisN7 had, except when I try to run `'git submodule update --init --recursive'` from the github command line I get a git permissions error with my authentication.

![Capture](https://user-images.githubusercontent.com/13543088/71656099-d411db00-2cee-11ea-884c-f0c2ab14d0ba.PNG)

Does this indicate a problem when I set up git itself?
