### ISSUE TITLE
How to double Retopoflow 

### ISSUE THREAD

**Issue by leecreat** [CGCookie/retopoflow#744]
I did sculpt and made obgect use retopoflow.
I wanna do retopoflow again on retopoflow obect.
So I try to double retopoflow. But when I try double retopoflow, retopoflow tool box light is turn off. It means cannot use... how can I do double retopoflow???

**Comment by vxlcoder** [comment]
When in object mode, whatever is selected and active is considered the target, and everything else is source.  So, if you want to retopo a retopo'd mesh, simply unselect it, and start RF.

Alternatively, create a new mesh, enter edit mode, and then start RF.  The edited object is the target.

Note, this only works in version 2.0.3.
