### ISSUE TITLE
retapoflow will it available on 2.80 and why does not working or why not avaliable in 2.79 after i want to try in my computer 

### ISSUE THREAD

**Issue by Ramalium** [CGCookie/retopoflow#745]
hi iam from over sea i hope my english word is can be understand?

could you please give me good news for available if retapoflow available in 2.80 reason after i instal 2.79 i dont rely familiar even after i instal the system in 2.79 is not working help.

i want to purchase  for 2.80 could you let me know thru my email if available on the market, how ever when i was disappoint its only for 2.79 which is i up set reason i dont use 2.79. should i used blender 2.79 reason i kind a new beginner in blender?  should i wait or instal blender 2.79 or just waiting the the development in to purchase the retapoflow  i want to help as geting the help from same from retapoflow . 

thank you 
this is my email orbitalsinium@gmail.com 

i am sorry  if are  my english are not  familier i hope i still communicate with polite word

**Comment by vxlcoder** [comment]
Hi, @Ramalium.

We are working on RetopoFlow for Blender 2.80, but it is not ready, yet.  Soon it will be.

If you want to try RetopoFlow, you will need to use Blender 2.79.

We will say when it is ready on the Blender Market https://blendermarket.com/products/retopoflow.

I hope you can understand my reply.  Tell me if you have more questions.

Thank you.
