### ISSUE TITLE
2.8x Release

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#746]
The following are the remaining items holding back a release for Blender 2.8x.

- [x] Patches
- [x] allow several tools use same widget: workaround with duplicated widgets---bad!
- [x] welcome message (anyone)
- [x] help system (longer, @vxlcoder)
- [x] help messages (anyone)
- [x] update all shaders to 3.3 core: I believe this is done, but need to test on OSX!
- [x] UI scrolling (@vxlcoder)
- [x] Crash Handling!! (longer, @vxlcoder)
- [ ] update images in help
- [ ] test on large sources/targets (anyone)
- [x] scaling sources+target to unit cube, adjust near and far planes (@vxlcoder)

These are high-priority items, but might take longer to figure out.

- [ ] fix recover button (harder, blender bug?, @vxlcoder)
- [x] faster ui (harder, @vxlcoder)
- [x] retina display / non-unit ui scaling

The following would be nice to have done before, but not absolutely necessary.  These can be improved over time.  Note: some are CC-related issues.

- [x] Options: Contours, PolyStrips, PolyPen, Strokes, ...
- [ ] UI drag to change values
- [ ] improve UI text inputs
- [x] UI float clamping

**Comment by Diochris** [comment]
How can i have retopoflow for test?

**Comment by grimakaka** [comment]
Hello! I install the version for 2.8 and when I try to enable it I get the following message.
![2019-11-21 (3)](https://user-images.githubusercontent.com/50794359/69357956-1deeb680-0c97-11ea-97a9-78a0a5e45004.png)
![2019-11-21 (4)](https://user-images.githubusercontent.com/50794359/69357971-247d2e00-0c97-11ea-8c2e-7beded6386b1.png)

**Comment by vxlcoder** [comment]
@Diochris and @grimakaka, there are instructions on the readme (https://github.com/CGCookie/retopoflow/blob/b280/README.md).  We are working to get an install-able zip ready over the next few days.

**Comment by NazzarenoGiannelli** [comment]
Same error as the guy above. I am probably missing something, but in the Readme file I do not see any instruction about it.

**Comment by vxlcoder** [comment]
sorry, the instructions are at the very bottom of the readme, in a not-very-obvious spot.  will work on that.  i've copy-pasted them below.

```
$ git clone git@github.com:CGCookie/retopoflow.git retopoflow
$ cd retopoflow
$ git checkout b280
$ git submodule update --init --recursive
```

if you are not using git, you can download the zip of RF from https://github.com/CGCookie/addon_common/archive/b280.zip, but then you'll need to download and extract this zip https://github.com/CGCookie/addon_common/archive/b280.zip into the `addon_common` folder.  (there are two parts if you go by zips on GitHub)

note on updating to latest version: downloading RF with the zip files will mean that you'll have to repeat both steps.  if you use git, you can follow the instructions below

```
$ cd into_the_retopoflow_folder
$ git pull
$ git submodule foreach git pull origin master
```

**Comment by NazzarenoGiannelli** [comment]
Awesome! Thx! Now I got it working :)
It's so nice to finally have it on 2.8x! It was the only reason I was still keeping a 2.79 version installed
Thanks for the incredible work

**Comment by Diochris** [comment]
why i cant figure out how its done? anyone can explain please?

**Comment by NazzarenoGiannelli** [comment]
What worked for me:
- go here https://github.com/CGCookie/retopoflow/tree/b280 and download the zip via the Clone or download button.
- extract it
- then download this  https://github.com/CGCookie/addon_common/archive/b280.zip
- copy the content of the last zip into the addon_common
- zip again the whole retopoflow folder (first download)
- install the newly zipped file via addon tab in Blender 2.81

Let me know if it works for you this way

**Comment by Diochris** [comment]
Yes everything seems fine now! thx so much! testing time!

**Comment by Diochris** [comment]
> What worked for me:
> 
> * go here https://github.com/CGCookie/retopoflow/tree/b280 and download the zip via the Clone or download button.
> * extract it
> * then download this  https://github.com/CGCookie/addon_common/archive/b280.zip
> * copy the content of the last zip into the addon_common folder of the above extracted one
> * zip again the whole retopoflow folder (first download)
> * install the newly zipped file via addon tab in Blender 2.81
> 
> Let me know if it works for you this way

Nop it doesnt works unfortuanately,blender stucks and crashes! can you share your zip file?

**Comment by NazzarenoGiannelli** [comment]
Sure! [https://drive.google.com/open?id=131FM2OEnzzBabOC5yT4mN6vsA6s8fg1X](url)
Tested on two different Windows 10 machines with 2.81. No issues.

**Comment by Diochris** [comment]
> Sure! [https://drive.google.com/open?id=131FM2OEnzzBabOC5yT4mN6vsA6s8fg1X](url)
> Tested on two different Windows 10 machines with 2.81. No issues.

Thanks man,i dont know what i was doing wrong..your zip file played like charm..
Ofc some features missing but its still alpha,i am bery happy to see to RF on blende 2.8x again!

**Comment by NazzarenoGiannelli** [comment]
Actually what I did was to follow the above git commands for cloning the repo and the submodule and then I copied the addon_common files in the appropriate folder. Probably cloning via git in that way did something different than just downloading the zip file from the GitHub page and in this way everything went to the right place.

**Comment by carter2422** [comment]
Thanks for helping to test @NazzarenoGiannelli and @Diochris! If you run into any errors please report them here by opening a new issue: https://github.com/CGCookie/retopoflow/issues/new

We're working to get a beta ready today and tomorrow and so all error reports are welcome.

Once we're ready for beta we will package up a `.zip` that can simply be installed like any other add-on.

**Comment by Diochris** [comment]
Sorry i dont know where else to ask,if i buy retopoflow 2 on blender market,will i get update on 3 too?

**Comment by vxlcoder** [comment]
Yes. You will get a free upgrade to 3

>

**Comment by ijustwanttopass** [comment]
> Sure! [https://drive.google.com/open?id=131FM2OEnzzBabOC5yT4mN6vsA6s8fg1X](url)
> Tested on two different Windows 10 machines with 2.81. No issues.

Could you please share your zip file again? The link doesn't seem to be working for me.

**Comment by NazzarenoGiannelli** [comment]
@ijustwanttopass try [this](https://drive.google.com/open?id=131FM2OEnzzBabOC5yT4mN6vsA6s8fg1X) or select the link text from the older post and paste it in an empty browser tab. It should work.

Anyway, the Retopoflow' developers have updated the repo since my other post and you should be able to try the official alpha cloning the 2.80 branch.

**Comment by ijustwanttopass** [comment]
Awesome... thanks a bunch :)

**Comment by mix-123** [comment]
Yeah, so i've tried both the copy paste method and the git method to get the alpha to work, both have failed. The fault is mine for sure for failing because NazzarenoGiannelli managed to get it to work. But that's not the point. The point is, that it is overly complicated to get it to work, thus it's an excellent way to build frustration and discontent. In fact I got so frustrated, that if it wasn't for NazzarenoGiannelli posting a working .zip, i would have erased CGCookie from my mind permanently. And i'm saying this as a paying former CGCookie customer. I'm still a fan though (for now), otherwise i wouldn't have cared enough to write this message.  /m

**Comment by mix-123** [comment]
A suggestion for the PolyPen tool. As it is now, one selects with Right Click and then move with Left Click. Selecting with Right Click, holding down the button and moving with one motion seems more intuitive and it's one click faster. Anyway that is the Blender default (with right click select). Or perhaps being able to chose between the two.

**Comment by vxlcoder** [comment]
Thanks for the suggestion! Actually, that code is already there. I just
haven't brought the option to enable it back. Thanks for the reminder!

**Comment by mix-123** [comment]
Hi, no vertices/edges/faces visible in latest version (alpha2). Tested on Ubuntu 18.04.3 & win7.
![retopo](https://user-images.githubusercontent.com/58984092/71527683-c3bbc380-28dc-11ea-82df-c7277fc1ca63.png)

**Comment by vxlcoder** [comment]
sorry, @mix-123!  I've been debugging some OSX issues, which has involved converting the mesh drawing to use the new BPY/BGL/Shader stuff, and I haven't yet finished upgrading the vert+edge drawing.  will be working on that next!

for now, you might want to checkout a previous commit, or just wait.  i'm hoping to have this ready later today

**Comment by mix-123** [comment]
Yes the previous one works fine, thank you and happy holidays!

**Comment by vxlcoder** [comment]
@mix-123, verts and edges draw in the latest commit.  let me know if you have any other problems!

**Comment by SavMartin** [comment]
Before,this update, retopoflow vertex and edge looks like this 
![imagen](https://user-images.githubusercontent.com/30030642/71543837-8fddae00-296f-11ea-96ac-da8e69d560fa.png)
And after this last update it looks like this:
![imagen](https://user-images.githubusercontent.com/30030642/71543850-daf7c100-296f-11ea-8731-c3c620b7e389.png)

**Comment by mix-123** [comment]
Hi, i don't know if it qualifies as a bug/problem, but perhaps still worth mentioning.
Edges/faces get longer and longer from the middle of the strip towards the ends of the strip, when drawing on curved surfaces with the PolyStrip tool. 
Tested on Ubuntu 18.04.3 & win7 on Blender 2.80 & 2.81.

Bottom row objects rotated 45 degrees.

![retopo](https://user-images.githubusercontent.com/58984092/71549919-04433c00-29c6-11ea-8de1-be60cab03737.png)

**Comment by SavMartin** [comment]
> Before,this update, retopoflow vertex and edge looks like this
> ![imagen](https://user-images.githubusercontent.com/30030642/71543837-8fddae00-296f-11ea-96ac-da8e69d560fa.png)
> And after this last update it looks like this:
> ![imagen](https://user-images.githubusercontent.com/30030642/71543850-daf7c100-296f-11ea-8731-c3c620b7e389.png)
I found the way to change it.. 
![imagen](https://user-images.githubusercontent.com/30030642/71593933-c3663700-2b2d-11ea-9e1c-229e1841b835.png)

**Comment by TheCharacterhero** [comment]
> What worked for me:
> 
>     * go here https://github.com/CGCookie/retopoflow/tree/b280 and download the zip via the Clone or download button.
> 
>     * extract it
> 
>     * then download this  https://github.com/CGCookie/addon_common/archive/b280.zip
> 
>     * copy the content of the last zip into the addon_common folder of the above extracted one
> 
>     * zip again the whole retopoflow folder (first download)
> 
>     * install the newly zipped file via addon tab in Blender 2.81
If you add files and archive again, it will not work. I added the files directly to the archive, without extract them. And then installed.

I have Windows, so I had to install Virtual Box.
I downloaded the source code and extract it.
I went to the given folder through the terminal and entered the command **make**
Then he opened the created archive RetopoFlow v3.00.0 and added the files from [https://github.com/CGCookie/addon_common/archive/b280.zip](https://github.com/CGCookie/addon_common/archive/b280.zip) to the addon_common folder
Then he installed the addon as usual.

**Comment by n3m4nj4** [comment]
Bug issue... I have a small issue with contours, when I hit shift and scroll up and down the number of segments only goes up but not down. Poly stripes are working fine

**Comment by Bossyao168** [comment]
> Bug issue... I have a small issue with contours, when I hit shift and scroll up and down the number of segments only goes up but not down. Poly stripes are working fine. I'm using blender 2.8.1a so it might be the blender issue, anyways i just wanted to let you know.

Same issue to me. And I'm unable to increase/decrease the segment count if the symmetry is on.

**Comment by vxlcoder** [comment]
Will take a look at these later comments.  If you did find a bug, please consider creating a new issue and include screenshots or instructions to reproduce the bug.  Thanks!

**Comment by Bossyao168** [comment]
> Will take a look at these later comments. If you did find a bug, please consider creating a new issue and include screenshots or instructions to reproduce the bug. Thanks!

**Is your issue in regard to RetopoFlow on Blender 2.8?:** **If so, please refrain from posting.**
So why are these hints there, can the issue of 2.8 really be put forward.

**Comment by vxlcoder** [comment]
Ack!  that should be reworded/updated!  Sorry about that, @Bossyao168!

**Comment by vxlcoder** [comment]
closing this thread.  please see issue #822
