### ISSUE TITLE
can't use retopo flow

### ISSUE THREAD

**Issue by sabbiroz** [CGCookie/retopoflow#748]
![Capture](https://user-images.githubusercontent.com/34922213/68788186-23337c00-066d-11ea-8cc1-ef5d9cb965d4.JPG)
![Capture1](https://user-images.githubusercontent.com/34922213/68788191-23cc1280-066d-11ea-8863-a2264897b59d.JPG)

**Comment by vxlcoder** [comment]
Thanks for the report, @sabbiroz.  We are currently working on getting RF working in Blender 2.8x, and we're nearly ready to release it.  Keep an eye on issue #746!
