### ISSUE TITLE
So far some orthographic cameras doesnt work!

### ISSUE THREAD

**Issue by Diochris** [CGCookie/retopoflow#754]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**Is your issue in regard to RetopoFlow on Blender 2.8?:**

If so, please refrain from posting. We understand you are excited for the 2.8 version of Retopoflow but the time spent replying to these issues could be better spent towards 2.8 development. Check the [closed issues](https://github.com/CGCookie/retopoflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) for existing 2.8 related questions instead.

**Questions not directly related to the RetopoFlow project are considered general and should be asked elsewhere (e.g. git, blender, python, etc).**

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read through the README to assure the process taken is correct
- [ ] I have checked and can confirm this issue has not already been reported in some variantion in the existing [issues](https://github.com/CGCookie/retopoflow/issues).
- [ ] I have checked that the bug I am reporting can be replicated, and have provided what is required to allow another party to replicate.
- [ ] I have provided as much information as possible about the issue for the developer to replicate this issue; blend files, screenshots, logfiles, info about the expected result and actual result.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I just started using this project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.

----

**Retopoflow Version:** {retopoflow version here}

**Blender Version (Hash):** {blender version hash here}

**Platform:** {platform here}

**Issue:**

{issue content here}

{screenshot of issue}

**Replication Resources:**

**Replication Steps:**

1. {step 1}

**Comment by vxlcoder** [comment]
hi, @Diochris.

I'm not sure what you mean by "So far some orthographic cameras doesnt work!".  I can switch to orthographic view, and all the tools appear to work just fine.

Can you please provide more details, such as screenshots, what you're doing, what you'd expect RF to do, what RF is actually doing, etc.?

Thank you

**Comment by Diochris** [comment]
I am sorry Jon, on my edition numlock 1,3,7 and 9 doesnt work!
Its bottom orthografic camera,right,top and front.But user perspective works fine.I hope it helps..
I am gonna do some more tests in the week,i will let you know!

**Comment by vxlcoder** [comment]
ah!  yeah... will look into that.  Thank you for catching it!

**Comment by vxlcoder** [comment]
should be fixed now!
