### ISSUE TITLE
Merging at center with polypen tool

### ISSUE THREAD

**Issue by Diochris** [CGCookie/retopoflow#762]
Having this problem with polypen tool!when i try to attach new quad it merges verts on center i think..see images beloew!

![Screenshot_1](https://user-images.githubusercontent.com/57815371/69831227-23b54080-1231-11ea-925c-829a749f63a3.png)
![Screenshot_2](https://user-images.githubusercontent.com/57815371/69831228-244dd700-1231-11ea-9982-9c072668a47d.png)
![Screenshot_3](https://user-images.githubusercontent.com/57815371/69831229-244dd700-1231-11ea-9b81-9661bd8a7a74.png)

**Comment by carter2422** [comment]
@Diochris this is likely a `Merge Distance` issue, which you can adjust via the Polypen options. Can you try adjusting that and see if it still happens?

Also if you can provide step-by-step instructions for how to replicate this that would help. So far I've not been able to replicate it with a default UV sphere.

**Comment by jlampel** [comment]
Closing this out since no more info was provided and it hasn't been reported since
