### ISSUE TITLE
Crash when pressing Ctrl-S on unsaved file (default scene)

### ISSUE THREAD

**Issue by VincentKueszter** [CGCookie/retopoflow#764]
Just a small inconvenience, I stumbled upon this when I tried to replicate a different bug.
This happens when you open Blender, start Retopo on the default cube and then press Ctrl-S without having saved the file before/given it a name.

Environment:

- RetopoFlow: 3.0.0α
- Blender: 2.81.16 master 2019-11-20
- Undo: insert, insert, select, grab, select, insert, insert, insert, insert

Error Hash: 5cd20cc814c721fa2d11f235c86c7f2c

EXCEPTION (<class 'RuntimeError'>): Error: Cannot open file untitled.blend@ for writing: Permission denied

Trace (partially anonymized):
```
-     C:\Program Files\Blender Foundation\Blender 2.81\2.81\scripts\modules\bpy\ops.py
- 000 0201:__call__() ret = op_call(self.idname_py(), None, kw)
-     C:\Users\[...]\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RetopoFlow\retopoflow\rf\rf_blender.py
- 001 0397:save_normal() bpy.ops.wm.save_mainfile()
-     C:\Users\[...]\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\RetopoFlow\retopoflow\rf\rf_states.py
- 002 0078:modal_main() self.save_normal()
-     .../common\fsm.py
- 003 0063:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
this should now be fixed.  thanks for the report, @VincentKueszter!

**Comment by VincentKueszter** [comment]
Confirmed, it's working.
