### ISSUE TITLE
Inconsistencies after Save in Retopo -> Load

### ISSUE THREAD

**Issue by VincentKueszter** [CGCookie/retopoflow#765]
Steps to reproduce:
- enter RetopoFlow mode
- save via Ctrl-S
- close Blender without saving in "normal" mode
- load again 

The following settings will not be changed back by RetopoFlow:

- Size is 5, in one file's case it's 5.75942 (This might be related to ClipStart being 0.575942 m and ClipEnd 5759.42 m for that file, those values are not set by me (to my knowledge)) (Probably related to the sizing issue mentioned in issue #753 )
- 3D Viewport header is disabled, as are Toolbar and Property Window etc
- The RetopoFlow model has "Disable in Viewports" enabled

Environment:

- RetopoFlow: 3.0.0α
- Blender: 2.81.16 master 2019-11-20

**Comment by vxlcoder** [comment]
Thanks for the report! Will take a look

**Comment by vxlcoder** [comment]
this should now be fixed.  thanks!

**Comment by VincentKueszter** [comment]
Confirmed, it's working now!
PS: I noticed my clip start/end was still weird (as expected), but apparently, there is no way to set it in the Retopo options menu during Retopo mode. I suppose that feature will be back with the release candidate?

**Comment by vxlcoder** [comment]
clip start and end are back in with commit 885d6cc!

closing this issue.  let me know if you have any other problems.  thanks!
