### ISSUE TITLE
[BUG] Model Resizing issues on 3.0.0a

### ISSUE THREAD

**Issue by Weebtiik** [CGCookie/retopoflow#767]
**Retopoflow Version:** 3.0.0a

**Blender Version (Hash):** Blender 2.8 master

**Platform:** Windows 10

**Issue:**

Retopoflow constantly resizes models when entering retopology mode, no matter the model.

**Replication Steps:**

1. Start Retopo
2. Exit Retopo
3. Done, the sizing of the model changed from it's original size and there's no way to get it back as it's random.

**Comment by vxlcoder** [comment]
thanks for the report, @Weebtiik.

This should now be fixed in commit (commit 7930b34)
