### ISSUE TITLE
Add support for two sided, U, patches

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#77]
A two-sided, U patch looks like this:
![screen shot 2015-01-06 at 4 44 11 pm](https://cloud.githubusercontent.com/assets/1648631/5637638/56505f60-95c3-11e4-876f-900e309cafd8.png)

And should fill like this:
![screen shot 2015-01-06 at 4 45 08 pm](https://cloud.githubusercontent.com/assets/1648631/5637648/65c9a294-95c3-11e4-87fd-814d50b4ef7e.png)

The edge flow is this:
![screen shot 2015-01-06 at 4 47 02 pm](https://cloud.githubusercontent.com/assets/1648631/5637673/aabee1e8-95c3-11e4-8858-3c40f21ab0e3.png)

**Comment by patmo141** [comment]
In above example.  Side A is N, Side B is N + 2. For Equal sides, there is this solution
![image](https://cloud.githubusercontent.com/assets/2917743/12045634/339b5e4a-ae75-11e5-84df-b397f41e8509.png)

**Comment by patmo141** [comment]
This is also a TODO for edge_patches.  It will be easy compared to the other patches already implemented.

**Comment by carter2422** [comment]
@patmo141 if you feel like tackling this go ahead and self-assign :)

**Comment by carter2422** [comment]
Moving this to 2.0.
