### ISSUE TITLE
Can't grab the green handle (retopoflow)

### ISSUE THREAD

**Issue by Octave1201** [CGCookie/retopoflow#770]
Hello!

I've got a problem and I really need some help! I've install retopflow 1.3.2 with Blender 2.79. When I draw some strips with Polymesh, I can't grab the green handle (with the Right Mouse Button).

https://www.zupimages.net/viewer.php?id=19/49/ky7h.png

I prefer to use retopoflow 1.3.2 instead of 2.0 or above because 2.0 is lagging on my PC....

Please help...

Thanks in advance for your help... I really love this addon

**Comment by Octave1201** [comment]
Please help

**Comment by vxlcoder** [comment]
Will dig into this problem as soon as possible.

**Comment by Octave1201** [comment]
Thank you

**Comment by carter2422** [comment]
@Octave1201 can you try switching into Perspective mode? We've had issues in the past where handles would be unselectable in Orthographic mode on some models.

**Comment by jlampel** [comment]
If this continues to be a problem in 3.0 and in perspective mode, please let us know by opening a new issue!
