### ISSUE TITLE
Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by DeWolfePilot** [CGCookie/retopoflow#771]
After few mins in any mode polypen/polystrip - black "darkening" overlay blink for a second (looks like "T" side toolbar trying to extend by itself) and after this mouse stop responding, cant select/create new polygon/edge/vertex. Then after i try to select all "A" - error message appear. Trying to install 2.8 and load factory settings -  gives same error. 
There is screen recording https://youtu.be/hYXOsSKZ9rE

Environment:

- RetopoFlow: 3.0.0β
- Blender: 2.81.16 master 2019-11-20
- Platform: Windows, 7, 6.1.7601, AMD64, Intel64 Family 6 Model 58 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 670MX/PCIe/SSE2, 4.5.0 NVIDIA 425.31, 4.50 NVIDIA
- Timestamp: 2019-12-05 03:08:04.141408
- Undo: select all, select all, select, grab, select, move after select, grab, move after select, grab, insert

Error Hash: e167b9f1d099a0f65c1627846f2849ef

Trace:

- EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
-     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modules\bpy_types.py
- 000 0712:__getattribute__() return super().__getattribute__(attr)
-     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow\retopoflow\rf\rf_target.py
- 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_selection_center()
- 002 0530:select_toggle() self.update_rot_object()
-     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\retopoflow\retopoflow\rf\rf_states.py
- 003 0109:modal_main() self.select_toggle()
-     .../common\fsm.py
- 004 0063:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report and video, @DeWolfePilot!

i think the problem is from the auto save doing its thing, but something went wrong.

Are you able to do it again with the terminal opened first (Window ‣ Toggle System Console).  there might be other useful details printed out there when this happens.

**Comment by DeWolfePilot** [comment]
Yes, you was right, it's triggered when saving. I can manually instantly trigger this error by pressing ctrl+s. Thats what consol shows:

\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.002910
- Count: 301
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.009911
- Count: 302
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.049913
- Count: 303
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.058913
- Count: 304
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.067914
- Count: 305
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.075914
- Count: 306
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "insert" ("insert", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:51.084915
- Count: 307
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0521:select() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 003 0416:_insert() self.rfcontext.select(bmv)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool.py
  - 004 0141:wrapper() ret = fn(*args, **kwargs)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rftool_polypen\polypen.py
  - 005 0221:insert() return self._insert()
  -     .../common\fsm.py
  - 006 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
Caught exception in function "modal_main" ("main", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:52.034969
- Count: 308
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0530:select_toggle() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_states.py
  - 003 0109:modal_main() self.select_toggle()
  -     .../common\fsm.py
  - 004 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
CookieCutter_Exceptions._callback_exception_callbacks: 'VIEW3D_OT_RetopoFlow' ob
ject has no attribute 'rot_object'
Loaded font "C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\sc
ripts\addons\retopoflow\addon_common\common\fonts\DejaVuSansMono.ttf" as id 4
Loading image "close.png" (C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\B
lender\2.81\scripts\addons\retopoflow\addon_common\common\images\close.png)
Caught exception in function "modal_main" ("main", "main")
________________________________________________________________________________
____________________
Exception Info
- Time: 2019-12-06 18:46:52.359988
- Count: 309
- Hash: e167b9f1d099a0f65c1627846f2849ef
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no a
ttribute 'rot_object'
  -     F:\Program Files\SteamLibrary\steamapps\common\Blender\2.81\scripts\modu
les\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_target.py
  - 001 0545:update_rot_object() self.rot_object.location = self.rftarget.get_se
lection_center()
  - 002 0530:select_toggle() self.update_rot_object()
  -     C:\Users\DeWolfe\AppData\Roaming\Blender Foundation\Blender\2.81\scripts
\addons\retopoflow\retopoflow\rf\rf_states.py
  - 003 0109:modal_main() self.select_toggle()
  -     .../common\fsm.py
  - 004 0063:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
^^^^^^^^^^^^^^^^^^^^
'VIEW3D_OT_RetopoFlow' object has no attribute 'rot_object'
CookieCutter_Exceptions._callback_exception_callbacks: 'VIEW3D_OT_RetopoFlow' ob
ject has no attribute 'rot_object'
GitHub: Already reported!
GitHub: Already reported!

**Comment by vxlcoder** [comment]
this issue should now be fixed.  if you get a chance, please test.  thanks for the report!
