### ISSUE TITLE
Error enabling add on after install from Zip.

### ISSUE THREAD

**Issue by dodeqaa** [CGCookie/retopoflow#772]
Hi, received an error installing from zip.

I was unable to click the checkbox to enable the plugin. 

Restarting blender solved this. 

Win 10
Blender 2.81 (master) 
Retopoflow 3 alpha.

**Comment by vxlcoder** [comment]
Interesting. Will have to check that out. thanks for the report!

**Comment by vxlcoder** [comment]
@dodeqaa, I haven't been able to reproduce this.  Have you had this problem again?

It might have been an unusual situation.

closing for now, but please reopen if you (or anyone else) runs into this problem.

thanks!
