### ISSUE TITLE
Expose style settings for edge thickness and vertex size

### ISSUE THREAD

**Issue by cloudnix** [CGCookie/retopoflow#776]
Hi thank's for this awesome addOn 👍🏻👍🏻👍🏻

My proposal is;

Can we have vertex and edge/line thick setting for tweak it ?
The default for me is too thick.
Thank's again

**Comment by carter2422** [comment]
Thank you for the suggestion @cloudnix! Better theme options is something we hope to add but no promises yet. For now we're focused on stability and performance for the 3.0.0 beta (and final release).

**Comment by vxlcoder** [comment]
target drawing has been significantly improved, and there are now options for adjusting vert and edge sizes.  there are still improvements to be made, but it's working at this point.

thanks!
