### ISSUE TITLE
Patches bug when y-Symmetry enabled

### ISSUE THREAD

**Issue by VincentKueszter** [CGCookie/retopoflow#777]
**Retopoflow Version:** 3.0.0β  b0220bb 

**Blender Version (Hash):** 2.81.16 master 2019-11-20

**Issue:**

When enabling y-Symmetry, the Patches tool snaps the upper row of generated vertices to the mirror center.
https://imgur.com/ZjCyhxk
x-Symmetry and z-Symmetry seem to be unaffected.

**Replication Steps:**

1. Enable retopo
2. Enable y Symmetry
3. Create topology that enables the generation of more than one quad (see image)
4. Use the Patches tool

**Comment by vxlcoder** [comment]
Interesting find!

Would you mind sharing the .blend file? You can email it to
retopoflow@gmail.com or share a link on here.

**Comment by VincentKueszter** [comment]
Sent!

**Comment by vxlcoder** [comment]
@VincentKueszter, this bug should be fixed now.  thanks for reporting it!

please let me know if you have any other problems

**Comment by VincentKueszter** [comment]
Tested it, it works now. Thank you!
