### ISSUE TITLE
**[BUG]** Retopoflow 3.0.0 alpha 2

### ISSUE THREAD

**Issue by SavMartin** [CGCookie/retopoflow#781]
**Retopoflow Version:** {3.0.0 alpha 2}

![imagen](https://user-images.githubusercontent.com/30030642/71624405-493fbc00-2bda-11ea-9f1c-e0c6e3482139.png)

**Platform:** {Linux Mint 19.03}

![imagen](https://user-images.githubusercontent.com/30030642/71624390-3200ce80-2bda-11ea-8120-0a2126ac9bc4.png)

**Comment by vxlcoder** [comment]
thanks for the report, @SavMartin!  this should be fixed now with this commit ^^
