### ISSUE TITLE
PolyStrips exception for selection + grab (2.79)

### ISSUE THREAD

**Issue by JoshuaLamusga** [CGCookie/retopoflow#785]
An unhandled exception occurred after I Ctrl + right-clicked to get a selection of connected faces in a line (not forming a loop) and pressed G to try and move it. Repros consistently. Tagged in title as 2.79 to indicate I haven't tested with version 3 on Blender 2.8.

Here's the selection in case it's relevant.
![image](https://user-images.githubusercontent.com/30244654/72211156-516de600-347b-11ea-8bb9-2919f8db036c.png)

```
Environment:

- RetopoFlow: 2.0.2
- Blender: 2.79.0 master 2017-09-11
- Platform: Windows, 8.1, 6.3.9600, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 960M/PCIe/SSE2, 4.6.0 NVIDIA 441.87, 4.60 NVIDIA
- Timestamp: 2020-01-11 13:58:35.848750
- Undo: move grabbed, select all, select all, select, select, relax, relax, select all, move grabbed, select

Error Hash: 11fe08aec24056eeeb7e571a8715a2dd

Trace:

- EXCEPTION (<class 'AttributeError'>): Vector addition: (NoneType + Vec2D) invalid type for this operation
- .../rfmode\rftool_polystrips.py
- 000 0452:modal_move() set2D_vert(bmv, xy + delta)
- .../common\profiler.py
- 001 0174:wrapper() return fn(*args, **kwargs)
- .../rfmode\rftool.py
- 002 0076:wrapper() ret = fn(*args, **kwargs)
- 003 0110:modal() nmode = self.FSM[self.mode]()
- 004 0114:modal() raise e     # passing on the exception to RFContext
- .../rfmode\rfcontext.py
- 005 0579:modal_main() self.tool.modal()
- 006 0494:modal() nmode = self.FSM[self.mode]()
```

**Comment by vxlcoder** [comment]
thanks for the report, @JoshuaLamusga!  Likely, this is still an issue in the latest RF.  i'll investigate

**Comment by vxlcoder** [comment]
I believe this is now fixed.  (that part of the code is now in a different file, and it handles cases more robustly)  Closing this issue, but please let us know if you run into it again.

Thanks!
