### ISSUE TITLE
[BUG] Hello. Retopoflow 2.8 freezes Blender if the option "Enter Edit Mode" is enabled in the Editing tab options.

### ISSUE THREAD

**Issue by slick3d** [CGCookie/retopoflow#786]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**Is your issue in regard to RetopoFlow on Blender 2.8?:**

If so, please refrain from posting. We understand you are excited for the 2.8 version of Retopoflow but the time spent replying to these issues could be better spent towards 2.8 development. Check the [closed issues](https://github.com/CGCookie/retopoflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) for existing 2.8 related questions instead.

**Questions not directly related to the RetopoFlow project are considered general and should be asked elsewhere (e.g. git, blender, python, etc).**

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read through the README to assure the process taken is correct
- [ ] I have checked and can confirm this issue has not already been reported in some variantion in the existing [issues](https://github.com/CGCookie/retopoflow/issues).
- [x] I have checked that the bug I am reporting can be replicated, and have provided what is required to allow another party to replicate.
- [x] I have provided as much information as possible about the issue for the developer to replicate this issue; blend files, screenshots, logfiles, info about the expected result and actual result.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [x] I just started using this project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.

----

**Retopoflow Version:** {retopoflow version here}

**Blender Version (Hash):** {blender version hash here}

**Platform:** {platform here}

**Issue:**

{issue content here}

{screenshot of issue}

**Replication Resources:**

**Replication Steps:**

1. {step 1}

**Comment by vxlcoder** [comment]
thanks for the report @slick3d.

This appears to be a Blender bug.  I reported it here: https://developer.blender.org/T73681

Working on a workaround...

**Comment by vxlcoder** [comment]
this should now be fixed (with workaround).

please let me know if you continue to have problems.

Thanks!
