### ISSUE TITLE
[BUG] unable to see preview Blender 2.79

### ISSUE THREAD

**Issue by GobIinKing** [CGCookie/retopoflow#787]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**Is your issue in regard to RetopoFlow on Blender 2.8?:*no*

If so, please refrain from posting. We understand you are excited for the 2.8 version of Retopoflow but the time spent replying to these issues could be better spent towards 2.8 development. Check the [closed issues](https://github.com/CGCookie/retopoflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) for existing 2.8 related questions instead.

**Questions not directly related to the RetopoFlow project are considered general and should be asked elsewhere (e.g. git, blender, python, etc).**

**In raising this issue, I confirm the following (please check boxes):**

- [ x] I have read through the README to assure the process taken is correct
- [ x] I have checked and can confirm this issue has not already been reported in some variantion in the existing [issues](https://github.com/CGCookie/retopoflow/issues).
- [ x] I have checked that the bug I am reporting can be replicated, and have provided what is required to allow another party to replicate.
- [ x] I have provided as much information as possible about the issue for the developer to replicate this issue; blend files, screenshots, logfiles, info about the expected result and actual result.
- [x ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ x] I just started using this project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.

----

**Retopoflow Version:** {2.02 and 2.01}

**Blender Version (Hash):** {2.79}

**Platform:** {Windows 10}

**Issue:**

{The addon works however I am unable to preview anything besides the number of how many vertices are being done but no preview or faces edges or vertices.}

{ https://cdn.discordapp.com/attachments/276471869857857548/668603986487672872/unknown.png }
 
**Replication Resources:**

**Replication Steps:**

1. {step 1}

**Comment by GobIinKing** [comment]
Fixed screenshot link my bad

**Comment by vxlcoder** [comment]
Will take a look!

**Comment by GobIinKing** [comment]
Any progress and finding anything?

**Comment by callimogua** [comment]
I'm using Retopoflow (downloaded from here) with Blender 2.79 and I'm having the same problem even today. Set the source, set the target (a plane), still only see the dashes and numbers but no preview geometry.

**Comment by jlampel** [comment]
Apologies for the late reply here but we haven't been able to both keep up with new Blender builds and go back to fix edge cases in 2.79 since it's unlikely many people are still using it. If this ever happens in RetopoFlow 3 in Blender 2.83 or later, please let us know!
