### ISSUE TITLE
Contours, increase/decrease segment counts

### ISSUE THREAD

**Issue by Larry3d** [CGCookie/retopoflow#788]
Please prefix your issue with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**.

**Is your issue in regard to RetopoFlow on Blender 2.8?:**

If so, please refrain from posting. We understand you are excited for the 2.8 version of Retopoflow but the time spent replying to these issues could be better spent towards 2.8 development. Check the [closed issues](https://github.com/CGCookie/retopoflow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed) for existing 2.8 related questions instead.

**Questions not directly related to the RetopoFlow project are considered general and should be asked elsewhere (e.g. git, blender, python, etc).**

**In raising this issue, I confirm the following (please check boxes):**

- [ ] I have read through the README to assure the process taken is correct
- [ ] I have checked and can confirm this issue has not already been reported in some variantion in the existing [issues](https://github.com/CGCookie/retopoflow/issues).
- [ ] I have checked that the bug I am reporting can be replicated, and have provided what is required to allow another party to replicate.
- [ ] I have provided as much information as possible about the issue for the developer to replicate this issue; blend files, screenshots, logfiles, info about the expected result and actual result.
- [ ] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I just started using this project.
- [ ] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.

----

**Retopoflow Version:** {retopoflow version here}
3.0 beta
**Blender Version (Hash):** {blender version hash here}
2.82.6 
blender-2.82-3ba5461af0c8-windows64
**Platform:** {platform here}
Windows 10
**Issue:**
Only after Load factory settings does it work only partially. Not at all before. If it works, I can only increase the number, but not make it lower. So shift + middle mouse wheel has no effect.
It doesn't work on the torso, where symmetry is switched on.

{issue content here}

{screenshot of issue}

**Replication Resources:**

**Replication Steps:**

1. {step 1}

**Comment by vxlcoder** [comment]
ah, missed the notes about symmetry...

**Comment by vxlcoder** [comment]
thanks for the report, @Larry3d!

this _should_ be fixed now.  please let us know if you have any other problems!

**Comment by blanchsb** [comment]
@vxlcoder 

Increase/decrease face count does not work for me on contours. (Windows 10 machine, blender 2.82 official release). Using beta build from blenderMarket. It is a few weeks old though. Is this fixed and should I download from blendermarket again?

**Comment by vxlcoder** [comment]
this should be fixed on the latest `b280` branch, but we haven't repackaged RF up again.
This link won't work for too long, but you can try downloading and installing RF from here https://www.dropbox.com/s/sjklq70oyvf5h25/RetopoFlow_v3.00.0.zip?dl=0

Thanks!

**Comment by JazzEW** [comment]
Hi @vxlcoder ! I just bought RetopoFlow a few days ago and found the same problem @blanchsb had found. I followed your link to the updated zip file in Dropbox, and I can confirm (on my end, anyway) that the shift+middle mouse wheel issue is resolved. I was able to roll the wheel upward to increase the face count; downward to decrease it.
