### ISSUE TITLE
[PROPOSAL] Wireframe visible while using Retopoflow

### ISSUE THREAD

**Issue by biteworks** [CGCookie/retopoflow#789]
**Questions not directly related to the RetopoFlow project are considered general and should be asked elsewhere (e.g. git, blender, python, etc).**

**In raising this issue, I confirm the following (please check boxes):**

- [x] I have read through the README to assure the process taken is correct
- [x] I have checked and can confirm this issue has not already been reported in some variantion in the existing [issues](https://github.com/CGCookie/retopoflow/issues).
- [x] I have checked that the bug I am reporting can be replicated, and have provided what is required to allow another party to replicate.
- [x] I have provided as much information as possible about the issue for the developer to replicate this issue; blend files, screenshots, logfiles, info about the expected result and actual result.
- [x] I have checked the pull requests tab for existing solutions/implementations to my issue/suggestion.

**My familiarity with the project is as follows (check one):**

- [ ] I just started using this project.
- [x] I have used the project briefly.
- [ ] I have used the project extensively, but have not contributed previously.

----

**Retopoflow Version:** 3.0.0 beta

**Blender Version (Hash):** 2.81

**Platform:** Windows 10

**Issue/Feature Request:**

When creating low poly versions of CAD data, it would be good if the wireframe of the high-resolution geometry could be visible.
Often it is important to see edges for a useful abstraction and to orientate yourself on them.
Unfortunately the wireframe disappears as soon as you switch to Retopoflow. 
It would be good if there was the possibility to show the highpoly wireframe. A option under view options would be great

When using Retopoflow we have no orientation
![Screenshot_1](https://user-images.githubusercontent.com/22855132/73862265-a0225c00-483e-11ea-819c-f61d9662db98.png)

Without Retopoflow it es possible to see where there are design edges
![Screenshot_2](https://user-images.githubusercontent.com/22855132/73862440-dc55bc80-483e-11ea-992f-4d539e89c84c.png)

**Comment by biteworks** [comment]
Would this feature be possible? Or simply to prevent the wireframe from being overwritten?

**Comment by MaximStale** [comment]
Yeah, it would be very helpful. 

We really need some way to show or highlight edges of highpoly with different color

For example, every day I use your great tool make LODs for character's clothes, and in technical documentation\requirements of project said that the loop or edge flow of low poly clothes should follow the edge\loop flow of the character body.

Also there are frequent issue with your super tool (your tool should be industrial standart) 
Sometimes verts won't snap, I dunno why, but we need something which it can highlight intersections, gaps and unwelded verts/edges/polygons.

And also it would be nice to have opportunity to add reference images (there are a lot of requirements to make forms as on the concept)

**Comment by MaximStale** [comment]
> 
> 
> Would this feature be possible? Or simply to prevent the wireframe from being overwritten?

maybe you can in someway update your request? 

I try to see if it was up'ed on the 'issue' board, but after my comment it show nothing

**Comment by vxlcoder** [comment]
made a quick first pass at this feature request.  below is a copy-paste from commit message.

> can now allow overlays to be drawn.  this option is sticky across RF sessions.
> 
> note: because we scale xforms of sources, target, and view, the grid and non-mesh objects will appear to change scale/positions!
> 
> ideally, we could visualize only the wireframe of source meshes.  maybe add to source mesh render?
> 
> otherwise, only solutions are:
> 
> - scale xforms of all objects (camera, lights, etc) and scale the `overlay.grid_scale` when starting/ending RF
> - store and then hide non-mesh objects and grid visualization, then restore when ending RF session
> 
> former is the better option.
> 
> note: not prioritizing finishing this feature right now.

![image](https://user-images.githubusercontent.com/3790699/91322553-e369fb00-e78d-11ea-9ae2-314e9f70ab1f.png)

**Comment by biteworks** [comment]
Cool, thanks!
Looks good already!
