### ISSUE TITLE
no edit undo

### ISSUE THREAD

**Issue by juan497** [CGCookie/retopoflow#793]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
@juan497, I'm not sure what the problem is.  RF does have the ability to Undo with CTRL+Z.

Can you please provide a description of what you're expecting RF to do and what RF is doing instead?

**Comment by juan497** [comment]
Oh it actually does have Ctrl + z. I was on a Mac doing cmd + z. Problem
solved thank you.

**Comment by juan497** [comment]
While I'm at at there is another issue. Rf mode does not allow you to use
the on screen rotation, grab , and zoom tool. Just for people who might
want to use this on a tablet.

**Comment by vxlcoder** [comment]
ah, good!

i'm currently working on better integration with blender keymap settings, so this should be a non-issue very soon...

on your other note: i'm not sure what you mean by "on screen rotation, grab, and zoom tool".  are you referring to the gizmos in the top-right corner of 3d view?

![image](https://user-images.githubusercontent.com/3790699/75291867-10465100-57f1-11ea-9311-f4e7e3b1b4fa.png)

**Comment by juan497** [comment]
Correct, since users with tablets may find it easier to use.

**Comment by vxlcoder** [comment]
marking the original issue as done.  will consider integrating the tablet-friendly gizmos in a separate issue.

**Comment by vxlcoder** [comment]
note: RF now uses Blender's undo/redo shortcuts
