### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by raven1934** [CGCookie/retopoflow#795]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*3.0.0(beta)*}

Blender Version/Hash: {*2.8.2.7*}

Platform Version/Distribution: {*Windows 10*}

&nbsp;

**Issue:**

{*Savefile loads old data*}

{*Don't have screenshot but i've worked making a character, it seems to rollback to older data when i load blender file but i can still recover the autosave file which has the progress that i've made, this is pretty spooky and happens when i switch between edit mode and the retopoflow mode. *}

&nbsp;

**Try altering the mesh at editmode when retopoflow has generated an initial mesh, then alter the mesh by for example switching loop subdivisions after adding new geometry with the contours tool, if you reload the file at blender after saving in both modes it seems to sometimes return the unaltered geometry before the modification, however by loading the autosave from retopoflow button it seems to return correct data.:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Thanks for the report, @raven1934.

I believe this should now be fixed.
