### ISSUE TITLE
FONT TOO SMALL

### ISSUE THREAD

**Issue by MooseQ** [CGCookie/retopoflow#796]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: BUG

Retopoflow Version: {*3.0*}

Blender Version/Hash: {*2.81*}

Platform Version/Distribution: {*iMAC*}

&nbsp;

**Issue:**

{*I am trying to use the 3.0 version of Retopoflow.  When I'm in the Retopoflow page, the fonts for the menus and Quick Start guides are too small for me to read without getting right up to the monitor (27").  In the previous version (2.0) I didn't have this problem.  Additionally, it's very hard to see the actual retopo mesh that's created, especially the vertices, which makes it so frustrating to see what I'm doing.  Keep in mind, I used Retopoflow 2.0 on Blender v2.79 with no issues like this on the same computer.*}

add any screenshots of the issue here*}
<img width="1302" alt="Screen Shot 2020-03-06 at 1 07 18 PM" src="https://user-images.githubusercontent.com/42391247/76109913-75493600-5fab-11ea-87f0-2f4c7da6912d.png">

<img width="1049" alt="Screen Shot 2020-03-06 at 12 49 14 PM" src="https://user-images.githubusercontent.com/42391247/76109579-b7be4300-5faa-11ea-8cc2-8379d89111a7.png">

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Thanks for the report, @MooseQ.

I believe this should be corrected in the very latest version of RF.  If you can, try using the version linked below (URL won't be accessible forever).

https://www.dropbox.com/s/sjklq70oyvf5h25/RetopoFlow_v3.00.0.zip?dl=0

If this does not resolve the problem, let us know, but also you can adjust the UI scaling manually using the Options > General > UI Scale option

![image](https://user-images.githubusercontent.com/3790699/76146864-a9346200-6064-11ea-8037-0f52d594ef2b.png)

Please let us know if you continue to have problems!

**Comment by MooseQ** [comment]
Hi Jon,

I tried that version you sent the link to and it didn’t help.
Can you tell me where to find the Options Menu to try that?
Thank you.
MooseQ

**Comment by vxlcoder** [comment]
Start RF, then click General in the Options menu in the top-right window, then click in the textbox next to UI Scale.

**Comment by MooseQ** [comment]
Got it!  Thank you!

**Comment by vxlcoder** [comment]
Great!  You're welcome!
