### ISSUE TITLE
[BUG] Imbedded Vertex in RetopoFlow 3

### ISSUE THREAD

**Issue by Dradeeus** [CGCookie/retopoflow#799]
Retopoflow Version: Retopoflow 3.0
Blender Version: 2.8

Very often 3.0 will create vertices that are embedded within the mesh. Usually, I would think there's too much information there, so I'd want to do it over, but can't, because I can't select anything. Doesn't help that anything sharing that vertex is also unselectable.
The only way to fix this is to go back out to normal Blender and select and delete the offending vertex.

The picture shows all that can be selected just by painting the mouse around the area. I know something about this being a bug was said in the tutorial video, but they didn't have much problem continuing. This has happened most times I have used the program.

I have tried merging vertices by distance and snapping all to surface.
This has been the case in perspective mode as well as orthographic mode.

If I had to give an uneducated guess, it's that it doesn't like thinner objects and keeps confusing which side to put the mesh overlay.

![7c79b4237a0251dbcdd8fdb32e108a82](https://user-images.githubusercontent.com/62775427/77804882-fbaae200-7056-11ea-950a-c0d4da75a07c.png)

**Comment by benjaminghys** [comment]
I have had this happen too, but nothing as bad like this. But still unselectable.
By zooming out I was able to select it again. Could be a temporary workaround until it gets fixed.

**Comment by vxlcoder** [comment]
sorry that i missed the original post of the issue.

which tool does this?  this might be a quick fix depending on the tool.

another workaround is to use Options > Target Cleaning > Snap Verts

![image](https://user-images.githubusercontent.com/3790699/78904610-ce910300-7a4a-11ea-84f9-2bfaefd0c70e.png)

**Comment by vxlcoder** [comment]
ah, just noticed that you're already trying the snap verts.  would you mind sharing your .blend file?  you can email to retopoflow@cgcookie.com

**Comment by jlampel** [comment]
The issue of unselectable vertices has come up a few times in support conversations, and I'm experiencing it every now and then as well. Here's a vertex that I placed with PolyPen that I can't grab from any view angle:

![image](https://user-images.githubusercontent.com/12982300/100780839-18a26c80-33bf-11eb-86b4-7d635e4db621.png)

However, if I exit RF and start it again without changing anything, I can select it again. If I find a case where I can't select it even after restarting, I'll send over the file.

**Comment by jlampel** [comment]
Actually, here's an example. Try using PolyPen to select and fill in this area of the mesh:
![image](https://user-images.githubusercontent.com/12982300/100781709-3ae8ba00-33c0-11eb-9d16-919a9fab3547.png)

https://www.dropbox.com/s/yazjtzw4y7h82ky/shark_retopo_02.blend?dl=0

**Comment by jlampel** [comment]
This seems to have been fixed and I no longer have an issue in the above file. We've also since added a way to select vertices behind the mesh if needed.
