### ISSUE TITLE
[BUG] Polypen snaps to vertices behind target mesh

### ISSUE THREAD

**Issue by benjaminghys** [CGCookie/retopoflow#803]
Retopoflow Version: 3.00.0 beta
Blender Version: 2.82a
Platform Version: Windows 10 - 64 bit

When creating a polygon with the polypen tool it snaps to existing vertices behind the target mesh (1).
turning off automerge fixes the snapping to the vertex behind the target mesh.
But then the vertex behind the target mesh gets snapped to the created vertex (2).

It can hard to see the geometry behind the target mesh since they get a little faded
(screenshot 1)
![image](https://user-images.githubusercontent.com/23158001/78907575-2c404200-7a81-11ea-90e3-508ac88e8a4c.png)
(screenshot 2)
![image](https://user-images.githubusercontent.com/23158001/78907684-4f6af180-7a81-11ea-818a-7de87e66563b.png)

**Steps to reproduce:**
- Have retopologized geometry behind polygons of target mesh.
- Move polypen tool near a faded vertex that's behind a part of the target mesh.

**Comment by vxlcoder** [comment]
Can you double check that the normals on your source mesh are facing out?

**Comment by benjaminghys** [comment]
Yes almost all of them are, only a few (<5) that are pointing inwards.
Could it be because of those few it misses?
![image](https://user-images.githubusercontent.com/23158001/78923196-1f7b1880-7a98-11ea-92f9-96eb424bc9ff.png)

This is the inside of the mesh I'm drawing on
![image](https://user-images.githubusercontent.com/23158001/78923275-3883c980-7a98-11ea-8054-81d4cd0d0a65.png)

Maybe I should mention that the object the geometry is drawn on is different from the one I'm trying to draw on, they're separate meshes

**Comment by vxlcoder** [comment]
I'm a little confused about "Maybe I should mention that the object the geometry is drawn on is different from the one I'm trying to draw on, they're separate meshes".  Can you provide a few more details?

RetopoFlow assumes that all of the normals are outward facing, so having some inward facing might cause some problems for some tools.

Can you share your .blend file with us?  email to retopoflow@cgcookie.com

**Comment by benjaminghys** [comment]
With the separate meshes I mean that the red is one mesh in blender and green is another mesh in blender.

![image](https://user-images.githubusercontent.com/23158001/78931126-b00c2580-7aa5-11ea-92ba-14ee02aea998.png)

I will need to ask for confirmation before being allowed to send the .blend file.
Upon making a lasso selection of the area and deleting all other vertices + trying it again the tool seems to work as intended.

After some more testing I think I might be on to the issue, the mesh I'm retopologizing is very big, so when deleting all other verts of the mesh the scaling changes inside of RF (as I heard from the livestream about v3.0 to keep consistency)
So when I keep the lasso selection and the extends of the mesh (so that the bounding box doesn't change) I was able to reproduce it the issue I'm having.

I'm guessing it's a clipping issue, but I would have no idea what to change to avoid this.

**Comment by vxlcoder** [comment]
hi @benjaminghys.  I'm finally getting back to this issue.  Are you still having these problems?  If so, would you mind sharing the .blend file with us by emailing to retopoflow@cgcookie.com.  then I can take a closer look.  Thanks!

**Comment by vxlcoder** [comment]
finally able to replicate!  working on a fix

**Comment by vxlcoder** [comment]
ok, @benjaminghys, I think I've got a fix for you!

the parameters for testing whether a vertex is visible or not were set for working at "normal" scales.  the problem is that you're model is much tinier than what is considered "normal".  so, i've added some UI settings to the options window (see screenshot below) to adjust these visibility testing parameters.  you can adjust them individually as needed (i don't give much explanation because it gets a bit technical), but i'd recommend simply using the presets.  when you're working in tight spaces, click the `Tiny` preset button.  when you're working on normal-sized objects, click the `Normal` preset button.

![image](https://user-images.githubusercontent.com/3790699/81810984-e815e680-94f1-11ea-970b-7b4370e3ce7f.png)

Please let me know if you have any further problems or questions, or if this fix works for you.

thanks for your patience and help in this issue!

**Comment by vxlcoder** [comment]
another note: you do not need to apply scale or rotation on the source meshes!  (at least, you don't need to do that to solve this problem)

**Comment by benjaminghys** [comment]
How do I update retopoflow best? 
re-download it from the blender market?
I tried download the files from github from the branch you made for the issue, file size do differ about 4mb
when installing it and enabling it it spat out some errors:
`Traceback (most recent call last):
  File "E:\Program Files(x86)\Blender\2.82\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\__init__.py", line 38, in <module>
    from .retopoflow import retopoflow
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\retopoflow.py", line 29, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rf\rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "C:\Users\benja\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\config\options.py", line 33, in <module>
    from ..addon_common.common.blender import get_preferences
ModuleNotFoundError: No module named 'retopoflow.addon_common.common'
`

**Comment by vxlcoder** [comment]
will send you an email later today
