### ISSUE TITLE
PolyStrips: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by shaqualeek** [CGCookie/retopoflow#805]
crashed in some basic scene in 2.83 and also 2.9

```
Environment:

- RetopoFlow: 3.0.0β
- Blender: 2.83.13 master 2020-04-20
- Platform: Windows, 10, 10.0.18362, AMD64, Intel64 Family 6 Model 63 Stepping 2, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 970/PCIe/SSE2, 4.5.0 NVIDIA 445.87, 4.50 NVIDIA
- Timestamp: 2020-04-21 01:03:01.992271
- Undo: 

Error Hash: 3f270c00d41ca304368124d4ef4721e0

Trace:

- EXCEPTION (<class 'KeyError'>): 'bpy_prop_collection[key]: key "Layout" not found'
-     C:\Users\petrk\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rf\rf_blender.py
- 000 0282:restore_window_state() bpy.context.window.screen = bpy.data.screens[data['screen name']]
-     C:\Users\petrk\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rf\rf_ui.py
- 001 0335:blender_ui_reset() self.restore_window_state()
-     C:\Users\petrk\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rf\rf_blendersave.py
- 002 0071:save_backup() self.blender_ui_reset()
- 003 0049:check_auto_save() self.save_backup()
-     C:\Users\petrk\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rf\rf_states.py
- 004 0149:modal_main() self.check_auto_save()
-     .../common\fsm.py
- 005 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report!  will check into this

**Comment by vxlcoder** [comment]
@shaqualeek, i'm not sure why you're getting that error, but that code seems to be not doing anything useful so i commented it out in ^^ commit.

When you get a chance, can you check to see if you still get errors?

Thanks!

**Comment by shaqualeek** [comment]
Hi,
I did another test with current build of blender 2.9 - just a simple random sculpt on subdivided quad sphere and then took it into retopo. Did few contours, then tried to change resolution, which didn't work. and finally, after pressing exit button, it crashed/killed whole blender without any warning. I didn't save the scene of course :)

**Comment by vxlcoder** [comment]
i believe i've finally fixed (worked around) this bug!  if you get a chance, @shaqualeek, would you mind taking another look?

**Comment by vxlcoder** [comment]
grr... still seems broke on OSX Blender 2.83.  more testing needed...

**Comment by vxlcoder** [comment]
ok.  i believe i've really finally fixed this bug!

**Comment by shaqualeek** [comment]
cool! when can we expect the updated version?

**Comment by vxlcoder** [comment]
you can pull from GH at any time, but we're working on getting an official beta 2 released this weekend (if all goes well)
