### ISSUE TITLE
Installation problems

### ISSUE THREAD

**Issue by Duca-Simone-Luchini** [CGCookie/retopoflow#806]
Retopoflow Version: 3.0.0 beta 1

Blender Version/Hash: 2.82

Platform Version/Distribution: Windows 10
[DESKTOP-O6170R4.txt](https://github.com/CGCookie/retopoflow/files/4520559/DESKTOP-O6170R4.txt)

**QUESTION**

Can install addon but not activate and use it. In the screen shot (blue message above)  it seems to be activated but i can see it in the Addons panel and then I can not activate it. I followed this installation process from Reddit dedicate thread ;
1.Download v3.0.0-beta-1 from https://github.com/CGCookie/retopoflow/releases

2. extract and rename folder to "retopoflow"

3. (this is the weird/tricky part) You may notice that the "Addon_common" folder is empty. You need to download and extract the content of https://github.com/CGCookie/addon_common/archive/b280.zip into it.

4. rezip the folder and install normally from addon menu. 

{*https://i.postimg.cc/XJv1tXK3/Screenshot-9.png*}

{*[Retopology_Duca_01.zip](https://github.com/CGCookie/retopoflow/files/4520498/Retopology_Duca_01.zip)*}

**Comment by vxlcoder** [comment]
ack.  adding comments when GH is flaking out does weird things.

**Comment by Duca-Simone-Luchini** [comment]
Sorry Jon, but I am completely new in Blender world and Blender addons as well. I started 2 o 3  mouth ago with Blender 2.81, now I am on 2.82 and I simply would like how to install it properly to test it and eventually buy it, of course. 
I finally find the readme b280 but sincerely I didn't understand what it means... and I didn't find any info about installation. 
I don' t know what I have to to do..., sorry!
Anyway, if there is a possibility to install it and try it, I can absolutely contribute to improve it and to buy it when it will stable for Blender 2.8. Thank for your help!

**Comment by Duca-Simone-Luchini** [comment]
Hi Jon and many thanks for your replay,
sorry, but I am completely new in Blender world and Blender addons as well. I started 2 o 3  mouth ago with Blender 2.81, now I am on 2.82 and I simply would like how to install it properly to test it and eventually buy it, of course.
I finally find the readme b280 but sincerely I didn't understand what it means... and I didn't find any info about installation.
I don' t know what I have to to do..., sorry!
Anyway, if there is a possibility to install it and try it, I can absolutely contribute to improve it and to buy it when it will stable for Blender 2.8. Thank for your help!
________________________________
Da: Jon Denning <notifications@github.com>
Inviato: giovedì 23 aprile 2020 15:31
A: CGCookie/retopoflow <retopoflow@noreply.github.com>
Cc: Duca-Simone-Luchini <simone.luchini@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CGCookie/retopoflow] Installation problems (#806)


@Duca-Simone-Luchini<https://github.com/Duca-Simone-Luchini>, the latest version of RF is structured differently than previous, so you have to do a little more to install it from GH. This is noted in the readme in the b280 branch.

Specifically and technically speaking, RF has the addon_common repo added as a submodule, and git stores submodules as a reference, not as code / part of the RF repo. This is why you have that extra step.

Did you have any questions or other issues?

**Comment by Duca-Simone-Luchini** [comment]
Please help...

**Comment by vxlcoder** [comment]
note: we did not create the reddit post with the instructions, so we can provide no guarantees there.

which step of those instructions were you getting stuck on?

**Comment by Duca-Simone-Luchini** [comment]
Hi Jon,
I understand but I simply followed the provided instruction on reddit.
These installation instruction don't work and you also have not responsibility about them, okay, full comprehensive, but well, where can I find the installer and the installation info to do this operation?
I just download this beta 3.0.0. from here (https://github.com/CGCookie/retopoflow/releases) bit I receive this error:
[cid:900d9b5a-7e58-4f1a-bc1b-d3ffbe96f42e]

So, I really don't know what I have to do.
________________________________
Da: Jon Denning <notifications@github.com>
Inviato: venerdì 24 aprile 2020 17:42
A: CGCookie/retopoflow <retopoflow@noreply.github.com>
Cc: Duca-Simone-Luchini <simone.luchini@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CGCookie/retopoflow] Installation problems (#806)


note: we did not create the reddit post with the instructions, so we can provide no guarantees there.

which step of those instructions were you getting stuck on?

**Comment by vxlcoder** [comment]
what is the URL to the reddit post?

**Comment by Duca-Simone-Luchini** [comment]
<https://www.reddit.com/r/blenderhelp/comments/eljxj8/short_guide_on_getting_retopoflow_30_to_work_from/>

https://www.reddit.com/r/blenderhelp/comments/eljxj8/short_guide_on_getting_retopoflow_30_to_work_from/

________________________________
Da: Jon Denning <notifications@github.com>
Inviato: venerdì 24 aprile 2020 19:18
A: CGCookie/retopoflow <retopoflow@noreply.github.com>
Cc: Duca-Simone-Luchini <simone.luchini@hotmail.it>; Mention <mention@noreply.github.com>
Oggetto: Re: [CGCookie/retopoflow] Installation problems (#806)


what is the URL to the reddit post?

**Comment by vxlcoder** [comment]
thanks!

so, you said that you followed the instructions? which part of the instructions did not work?

In the end, you will need to download RF as a zip file, extract it, and rename the folder to `retopoflow`.  Then, download addon_common as a zip file, and extract it into the `retopoflow` folder.

```
retopoflow/
  addon_common/
    common/
      ...
    cookiecutter/
      ...
    ext/
      ...
  config/ ...
  help/ ...
  icons/ ...
  ...
```

once you have this, zip up the `retopoflow` folder to `retopoflow.zip`, and install that in Blender (edit > preferences > add-ons > install...)

**Comment by vxlcoder** [comment]
(basically, what i just wrote above is what is on that reddit post)

**Comment by vxlcoder** [comment]
but, without knowing which step is not working, i don't know how to help you with installing RF using this process.

**Comment by Duca-Simone-Luchini** [comment]
Hi Jon, I simply did all the steps suggested. I tried 5 times!
![Screenshot (11)](https://user-images.githubusercontent.com/57936586/80242323-7cb0c580-8665-11ea-929d-9b66ef4ec4ef.png)
How can you see above, on the blue line, it seems to be okay but in the Addons pane It isn't show.

**Comment by vxlcoder** [comment]
did you try restarting blender after installing addon?

another thing to test is to look in your add-ons folder for blender to make sure RF was actually installed.  alternatively, you can extract the RF.zip you created in the steps (or just copy the retopoflow folder) directly into the add-ons folder

`C:\Users\yourusername\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\`

**Comment by Duca-Simone-Luchini** [comment]
I just restarted and again installed many times... and of course deleted every time from add-ons folder..., now I try to install it directly “brute” there. See you soon

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Duca-Simone-Luchini** [comment]
Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by vxlcoder** [comment]
strange.  can you send an email to retopoflow@cgcookie.com?

**Comment by Duca-Simone-Luchini** [comment]
I mean, if I say that I followed the installation information on a Reddit thread, they will tell me that that is not an official CGCookie site and therefore they are not responsible ...
On your official Github channel you can download the "retopoflow-3.0.0-beta-1" version but if you install that file it won't work because the "addon_common" folder is empty. But there is no official installation information that tells you that you have to fill that empty "addon_common" folder with the contents of another folder called "addon_common-b280"! Unfortunately, you need to find those infos somewhere on the internet to understand that in that installation file retopoflow-3.0.0-beta-1 contains an empty "addon_common" folder that must be filled with the contents of another file, namely "addon_common -b280 "which, moreover, can be found in two different places (http://github.com/CGCookie/addon_common/tree/b280,,,m or in http://github.com/CGCookie/addon_common/archive/b280 .zip) and you cannot understand if they are the same files ...

I found this info on reddit but also in other sharing sites, where for example this installation process is recommended:
Download this => http://github.com/CGCookie/retopoflow/tree/b280 (for simplicity I call this X)
Then This => http://github.com/CGCookie/addon_common/tree/b280 (for Simplicity I call this Y)
Now Extract X somewhere in your pc, There are bunch of folders like retopoflow, scripts and addon_common
Open addon_common folder (it's empty)
Now copy the content of Y into the addon_common folder
Compress the X folder (.zip) and install it.

or yet another process, very similar, but slightly change the origins of the files from where you download:

Download (or git clone): http://github.com/CGCookie/retopoflow/archive/b280.zip

This URL will * ALWAYS * be the same as it's the current development branch for 2.8x. I * highly * recommend you add the date to the zip file so you can know when it was last updated.
Then download (or git clone): http://github.com/CGCookie/addon_common/archive/b280.zip
The same as above is also true here but date isn't as important.
Add the files of "addon_common- {git-commit-here}" to the folder "addon-common" of the first zip.
Then install it in blender as normal. Do this once a hour / day / week / etc for the most recent version.

All this huge confusion happens because, I repeat, there are no official installation documents of the addon on Github ..., there is no "Installation_read.me" file with written what are the steps to do to install this correctly addon and try to test it. So to install it you have to arrange to find unofficial information on the internet. I believe this is the problem.

Finally, I wonder if it is not the case that you contact cgcookie and explain what is going on since you certainly know much more than me and you know how to express yourself.

**Comment by Duca-Simone-Luchini** [comment]
I have however tried again right now to install once again following this procedure:
Download this => http://github.com/CGCookie/retopoflow/tree/b280 (for simplicity I call this X)
Then This => http://github.com/CGCookie/addon_common/tree/b280 (for Simplicity I call this Y)
Now Extract X somewhere in your pc, There are bunch of folders like retopoflow, scripts and addon_common
Open addon_common folder (it's empty)
Now copy the content of Y into the addon_common folder
Compress the X folder (.zip) and install it.

Well, the addon is finally visible on the Add-ons Panel but if I activate it, I get this error:
![Retopoflow install tree](https://user-images.githubusercontent.com/57936586/80270825-9d0b6f00-86bb-11ea-981e-45e2f70b95cd.png)

**Comment by vxlcoder** [comment]
try changing the name of `retopoflow-b280` folder to `retopoflow`.  Python does not like folder names with `-` in it.

**Comment by Duca-Simone-Luchini** [comment]
![Screenshot (13)](https://user-images.githubusercontent.com/57936586/80283060-521e4580-8715-11ea-96aa-7325b78c6e3a.png)
 this is the result

**Comment by vxlcoder** [comment]
Can you send me an email at retopoflow@cgcookie.com?

**Comment by Duca-Simone-Luchini** [comment]
I just did it.

**Comment by vxlcoder** [comment]
(This issue has been resolved over email)

For future viewers: Although there are instructions available, we haven't provided official instructions for creating an installable zip file of RetopoFlow directly from GitHub for a few reasons.  One reason: it can be tricky for some to get right.  Another: accidentally pulling down a commit/branch that is a work-in-progress (not ready for general public to try out) would present a bad experience for our users.

We do provide basic instructions for cloning the repository, but these instructions are meant for developers who have experience with git.

Note: you will get a properly created zip file with a Blender Market purchase, plus you'll get support.  This GitHub site is really meant for bug reporting, issue tracking, etc.

**Comment by AFWSI** [comment]
> 
> We do provide basic instructions for cloning the repository, but these instructions are meant for developers who have experience with git.
>



Are the git instructions up to date? Gave warning/errors on couple lines.

This gave warning/errors

```
git clone git@github.com:CGCookie/retopoflow.git retopoflow
```

This worked

```
git clone https://github.com/CGCookie/retopoflow.git
```

Tried both of these from the instructions for addon_common folder ,but both gave error

```
git submodule update --init --recursive
git submodule foreach git pull
```

Had to do this to get the addon_common folder

```
git clone https://github.com/CGCookie/addon_common.git
cd addon_common
git checkout b280
```

**Comment by vxlcoder** [comment]
Will double-check that the instructions are correct tomorrow morning

**Comment by vxlcoder** [comment]
everything works as expected on my machine* following exactly the instructions in the `readme.md`.

```
09:23@desktop:~/projects$ mkdir test && cd test
09:23@desktop:~/projects/test$ git clone git@github.com:CGCookie/retopoflow.git retopoflow
Cloning into 'retopoflow'...
remote: Enumerating objects: 194, done.
remote: Counting objects: 100% (194/194), done.
remote: Compressing objects: 100% (130/130), done.
remote: Total 13365 (delta 107), reused 121 (delta 53), pack-reused 13171
Receiving objects: 100% (13365/13365), 24.55 MiB | 8.48 MiB/s, done.
Resolving deltas: 100% (9716/9716), done.
09:23@desktop:~/projects/test$ cd retopoflow/
09:23@desktop:~/projects/test/retopoflow$ git checkout b280
Branch 'b280' set up to track remote branch 'b280' from 'origin'.
Switched to a new branch 'b280'
09:23@desktop:~/projects/test/retopoflow$ git submodule update --init --recursive
Submodule 'addon_common' (git@github.com:CGCookie/addon_common.git) registered for path 'addon_common'
Cloning into '/home/jon/projects/test/retopoflow/addon_common'...                                                                              
Submodule path 'addon_common': checked out '94d8fef46f0b676a923c59f82d2123fb599e790d'                                                          
09:24@desktop:~/projects/test/retopoflow$                                                                                                      
```

@AFWSI, please post the warnings/errors that you see when you try the commands.

**Comment by AFWSI** [comment]
> 
> 
> everything works as expected on my machine* following exactly the instructions in the `readme.md`.
> 
> ```
> 09:23@desktop:~/projects$ mkdir test && cd test
> 09:23@desktop:~/projects/test$ git clone git@github.com:CGCookie/retopoflow.git retopoflow
> Cloning into 'retopoflow'...
> remote: Enumerating objects: 194, done.
> remote: Counting objects: 100% (194/194), done.
> remote: Compressing objects: 100% (130/130), done.
> remote: Total 13365 (delta 107), reused 121 (delta 53), pack-reused 13171
> Receiving objects: 100% (13365/13365), 24.55 MiB | 8.48 MiB/s, done.
> Resolving deltas: 100% (9716/9716), done.
> 09:23@desktop:~/projects/test$ cd retopoflow/
> 09:23@desktop:~/projects/test/retopoflow$ git checkout b280
> Branch 'b280' set up to track remote branch 'b280' from 'origin'.
> Switched to a new branch 'b280'
> 09:23@desktop:~/projects/test/retopoflow$ git submodule update --init --recursive
> Submodule 'addon_common' (git@github.com:CGCookie/addon_common.git) registered for path 'addon_common'
> Cloning into '/home/jon/projects/test/retopoflow/addon_common'...                                                                              
> Submodule path 'addon_common': checked out '94d8fef46f0b676a923c59f82d2123fb599e790d'                                                          
> 09:24@desktop:~/projects/test/retopoflow$                                                                                                      
> ```
> 
> @AFWSI, please post the warnings/errors that you see when you try the commands.

It was 
`
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.
`

Did some searching online and I think I got it working now.
