### ISSUE TITLE
[PROPOSAL] Don't use a custom UI for windows, dialogs, panels..

### ISSUE THREAD

**Issue by xan2622** [CGCookie/retopoflow#810]
**Retopoflow Version:** 3.0.0 b2
**Blender Version/Hash:** 2.82a / rB375c7dc4caf4
**Platform Version/Distribution:** Windows 10
**Computer specs:** AMD Phenom II X4 965 quad core 3.4 Ghz - 16 Gb RAM - nvidia GTX 1070 8 Gb VRAM (driver: 442.19) - 512 Gb SSD

**Note**
The new beta 2 version of Retopoflow 3 reacts much faster (than the previous beta) on my computer. FYI, with the previous beta, I had slowdowns while rotating the viewport (which performed at about 6 FPS) and the different Retopoflow UI windows took 5 seconds to be displayed). This lag made the RetopoFlow 3 beta 1 almost unusable. Note that it was sluggish only while using RetopoFlow.

**Issues**
1. What is really annoying is the RetopoFlow UI that obfuscates the rest of the Blender window. 

2. I understand that you wanted the RetopoFlow UI to help focus on the viewport but RetopoFlow makes it impossible to use other tools at the same time (such as the *Poly Build* tool, or even other addons (retopology or not), addons that are usually displayed in the N panel sidebar. 

3. It also prevents the user to perform ordinary hotkeys such as CTRL+R (Loop Cut), or any of the hotkeys used by the _3D Viewport Pie menus_ addon, nor some other custom hotkeys. 

4. Btw, I noticed that, pressing X, it brings up a "Delete menu"... but with the style of the RetopoFlow UI. I use an addon ([Auto-Delete](https://blenderartists.org/t/auto-delete/678815)) that gets rid of this "Delete menu" and automatically detects if a vertex/edge/face has to be dissolved or deleted. RetopoFlow removes this ability.. 

5. It's also not possible anymore to change the Viewport Shading while doing Retopology... 

I am pretty sure you spent a lot of time coding this special UI (even for the Help windows) but *please* consider removing this custom UI. I am sure that all the Retopoflow panels (and tools) can fit in an ordinary (N panel) tab.

The Help could be accessible through a simple link, placed in the *Addon Preferences* :
[image1](https://user-images.githubusercontent.com/1732773/80306629-bba95d00-87c4-11ea-9633-89b19a183934.png) -- [image2](https://user-images.githubusercontent.com/1732773/80306654-e3002a00-87c4-11ea-8359-1921ea67e7b3.png)

Frankly, it would be better (imo) if RetopoFlow3 could be located in a tab, in the usual N panel.. for these 5 very annoying limitations.

**Comment by vxlcoder** [comment]
@xan2622, thanks for the proposal.

RF 1.x was originally designed to be it's own mode (like edit mode) for Blender 2.79 and previous versions.  RF 2.x was a revamp of that same design.  There were many reasons for this design decision, many reasons are technical and some UX.  But the biggest driving goal was to provide a complete retopology workflow experience.  And we think RF hits that goal.

Blender 2.8x has made significant changes to the "normal" way of doing tools and add-ons.  Moreover, there are many other new tools and add-ons that fit in the same space as RF (ex: poly build, auto-delete, but also the recent work by https://twitter.com/AFX_LAB).

Some of the technical reasons for original design still hold in the latest version of Blender, but we have had conversations with Blender core devs, and many of these lingering technical issues may go away.  We might be able to circumvent the remaining tech problems with significant changes to the workflow (ex: switching to "single use" tools similar to most of the standard Blender edit tools).

Note: there is great discussion and disagreement on what a retopology workflow looks like, even within the Blender community (https://developer.blender.org/T67997, https://developer.blender.org/T70267, https://developer.blender.org/D5919, search "retopology" on https://blender.community/c/rightclickselect/, others).

All that said, we are planning to reevaluate RF after a full release of RF that works correctly with Blender 2.8x and once Blender's development settles a bit more (2.8x changes brought on a significant number of severe bugs within Blender core that are still getting worked out, and many of these Blender bugs are contributing to RF's issues and cause for overhaul of RF core)

**Comment by jlampel** [comment]
Closing this out, but the weaknesses pointed out above are well noted and will be taken into account when planning future changes.

**Comment by xan2622** [comment]
I still hope you can reconsider putting your add-on's tools directly into the N panel, in Edit Mode (without obfuscating the whole Blender UI). 🤞
