### ISSUE TITLE
[BUG] Cannot initiate UI

### ISSUE THREAD

**Issue by chance-an** [CGCookie/retopoflow#811]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: b280 branch

Blender Version/Hash: {2.82}

Platform Version/Distribution: {Windows}

&nbsp;

**Issue:**

Upon clicking any button on the Retopoflow flyout, the following exception is thrown and UI cannot be initiated. 

Traceback (most recent call last):
  File "C_USER_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 134, in modal
    self._cc_actions_update()
  File "C_USER_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 168, in _cc_actions_update
    self.actions.update(self.context, self.event, print_actions=False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy_types.py", line 712, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OT_RetopoFlow' object has no attribute 'actions'

location: <unknown location>:-1

{*add any screenshots of the issue here*}

![image](https://user-images.githubusercontent.com/1046489/80335209-773fb080-8808-11ea-9ec6-055d3588d2ca.png)

&nbsp;

**How to Reproduce:**

- Click any button

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
hi @chance-an!

Is this a clone of the repo?  or did you install it by downloading and creating zips?  or is this from the Blender Market?

I made a recent major change to the repo, so this might be an issue due to not completely pulling everything.

**Comment by chance-an** [comment]
Hi vxlcoder 

It is a clone of the repo, I did pull down the addon_common submodule.

I also tried downloading the zip of this repo, and the zip of the addon_common repo, extracted to the addon_common subfolder. It does not really help. 

I can attach the zip file I have. 
[retopoflow.zip](https://github.com/CGCookie/retopoflow/files/4542151/retopoflow.zip)

Can you suggest what else might be needed?[

**Comment by vxlcoder** [comment]
did you pull the `b280` branch of the addon_common submodule?  it looks like it based on the zip your attached, but just making sure.

can you try toggling the system console (Blender > Window > Toggle System Console) before starting RetopoFlow.  there might be an error that occurred before this that is actually causing this error.

Please copy-paste the contents of the system console here.

Thanks for the report and for helping debug!

**Comment by chance-an** [comment]
Thanks for helping taking a look!

If I recalled correctly, I didn't pull b280 branch of addon_common manually, I was using `git submodule update --init --recursive` to pull whatever commit hash which the submodule attaches to. 

Checking the system console, there is indeed some errors before that, I will let you folks take a first look. 

```
Read prefs: C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
RetopoFlow: Initial load
(shaders) GLSL Version: 4.50 NVIDIA
RetopoFlow git: None
RetopoFlow options path: C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\RetopoFlow_options.json
(bmesh_render) GLSL Version: 4.50 NVIDIA
cgcookie updater verbose is enabled
cgcookie Updater: Read in JSON settings from file
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Warning: could not translate blender op "3D View | view3d.viewnumpad" to actions
Warning: could not translate blender op "3D View | view2d.ndof" to actions
Warning: could not translate blender op "3D View | view3d.view_center_cursor" to actions
Warning: could not translate blender op "Window | wm.window_fullscreen_toggle" to actions
CookieCutter handling exception caught while trying to "initializing Exception Callbacks, FSM, UI, Actions"
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-01 01:48:11.822954
- Count: 1
- Hash: 235503e636daf31c26b47376b70c39c6
- Info:
  - EXCEPTION (<class 'KeyError'>): 'bpy_struct[key]: key "select_mouse" not found'
  -     .../common\blender_preferences.py
  - 000 0040:mouse_select() return bpy.context.window_manager.keyconfigs.active.preferences['select_mouse']
  -     .../common\useractions.py
  - 001 0318:__init__() self.mouse_select     = bprefs.mouse_select()
  - 002 0265:get_instance() Actions._instance = Actions(context)
  - 003 0529:__init__() self.__dict__['_action'] = Actions.get_instance(context)
  -     .../common\ui_core.py
  - 004 2971:init() self.actions = ActionHandler(bpy.context, UI_Document.default_keymap)
  -     .../cookiecutter\cookiecutter_ui.py
  - 005 0077:_cc_ui_init() self.document.init(self.context)
  -     .../cookiecutter\cookiecutter.py
  - 006 0092:invoke() self._cc_ui_init()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'bpy_struct[key]: key "select_mouse" not found'
CookieCutter handling exception caught while trying to "call start()"
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-01 01:48:12.101952
- Count: 2
- Hash: 7bfbd955adda67d378a4d0d9a4e603c5
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'UI_Document' object has no attribute '_body'
  -     .../common\ui_core.py
  - 000 3007:body() return self._body
  -     C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rf\rf_helpsystem.py
  - 001 0042:reload_stylings() Globals.ui_document.body.dirty('Reloaded stylings', children=True)
  -     C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\retopoflow.py
  - 002 0064:start() self.reload_stylings()
  -     .../cookiecutter\cookiecutter.py
  - 003 0096:invoke() try: self.start()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'UI_Document' object has no attribute '_body'
CookieCutter handling exception caught while trying to "starting UI"
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-01 01:48:12.103947
- Count: 3
- Hash: 7af8b755a46c412833241e8a2da8cbdc
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_OpenQuickStart' object has no attribute '_space'
  -     C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     .../cookiecutter\cookiecutter_ui.py
  - 001 0120:_cc_ui_start() self._handle_preview   = self._space.draw_handler_add(preview,   tuple(), 'WINDOW', 'PRE_VIEW')
  -     .../cookiecutter\cookiecutter.py
  - 002 0098:invoke() try: self._cc_ui_start()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 'VIEW3D_OT_RetopoFlow_OpenQuickStart' object has no attribute '_space'
Traceback (most recent call last):
  File "C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 134, in modal
    self._cc_actions_update()
  File "C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 168, in _cc_actions_update
    self.actions.update(self.context, self.event, print_actions=False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy_types.py", line 712, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OT_RetopoFlow_OpenQuickStart' object has no attribute 'actions'

location: <unknown location>:-1

location: <unknown location>:-1
Error: Traceback (most recent call last):
  File "C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 134, in modal
    self._cc_actions_update()
  File "C_USERS_FOLDER\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\cookiecutter\cookiecutter.py", line 168, in _cc_actions_update
    self.actions.update(self.context, self.event, print_actions=False)
  File "C:\Program Files\Blender Foundation\Blender 2.82\2.82\scripts\modules\bpy_types.py", line 712, in __getattribute__
    return super().__getattribute__(attr)
AttributeError: 'VIEW3D_OT_RetopoFlow_OpenQuickStart' object has no attribute 'actions'

location: <unknown location>:-1

```

**Comment by vxlcoder** [comment]
addon_common: perfect.  thanks!

console: exactly what I needed.  not sure why `select_mouse` is not found.  will dig into this.  are you using Blender 2.82a or 2.82?

**Comment by vxlcoder** [comment]
@chance-an I think this issue should be fixed now.  if you get a chance, can you try pulling and confirming for me?  thank you!

presently, the left/right mouse selection option is not used (still wip!), but it will be soon!

**Comment by chance-an** [comment]
Thanks @vxlcoder I can see the UI now. But like you said, left/right mouse doesn't really do anything. Say in the Contours tool, I can't really cut a contour with LMB at all. So basically the whole thing does not quite do anything in 2.82a, is my understanding correct?

**Comment by vxlcoder** [comment]
sorry.  what i meant was this: whichever is your normal selection button, whether left or right, doesn't matter yet.  I'm still working on adding leftmouse selection.

but everything else _should_ work.

to create a new contours cut, or polystrips strip, or whatever, use CTRL+LMB.

(see help for more details)

**Comment by chance-an** [comment]
Thanks for reminding me that. Everything looks pretty good now. Thanks for fixing the bug!
