### ISSUE TITLE
[BUG] Relax, Tweak, and PolyStrips handles only work while Shift is held down

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#812]
Retopoflow Version: 3.0 beta 2

Blender Version/Hash: 2.82

Platform Version/Distribution: GitHub

&nbsp;

**Issue:**

Left clicking and dragging on PolyStrips handles does not move the handle or the control point. Shift left clicking will rotate the control point though. 

The Tweak and Relax tools also only work when the mesh is selected (and Selected masking is off) and Shift is held down. 

&nbsp;

**How to Reproduce:**

- Start RetopoFlow
- Draw a line with PolyStrips
- Try to move the control point with left click and dragging
- Shift left click and drag on the control point to rotate it
- Switch to the Relax or Tweak Tool
- Left click and drag on any part of the mesh
- Select the mesh and hold shift while left clicking and dragging

**Comment by vxlcoder** [comment]
this has been fixed!
