### ISSUE TITLE
**[BUG]** RF hangs up on setup

### ISSUE THREAD

**Issue by DeadlockAvenger** [CGCookie/retopoflow#814]
&nbsp;

Retopoflow Version: 3.0.0 BETA2

Blender Version/Hash: 2.82a

Platform Version/Distribution: Arch Linux

&nbsp;

**Issue:**

Retopoflow hangs up during setup on the following screen. During this state you're able to rotate around the model and exit the RF menu but you're not able to use any tools. After some time addon crashes the whole program and it has to be re-enabled on restart.

![hangup](https://user-images.githubusercontent.com/24703618/80850249-333f1800-8c1b-11ea-9156-054f969b544d.jpg)

&nbsp;

**How to Reproduce:**
Start Retopoflow > RF: Create new target

**Comment by vxlcoder** [comment]
Thanks for the report, @DeadlockAvenger.  Few questions:

- is this version from Blender Market?  how did you install it?
- can you try starting Blender from a terminal, and then copy-paste the output in terminal here?  I think there's a bug that might be reported there that will point me in the right direction.

Thanks!

**Comment by DeadlockAvenger** [comment]
I downloaded a zip of the b280 branch, unpacked it, added addon_common content from https://github.com/CGCookie/addon_common/archive/b280.zip, reziped it and installed the addon.

**Here's the output from the terminal:**

`RetopoFlow: Initial load
(shaders) GLSL Version: 4.50 NVIDIA
RetopoFlow git: None
RetopoFlow options path: /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/RetopoFlow_options.json
(bmesh_render) GLSL Version: 4.50 NVIDIA
cgcookie updater verbose is enabled
cgcookie Updater: Read in JSON settings from file
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
Warning: could not translate blender op "3D View | view3d.viewnumpad" to actions
Warning: could not translate blender op "3D View | view2d.ndof" to actions
Warning: could not translate blender op "3D View | view3d.view_center_cursor" to actions
Warning: could not translate blender op "Window | wm.window_fullscreen_toggle" to actions
RetopoFlow: setting up scaling factor
Unit scaling factor: 0.2
Loaded font "/home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/addon_common/common/fonts/DroidSans-Blender.ttf" as id 3
RetopoFlow: setting up target mesh
RetopoFlow: self.update_displace_option()
RetopoFlow: setting up source mesh(es)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: setting up symmetry data structures
RetopoFlow: setting up rotation target
RetopoFlow: setting up RetopoFlow states
RetopoFlow: setting up RetopoFlow tools
RetopoFlow: setting up grease marks
RetopoFlow: setting up drawing callbacks
RetopoFlow: setting up user interface
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-03 01:02:51.037799
- Count: 1
- Hash: bf1e0bf94397cfe78d10d46a090860ca
- Info:
  - EXCEPTION (<class 'UnicodeDecodeError'>): 'ascii' codec can't decode byte 0xce in position 29: ordinal not in range(128)
  -     /usr/lib/python3.8/encodings/ascii.py
  - 000 0026:decode() return codecs.ascii_decode(input, self.errors)[0]
  -     .../common/ui.py
  - 001 0386:set_markdown() if mdown_path: mdown = open(get_mdown_path(mdown_path), 'rt').read()
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_helpsystem.py
  - 002 0083:helpsystem_open() ui.set_markdown(ui_markdown, mdown_path=mdown_path)
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_ui.py
  - 003 0623:setup_ui() self.helpsystem_open('welcome.md')
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/retopoflow.py
  - 004 0161:setup_next_stage() stage_fn()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Caught exception in function "setup_next_stage" ("loading", "main")
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-03 01:02:51.038926
- Count: 2
- Hash: 3817aa6078d35db874eae4f9243b8889
- Info:
  - EXCEPTION (<class 'AssertionError'>): 
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/retopoflow.py
  - 000 0164:setup_next_stage() assert False
  -     .../common/fsm.py
  - 001 0054:run() return fn(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

CookieCutter_Exceptions._callback_exception_callbacks: 
CookieCutter caught exception while calling back exception callbacks: handle_exception
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-03 01:02:51.053082
- Count: 3
- Hash: edfd626a5bcb51585296152602650c08
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no attribute 'undo'
  -     /usr/share/blender/2.82/scripts/modules/bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_undo.py
  - 001 0096:undo_stack_actions() return [u['action'] for u in reversed(self.undo)]
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_ui.py
  - 002 0243:alert_user() get_trace_details(self.undo_stack_actions(), msghash=msghash, message=message_orig),
  - 003 0112:handle_exception() self.alert_user(title='Exception caught', message=message, level='exception', msghash=h)
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 004 0043:_callback_exception_callbacks() fn(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: 
CookieCutter caught exception while calling back exception callbacks: handle_exception
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-03 01:02:51.055920
- Count: 4
- Hash: edfd626a5bcb51585296152602650c08
- Info:
  - EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow' object has no attribute 'undo'
  -     /usr/share/blender/2.82/scripts/modules/bpy_types.py
  - 000 0712:__getattribute__() return super().__getattribute__(attr)
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_undo.py
  - 001 0096:undo_stack_actions() return [u['action'] for u in reversed(self.undo)]
  -     /home/deadlock/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rf/rf_ui.py
  - 002 0243:alert_user() get_trace_details(self.undo_stack_actions(), msghash=msghash, message=message_orig),
  - 003 0112:handle_exception() self.alert_user(title='Exception caught', message=message, level='exception', msghash=h)
  -     .../cookiecutter/cookiecutter_exceptions.py
  - 004 0043:_callback_exception_callbacks() fn(e)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
GitHub: Not reported, yet
GitHub: Not reported, yet 
`

**Comment by vxlcoder** [comment]
ok, @DeadlockAvenger.

I _think_ i fixed this issue.  when you get a chance, can you try getting the latest version to see if you're system runs into the same exception?

**Comment by DeadlockAvenger** [comment]
It should now work fine. Thanks!
