### ISSUE TITLE
[BUG] Errors when using "Industrial Standard" keymap

### ISSUE THREAD

**Issue by samkumo** [CGCookie/retopoflow#815]
Retopoflow Version: 3.0.0 beta-1
Blender Version/Hash: 2.82
Platform Version/Distribution: Github

&nbsp;

**Issue:**

On fresh install of the plugin, "RF: Create new target" and "Open Quick Start Guide" dumps if Blender keymap is set to "Industrial Standard" on launch.  Plugin works as intended after switching to default "Blender" keymap and curiously, creating RF target with default keymap and then switching back to "Industrial Standard" does work, but only until Blender is restarted again. Errors messages are provided below. 

"RF: Create new target"
![image](https://user-images.githubusercontent.com/19494589/80891439-4b1ea680-8cc4-11ea-9f74-778cdea00ab0.png)

"Open Quick Start Guide"
![image](https://user-images.githubusercontent.com/19494589/80891457-6984a200-8cc4-11ea-9b54-68d9f61873ee.png)

&nbsp;

**How to Reproduce:**

- Set keymap to "Industrial Standard" and restart Blender
- Install RetopoFlow 3.0.0 beta-1
- (restart if needed to complete plugin install)
- Attempt to create new Retopoflow via "RF: Create new target" button in the dropdown menu or click "Open Quick Start Guide".

**Comment by vxlcoder** [comment]
thanks for the report, @samkumo! 

will dive into this

**Comment by vxlcoder** [comment]
ok @samkumo.

I've reworked that code so it doesn't break RetopoFlow, but we haven't fully tested RF with Industry Compatible keymap selected.

if you use it, would you mind do the testing for us?  Letting us know what shortcuts don't work at all or as expected?

**Comment by samkumo** [comment]
I do use Industrial Compatible keymap and could do some testing over the weekend, but I have very little experience with the plugin itself.

**Comment by samkumo** [comment]
Tested the latest dev build 3.0.0 beta 2 and the same error still appears, plus there seems to be new bug with this version where the tool drawers in Retopology view are not displaying at all.

**Comment by jlampel** [comment]
The errors here appear to be fixed in 3.0, and any other quirks will be investigated in https://github.com/CGCookie/retopoflow/issues/902
