### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by dchotwolf101** [CGCookie/retopoflow#817]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.82.7 master 2020-03-12
- Platform: Linux, 5.3.0-7648-generic, #41~1586789791~19.10~9593806-Ubuntu SMP Mon Apr 13 17:50:40 UTC , x86_64, x86_64
- GPU: NVIDIA Corporation, GeForce GT 730/PCIe/SSE2, 4.5.0 NVIDIA 440.82, 4.50 NVIDIA
- Timestamp: 2020-05-04 00:45:02.078298
- Undo: insert, insert, insert, insert, select, insert, insert, insert, select, select

Error Hash: 4f26f6d57d9fefb008b1db5c85052259

Trace:

- EXCEPTION (<class 'AssertionError'>): unhandled type of other: None (<class 'NoneType'>)
-     .../common/maths.py
- 000 0186:__sub__() assert False, "unhandled type of other: %s (%s)" % (str(other), str(t))
-     /home/david/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rftool_polypen/polypen.py
- 001 0465:mergeSnapped() delta = Vec2D(self.rfcontext.actions.mouse - self.mousedown)
- 002 0526:modal_move() self.mergeSnapped()
-     /home/david/.config/blender/2.82/scripts/addons/retopoflow/retopoflow/rftool.py
- 003 0141:wrapper() ret = fn(*args, **kwargs)
-     .../common/fsm.py
- 004 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @dchotwolf101.

this should be fixed in the commit above.

**Comment by vxlcoder** [comment]
let us know if you're still having problems, though!
