### ISSUE TITLE
**[BUG]** (some) Shortcuts are not working

### ISSUE THREAD

**Issue by GomorrahDotD** [CGCookie/retopoflow#818]
Retopoflow Version: RetopoFlow 3.0.0ß2

Blender Version/Hash: Blender 2.82

Platform Version/Distribution: Windows

&nbsp;

**Issue:**

The main shortcuts for the tools (e.g q for contours, w, e etc) don't work, at least since the update to this version.
However, The shortcut in the contours tool to up/down the segment count (Shift + Up/Down or plus / minus) hasn't worked in my previous instalments and still doesn't. 
I will check if I can report any other shortcuts but for now, these are the main concerns. 

I am using the standard Blender keymap by the way but I tried out the other keymap presets as well just to make sure.

&nbsp;

**How to Reproduce:**

- Install RetopoFlow
- Start using RetopoFlow
- Check if the shortcuts work

**Comment by vxlcoder** [comment]
Thanks for the report, @GomorrahDotD.

How did you install RF?  Are you using the latest version from the Blender Market, or did you pull it from GitHub?

If from GitHub, we have recently switched the shortcuts for the tools to the numbers across the top of keyboard (not numpad numbers) in order to support traditional `r` for rotate keymap.  (still need to update the help system)

What other shortcuts are you trying?  Do any work?  Which do not?

**Comment by GomorrahDotD** [comment]
I pulled it from GitHub and installed everything like always (putting the content of the addons_common in the common folder etc).

Because I am working on a project for the moment I reverted back to an older version of RetopoFlow. When I am finished I can check out wich hotkeys work and which don't.

**Comment by vxlcoder** [comment]
thanks!

quick note: i did notice last night that a recent push introduced a bug.  will be working on that today

**Comment by cgvirus** [comment]
Hello Polystrip Brush Size (F) is also not working in 3.0 Beta 2

**Comment by vxlcoder** [comment]
nice catch!

**Comment by vxlcoder** [comment]
this should now be fixed in the latest commit.

i made a change to the widgets, so that the active widget changes based on context (about to insert, hovering selected geometry, etc.), which caused widget-related events to not occur.  now, if there are multiple widgets available, actions are passed through to allow to capture focus.

**Comment by cgvirus** [comment]
Many thanks! It's working now.

**Comment by vxlcoder** [comment]
are you still having this issue, @GomorrahDotD?

**Comment by GomorrahDotD** [comment]
@vxlcoder Sorry for my lack of interaction! I was busy with a different project. But now I am going for bug hunting. 
First of all, I haven't fully figured out how the whole thing here on GitHub works - still new to it - so I didn't pull any special files but I updated Retopoflow to the newest version.

I am just posting everything that catches my intention - without knowing if they are known issues -

**Issues**
_**General**_
- The Interface is really slow. I am speaking of 2sec reaction time after a button press minimum. However, the duration fluctuates. Sometimes it takes less time and almost reacts instantly, sometimes it needs longer. I think it depends on the size of the menu and the amount of content in it. It says UI FPS: 12.25 maybe that is useful piece of info. Working with shortcuts works best but unfortunately one has to access the options panel via the UI.

_**Options Menu**_
- The option "Escape to Quit" is not checked. But it quits when pressing Esc (When there is no other window to close)

- The value change in Normal Offset in "Target Drawing" does not change anything visually. Or maybe I am just blind.

- Setting the Alpha is great! But why does one have to change the alpha of the mirrored side for every component (Verts, Edges, Faces) individually? Could you add the option to set the alpha for the mirror side in general?

**_Contours_**
- No issues found. Every shortcut works. Perfect!

_**Poly Strips**_
- No issues found. Every shortcut works. Perfect!

_**Poly Pen**_
- No issues found. Every shortcut works. Perfect!

_**Relax**_
- No issues found. Every shortcut works. Perfect!

_**Tweak**_
- No issues found. Every shortcut works. Perfect!

_**Loops**_
- Shortcuts for "paint edge selection" do not work. LMB + Drag is used for Transforming and Ahift+LMB+Drag does not do anything at all

_**Patches**_
- No issues found. Every shortcut works. Perfect!

_**Strokes**_
- No issues found. Every shortcut works. Perfect!

I hope that provides lots of information! Thank you very much for the amazing work!

**Comment by vxlcoder** [comment]
fantastic feedback, @GomorrahDotD!  will work through this!

**Comment by jlampel** [comment]
Ok, the main issues here appear to be resolved in 3.0. If you run into any other trouble, please post it as a new issue. Thanks!
