### ISSUE TITLE
What is the purpose of Autosave

### ISSUE THREAD

**Issue by bennu69** [CGCookie/retopoflow#819]
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.0

Blender Version/Hash: 2.82

Platform Version/Distribution: iOS

&nbsp;

I have spent 12 Hrs work on retopflow remeshing a high detail body and head and having, the whole time I have had autosave freezing blender every 2 mins to save it...It has then caused blender to crash (yet again) and I have now had the pleasure of losing every single thing I have done. The autosave restore button is blacked out so I wondering what the purpose of autosave actually is given it has seemingly saved absolutely nothing. Its also worth ,mentioning that aswell as this amazing feature, the tweak and relax features don't function at all and I can't change any values in the settings. 
I feel completely mislead by the videos etc promoting this as revolutionary efficient software aimed at making it easier and "fun" to retopologize. ill leave reviews elsewhere but complete rubbish as far as im concerned and I won't be using it again.

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
I'm sorry for your troubles, @bennu69.  If you're willing, I would like to fix these problems!

Are you using version of RetopoFlow that's on the Blender Market or did you install it from GitHub?  A few of your issues might have been fixed, and we are planning a new beta version here in the next few days.

The auto save uses the Blender's auto save setting to know when to save.  If 2min is too often, you can adjust that in Blender > Edit > Preferences > Save & Load > Auto Save > Timer (mins).  Presently, we write to a different temp file than Blender, but this will be changed soon.  Beyond that, unfortunately, we do not have much control over how long save happens, but we're working on making it less interruptive.

In previous versions of RF/Blender, there was a bug that crashed Blender when trying to recover, but this appears to be fixed now, so the recover feature was reenabled in later versions of RF (will be in next beta).

As for Tweak / Relax, we have tested these tools as extensively as we can, but there might be scenes that contain meshes and/or settings that are outside our test cases.  If you're having issues with a particular fille, would you mind sharing your .blend file with us so we can investigate?  You can send it to retopoflow@cgcookie.com so it's not shared in public.

We have been continuing to improve the UI in terms of making it easier to use.  The latest version might have fixed this issue (changing values), but I'll look into it again further.

Thank you again for letting us know what isn't working for you with RF.  We know that RF works well for most users, and we want to bring you into that experience.

**Comment by vxlcoder** [comment]
I have rewritten auto save to be more intuitive.  I plan to revisit Relax/Tweak after RF 3 is released.
