### ISSUE TITLE
[BUG] Blender freezes after a few actions with RF enabled

### ISSUE THREAD

**Issue by Niskran** [CGCookie/retopoflow#820]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {3.0.0 beta}

Blender Version/Hash: {2.82a}

Platform Version/Distribution: {Windows 10 64bits}

&nbsp;

**Issue:**

Blender freezes after doing a few actions in RF mode (moving the camera, laying down polygons)
Issue occurs on a machine with an RTX 2070, Ryzen 5 3600 and 16GB RAM.
However it does not occur on a Surface Pro 4, running on an Intel HD GPU

![2020-05-11 12_56_13-Blender (Not Responding)](https://user-images.githubusercontent.com/24385748/81554356-ef6cb100-9386-11ea-99e4-afcabb099755.png)

cmd log:

`RetopoFlow: done with start
Loaded font "C:\Users\niskn\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\DroidSans-Blender.ttf" as id 3
Loaded font "C:\Users\niskn\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\OpenSans-Bold.ttf" as id 4
Loaded font "C:\Users\niskn\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\OpenSans-Italic.ttf" as id 5
Created new GPUOffScreen <GPUOffScreen object at 0x000001BE6F5490F0> 55 1586x905 for <UI_Element tagName="body">
GPUOffScreen needs resized from 1586x905 to 1586x931
Created new GPUOffScreen <GPUOffScreen object at 0x000001BE603EF790> 39 1586x931 for <UI_Element tagName="body">
~22.545203 fps  (4.435533 / 100 = 0.044355)
~1669.022654 fps  (0.059915 / 100 = 0.000599)
~3199.853522 fps  (0.031251 / 100 = 0.000313)
~15349.694419 fps  (0.006515 / 100 = 0.000065)
~15346.886206 fps  (0.006516 / 100 = 0.000065)
~1282.657851 fps  (0.077963 / 100 = 0.000780)
CookieCutter handling exception caught while trying to "draw window UI"
____________________________________________________________________________________________________
Exception Info
- Time: 2020-05-11 12:34:08.952769
- Count: 1
- Hash: 4d0b6a636b2163e33176eac2d8de36c9
- Info:
  - EXCEPTION (<class 'ZeroDivisionError'>): float division by zero
  -     .../common\ui_core.py
  - 000 3338:draw() self._draw_fps = self._draw_count / self._draw_time
  -     .../cookiecutter\cookiecutter_ui.py
  - 001 0113:postpixel() try: self.document.draw(self.context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
`

&nbsp;

**How to Reproduce:**

- Open new file, select default cube and enter RF. Move camera around for a bit and it will freeze at one point (less than 1 minute)

**Comment by vxlcoder** [comment]
thanks for the report, @Niskran!

This _should_ now be fixed in latest `b280` branch (see commit a2ab51f above).

This fix will be part of the next beta release
