### ISSUE TITLE
Add Tweak support to Contours

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#83]
Let's add support for Contours to use the Tweak tool.

**Comment by carter2422** [comment]
With Tweak being it's own operator now I'm tempted to suggest we no longer do this, and even go so far as to remove it from Polystrips. 

Thoughts?

**Comment by vxlcoder** [comment]
depending on the data structure of contours, we could have a *lite* version of tweak in contours similar to the one in polystrips (one that does simple changes), but focus very little attention on it.  i vote to delay removing the tweaking from both tools until we have a more integrated retopo ecosystem in place first

**Comment by carter2422** [comment]
@vxlcoder sounds good. I'm going to remove the milestone for this and just keep it open, then.

**Comment by carter2422** [comment]
Scrapping this issue. With Tweak being it's own tool now it's not really needed and might even get further addressed via #176
