### ISSUE TITLE
3.0 Official Release

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#830]
Items remaining for 3.0 release:

- [ ] improve Loops slide mechanic
- [ ] selection
  - [ ] Relax/Tweak
  - [ ] Copy single/single add from Loops into other tools
- [ ] squeeze any other performance out of UI??
- [ ] new tool icons?
- [ ] special, secret, new tools?
- [ ] scrolling
  - [ ] trackpad
  - [ ] visualize
- [ ] others??

**Comment by MaximStale** [comment]
Hello, you are best guys!

Can you drop your eye on this tread, please?

https://github.com/CGCookie/retopoflow/issues/789

**Comment by jlampel** [comment]
It's official 🎉
