### ISSUE TITLE
Strokes: Unhandled Exception Caught While Shift Scrolling

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#831]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: 3.0 beta 2

Blender Version/Hash: 2.82a

Platform Version/Distribution: GitHub

**Issue:**

Error caught while Shift Scrolling to adjust number of loops generated by the Strokes tool

**How to Reproduce:**

- Select one edge loop on the boundary of a mesh
- Draw a stroke parallel to the selection
- Hold Shift and scroll mouse wheel 

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.82.7 master 2020-02-12
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce GTX 1080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 432.00, 4.50 NVIDIA
- Timestamp: 2020-05-21 13:40:54.484737
- Undo: extrude strip, select, select, select, select, delete Faces, select, select, grab, select

Error Hash: bdf0874d3b4e92873b8009f880e91f8f

Trace:

- EXCEPTION (<class 'AttributeError'>): 'RFWidget_Default' object has no attribute 'size'
-     C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py
- 000 0675:extrude_strip() bmv0,_ = self.rfcontext.accel_nearest2D_vert(point=s0, max_dist=self.rfwidget.size)
-     C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rftool.py
- 001 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\jonat\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\retopoflow\rftool_strokes\strokes.py
- 002 0271:modal_main() self.replay()
-     .../common\fsm.py
- 003 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
should be fixed now

**Comment by jlampel** [comment]
Confirmed fixed!
