### ISSUE TITLE
Proposal: Pie Menu and alphabet letters shortcuts

### ISSUE THREAD

**Issue by cgvirus** [CGCookie/retopoflow#832]
Reason: 
- Retopolgy needs a **state of flow** as it's a laborious and repetitive task.
- Pie Menu is the fastest way for brain muscling to access the tool.
- Numbers are very far to reach as shortcut and it breaks the flow as ctrl key is the prime button for operation and numbers are direct reverse (specially 5-8).

Structure: pressing ctrl+tab will open all the tool for retopoflow. As the tools don't require any other subtools, it will be simply just the standalone tools. 

Alphabet letters as in tool name alphabets or option for custom shortcut would be great.

**Comment by cgvirus** [comment]
Here are some of my shortcuts which feels to functioning faster:

```
    # shortcuts to tools
    'contours tool': {'ONE','CTRL+ALT+C'},
    'polystrips tool': {'TWO','CTRL+ALT+P'},
    'polypen tool': {'THREE','CTRL+ALT+V'},
    'relax tool': {'FOUR','CTRL+ALT+X'},
    'tweak tool': {'FIVE','CTRL+ALT+T'},
    'loops tool': {'SIX','CTRL+ALT+Q'},
    'patches tool': {'SEVEN','CTRL+ALT+F',},
    'strokes tool': {'EIGHT','CTRL+ALT+B'},
    'stretch tool': {'NINE'},          # not ported from rf279, yet
    'grease pencil tool': {'ZERO'},    # not ported from rf279, yet 
```

**Comment by vxlcoder** [comment]
Thanks for your suggestions!

We are planning on visiting pie menus after the RetopoFlow 3 beta 2 release.

I'm not sure what you mean by "Numbers [...] break the flow as ctrl key is the prime button for operation and numbers are direct reverse (specially 5-8)."

As for your suggested additional shortcuts, we can definitely add letter shortcuts.  (we originally had these, but the `R` for Relax was conflicting with Rotate.  However, with your specific suggestions, I'm not sure how CTRL+ALT+C is easier than the top 1.  Maybe I'm missing something here.

**Comment by cgvirus** [comment]
Hi, Thanks for the response, 
- as we have to press ctrl always for doing any tool operation, our left hand little finger is always stuck to the west-south end region of the keyboard. 
Now the 5-0 numbers are at the top right and direct reverse of our left little finger. 

- Also we usually don't use those numeric keys for numbers, instead we use numpads). So for muscle memory it is a bit odd and that starts breaking the flow.
- Yes, 1-4 are in comfortable position though.
- As we are continuously pressing ctrl, CTRL+ALT+C or any alphabet in the left hand side becomes easy for muscle memory. for "1" we have to look down at your keyboard at least once.
- I am also using  CTRL+ALT+P for polystrip as this is the (init) tool for topology. 

BTW: These are all my and some of our colleges' personal preference as we are used to Blender keymaps in standard US destop keyboards a lot. May differ user to user. That's why a basic tool keymap function in preference might be great. Although we can tweak it in keymaps.py. But may be end users will find it difficult.

**Comment by vxlcoder** [comment]
Ok.  I think I understand now.

Yes, we are looking at better ways of handling keymaps (maybe moving into Blender > Edit > Keymaps?).  Glad that you're comfortable jumping into the keymaps file and modifying it!

will look at more options after the release, but in the meantime feel free to post more to this thread!

**Comment by cgvirus** [comment]
Yes, Blender>Keymaps can be a good place for it. If there are other dependencies to compile then may be in preference>addon>Retopoflow > addon kemaps [] will be much more easier.
Here is a thread for some boilerplate:
https://blenderartists.org/t/keymap-for-addons/685544/19

**Comment by jlampel** [comment]
A pie menu was added to the latest release!

**Comment by cgvirus** [comment]
Thanks folks for the hard works! Feels Awesome!
