### ISSUE TITLE
[BUG]I can´t rotate and zoom the camera with MMB

### ISSUE THREAD

**Issue by neoanimator** [CGCookie/retopoflow#835]
Retopoflow Version: beta2

Blender Version/Hash: 2.82a

Windows 10 64-bit

Issue:
After clicking "RF: Create new target", an object named RetopoFlow is added to the scene and the cursor turns into a hand. I can´t rotate and zoom the camera with MMB

How to Reproduce:

Open blender 2.82a with the addon installed
Click "RF: Create new target"
The issue listed above occurs

**Comment by TehSethalophagus** [comment]
Same issue and build. The cursor changes to a hand - I can rotate and zoom with middle mouse but I can't interact with any UI elements or use any keyboard shortcuts.

**Comment by vxlcoder** [comment]
Thanks for the report, @neoanimator.

first question: how did you install RetopoFlow?  Did you follow instructions found elsewhere?  What steps did you take to create the install .zip file?  The reason I ask is that we have had several reports similar to this that were caused by incorrectly creating the .zip file to install.

**Comment by TehSethalophagus** [comment]
Not OP, but I followed the suggested steps (extracted the hosted addon-common zip into the retopoflow folder and rezipped before installing in Blender).

**Comment by vxlcoder** [comment]
Not sure what you meant by "OP".

Can you please post here the steps that you took?

Also, can you try doing the following:

- Open Blender
- Open the System Console by Window > Toggle System Console
- Start RetopoFlow
- Copy-paste all the stuff that is reported in the system console.

I'm fairly confident that this is an issues of installing incorrectly.

**Comment by TehSethalophagus** [comment]
I was just clarifying that I wasn't the "original poster" (OP)

I followed the steps listed here:
https://www.reddit.com/r/blenderhelp/comments/eljxj8/short_guide_on_getting_retopoflow_30_to_work_from/

The System Console just kicks out an endless stream of errors until I force quit. I'll attach that in a text document.

[Console.txt](https://github.com/CGCookie/retopoflow/files/4673880/Console.txt)

**Comment by neoanimator** [comment]
I followed this instrutions
[https://github.com/CGCookie/retopoflow/pull/800/files](url)
this appear in the system console when start Retopoflow
Read prefs: C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\Blender 2.82\2.82\python
_______REgister previews
.. .ao
.. .ao_legacy
.. .bevel_mask
.. .cavity
.. .curvature
.. .diffuse
.. .displacment
.. .dust
.. .id_element
.. .id_material
.. .normal_object
.. .normal_object_bevel
.. .normal_tangent
.. .normal_tangent_bevel
.. .paint_base
.. .position
.. .selection
.. .wireframe
RetopoFlow: Initial load
(shaders) GLSL Version: 4.50 - Build 26.20.100.6859
RetopoFlow git: None
RetopoFlow options path: C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow-b280\RetopoFlow_options.json
(bmesh_render) GLSL Version: 4.50 - Build 26.20.100.6859
cgcookie updater verbose is enabled
cgcookie Updater: Read in JSON settings from file
Warning: property 'release_confirm' not found in keymap item 'OperatorProperties'
addon_utils.disable: retopoflow-b280 not loaded
addon_utils.disable: retopoflow not disabled
Modules Installed (retopoflow) from 'C:\\Users\\mrrob\\Downloads\\2.80\\retopoflow.zip' into 'C:\\Users\\mrrob\\AppData\\Roaming\\Blender Foundation\\Blender\\2.82\\scripts\\addons'
RetopoFlow: Initial load
(shaders) GLSL Version: 4.50 - Build 26.20.100.6859
RetopoFlow git: None
RetopoFlow options path: C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\RetopoFlow_options.json
No options file
RetopoFlow version has changed.  Reseting options
(bmesh_render) GLSL Version: 4.50 - Build 26.20.100.6859
cgcookie updater verbose is enabled
cgcookie: Wrote out updater JSON settings to file, with the contents:
{'last_check': '', 'backup_date': '', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
Warning: could not translate blender op "3D View | view3d.rotate" to actions
Warning: could not translate blender op "3D View | view3d.rotate" to actions
Warning: could not translate blender op "3D View | view3d.move" to actions
Warning: could not translate blender op "3D View | view3d.zoom" to actions
Warning: could not translate blender op "3D View | view3d.dolly" to actions
Warning: could not translate blender op "3D View | view3d.view_pan" to actions
Warning: could not translate blender op "3D View | view3d.view_orbit" to actions
Warning: could not translate blender op "3D View | view3d.view_persportho" to actions
Warning: could not translate blender op "3D View | view3d.viewnumpad" to actions
Warning: could not translate blender op "3D View | view3d.view_axis" to actions
Warning: could not translate blender op "3D View | view2d.ndof" to actions
Warning: could not translate blender op "3D View | view3d.ndof_orbit_zoom" to actions
Warning: could not translate blender op "3D View | view3d.ndof_orbit" to actions
Warning: could not translate blender op "3D View | view3d.ndof_pan" to actions
Warning: could not translate blender op "3D View | view3d.ndof_all" to actions
Warning: could not translate blender op "3D View | view3d.view_selected" to actions
Warning: could not translate blender op "3D View | view3d.view_center_cursor" to actions
Warning: could not translate blender op "Screen | screen.screen_full_area" to actions
Warning: could not translate blender op "Window | wm.window_fullscreen_toggle" to actions
Warning: could not translate blender op "Window | wm.save_mainfile" to actions
RetopoFlow: setting up scaling factor
Unit scaling factor: 0.2
RetopoFlow: scaling view, sources, and target by 5.00
Loaded font "C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\DroidSans-Blender.ttf" as id 3
RetopoFlow: Setting up target mesh
RetopoFlow: self.update_displace_option()
RetopoFlow: Setting up source mesh(es)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures
RetopoFlow: Setting up rotation target
RetopoFlow: Setting up RetopoFlow states
RetopoFlow: Setting up RetopoFlow tools
RetopoFlow: Setting up grease marks
RetopoFlow: Setting up visualizations
RetopoFlow: Setting up user interface
RetopoFlow: Setting up undo system
RetopoFlow: Loading welcome message
Loaded font "C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\OpenSans-Bold.ttf" as id 4
Loaded font "C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\DejaVuSansMono.ttf" as id 5
RetopoFlow: Checking auto save / save
Loaded font "C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\addon_common\common\fonts\OpenSans-Italic.ttf" as id 6
RetopoFlow: done with start
RetopoFlow: scaling view, sources, and target by 0.20

**Comment by vxlcoder** [comment]
Thanks for this.

It looks like you might have RF installed twice

- `C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow-b280\`
- `C:\Users\mrrob\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\retopoflow\`

Try deleting both of these.  Then, reinstall it again.  Few things though: the .zip file must be named `retopoflow.zip`, and when it is installed the folder structure needs to look like this:

```
scripts\
  addons\
    retopoflow\
      addon_common\
        common\...
        cookiecutter\...
        ext\...
        ...
      config\...
      help\...
      icons\...
      ...
```

if it doesn't look like the above, you're install zip is incorrect.

note: installing from GH is not recommended for non-developers, because it can get technical and is easy to do incorrectly.

**Comment by TehSethalophagus** [comment]
In my case, I mistakenly downloaded the 3.0 beta from the [releases page
](https://github.com/CGCookie/retopoflow/releases)

vxlcoder's post made me realize I had Beta 1 not Beta 2. Deleting and reinstalling Beta 2 from the RetopoFlow github fixed my issue.

**Comment by neoanimator** [comment]
In my case I deleted both and reinstalled again but I can´t  rotate and zoom the camera yet, that is exactly the folder structrure that I have, I don't mentioned before that I can use all tools but I can't rotate and zoom the camera

**Comment by vxlcoder** [comment]
great to hear @TehSethalophagus!

@neoanimator, can you try restoring factory defaults on Blender, then reinstall RF, restart Blender, and then try starting RF to see if maybe another add-on or a keymap setting is interfering?

**Comment by neoanimator** [comment]
I disabled all add-ons, checked the keymap and restore factory settings, but rotation and zoom still don't work

**Comment by vxlcoder** [comment]
few other questions if you don't mind:

- has it ever worked correctly before?
- do you use only MMB to rotate and zoom, or do you use another key (like Alt, Ctrl, etc.)?
- do you have a relatively standard mouse?
- when you first started RF, did you see a Welcome Message?
- try resetting RF's settings: RF > Options > General > Advanced > Reset All Settigns, then exit RF and restart RF.

I have some other things to try, but I'd like to check these first.

Thanks!

**Comment by neoanimator** [comment]
yes I was working correcly before with RF beta1
I use only MMB
yes, it is a standard mouse
yes can see a welcome message
I reset all RT Settings already but I can't rotate, zoon and pan yet

**Comment by vxlcoder** [comment]
very strange, @neoanimator.

Let's try this:

- install the very latest version (just pushed a commit that you'll need)
- open system console (Blender > Window > Toggle System Console)
- start retopoflow
- check the checkbox: Options > General > Advanced > Debugging > Print actions.  this will cause RF to print to the system console (almost) all of the actions that you do.  try using MMB to rotate / zoom / etc.
- copy-paste all the text from the system console to here

**Comment by vxlcoder** [comment]
Ah!  I think I found it. @neoanimator, what is your Blender Translation Preferences set to?  I think the translations are interfering!  looking into it now

**Comment by vxlcoder** [comment]
i think this should now be fixed, @neoanimator!

I had missed these warnings in your console dump.

> `Warning: could not translate blender op "3D View | view3d.rotate" to actions`

if you could, please try the latest version (will need to update everything, including addon_common) and let me know if this fixed the issue or if it's still a problem.

Thank you for your help!

**Comment by neoanimator** [comment]
yes, it works, 
 you are the best 🥇  
Thank you
