### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by ezracove** [CGCookie/retopoflow#839]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.82.7 master 2020-03-12
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 8 Stepping 2, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.5.0 NVIDIA 445.87, 4.50 NVIDIA
- Timestamp: 2020-05-28 10:49:26.521420
- Undo: 

Error Hash: 9aa6097db5a35eda854dc39e78cb5c05

Trace:

- EXCEPTION (<class 'KeyError'>): 'keyboard repeat delay'
-     C:\Users\Ezra\AppData\Roaming\Blender Foundation\Blender\2.82\scripts\addons\RetopoFlow\config\options.py
- 000 0346:reset() del Options.db[key]
-     <string>
- 001 0001:<module>() 
-     .../common\utils.py
- 002 0175:run_it() return exec(action, f_globals, f_locals)
- 003 0180:run_it() raise e
-     .../common\ui_core.py
- 004 3007:_fire_event() if not cap: cb(details)
- 005 3022:_dispatch_event() self._fire_event(event, ui_event)
- 006 3493:mousedown_exit() self._under_mousedown._dispatch_event('on_mouseclick')
-     .../common\fsm.py
- 007 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @ezracove.  What were you doing at the time that caused this issue?  Also, how did you install RetopoFlow?

**Comment by ezracove** [comment]
Hi Jon,

I downloaded the latest version from Blendermarket, and installed from within Blender in Addon prefs. I confess I can’t recall if I manually removed the previous version of the 3.0 beta first.

The error occurred while I had PolyPen active, went to Options-General and clicked on Reset Keyboard Settings.

Ezra

**Comment by vxlcoder** [comment]
thanks for the quick reply!  i think i know what's the problem

**Comment by vxlcoder** [comment]
This is now fixed, and will be part of the next release.

Thanks!
