### ISSUE TITLE
[BUG] Tweak: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by swilde** [CGCookie/retopoflow#847]
**Issue:**

retopoflow 3 beta from git head crashes after closing the Welcome dialogue.

**How to Reproduce:**

- Install from b280 branch in blender 2.83.
- Start Retopoflow and close welcome dialogue

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- RF git: b280 529b1b548e3d8082db08e1e6affbdb9c51cd6d3c
- Blender: 2.83.0 master 2020-06-03
- Platform: Linux, 5.7.4-arch1-1, #1 SMP PREEMPT Thu, 18 Jun 2020 16:01:07 +0000, x86_64, 
- GPU: NVIDIA Corporation, GeForce GTX 750 Ti/PCIe/SSE2, 4.5.0 NVIDIA 440.82, 4.50 NVIDIA
- Timestamp: 2020-06-24 17:56:55.760661
- Undo: 

Error Hash: a135cb2aabcc123da3d68c9f6212b756

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'forId'
-     .../common/ui_document.py
- 000 0461:mousedown_exit() if self._under_mousedown.forId:
-     .../common/fsm.py
- 001 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report! Will take a look tomorrow morning.

**Comment by swilde** [comment]
With the latest Versions from the b280 branch:
retopoflow: 75dcce45eca652b0fb2d71cea374295f59473006
addon_common: dfbc8a2b70e3f595fe818d9d8b64009bbaddbad0
this seems to be fixed...
