### ISSUE TITLE
UI Visualization Bug

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#853]
viz bug when hovering tables in mdown

![image](https://user-images.githubusercontent.com/3790699/86221722-46a32c80-bb53-11ea-812a-f5008f847c30.png)

**Comment by isuruwelagedara** [comment]
UI Render issue  

![Screenshot 2020-08-02 at 1 34 03 AM](https://user-images.githubusercontent.com/15871770/89109590-54a0e180-d460-11ea-9921-24e9cf4081a7.png)
![Screenshot 2020-08-02 at 1 33 23 AM](https://user-images.githubusercontent.com/15871770/89109591-57033b80-d460-11ea-9c45-3ba8c0a075b2.png)

**Comment by jlampel** [comment]
The original issue appears fixed, and the second issue mentioned is being investigated here: https://github.com/CGCookie/retopoflow/issues/879

**Comment by vxlcoder** [comment]
for those with this issue, can you please try the `v3.2.1` branch to see whether the committed changes improve this visual bug?  see [link](https://docs.retopoflow.com/addon_updater.html) for details.

also, if possible, can someone post a video capture of using RetopoFlow with this visual issue?  I have a few other hypotheses that I think a video might provide the right evidence.

in particular, can you capture the following in the video:

- start with default cube
- start RF
- move the main/poly count/options windows around the screen slowly
- try minimizing / restoring each of the windows
- create new geometry using one of the tools
- rotate the view around just a bit
- open the help menu
- slowly scroll through the help
- try resizing the entire blender window very slowly

i think doing the items above might expose what the issue _might_ be.  thank you!!
