### ISSUE TITLE
[BUG] I cannot install addon RetopoFlow_v3.0-beta2_Blender-2.8x correctly on Blender 2.83a

### ISSUE THREAD

**Issue by Lewiatan45** [CGCookie/retopoflow#854]
Retopoflow Version:  RetopoFlow_v3.0-beta2_Blender-2.8x
Blender Version/Hash: Blender 2,83a

Platform Version/Distribution: Blendermarket.com

&nbsp;

**Issue:**
Your plugin cannot be installed correctly at all on Blender 2.83a. 
I go to my preferences > Add on > Install > Choose the zip file and then enable it; exactly the way you described in FAQ. In Blender, I see the notification Retopoflow cannot start due to incorrect installation and tell me to reinstall it again. 

Before I updated the previous version of this addon to the newest one I did remove the old plugin.

![image](https://user-images.githubusercontent.com/26897892/86517082-4aba9d00-be26-11ea-9caa-cb245f974f52.png)

You should have kept all versions of this addon on the website so I could at least downgrade to the working version. 

&nbsp;

**How to Reproduce:**

- Remove old Retopoflow
- Save Blender 2.83a
- Open Blender 2.83a again
- Go to Preferences > Addons > Install and choose RetopoFlow_v3.0-beta2_Blender-2.8x.zip file.
- Enable it,
- You see notification RetopoFlow (broken)

**Comment by vxlcoder** [comment]
Thanks for the report. Quick question to get this resolved: did you download the zip from the blender market, or by some other method?

**Comment by Lewiatan45** [comment]
> Thanks for the report. Quick question to get this resolved: did you download the zip from the blender market, or by some other method?

From the Blendermarket website, I did wrote the source of the file in the report.

**Comment by vxlcoder** [comment]
Sorry I missed that!  (on mobile, so I missed that nite)

Next questions...

Are you on a windows machine?  If so, can you try opening the terminal (window > toggle console), then try enabling the add-on. There might be useful info printed there. If you are on a osx or Linux machine, do you know how to start blender from the terminal?

**Comment by vxlcoder** [comment]
Also, we have had some need to restart blender after installing and before enabling

**Comment by Lewiatan45** [comment]
I'm using Windows 10 64bit.

You need to be more specific what I'm supposed to do to open a console.

**Comment by Lewiatan45** [comment]
> Also, we have had some need to restart blender after installing and before enabling

That helped, I don't see "broken" notification anymore

**Comment by vxlcoder** [comment]
Great! So, problem is resolved?

Will add that note to the instructions. Thanks!

**Comment by Lewiatan45** [comment]
> Great! So, problem is resolved?
> 
> Will add that note to the instructions. Thanks!

It is.

I noticed another bug tho. The RetopoFlow Mesh object origin is not the same as source mesh and it's somewhere in the space instead. I had to snap RetopoFlow Mesh into origin on the source mesh.

**Comment by vxlcoder** [comment]
Glad to hear! Closing issue.

When you create a new target, the origin is placed at the 3d cursor (same as adding a new object like monkey).

If you have more issues, please create a new issue. Happy to help further.

**Comment by Lewiatan45** [comment]
Alright, but this is quite an illogical thing, to be honest. If you retopo a mesh, you want RetopoFlow mesh to be on the source mesh, not somewhere in the space because your 3D cursor was there. Hmmm.

Anyway, thank you for help :)
