### ISSUE TITLE
[BUG] Decreasing/Increasing segments count still does not work

### ISSUE THREAD

**Issue by EtudeinG** [CGCookie/retopoflow#858]
Retopoflow Version: 3.0.0 beta2

Blender Version/Hash: 2.83.2

Platform Version/Distribution: Win10

I bought your tool yesterday so I think I'm using the lastest version available.

Changing segments does not work with contours and only increasing with polystrips.

**Comment by vxlcoder** [comment]
yes, 3.0.0 beta2 is the latest version.  taking a look at it now!

**Comment by jlampel** [comment]
Closing out since this doesn't appear to be reproducible in the latest version.
