### ISSUE TITLE
[PROPOSAL] Order of the tools in the 3D view "Tools" panel

### ISSUE THREAD

**Issue by ilyafr37** [CGCookie/retopoflow#862]
Issue Template
-----------------------------------

Retopoflow Version: 2.0.3

Blender Version/Hash: 2.79.7

Platform Version/Distribution: Windows 7 SP1 Integral Edition, 6.1.7601, AMD64, Intel64 Family 6 Model 26 Stepping 5, GenuineIntel

&nbsp;

**Issue:**

Hi you !

Not a issue, just a proposal : would it be possible that the tools list (below, my 2nd screeen capture "PresentOrder"), have the same order than it is in the "PreferedOrder" capture : Q W E R T Y U I ?
I think it would be easier to remember !

I tried to concretise this idea, but I am not enough "pro" to modifiy the .py file(s)...

Thanks to take care of this idea, or tell me what and where I have to modifiy the .py syntax !

ILYA

![PreferedOrder](https://user-images.githubusercontent.com/38527057/92730828-9b91c900-f374-11ea-8fb9-06590b4d612a.JPG)
![PresentOrder](https://user-images.githubusercontent.com/38527057/92730832-9c2a5f80-f374-11ea-98c0-250c8c803fbc.JPG)

**Comment by vxlcoder** [comment]
should be an easy fix!  (i haven't opened 2.0.3 in a long while!)

**Comment by vxlcoder** [comment]
done!
