### ISSUE TITLE
[BUG] 'Loops' has no attribute 'hovering_sel_edge'

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#863]
Retopoflow Version: 3.0.0β3

Blender Version/Hash: 2.83.4 master 2020-08-05

Platform Version/Distribution: RF git: b280 f04a1f8975a7334502219a29703892234f184d57

**Issue:**

RetopoFlow immediately errored when started by this user: https://blendermarket.com/inbox/conversations/31833
If this was just because of a untimely GitHub download and has since been solved, please ignore! I have not yet been able to reproduce it myself. 

Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
GPU: ATI Technologies Inc., Radeon RX 580 Series, 4.5.13587 Core Profile Context 20.4.2 26.20.15029.27017, 4.60
Timestamp: 2020-09-22 21:09:46.310852
Undo: Error Hash: c9165672328c4042a4c7596d7cf60129
Trace:
- EXCEPTION (<class 'AttributeError'>): 'Loops' object has no attribute 'hovering_sel_edge'
- C:\Users\poten\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\retopoflow\retopoflow\rftool_loops\loops.py
- 000 0115:main() if self.hovering_sel_edge and not self.hovering_sel_edge.is_valid: self.hovering_sel_edge = None
- /common\fsm.py
- 001 0054:run() return fn(*args, **kwargs)

![image](https://user-images.githubusercontent.com/12982300/94465923-7d4e0a80-0175-11eb-9143-d32f07fe110b.png)

&nbsp;

**How to Reproduce:**

- Installed RetopoFlow 3.0.0β3 from GitHub
- Opened the below file
- Started RetopoFlow

[Tongue.zip](https://github.com/CGCookie/retopoflow/files/5294022/Tongue.zip)

**Comment by vxlcoder** [comment]
I was not able to replicate, but I'm fairly confident in the cause.  commit e518714 adds the `hovering_sel_edge` attribute.  ready for testing!

**Comment by jlampel** [comment]
Perfect, thank you! I still haven't found a way to replicate it either. I can send him the new build and re-open this issue if it's not fixed.
