### ISSUE TITLE
[BUG] RetopoFlow starts with wrong location for mesh

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#864]
Retopoflow Version: 3.0.0β3

Blender Version/Hash: 2.90.0 0330d1af29c0

Platform Version/Distribution: GitHub 9-28-2020

**Issue:**

Upon starting RetopoFlow, the mesh moves upwards (or the viewport camera moves downwards) and the mesh starts offscreen. Applying scale or location does not make a difference. There are no modifiers and the scene's scale is 1. I can't find anything unusual about this situation. It looks like RetopoFlow is actually grabbing the wrong location for the mesh, because using the numberpad '.' shortcut to zoom to selection zooms to where the mesh should appear rather than where it is displayed. 

&nbsp;

**How to Reproduce:**
- open the below file
- enter edit mode on the green retopo mesh
- start RetopoFlow

[Tongue.zip](https://github.com/CGCookie/retopoflow/files/5294176/Tongue.zip)

**Comment by vxlcoder** [comment]
interesting...  it has to do with "View Lock > Lock to 3D Cursor" in the N panel.

![image](https://user-images.githubusercontent.com/3790699/94500142-828a7400-01cc-11eb-95a3-6b17231e5c45.png)

will have to think about how to approach this....

**Comment by jlampel** [comment]
Whoa, haha I didn't even know that was a feature! Not sure when it would be helpful, but I guess people use it. I'll look out for that in the future!

**Comment by jlampel** [comment]
Perhaps view locking could be one of the things we check for on startup?

**Comment by vxlcoder** [comment]
added check + warning!

**Comment by vxlcoder** [comment]
leaving this issue with the warnings.  future versions of RF might not have this issue.
