### ISSUE TITLE
PC´s screen gets black

### ISSUE THREAD

**Issue by famotril** [CGCookie/retopoflow#866]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**
BUG
Retopoflow Version: {*add here*}
3.0.0 beta2
Blender Version/Hash: {*add here*}
2.83.1
Platform Version/Distribution: {*add here*}
Windows 10
&nbsp;

**Issue:**
PC´s screen gets black
{*enter your issue here*}
The full screen of the pc gets black, I do not mind Blender, I mind the full screen, and no way of getting it back normal again, you have to turn off pc to recover the visual of the screen (I tried opening task manager, pressing windows, pressing differents commands in the keyboard but you only see a full black screen). 

{*add any screenshots of the issue here*}
A full black image, that's all

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}
Not sure the exact moment, but after using a pair of hours Retopoflow, I was using Polypen and it happened. I restarted everything: pc, blender, and it happened again. I do not know if it is Polypen related or it could happen with other tools, as I was using all of them without problems for hours
{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
Thanks for the report, @famotril.

I'm quite perplexed by this issue, as it is the first time we've heard of something like this.

Is it the full screen that goes black or just Blender?  When it goes black, did you have Blender maximized or running full screened?  Have you tried it when Blender was windowed and filling the entire screen?

Just curious, but do you play 3D video games on your machine?  Do you sculpt in Blender using this machine?  Have you ever had the screen go black at any other time (not when using RF)?  I'm wondering if it is a graphics card or driver issue.  RF does use custom shaders and uses some graphics RAM, but it shouldn't be more than a modern day FPS game or sculpting.  What happens if you watch some of the shaders on [Shadertoy](https://www.shadertoy.com/)?

**Comment by famotril** [comment]
Hi, I am gonna reply one by one:
. All the screen goes black as if the screen were turned off.
. I had Blender maximized by pressing the button Maximize size in the top right corner.
. I did not try with Blender to maximize and filling the entire screen, as I use with the down taskbar of windows visible.
. Yes, I play all kinds of videogames including AAA, and I frequently sculpt in Blender in this machine.
. No, the first time in life the screen goes black. Indeed I changed the channel of the screen to other inputs: tv, another HDMI, and everything were right, but when getting back to the HDMI channel of the pc all was permanently black and I only could turn off the pc.
. My graphic card is AMD Radeon Saphire 390 8GB GDDR5.
. I did not know this web, but the images, shaders, and so on look ok and permanently moving.

I am saving frequently when using RF after that, and if I figure out what happened, or if it happens again I will notify here.

If you need more data or make more questions to solve the issue, please do it.

**Comment by vxlcoder** [comment]
Thanks for the report!  This is a very strange issue indeed.

I am wondering what will happen if you run RF with Blender windowed (not maximized or full screened), if the entire screen turns black or not.

Will wait to hear back from you or from anyone else if they have this same issue.

**Comment by famotril** [comment]
> Thanks for the report! This is a very strange issue indeed.
> 
> I am wondering what will happen if you run RF with Blender windowed (not maximized or full screened), if the entire screen turns black or not.
> 
> Will wait to hear back from you or from anyone else if they have this same issue.

I tried too with Blender windowed to see if this was the solution, but the black screen happens again. Three times today in total, always after a few minutes of using RF.

**Comment by vxlcoder** [comment]
Thanks for the feedback, @famotril.

When Blender is running not maximized or full screen, does the entire screen turn black?  Are you able to close Blender, do anything else outside Blender, alt+tab to another program, etc.?

When you start Blender, can you open the System Console (Window > Toggle System Console), make sure the two windows are not overlapping (much) if possible, then start RF.  Some text will get written to the system console.  Can you copy-paste that text here?

Thanks again for your help on this issue!  I'm sorry for the inconvenience.

**Comment by famotril** [comment]
Hi, I have to say that the issue is solved, it was due to AMD drivers in its card. Summarizing a lot, AMD does not know to fix their own drivers and I had to buy an NVIDIA card, where I happily use Retopoflow. Thanks and I close this case.

**Comment by vxlcoder** [comment]
I'm glad that the issue is resolved (but sad about AMD and your purchase to fix it).

Please let us know if you run into any other issues!
