### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Mirthra** [CGCookie/retopoflow#867]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.90.1 master 2020-09-23
- Platform: Darwin, 18.7.0, Darwin Kernel Version 18.7.0: Mon Aug 31 20:53:32 PDT 2020; root:xnu-4903.278.44~1/RELEASE_X86_64, x86_64, i386
- GPU: Intel Inc., Intel(R) Iris(TM) Plus Graphics 655, 4.1 INTEL-12.10.22, 4.10
- Timestamp: 2020-10-14 09:27:34.993795
- Undo: move after select, grab, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move, tweak move

Error Hash: 77e947c1959530ae7c00fc74b598b49f

Trace:

- EXCEPTION (<class 'AttributeError'>): Vector addition: (NoneType + Vec2D) invalid type for this operation
-     /Users/robertlantry/Library/Application Support/Blender/2.90/scripts/addons/RetopoFlow/retopoflow/rftool_polypen/polypen.py
- 000 0537:modal_move() xy_updated = xy + delta
-     /Users/robertlantry/Library/Application Support/Blender/2.90/scripts/addons/RetopoFlow/retopoflow/rftool.py
- 001 0141:wrapper() ret = fn(*args, **kwargs)
-     .../common/fsm.py
- 002 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Mirthra.  Will take a look!

**Comment by vxlcoder** [comment]
this issue should now be fixed!
