### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by deock90** [CGCookie/retopoflow#869]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.90.1 master 2020-09-23
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2070/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2020-10-17 14:15:38.047526
- Undo: move grabbed, select, select, select, insert, insert, select, insert, insert, select

Error Hash: 4f26f6d57d9fefb008b1db5c85052259

Trace:

- EXCEPTION (<class 'AssertionError'>): unhandled type of other: None (<class 'NoneType'>)
-     .../common\maths.py
- 000 0186:__sub__() assert False, "unhandled type of other: %s (%s)" % (str(other), str(t))
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\RetopoFlow\retopoflow\rftool_polypen\polypen.py
- 001 0542:modal_move() if (xy_updated - xy1).length < self.rfcontext.drawing.scale(options['polypen merge dist']):
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0141:wrapper() ret = fn(*args, **kwargs)
-     .../common\fsm.py
- 003 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report! I believe this is similar to a previous issue, which had been fixed. will double check soon

**Comment by vxlcoder** [comment]
this should now be fixed!
