### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by deock90** [CGCookie/retopoflow#870]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0β2
- Blender: 2.90.1 master 2020-09-23
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 1 Stepping 1, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2070/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2020-10-17 14:44:38.276084
- Undo: extrude L, select, select, select, select, select, select, insert, select, insert

Error Hash: a01870b8ae52a36a4e4f10b0948add53

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'link_edges'
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 000 0624:extrude_l() bmes = set(nverts[-1].link_edges) & edges
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Deock\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0262:modal_main() self.replay()
-     .../common\fsm.py
- 003 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report! will take a look at it

**Comment by deock90** [comment]
Retopoflow stopped working, but it saved all the work I had and I didn't lose any of the progress, that was excellent. Congratulations.

I would love if the Knife could be used, as it is very useful.

**Comment by jlampel** [comment]
This appears to be fixed. Please reopen or open a new issue if it gives you trouble in the future!
