### ISSUE TITLE
Guide mode

### ISSUE THREAD

**Issue by brunodemasi** [CGCookie/retopoflow#872]
###**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {*add here*}

Blender Version/Hash: {*add here*}

Platform Version/Distribution: {*add here*}

&nbsp;

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

**Comment by brunodemasi** [comment]
But does the "Guide mode" function still exist?

**Comment by brunodemasi** [comment]
![guide](https://user-images.githubusercontent.com/6616582/97801662-a4996b00-1c3e-11eb-9a53-38b243c98762.jpg)

**Comment by vxlcoder** [comment]
RF 2.x and 3.x currently do not have guide mode, because it was tricky to get it working in all cases. We will look back at that when 3.0 is officially released.

please direct any other questions to https://blendermarket.com/products/retopoflow or retopoflow@cgcookie.com.
