### ISSUE TITLE
[BUG] Polypen creates broken loop

### ISSUE THREAD

**Issue by igrCaveman** [CGCookie/retopoflow#874]
Retopoflow Version: 3.0.0 RC1

Blender Version/Hash: 2.90.1 / 3e85bb34d0d7

Platform Version/Distribution: BlenderMarket 

Issue:

Polypen creates broken loop

If i'm create polygon with 2 steps (select edge, ctrl+click another edge) - fine, but

**How to Reproduce:**

if i'm use polypen with 3 steps (select edge, ctrl+click at 1st vertex, ctrl+click at 2nd vertex), it creates polygon but with broken loop
(sorry my bad English)

![Sequence 01_4](https://user-images.githubusercontent.com/73773826/97809170-90348d00-1c95-11eb-9104-2b5ae124f3fd.gif)

**Comment by vxlcoder** [comment]
good catch and super useful videos! will take a look

**Comment by vxlcoder** [comment]
this issue should now be fixed!  thanks for reporting!
