### ISSUE TITLE
Contours: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by MartinB309** [CGCookie/retopoflow#875]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.0 RC1
- RF git: b280 1a39e6d89e3f16d54319bbfe3818b44bc9617da8
- Blender: 2.90.1 master 2020-09-23
- Platform: Windows, 10, 10.0.18362, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2080 Ti/PCIe/SSE2, 4.5.0 NVIDIA 457.09, 4.50 NVIDIA
- Timestamp: 2020-11-10 11:53:09.836325
- Undo: 

Error Hash: 4a38d406446d4bae36e99d5a51bc3170

Trace:

- EXCEPTION (<class 'PermissionError'>): [Errno 13] Permission denied: 'C:\\Program Files\\Blender Foundation\\Blender 2.90\\2.90\\scripts\\addons\\retopoflow\\RetopoFlow_options.json'
-     C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\retopoflow\config\options.py
- 000 0327:clean() json.dump(Options.db, open(Options.fndb, 'wt'), indent=2, sort_keys=True)
-     C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\retopoflow\retopoflow\rf\rf_states.py
- 001 0044:update() options.clean()
-     C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\addons\retopoflow\retopoflow\rf\rf_drawing.py
- 002 0059:predraw() self.update(timer=False)
-     .../common\drawing.py
- 003 1475:_call() for fn in self._fns[n]: fn(self.obj)
- 004 1480:_pre() self._call('pre')
- 005 1486:post3d() self._pre()
-     .../cookiecutter\cookiecutter_ui.py
- 006 0107:postview() try: self.drawcallbacks.post3d()
```

**Comment by vxlcoder** [comment]
thanks for the report, @MartinB309 .

it seems that the permissions for the RF addon is not set properly for RF to write to the options file.

can you give details on how you installed RF?  are you able to change the permissions of the `addons\\retopoflow` folder? alternatively, you can install RF in the user addon folder (`C:\Users\[profile]\AppData\Roaming\Blender Foundation\...`)?

**Comment by vxlcoder** [comment]
@MartinB309, were you able to check on the permissions of the folder, or try installing RF in the user addon folder instead?

Thanks!

**Comment by jlampel** [comment]
Closing for lack of response. If this continues to be an issue, please let us know!
