### ISSUE TITLE
Long lines are overlapping help box when Region Overlap enabled

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#88]
I'm guessing this is due to the spacing changes.

![screen shot 2015-01-12 at 3 27 39 pm](https://cloud.githubusercontent.com/assets/1648631/5711373/9aa6471e-9a6f-11e4-89b7-0190a07cc459.png)

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/10269517/690aac04-6aa8-11e5-8084-3a144890ee82.png)

I think we are good here.

**Comment by carter2422** [comment]
I still get a lot of overlap: http://cl.ly/dQhf

**Comment by carter2422** [comment]
Ah! It is only an issue when the `N Panel` is open.

**Comment by patmo141** [comment]
![image](https://cloud.githubusercontent.com/assets/2917743/10269539/097b79ac-6aa9-11e5-8531-9c862b04b0af.png)

hmm....no problem with N panel for me.  This may be a problem where the size calculations are wrong with a paticular font or something

**Comment by patmo141** [comment]
https://developer.blender.org/T46371

**Comment by vxlcoder** [comment]
it seems that this bug was a problem with settings.  @carter2422, when you figure out which setting caused this, let em know so we can report it to blender devs or fix it in our code.  (one option is to ship a ttf along with the tool, so we know exactly what font is getting used)

**Comment by carter2422** [comment]
I _think_ the settings is **Region Overlap**. Disabling it just fixed it for me. However, the weird bit is that Region Overlap doesn't always cause it.

**Comment by carter2422** [comment]
Correction, it doesn't always happen with Region Overlap **per session**. It's consistent within the session, though.

**Comment by vxlcoder** [comment]
I cannot reproduce this bug.  Can you @carter2422?

**Comment by carter2422** [comment]
@vxlcoder perhaps it's a Mac thing only? I can still replicate it. 

**With *Region Overlap* enabled**:
![screen shot 2017-01-03 at 1 06 49 pm](https://cloud.githubusercontent.com/assets/1648631/21619500/8f258394-d1b5-11e6-8103-ce952cd73dd5.png)


**Without *Region Overlap* enabled**:
![screen shot 2017-01-03 at 1 06 39 pm](https://cloud.githubusercontent.com/assets/1648631/21619505/96f1bf84-d1b5-11e6-9505-737621d588f6.png)

**Comment by vxlcoder** [comment]
hmmm. it seems that i can replicate on linux and osx; haven't tried win.  blf.dimensions appears to return different/incorrect values (~10% difference) if n panel is open and region overlap is enabled.

ex: "Contours Help (click to hide help):" is (186.046875, 11.625) if either n panel is closed or region overlap is off, but is (169.703125, 10.640625) when n panel is open and region overlap is on.

the t panel (tool shelf) seems to make no difference.

this appears to be a blender bug.

**Comment by vxlcoder** [comment]
yes.  playing in console, i can replicate this problem on osx and linux.  strangely, though, it reports different text sizes but only when t panel is open and n panel is closed.  will report to blender devs.

**Comment by vxlcoder** [comment]
reported: https://developer.blender.org/T50372

will update when we hear back from blender devs.

**Comment by carter2422** [comment]
Thanks for digging in and reporting the bug @vxlcoder

**Comment by vxlcoder** [comment]
turns out this is not a blender bug.  the problem is that the drawing order changes when settings are changed (region overlap, open/close panels, etc.), so something was changing the font size.  therefore, explicitly placing a blf.size() call before calling blf.dimensions() solved the problem.
