### ISSUE TITLE
[PROPOSAL] PolyPen quad insert vertex snapping

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#880]
Currently, quad-only mode in PolyPen snaps the quad using the center of the newly created edge. This is great for use cases where you want to connect two edges to make a face:

![image](https://user-images.githubusercontent.com/12982300/100028691-56dad300-2da4-11eb-8be4-37e9ddc30420.png)

However, it's very difficult to run along an edge like this, because the edge doesn't snap and the result is not auto-merged:
![image](https://user-images.githubusercontent.com/12982300/100028778-812c9080-2da4-11eb-9fff-3438231baed8.png)

It would helpful if the vertices of the newly created edge could also snap to vertices within the merge distance around them.

**Comment by vxlcoder** [comment]
if I understand correctly, that should be an easy fix

**Comment by vxlcoder** [comment]
looking more into this... 

![image](https://user-images.githubusercontent.com/3790699/100036325-02e4e400-2dce-11eb-9d51-2d4583f38906.png)

you're wanting the top green vertex to snap to that top white vertex because it is close?  where would that bottom green vert to go, then?

**Comment by jlampel** [comment]
Exactly! Ideally the bottom vert would jump up in proportion to keep the edge length the same, but frankly it would be fine too if it stayed in the same spot since the distance is going to be rather small in any situation.

**Comment by jlampel** [comment]
This is great - exactly what I was looking for!
