### ISSUE TITLE
[PROPOSAL] Use 'Select All Toggles' preference for deselecting all with Alt+A

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#881]
In Blender 2.8+, hitting A multiple times doesn't toggle select and deselect all by default. It's not A to select all and Alt+A to deselect all. RetopoFlow may not be catching this like other key bindings though because it's a user preference at the top of the Keymap section rather than a normal key binding (as far as I'm aware):
![image](https://user-images.githubusercontent.com/12982300/100030382-3d3b8a80-2da8-11eb-8546-0cb971a0928e.png)

It would be helpful if RF could know whether this is on or off and respond accordingly.

**Comment by vxlcoder** [comment]
Note: `A` will still select all / deselect all (toggle), but `ALT+A` now deselects all.
