### ISSUE TITLE
symmetry selection

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#886]
selection seems broken if accidentally working on the mirrored side.  would be best to allow selection on either side of the mirror, or to provide some feedback to the artist that they're on the mirrored side.

**Comment by jlampel** [comment]
Your previous idea of changing the cursor seems like it would work : https://github.com/CGCookie/retopoflow/issues/760
I can also edit the default alpha values of the mirrored side to make it more clear. Turning vertices off completely should be a good indicator.

**Comment by jlampel** [comment]
The mirrored side is now much more obvious so this should no longer be an issue 
![image](https://user-images.githubusercontent.com/12982300/122257946-5bbcbc80-ce85-11eb-9e82-56539d98abd5.png)
