### ISSUE TITLE
Console Error, when you try to create a new target without any object in the scene.

### ISSUE THREAD

**Issue by SavMartin** [CGCookie/retopoflow#893]
Console Error when you try to create a new target without any object in the scene.

Retopoflow Version: {*3.0.0!*}

Blender Version/Hash: {*2.83.9*}

Platform Version/Distribution: {*linux Mint 20.03*}

&nbsp;

**Issue:**

Error if you try create a retopo without a object selected

&nbsp;

**How to Reproduce:**

No object create, create a new target 

.config/blender/2.83/scripts/addons/retopoflow/__init__.py", line 166, in invoke
    return bpy.ops.cgcookie.retopoflow('INVOKE_DEFAULT')
  File "/blender-2.83/2.83/scripts/modules/bpy/ops.py", line 199, in __call__
    ret = op_call(self.idname_py(), C_dict, kw, C_exec, C_undo)
RuntimeError: Operator bpy.ops.cgcookie.retopoflow.poll() failed, context is incorrect

location: <unknown location>:-1

![Peek 25-11-2020 11-38](https://user-images.githubusercontent.com/30030642/100223834-ebb00e80-2f13-11eb-9abd-884a0c741760.gif)

**Comment by vxlcoder** [comment]
great catch. will get that fixed!

**Comment by vxlcoder** [comment]
this issue should be fixed, @SavMartin.

Thanks again for the report!
