### ISSUE TITLE
Strokes: terminology change and auto span feature

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#896]
ht: Daniel Bystedt

![image](https://user-images.githubusercontent.com/3790699/100271601-be6d5b80-2f27-11eb-97b7-d13bc25e504d.png)

In some areas it is really hard to control how many spans/crosses you get when inserting new edge strips. It often results in manually going back and removing spans/loops/crosses. It also seems that you can only get a minimum of 2 spans/crosses as you lay down a new stroke.

![image](https://user-images.githubusercontent.com/3790699/100271634-ce853b00-2f27-11eb-9132-b532044ba12f.png)

Image above shows “minimum of two spans”. The spans/crosses seem to “reset” after each stroke to a minimum of 2, even after you set it to crosses = 1

![image](https://user-images.githubusercontent.com/3790699/100271458-82d29180-2f27-11eb-87af-b1b7db07e9fd.png)

current (red):Contains the word “Crosses” which is not commonly used within “topology linguistics”. Perhaps it is common in “math linguistics”?

suggestion (green):

- “Crosses” changed to “spans”, which is more commonly used (spans of a curve etc)
- Auto spans = ON  would activate an automatic adjustments of amount of spans, just like the strokes tool is currently working. 
 When auto spans = OFF, the amount of spans that the user has set is explicitly used when laying down new strokes

**Comment by vxlcoder** [comment]
this now works for extruding strip!

**Comment by jlampel** [comment]
This looks great! As a last minor UI touch, could the Fixed Spans number option be replaced by a Brush Size option when the Insert Mode is set to Brush Size? Or, alternatively, could the option be disabled when it's set to Brush Size? That would help avoid any confusion.

**Comment by vxlcoder** [comment]
I added a brush size option, and there is code to disable the text boxes, but it's not working.  need to review the code to generate the composite UI elements (labeled text box, checkboxes, radio buttons, etc.)

**Comment by vxlcoder** [comment]
some UI stuff remaining, but this feature is working!
