### ISSUE TITLE
"Dissolve Edges" don't delete vertices

### ISSUE THREAD

**Issue by Taroslord** [CGCookie/retopoflow#904]
Retopoflow Version: 3.0.0

Blender Version/Hash: 2.91.0 (Official)

Platform Version/Distribution: Windows

**Issue:**
Dissolving[edited by author] an edge works for edges only, but not for vertices. Vertices will not be deleted.
See my screenshot.

![image](https://user-images.githubusercontent.com/55150926/100764769-004e4400-33f7-11eb-8821-d39c6d736086.png)

**How to Reproduce:**

- Try to dissolve an edge
- Edge vertices stay visible after dissolving the corresponding edge

**Comment by vxlcoder** [comment]
Thanks for the report, @Taroslord.

This is actually correct.  Note: we modeled delete/dissolve off what Blender does, and it does exactly the same thing.

If you want to "delete" the edge and the vertices, then use Dissolve Vertices instead.

**Comment by Taroslord** [comment]
You're basically right, but "dissolve edges" in retopoflow has the same problem and works in Blender itself.... Sorry I haven't mentioned this, please.

![image](https://user-images.githubusercontent.com/55150926/100767852-85872800-33fa-11eb-96d4-754342aee240.png)

**Comment by vxlcoder** [comment]
ah, I see.  below are other examples.  (left: blender, right: retopoflow)

before:

![blender](https://user-images.githubusercontent.com/3790699/100769311-da5e7a80-33c9-11eb-9dee-e698a7beec11.png) ![image](https://user-images.githubusercontent.com/3790699/100769663-5eb0fd80-33ca-11eb-8234-36a7ce4c853b.png)


dissolve edges (incorrect):

![blender](https://user-images.githubusercontent.com/3790699/100769333-e2b6b580-33c9-11eb-8895-2cdb136e64fe.png) ![image](https://user-images.githubusercontent.com/3790699/100769713-6e304680-33ca-11eb-9d61-921921b82533.png)


dissolve vertices (correct):

![blender](https://user-images.githubusercontent.com/3790699/100769524-2d383200-33ca-11eb-98ca-28879b1202e3.png) ![retopoflow](https://user-images.githubusercontent.com/3790699/100769510-24476080-33ca-11eb-8040-96764e17069f.png)

I'm thinking: all vertices of dissolved edges with exactly two edges should also be dissolved.

note: only two faces isn't enough.  in example below, the right selected vertex will have 2 faces after dissolve, but it _should_ not get dissolved.

![image](https://user-images.githubusercontent.com/3790699/100770555-645b1300-33cb-11eb-8ff2-50b7b60549b7.png)

example below shows this best:

![image](https://user-images.githubusercontent.com/3790699/100771112-04b13780-33cc-11eb-884c-e4d91428d34c.png) 
![image](https://user-images.githubusercontent.com/3790699/100771134-0c70dc00-33cc-11eb-9043-38e9e0bdc8b6.png)

**Comment by Taroslord** [comment]
So at the moment retopoflow results different, in compare to the regular Blender result when dissolving edges?
Do you plane to "fix" this?

**Comment by vxlcoder** [comment]
oh sorry, yes, we'll update RF to match what Blender does.  I will get to it as soon as I can.

**Comment by Taroslord** [comment]
> oh sorry, yes, we'll update RF to match what Blender does. I will get to it as soon as I can.

Great. Thank you a lot.

Greetings from Germany
Chris

**Comment by vxlcoder** [comment]
this should now be fixed!  thanks for the report, @Taroslord

**Comment by Taroslord** [comment]
> this should now be fixed! thanks for the report, @Taroslord

Thank you. I'm new to retopoflow. Where do I download the recent version? I bought it via Blendermarket.

**Comment by vxlcoder** [comment]
thanks for your support!

we will be releasing a new version later today.  once that happens, you can download it from bm or use the update button in RF blender menu.

let us know if you have any other issues.

we would also appreciate a review on bm when you feel you have used it enough to give a review.

**Comment by Taroslord** [comment]
I need some more time to learn the philosophy. I'm experienced in retopology since years and use 3D Coat normally. But in the recent time I don't like to switch between the apps, even if there is an Addon to do this for 3D Coat.
I'm curious what you guys have done and like the first steps in retopoflow. I use it for my client projects, so if I see something not working or I don't "like" I'll drop a line.

**Comment by jlampel** [comment]
I plan on creating a free course about retopology with RF early next year, so hopefully that will help answer those sorts of bigger questions

**Comment by jlampel** [comment]
This appears to work well! Closing out.
