### ISSUE TITLE
[BUG] RF doesn't start in Blender 2.80

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#905]
Starting RF 3.0 with Blender 2.80 will not work and then lock the Blender interface. This can be tested on the default scene. In 2.81 it works just fine. Since the latest LTS release is 2.83, I wouldn't consider this critical and we could just say we only support 2.83+ if it turns out large changes would be needed to make it work.

**Comment by vxlcoder** [comment]
@jlampel, do we want to support blender versions < 2.83?

**Comment by jlampel** [comment]
Whoops, just now seeing this - I really don't think it's worth it to worry about versions before the most recent LTS so I'll close this out.
