### ISSUE TITLE
Strokes: sometimes strokes generates twisted geometry

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#906]
![image](https://user-images.githubusercontent.com/3790699/100791864-cd508400-33e7-11eb-81ae-07c8a811ee66.png)

**Comment by jlampel** [comment]
This only seems to happen when drawing perpendicular to a single edge and in the opposite direction of the vertex order.

**Comment by vxlcoder** [comment]
this should be fixed now!

**Comment by jlampel** [comment]
Confirmed fixed!
