### ISSUE TITLE
[BUG] Inverted normals warning on default cube

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#910]
Contours will occasionally detect inverted normals on the default cube when slicing across it. I doubt folks will be retopoing the cube, but it's a good example of where the detection doesn't quite get it right. 

To reproduce, use contours and keep creating loops around the cube. It doesn't happen every time, but often enough that you'll probably get it within the first 10 tries. I have not yet been able to find any consistencies between the times it does happen. 

![image](https://user-images.githubusercontent.com/12982300/101071043-ef194a80-3550-11eb-866c-5d93316df74d.png)

**Comment by jlampel** [comment]
Here's an example of it happening with PolyStrips, where it seems to reliably happen if you end the stroke right on the corner:
![image](https://user-images.githubusercontent.com/12982300/101071835-0147b880-3552-11eb-92ad-850944af61c4.png)

**Comment by vxlcoder** [comment]
will take a look at that...

**Comment by vxlcoder** [comment]
commit 17e5611 _should_ improve this.

**Comment by jlampel** [comment]
Yes, this is much better! I was still able to get this when drawing a PolyStrip right to the edge, but I could not break it with Contours.

**Comment by vxlcoder** [comment]
fixed!

**Comment by jlampel** [comment]
Nice!
