### ISSUE TITLE
[PROPOSAL] Only show RF menu in Object and mesh Edit mode

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#912]
The RF menu appears in every 3D viewport, and it would be nice if it was only there in contexts where it makes sense. For example, it's not really helpful in Grease Pencil Draw mode, curve Edit Mode, or Vertex Paint mode and takes up a good amount of header space.

**Comment by vxlcoder** [comment]
should be done!

**Comment by jlampel** [comment]
Looks great!
