### ISSUE TITLE
Can't select elements in "tight" areas

### ISSUE THREAD

**Issue by Taroslord** [CGCookie/retopoflow#914]
**Retopoflow Version:** 3.0.0
Blender Version/Hash: 2.91.0 (Official)
Platform Version/Distribution: Windows

**Issue:**
I'm not able to select mesh elements in "tight" areas.
Even zooming in or out doesn't help.

**Screenshots:**
![image](https://user-images.githubusercontent.com/55150926/101168756-2fa1c280-363c-11eb-8f29-aaddf07b94c2.png)

![image](https://user-images.githubusercontent.com/55150926/101168798-421bfc00-363c-11eb-8c76-56a90042cd44.png)

Are there settings, to help me select something in tight areas?

**Comment by vxlcoder** [comment]
@Taroslord, could you share your .blend file?  you can share it with retopoflow@cgcookie.com

I believe this is a similar problem to some other issues of selecting geometry with thin surfaces / inward facing normals.  I'm thinking through a solution to the other problems now.  Having another data point might help find a better solution.

**Comment by Taroslord** [comment]
> @Taroslord, could you share your .blend file? you can share it with [retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com)
> 
> I believe this is a similar problem to some other issues of selecting geometry with thin surfaces / inward facing normals. I'm thinking through a solution to the other problems now. Having another data point might help find a better solution.

I can send you the file within the next days, but please don't share the mesh in any way or publish it, please.
I'll try to cut the high resolution model down to the area causing problems and send you this.

Thank you

**Comment by Taroslord** [comment]
> @Taroslord, could you share your .blend file? you can share it with [retopoflow@cgcookie.com](mailto:retopoflow@cgcookie.com)
> 
> I believe this is a similar problem to some other issues of selecting geometry with thin surfaces / inward facing normals. I'm thinking through a solution to the other problems now. Having another data point might help find a better solution.

For your info: My mail including the test file was just sent.

Thank you
Chris

**Comment by vxlcoder** [comment]
thanks for the .blend file, @Taroslord!

this issue _should_ be resolved in latest commit (8d8390d), or at least significantly improved.  if you can test, that would be great.  otherwise it will be in the next minor release.

**Comment by Taroslord** [comment]
If I want to test the changes: how I do this, please?
Just download the reated code and replace it locally on my workstation?
What is the best way to do this?

I'm new here.
Thank you!

**Comment by vxlcoder** [comment]
Here is a temporary link to an Blender installable zip file: [https://www.dropbox.com/s/p2yu4hu4rkbwsom/RetopoFlow_v3.00.2.zip?dl=0](https://www.dropbox.com/s/p2yu4hu4rkbwsom/RetopoFlow_v3.00.2.zip?dl=0)

**Comment by Taroslord** [comment]
I've tested the new version this morning. It works pretty well and I haven't found any issues, yet.

Thank you!

PS: Off topic question: Do you plan a "Fill with quads" tool? I know it from 3DCoat. There it's called "RFill". You can fill areas by using one click. This saves a lot of time.

![image](https://user-images.githubusercontent.com/55150926/102319614-77e5ac80-3f7b-11eb-8166-0d9e4b050760.png)

**Comment by jlampel** [comment]
Closing this out as it appears fixed in the latest version. 

@Taroslord It's possible to do a quad fill with the patches tool, but it does take marking the corners manually which is not speedy and it only supports simple grids. I've made a note that this is something we could improve. 

![image](https://user-images.githubusercontent.com/12982300/102829281-9d1f5400-439b-11eb-9da1-b3f7722117c2.png)
