### ISSUE TITLE
[BUG] Target object origin created at 3D cursor

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#917]
RF 3.0.2
Blender 2.91

The target object is created at the 3D cursor rather than at the world origin, which results in incorrect symmetry. 
![OA98d3URA4](https://user-images.githubusercontent.com/12982300/101697666-111d3c00-3a2d-11eb-84a5-6cc1927ca144.gif)

**Comment by vxlcoder** [comment]
this is by design, same as adding any 3d mesh. but not sure why the 3d cursor seems to jump.

**Comment by jlampel** [comment]
Gotcha, ok. False alarm then. The cursor stays in the same location - if I set it to 10 along the X, that's where it is in and after RF.
