### ISSUE TITLE
saving causes N panel to show and not rehide

### ISSUE THREAD

**Issue by vxlcoder** [CGCookie/retopoflow#920]
When saving, the N panel is shown right before save and it should rehide right after, but it does not.  this causes the N panel to draw strangely over the right hand side, covering RF options.

before save
![image](https://user-images.githubusercontent.com/3790699/101937979-a1d05500-3bb0-11eb-8dbe-47fdad1a881d.png)

after save
![image](https://user-images.githubusercontent.com/3790699/101938014-b14f9e00-3bb0-11eb-9cae-f600ca415c43.png)

**Comment by vxlcoder** [comment]
not sure how to reproduce this

shows up at 10:55 in https://youtu.be/-45vuesifUQ?t=655

**Comment by jlampel** [comment]
I haven't been able to replicate this either.

**Comment by jlampel** [comment]
Thanks to https://github.com/CGCookie/retopoflow/issues/450 , I noticed that the toolbar and sidebar do not hide when region overlap is disabled in preferences. That doesn't appear to be directly relevant since region overlap is definitely on in this screenshot, but I figured I'd mention it just in case.

**Comment by jlampel** [comment]
This happened to me today while hitting ctrl+s in an unsaved file in Blender 2.91 and RF 3.00.3. Here's the console output:

```
RetopoFlow: Reloading stylings
RetopoFlow: scaling view, sources, and target by 0.20
Error: Cannot open file untitled.blend@ for writing: Permission denied
UI: Buffering texture "close.png"
RetopoFlow: scaling view, sources, and target by 5.00
RetopoFlow: scaling view, sources, and target by 0.20
```

**Comment by vxlcoder** [comment]
ah, interesting.  not sure why you got the permission denied report, though

**Comment by jlampel** [comment]
That's not a RF problem, it's because I'm using a vanilla version of Blender and it defaulted to trying to save at C:\. It could be that any error or warning during saving though could be the cause of this particular issue. I'll see if I can find another error to try it on

**Comment by vxlcoder** [comment]
RF should still detect and report this in addition to handling it correctly.  If this consistently reproduces the original issue, this _should_ be an easy fix.

**Comment by jlampel** [comment]
It seems to be unrelated to the error. I was able to reproduce this one time and then not again after several tries and many restarts

**Comment by vxlcoder** [comment]
i'm going to close this issue for now.  will reopen (or create a new one) if it resurfaces again.  this might be already resolved with some recent changes.
