### ISSUE TITLE
New Change to Blender UI breaks addon installation

### ISSUE THREAD

**Issue by blessedcoolant** [CGCookie/retopoflow#921]
Today Blender made this update.
https://developer.blender.org/rBbec583951d736776d2096368ef8d2b764287ac11

As a result, the usage of wheel_scroll_lines in ui_document.py breaks the app installation and usage.

I currently bypassed it commenting out the scroll_wheel_lines usage which fixes the issue .. but this needs to be solved in a patch.

Just thought I'll let you guys know.

**Comment by vxlcoder** [comment]
thanks for the report. much too bad that it was removed. will fix this tomorrow

**Comment by vxlcoder** [comment]
this is now fixed!  thanks, @blessedcoolant!

**Comment by jlampel** [comment]
Looks good!
