### ISSUE TITLE
[BUG] Blender 2.91.0 crashes.

### ISSUE THREAD

**Issue by ca3games** [CGCookie/retopoflow#923]
Retopoflow Version: {*add here*}
3.0.1

Blender Version/Hash: {*add here*}
2.91.0

Platform Version/Distribution: {*add here*}
Lubuntu 20.10

**Issue:**
Blender crashes if I try to enable retopoflow.
Console gives this error.
RetopoFlow: Initial load
Aborted (core dumped)

**How to Reproduce:**
Just install from the snap store (sudo snap install blender --classic)
Add retopoflow from github releases.
Try to enable it.

**Comment by vxlcoder** [comment]
Thanks for the report, @ca3games.

Few questions:

- how did you install RF?
- can you try using Blender from blender.org instead of using snap?
- have you tried other versions of blender?
- what graphics card do you have, and do you have the very latest drivers installed?
- can you copy-paste everything that is reported to the Console when you run?  (there is a lot of other very useful data there that might help debug this issue)

**Comment by ca3games** [comment]
>How did u install
I downloaded from the github releases.

>blender.org
Just downloaded, same issue.

>have you tried other versions
There's another bug on 2.79 that prevent me from activating it.

>Graphics card
Ryzen 3200G with Vega 8

>latest drivers
No propietary drivers appear on the aditional drivers window.

>console
Read prefs: /home/cristian/.config/blender/2.91/config/userpr
found bundled python: /snap/blender/51/2.91/python
LLVM triggered Diagnostic Handler: Illegal instruction detecttion violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr5, imcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
LLVM triggered Diagnostic Handler: Illegal instruction detecttion violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr4, imcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
RetopoFlow: Initial load
Aborted (core dumped)

**Comment by vxlcoder** [comment]
sorry, not other versions of RF, but have you tried other versions of blender, like b283 or b290?

the `LLVM failed to compile shader  radeonsi: can't compile a main shader part` seems to point toward a graphics-related issue.

it's strange that there are no other details between the `Read prefs` and `found bundled python` lines.  That's where the graphics card details should be printed.

do you know which driver is installed?  at terminal, you can try `lshw -c video` to get some details (see [link](https://askubuntu.com/questions/23238/how-can-i-find-what-video-driver-is-in-use-on-my-system) for more)

**Comment by vxlcoder** [comment]
another thing to try: open Blender, switch to `Scripting` tab, in Python Console type the following, then copy-paste output here.

```
import bgl
bgl.glGetString(bgl.GL_VERSION)
bgl.glGetString(bgl.GL_SHADING_LANGUAGE_VERSION)
```

thank you for helping me debug this issue!

**Comment by ca3games** [comment]
>lshw -c video

  *-display                 
       description: VGA compatible controller
       product: Picasso
       vendor: Advanced Micro Devices, Inc. [AMD/ATI]
       physical id: 0
       bus info: pci@0000:08:00.0
       version: c9
       width: 64 bits
       clock: 33MHz
       capabilities: pm pciexpress msi msix vga_controller bus_master cap_list rom
       configuration: driver=amdgpu latency=0
       resources: irq:46 memory:e0000000-efffffff memory:f0000000-f01fffff ioport:e000(size=256) memory:fcc00000-fcc7ffff memory:c0000-dffff

**Comment by ca3games** [comment]
> import bgl
> bgl.glGetString(bgl.GL_VERSION)
'4.6 (Core Profile) Mesa 20.2.1'

> bgl.glGetString(bgl.GL_SHADING_LANGUAGE_VERSION)
'4.60'

**Comment by vxlcoder** [comment]
thanks!  the `amdgpu` is the open source graphics driver for AMD Radeon cards.  it probably works with your particular card, but I cannot confirm.  AMD does have a closed-source proprietary driver, but the open source version might be just fine.

Do you play video games on this machine, or have you use blender's shader nodes, or more complicated materials using Eevee?  (wondering if more complex shaders compile just fine in other contexts)

**Comment by ca3games** [comment]
I haven't used this driver for anything advanced yet.
If you suspect is a driver issue, can you point me how to install the propietary AMD drivers?

**Comment by vxlcoder** [comment]
i think i might be wrong on the proprietary driver comment...

Would you mind trying eevee?  ex: on new scene, add a new material to default cube, then switch render to `Rendered`.  (i changed the base color of material, but that's not necessary)

![image](https://user-images.githubusercontent.com/3790699/102512847-805fe500-4058-11eb-8a4d-a725156395e6.png)

alternative: try visiting one example on [shadertoy](https://shadertoy.com).  for example, [Sirenian Dawn](https://www.shadertoy.com/view/XsyGWV)

**Comment by ca3games** [comment]
I switched to eeve without issues, but still blender crash at activating retopoflow.

Also, the shadertoy has no issues, is a red planet.

**Comment by vxlcoder** [comment]
ok.  here's another thing to try if you don't mind.  first uninstall RF, then close Blender.  Download RF linked below (contains a few updates but also some debugging info).  Run Blender from the terminal (same as before), and then install and enable RF.  then try starting RF.  close completely out of Blender (if it doesn't just crash)  the terminal will have a bunch of text printed out.  copy-paste everything here.

https://www.dropbox.com/s/p2yu4hu4rkbwsom/RetopoFlow_v3.00.2.zip?dl=0

**Comment by vxlcoder** [comment]
oh!  when you run Blender, can you add `--debug-gpu-shaders` parameter first?

ex: `/path/to/blender --debug-gpu-shaders`

**Comment by ca3games** [comment]
cristian@cristian-pc:~$ blender --debug-gpu-shaders
Read prefs: /home/cristian/.config/blender/2.91/config/userpref.blend
found bundled python: /snap/blender/51/2.91/python
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr5, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr4, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
addon_utils.disable: RetopoFlow not disabled
Modules Installed (RetopoFlow) from '/home/cristian/Apps/RetopoFlow_v3.00.2.zip' into '/home/cristian/.config/blender/2.91/scripts/addons'
RetopoFlow: Initial load
Aborted (core dumped)

**Comment by vxlcoder** [comment]
note: edited parameters above

**Comment by ca3games** [comment]
cristian@cristian-pc:~$ blender --debug --debug-gpu --debug-gpu-shaders
Switching to fully guarded memory allocator.
Blender 2.91.0
Build: 2020-11-25 08:51:08 Linux Release
argv[0] = /snap/blender/51/blender
argv[1] = --debug
argv[2] = --debug-gpu
argv[3] = --debug-gpu-shaders
Read prefs: /home/cristian/.config/blender/2.91/config/userpref.blend
read file 
  Version 280 sub 39 date unknown hash unknown
found bundled python: /snap/blender/51/2.91/python
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr5, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
LLVM triggered Diagnostic Handler: Illegal instruction detected: VOP* instruction violates constant bus restriction
renamable $vgpr4 = V_CNDMASK_B32_e32 32768, killed $vgpr4, implicit killed $vcc, implicit $exec
LLVM failed to compile shader
radeonsi: can't compile a main shader part
RetopoFlow: Initial load
Aborted (core dumped)

**Comment by vxlcoder** [comment]
weird.  it's not even getting to the video card debug printout stuff.  digging further

**Comment by ca3games** [comment]
Will try to post if retopoflow runs on my windows partition.

**Comment by ca3games** [comment]
Can confirm there's not crash on windows.
Seems likely a linux only issue.

**Comment by CustomLenny** [comment]
I feel as though I have the same issue but without the crash but a hang instead, just our computers behaving differently.
I've tried to enable multiple of these retopoflow 3 (the latest bug update ones and such) on multiple blender 2.9 (including now 2.91.2) on Ubuntu 20.04 (overtime with different kernels currently 5.8.0-40-generic) with a GTX 1060 6gb edition (overtime with different drivers currently 450.102.04).

In terminal, upon enabling I get:
```
RetopoFlow: Initial load
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
RetopoFlow Shader Info: brushStrokeShader (226)
  attribs: vPos (0), vColor (1), vDistAccum (2)
  uniforms: uMVPMatrix (0)
RetopoFlow Shader Info: edgeShortenShader (229)
  attribs: vPos (0), vFrom (1), vColor (2), vRadius (3)
  uniforms: uScreenSize (1), uMVPMatrix (0)
RetopoFlow Shader Info: arrowShader (232)
  attribs: vPos (0), vFrom (1), vInColor (2), vOutColor (3)
  uniforms: uMVPMatrix (1), uInOut (0)
RetopoFlow Shader Info: circleShader (235)
  attribs: vPos (0), vInColor (1), vOutColor (2)
  uniforms: uMVPMatrix (1), uInOut (0)
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
```

In which blender then freezes and hogs 25% of my CPU which is 100% of one core.

Upon keyboard interruption in the terminal, the traceback leads to:
```
  File "./blender-2.91.2-linux64/2.91/scripts/startup/bl_operators/userpref.py", line 466, in execute
    mod = addon_utils.enable(self.module, default_set=True, handle_error=err_cb)
  File "./blender-2.91.2-linux64/2.91/scripts/modules/addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "./blender-2.91.2-linux64/2.91/scripts/addons_contrib/RetopoFlow/__init__.py", line 58, in <module>
    from .retopoflow import retopoflow
  File "./blender-2.91.2-linux64/2.91/scripts/addons_contrib/RetopoFlow/retopoflow/retopoflow.py", line 31, in <module>
    from .rf.rf_blender     import RetopoFlow_Blender
  File "./blender-2.91.2-linux64/2.91/scripts/addons_contrib/RetopoFlow/retopoflow/rf/rf_blender.py", line 30, in <module>
    from ...config.options import options, retopoflow_version
  File "./blender-2.91.2-linux64/2.91/scripts/addons_contrib/RetopoFlow/config/options.py", line 92, in <module>
    retopoflow_git_version = git_info()
  File "./blender-2.91.2-linux64/2.91/scripts/addons_contrib/RetopoFlow/addon_common/common/utils.py", line 201, in git_info
    if os.path.split(path_root)[1] == 'addons':
  File "./blender-2.91.2-linux64/2.91/python/lib/python3.7/posixpath.py", line 109, in split
    i = p.rfind(sep) + 1
```

**Comment by vxlcoder** [comment]
thanks for the extra details @CustomLenny.

what is the full path to where RetopoFlow is installed on your machine?

**Comment by CustomLenny** [comment]
@vxlcoder 
My blender is downloaded and unzipped to:
`/home/UserName/ProgramFolder/blender-2.91.2-linux64/`
and folder called `RetopoFlow` which is retopoflow unzipped goes into:
`/home/UserName/ProgramFolder/blender-2.91.2-linux64/2.91/scripts/addons_contrib/`
I use `addons_contrib` so I can easily find the add-ons that I've added under the Testing tab (rather than Official or Community)

**Comment by vxlcoder** [comment]
thanks.  where did you get the zip file that you installed? from blender market, git clone, git released, etc.?

I think you're problem is actually different from original post issue.

**Comment by CustomLenny** [comment]
I got it from the releases section in this github repo. I'm unsure where I've gotten the others from in the past but I think they've come from here as well.

**Comment by vxlcoder** [comment]
just a quick test, @CustomLenny... if you install RF into `addons/` folder instead of `addons_contrib/`, does RF starting working ok?

**Comment by vxlcoder** [comment]
if that fixes the problem, I believe your having a similar issue as #903, which is now fixed in the `v3.00.3` branch and will be released soon.

**Comment by CustomLenny** [comment]
@vxlcoder that actually did fix the problem. My mistake, didn't even think to test that. I've never used retopoflow before, I was trying to help with this issue as it's what popped up when googling my issue.

**Comment by vxlcoder** [comment]
glad to hear! we will be releasing v3.00.3 which has that fix soon. please let us know if you have other issues!

**Comment by CustomLenny** [comment]
Thanks very much for your help.

**Comment by vxlcoder** [comment]
Thanks for the reports!  Closing this issue now.  Let us know if you have any other problems!
