### ISSUE TITLE
The same names of different icons

### ISSUE THREAD

**Issue by LLKoder** [CGCookie/retopoflow#925]
Retopoflow Version: 3.00.1, 3.00.2

Blender Version/Hash: irrelevant

Platform Version/Distribution: Windows 10

**Issue:**

I download (RetopoFlow_v3.00.2.zip) the latest version of RF and update it manually.
During the update I see the notice about the same names of different icons in the archive:
contours_32.png
Contours_32.png
Please fix icons name.
The same issue in 3.00.1.

**How to Reproduce:**

Try to unpack the archive (RetopoFlow_v3.00.2.zip) in any folder in Windows 10.

**Comment by vxlcoder** [comment]
thanks for the report! will get this fixed

**Comment by vxlcoder** [comment]
created a script to make sure that this issue doesn't happen.

thanks for reporting!

closing this issue
