### ISSUE TITLE
Symetry: Improve Documentation

### ISSUE THREAD

**Issue by josmos** [CGCookie/retopoflow#936]
I had a problem setting symetry for my model. It seems the Symetry axis is aplied to the 3d cursor rather than the object origin. In my opinion this is not obvious. It took me a very long time to figure this out. I suggest you shoud add this to your documentation.

**Comment by vxlcoder** [comment]
thanks for the report, @josmos.

RetopoFlow follows Blender convention where new objects are created at the 3d cursor and that symmetry is about the object's origin.  So, when you create a new target mesh, it's origin is placed and orientated by the 3d cursor.

I believe the quick start guide has this, but I could be wrong or the docs might need to be clearer. will check once I am back at a computer.

**Comment by vxlcoder** [comment]
latest commit address this issue by adding a new blender operator to create new target mesh based on active source mesh.

again, thanks for the report!
