### ISSUE TITLE
**[BUG]** Contours warning - "One of the sources has inwards facing normals"

### ISSUE THREAD

**Issue by akomili** [CGCookie/retopoflow#938]
Retopoflow Version: 3.0.1

Blender Version/Hash: 2.91

Platform Version/Distribution: not sure

**Issue:**

When I try to add a contour strip to my mesh I get the following Warning:

![image](https://user-images.githubusercontent.com/76419082/106235465-8e546a00-61af-11eb-803e-3984507437ad.png)

I have recalculated the normals and made sure they're all facing the right way but can't seem to stop getting this warning and I sometimes can't select the edges after the contour is created.

**How to Reproduce:**

I sculpted a mesh using dynotopo but there isn't anything different about it. I can send my blend file to test, you would just need to create a new RT target and add a contour across the mesh and the error pops up right away. I've attached a video of me doing exactly that. I've also attached an image of the rest of the body of the creature for context.

![RT_Test](https://user-images.githubusercontent.com/76419082/106301793-000ed100-620d-11eb-8fce-d18c1f722695.PNG)

https://user-images.githubusercontent.com/76419082/106301437-92fb3b80-620c-11eb-9a6c-61618ed2bcec.mp4

Thanks
Amy

**Comment by vxlcoder** [comment]
Thanks for the report, @akomili!

Would you mind sending your .blend file to retopoflow@cgcookie.com so that we can take a look at it?

It might just be that RF is too eager to report an inward facing normal.

**Comment by vxlcoder** [comment]
Note: version 3.00.1 had a bug that would detect inward facing normals incorrectly if the source mesh was rotated.  version 3.00.2 fixed that issue.  the issue reported above was due to this fixed bug.  closing the issue

Please let us know if you have any other problems @akomili!

**Comment by akomili** [comment]
Thank you so much!
