### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by GameHatcher00** [CGCookie/retopoflow#940]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [x] Read through the README.md file in the branch used to assure the process taken is correct
- [x] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [x] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.00.2
- CG Cookie built
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.5.0 NVIDIA 457.30, 4.50 NVIDIA
- Timestamp: 2021-01-30 18:11:53.481141
- Undo: extrude strip, extrude strip, create strip, deselect all, select, extrude strip, extrude strip, extrude strip, extrude strip, extrude strip

Error Hash: 41a8805e52e6be36048736d9b02a97f2

Trace:

- EXCEPTION (<class 'ValueError'>): vert_splice(...): verts can't share a face
-     C:\Users\gameh\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rfmesh\rfmesh_wrapper.py
- 000 0230:merge() vert_splice(bmv1, bmv0)
-     C:\Users\gameh\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 001 0871:extrude_strip() b.merge(a)
-     C:\Users\gameh\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 002 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\gameh\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 003 0356:modal_main() self.replay()
-     .../common\fsm.py
- 004 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @GameHatcher00.

This is the same as issue #927.

I have started tracking down this issue but haven't solved it quite yet.

**Comment by vxlcoder** [comment]
to simplify things, i'm going to close this issue.

I'll post updates in issue #927.
