### ISSUE TITLE
[BUG] Merging vertices of n-gon appears to remove a face

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#941]
Version 3.00.3
Blender 2.91

Merging some vertices can result in disappearing faces. 

-Create a shape with the knife tool as shown below
-Try to merge the example vertices together by dragging one on top of the other

![0tEgN1dDb4](https://user-images.githubusercontent.com/12982300/106511737-7cabe480-6485-11eb-82f3-6218e63a5c2e.gif)

![kgPAwIE0MY](https://user-images.githubusercontent.com/12982300/106511741-7fa6d500-6485-11eb-9b50-2549421d837c.gif)

**Comment by vxlcoder** [comment]
commit ^^ should now fix this

bonus: now PP merge is _way_ more robust :)

https://user-images.githubusercontent.com/3790699/106517555-a75a6500-64a6-11eb-8ece-ae4053d1d38b.mp4

**Comment by jlampel** [comment]
Awesome, it works great on PolyPen! Should it be copied over to Knife?

**Comment by vxlcoder** [comment]
good catch.  moved the code to more general area and updated both PP and Knife to use it

**Comment by jlampel** [comment]
Looks good to me!
