### ISSUE TITLE
Knife creates duplicate vertices when splitting edges

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#943]
I haven't been able to narrow down exactly when it happens, but Knife will occasionally place two vertices very close to each other when I make a cut instead of one when splitting an edge. So far this has not happened when placing a vert in the middle of a face or starting/ending the cut from outside the mesh. 

This *could* be me just accidentally overshooting the edge, but I've tried to be super careful. It could just be that increasing the pixel distance for the snapping would make this disappear. I'll continue to test as I use it to find out. 

Examples:
![image](https://user-images.githubusercontent.com/12982300/106539369-b515e780-64b2-11eb-8cfa-672cca34a04f.png)

![image](https://user-images.githubusercontent.com/12982300/106539619-2d7ca880-64b3-11eb-963e-197ff5467015.png)

**Comment by vxlcoder** [comment]
I have tried to reproduce this, but it seems to be working ok on my machine.  might be just missing the edge.

note: there is a knife snap distance option (Options > Knife > Knife Options > Snap distance).  you can adjust this pixel distance.

let me know how to reproduce, if you can figure out how to do that reliably :)

**Comment by jlampel** [comment]
Ok, I'm getting this again just by drawing polys with PP and then adding a cut by clicking on an edge from a slightly zoomed out view. 

![35cGUeIhQV](https://user-images.githubusercontent.com/12982300/108777646-fc731f00-7518-11eb-83de-c4e7f4fb1fd8.gif)

What's interesting is that increasing the Snap Distance increases the distance at which it draws the connection preview but does not seem to affect the actual vertex that's created. Turn Snap and Merge distance up to something wild like 50 to see what I mean. 

![zLYAyUC1I6](https://user-images.githubusercontent.com/12982300/108777785-33e1cb80-7519-11eb-9c1d-551be7ce30fb.gif)

**Comment by vxlcoder** [comment]
this _should_ be fixed now!

**Comment by jlampel** [comment]
Confirmed fixed!
