### ISSUE TITLE
Hidden vertices visible in RF 

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#944]
Blender 2.91 and RF 3.00.3

I'm not sure how this feature is supposed to behave exactly, but something seems to be off with hidden geometry. Here's what I'm seeing:

- Vertices hidden in edit mode are visible in RF
- Vertices hidden in edit mode are not masked by the Exclude Hidden option
- Vertices hidden in edit mode are unselectable in RF 
- There is no way (that I know of) to hide or unhide vertices within RF

**Comment by jlampel** [comment]
Ok cool, so then is the issue that the Exclude Hidden option doesn't work? The vertices are unselectable in other tools so it seems like something is going on under the hood. Having it match with Edit Mode would be ideal if we need to implement that functionality.

**Comment by vxlcoder** [comment]
hidden geometry is now treated correctly in RF (not drawn, no snap, etc)

still do not have a way to hide or reveal geometry from within RF

**Comment by vxlcoder** [comment]
added ability to hide selected, hide unselected, and reveal hidden!

now just need some additional tooling for selecting

**Comment by jlampel** [comment]
This works great!
