### ISSUE TITLE
Multiple tools appear selected in mini toolbar

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#945]
Blender 2.91 and RF 3.00.3

It's possible for several tools to appear selected in the minimized toolbar as shown below:
![image](https://user-images.githubusercontent.com/12982300/106810488-dea15100-6621-11eb-91d2-40153eaa58f3.png)

To replicate:
-Switch to the regular toolbar
-Restart Blender
-Start RetopoFlow 
-Switch tools via the pie menu
-Minimize the toolbar 

Once you switch tools again, this problem will go away.

**Comment by vxlcoder** [comment]
this should be fixed now!

**Comment by jlampel** [comment]
Confirmed fixed!
