### ISSUE TITLE
Retopoflow poor performance

### ISSUE THREAD

**Issue by LucasMCuenca** [CGCookie/retopoflow#946]
Hello guys hows going ?? 

ok so i just wanted to trow this over here and see if this is something that can be improved or not . 

I do creatures for the film industry and of course topology is one of the main things needs to be done properly, but is not a fast process, retopoflow have the potential to make it a bit faster, i tested quite a bit but unfortunatelly the performace is not good enough, my target mesh is under 1M polys and the retopomesh is over 25k.  With quad draw in maya this goes pretty fast but in retopoflow is very laggy is any chance that you guys find a way to improve the performance a bit.

I would be super happy of talk about this in more indepth if you guys want 
btw is not the system my work and home computer are pretty good full of cores and gpus

cheers 

Lucas

**Comment by vxlcoder** [comment]
We appreciate your request @LucasMCuenca.

Better performance with higher poly counts is a top goal of mine. recently we focused on overall performance improvements with the new ui system, which took a bulk of dev time but this work will be considered "done" here soon with the next release.

I would be very interested in discussing your particular setup in more detail. perhaps we can video chat or at least exchange some details over email? please contact us at retopoflow@cgcookie.com

**Comment by vxlcoder** [comment]
We have made some extensive improvements toward better performance on larger target meshes.  These changes are in v3.1.0 release.

We plan to improvement performance further, but will close this issue for now.

@LucasMCuenca, please let us know if the changes in v3.1.0 do not improve your situation!

thanks!
