### ISSUE TITLE
[QUESTION] Strokes tool snaping to vertices near the cursor

### ISSUE THREAD

**Issue by paulocspaes** [CGCookie/retopoflow#947]
Retopoflow Version: 3.00.2
Blender Version/Hash: 2.91.0
Platform Version/Distribution: GitHub

When using the Strokes tool, if I start the stroke near another vertice, the stroke will start from that vertice. I understand the usefulness of such behavior and have used it many times beforre. The problem I have is when using the Strokes tool in small areas where I don't want the stroke to snap and start from another vertice, like for example when retopologizing the hand shown in the screenshots.
I've searched for a way to disable this feature but couldn't find anything.

![problem](https://user-images.githubusercontent.com/67326846/107406723-7fdb4c00-6ae7-11eb-8edc-0ff6d8614a95.jpg)
![problem1](https://user-images.githubusercontent.com/67326846/107406750-8964b400-6ae7-11eb-9df4-eed8fbeead43.jpg)

**Comment by vxlcoder** [comment]
Ok, I played around with this a bit, and I think it works well.

The stroke will _always_ snap to nearby selected geometry (based on brush size).  This allows for the types of fills I posted earlier.

However, now you can optionally snap to nearby unselected geometry, which solves the problem you're running into above.

**Comment by paulocspaes** [comment]
Ok, dumb question, How do I update my retopoflow in order to check the changes you've made?

**Comment by vxlcoder** [comment]
not a dumb a question!

I will post a link later today to do that.

**Comment by vxlcoder** [comment]
here is a link to the latest version that contains the commit above: https://www.dropbox.com/s/wwxp73yac23me7e/RetopoFlow_v3.1.0-rc2.zip?dl=0

**Comment by paulocspaes** [comment]
It totally worked!
Gonna be so much easier when retopologyzing tight areas like the fingers or ears.
Such good work you've done man! Thank you, really appreciate it.
Awesome tool you guys working on, I'll make sure to support at Blender Market when I've got the finances for it.
