### ISSUE TITLE
[BUG] Tweak and Relax ignoring vertices at some view angles

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#948]
Here's a new bug report we got via BM inbox:

> Is there some setting that makes it work incorrectly? I don't have problems moving verts around with PolyPen tool, but when I try to use Tweak tool, certain vertices don't move until I change camera angle. Then some other don't move. The brush size doesn't matter, I can choose a small brush and not be able to move the vertex, if I use a big brush I can move most vertices in range at the same time, but some stay in place.

>I did a small edit to RetopoFlow object (only ear area) in Edit mode and the bug appeared. I thought maybe I moved some vertices inside source object, so I moved them away to be sure they aren't inside, but it didn't help.

> You can see on the video that some points far away from the ear don't react to Tweak tool, while I didn't move these verts in Edit mode, nor in RetopoFlow mode. At some point you can even see t hat only several vertices from ear area react, while the brush covers half of the head.

> One more thing - The bug didn't go out with Blender restart. It did disappear when I started RetopoFlow mode with source object hidden and other mesh (eyes) visible, then Exited RetopoFlow, switched source object back on.

I can confirm this using the file provided: 
https://drive.google.com/drive/folders/1tYelFr2T5u_hJKuZfQ3gKkKU-KkvR-EM?usp=sharing

One additional observation is that this only seems to be a problem when Hidden is set to Exclude rather than Include. I'm not sure why since the vertices are not hidden in edit mode, but it seems to make a difference. Snapping all vertices to target makes no difference, so they are not stuck under the mesh. 

To reproduce: 
- Download the file in the above link
- Switch to the Tweak tool with Hidden set to Exclude
- Try to move vertices around the earlobe, forehead, or neck while looking at them dead on
- Switch Hidden to Include and try again
- Undo and set Hidden back to Exclude 
- Rotate the view and try again until you find a view angle that will allow you to move the vertex

**Comment by jlampel** [comment]
A note from a second user experiencing the same thing: 

> Im not 100% how I got this issue. I think it was that I went out of Retopoflow, into edit mode, added a polyloop, maybe closed Blender, opened it again and initiated Retopoflow, and there it was.

**Comment by vxlcoder** [comment]
the tweak from commit 25195f4 _should_ help with this.  I just adjusted the default distance offset value from 0.0008 to 0.0016.  The artist can adjust it as needed, although it's somewhat hidden under Options > General > Advanced > Visibility Testing > Distance Offset.

This issue looks like a precision problem, which unfortunately is very hard to solve.  I'll tinker around a bit more with some ideas, though.

**Comment by vxlcoder** [comment]
marked as ready for testing, but still needing more work

**Comment by jlampel** [comment]
I can no longer reproduce this with the same example file, so I'll consider it closed and will open a new issue if it crops up again.
