### ISSUE TITLE
[BUG] Object has no attribute "undo"

### ISSUE THREAD

**Issue by Slemgrim** [CGCookie/retopoflow#949]
Retopoflow Version: v3.00.2

Blender Version/Hash: ec682409fb3d5b6abfb7959999355458

Platform Version/Distribution: Windows 10

**Issue:**

When i switch into edit mode of an existing retopology and hit the white diamond icon to start retopoflow it gets stuck on "Setting up RetopoFlow Tools" message. However, this only happens if there are selected faces before activation retopoflow.

I checked the consolo. It repeats the error:
EXCEPTION (<class 'AttributeError'>): 'VIEW3D_OT_RetopoFlow_LastTool' object has no attribute 'undo'

&nbsp;

**How to Reproduce:**

- Close retopoflow
- Switch to edit mode of retopology
- **Select faces (All)**
- Click on retopoflow button to reactivate retopoflow
- retopoflow gets stuck during loading

**Comment by vxlcoder** [comment]
thanks for the report, @Slemgrim .

will take a look at this later today

**Comment by vxlcoder** [comment]
@Slemgrim, do you have more context to this issue from the console?  Right around and before that EXCEPTION line is printed repeatedly to the console, there should be a call stack and maybe other info printed to console.  If you can copy-paste that here, that will help me debug this issue quicker.  Thanks!

**Comment by vxlcoder** [comment]
Also, what was the very last tool you used before this error started occurring?

**Comment by vxlcoder** [comment]
commit cfe0e52 possibly works around the issue, but this is not a permanent solution.

will wait for more details to pursue a correct solution.

**Comment by Slemgrim** [comment]
I'm afraid i can't replicate it either. 

My steps were the following:
I worked on the retopopology of a heavy model (150k polygons)
Retopoflow got slower and slower at around 3000polys. 
I pressed tab to exit retopowlow, entered edit mode and split the retopo into two parts to increase performance. 
This was done py selecting a big part of the mesh in edit mode and press "P" to separate by selection. 
I then selected the smaller part, entered edit mode and activated retopoflow.
retopoflow stopped during loading. 

The faces were still selected. After unselecting all faces i was able to start retopoflow.

I was able to replicate this several times with the same model

**Comment by vxlcoder** [comment]
do you recall which tool you used?

**Comment by vxlcoder** [comment]
I have not been able to replicate this issue (I think it _might_ be fixed in latest version of RetopoFlow).  will close this issue for now, but please let us know if you continue to have this problem in the latest version.

Happy retopo'ing!

**Comment by Gabe687** [comment]
Hi I'm getting this error also, retopoflow gets stuck when I try to enter the retopology space by any method.  If I have no starter object and let the tool create one for me, or if I start from an existing one and enter through the launcher icon in edit mode.  

I used no tools before opening retopoflow, and I disabled all my other user addons.  I can't open retopoflow even on a primitive object and I have no idea why.



Environment:

- RetopoFlow: 3.2.1
- CG Cookie built
- Blender: 2.93.2 master 2021-08-03
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1080/PCIe/SSE2, 4.5.0 NVIDIA 456.71, 4.50 NVIDIA
- Timestamp: 2021-08-15 03:22:12.593118
- Undo: 

Error Hash: 7219be82d192c7240b189b71f56843f5

Trace:

- EXCEPTION (<class 'AssertionError'>): 
-     C:\Users\gabe6\AppData\Roaming\Blender Foundation\Blender\2.93\scripts\addons\RetopoFlow\retopoflow\retopoflow.py
- 000 0210:setup_next_stage() assert False
-     .../common\fsm.py
- 001 0169:wrapped() return fn(*args, **kwargs)



![RetopoFlow_screenshot](https://user-images.githubusercontent.com/7055390/129470601-fd7b9815-8adc-4f4a-9034-eea2ec95095b.png)

**Comment by vxlcoder** [comment]
sorry to hear that @Gabe687.

how did you install RetopoFlow? did you use RF's upgrade system to go from 3.2
0? is this a brand new install? etc.

**Comment by Gabe687** [comment]
I got it from Blender Market, I don't remember how I installed it, if I had to do anything special, I don't think so.  It was a while ago, so whatever it said in the instructions.  I normally just install through the addons tab in the properties panel.

I upgraded using the built in buttons in the retopoflow tab.  Check for updates and updater system.

**Comment by vxlcoder** [comment]
ok. we have had reports of the built in updater has caused issues. try this: uninstall RF from blender, then restart blender, then install RF from zip file on blender market. let us know if that doesn't work.

**Comment by Gabe687** [comment]
Ok thanks, a clean install has fixed the problem.

**Comment by vxlcoder** [comment]
good to hear!

happy retopo'ing!
