### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by GarvitGothwal** [CGCookie/retopoflow#957]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.18362, AMD64, Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce MX150/PCIe/SSE2, 4.5.0 NVIDIA 451.67, 4.50 NVIDIA
- Timestamp: 2021-02-19 03:22:47.411269
- Undo: insert, select, select, delete Vertices, select, select, select, insert, smart select, cut

Error Hash: 29df084ee10ac3025b71646724418438

Trace:

- EXCEPTION (<class 'ValueError'>): faces.new(...): found the same (BMVert) used multiple times
-     C:\Users\Riuzaki-PC\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh.py
- 000 1557:new_face() bmf = self.bme.faces.new(verts)
-     C:\Users\Riuzaki-PC\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 001 0482:new_face() return self.rftarget.new_face(verts)
-     C:\Users\Riuzaki-PC\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 002 0500:_insert() bmf = self.rfcontext.new_face([bmv0, bmv1, bmv2, bmv3])
-     C:\Users\Riuzaki-PC\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 003 0155:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Riuzaki-PC\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 004 0298:insert() return self._insert()
-     .../common\fsm.py
- 005 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
Thanks for the report, @GarvitGothwal.

Will look into this.  In the mean time, could you post a screenshot or provide steps for reproducing this issue?

**Comment by vxlcoder** [comment]
the above commit possibly works around this issue.  however, I was unable to reproduce this issue, so I cannot test that it actually works.

will mark this issue as closed, but please reopen if it happens again or post additional info on reproducing this if you can.

Thanks!
