### ISSUE TITLE
[BUG] Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by funksyt** [CGCookie/retopoflow#958]
Issue:

RetopoFlow crashes using the Strokes tool on existing geometry. See video link below.

How to Reproduce:

See video [https://youtu.be/pGo3O7Hl-gE](https://youtu.be/pGo3O7Hl-gE)

![crash1](https://user-images.githubusercontent.com/62566181/108829459-e163e600-75d0-11eb-9cbc-444e53dac831.png)
![crash2](https://user-images.githubusercontent.com/62566181/108829511-ed4fa800-75d0-11eb-9fa4-fc353057ffeb.png)

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- CG Cookie built
- Blender: 2.91.2 master 2021-01-19
- Platform: Windows, 10, 10.0.19041, AMD64, AMD64 Family 23 Model 113 Stepping 0, AuthenticAMD
- GPU: NVIDIA Corporation, GeForce RTX 2060/PCIe/SSE2, 4.5.0 NVIDIA 460.89, 4.50 NVIDIA
- Timestamp: 2021-02-23 11:57:24.343316
- Undo: extrude strip, select, select, select

Error Hash: 3782d73b634e1c4590b87b37936d5127

Trace:

- EXCEPTION (<class 'AttributeError'>): 'tuple' object has no attribute 'reverse'
-     C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 000 0826:extrude_strip() if side_verts[1] == verts[0]: side_verts.reverse()
-     C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0371:stroke() if self.replay: self.replay()
-     C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0087:modal_line() self.callback_actions()
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
```

**Comment by funksyt** [comment]
Here is the file:

[Skull_Report.zip](https://github.com/CGCookie/retopoflow/files/6028210/Skull_Report.zip)

**Comment by vxlcoder** [comment]
thanks for the report, @funksyt!

will take a look as soon as possible

**Comment by vxlcoder** [comment]
this issue should now be fixed.

If you get a chance to test this fix, let me know whether I fixed it for you or if there is anything lingering.  To test the fix, click on Updater System at the bottom of the RetopoFlow menu, type into the Advanced Commit / Branch the text `2eb10aa`, then click the Load button.  If all goes well, you should see a "successfully updated" window.  Exit Blender, reopen Blender, then try to reproduce the bug.

Let us know if you have any problems or questions!

![image](https://user-images.githubusercontent.com/3790699/108848506-119a8d00-75af-11eb-8f95-637667393883.png)

![image](https://user-images.githubusercontent.com/3790699/108848650-3db60e00-75af-11eb-80f0-ee39126f37ee.png)

![image](https://user-images.githubusercontent.com/3790699/108848807-6f2ed980-75af-11eb-807e-9197b8a9faa0.png)

**Comment by funksyt** [comment]
Couldn't test it because the updater didn't work.

"Failed to make extract directory"

https://user-images.githubusercontent.com/62566181/108857056-58aa7180-75f3-11eb-8413-27f813cff3b1.mp4

**Comment by vxlcoder** [comment]
helpful feedback, thank you. 

you're the first to test this out, so I appreciate your willingness to test this out.

how did you install RF?  Is it installed in the usual addons folder?

will continue to work on this.

**Comment by vxlcoder** [comment]
or, can you copy-paste hete everything that is printed to the console after you try updating (window > toggle system console)?  that would be helpful too.  thanks!

**Comment by funksyt** [comment]
> helpful feedback, thank you.
> 
> you're the first to test this out, so I appreciate your willingness to test this out.
> 
> how did you install RF? Is it installed in the usual addons folder?
> 
> will continue to work on this.

I installed it from the zip from Blender Market. The path is this I think:
C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow

> or, can you copy-paste hete everything that is printed to the console after you try updating (window > toggle system console)? that would be helpful too. thanks!

Here is what was in System Console after trying update:

_Read prefs: C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\config\userpref.blend
found bundled python: C:\Program Files\Blender Foundation\2.91\2.91\python
register
addon_updater_demo updater verbose is enabled
addon_updater_demo Updater: Read in JSON settings from file
The custom limb directory seems invalid: C:\Custom Limbs/
Registered MESHmachine 0.7.0 with 2 plug libraries
 ┬╗ plug library: Examples
 ┬╗ plug library: MyPlugs
RetopoFlow: Initial load
Addon Common: (shaders) GLSL Version: 4.50 NVIDIA
RetopoFlow Shader Info: brushStrokeShader (7)
  attribs: vPos (0), vColor (1), vDistAccum (2)
  uniforms: uMVPMatrix (0)
RetopoFlow Shader Info: edgeShortenShader (10)
  attribs: vPos (0), vFrom (1), vColor (2), vRadius (3)
  uniforms: uScreenSize (1), uMVPMatrix (0)
RetopoFlow Shader Info: arrowShader (13)
  attribs: vPos (0), vFrom (1), vInColor (2), vOutColor (3)
  uniforms: uMVPMatrix (1), uInOut (0)
RetopoFlow Shader Info: circleShader (16)
  attribs: vPos (0), vInColor (1), vOutColor (2)
  uniforms: uMVPMatrix (1), uInOut (0)
Addon Common: compiling UI shader
Addon Common: batching for shader
Addon Common: UI shader initialized
RetopoFlow git: None
RetopoFlow options path: C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\RetopoFlow_options.json
Addon Common: (bmesh_render) GLSL Version: 4.50 NVIDIA
cgcookie updater verbose is enabled
cgcookie Updater: Read in JSON settings from file
Read blend: C:\Projects_3D\Personal Projects\Unfinished\Skull Stylized\Skull_Report.blend
Addon Common Warning: could not translate blender op "3D View | view3d.viewnumpad" to actions (3D View->3D View, view3d.viewnumpad->view3d.viewnumpad)
Addon Common Warning: could not translate blender op "3D View | view2d.ndof" to actions (3D View->3D View, view2d.ndof->view2d.ndof)
Addon Common Warning: could not translate blender op "3D View | view3d.view_center_cursor" to actions (3D View->3D View, view3d.view_center_cursor->view3d.view_center_cursor)
Getting tags from server
Most recent tag found: v3.1.0
Addon Common: Loaded font "C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\addon_common\common\fonts\DroidSans-Blender.ttf" as id 3
Running update
Staging update
Preparing staging folder for download:
 C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\updater_tmp\update_staging
Backing up current addon folder
Backup destination path:  C:\Users\Antti\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\updater_tmp\backup
cgcookie: Wrote out updater JSON settings to file, with the contents:
{'last_check': '', 'backup_date': 'February-23-2021', 'update_ready': False, 'ignore': False, 'just_restored': False, 'just_updated': False, 'version_text': {}}
Now retrieving the new source zip
Starting download update zip
Successfully downloaded update zip
Source folder cleared and recreated
Error occurred while making extract dir:
[WinError 183] Cannot create a file when that file already exists: 'C:\\Users\\Antti\\AppData\\Roaming\\Blender Foundation\\Blender\\2.91\\scripts\\addons\\RetopoFlow\\updater_tmp\\source'_

**Comment by vxlcoder** [comment]
I think I _might_ have fixed this bug, but you will need to install manually rather than using the updater system to test it.

You can get the latest version from https://www.dropbox.com/s/gmxmt9f62q8us78/RetopoFlow_v3.1.1-alpha.zip?dl=0 (link will only exist for a few days) or you can wait for the next official release.

Thanks!

**Comment by funksyt** [comment]
Yes! It works now, thank you!

PS. Really great work on the addon btw! UI works a lot smoother now and the knife tool is great!

https://user-images.githubusercontent.com/62566181/109059218-ace54c80-76ec-11eb-93c6-6b90d0b0c6d0.mp4

**Comment by vxlcoder** [comment]
Excellent!  thanks for the feedback, and we're glad to hear that you're enjoying RF!

if you get a chance to try the updater again and you still have issues, do let us know.

closing this issue.  cheers!
