### ISSUE TITLE
Pie Menu is broken w/ 4K HiDPI mode

### ISSUE THREAD

**Issue by visualworx** [CGCookie/retopoflow#959]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: {3.1.0}

Blender Version/Hash: 2.91.2

Platform Version/Distribution: Windows 10 Home 20H2
&nbsp;

**Issue:**

Pie Menu is broken w/ 4K HiDPI mode

![retopoflow_hidpi](https://user-images.githubusercontent.com/54339099/108987159-4e14d880-76d6-11eb-864f-bdc8013ed40b.png)

&nbsp;

**How to Reproduce:**

- Run Retopoflow on Blender with any mesh
- Press and hold Q

**Comment by vxlcoder** [comment]
thanks for the report, @visualworx .

will take a look as soon as I can.

question: is the pie menu visually broken but functionally it still works (can still change tools), or does it not work at all?

**Comment by visualworx** [comment]
If I click any box it doesn't highlight but if I click the where the box supposed to be it does highlight and it works. I think the boxes just don't stay on the right spot w/ 4k HiDPI mode.

**Comment by vxlcoder** [comment]
Perfect!  That's an easy fix :)

thanks!

**Comment by vxlcoder** [comment]
this _should_ be fixed in commit 7d75f45.

@visualworx, you can try following the instructions on https://docs.retopoflow.com/addon_updater.html to try out the fix.  Just enter either `7d75f45` or `v3.1.1` into the `Advanced: Commit / Branch` box, then click `Install`.
