### ISSUE TITLE
[BUG] Retopoflow exits automatically

### ISSUE THREAD

**Issue by visualworx** [CGCookie/retopoflow#960]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

&nbsp;

Issue Template
-----------------------------------

---
Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Retopoflow Version: 3.1

Blender Version/Hash: 2.91.2

Platform Version/Distribution: Windows 10 20H2

&nbsp;

Retopoflow exits by itself if the mouse cursor is on the any panel window. It didn't happen in older version 3.0.1.

&nbsp;

**How to Reproduce:**

- Run retopoflow and move the cursor onto any panel window such as options panel, tool menu or any panel. 

{*attach any files needed to replicate the issue*}

**Comment by vxlcoder** [comment]
thanks for the report, @visualworx!

does anything get reported to the console (window > toggle system console) when this happens?

**Comment by vxlcoder** [comment]
I'm a little confused by your issue, @visualworx.

Are you saying that RetopoFlow exits whenever you press `Tab` or `Esc` (if enabled) when mouse is hovering area/panel/window of Blender that is not the 3D View, but this did not happen in previous versions of RF?  If so, this is by design.

If RetopoFlow is exiting as soon as you move your mouse outside the 3D View area, without any other action occurring, then this is a bug, and likely something is reported to the console.  If so, please copy-paste everything that is reported to the console.

Thanks!

**Comment by visualworx** [comment]
RetopoFlow: Setting up undo system (0.26578617095947266)
RetopoFlow: Checking auto save / save (0.019004344940185547)
RetopoFlow: Loading welcome message (0.004001140594482422)
RetopoFlow: Resuming help image preloading (0.016478776931762695)
RetopoFlow: done with start
>>>>>>>>> auto auto
can't multiply sequence by non-int of type 'float'
CookieCutter handling exception caught while trying to "draw window UI"
____________________________________________________________________________________________________
Exception Info
- Time: 2021-02-25 08:42:29.029136
- Count: 2
- Hash: 307448f8158ecc91a591d3ed7a254adf
- Info:
  - EXCEPTION (<class 'TypeError'>): unsupported operand type(s) for +: 'float' and 'NoneType'
  -     .../common\ui_properties.py
  - 000 0583:reposition() if top  is not None: top  = clamp(top, -(rh - mbph) + h + mymbph, 0)
  -     .../common\ui_document.py
  - 001 0199:_reposition_tooltip() self._tooltip.reposition(left=ttl, top=ttt - hp)
  - 002 0697:force_clean() self._reposition_tooltip()
  - 003 0706:draw() self.force_clean(context)
  -     .../cookiecutter\cookiecutter_ui.py
  - 004 0119:postpixel() try: self.document.draw(self.context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
CookieCutter_Exceptions._callback_exception_callbacks: unsupported operand type(s) for +: 'float' and 'NoneType'
RF_UI.handle_exception unsupported operand type(s) for +: 'float' and 'NoneType'
RetopoFlow: scaling view, sources, and target by 1.00

**Comment by vxlcoder** [comment]
hmm. would you mind posting a screenshot of blender with rf running? I have an idea of what might be the cause.

thank you for helping debug this issue!

**Comment by visualworx** [comment]
![retopoflow_quit](https://user-images.githubusercontent.com/54339099/109081884-560c6100-7746-11eb-8f93-b5e88985e730.png)

**Comment by vxlcoder** [comment]
sorry I wasn't clear on that (on a not-so-smart phone).

can you post a screenshot of blender when you have RetopoFlow running, not a screenshot of the console.  you can run RF with the default cube as source mesh.

**Comment by visualworx** [comment]
RetopoFlow is exiting as soon as you move your mouse outside the 3D View area, without any other action occurring.

I didn't press any key. It just happens whenever the mouse cursor stays more than a sec (or may little less that?). So if I click any menu button quick enough I can still be in Retopoflow.

**Comment by visualworx** [comment]
![image](https://user-images.githubusercontent.com/54339099/109082474-696bfc00-7747-11eb-9cdf-7dd68ced4bcb.png)

**Comment by visualworx** [comment]
![image](https://user-images.githubusercontent.com/54339099/109082563-96b8aa00-7747-11eb-89b0-6f4d8b330bc3.png)

**Comment by visualworx** [comment]
Maximum view or normal view both the results are the same.

**Comment by vxlcoder** [comment]
interesting. thank you for the info!  I think I know how to fix it. will work on it as soon as I can

**Comment by visualworx** [comment]
I use 3090FE and 5950x with no overclocked btw.

**Comment by visualworx** [comment]
I tried with default cube. Here is something interesting result.

1. With just cube start (no retopo mesh yet)
2. Cube with a simple mesh
![image](https://user-images.githubusercontent.com/54339099/109083659-ab963d00-7749-11eb-91b9-9dfb79872389.png)

in both 1 and 2 situation blender hung if I move the cursor on any panel and stays for about a sec.

**Comment by visualworx** [comment]
Addon Common Warning: could not translate blender op "3D View | view3d.view_persportho" to actions (3D View->3D View, view3d.view_persportho->view3d.view_persportho)
Addon Common Warning: could not translate blender op "3D View | view3d.viewnumpad" to actions (3D View->3D View, view3d.viewnumpad->view3d.viewnumpad)
Addon Common Warning: could not translate blender op "3D View | view2d.ndof" to actions (3D View->3D View, view2d.ndof->view2d.ndof)
Addon Common Warning: could not translate blender op "3D View | view3d.view_center_cursor" to actions (3D View->3D View, view3d.view_center_cursor->view3d.view_center_cursor)
RetopoFlow: setting up scaling factor
Unit scaling factor: 0.2
RetopoFlow: scaling view, sources, and target by 5.00
RetopoFlow: Pausing help image preloading (1614211729.5859008)
RetopoFlow: Setting up target mesh (0.02904343605041504)
RetopoFlow: Setting up source mesh(es) (0.0009999275207519531)
  rfsources...
  bboxes...
  drawing...
  done!
RetopoFlow: Setting up symmetry data structures (0.0010018348693847656)
RetopoFlow: Setting up rotation target (0.0060007572174072266)
RetopoFlow: Setting up RetopoFlow states (0.007001161575317383)
RetopoFlow: Setting up RetopoFlow tools (0.010003328323364258)
RetopoFlow: Setting up grease marks (0.005001544952392578)
RetopoFlow: Setting up visualizations (0.007003307342529297)
RetopoFlow: Setting up user interface (0.012003183364868164)
RetopoFlow: Setting up undo system (0.2515535354614258)
RetopoFlow: Checking auto save / save (0.021004676818847656)
RetopoFlow: Loading welcome message (0.019006967544555664)
RetopoFlow: Resuming help image preloading (0.025007009506225586)
RetopoFlow: done with start
>>>>>>>>> auto auto
can't multiply sequence by non-int of type 'float'
CookieCutter handling exception caught while trying to "draw window UI"
____________________________________________________________________________________________________
Exception Info
- Time: 2021-02-25 09:08:52.738837
- Count: 1
- Hash: 307448f8158ecc91a591d3ed7a254adf
- Info:
  - EXCEPTION (<class 'TypeError'>): unsupported operand type(s) for +: 'float' and 'NoneType'
  -     .../common\ui_properties.py
  - 000 0583:reposition() if top  is not None: top  = clamp(top, -(rh - mbph) + h + mymbph, 0)
  -     .../common\ui_document.py
  - 001 0199:_reposition_tooltip() self._tooltip.reposition(left=ttl, top=ttt - hp)
  - 002 0697:force_clean() self._reposition_tooltip()
  - 003 0706:draw() self.force_clean(context)
  -     .../cookiecutter\cookiecutter_ui.py
  - 004 0119:postpixel() try: self.document.draw(self.context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by visualworx** [comment]
I purchased this on the Blender Market. This is the best retopo tool so far.

**Comment by vxlcoder** [comment]
the bug is in how the tooltip gets positioned. for some reason, your machine causes this bug to occur very often. I have seen this on my machine, but I never found a cause, and I never spent much time working on it. but I will get it working :D

**Comment by visualworx** [comment]
I tested this on my office PC. It doesn't happened at all.
The difference is that this one has:
2080Ti w/QHD, Intel 7900X. I think it might be related to 4K w/HiDPI?? or rtx3090 driver? IDK...
Regardless, Thanks for your effort! I appreciate it.

**Comment by vxlcoder** [comment]
I _think_ I have a workaround for your issue, @visualworx.  if you get a chance, can you give commit dcb1818 a try to see if it resolves your issue or if it introduces any other issues?

follow the instructions on https://docs.retopoflow.com/addon_updater.html and enter `dcb1818` in the Advanced: Branch / Commit box.

thanks!

**Comment by jlampel** [comment]
I can't reproduce this problem on my machine and its been several months so I'll consider the above commit as a solution, but please reopen if you continue to experience this issue with your particular setup.
