### ISSUE TITLE
Exclude Hidden does not exclude the hidden vertices

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#961]
The Exclude Hidden option for Tweak and Relax no longer works in 3.1.0 as pointed out by a user. A quick way to test this is to create some geometry, hide it all, adjust that area with Tweak, and then unhide it to see the change.

**Comment by vxlcoder** [comment]
there might be some confusion of terms here along with a bug. exclude hidden refers to verts that are within brush radius, but are occluded (think of working on a nose where there are verts inside the nostril). maybe should change wording to exclude occluded.

I think the brush tool (tweak or relax)  might be ignoring the hiddenness of verts.

both are easy fixes

**Comment by jlampel** [comment]
Ah, occluded makes much more sense to me in this case! I'm on board with the word change 👍

**Comment by vxlcoder** [comment]
should be fixed!

**Comment by jlampel** [comment]
Awesome, thank you!
