### ISSUE TITLE
Add warning for orthographic view

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#970]
I've seen a few support tickets come from folks working in orthographic view, which must be more common than I thought. There is surely a better long term solution, but in the meantime it may be helpful for us to add an optional check for orthographic view and bring up a warning/note if it is switched to.

**Comment by vxlcoder** [comment]
what's the problem with working with orthographic projection?

has this been resolved with recent tweaks to target mesh shader?

**Comment by jlampel** [comment]
Oh, it may have been improved since last I checked, but I thought orthographic view made some of the screen space tools freak out. If that's not the case (I'm not seeing any current problems) then this could be closed out.

**Comment by jlampel** [comment]
Oh, I do see that Tweak and Relax sometimes ignore vertices in orthographic view, but that could be its own issue if we're fine fully supporting orthographic. 
![95AyvGWtIW](https://user-images.githubusercontent.com/12982300/122571766-ec200c00-d001-11eb-903c-372f6c6a86e4.gif)

**Comment by vxlcoder** [comment]
we should be supporting ortho projection.  this seems to be a bug in tweak/relax.  will take a look.

**Comment by vxlcoder** [comment]
commit a36607c should improve that tweak and relax issue.  note: that issue is not only an ortho issue (might be exacerbated by that projection, though), and it's not just a tweak/relax issue.  it is a visibility test issue.

are there any other ortho-related issues that you can think of, @jlampel?

**Comment by jlampel** [comment]
Great! Not that I can see. I'll open a new issue if there are any
