### ISSUE TITLE
[BUG] RF Undo does not work if Blender Undo is remapped

### ISSUE THREAD

**Issue by basillicus** [CGCookie/retopoflow#972]
Retopoflow Version:  3.1

Blender Version/Hash: 2.92 , and 2.83

Platform Version/Distribution: Linux Kubuntu 20.04

&nbsp;

**Issue:**

RF undo (Ctrl-Z) does not work if Blender's Undo  is remapped to something else different to Ctrl-Z

I have the Undo in blender remapped to the Z key, instead of the classic Ctrl-Z. But it does not mater what key undo is remapped, RF would not work unless Blender undo is kept as Ctrl-Z. 

I tried it in both version 2.83 and 2.92 and the issue is there in both versions of blender. 

Video reproducing the issue: https://youtu.be/vSmboyZOX8k

&nbsp;

**How to Reproduce:**

- Remap  Blender's undo keymap to something different to Ctrl-Z
- Open RF
- RetopoFlow undo (Ctrl-Z) does nothing.

**Comment by vxlcoder** [comment]
Thanks for the report, @basillicus.

We have custom keymaps and improve tie-in to Blender keymaps on our to-do list, but we haven't yet started on this.  maybe it's time to revisit this?

Note: The `Z` key is currently mapped to Relax quick shortcut (by default, holding `Z` then pressing left mouse button relaxes the target), and the quick shortcuts are handled before undo/redo, hence the breaking of undo.  There is a way to distinguish between _holding_ the `Z` key and _pressing_, so it is possible to make this work for your custom set up, but making the change in code would require nearly implementing the custom keymaps.

note: A more general (if not still really a prototype) keymap customizer would better handle other custom setups as well as non-US keyboard layouts, and it might help get a solution to this issue faster than tweaking the quick shortcuts.

If you feeling comfortable in a custom quick fix, you can modify the RF keymap file to switch the Relax quick shortcut to something that works with your setup.  to do that:

- browse to your addons folder, where addons are installed
- open `RetopoFlow/config/keymaps.py` file in a text editor (not MS Word, but Notepad or in Blender's built-in text editor)
- look for the line: `'relax quick': {'Z'},` and change the `Z` to something else (maybe `S`)?
- save
- restart Blender

**Comment by basillicus** [comment]
Hi @vxlcoder, 

Sorry, I might have not explained the issue correctly. The problem is that undo does not work in RetopoFlow  if blender undo is remapped to something different to Ctrl-Z.  For the UNDO to work in RetopoFlow, Blender has to have 'undo' mapped to Ctrl-Z (default) 

I was not trying to remap anything within RetopoFlow, but now I know where to touch, I might :)

**Comment by vxlcoder** [comment]
Sorry I didn't communicate correctly.  Yes, I understood your initial issue :)

RF looks at Blender's keymap for a few items (undo, redo, left/right mouse select, etc.), so when you map `Z` to undo in Blender, RF also maps `Z` to undo.  The problem is that Relax's quick shortcut is also `Z`, and RF checks the quick shortcuts before handling undo.  This means that the `Z` action is "caught" by Relax, so it never gets to Undo.

Most of my comments were technical notes to myself, helping me think through the problem (again, sorry for my poor communication!)

If I get some time this evening, I'll see if I can get a _very_ crude way to access this pushed into a commit.  I'll update with details as soon as I can.

**Comment by basillicus** [comment]
Thanks for your quick response! 

> RF looks at Blender's keymap for a few items (undo, redo, left/right mouse select, etc.)

That is what I thought i might be happening. 

I tried your suggestion of editing the quick short cut for 'realax quick' in `keymaps.py` file and then undo works indeed. 

Thanks! Now I know how to configure it.
