### ISSUE TITLE
[BUG] Custom button viewport navigation not working

### ISSUE THREAD

**Issue by Dprasni** [CGCookie/retopoflow#975]
Issue Template
-----------------------------------
Retopoflow Version: 3.1

Blender Version/Hash: 2.92 Release

Platform Version/Distribution: Microsoft store

&nbsp;

**Issue:**

Using custom controls/key input for the navigation in the viewport wont work in the Retopoflow mode,

I have replaced the normal navigation shortcuts to my custom ones which are, RMB hold for rotation, MMB is for panning, double RMB is to cancel operation, and RMB click is for menu call. (i did it cause the normal navigation buttons for blender are very exhausting/fatiguing since i rotate my camera a lot, RMB is much easier to use for that purpose)

I will attach my key settings for testing purposes,
Small note, the Default blender key map and the industry standard work fine.

{*add any screenshots of the issue here*}

&nbsp;

**How to Reproduce:**

- Use my key map setup or change it yourself to how i set it up

[RMB Orbit DP 2.zip](https://github.com/CGCookie/retopoflow/files/6107979/RMB.Orbit.DP.2.zip)

**Comment by vxlcoder** [comment]
Thanks for the report @Dprasni!

RetopoFlow does have issues with some keyboard+mouse mappings, and this looks like another mapping that causes problems.

We are working on a custom mapping system right now.  I'll take a look to make sure that RMB-for-rotation works.

**Comment by vxlcoder** [comment]
@Dprasni, I just tried the latest RetopoFlow with your Blender keymappings (RMB: rotate view, MMB: pan view) and it works fine for me.

Note: I was not able to get Blender to open a context menu on RMB+Click.

Also, RMB+Double to cancel an action does not work in RetopoFlow, as the RMB to rotate view takes precedence, so RMB+Double event never makes it to the cancel code.  alternatively, you can still use ESC to cancel or create a new keymap binding using the new RetopoFlow Keymap Editor (in next release!).

closing this issue, but feel free to open it back up if you continue to have issues!

happy retopo'ing!
