### ISSUE TITLE
retopoFlow 3 - freezes or hangs up

### ISSUE THREAD

**Issue by duzerkitz** [CGCookie/retopoflow#976]
**FREEZES** **FIX** **IS THIS ISSUE MAC RELATED?**

Retopoflow Version: 3

Blender Version/Hash: 2.92

Platform Version/Distribution: iMac Pro 2017, OS 11.2.3, 64GB memory, Radeon Pro Vega 64 16GB

Issue: lag/freezing/slow

<img width="1330" alt="Screen Shot 2021-03-18 at 8 02 36 AM" src="https://user-images.githubusercontent.com/80906917/111648205-5be2e880-87c0-11eb-9501-3513facf4c70.png">

**How to Reproduce: Start the add on**

- {*Simple rotation around the object*}

Hello, I think the form entries above say it all. Why is this add-on so slow? My target mesh is only 40k and even when rotating around this head RT3 is freezing half of the time. Unusable. I am using an iMac Pro and I am using Keymap 'Industry Compatible'. Are these contributing factors to this problem? Thank you

**Comment by vxlcoder** [comment]
Thanks for the report, @duzerkitz.  Here are a few questions:

Are you using the latest official release of RF, v3.1.0?

What is the poly count of the source mesh?

Are you using symmetry?

Can you share the .blend file with us?  You can email a link to retopoflow@cgcookie.com

**Comment by duzerkitz** [comment]
I am using RF, v3.1.0.
Polycount of the source mesh is 40k (in my image the one on the screen right).
For more context: I am a character modeler. I am learning Blender this week and I just bought RT3.1, I am testing. My screen shot is of a character I have made in the past. In ZBrush I divided it so that it has 40k and I set it as what I want to draw topology on. I then imported my original mesh of 8k faces to lay over the top and told RT that I want to use this topology and edit it (my screenshot screen left). So the total polycount in the scene is roughly 48k which should be easy. As I said my viewport keeps freezing. I just now got rid of the 8k mesh to see if starting clean would improve things. It did. I no longer have lag. Am I to expect lag as I increase the topology over my character - for instance 8k will be unusable, 5k difficult, 2k maximum topology to remain workable? Thank you.

**Comment by vxlcoder** [comment]
Hmmm.  Thanks for the details!

There will be _some_ lag as your target gets "larger", but the lag should not interfere with your workflow.

We are actively working on improving the speed of RF with high poly counts, but we have tested RF on source meshes with 100k faces and targets 10--20k range, and RF was still usable on modest hardware.

Do you notice the lag with each of the RF tools or just some?  (even as you rotate the model, each tool does some calculations to figure out how you might want to edit the target)  If you notice the lag for particular tools, maybe I can focus some attention on that tool.

**Comment by duzerkitz** [comment]
I am emailed you my blender file.

**Comment by duzerkitz** [comment]
@vxlcoder sorry for not answering the question. The lag is on every tool in my scene (with the two heads, 40k and 8k).

**Comment by jlampel** [comment]
The upcoming release (RF 3.4) has some big performance improvements, but either way, performance is a known issue and something we will continue to work on.
