### ISSUE TITLE
Retopoflow not working in Blender 2.9

### ISSUE THREAD

**Issue by MuppetMoff** [CGCookie/retopoflow#977]
I just purchased Retopoflow 3 and I can't use it. In the add-ons section when I try to turn it on, I get a "upgrade to 2.8x required" message. How do I resolve this?

**Comment by vxlcoder** [comment]
sorry for the issues you're having.

can you post a screenshot of what you're seeing?

**Comment by MuppetMoff** [comment]
No problem. Yeah this is what I'm seeing.
![image](https://user-images.githubusercontent.com/80925805/111702892-ecdeb180-880a-11eb-8034-35d9cdcb3408.png)

**Comment by vxlcoder** [comment]
thanks!

it looks like you installed RetopoFlow 2.0. Instead, grab and install version 3.1. that should fix you're problem!

**Comment by MuppetMoff** [comment]
seems straightforward enough but I never got an option for versions. I just went here, paid the 86 bucks and it gave me 2.0 for some reason. How do I get 3.1?
https://blendermarket.com/products/retopoflow

**Comment by vxlcoder** [comment]
hmm, I will let @jlampel take that. you should have access to both versions through BM

**Comment by MuppetMoff** [comment]
Ok thanks. A direct link would be awesome

**Comment by jlampel** [comment]
Ok, I double checked and both versions are available on the Blender Market: 
![image](https://user-images.githubusercontent.com/12982300/111704441-5c997000-87fc-11eb-81d9-e7a3b393ab1c.png)

Try heading to your orders page and downloading there: https://blendermarket.com/account/orders 

If you don't see it on your orders page, please screenshot and let me know!

**Comment by MuppetMoff** [comment]
I was never prompted to make an account when I purchased so I have no way to get back to the orders page.

**Comment by jlampel** [comment]
Oh that's interesting. So the email receipt doesn't contain both download links? Well, either way, if you make an account with the same email you purchased it with you can email support@blendermarket.com and Matthew can link the purchase to your new account.

**Comment by MuppetMoff** [comment]
Oh sorry, I thought I used a different email for purchase. Yes, I have the link, thank you

**Comment by MuppetMoff** [comment]
Plugin works great, thanks!

**Comment by jlampel** [comment]
Perfect! I'll close this out then. Happy retopo-ing :)
