### ISSUE TITLE
**[PROPOSAL]** Target Cleaning : Please don't affect hidden meshes

### ISSUE THREAD

**Issue by nyaarium** [CGCookie/retopoflow#978]
Retopoflow Version: 3.1.0

Blender Version/Hash: 2.90.0

Platform Version/Distribution: Windows

&nbsp;

**Issue:**

For an insanely high poly sculpt, I cut it & tried to do retopo on "parts" of the body at a time. I hid retopo polys I was done with (the H key) before entering Retopoflow, and used "Target Cleaning > Snap Verticies". As it turns out, it affects hidden geometry as well.

R.I.P. hours of work.

You would think it wont affect hidden geometry since geometry it is also hidden in Retopoflow.

**How to Reproduce:**

1. Make a simple sculpt (or cylinder or anything).
2. Begin retopoflow & make some strips.
3. Exit retopflow.
4. Delete parts of the sculpt.
5. Hide retopoflow-made polys anywhere you deleted the sculpt at (H key).
6. Enter retopoflow & hit **Target Cleaning** > **Snap Verticies All**
7. Exit retopoflow & unhide everything. Your hidden meshes should now be thoroughly squashed.

**Comment by vxlcoder** [comment]
thanks for the report!

I will get this taken care of as soon as possible. (thought I already did, actually, but it seems otherwise)

**Comment by RandomClown0** [comment]
Loving Retopoflow a whole lot btw. Thanks for all your hard work!

**Comment by vxlcoder** [comment]
now, there are several buttons for snapping, hopefully making it clearer which verts will be modified.

I'm very sorry that the previous button lost you so much work!

please let us if there is anything else that we can help with.

happy retopo'ing!
