### ISSUE TITLE
**[BUG]**  Relax brush makes the mesh explode

### ISSUE THREAD

**Issue by ashercypress** [CGCookie/retopoflow#981]
Retopoflow Version: 3.1.0

Blender Version/Hash: 2.92.0

&nbsp;

**Issue:**

When using the relax brush on some sections, the mesh will explode, however, this only happens in certain areas, whereas some others will relax normally

![bug](https://user-images.githubusercontent.com/65720531/112212150-40257b00-8be2-11eb-902e-f98a398933a0.gif)

Have already tried:

Applying all transforms
Making both mesh and target bigger and applying all transforms
Unify normals (Shift + N)
Using tweak to move the vertexes further away from each other before trying to use relax

**Comment by vxlcoder** [comment]
thanks for the report, @ashercypress.

I'm not sure what exactly is causing this.

is there any chance you might be able to share the .blend file with retopoflow@cgcookie.com?

**Comment by vxlcoder** [comment]
looking more into this, it seems that the relax tool does not behave well when there is exactly one vertex inside the brush.  commit dd70258 prevents relax from moving any vertices unless there are at least 2 vertices within the brush radius (a low threshold, but one that appears to fix the original issue as presented).
