### ISSUE TITLE
Retop Flow welcome Page is impossible to exit

### ISSUE THREAD

**Issue by GianniRoden49** [CGCookie/retopoflow#982]
Hi,
i us mac Os  Catalina 10.15.7.   Blender 2.91.2 

I uploaded a file of 150000 poly.
When i active the Retopo Flow addon  opens the welcome page.
Here is the problem. I can't get back into blender.  It is impossible to close and exit the welcome page.
Thank you for quick help

Gianni
 
<img width="2988" alt="Screenshot 2021-03-24 at 10 39 03" src="https://user-images.githubusercontent.com/81296178/112288084-4ae91a00-8c8d-11eb-94f8-7ac9eea8b6d4.png">

**Comment by vxlcoder** [comment]
thanks for the report, @GianniRoden49.

I'm sorry for your troubles.

RetopoFlow is designed to work with only one 3d view. you appear to have quad view turned on, which is causing RetopoFlow to appear multiple times, but only actually run in one.

you _should_ be able to quit RetopoFlow by pressing escape when your mouse is hovering the "correct" 3d view (whichever RetopoFlow thinks it is running in).

for the time being, you will need to make sure you're not using quad view and only have a single 3d view open to run RetopoFlow correctly.

I will work on a better solution or add a warning soon.
