### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Evanesme** [CGCookie/retopoflow#983]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.0.1
- Blender: 2.91.2 master 2021-01-19
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1050 Ti/PCIe/SSE2, 4.5.0 NVIDIA 461.40, 4.50 NVIDIA
- Timestamp: 2021-03-25 01:17:14.699233
- Undo: insert, select, insert, select, insert, select, move after select, grab, select, insert

Error Hash: 2a1de537f6e24d10f04e9a321bd0667e

Trace:

- EXCEPTION (<class 'ValueError'>): edges.new(): this edge exists
-     C:\Users\ola99\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rfmesh\rfmesh.py
- 000 1523:new_edge() bme = self.bme.edges.new(verts)
-     C:\Users\ola99\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rf\rf_target.py
- 001 0470:new_edge() return self.rftarget.new_edge(verts)
-     C:\Users\ola99\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 002 0563:_insert() e1 = self.rfcontext.new_edge([bmv2, bmv3])
-     C:\Users\ola99\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool.py
- 003 0141:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\ola99\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\retopoflow-master\retopoflow\rftool_polypen\polypen.py
- 004 0365:insert() return self._insert()
-     .../common\fsm.py
- 005 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Evanesme, and sorry for the very late response!

I believe this issue has been fixed in version 3.1.0.  please update to the latest version of RetopoFlow, and let us know if you continue to have issues.

thanks!
