### ISSUE TITLE
Tweak and Relax: Brush size does not always confirm with left click

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#984]
A user mentioned that the Tweak and Relax tools have a bug where left clicking does not always confirm the size after adjusting with F. I was able to replicate this with both left and right click select. After pushing some vertices around, I would hit F and change the size, then push more vertices around. Most of the time it worked, but occasionally it would get stuck and I would need to left click multiple times in order for it to confirm. 

I found that it happens most when you click while you are dragging rather than keeping your mouse still while confirming.

**Comment by vxlcoder** [comment]
this should now be working as expected

**Comment by jlampel** [comment]
This works great!
