### ISSUE TITLE
Critical conflicts with SculptLayers addon.

### ISSUE THREAD

**Issue by mifth** [CGCookie/retopoflow#985]
Hi, I've got a report on my addon's space. But it could be on your side.
https://blenderartists.org/t/sculpt-layers-addon/1288145/114?u=mifth

![image](https://user-images.githubusercontent.com/2251298/113411710-30b2e880-93bf-11eb-87ef-52403e94bd43.png)

**Comment by vxlcoder** [comment]
thanks for the report, @mifth, and sorry for the slow response.

do you have any more details on what isn't working?

**Comment by mifth** [comment]
No worries. I have only this information 
https://blenderartists.org/t/sculpt-layers-addon/1288145/132?u=mifth

**Comment by jlampel** [comment]
I don't know if this was ever resolved, but both addons have been updated quite a bit since then. If this continues to be a common issue, please let us know.
