### ISSUE TITLE
PolyPen: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Andytzzu** [CGCookie/retopoflow#986]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- CG Cookie built
- Blender: 2.90.1 master 2020-09-23
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
- GPU: NVIDIA Corporation, GeForce GTX 1650/PCIe/SSE2, 4.5.0 NVIDIA 461.92, 4.50 NVIDIA
- Timestamp: 2021-04-02 13:07:58.970788
- Undo: relax, relax, relax, select smart, select smart, select smart, select smart, select, select, select smart

Error Hash: dd0015a29a296e85796b78670a42cf0a

Trace:

- EXCEPTION (<class 'NameError'>): name 'self' is not defined
-     <string>
- 000 0039:update_hide_overlays() 
- 001 0001:<module>() 
-     .../common\utils.py
- 002 0181:run_it() return exec(action, f_globals, nf_locals)
- 003 0186:run_it() raise e
-     .../common\ui_core.py
- 004 2033:_fire_event() cb(details)
- 005 2039:_fire_event() raise e
- 006 2070:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_properties.py
- 007 1037:_checked_change() self.dispatch_event('on_input')
-     .../common\boundvar.py
- 008 0069:_call_callbacks() for cb in self._callbacks: cb()
- 009 0096:set_value() self._call_callbacks()
- 010 0101:value() def value(self, value): self.set_value(value)
-     .../common\ui_properties.py
- 011 1027:checked() self._checked.value = v
-     <string>
- 012 0001:<module>() 
-     .../common\utils.py
- 013 0181:run_it() return exec(action, f_globals, nf_locals)
- 014 0186:run_it() raise e
-     .../common\ui_core.py
- 015 2033:_fire_event() cb(details)
- 016 2039:_fire_event() raise e
- 017 2070:dispatch_event() self._fire_event(event, ui_event)
-     .../common\ui_document.py
- 018 0570:mousedown_exit() under_mouseclick.dispatch_event('on_mouseclick')
-     .../common\fsm.py
- 019 0054:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Andytzzu, and sorry for the slow response!

have you ran into this problem again?  do you happen to recall how to reproduce this bug?  I'm having troubles recreating it.
