### ISSUE TITLE
**[BUG]** Overlapping text and links in the online documenation

### ISSUE THREAD

**Issue by git-yulia** [CGCookie/retopoflow#988]
Sorry if this isn't the right place to submit this, but I didn't see a separate Issues page for the online documentation. 

**Issue:**

It's difficult to navigate the [online documentation](http://docs.retopoflow.com/welcome.html) in Firefox because the text and links overlap. 

Screenshot from Firefox: 
![image](https://user-images.githubusercontent.com/15273645/114464953-5304ed00-9b9b-11eb-9d91-7a4d8499044c.png)

Screenshot from Chrome (looks fine):
![image](https://user-images.githubusercontent.com/15273645/114465007-61eb9f80-9b9b-11eb-9291-787f5ac6de4d.png)

**Comment by vxlcoder** [comment]
thanks for the report! will get this fixed as soon as we can.

**Comment by vxlcoder** [comment]
thanks for the report, @git-yulia!

this issue is fixed now, and will be released soon.
