### ISSUE TITLE
Polystrips does not work on objects with modifiers

### ISSUE THREAD

**Issue by carter2422** [CGCookie/retopoflow#99]
As reported by several users [here](http://cgcookiemarkets.com/blender/forums/topic/polystrip-error-retopoflow-1-0-0-beta/) it seems Polystrips fails on objects that have modifiers.

I know we did some work with this before, but we need to revisit it. Ideally we should allow modifiers but if we can't then we at least need to present a nice error message to the user rather than crashing.

**Comment by mifth** [comment]
My tools use standart blender's picking. They work witth modifiers ok.
You can check my DrawClones tool.

I just take obj and its matrix. Nothing special.
https://github.com/mifth/mifthtools/blob/237aceb838e6842bbd0ea0b89036b6783c702bb8/blender/addons/mifth_tools/mifth_tools_cloning.py#L341

i can guess this is your custom picking issue.

**Comment by carter2422** [comment]
I still cannot repo this. I suspect it's less of an issue with modifiers and more of an issue with empty mesh data.

Closing.
