### ISSUE TITLE
Strokes: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by Plexzerion** [CGCookie/retopoflow#992]
![RetopoFlow_screenshot](https://user-images.githubusercontent.com/83886559/117553850-d6422300-b021-11eb-9dc9-3218837982f6.png)
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- CG Cookie built
- Blender: 2.83.5 master 2020-08-19
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce GTX 970/PCIe/SSE2, 4.5.0 NVIDIA 466.27, 4.50 NVIDIA
- Timestamp: 2021-05-08 17:10:42.372323
- Undo: extrude strip, extrude L, move grabbed, select, move grabbed, select, select, extrude strip, move grabbed, move grabbed

Error Hash: 8a38ee9689a556038ea48455153016b8

Trace:

- EXCEPTION (<class 'AttributeError'>): 'tuple' object has no attribute 'reverse'
-     C:\Users\starf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 000 0834:extrude_strip() if side_verts[1] == verts[-1]: side_verts.reverse()
-     C:\Users\starf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\starf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rftool_strokes\strokes.py
- 002 0371:stroke() if self.replay: self.replay()
-     C:\Users\starf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfwidget.py
- 003 0108:_callback_tool() fn(self.rftool, *args, **kwargs)
- 004 0128:callback_actions() self._callback_tool('action', *args, **kwargs)
-     C:\Users\starf\AppData\Roaming\Blender Foundation\Blender\2.83\scripts\addons\RetopoFlow\retopoflow\rfwidgets\rfwidget_brushstroke.py
- 005 0087:modal_line() self.callback_actions()
-     .../common\fsm.py
- 006 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @Plexzerion.

This issue is the same as #958, which has been fixed (still to be released).

You can update to the commit that fixed this bug (see my replies on that issue), or you can try out the current latest by using the RetopoFlow system updater to update to the `v3.1.1` branch (use `v3.1.1` instead of `2eb10aa`).

We are hoping to release the next version of RF very soon.

closing this issue for now, but please reopen if you continue to have problems.  thank you!
