### ISSUE TITLE
Knife: Unhandled Exception Caught: Exception caught

### ISSUE THREAD

**Issue by masterbleu** [CGCookie/retopoflow#993]
**PLEASE READ THE FOLLOWING AND USE THE TEMPLATE TO POST YOUR ISSUE**

*Questions not directly related to the RetopoFlow project are considered general and should be posted elsewhere (e.g. git, blender, python, etc).*

**Before raising the issue, please check the following first:**

- [ ] Read through the README.md file in the branch used to assure the process taken is correct
- [ ] Check the existing [issues](https://github.com/CGCookie/retopoflow/issues) and [pull requests](https://github.com/CGCookie/retopoflow/pulls) to make sure the issue has not already been reported and/or fixed.
- [ ] You can replicate the bug and will provide as much info as possible with blend files, screenshots, logfiles, as well as show the expected result and actual result.

Please prefix your issue name with one of the following: **[BUG]** **[PROPOSAL]** **[QUESTION]**

Issue Template
-----------------------------------

**Issue:**

{*enter your issue here*}

{*add any screenshots of the issue here*}

**How to Reproduce:**

- {*add your list replication steps*}

{*attach any files needed to replicate the issue*}

Automatically Generated Info
-----------------------------------

```
Environment:

- RetopoFlow: 3.1.0
- CG Cookie built
- Blender: 2.91.0 master 2020-11-25
- Platform: Windows, 10, 10.0.19041, AMD64, Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
- GPU: NVIDIA Corporation, NVIDIA GeForce RTX 2060 SUPER/PCIe/SSE2, 4.5.0 NVIDIA 466.27, 4.50 NVIDIA
- Timestamp: 2021-05-09 13:03:14.711159
- Undo: insert, select, insert, insert, select, insert, insert, select, insert, insert

Error Hash: 7c2fb84cb160500215270d55c6afbd45

Trace:

- EXCEPTION (<class 'AttributeError'>): 'NoneType' object has no attribute 'shatter'
-     C:\Users\Mainframe12\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 000 0413:_insert() bmf.shatter()
-     C:\Users\Mainframe12\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool.py
- 001 0158:wrapper() ret = fn(*args, **kwargs)
-     C:\Users\Mainframe12\AppData\Roaming\Blender Foundation\Blender\2.91\scripts\addons\RetopoFlow\retopoflow\rftool_knife\knife.py
- 002 0246:insert() return self._insert()
-     .../common\fsm.py
- 003 0058:run() return fn(*args, **kwargs)
```

**Comment by vxlcoder** [comment]
thanks for the report, @masterbleu!

commit 4ac1717 should fix this bug.
