### ISSUE TITLE
PROPOSAL - Collapse Edges and Faces

### ISSUE THREAD

**Issue by jlampel** [CGCookie/retopoflow#998]
A user mentioned that it would be helpful to have the Collapse Edges and Faces from Blender's Delete menu in the RetopoFlow delete menu, and I agree that it would be useful.

**Comment by vxlcoder** [comment]
we can definitely add this.

note: this is not a bmesh operation, so I will have to write from scratch.  this is not a big deal, but it does take some time to understand how this works.  below is my attempt to understand it (the [docs](https://docs.blender.org/api/current/bpy.ops.mesh.html#bpy.ops.mesh.edge_collapse) are not super clear)

it looks to me that this operation does this:

- separate selection into connected components/regions
- then, for each component
    - find average vertex position of all selected verts (in component)
    - merge all selected verts into a single point located at that average
        - edges between selected verts and faces composed entirely of selected verts are collapsed (essentially deleted)
        - edge with exactly one unselected vert will now be between unselected vert and the newly created merged vert
        - face with at least two unselected vert will now be between all unselected vert and the newly created merged vert
        - face with exactly one unselected vert will collapse to an edge between that unselected vert and the newly created merged vert

does this look correct?

in RF, should that newly created merged vert get snapped to nearest position on source mesh or should it be projected to the source mesh from the camera's POV (with fallback of snapping if no source mesh exists under average position)?  most cases, the difference between these won't make that much of a difference.  snapping is the probably the simplest.

**Comment by jlampel** [comment]
That sounds exactly correct! I think the nearest position snapping would make the most sense because in some cases I would do it for parts of loops that wrap around the mesh like so:

![5vLtuZAVET](https://user-images.githubusercontent.com/12982300/121945619-d1e7e480-cd08-11eb-86cd-674d8e57a501.gif)

**Comment by vxlcoder** [comment]
commit 788f4cc has a collapse edges & faces option added to delete/dissolve/collapse menu (`X`).  i haven't tested it on a lot of different meshes, but it _seems_ to be working.  @jlampel, would you mind beating on it a bit?

**Comment by jlampel** [comment]
Wow, that was fast! I've tried it on just about every scenario I can think of including boundary edges, sets of edges all around the model, sets of faces, triangles, n-gons, sets of vertices (correctly does nothing), and more. It seems to behave just like Blender's in all situations. I'll keep trying it before release but it looks really solid to me.

**Comment by jlampel** [comment]
I've continued to try this out and so far have not found any problems. Works exactly as expected.
